INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1839, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1839, 'pseudoephedrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29692, 'dimethyl ether', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29692, 'ethyl acetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29692, 'acrylates copolymer', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17970, 'english ivy ( leaf)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17970, 'licorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17970, 'thyme (leaf)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23953, 'pilocarpine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3767, 'divalproex sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32943, 'liposomal iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32943, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32943, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32943, 'vit b', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15449, 'bosentan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15180, 'multivitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15180, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27273, 'acetylcysteine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15068, 'blood-coagulation factor ix', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23546, 'omeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23546, 'sodium bicarbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'omega3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'vit a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'vit e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'vit d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'iodine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3124, 'honey', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16349, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28274, 'dydrogesterone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19716, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28197, 'vitamin d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4107, 'tribulus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4107, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4107, 'maca root extraxt', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4107, 'ginkgo', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4107, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31839, 'rosuvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20988, 'isoniazid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'iron (ferrous bisglycinate) 35 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'vitamin b1 4.5 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'vitamin b2 3.75 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'vitami b3 5 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'vitamin b6 3.42 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'vitamin b12 1000 mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'copper 1000 mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'folate 1000 mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1468, 'vitamin c 75 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18884, 'citric acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18884, 'sodium bicarbonte', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18884, 'tartaric acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24936, 'balsam peru', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24936, 'bismuth subgallate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24936, 'dexapanthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24936, 'hamamelis extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24936, 'lidocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24936, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1622, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1622, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19531, 'gabapentin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12702, 'azithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'avocado', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'rose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'guar', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'azelaic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'tea tree', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'vit e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'glycerine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'ascorbic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'urea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4216, 'sulfur.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19144, 'fluticasone propionate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27216, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27216, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27216, 'whey protein', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18798, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27780, 'lactose free milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18812, 'piperazine theophylline ethanoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27868, 'zinc pyrithione', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27868, 'simethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27868, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27868, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27868, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27868, 'menthol crystals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25480, 'budesonide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (994, 'celecoxib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17893, 'sucralose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17893, 'lactose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17893, 'croscarmellose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10826, 'd-alpha tocopherol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17998, 'carbamide peroxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5699, 'cabergoline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28998, 'horse-chestnut', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28998, 'centella', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28998, 'calendula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28998, 'ginger', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28998, 'grape seed', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28998, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26695, 'tolterodine l tartarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15781, 'capecitabine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20586, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16004, 'cefaclor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, '32 active ingredients panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'argan oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'keratin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'saw palmetto extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'hydrolyzed wheat protein', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'amla oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'shea butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'rosemary extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'emu oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27919, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32468, 'azathioprine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'saw palmetto extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'ginkgo', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'rosemary', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'lavender oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25383, 'vitamin c&e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6666, 'cefotaxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29579, 'diclofenac sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29579, 'lidocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4689, 'meropenem', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4125, 'cyclizine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4125, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19980, 'glycine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30973, 'brexpiprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2149, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2149, 'menthol crystals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2149, 'clove extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2149, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30034, 'acyclovir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29775, 'cefotaxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19954, 'pioglitazone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27864, 'omega-3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27864, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4154, 'amoxicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4154, 'clavulanic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19079, 'metronidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4816, 'iron proteinsuccinylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24993, 'hydrolyzed whey protein isolate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24993, 'micronized branched chain amino acids(l-leucine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24993, 'l-isoleucine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24993, 'l-valine)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'alpha lipoic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'vitamin b2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33244, 'folate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33685, 'licorice extract (glabridin)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33685, 'kojic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33685, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33685, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24927, 'vitamin k1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (515, 'secnidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25393, 'saw palmetto ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25393, 'nettle powder ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2063, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2063, 'vit a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2063, 'vit e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2063, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2063, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2063, 'vit d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31151, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31151, 'methyl salicylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31151, 'camphor oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31151, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31151, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31151, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4673, 'cholecalciferol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22122, 'lubiprostone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24382, 'oxaliplatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24845, 'brimonidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24845, 'timolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23773, 'ampicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23773, 'sulbactam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27448, 'azilsartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13021, 'rabeprazole sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21833, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32289, 'dapagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32289, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9268, 'cefepime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3559, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3559, 'propolis', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3559, 'calcium carbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3559, 'sodium bicarbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25633, 'ramipril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30370, 'cholecalciferol(vitamin d3)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5586, 'pregabalin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27285, 'citicholine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4287, 'adenosine triphosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4287, 'cocarboxylase', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4287, 'nicotinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4287, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7163, 'collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7163, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7163, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26761, 'fish oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26761, 'marigold', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26761, 'cholecalciferol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23536, 'amoxicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23536, 'clavulanic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13888, 'amantadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'chondroitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'msm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'gotu kola', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'ginkgo', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8259, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32786, 'fexofenadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25271, 'chlorpheniramine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25271, 'naphazoline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25271, 'zinc sulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8376, 'ivy leaf extract (35 mg)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8376, 'thyme leaf extract (21.5 mg)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8376, 'licorice root extract (21.7 mg)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8376, '5 ml', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14598, 'fenoterol hydrobromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14598, 'ipratropium bromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'multivitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'manganese', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'chromium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'iodine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'potassium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'chlorid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'phosphporous', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11570, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31554, 'pentoxifylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14071, 'theophylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24274, 'phmb', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24274, 'poloxamer', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24274, 'isotonic buffered solution', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'ascorbic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'boron aac', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'calcium carbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'cholecalciferol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'horsetail extax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'ipriflavone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'lysine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28679, 'magnesi', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26260, 'vardenafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30597, 'empagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3924, 'mebeverine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'green tea extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'retinyl palmitate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13357, 'ascorbic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20922, 'ceftazidime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5712, 'vitamin a-d3-b1-b2-b6-c-e-nicotinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5686, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5686, 'chondroitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5686, 'msm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5686, 'ginko', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12571, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12571, 'metoclopramide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12571, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22430, 'meclizine hydrochloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24704, 'miconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15595, 'tretinoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25362, 'dinoprostone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15676, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31351, 'silver sulfadiazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3889, 'finerenone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24887, 'fluoxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24528, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20148, 'haemodialysis solution', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21365, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'calcium 400mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'vitamin d3 500 iu', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'manganese 250mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'zinc 5mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'copper sulfate 0.63mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'magnesium 150mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33614, 'selenium 27.5mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14281, 'apixaban', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24250, 'collagen peptides marine source 9 gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24250, 'calcium citrate 1250 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24250, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16971, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16971, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16971, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2915, 'sodium cyclamate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2915, 'sodium saccharin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27102, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27102, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27102, 'cod liver oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27102, 'castor oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24374, 'oxaliplatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19595, 'trimebutine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3238, 'cynara dry extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3238, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3238, 'magnesium oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3238, 'silymarin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11770, 'tigecycline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23715, 'mometasone furoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6316, 'agar agar liquid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10642, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12056, 'valsartan-hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10438, 'ceftazidime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5351, 'omeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17723, 'prednisolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18805, 'doxazosin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15401, 'sun protection formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5463, 'multivitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5463, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18601, 'ethamsylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4455, 'paclitaxel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17551, 'dapagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17551, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33260, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33260, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6953, 'clarithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18413, 'diclofenac sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12050, 'cholecalciferol (vit. d3)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16864, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16864, 'perindopril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15640, 'leucovorin calcium=folinic acid=calcium folinate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21609, 'lansoprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13413, 'probiotic', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9060, 'insulin aspart', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16540, 'clobetasol propionate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3663, 'fluconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7775, 'whitening formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20572, 'sodium hyaluronate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'bees wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'shea butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'propolis ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'honey ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2878, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28092, 'eprosartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14736, 'strontium-89 chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15548, 'ibuprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15548, 'pseudoephedrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (750, 'vortioxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1831, 'pentoxyverine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11009, 'artichoke extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32819, 'pemetrexed', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17602, 'bacitracin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17602, 'neomycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11492, 'tolmetin sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18232, 'ondansetron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'centella asiatica extracts', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'niacinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'squalane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'adenosine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'd-panthenol vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5938, 'zinc oxide copper gluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22721, 'ethinyl estradiol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22721, 'levonorgestrel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26130, 'calcium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26130, 'potassium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26130, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26130, 'sodium lactate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'silicon dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'grapefruit extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'propolis extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16098, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5401, 'vonoprazan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32441, 'aripiprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'fennel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'guava', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'liquorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'majoram', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'peppermint', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'tilia', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31326, 'verbascum', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15300, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15300, 'royal jelly', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15300, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27620, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27620, 'ethanol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27620, 'propane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27620, 'butane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32878, 'fusidic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31629, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31629, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31629, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20807, 'ethylhexylmethoxy dibenzoylmethane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20807, 'ethylhexyl methoxy cinnamate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20807, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20807, 'benzophenone-3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20807, 'titanium di', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17700, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'capixyl', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'shea butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'tocopherol acetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'polyquaternium-7', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'saw palmetto', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'coconut oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30264, 'argan oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'bisabolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (415, 'paraffin oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'ferrous fumarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'vitamins(b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'b2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'd', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'e)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'linoleic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'linolenic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5828, 'manganese', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16455, 'cilostazol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15639, 'alendronate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15639, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19245, 'fluticasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19245, 'formoterol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5013, 'trypsin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5013, 'bromelain', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5013, 'rutin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29999, 'alprazolam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27801, 'budesonide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27801, 'formoterol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19894, 'khellin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19894, 'diprophylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19894, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19894, 'theophylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19969, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19969, 'ichtammol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21305, 'pregabalin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29155, 'sun protection formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29524, 'calcium pantothenate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29524, 'nicotinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29524, 'vitamin b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29524, 'vitamin b2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29524, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29524, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12885, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12885, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12885, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12885, 'citrillus colocynth', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30713, 'green tea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32296, 'primula root fluid extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32296, 'thyme fluid extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28697, 'amoxicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28697, 'clavulanic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27580, 'clopidogrel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17178, 'n-pentane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17178, 'iso-butane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17178, 'propane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17178, 'n-butane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17178, 'denatured ethanol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17178, 'levomenthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17697, 'l-alanyl-l-glutamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15900, 'l-carnitine l-tartrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15900, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20134, 'ferrous fumarate(iron)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20134, 'folic acid', 0);
