INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21145, 'glycerine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6854, 'levetiracetam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24098, 'somatropin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1925, 'ivy extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28396, 'trandolapril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24149, 'oxomemazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25854, 'infliximab', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14148, 'testosterone undecanoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26567, 'cetrimide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26567, 'chlorhexidine gluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32007, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32007, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32007, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5113, 'ceftazidime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4596, 'nabumetone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30363, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30363, 'vit b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9346, 'vitamin c 500 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9346, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31198, 'sevelamer', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1917, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1917, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1917, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1917, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4334, 'olmesratan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4334, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30102, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30102, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30102, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30102, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24144, 'montelukast', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'rosemary', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'fenugreek', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'wheat germ', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'amla', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'jojoba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'olive', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14199, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18591, 'ethinyl estradiol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18591, 'norgestimate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27482, 'montelukast', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25870, 'glycerol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25870, 'hpmc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25870, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25870, 'rosemary', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25870, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25870, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32223, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19847, 'empagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14900, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14900, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14900, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14900, 'glycerol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17146, 'raloxifene hydrochloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (458, 'hair tonic', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22513, 'memantine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24320, 'chondroitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24320, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26984, 'silver sulfadiazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13403, 'isotretinoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8158, 'midazolam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29192, 'abemaciclib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20037, 'ofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6394, 'alogliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6394, 'pioglitazone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28516, 'vaccine measles', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28516, 'mumps', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28516, 'rubella', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33570, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33570, 'arnica', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33570, 'campher', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33570, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33570, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22273, 'memantine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4886, 'ibuprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16008, 'cefepime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28481, 'ambroxol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28481, 'guaifenesin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28481, 'theophylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25465, 'risperidone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28635, 'kojic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28635, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28635, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28635, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28635, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28635, 'liquorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24159, 'vitamin d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22342, 'levobunolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (886, 'milk formula stage 2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19501, 'sodium fusidate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7519, 'vardenafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5794, 'calcium citrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5794, 'calcium carbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5794, 'magnesium citrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5794, 'magnesium oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5794, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5794, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23620, 'nitazoxanide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (354, 'coal tar', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (354, 'cade oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29631, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29631, 'iron(as ferrous biglycinate)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29631, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29631, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29631, 'vitamin b complex(b1-b6-b12)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17392, 'desloratadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'marine collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32963, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25259, 'metoclopramide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24460, 'paclitaxel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19822, 'gliclazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20935, 'ipratropium bromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20713, 'rabeprazole sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15328, 'bisacodyl', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22666, 'metolazone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27924, 'nilotinib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26296, 'isoflavonoids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27146, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27146, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'calendula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'vitamins (a-c-e)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'green tea extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'paraffin oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'stearic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'cetyl alcohol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22899, 'methy', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14805, 'rimexolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4247, 'tenoxicam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6649, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6649, 'vitamin k2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14818, 'azithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31926, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31926, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31926, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18684, 'torsemide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9738, 'cefotaxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27910, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27910, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27910, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27910, 'arrange oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27910, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27910, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22915, 'miconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27007, 'extra care milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4052, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4052, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23345, 'nefopam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22850, 'granisetron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2004, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2004, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2004, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2004, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17564, 'gliclazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21741, 'insulin detemir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15887, 'psyllium husk', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'kojic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'licorice ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'mulberry ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'avobenzone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'oxybenzone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'royal jelly ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'vit.(e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24014, 'a)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14112, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14112, 'perindopril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4468, 'glibenclamide(glyburide)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4468, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16559, 'betamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16559, 'clotrimazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31343, 'kamigen e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31343, 'kamigen k', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31343, 'hydrolyzed lupin protein', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31343, 'hordeum vulgare', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31343, 'urtica dioica germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31343, 'coffee arabica fruit ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15080, 'benzocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29234, 'terconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20248, 'halothane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29904, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29904, 'valsartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5456, 'chondroitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5456, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5456, 'methyl sulphonyl methane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21382, 'citicoline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23129, 'elastoregulator', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23129, 'lupeol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23129, 'sophora japonica', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23129, 'avocado peptides', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27598, 'sucralfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'avobenzone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'oxybenzone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'liquorice ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'green tea ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'mulberry ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'ginkgo biloba ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32473, 'lemon ex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26851, 'kamigen e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26851, 'kamigen k', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26851, 'hydrolyzed lupin protein', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26851, 'hordeum vulgare', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26851, 'urtica dioica germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26851, 'coffee arabica fruit ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28478, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28478, 'olmesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28478, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27173, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (119, 'risedronate sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9011, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9011, 'pseudoephedrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9011, 'triprolidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17340, 'hydrocortisone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17340, 'nystatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17340, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27241, 'extract free from calves blood', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7488, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7488, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7488, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7488, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26559, 'atorvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11759, 'dextromethorphan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3708, 'isosorbide dinitrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27531, 'esomeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26399, 'gelatin (collagen) hydrolysate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26399, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26399, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24348, 'cinchocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24348, 'dexamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24348, 'framycetin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24348, 'gramicidin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20944, 'irbesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17473, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32561, 'alpha lipoic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32561, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32561, 'benfotiamin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32561, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32561, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26734, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26734, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26734, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26734, 'methyl paraben', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26734, 'propyl paraben', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26734, 'castor oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20880, 'paclitaxel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26504, 'saponin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26504, 'thymus vulgaris', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22405, 'cefpodoxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (209, 'valsartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33232, 'winter green oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33232, 'mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33232, 'bosouilla extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33232, 'mental', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33232, 'eculaptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'argan oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'keratin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'nigella sativa', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14947, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33175, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3507, 'hydrocortisone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3507, 'miconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31255, 'carbamide(urea)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25555, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5227, 'dapsone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9664, 'pancuronium bromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21325, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21325, 'menthol crystals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21325, 'chlorhexidine digluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21325, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (705, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (705, 'vitamin b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (705, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (705, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28466, 'chlorpheniramine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28466, 'dextromethorphan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28466, 'pseudoephedrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28658, 'remifentanil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'vit d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'vit b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'boron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5709, 'manganese', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2589, 'myo inositol. d chiro inositol. melatonin. co q10 .alpha lipoic acid. acetylcysteine. vitamins. antioxidants', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3911, 'doxazosin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24412, 'oxytocin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2384, 'cefalexin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13648, 'green coffee ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13648, 'garcinia cambogia', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13648, 'green tea ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13648, 'ashwaganda', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20575, 'silver sulfadiazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20575, 'sodium hyaluronate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17062, 'ibuprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26527, 'dill oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26527, 'sodium bicarbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32692, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32692, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32692, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'kojic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'sulfur', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'tocopheryl acetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'honey', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'allantion', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'vitamin a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'calendula extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'propolis extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7046, 'liquorice extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15793, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15793, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15793, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12025, 'clindamycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20288, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20288, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20288, 'methyl salicylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20288, 'terpentine oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31534, 'colchicine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31534, 'piperazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23421, 'diflucortolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23208, 'nabumetone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2335, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2335, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16155, 'piracetam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30068, 'linezolid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12640, 'ceftriaxone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5578, 'pefloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27113, 'pregabalin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2636, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2636, 'metronidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19829, 'omega oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19829, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15766, 'clotrimazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3601, 'acetazolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25347, 'colesevelam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14611, 'teriflunomide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14095, 'dipyrone(metamizole)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6484, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6484, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6484, 'liquorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6484, 'hydrolyzed collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6484, 'hydrolyzed elastine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6484, 'and ecoslim caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5626, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26673, 'amiodarone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31895, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31895, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13035, 'collegen hydrolysate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21476, 'mebeverine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24786, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24786, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24786, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24786, 'methyl salicylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24786, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29606, 'linezolid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25684, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2798, 'cefaclor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9369, 'rutosidetrihydrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9369, 'bromelain', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9369, 'trpsin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'vitamins(a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'd', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'k', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'c)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'chromium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30985, 'potassium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20960, 'irinotecan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23598, 'redensyl', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23598, 'capixyl', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23598, 'anagain', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23598, 'baicapil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23598, 'aminexil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23598, 'procapil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2466, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2185, 'cefdinir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20390, 'flaxseed oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20390, 'omega-3 fatty acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13695, 'calcium bisglycinate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13695, 'vitamin k2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13695, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28736, 'hypertonic seawater', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7728, 'nitroglycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29174, 'psyllium husk powder', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29174, 'chromium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26070, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26070, 'calendula extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26070, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26070, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9211, 'omega-3 fish oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3008, 'lamotrigine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23091, 'erdosteine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7711, 'tocopherol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7711, 'octocrylene', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7711, 'benzophenone-3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7711, 'drometrizole trisiloxane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7711, 'peg-8 laurate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33491, 'ferrous bisglycinate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33491, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33491, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33491, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33491, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25847, 'fluticasone furoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25847, 'vilanterol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12936, 'acyclovir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25628, 'fluoxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25628, 'olanzapine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15089, 'blood-coagulation factor viii', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2737, 'hydroquinone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23400, 'n acetyl cysteine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23400, 'ivy', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23400, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23400, 'propolis', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23400, 'msm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4684, 'metformin hydrochloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'whey proteinisolate 5gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'full cream milk powder 3 gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'cocoa powder 3gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'sucrose 1gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'lethicin 0.8 gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'dextrose 2 gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14476, 'dietary fibers 2gm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19759, 'ketoprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6031, 'essential phospholipids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6031, 'vitamins (b3-b1-b2-b6-b12-e)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33328, 'fish oil 400 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33328, 'flax seed oil 400 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33328, 'borage seed oil 400mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33328, 'vit e 30mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15989, 'cefotaxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'rutin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'elastin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'calndula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'vitamin (c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'e)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'centella extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29910, 'grape', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15061, 'bendamustine hydrochloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'jojoba extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'rosemary extraxt', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'alo vera extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13436, 'vit b3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31013, 'fructo-oligosaccharide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24779, 'econazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24779, 'triamcinolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28032, 'etilefrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22182, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2377, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2377, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2377, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2377, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2377, 'echinacea purpurea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17244, 'kojic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17244, 'licuorice extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17244, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17244, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17244, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13933, 'amino acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19410, 'fat', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19410, 'carbohydrates', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19410, 'protein', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25252, 'moexipril', 0);
