INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18508, 'cetuximab', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16412, 'cisplatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9444, 'diacerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2626, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5871, 'quetiapine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29061, 'carvedilol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17744, 'dobutamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31476, 'mentol oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31476, 'equlyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31476, 'camphor oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31476, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2540, 'lidocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2540, 'phenylephrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2540, 'thiomersal', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1720, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1720, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1720, 'chamomile extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1720, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1720, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1720, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29199, 'chitosan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29003, 'live attenuated varicella virus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (45, 'ibuprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (45, 'paracetamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4932, 'carbazochrom', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4932, 'troxerutin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (498, 'sorbitol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (498, 'sucralose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22218, 'magnesium citrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2868, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2868, 'valsartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29577, 'urea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2883, 'benztropine mesylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21717, 'levocetirizine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9392, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9392, 'ginko biloba leaf extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11664, 'glyceryl trinitrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26419, 'hypo-allergenic milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14385, 'l-arginine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25179, 'conjucated estrogen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'polysorbate 80', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'decyl glucoside', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'hexylene glycol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'triethanolamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'cocamidopropyl betaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'zinc gluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'citric acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13345, 'salicylic acid - capryloyl salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28100, 'dexamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28100, 'tobramycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3093, 'alpha lipoic acid 600mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3093, 'acetyl carnitine 300mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3093, 'vit b1 1.1mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3093, 'vit b5 6mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3093, 'pyridoxine hcl 1.7mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3093, 'methyl cobalamine 2.5 mcg.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (333, 'potassium bicarbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (333, 'sodium alginate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23316, 'vinorelbine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6136, 'palmitoylethanolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5411, 'gemifloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29504, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1961, 'luspatercept', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19564, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15306, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15306, 'mineral oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15306, 'lanolin anhydrous', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3502, 'clobetasol propionate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18201, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18201, 'mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18201, 'vitamin d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18201, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30523, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30523, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4297, 'cetirizine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27647, 'sumatriptan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'keratin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'hydrolyzed wheat protein', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'silicon', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'tocopherol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'cinnamon oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30753, 'triclosan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3245, 'cyclopentasiloxane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25543, 'quetiapine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17078, 'doxazosin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'nicotinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin b2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25056, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4041, 'piracetam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23950, 'sodium hyaluronate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20539, 'mesterolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17393, 'desloratadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17170, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18322, 'glipizide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18322, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21107, 'verapamil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8919, 'ketoconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26158, 'calcium carbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26158, 'risedronate sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11406, 'ornidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26372, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26372, 'royal jelly', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26372, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26372, 'bee pollen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26372, 'bee propolis', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18309, 'ambrisentan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6163, 'vit d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19957, 'glutamic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1393, 'benzyl alcohol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1393, 'benzyl benzoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31631, 'dapagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31631, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32458, 'lactoferrin 50 mg - ferrous sulphate 20 mg - vit c 100mg - folic acid 200mcg - vit b 12 1mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25139, 'alprazolam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30433, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30433, 'dexamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17098, 'ondansetron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5736, 'etoricoxib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26015, 'diclofenac sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16453, 'cilostazol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26499, 'octreotide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'lactic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'sulphur', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'retinol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'liquorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21577, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28590, 'dorzolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22545, 'ibuprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22545, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17253, 'benzocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'vitamins b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'b2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'b3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'b5', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31948, 'b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4923, 'diclofenac potassium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16006, 'panthenol-urea - shea butter - dimethicone potassium hydroxide - glycerin - sodium benzoate - aloe vera leaf extract - stearic acid - paraffin wax - glyceryl stearate - water', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17825, 'febuxostat', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3143, 'omega iii', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3143, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25419, 'dothiepin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17671, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26043, 'chlorpheniramine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26043, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26043, 'pseudoephedrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3161, 'abrocitinib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30965, 'tropicamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4293, 'chlordiazepoxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4293, 'clidinium bromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14924, 'ginkgo biloba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30225, 'ipratropium bromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30225, 'salbutamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28371, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28371, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28371, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28371, 'vitamin b', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28371, 'vitamin d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28482, 'ambroxol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28482, 'guaifenesin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28482, 'theophylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'vitamin a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'liquorice extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7343, 'titanium dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7388, 'thioctic acid(alpha lipoic acid)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'l-carnatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'vit d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'vit a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'vit e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24076, 'b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3236, 'ganciclovir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5525, 'ivy leaf extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1390, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1390, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1390, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1390, 'b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1390, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1390, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13569, 'thioctic acid(alpha lipoic acid)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13569, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13569, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13569, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13569, 'ginko biloba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13569, 'bacopa extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6669, 'itraconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8686, 'neomycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8686, 'polymyxin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8686, 'prednisolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (663, 'sweet almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (663, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (663, 'beta-sitosterol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (663, 'centella asiatica', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (663, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (663, 'beeswax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17095, 'ondansetron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11481, 'tobramycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31028, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25658, 'ramipril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33236, 'infant milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12978, 'dapsone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9410, 'phenoxymethyl penicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2975, 'bisoprolol fumarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19051, 'orlistat', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'saw palmetto', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'ginkgo', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'royal jelly', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'aloe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'rosemary', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'chamomil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'clove', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'jojoba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'lavender', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25377, 'panthe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22895, 'moxifloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4890, 'deflazacort', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3326, 'dapsone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21573, 'ivy leaves', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21573, 'acetyl cysteine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18985, 'citicoline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18985, 'alpha lipoic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18985, 'l carnitine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18985, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30010, 'nitazoxanide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26388, 'silicon', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26388, 'amla oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26388, 'coconut oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26388, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26388, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26388, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29201, 'amikacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3569, 'glimepiride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32908, 'alogliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1341, 'vitamin b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1341, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1341, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23986, 'ceftriaxone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27126, 'thioctic acid(alpha lipoic acid)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30634, 'jojoba liquid wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24989, 'human albumin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30286, 'cefepime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'jojoba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'coconut', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'carrot', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14295, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21000, 'isoflurane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25608, 'rabeprazole sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24354, 'acetic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27104, 'glucose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27104, 'amino acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27104, 'lipids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17482, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17482, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18494, 'erythropoietin-alpha', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27679, 'fluconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1923, 'glucosamine sulfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1923, 'collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1923, 'chondroitin sulfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1923, 'msm', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'gtn', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'tannic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'lidocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'clove extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1770, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20545, 'empagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20545, 'linagliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12661, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8306, 'fosinopril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8306, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14115, 'fenticonazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25200, 'stearic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25200, 'paraffin oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25200, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25200, 'urea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'lactobacillus acidophilus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'vitamin b5', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'iodin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3539, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6501, 'insulin neutral human', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24768, 'pantoprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6939, 'royal jelly', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6939, 'bee pollen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6939, 'wheat germ', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6939, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11936, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15095, 'fenoterol hydrobromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32120, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25098, 'povidone- iodine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3147, 'rosuvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14522, 'avanafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5731, 'linagliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5731, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13252, 'anti-t lymphocyte(anti-thymocyte) immunoglobulin=a.t.g.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22810, 'diclofenac potassium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28351, 'cefdinir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29284, 'boceprevir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29040, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29040, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3833, 'vitmain b', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7149, 'alprazolam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26304, 'psyllium husk powder', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26304, 'chromium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11684, 'clarithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11684, 'omeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11684, 'tinidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24746, 'haloperidol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21385, 'vitamin d3 active form', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (61, 'magaldrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (61, 'simethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32460, 'mirabegron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33549, 'ivy leaves', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33549, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33549, 'liquorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22059, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22059, 'losartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5432, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14506, 'fludrocortisone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15661, 'calcitonin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21896, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21896, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4674, 'captopril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4674, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32445, 'articaine hydrochloride 4%', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32445, 'epinephrine 0.017mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2682, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2682, 'sodium fluoride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2682, 'essential oils', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2850, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2850, 'mecobalamin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27986, 'tegaserod', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'pantothenic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'catalase', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'horsetail extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'paba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'l-tyrosine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'beta sitosterol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'nettle root extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3863, 'chlorophyllin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8139, 'miconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4592, 'enalapril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4592, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27167, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27167, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22624, 'zoledronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11178, 'valsartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15115, 'povidone- iodine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13052, 'carbinoxamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21517, 'carbimazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17024, 'tolterodine l tartarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21914, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21914, 'vitamin k2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12864, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12864, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12864, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12864, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12864, 'citrus bioflavonoids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23601, 'cisatracurium besylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4255, 'vonoprazan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6166, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6166, 'multivitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7797, 'triamcinolone acetonide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20077, 'empagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'melfade', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'natural thymic peptides', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'glycosomes', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'copper ion inactivators', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'titanium dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'vitamin a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29665, 'vitami', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5080, 'matmarine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5080, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5080, 'lactic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5080, 'urea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5080, 'patch20', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5080, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4256, 'dexamethasone sodium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5919, 'haloperidol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28329, 'topiramate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30442, 'escitalopram', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'calendula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'dexpanthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'simethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22106, 'vaseline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6789, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6789, 'avocado butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6789, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1822, 'ivy', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1822, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28188, 'l-ornithine-l-aspartate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4146, 'isotretinoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26427, 'ampicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26427, 'sulbactam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25466, 'risperidone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22599, 'human menopausal gonadotrophin (fsh', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22599, 'lh)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4800, 'cholecalciferol(vitamin d3)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33912, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33912, 'saw palmetto', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33912, 'bitten', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29462, 'sea salt 0.9%', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29462, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29462, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32926, 'green coffee bean extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32926, 'raspberry ketones', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32926, 'garcinia anhydrous', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32926, 'green tea extract (dried leaves)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'niacinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'green tea extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'liquorice extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'vit e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32078, 'chamomile extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22534, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22534, 'methyl salicylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20391, 'flaxseed oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20391, 'omega-3 fatty acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8112, 'mexiletine hydrochloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29612, 'lamivudine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21147, 'metformin hydrochloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3431, 'citalopram', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8764, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8764, 'vitamin b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8764, 'vitamin b2', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8764, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8764, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24172, 'hypromellose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14819, 'azithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27710, 'amino acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27710, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27710, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16835, 'secukinumab', 0);
