INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31907, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19558, 'gabapentin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22137, 'saw palmetto oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22137, 'tomato extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22137, 'd-calcium glucarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22137, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22137, 'zinc sulfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18458, 'epirubicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8592, 'sodium cromoglycate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8592, 'xylometazoline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'bees wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'stearic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'paraffin oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27590, 'vaseline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11673, 'citicoline 100 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11673, 'omega 3 (epa', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11673, 'dha)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11673, 'gincobiloba extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18175, 'apixaban', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26438, 'sucralose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26438, 'dextrose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26438, 'maltodextrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32099, 'vitamin k', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'nanosilver', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'collagen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'l-carnitine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'silicon', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7686, 'others', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30577, 'cholecalciferol(vitamin d3)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19271, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28236, 'dexamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28236, 'tobramycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'gaultheria oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'turpentine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'willow bark', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'rosemary', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22384, 'bees wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14827, 'brinzolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18689, 'escitalopram', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25683, 'clozapine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23058, 'sertaconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17196, 'diltiazem', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19708, 'hidrolized keratin panthenol vital hair & scalp complex poliquaternium 7', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10622, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20521, 'betahistine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32929, 'dextromethorphan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32929, 'guaifenesin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10870, 'fluvoxamine maleate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33775, 'dha', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33775, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33775, 'vitamind3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33775, '19 vitamins and minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23104, 'bacitracin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23104, 'neomycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23104, 'polymyxin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24024, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24024, 'olmesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16211, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24654, 'penciclovir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1336, 'lactose free milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28934, 'sodium valproate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (566, 'methocarbamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (566, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8452, 'mupirocin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7891, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7891, 'vitamin d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7891, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7891, 'and magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29738, 'orlistat', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4577, 'selpercatinib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6871, 'ketoprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (325, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (325, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (325, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (325, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (325, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2542, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6246, 'insulin neutral human', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6246, 'insulin isophane protamine human', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8201, 'desmopressin acetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4193, 'cod liver oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4193, 'fish oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4193, 'blackcurrant oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4193, 'pumpkin seeds oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4193, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4193, 'dl-alpha-tecopheryl acetate 50%powder', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5206, 'ferrous fumarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5206, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5206, 'vit.b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5206, 'vit.c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5206, 'zn', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13684, 'articaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13684, 'adrinaline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31807, 'guaifenesin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31807, 'oxomemazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31807, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31807, 'sodium benzoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17986, 'parsley', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17986, 'celery seeds', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17986, 'basil leaves', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11768, 'dorzolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11768, 'timolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20733, 'clarithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'l-carnitine fumarate 2900 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'l-arginine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'glutathione', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'coenzyme 010', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7557, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13628, 'etoricoxib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22792, 'piperazine theophylline ethanoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3087, 'vit b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3087, 'vit b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3087, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3087, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2804, 'rosuvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32641, 'levosalbutamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4836, 'ferrous fumarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4836, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22062, 'omeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13197, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13197, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13197, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21021, 'pilocarpine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'calamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'dimensioned', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'honey', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'shea butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'rose oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15712, 'aloe vera extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22501, 'empagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22501, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19792, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4417, 'omeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24297, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24297, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24297, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24297, 'sodium saccharine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24297, 'sodium monofluorophosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24297, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'methyl salicylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'mint flavor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'poloxamer407', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'sodium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'fluride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33343, 'benzoic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5679, 'calcium carbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5679, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5679, 'glycine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27163, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24293, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24293, 'lignocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2770, 'clindamycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6716, 'estradiol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6716, 'dydrogesterone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3066, 'serratiopeptidase', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3066, 'trypsin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3066, 'rutin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3066, 'papain', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3066, 'bromelain', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3066, '8×pancreatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22723, 'ethinyl estradiol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22723, 'levonorgestrel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19570, 'amoxicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19570, 'clavulanic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9560, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3639, 'isosorbide dinitrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7435, 'ivy leaf extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3756, 'ivy powder extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3756, 'licorice extract 15:1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3756, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3756, 'strawberry liquid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22376, 'amikacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14591, 'atropine sulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4576, 'acetylsalicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22229, 'gadopentetate dimeglumine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12948, 'ketotifen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26862, 'quetiapine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7938, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7938, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7938, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7938, 'urea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7938, 'niacinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24264, 'fexofenadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5374, 'domperidone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29196, 'solifenacin succinate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28564, 'ceftriaxone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16526, 'clindamycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24930, 'sodium picosulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30982, 'dexamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30982, 'netilmicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19818, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19818, 'sitagliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30759, 'dill seed oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30759, 'caraway seed oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24138, 'chloramphenicol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14448, 'celecoxib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25803, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25803, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'horse tail ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'avocado oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'potassium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'fennel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'camphor oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33829, 'ginger', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1073, 'atenolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15098, 'scilla tincture', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15098, 'liquorice extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15098, 'honey', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1079, 'atomoxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (420, 'ivy leaf', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (420, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (420, 'licorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26038, 'budesonide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-histidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-isoleucine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-leucine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-lysine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-methionine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-phenylalanine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-threonin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-tryptophan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-tyrosine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24158, 'l-valine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'ceteareth-23', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'fatty acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'licorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'titanium dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3450, 'sun protection', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25337, 'propranolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'halibut liver oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'melissa', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'zinc yeast', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'dried yeast', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12427, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21386, 'ketoprofen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3039, 'trypsin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3039, 'rutoside', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3039, 'bromalin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'chamazulene', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'bee wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'liquorice', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'titanium dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'vaseline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9012, 'propylene glycol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26330, 'ivy leaves', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1718, 'brimonidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1718, 'timolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (263, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (156, 'distigmine bromide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27049, 'hypertonic seawater', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1092, 'atorvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1092, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21028, 'prednisolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21028, 'phenylepherine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'chlorhexedine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'thyme ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'ginger ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'chamomile ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'marshmallow ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'licorice ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'echinacea ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19493, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16615, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16615, 'irbesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22178, 'multivitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22178, 'minerals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2667, 'cisplatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1269, 'mupirocin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4501, 'ebastine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16929, 'tedizolid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16661, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16661, 'chondroitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16661, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16661, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5455, 'chondroitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5455, 'glucosamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5455, 'methyl sulphonyl methane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4808, 'desloratadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12625, 'cefepime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6474, 'melatonin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6474, 'pyridoxine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6474, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23429, 'pregabalin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23996, 'ginseng root 500 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23996, 'royal jelly 1000 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23996, 'wheat germ oil 250 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23996, 'fermented bee pollen 250 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30738, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30738, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30738, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30738, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30738, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22084, 'losartan potassium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4623, 'maca root extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27533, 'citric acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27533, 'magnesium citrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27533, 'potassium citrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27533, 'sodium citrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15178, 'betaxolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26770, 'bearberry ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26770, 'liquorice ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26770, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26770, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19712, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5551, 'esomeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29229, 'human albumin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26366, 'cefadroxil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6686, 'ivermectin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9886, 'chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9886, 'sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9886, 'potasium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9886, 'zink', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22015, 'trifluridine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22015, 'tipiracil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18078, 'vancomycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3703, 'proso millet fruit extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3703, 'pantothenic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3703, 'l-cystine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3703, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7984, 'ferrous bis glycinat', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7984, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7984, 'vaitimn c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7554, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7554, 'losartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9545, 'paclitaxel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21723, 'letrozole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7838, 'melatonine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7838, 'chamomile extrac', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27541, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27541, 'lacticacid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27541, 'teatreeoil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27541, 'chlorhexidinegluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31624, 'etoricoxib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19745, 'mosapride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8251, 'insulin neutral human', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8251, 'insulin isophane protamine human', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19243, 'fluticasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19243, 'formoterol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26456, 'sulphasalazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27438, 'gabapentin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25015, 'cefoxitin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13316, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13316, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13316, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13316, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13316, 'echineacea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13316, 'elderberry', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2500, 'chlorpheniramine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4821, 'risankizumab', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32693, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32693, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32693, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22565, 'cephradine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20779, 'bisoprolol fumarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2448, 'cetirizine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5234, 'diloxanide furoate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5234, 'metronidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'omega3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, '6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'boswellic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'curcmin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'rosemary extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33169, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'argan oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'rosemary oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'coconut oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'chamomile oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26580, 'cyclopentasiloxane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'tocopheryl acetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'triethanolamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'cetearyl alcohol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'carbomer', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'parfum', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'propylparaben', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'methylparaben', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'diazolidinyl urea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'chamomilla recutita flower oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'simmondsia chinensis seed oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'isopropyl myristate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'aqua', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'polysorbate 20', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'stearic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3418, 'steareth-20', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (121, 'pioglitazone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21171, 'kojic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21171, 'licorice extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21171, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17829, 'rasagiline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14346, 'dapoxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24680, 'gabapentin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19498, 'fusidic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9688, 'nutritive powder formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29377, 'clioquinol(iodochlorhydroxyquin)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29377, 'hydrocortisone acetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13440, 'calcium carbonate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13440, 'risedronate sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11975, 'colchicine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11975, 'khellin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11975, 'piperazine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25933, 'camphor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25933, 'menthol crystals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25933, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25933, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21445, 'pramoxin hcl', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21445, 'cetrimide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21445, 'benzyl alchol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21445, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17057, 'zinc pyrithion', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17057, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17057, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17057, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17057, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7275, 'levofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16218, 'fish oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16218, 'l-methylfolate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20055, 'sofosbuvir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12938, 'acyclovir', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6978, 'clonazepam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9812, 'semaglutide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7290, 'tetramethrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7290, 'piperonyl butoxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19936, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23634, 'nifuroxazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25669, 'pramipexol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4844, 'ferrous sulfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4844, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4844, 'zinc sulfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14979, 'ivy extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17559, 'chromium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17559, 'vandyl', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17559, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17559, 'floc acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17559, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17559, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24013, 'alogliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4590, 'brexpiprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26725, 'selenium sulfide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26725, 'pirocton olamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26725, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26725, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26725, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26725, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17087, 'zinc pyrithion', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17087, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17087, 'resorcinol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33667, 'soyabean oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33667, 'avocado oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5131, 'vonoprazan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3091, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3091, 'valsartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2072, 'dexrazoxane', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8494, 'miconazole', 0);
