INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18459, 'epirubicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16732, 'olopatadine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'caffiec acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'keratin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'aloe vera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26448, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24389, 'dapoxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20921, 'canagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25194, 'betaxolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2922, 'mebeverine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31079, 'safinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1544, 'procapil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1544, 'trichogen veg ls 9922', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1544, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1544, 'saw palmetto extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1544, 'hydrolyzed keratin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1544, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16443, 'clarithromycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18992, 'ferrous (ii)-glycine sulphate complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7777, 'palmitoylethanolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2650, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6711, 'estradiol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6711, 'dydrogesterone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12907, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12907, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19844, 'glimepiride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18701, 'rivastigmine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'collagen from fish', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'elastin from fish', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'lanoline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'caffeine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'paraffin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'alovera', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'd- panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'dimethicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'shea butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'coco butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'retinyl palmitate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'glycerine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2322, 'vitamin e.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6419, 'immunoglobulin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (238, 'biperidene', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16102, 'rosuvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'triple silicone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'onion oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'quercetin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'vit e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'vit a', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'soybean oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'fish oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'palm oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'titanium dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6491, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12860, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12860, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12860, 'dimethicone(350)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12860, 'bisabolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12860, 'cetrimide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31519, 'carbazochrom', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31519, 'troxerutin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6454, 'indomethacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24119, 'alfacalcidol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15635, 'alfacalcidol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16230, 'sulphamethoxazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16230, 'trimethoprim', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16293, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14431, 'paracetamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14431, 'diphenhydramine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14431, 'phenylephrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3019, 'gabapentin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29870, 'paricalcitol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8520, 'zinc sulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15592, 'exenatide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15393, 'clopidogrel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6322, 'activated charcoal', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6322, 'fennel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6322, 'caraway', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6322, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6322, 'ginger', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6322, 'anise', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1914, 'echinacea - black elderberry -zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21315, 'vancomycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14769, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14769, 'atorvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8512, 'triethanolamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18639, 'granisetron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15167, 'cefotaxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33691, 'steviol glycosides', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33691, 'erythritol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4053, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4053, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4239, 'melatonin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4239, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32887, 'gemcitabine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19806, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19806, 'sitagliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23775, 'ampicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23775, 'sulbactam', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3537, 'dexamethasone sodium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4062, 'miconazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4062, 'mometason', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3728, 'propofol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19344, 'propolis', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19344, 'manuka honey', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19344, 'echinacea', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19344, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19344, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19344, 'probioitics', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9698, 'pefloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29914, 'cefprozil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10348, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29781, 'irbesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19910, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (741, 'olmesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5946, 'vitamins: vitamin c vitamin b1 (thiamine) vitamin b2 (riboflavin) vitamin b3 (niacin) vitamin b5 (pantothenic acid) vitamin b6 (pyridoxine) vitamin b7 (biotin) vitamin b9 (folate) vitamin b12 (cobalamin) minerals: iron zinc calcium magnesium potassium copper manganese', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30185, 'probiotic blend( lactobacillus plantarum', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30185, 'bifidobacterium longum subsp.infantis)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30185, 'whey protein concentrate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'kojic dipalimtat', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'alpha arbutin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'niacinamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'ceramide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'boswellia', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'grape seed', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7809, 'lactic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11301, 'lercanidipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11301, 'enalapril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26848, 'sertraline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1440, 'betamethasone dipropionate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1440, 'betamethasone sodium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31987, 'cholecalciferol(vitamin d3)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26608, 'risperidone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'sunactive liposomal iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'amino acid chelated iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'active folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'iodine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8145, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33105, 'omega 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33105, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33105, 'vitamin b1', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33105, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31524, 'garcinia 200 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31524, 'green coffee bean extract 200 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31524, 'green tea extract 200 mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31524, 'chromium 804.4 mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27028, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27028, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21322, 'gramicidin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21322, 'neomycin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21322, 'nystatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21322, 'triamcinolone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2568, 'hydroxyprogesterone caproate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16765, 'pantoprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1751, 'bacterial lysate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31073, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23437, 'eszopiclone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19726, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15455, 'sodium picosulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28269, 'cetirizine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11202, 'levofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'avocado oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'coconut oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'aloe vera oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28252, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12695, 'cefixime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27002, 'milk formula stage 3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27006, 'premature milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23362, 'apixaban', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1790, 'ubidecarenone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1790, 'coenzyme q10', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29312, 'vilazodone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32150, 'ondansetron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20740, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20740, 'glycolic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20740, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20740, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20740, 'sulfur', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21990, 'bisoprolol fumarate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21990, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19635, 'betamethasone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'lemon oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'menthol crystals', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'chlorohexidine digluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21500, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10527, 'lisinopril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19223, 'vitb1 thiamin 100mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19223, 'vit b6 pyridoxin 100mg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19223, 'vitb12 cyanocobalamine 200 mcg', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'chlorhexidine gluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'thymus extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'cinnamon bark extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'horse tail extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'cinnamon bark oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5695, 'lidocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7166, 'garcinia cambogia', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7166, 'green coffee bean extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7166, 'caffeine anhydrous', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7166, 'green tea extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16912, 'ivy leaves', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17678, 'povidone- iodine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20076, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27958, 'ginkgo biloba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16040, 'cefotaxime', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19828, 'arnica montana', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19828, 'harpagophytum', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25389, 'hamamelis extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25389, 'ichtammol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25389, 'potassium iodide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24485, 'amino acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24485, 'sorbitol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26235, 'ceftriaxone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22802, 'minoxidil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9729, 'pentoxifylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26139, 'calcium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26139, 'potassium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26139, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26139, 'sodium lactate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6708, 'copper sulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6708, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6708, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6708, 'manganese sulphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6708, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6708, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17422, 'dexamethasone sodium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20393, 'phyto-extract-bio-active oils', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11170, 'benzydamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9223, 'omeprazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30606, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2037, 'psyllium husk', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2037, 'pineapple flavor', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2037, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2037, 'sucralose', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28199, 'dorzolamide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28199, 'timolol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26458, 'salbutamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32660, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32660, 'thyme', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32660, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32660, 'oak ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32660, 'ginko ext.', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (32660, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23377, 'glucose (dextrose)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23377, 'potassium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23377, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30477, 'methylcobalamin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30477, 'folic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5647, 'imeglimin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16024, 'cefoperazone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'co enzyme q10', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'ginko biloba', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'ginseng', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'l-arginine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'biotin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15197, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5014, 'amoxicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5014, 'flucloxacillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (29814, 'ketotifen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24298, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24298, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24298, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24298, 'sodium saccharine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24298, 'sodium monofluorophosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24298, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4136, 'lidocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4136, 'prilocaine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31663, 'polysiloxanes', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31663, 'silicon dioxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10698, 'citicholine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15650, 'calcium gluconate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15650, 'calcium levulinate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27017, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27017, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16255, 'chlorpheniramine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14082, 'cefalexin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13931, 'amino acids', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13931, 'electrolytes', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1829, 'silicone gel', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27859, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20514, 'pseudoephedrine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20514, 'triprolidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7214, 'duloxetine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22259, 'mannitol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'chamomile ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'jojoba oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'coconut oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'triethanolamine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28621, 'white bees wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21619, 'amoxicillin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21619, 'clavulanic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1123, 'isotonic sea water', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (1123, 'bicarbonates', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'chlorhexidine diacetate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'tea tree ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'eugenia', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'clove ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'thyme ext', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2814, 'calcium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (248, 'policresulen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (18696, 'rivastigmine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10172, 'sodium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22561, 'salbutamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11758, 'dextromethorphan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33292, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33292, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33292, 'vit d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33292, 'vit c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33292, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20301, 'ivy leaves', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27677, 'amiodarone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22010, 'hydroxocobalamin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (12208, 'theophylline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3634, 'diclofenac sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (27884, 'tamoxifen', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6161, 'ubidecarenone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6161, 'coenzyme q10', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20657, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20657, 'losartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20366, 'yeast', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5530, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5530, 'sitagliptin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16608, 'ethyl alcohol 70%', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16608, 'salicylic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16608, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (16608, 'vitamin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25786, 'gentamicin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8527, 'tadalafil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33325, 'omega-3 fish oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (33325, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28900, 'sun protection formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'chlorohexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'clove oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'thymol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'peppermint oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10910, 'calendula ectract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31606, 'probiotic', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31606, 'prebiotic', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31606, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31606, 'lactoferrin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22434, 'acnacidol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22434, 'allantoin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22434, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22434, 'parsol tx', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22434, 'uvinul a plus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28576, 'trospium chloride', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3357, 'diclofenac sodium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23558, 'nicotinic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'calcium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'magnesium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'copper', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'manganese', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26529, 'boron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19132, 'methocarbamol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19132, 'paracetamol(acetaminophen)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24026, 'hydrochlorothiazide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (24026, 'olmesartan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23233, 'extra care milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'chlorobutanol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'bht', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'calendula oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14647, 'paraffin oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7432, 'lisinopril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31805, 'probiotics', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31805, 'prebiotics', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31805, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (31805, 'colostrum', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8250, 'iron', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8250, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (8250, 'vitamin b12', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22774, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22774, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'olive oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'almond oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'soy bean oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'seasame oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'menthol oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'eruca oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'aloe vera extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28556, 'wheat germ oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23164, 'bacillus coagulans spores', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23164, 'curcumin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (23164, 'niacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25473, 'escitalopram', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30599, 'empagliflozin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30599, 'metformin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'sucralfate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'cocoa butter', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'lanoloin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'white vaseline', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'white wax', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'purified water', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'caprilyl glycol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'calendula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (30471, 'witch hazel leaf', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2861, 'betaglucan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2861, 'vitamin c', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2861, 'zinc', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14909, 'chlorhexidine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14909, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14909, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14909, 'alo vera extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14909, 'chammomile extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (13950, 'lubiprostone', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14800, 'ezetimibe', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (14800, 'simvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5972, 'eucalyptus oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5972, 'menthol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5972, 'methyl salicylate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5972, 'terpentine oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (5881, 'omega', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26224, 'rizatriptan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (25048, 'vitamins', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (4661, 'indomethacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21969, 'amlodipine', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21969, 'benazepril', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (2803, 'rosuvastatin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10100, 'sea water', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10100, 'eucalyptus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10100, 'glycerin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (10100, 'hyaluronic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28683, 'ciprofloxacin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22445, 'massage cream formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28388, 'tramadol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (890, 'lactose free milk formula', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17704, 'betamethasone dipropionate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (17704, 'betamethasone sodium phosphate', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22865, 'resveratrol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22865, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (22865, 'vitamin d3', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (3916, 'cefadroxil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (821, 'selenium', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (821, 'vitamins (a-c-e)', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (9702, 'peginterferon alfa - 2b', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26819, 'lanolin', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26819, 'petrolatum', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26819, 'panthenol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26819, 'cetyl stearyl alcohol', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26819, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26819, 'vitamin b6', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (28491, 'metronidazole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (7244, 'etoricoxib', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15758, 'honey', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15758, 'bee propolis', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15758, 'zinc oxide', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15758, 'paraffin oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15758, 'stearic acid', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (15758, 'chamomile', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (11927, 'lactobacillus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6788, 'spirulina', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20239, 'cod liver oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (20239, 'vitamin e', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21697, 'thyme extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21697, 'calendula extract', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21697, 'triclosan', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (21697, 'tea tree oil', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (26822, 'sertindole', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (6298, 'lactobacillus rhamnosus', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19071, 'vitamin b complex', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19071, 'vit d', 0);
INSERT OR IGNORE INTO med_ingredients (med_id, ingredient, updated_at) VALUES (19071, 'vit c', 0);
