INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'd- panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'polysorbate 20');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29069, 'dmdm hydantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29070, 'diosmin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29070, 'hesperidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29070, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29071, 'vinpocetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29072, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29072, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29072, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29072, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29073, 'vinblastine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29074, 'bortezomib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29075, 'bortezomib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29076, 'sertaconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29077, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29079, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29080, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29081, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29083, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29085, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29086, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29086, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29086, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29086, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29086, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29086, 'bht');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29087, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29091, 'venetoclax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29092, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29092, 'dexamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29093, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29095, 'selenium sulphide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29096, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29097, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29098, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29099, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29100, 'desvenlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29101, 'desvenlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29103, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29105, 'grape (vitis vinifera) leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29105, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29105, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29105, 'orange oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29105, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29109, 'diosmin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29109, 'hesperidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29109, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29110, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29111, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'centella');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29113, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29114, 'zafirlukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29115, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29116, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29118, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'licuorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29120, 'titanium dioxi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29123, 'dyphylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29123, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29124, 'dyphylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29124, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29125, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29125, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29125, 'bromhexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29127, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29128, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29131, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29133, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29133, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29134, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29137, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29139, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29141, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29143, 'escitalopram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29144, 'vardenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29155, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29156, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29161, 'teatree');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29161, 'borax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'caviar extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'marine collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'glutathione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'melone extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'papaya extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29162, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'aloe vera ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'silicon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'piroctone olamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29163, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29164, 'silicone oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29164, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29164, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29164, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29164, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29164, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29165, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29165, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29165, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29165, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29174, 'psyllium husk powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29174, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29176, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29177, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29178, 'vaccine rabies');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29182, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29183, 'eltrombopag olamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29185, 'fenugreek seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29185, 'caraway seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29185, 'fennel seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29185, 'thyme leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29185, 'dill seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29187, 'cinnarizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29187, 'domperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29188, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29189, 'abemaciclib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29190, 'abemaciclib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29191, 'abemaciclib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29192, 'abemaciclib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29193, 'tretinoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29195, 'solifenacin succinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29196, 'solifenacin succinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29199, 'chitosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29200, 'amikacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29201, 'amikacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29202, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29202, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29203, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29203, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29204, 'vancomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29205, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29205, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29206, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29206, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29207, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29207, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29208, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29209, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29210, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29211, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29211, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29211, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29212, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29213, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29214, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29216, 'rimexolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29218, 'voriconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29222, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29225, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29225, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29225, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29226, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29226, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29226, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29226, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29227, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29229, 'human albumin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29230, 'beclomethasone dipropionate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29231, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29232, 'beclomethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29232, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29233, 'terconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29234, 'terconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29237, 'doxycycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29280, 'dextromethorphan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29280, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29282, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29284, 'boceprevir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29285, 'thyme liquid ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29285, 'white pine ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29285, 'anise oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29285, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29286, 'azacitidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29287, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29288, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29289, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29290, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29291, 'polyvinylpyrrolidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29292, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29292, 'macadamia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29292, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29292, 'natural oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'cocamidopropyl betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'chlorhexidine gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'sodium fluoride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'ethanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'sorbitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29294, 'sodium sac');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29295, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29296, 'vardenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29299, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29300, 'human normal immunoglobulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29301, 'human normal immunoglobulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29303, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29305, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29307, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29307, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29307, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29307, 'omega-3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29308, 'alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29308, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29308, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29308, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29308, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29309, 'dihydroxyacetone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29310, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29311, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29312, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29313, 'omega3 2975mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29313, '5ml (epa & dha )');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29314, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29315, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29316, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29317, 'vilazodone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29318, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29318, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29319, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29320, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29321, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29321, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29322, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29323, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29323, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29351, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29352, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29353, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29354, 'linezolid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29355, 'clindamycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'sodium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'irgasan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29356, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29357, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29357, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29357, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29358, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29359, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29359, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29359, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29359, 'vitamin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29359, 'liposomal iron witn folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29359, 'vitamin c b3 6 12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29360, 'vincamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29364, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29364, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29364, 'methylcobalamin 1000 mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29366, 'vinorelbine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29367, 'vinorelbine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29368, 'vinorelbine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29369, 'vinorelbine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29371, 'vinpocetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29372, 'vinpocetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29377, 'clioquinol(iodochlorhydroxyquin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29377, 'hydrocortisone acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29378, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29378, 'hydrocortisone acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29379, 'cefixime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29380, 'cefixime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29384, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29384, 'vitamin (c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29384, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29384, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29385, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29385, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'centella');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29386, 'isopropyl myristate.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29387, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29387, 'flumethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29388, 'alogliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29388, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29389, 'alogliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29389, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29390, 'alogliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29391, 'ribavirin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29393, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29393, 'alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29393, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29393, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29395, 'amantadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29396, 'tenofovir disoproxil fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29397, 'tenofovir disoproxil fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29398, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29400, 'ribavirin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29402, 'ribavirin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29403, 'potassium hydrogen sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29403, 'potassium monopersulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29403, 'potassium sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29404, 'potassium hydrogen sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29404, 'potassium monopersulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29404, 'potassium sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29405, 'valacyclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29406, 'ribavirin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29407, 'ribavirin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29409, 'rimantadine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29410, 'tromantadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29411, 'acyclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29412, 'acyclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29413, 'acyclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29414, 'acyclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29416, 'dienogest');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29417, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29418, 'tiemonium methylsulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29419, 'tiemonium methylsulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29422, 'tiemonium methylsulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29423, 'tiemonium methylsulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29427, 'mecystiene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29428, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29429, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29430, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29431, 'mistletoe extract from the host tree ash');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29432, 'mistletoe extract from the host tree ash');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29433, 'sodium cromoglycate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29434, 'tetrahydrozoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29434, 'zinc sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29435, 'tetrahydrozoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29436, 'iodixanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29437, 'iodixanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29438, 'iodixanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29441, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29441, 'magnesium alginate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29441, 'magnesium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29442, 'levocabastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29443, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29443, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29443, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29443, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29443, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29443, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'amino acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'natural fibers');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'anti oxidant');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29444, 'lipo-tropics');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29446, 'cantharides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29446, 'capsicum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29446, 'jaborandi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29446, 'pilocarpine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29446, 'phenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29446, 'resorcinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'fluroide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'vit(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29448, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29450, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29450, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29451, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29451, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29452, 'calcium levulinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29452, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29452, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29453, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29454, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29455, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29456, 'lercanidipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29457, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29461, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29462, 'sea salt 0.9%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29462, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29462, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29463, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'halibut liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'melissa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'zinc yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'dried yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29464, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'halibut liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'melissa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'zinc yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'dried yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29466, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29467, 'glucosamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29467, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29467, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29467, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'betacarotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'cu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'mn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'se yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29468, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'eruca oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'nigella oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29475, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'eruca oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'nigella oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29476, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'eruca oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'nigella oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29477, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29478, 'zinc gluconate 80mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29478, 'vitamins (c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29478, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29478, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29480, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29480, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29480, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29481, 'african palm oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29481, 'curcuma');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29481, 'myrrh');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29481, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29481, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (29483, 'iron');