INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19787, 'troxerutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19788, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19788, 'magnesium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19788, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19788, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19788, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19788, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19791, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19792, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19793, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19793, 'lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19794, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19795, 'hydrolyzed marine collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19795, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19795, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19795, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19796, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19796, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19796, 'ginko biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19796, 'bee pollen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19796, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19797, 'afatinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19798, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19798, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19798, 'garlic extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19798, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19798, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19799, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19799, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19799, 'garlic extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19799, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19799, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19800, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19800, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19800, 'garlic extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19800, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19800, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19801, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19801, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19803, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19803, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19804, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19804, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19806, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19806, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19808, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19809, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19809, 'garcinia cambogia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19809, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19809, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19809, 'green coffee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19809, 'glucomannan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19811, 'myo-inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19811, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19811, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19812, 'dorzolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19812, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19813, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19814, 'mometasone furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19814, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19815, 'sertaconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19816, 'sertaconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19817, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19817, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19818, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19818, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19819, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19821, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19822, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19823, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19825, 'glipizide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19825, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19826, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19827, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19828, 'arnica montana');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19828, 'harpagophytum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19829, 'omega oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19829, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19833, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19835, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19836, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19837, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19838, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19839, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19839, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19840, 'sacubitril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19840, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19841, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19842, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19842, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19843, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19844, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19845, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19846, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19847, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19848, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19850, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19851, 'glipizide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19852, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19853, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19853, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19854, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19854, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19855, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19855, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19856, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19856, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19857, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19857, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19858, 'saxagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19858, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19859, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19860, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19860, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19861, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19861, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19862, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19863, 'imatinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19865, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19866, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'elemental calcium 400 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'vitamin d3 500 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'magnesium 150 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'zinc 5mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'boron0.3mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'manganese 0.25mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'copper 250mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19869, 'selenium0.28mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19870, 'levodropropizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19871, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19872, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19873, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19874, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19875, 'venlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19877, 'betamethasone disodium phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19879, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19880, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19881, 'benzophenone-3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19881, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19881, 'cyclomethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'dimethiconol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'cyclopentasiloxan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19884, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19885, 'guaiphensin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19885, 'papaverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19886, 'glucagon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19888, 'ferrous gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19889, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19890, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19890, 'potassium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19890, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19890, 'sodium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19894, 'khellin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19894, 'diprophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19894, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19894, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19895, 'repaglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19897, 'repaglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19904, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19908, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19909, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19910, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19912, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19913, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19914, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19915, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19916, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19917, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19918, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19919, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19920, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19921, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19922, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19923, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19924, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19925, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19926, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19926, 'potassium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19927, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19928, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19929, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19930, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19931, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19932, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19933, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19934, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19935, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19936, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19937, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19938, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19939, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19940, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19941, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19942, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19942, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19944, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19944, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19946, 'mitiglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19949, 'gliquidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19950, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19950, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19951, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19951, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19952, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19953, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19954, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19956, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19957, 'glutamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'glutathione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'silymarine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19960, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19962, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19962, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19963, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19963, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19964, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19964, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19965, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19966, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19968, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19969, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19969, 'ichtammol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19971, 'gelatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19971, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19972, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19974, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19975, 'nitroglycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19976, 'nitroglycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19977, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19979, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19980, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19983, 'magaldrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19984, 'sodium glycerophosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19985, 'terlipressin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19987, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19987, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19987, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19988, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19988, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19988, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19989, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19989, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19989, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19993, 'caviar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19993, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19993, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'lexol 300');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'cocamidopropyl betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'peg 7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'f');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19996, 'micellar casein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19997, 'partially hydrolyzed whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19997, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19998, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19998, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19998, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19999, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19999, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19999, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20000, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20000, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20000, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20001, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20001, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20001, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'protein blend(whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'hydrolyzed whey protein isolate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'carbohydrate blend');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'vitamin (d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'thiamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'muscle matrix');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'performance composite');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'energy & focus complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20004, 'agar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20005, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20006, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20007, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20007, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'ginger oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'orange oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'peg-7 glyceryl cocoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'eruca sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'capsacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20011, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20013, 'cabergoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20015, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20015, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20015, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20016, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20017, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20018, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20019, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20021, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20022, 'testosterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'piroctone olamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'sodium laureth sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20024, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20024, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20024, 'chlorhexidine gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20026, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20027, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20028, 'colchicine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20028, 'probenecid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'chitosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'forskolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'garcinia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'green tea ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'vitamins (b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'safflower oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'bioflavonoids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20031, 'anti-t lymphocyte(anti-thymocyte) immunoglobulin=a.t.g.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20032, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20033, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20034, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20035, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20036, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20036, 'flucloxacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20037, 'ofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20038, 'fesoterodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20039, 'fesoterodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20040, 'ketotifen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'oils(camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'peppermint)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'vitamin(c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'vitamin(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'folic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20043, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20045, 'gramicidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20045, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20045, 'nystatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20045, 'triamcinolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20046, 'granisetron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20047, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20047, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20047, 'ceramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20049, 'granisetron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20050, 'amitriptyline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20052, 'doxycycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20054, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20055, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20056, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20057, 'natural wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20057, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20057, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20058, 'chelated calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20060, 'interferon alfa-2a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20061, 'interferon alfa-2a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20062, 'green coffee bean extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20063, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20065, 'inulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20065, 'fructose powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20065, 'strawberry flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20065, 'vanillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'rose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20066, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20067, 'blood-coagulation factor viii');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20069, 'thiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20069, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20069, 'ferrous sulfate heptahydrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20069, 'zinc sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20069, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20071, 'trimebutine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20072, 'mometasone furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20073, 'mometasone furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20074, 'terpeneless dill seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20076, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20077, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20079, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20079, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20079, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20079, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20079, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20079, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20080, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20080, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20080, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20080, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20080, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20080, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20081, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20081, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20081, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20081, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20081, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20081, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20082, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20082, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20082, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20082, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20082, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20082, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20083, 'gatifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20084, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20084, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20084, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20084, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20084, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20084, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20085, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20085, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20085, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20085, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20085, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20085, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20086, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20086, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20086, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20086, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20086, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20086, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20089, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20089, 'tilia flower');