INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'ethyl chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'thymol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'allantoin glycyrrhetinic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'tocopheryl acetate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'isopropyl myristate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24371, 'melaleuca alternifolia leaf oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24373, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24374, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24377, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24381, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24382, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24383, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24384, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24385, 'oxaprozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24386, 'oxaprozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24387, 'oxcarbazepine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24388, 'oxcarbazepine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24389, 'dapoxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24390, 'linezolid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24391, 'linezolid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24392, 'oxeladin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24393, 'oxeladin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24394, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24395, 'oxazepam');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24398, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'omega 3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'thioctic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'proanthocyanidins');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'bioflavonoids');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'molybdenum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24399, 'beta-carotene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24400, 'oxcarbazepine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24403, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24404, 'oxaliplatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24407, 'oxybutynin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24408, 'oxybutynin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24409, 'oxybutynin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24411, 'oxytocin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24412, 'oxytocin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24414, 'oxymetazoline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24415, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24416, 'oxymetazoline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24417, 'oxycodone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24418, 'oxycodone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24419, 'oxycodone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24420, 'oxycodone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24423, 'medroxyprogesterone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24424, 'oxytetracycline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24424, 'polymyxin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24428, 'oxytocin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24431, 'dorzolamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24432, 'dexamethasone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24433, 'pyrazinamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24434, 'carbetocin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24435, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24435, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24435, 'camphor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24435, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'sodium hyaluronate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'collagen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'caviar ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'vitamin (c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'glutathione');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'liquorice ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24436, 'coffee arabica seed ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24438, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24440, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24441, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24442, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24443, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24445, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24446, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24447, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24448, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24449, 'rabeprazole sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24450, 'trace elements');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24451, 'calcium gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24451, 'glucose (dextrose)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24451, 'potassium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24451, 'sodium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24454, 'felbinac');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24455, 'pregabalin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24456, 'pregabalin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24457, 'pregabalin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24458, 'pregabalin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24460, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24461, 'paclitaxel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24463, 'adapalene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24464, 'paliperidone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24465, 'paliperidone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24467, 'tazarotene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24468, 'tazarotene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24469, 'camphor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24469, 'peppermint oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24469, 'emu oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24469, 'eucalyptus extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24469, 'methyl salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24469, 'turpentine oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24470, 'adapalene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'ferrous fumarate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'vitamin(b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'c)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24472, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24473, 'chlorpropamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24475, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24476, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24476, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24476, 'phenylephrine hydrochloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24477, 'bortezomib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24478, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24478, 'phenylepherine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24479, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24479, 'diphenhydramine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24480, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24480, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24481, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24482, 'acetylsalicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24482, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24482, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24483, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24483, 'phenylepherine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24485, 'amino acids');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24485, 'sorbitol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24486, 'povidone- iodine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24487, 'povidone- iodine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24488, 'povidone- iodine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24489, 'povidone- iodine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24490, 'nifuroxazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24491, 'nifuroxazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24493, 'cefuroxime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24494, 'cefuroxime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24495, 'pancuronium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24496, 'pancuronium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24500, 'penciclovir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24505, 'cetalkonium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24505, 'choline salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24506, 'gramicidin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24506, 'neomycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24506, 'polymyxin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24508, 'pantoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24512, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24512, 'octopirox');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24515, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24516, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24517, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24518, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24519, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24521, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24522, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24523, 'vitamin b5');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24524, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24525, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24526, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24526, 'escin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24527, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24527, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24528, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24529, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'seasame oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'chamomile ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'cetrimide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24532, 'dimethic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'seasame oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'chamomile ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'cetrimide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24533, 'dimethic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24538, 'pantoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24539, 'pantoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24540, 'pantoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24546, 'ribavirin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24547, 'ribavirin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24548, 'papaya extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24548, 'chlorophyllin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24548, 'carbamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24548, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24549, 'cinacalcet');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24550, 'cinacalcet');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24551, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24553, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24554, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24556, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24557, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24558, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24559, 'paraffin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24560, 'chlorzoxazone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24560, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24561, 'metoclopramide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24561, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24564, 'diiodohydroxyquinoline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24564, 'metronidazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24566, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24567, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24568, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24568, 'pseudoephedrine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24569, 'chlorpheniramine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24569, 'phenylephrine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24572, 'metoclopramide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24572, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24573, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24573, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24576, 'rabeprazole sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24577, 'rabeprazole sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24578, 'canagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24579, 'canagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24580, 'entacapone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24581, 'carbidopa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24581, 'levodopa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24582, 'selegiline chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24583, 'trihexyphenidyle');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24589, 'chlorhexidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24589, 'sodium fluoride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24591, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24591, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24593, 'vit d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24593, 'vit k2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24597, 'paroxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24598, 'paroxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24601, 'paroxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24602, 'paroxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24603, 'paroxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24604, 'liquorice ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24604, 'arbutin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24604, 'kojic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24604, 'sandalwood oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24604, 'titanium dioxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24605, 'camphor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24605, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24605, 'menthol crystal');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24606, 'olopatadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24607, 'olopatadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24608, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24608, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24608, 'witch hazel extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24609, 'oxeladin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24611, 'omega-3 fish oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'licorice extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'nigella sativa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'titanium dioxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24614, 'stearic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'oils(snake');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'jasmine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'castor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'jojoba');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'wheat germ');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'almond');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'olive');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'safflower');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'coconut');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'tea tree)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24618, 'vit.e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24619, 'pimecrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24620, 'benproperine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24622, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24622, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24622, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24622, 'bee propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24622, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24622, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'chlorhexidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'bee propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24623, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24624, 'nutritive powder formula');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24625, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24627, 'prednisolone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24628, 'copper cl');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24628, 'magnesium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24628, 'sodium delenite');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24628, 'sodium fluoride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24628, 'potassium iodide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24628, 'zinc chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24629, 'dill oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24629, 'sodium bicarbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24632, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24632, 'chamomile oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24632, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24632, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24632, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24632, 'mink oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24633, 'clove');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24633, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24633, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24633, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24635, 'dexapanthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24635, 'royal jelly');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24636, 'dexapanthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24636, 'royal jelly');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24638, 'brimonidine tartrate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24639, 'peginterferon alfa - 2a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24641, 'peginterferon alfa - 2b');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'vitamins(a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'd3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'b12)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'niacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'iodine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24642, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24643, 'tadalafil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24644, 'sodium hyaluronate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24645, 'sodium hyaluronate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24646, 'nicardipine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'saw palmetto ext');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'rosemary ext');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'vitamins(c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24648, 'c)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'saw palmetto ext');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'rosemary ext');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'cetrimide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24649, 'shea butter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24651, 'pefloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24652, 'pemetrexed');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24654, 'penciclovir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24655, 'amoxicillin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24655, 'flucloxacillin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24656, 'benzathine penicillin g');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'coconut oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24658, 'vaseline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'pumpkin oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'sesame oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'coconut oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24659, 'hydrolyzed pr');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'oils of(sesame');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'wheat germ');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'coconut');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'eruca sativa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'pumpkin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'jojoba');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'olive');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24660, 'almond)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24661, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24661, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24661, 'hydrolyzed protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24661, 'hydrolyzed keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24661, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24661, 'cocamidopropyl betaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24662, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24662, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24662, 'hydrolyzed protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24662, 'hydrolyzed keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24662, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24662, 'cocamidopropyl betaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'coconut oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'castor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'rosemary oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'garlic oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24663, 'rocket oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'shea butter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'avocado oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'banana extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'grape seed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24664, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24665, 'methylprednisolone aceponate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24666, 'biphenyl dimethyl dicarboxylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24666, 'garlic oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24668, 'memantine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24669, 'beta-sitosterol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24670, 'chlorpheniramine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24670, 'dextromethorphan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24670, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24670, 'phenylephrine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24671, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24678, 'gabapentin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24679, 'gabapentin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24680, 'gabapentin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24681, 'mebendazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24682, 'mebendazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24683, 'duloxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24684, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24685, 'irgasan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24685, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24685, 'lemon oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24685, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24685, 'sulphur');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24685, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24686, 'mesalazine(mesalamine)(5-asa)(5-aminosalicylic acid)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24687, 'mesalazine(mesalamine)(5-asa)(5-aminosalicylic acid)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24689, 'mesalazine(mesalamine)(5-asa)(5-aminosalicylic acid)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24690, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24691, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24693, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24693, 'vitamin b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24693, 'vitamin b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24693, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24693, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24694, 'diphtheria');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24694, 'haemophilus influenza b');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24694, 'pertussis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24694, 'poliomyelitis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24694, 'tetanus toxoid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24695, 'cyclopentolate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24696, 'cyclopentolate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24697, 'pentosan polysulphate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24699, 'pentoxifylline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24700, 'pentoxifylline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24701, 'ibuprofen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24702, 'ibuprofen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24704, 'miconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24706, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24707, 'diastase');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24707, 'papain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24707, 'simethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24709, 'glucosamine hcl 500');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24709, 'msm');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24709, 'chondroitin sulfate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24709, 'calcium fructoborate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24709, 'hyaluronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24709, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24710, 'clove oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24710, 'thymol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24710, 'chamomile extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24710, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24710, 'green tea extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24711, 'extra care milk formula');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24712, 'extra care milk formula');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24714, 'famotidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24715, 'famotidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24716, 'clarithromycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24716, 'omeprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24716, 'tinidazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24717, 'calcium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24717, 'famotidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24717, 'magnesium hydroxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24718, 'famotidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24719, 'lansoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24720, 'pantoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24721, 'pantoprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'calcium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'magnesium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'vitd3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'boron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'manganese');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (24722, 'selenium');