INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27417, 'calendula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27417, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27417, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27418, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27418, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27418, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'vitamin c 10%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'marine collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'caviar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27421, 'itraconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27423, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27423, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27424, 'fluocinolone acetonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27424, 'hydroquinone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27424, 'tretinoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27425, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27425, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27427, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27428, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27429, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27431, 'dasatinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27432, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27432, 'peg 400');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27432, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27434, 'idrocilamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27435, 'idrocilamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27436, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27437, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27438, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'co-enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27440, 'stavudine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27441, 'inulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27442, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27442, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27442, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27443, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27443, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27443, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27444, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27444, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27444, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27445, 'vaccine yellow fever');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27446, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27447, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27448, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27450, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27450, 'chlorthalidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27451, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27451, 'chlorthalidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27453, 'tigecycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'witch hazel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'butcher s broom');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'horse-chestnut');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'yarrow');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'great burnet');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'mullein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'st. john s warts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'white fi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27455, 'sodium fusidate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27456, 'sodium fusidate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27457, 'hydrocortisone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27457, 'fucidic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27459, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27460, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27461, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27462, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27463, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27465, 'nateglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27466, 'nateglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'lauryl glucoside');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'vitamin(e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'papaya');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'licorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'licorice extract (glabridin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27477, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27478, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27479, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27480, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'molybdenum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'vitamins(b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b8');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'beta-carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27482, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27483, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27484, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27485, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27486, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27487, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27488, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27489, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27490, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27491, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27492, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27493, 'ustekinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27494, 'ustekinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27495, 'ustekinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27496, 'isopropamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27496, 'trifluoperazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'green tea ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'aloe vera ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'lemon ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'ginger ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'panax ginseng ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'glyceri');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'limonene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'linalool');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'limonene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'linalool');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27506, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27507, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27508, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27509, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27511, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27513, 'norethisterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27514, 'steviol glycosides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27514, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27515, 'steviol glycosides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27515, 'erythritol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27516, 'steviol glycosides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27516, 'erythritol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27517, 'steviol glycosides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27517, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27518, 'pyridostigmin bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27519, 'desloratadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27520, 'desloratadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27522, 'piracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27523, 'piracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27525, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27526, 'regorafenib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27528, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27528, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27530, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27530, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27531, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27532, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27533, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27533, 'magnesium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27533, 'potassium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27533, 'sodium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27534, 'guava extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27534, 'tilia extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27534, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'citronella oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'pine oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'lemon grass oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27535, 'isopropanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27536, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27537, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27537, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27538, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27538, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27538, 'propyphenazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27540, 'loperamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27541, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27541, 'lacticacid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27541, 'teatreeoil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27541, 'chlorhexidinegluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27542, 'phloroglucinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27542, 'trimethylphloroglucinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27543, 'apixaban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27556, 'atomoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27557, 'atomoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27558, 'atomoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27559, 'atomoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27560, 'atomoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27563, 'dichlorophenylcarbinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27563, 'amylmetacresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27564, 'dichlorophenylcarbinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27564, 'amylmetacresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27566, 'dichlorophenylcarbinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27566, 'amylmetacresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27568, 'dichlorophenylcarbinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27568, 'amylmetacresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27569, 'streptokinase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27570, 'streptomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27571, 'streptomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27574, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27574, 'homatropine methylbromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27574, 'phthalyl sulfathiazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27574, 'streptomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27577, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27578, 'dichlorophenylcarbinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27578, 'amylmetacresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27580, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27587, 'strontium ranelate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27589, 'cinnarizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27590, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27595, 'mouth wash formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27596, 'succinylcholine chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27597, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27597, 'lactose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27597, 'croscarmellose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27597, 'l-leucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27598, 'sucralfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27599, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27599, 'benzyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27599, 'benzyl benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27599, 'benzyl cinnamate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27599, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27600, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27600, 'benzyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27600, 'benzyl benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27600, 'benzyl cinnamate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27600, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27601, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27601, 'benzyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27601, 'benzyl benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27601, 'benzyl cinnamate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27601, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27602, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27602, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27602, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27603, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27604, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27604, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27604, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27605, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27605, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27606, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27606, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27607, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27608, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27609, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27610, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27611, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27611, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27613, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27613, 'sulbactam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27617, 'sulconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27618, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27618, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27618, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27618, 'cetyl myristoleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27619, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27619, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27619, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27619, 'cetyl myristoleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27620, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27620, 'ethanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27620, 'propane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27620, 'butane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27621, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27621, 'vanillybutyl ether');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27625, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27625, 'chondroitin sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27625, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27626, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27628, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27628, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27628, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27628, 'cetyl myristoleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27629, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27629, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27629, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27629, 'cetyl myristoleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27630, 'selenium sulfide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27639, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27639, 'sulbactam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27640, 'phenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27640, 'sulphacetamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27641, 'sulphadiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27642, 'silver sulfadiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27644, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27647, 'sumatriptan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27648, 'sumatriptan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27649, 'sumatriptan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27652, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27654, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27654, 'bearberry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27654, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27654, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27654, 'octymethoxy cinnamate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27654, 'benzophenon-3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27655, 'aluminium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27655, 'calcium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27655, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27656, 'aluminium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27656, 'calcium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27656, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27657, 'aluminium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27657, 'calcium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27657, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27658, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27659, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27660, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27674, 'tirofiban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27675, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27676, 'acetylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27677, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27678, 'l-ornithine-l-aspartate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27679, 'fluconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27680, 'oxytocin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27681, 'bupivacaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27682, 'bupivacaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27683, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27684, 'zoledronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27697, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27697, 'vit b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27697, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27698, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27700, 'ginko biloba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27701, 'colloidal silver');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27702, 'colloidal silver');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27703, 'thioctic acid(alpha lipoic acid)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27703, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27703, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27703, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27704, 'cod liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27705, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27706, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27707, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27707, 'bee pollen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27708, 'brewer s yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27709, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27709, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27710, 'amino acids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27710, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27710, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27712, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27713, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27714, 'echinaceae purpurea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27714, 'milk thistle');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27714, 'dandelion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'glyceryl monostearate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'cocamide dea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'sls');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'peg-7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27715, 'sod. chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'colostrum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'vitamin(b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27716, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27717, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27718, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27719, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'fat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'carbohydrates');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'fibre');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27720, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27721, 'tetracycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27722, 'desflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27723, 'cilastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27723, 'imipenem');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27725, 'cilastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27725, 'imipenem');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27726, 'acyclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27728, 'cefixime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27731, 'collagen hydrolysate 8 gm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27731, 'ascorbic acid 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27732, 'naproxen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27736, 'tiaprofenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27737, 'beractant');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27738, 'beractant');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27740, 'dapoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27741, 'sunitinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27742, 'sunitinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27743, 'sunitinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27746, 'pine bark extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27747, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27748, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27762, 'atenolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27763, 'ipratropium bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27763, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27764, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27764, 'colostrum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27764, 'vit. c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27764, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27764, 'vit. e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27765, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27765, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27765, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27765, 'ginko');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27766, 'vitamin d3 2000iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27766, 'fish oil 1000 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'green coffee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'rice protin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'horse chestnut');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'aloe vera oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27767, 'panthenol');