INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24724, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24726, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24727, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24728, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24728, 'sulbactam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24729, 'sodium perborate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24730, 'sodium perborate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'chamomile ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'vitamins(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24733, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24734, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24735, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24737, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24737, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24737, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24743, 'minoxidil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24744, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24744, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24745, 'minoxidil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24746, 'haloperidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24747, 'paliperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24748, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24749, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24749, 'glucose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24753, 'indapamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24753, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24754, 'indapamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24754, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24755, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24755, 'glucose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24756, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24756, 'glucose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24757, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24757, 'glucose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24759, 'calcium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24759, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24759, 'magnesium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24759, 'sodium acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24759, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24765, 'calcium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24765, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24765, 'magnesium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24765, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24765, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24767, 'pertuzumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24768, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24769, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24770, 'mebendazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'mineral oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'promulgen d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24771, 'fragr');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24772, 'carbamide peroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24773, 'dipyridamole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24776, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24776, 'drotaverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24776, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24777, 'panthenol 5%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24777, 'alovera extract 5%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24777, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24777, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24777, 'bht');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24778, 'econazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24779, 'econazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24779, 'triamcinolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24780, 'pentoxifylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24783, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24783, 'amino acids chelated minerals with vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24784, 'benzyl benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24785, 'triamcinolone acetonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24786, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24786, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24786, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24786, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24786, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24787, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24790, 'squalane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24790, 'vitamine a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24790, 'rapeseed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24790, 'hempseed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24790, 'vitamine e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24790, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24815, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24815, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24815, 'photostable uva and uvb filters');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24816, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24816, 'photo-stable');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24816, 'uva');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24816, 'uvb filters');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'passion flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'golden alga');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'photostable uva and uvb filters');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24820, 'tamarind extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24820, 'burdock extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24820, 'zinc pca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24827, 'mandelic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24827, 'lemon extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24827, 'fuit-peel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24840, 'fluorescein sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24841, 'gatifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24842, 'brimonidine tartrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24843, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24844, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24845, 'brimonidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24845, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24846, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24847, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24848, 'piracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'ethyl alcohol 70%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'chloroxylenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'ethyl alcohol 70%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'chloroxylenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'magnesium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24852, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24852, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24852, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24853, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24853, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24853, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24854, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24855, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24856, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24856, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24856, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24857, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24857, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24857, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24858, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24858, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24859, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24860, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24860, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24861, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24862, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'glycerol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'vitis vinifera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'sambucus nigra extract fruit');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'allium cepa ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'silicone dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'slaicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'vitamin(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24866, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24866, 'dexamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24867, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24867, 'sulfacetamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24868, 'phenobarbitone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24870, 'phenobarbitone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24871, 'phenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24871, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24872, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24873, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24874, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24875, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24876, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24877, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24878, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24879, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24880, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24881, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24882, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24883, 'prenoxdiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24884, 'prenoxdiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24885, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24886, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24887, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24888, 'phenindione(dindevan)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'phenylpropanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'pholcodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'promethazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'tolu syrup');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24890, 'sodium acid phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24893, 'amphotericin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24894, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24895, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24896, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24897, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24898, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24899, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24900, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24901, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24902, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24903, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24904, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24905, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24906, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24907, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24908, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24909, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24910, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24911, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24912, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'olea europaea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'pentylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'palm glycerides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'olus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'hydrogenated lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'squalene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'bet');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24914, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24915, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'natural seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'hypertonic concentration of mineral salts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'essential oil of eucalyptus globulus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'natu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24917, 'natural undiluted seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24917, 'hypertonic concentration of mineral salts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24918, 'natural undiluted seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24918, 'hypertonic concentration of mineral salts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24920, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24921, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24922, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24923, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24924, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24925, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24926, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24927, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24928, 'citicoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24930, 'sodium picosulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24931, 'sodium picosulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24931, 'magnesium oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24931, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'balsam peru');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'bismuth subgallate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'dexapanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'hamamelis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24937, 'cefepime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24938, 'cefepime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24939, 'pimozide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24940, 'pin bark');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24940, 'grape seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24941, 'psyllium husk powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24941, 'choromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24941, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24942, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'eruca oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24945, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24945, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24946, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24946, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24947, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24948, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24948, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24949, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24949, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24950, 'piperacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24951, 'piperacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24952, 'piperacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24952, 'tazobactam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24953, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24954, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24955, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24956, 'pirfenidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24957, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24957, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24958, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24959, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24960, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24961, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24962, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24963, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24964, 'pitavastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24966, 'pitavastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24968, 'pitavastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24970, 'apixaban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24971, 'apixaban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24975, 'palmitoyl dipeptide-5 hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24975, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24975, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24975, 'algae extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24975, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24975, 'grape seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24976, 'amantadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24977, 'amantadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24978, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24978, 'sodium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24978, 'sodium borate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24978, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24982, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24982, 'whey powder con.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24982, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24982, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24982, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24982, 'natural flavour (chocolate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24983, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24983, 'sorbitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24983, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24983, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24983, 'pineapple flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24984, 'rose oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24986, 'hydroxychloroquine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24987, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24987, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24988, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24988, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24989, 'human albumin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24992, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24993, 'hydrolyzed whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24993, 'micronized branched chain amino acids(l-leucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24993, 'l-isoleucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24993, 'l-valine)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24994, 'cisplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24995, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24996, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24997, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24998, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24999, 'cyclopentolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25000, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25001, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25002, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25003, 'felodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25004, 'felodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25005, 'felodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25006, 'felodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25007, 'felodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25008, 'felodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25009, 'phytoestrogens');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25009, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25009, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25009, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25009, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25010, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25011, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25013, 'penciclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25014, 'cefoxitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25015, 'cefoxitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'lemon grass oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'eugenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25016, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25017, 'vaccine pneumococcal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25018, 'cefpodoxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25019, 'cefpodoxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25020, 'cefpodoxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25021, 'cefpodoxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25022, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25022, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25022, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25023, 'propofol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25024, 'propofol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25025, 'polymyxin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25025, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25026, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25027, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25028, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25029, 'pollen grains');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25029, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25029, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25030, 'pollen grains');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25030, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25031, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25031, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25031, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25032, 'bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25032, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25032, 'polymyxin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25033, 'bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25033, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25033, 'polymyxin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25034, 'bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25034, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25034, 'polymyxin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25035, 'polycarbophil calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25036, 'beclomethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25036, 'chlorocresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25036, 'miconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25036, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25037, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25038, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25039, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25040, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25040, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25040, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25041, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25042, 'hypertonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25042, 'solution enriched in trace elements of copper and manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25043, 'natural purified and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25044, 'hypertonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25044, 'solution enriched in trace elements of copper and manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25046, 'ketorolac tromethamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25047, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25048, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25049, 'vaccine meningitis (group a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25049, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25050, 'vaccine meningitis (group a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25050, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25051, 'vaccine meningitis (group a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25051, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25052, 'polytar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25053, 'coal tar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25053, 'cade oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25054, 'coal tar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25054, 'cade oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25055, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25056, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25057, 'pancreatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25057, 'pepsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25057, 'taka diastase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25058, 'sodium laureth sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25058, 'cocamidopropyl betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25058, 'chlorhexidine gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25059, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25059, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25059, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25059, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25059, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25060, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25060, 'vit.e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25060, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25060, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25060, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25061, 'mefenamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25063, 'mefenamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25064, 'mefenamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25065, 'mefenamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25066, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25069, 'meclizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25069, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25071, 'diastase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25071, 'hemicellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25071, 'papain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25071, 'pepsin');