INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8157, 'midazolam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8158, 'midazolam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8160, 'midodrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8161, 'midodrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8162, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8164, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8165, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8165, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8168, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8168, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8169, 'metoclopramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8169, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8176, 'benfotiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8176, 'cyanocobalamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8176, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8177, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8177, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8177, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8177, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8177, 'jinko bilbao');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, 'microencapsulated liposomal iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '2mg copper bisglycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '12 mg zinc bisglycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '676mcg methylfolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '10mcg methylcobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '1000 iu vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '5mg vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8178, '120 mg vitaminc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8180, 'l-lysine vitamin c magnesium niacin iron vitamin e zinc pantothenic acid vitamin b1 vitamin b2 vitamin b6 manganese vitamin a folate lodine biotin vitamin b12 vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8181, 'tranexamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8181, 'centella');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8181, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8181, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8181, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8182, 'cinacalcet');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8183, 'cinacalcet');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8185, 'alpha amylase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8187, 'omega3 epa 400mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8187, 'dha 300mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8187, 'vitamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8187, 'vitamina');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8187, 'vitamind');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8189, 'l-histidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8189, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8189, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8189, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8190, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8190, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8190, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8190, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8190, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8190, 'lactiferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8191, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8191, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8192, 'dexlansoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8193, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8193, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8194, 'guava extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8194, 'tilia extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8194, 'black seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8195, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8195, 'anise oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8196, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8196, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8196, 'caviar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8196, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8196, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8196, 'hony');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8197, 'prazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'tocopheryl acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'vitis vinifera seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'bht');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'parfum coffea arabica seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'simmondsia chinensis seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'thymus vulgaris oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'olea europaea fruit oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'prunus amygdalus dulcis oil keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'hydroxypropyltrimonium hydrolyzed wheat protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'argania spinosa kernel oil triticum vulgare germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'aloe barbadensis leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'simethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8198, 'polysorbate 80');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8199, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8201, 'desmopressin acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8202, 'desmopressin acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8205, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8205, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8205, 'rutosid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8207, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8207, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8207, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8207, 'vitamin b 12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'piroctone olamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'garlic extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'olive extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'jojoba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'eurica extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8208, 'cetrimid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8209, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8210, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8212, 'ethylendiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8212, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8213, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8213, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8213, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8213, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8215, 'minoxidil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8218, 'eucalyptol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8218, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8218, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8218, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8219, 'lactobacillus reuteri');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8219, 'lactobacillus rhamnosus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8219, 'bifidobacterium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8219, 'fructose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'disodium phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'glycyrrhetinic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'mentha piperita oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'potassium sorbate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'eugenia caryophyllus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'aloe barbadensis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'sorbitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8220, 'parfum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8221, 'fenugreek seed (trigonella foenum-graecum seeds) 600 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8221, 'fennel seed (foeniculum vulgare seeds) 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8221, 'thyme leaf powder (thymus vulgaris seeds) 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8221, 'caraway seed powder (canim carvi seed) 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'thiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'riboflavin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'phosphorus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'molybdenum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8222, 'lycopene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'thiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'riboflavin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'phosphorus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'molybdenum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8223, 'potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8224, 'magaldrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8225, 'magaldrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8226, 'n-acetylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8226, 'bromelain extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8226, 'l-ascorbic acid (vitamin c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8226, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8227, 'lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8227, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8227, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8227, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8227, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8228, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8228, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8228, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8228, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8228, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8230, 'cdp');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8230, 'inulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8230, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8230, 'pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8230, 'zn bisglycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8231, 'chloramphenicol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8232, 'chloramphenicol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8234, 'thyme herb dry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8234, 'primrose root dry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8234, 'ivy leaf dry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8237, 'pemirolast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8238, 'mirtazapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'ricinus communis seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'microcrystalline wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'aloe vera leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'parfum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'chamomilla recutita -');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'chlorhexidine fruit oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'olea europaea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8242, 'simmondsia chinensis seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8243, 'mitoxantrone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8247, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8247, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8247, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8247, 'tolnaftate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8248, 'cholecalciferol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8250, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8250, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8250, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8251, 'insulin neutral human');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8251, 'insulin isophane protamine human');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'epa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'dha');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'omega 6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'gla');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'ala');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8254, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8255, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8255, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8258, 'meloxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'gotu kola');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'ginkgo');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8259, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8260, 'ursodeoxycholic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'oiyl panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'shea oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'beta sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'pumpkin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'coriander oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'capsicum oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'pistachio oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'omega 3 6 oils');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8261, 'marula oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8263, 'meloxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8264, 'citicoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8265, 'meloxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8266, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8266, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8266, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8267, 'alpha-lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8267, 'benfotiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8267, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8267, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8267, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8269, 'fluphenazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8270, 'fluphenazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8271, 'amiloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8271, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8272, 'mycophenolate mofetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8273, 'mycophenolate mofetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8274, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8277, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8277, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8278, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8278, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8280, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8280, 'miconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8280, 'mometasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8282, 'mometasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8286, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8286, 'collagen hydrolysate (marine)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8286, 'chondriotin sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8286, 'methyl sulfonyl methane(msm)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8286, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8288, 'hydrocortisone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8288, 'miconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8290, 'miconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8291, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8291, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8293, 'policresulen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8295, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8295, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8297, 'isosorbide-5-mononitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8298, 'isosorbide-5-mononitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8299, 'isosorbide-5-mononitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8300, 'fosinopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8301, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8302, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8305, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8305, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8305, 'salithylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8305, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8305, 'propylene ethanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8305, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8306, 'fosinopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8306, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8307, 'alpha arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8307, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8307, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8307, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8308, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8308, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8308, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8308, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8308, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8308, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8309, 'n-acetyl cysteine 300mg. glutathione 100mg. selenium 50mcg. vitamin c 64 mg. molybdenum 40mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8311, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8315, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8317, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8322, 'sertraline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8327, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8327, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8327, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8327, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8327, 'capsicium oleoresin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8330, 'domperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8332, 'morphine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8333, 'mosapride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8334, 'mosapride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8335, 'mosapride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8336, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8336, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8336, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8336, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8338, 'loratadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8339, 'loratadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8339, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8342, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8342, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8346, 'domperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8348, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8348, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8348, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8349, 'methyl cobalamine(b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8349, 'methyl folate(b9)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8349, 'pyridoxine(b6)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8350, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8350, '...');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8351, 'clove oil - hyaluronic acid - peppermint oil - thyme oil - honey extract - vit. e - cinnamon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8352, 'panthenol - sweet almond oil -jojoba oil - tocopherol ( vit e ) - glycerine - lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8354, 'domperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8355, 'ferrous fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8355, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8355, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8355, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8355, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8355, 'cyanocobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8356, 'l-carnitine 1000 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8356, 'coq 10 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8356, 'vitamin b5 5 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8359, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8359, 'alpha arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8359, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8359, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8359, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8360, 'fluphenazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8360, 'nortiptyline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8362, 'ivy leaves extract 50 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8362, 'n-acetyl-l-cysteine 50 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8362, 'zinc gluconate 13.065 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8362, '5 ml');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8365, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8365, 'chondrotoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8366, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8366, 'chondrotoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8367, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8367, 'chondrotoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8368, 'itopride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8371, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8372, 'meloxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8373, 'meloxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8375, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8376, 'ivy leaf extract (35 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8376, 'thyme leaf extract (21.5 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8376, 'licorice root extract (21.7 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8376, '5 ml');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'glucosamine (147.9 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'hydrolysed type ii collagen (150 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'vitamin e (20 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'chondroitin (40.93 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'ginger root extract (40 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'vitamin c (30 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'zinc (5 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'manganese (2 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'copper (0.5 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'folate (340 mcg dfe)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'selenium (60 mcg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'vitamin b12 (10 mcg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8377, 'vitamin d3 (400 iu)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8378, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8379, 'suta collagen marine 8.5 gm - calcium 1000 mg - magnesium - vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8380, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8381, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8381, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8381, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8381, 'vit.c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8382, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8384, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8385, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8385, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8385, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8385, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8386, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8386, 'vit.c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8386, 'vit.b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8386, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8386, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8386, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8388, 'alpha lipoic acid (300 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8388, 'vitamin b1 (100 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8388, 'vitamin b6 (25 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8388, 'vitamin b12 (500 mcg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8388, 'vitamin d3 (1000 iu) (25mcg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8393, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8393, 'solve oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8393, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8393, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8393, 'pomegranate extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8394, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8395, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8396, 'ambroxol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8399, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8400, 'ambroxol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8402, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8408, 'citicoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8409, 'ambroxol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8412, 'carbocysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8413, 'carbocysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8416, 'ambroxol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8420, 'rebamipide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8421, 'erdosteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8422, 'erdosteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8425, 'echinacea purpurea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (8427, 'vitamins');