INSERT INTO med_ingredients (med_id, ingredient) VALUES (20089, 'fennel oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20091, 'thyme extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20091, 'anise extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20091, 'guava extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20094, 'thyme');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20094, 'guava leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20094, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20094, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20095, 'guava leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20095, 'tilia leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20095, 'thyme leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20095, 'fennel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20097, 'thyme extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20097, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20097, 'clove oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20097, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20097, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20100, 'hyaluronic acid 5 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20100, 'lactic acid 225 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20102, 'hexoprenaline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20103, 'hexoprenaline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20104, 'tioconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20105, 'tioconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20107, 'lactobacillus reuteri');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'african mango');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'l-carnitine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'green coffee');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'raspberry ketone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'chromium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'green tea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'chicory root');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20108, 'cayenne pepper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'paraffinium liquidum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'clove oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'pepperment oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'thyme extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'cinnamon oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'apri oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'jasmin oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'pomegranate oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'canola oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'bha');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20109, 'isopropyl alcohol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20110, 'miconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20112, 'terconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20113, 'terconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20114, 'terconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20115, 'miconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20116, 'econazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20117, 'dienogest');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20118, 'probiotic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20118, 'vit.d3(400 i.u)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20120, 'lactase 3000 alu');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20121, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20121, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20125, 'miconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20127, 'tranexamic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20127, 'hyaluronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20127, 'ceramide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'amla oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'sweet almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'watercress oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'rosemary oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20129, 'lavender');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20130, 'tioconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'ferrous fumarate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'vitamins(b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'd');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'calcium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'linoleic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'linolenic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20133, 'manganese');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20134, 'ferrous fumarate(iron)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20134, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20134, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20135, 'plasma subistitute');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'copper gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'vit. b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'vit. b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'vit. b3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'vit. b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'vit. b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'vit. c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20136, 'zinc piclonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20137, 'blood-coagulation factor viii');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20138, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20139, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20140, 'acetic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20140, 'calcium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20140, 'magnesium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20140, 'potassium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20140, 'sodium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20142, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20143, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20144, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20145, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20146, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20148, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20149, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20150, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20151, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20152, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20153, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20154, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20155, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20156, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20157, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20158, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20159, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20160, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20161, 'haemodialysis solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20163, 'calcium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20163, 'magnesium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20163, 'potassium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20163, 'sodium acetate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20163, 'sodium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20164, 'warfarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20165, 'warfarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20166, 'warfarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20167, 'warfarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20168, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20170, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20171, 'vitamin k1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20172, 'vitamin k1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20173, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20175, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20176, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20177, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20177, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20179, 'ethamsylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20184, 'hydroxyethyl starch');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20185, 'hydroxyethyl starch');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20186, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20187, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'oleic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'shea butter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'eruca oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20188, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'zinc pyrithione');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'peg-7 glyceryl cocoate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20191, 'aloe vera extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20196, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20197, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'vitamins(a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'd3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'b12)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'pantothenic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'calcium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'phosphorus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'magnesium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'manganese');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'paba');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20199, 'coline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'nettle');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'rosemary');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'cyclomethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20204, 'dimethico');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'saw palmetto extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'rosemary extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20205, 'peppermint ext');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20209, 'd-panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20209, 'pilocarpine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20209, 'quinine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20210, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20211, 'zinc pyrithione');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20211, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20211, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20211, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20211, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'silicone oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'neem seed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'vit(a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'dimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20212, 'emu');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'ginkgo ex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'rosemary ex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'thyme ex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'lavender oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'vit(c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'peppermint oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20215, 'dimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20216, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20221, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20222, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20223, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20224, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20225, 'eribulin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'chamomile extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'bee propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'stearic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'cetyl alcohol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'paraffin oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20227, 'glyceryl mon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20228, 'haloperidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20230, 'haloperidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20232, 'haloperidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20237, 'haloperidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20238, 'haloperidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20239, 'cod liver oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20239, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20240, 'cod liver oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20240, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20240, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20240, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20240, 'lecithin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20242, 'cod liver oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20242, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20243, 'halothane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20245, 'halothane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20247, 'halothane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20248, 'halothane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20249, 'halothane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20251, 'tibolone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'collagen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'alpha arbutin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'vitamin a-c-e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'bearberry ext');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'benzophenone-3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'dead sea salts');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'licorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20252, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'niacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'lycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20253, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'sodium fluoride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'potassium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'peppermint extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'sodium bicarbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'triclosan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'peppermint oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20255, 'ca');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20259, 'allopurinol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20259, 'benzbromarone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20260, 'ledipasvir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20260, 'sofosbuvir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'kojic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'triclosan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'glycolic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'vit.(e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'a)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20262, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20263, 'carbamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20263, 'paraffinum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20263, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20264, 'kojic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20264, 'licuorice extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20264, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20264, 'glycolic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20264, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20264, 'titanium dioxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20265, 'vaccine hepatitis a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20266, 'vaccine hepatitis a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20267, 'dimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20267, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20268, 'benzathine penicillin g');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20270, 'fluocinolone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20270, 'hydroquinone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20270, 'tretinoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20271, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20272, 'phenytoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20273, 'rebamipide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20278, 'ofloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20279, 'hydrocortisone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20279, 'fucidic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20280, 'hydrocortisone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20280, 'fucidic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20281, 'felodipine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'water');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'liquid paraffin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'lanolin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'cetearyl alcohol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'glyceryl stearate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'benzyl alcohol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20282, 'peg-100 s');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'water');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'cetearyl alcohol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'liquid paraffin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'glyceryl stearate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'petrolatum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20283, 'ricinus communis (cas');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20284, 'rupatadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20285, 'green coffee');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20285, 'green tea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20285, 'garcinia cambogia');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20285, 'moringa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20286, 'minerals');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20286, 'vitamins');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20288, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20288, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20288, 'methyl salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20288, 'terpentine oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20289, 'capsaicin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20291, 'pegfilgrastim');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20292, 'cefuroxime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20293, 'cefuroxime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20294, 'cefuroxime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20295, 'cefixime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20296, 'cefixime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20297, 'cefixime');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20298, 'ciprofloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20299, 'ciprofloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20300, 'ciprofloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20301, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20302, 'thioctic acid(alpha lipoic acid)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20302, 'benfotiamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20302, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20303, 'bee propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20303, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20303, 'chamomile extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20303, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20307, 'clarithromycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20307, 'omeprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20307, 'tinidazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20312, 'ferric hydroxide polymaltose');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20313, 'aescin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20313, 'diethylamine salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'ferrous bisglycenate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'vitamin b1 3 6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20314, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20315, 'balsam peru');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20315, 'benzyl benzoate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20315, 'bismuth oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20315, 'bismuth subgallate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20315, 'hydrocortisone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20315, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20317, 'emicizumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20318, 'emicizumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20319, 'vitamin d');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20321, 'galactoarbinan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20321, 'aloe vera extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20321, 'glucoronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20322, 'pentosan polysulphate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20323, 'pentosan polysulphate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20324, 'hydroxyethyl starch');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20325, 'tranexamic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20326, 'tranexamic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20328, 'avocado soya bean extract 300 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20328, 'vitamin d3 1000iu');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20328, 'vitamin k2 90mcg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20328, 'boron 6 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20329, 'tranexamic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20330, 'tranexamic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20332, 'hepatitis b immune globulin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20333, 'entecavir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20334, 'entecavir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20335, 'l-ornithine-l-aspartate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20336, 'l-ornithine-l-aspartate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20338, 'acetylcysteine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20338, 'silymarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20339, 'silymarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20339, 'soya lecithin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20339, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20339, 'astragalus root pwd ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20339, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20339, 'l-selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20340, 'liver support formula');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'beta carotene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'vitamin b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'vitamin b3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'folate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'l-methionine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'lycopene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'acetyl-l-carnitine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'pumpkin seeds powder');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'co enzyme q10');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20342, 'l-glutathione');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20343, 'l-ornithine-l-aspartate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20344, 'ambroxol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20346, 'trypsin complex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20346, 'pancreatin(alpha amylase-alpha protease-alpha lipase)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20346, 'rutin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20346, 'papain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20346, 'bromelain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20347, 'cynara dry extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20348, 'heparin sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20349, 'heparin sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20350, 'heparin sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20351, 'chelidonium rhizome extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20351, 'curcuma extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20351, 'curcuma oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20352, 'cod liver oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'acetylcysteine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'silymarin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'vitamin(b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'methionine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'inositol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20353, 'whey protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20355, 'diclofenac sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20358, 'dietary supplement');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20359, 'adapalene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20360, 'ivy extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20361, 'ribavirin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20362, 'vaccine hepatitis b');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20363, 'ribavirin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20364, 'adefovir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20365, 'heptaminol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20366, 'yeast');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20367, 'heptaminol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'hydrolyzed keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'silicon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'dimethiconol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'amodimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'linseed');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'grape seed');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20368, 'aloe vera oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'saga oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'juniper oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'carrot oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'linseed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'sesame oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'sunflower oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'aloe vera extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20370, 'ca');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20372, 'tincture primula root');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20372, 'tincture thyme');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20372, 'tincutre pimpinella');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20372, 'tincture grindelia');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20372, 'tincture tilia');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20373, 'cascara sagrada');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20373, 'senna ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20373, 'herbal proprietary blend(fennel seed-licorice root-uva ursi leaves)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20375, 'calcium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (20375, 'vitamin d3');