INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32002, 'cinnamon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32003, 'lactobacillus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32003, 'bifidobacterium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32006, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32006, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32006, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32006, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32007, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32007, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32007, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32008, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'vitamins(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'b9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'zinv');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32010, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'vitamine c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'pomegranate extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'cetyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32011, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32012, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32012, 'magnesium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32017, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32018, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32019, 'vitamin c 100mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32019, 'citrus bioflavonoid complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32020, 'lactoferen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32020, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32020, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32020, 'vitc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32020, 'vit b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'rosemary extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'ginseng extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'saw palmetto extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32021, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'sorbitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'eucalyptol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32022, 'sodium saccharin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32023, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32024, 'methyl sulphonyl methane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32025, 'probiotic bacteria');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32026, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32028, 'glucose 40%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32028, 'carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32028, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32029, 'esketamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32030, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32030, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32031, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32031, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32037, 'azithromycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32038, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32039, 'siponimod');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32040, 'glucosamine sulpate-condroitin sulphate-methysulfonylmethan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32041, 'agar agar extract 1165 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32042, 'silicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32044, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32044, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32044, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32044, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32045, 'vit b1(thiamin hcl)100mg&vit b6(pyridoxin hcl) 50mg&vit b12(cyanococobalamin)1000mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'vitamins(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'l-lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32046, 'malt extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32047, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32048, 'liposomal vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32049, 'brivaracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32050, 'brivaracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32052, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32053, 'activated charcoal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32054, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'sodium fluoride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32055, 'peppermint flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32056, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32056, 'thyum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32056, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32057, 'palonosetron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32058, 'glucosamine .collagen. chondroitin .vit d. vit c .b12 .vit e .ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32059, 'iron-folic acid- vitb12 -vitb6-copper-zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32060, 'calcium-vitd3 ï¿½ magnesium- manganese- boron-selenium- copper-zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'calendula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32061, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'sericin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'sodiumhyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'polymethylsilsesquioxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'tocopheryl acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32062, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'jasmine fragrance');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32063, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32064, 'linezolid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'vitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'ethylhexy1 methoxycinnamate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'benzophenone-4');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32065, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32066, 'bovine lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32067, 'avobenzone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32067, 'octocrylene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32067, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32067, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32068, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32070, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32070, 'magnesium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32070, 'simethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32071, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32071, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32072, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32073, 'alpha lipoic acid 600 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32074, 'glucosamine 500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32074, 'chandroitin400mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32074, 'm.s.m 400mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32075, 'chlorhexidine-mentol-clove oil- green tea-honey vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'tranexamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32076, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'procapil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'saw palmetto extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'linolenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32077, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32078, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32079, 'myo-inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32079, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32080, 'iron pyrophosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32080, 'vit b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32080, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32080, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32080, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32081, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32082, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32082, 'magnisium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32082, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32082, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32085, 'trypsin 2500 mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32085, 'chymotrypsin 400 mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32085, 'pancreatin 300 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32085, 'bromelain 135 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32085, 'papain 180 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32085, 'rutin 150 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32086, 'magnesium glycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32087, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32087, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32087, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32087, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32088, 'evening primrose oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32088, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32089, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32089, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32090, 'diosmin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32091, 'cyanocobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32092, 'calcium ascorbate 500 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32092, 'zinc gluconate 15 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32093, 'melatonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32094, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32094, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32094, 'methyl sulphonyl methane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32095, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32095, 'licorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32095, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32095, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32095, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32096, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32096, 'rose oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32096, 'chamomil ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32096, 'aloe vera ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32096, 'malva sylvestris ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32096, 'calendula officinalis ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32097, 'cod liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32098, 'guava leaves extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32098, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32098, 'tilia flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32099, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'calendula oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32100, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32101, 'palmitoylethanolamide(pea)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32102, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32102, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32102, 'retinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32102, 'sulfur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32103, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32103, 'calamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32104, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32104, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32104, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32105, 'acetylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32106, 'vonoprazan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32107, 'liposomal vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32107, 'liposomal vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32107, 'liposomal vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'ginko biloba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'rosemary extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32108, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'saw palmetto extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'ginko biloba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'ginseng extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'royal gelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'rosemary extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'clove extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'jojoba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32109, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32110, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32110, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32110, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32110, 'aloevera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32110, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32111, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32111, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32112, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32113, 'myo-inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32113, 'd chiroinositol-methylfolate-chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32114, 'water for injection');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32115, 'ivy leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32115, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32115, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'elemental iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'vitamins (b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'b6)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32116, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'saw palmetto extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'lycopene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'stinging nettle root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'ginger root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32117, 'quercetin dihydrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32118, 'cloperastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32120, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32121, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32122, 'vancomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32123, 'rifaximin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'alpha keto analog of(l-isoleucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-leucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-phenylalanine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-valine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-methionine)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-threonine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-tryptophan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-histidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32124, 'l-tyrosine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'sage');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32125, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'aloe vera leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32126, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32127, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32129, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32129, 'travoprost');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32131, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32132, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32132, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32132, 'follic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32132, 'vit. c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32132, 'vit. b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32132, 'cooper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32133, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32133, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32133, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32134, 'silicone oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32134, 'onion ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32134, 'chamomile ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32134, 'aloe vera ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32134, 'hydro elastomer carpylyl methicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32135, 'pancreatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32135, 'papain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32135, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32135, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32135, 'alpha chymotrypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32135, 'sophora japonica');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'coq10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32136, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32137, 'duloxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32138, 'hayaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32138, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32138, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32138, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32139, 'calcium gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32139, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32139, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32140, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32141, 'ivy leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32142, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32143, 'cetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32144, 'cyclopentolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32145, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32147, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32150, 'ondansetron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32151, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32151, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32151, 'phosphorous');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'vitis vinifera (grape) seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'tocopheryl acetate (bitamin e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'macadamia ternifolia seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'lavandula angustifolia oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'helianthus annuus (sunflower) seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'persea gratissima (avocado) oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'prunus amygdalus dulcis (sweet almond) oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'argania spinosa kernel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32152, 'squalane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32153, 'lactobacillus plantarum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32154, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32154, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32154, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32154, 'emu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32154, 'aranica');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32154, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'zinc 5%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'vit a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'camphore');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32155, 'tea oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32156, 'dapoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32157, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32157, 'artichoke');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32157, 'chacorea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32158, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32158, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32158, 'chamomile ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32159, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32159, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32159, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32159, 'allantoin');