INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1856, 'calcium-vitamin d3 400 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1857, 'calcium carbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1857, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1858, 'calcium-vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1859, 'calcium levulinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1859, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1859, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1860, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1861, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1861, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1861, 'povidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1863, 'calcium-vitamin b12-vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1865, 'calcium-vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1868, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1870, 'alfacalcidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1871, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1871, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1871, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1871, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1872, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1874, 'panthenol. stearic acid. glycerin. chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1876, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1877, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1878, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1878, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1879, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1880, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1880, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1881, 'carbomer. glycerin. thymol. propylene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1882, 'apixaban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1883, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1884, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1884, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1884, 'onion extract ( allium cepa )');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1884, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1886, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1886, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1887, 'calciporiol -betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1888, 'biperidene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1889, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1889, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1889, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1889, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1890, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1890, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1891, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1891, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1892, 'calcitonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'aloe vera leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'olea europaea fruit oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'melaleuca alternifolia leaf oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'rosa canina fruit oil. glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'recutita chamomile flower extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'simmondsia chinensis seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'citrus seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'carica papaya fruit extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'camellia sinensis leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'retinyl palmitate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1894, 'liquid paraffinum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1895, 'amino acids chelated minerals with vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1896, 'alpha amylase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1898, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1899, 'b12. b1. b6. b2. d3. folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1900, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1904, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1904, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1906, 'calcium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1907, 'lactobacillus rhamnosus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1907, 'lactobacillus reuteri');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1909, 'insulin glargine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1912, 'calcium levulinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1912, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1912, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1913, 'alpha amailse');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1914, 'echinacea - black elderberry -zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1916, 'iron folic acid zinc vitamin c copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1917, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1917, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1917, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1917, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1921, 'heparin calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1922, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1922, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1922, 'rutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1923, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1923, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1923, 'chondroitin sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1923, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1924, 'calcium carbonate 1250 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1924, 'vitamin d3 400 i.u');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1925, 'ivy extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1926, 'n-acetylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1926, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1926, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1926, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1928, 'loperamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1928, 'simethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1930, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1930, 'green coffee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1930, 'saga');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1930, 'fennel seeds');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1931, 'garcinia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1931, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1932, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1932, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1933, 'caraway oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1933, 'dill oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1933, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1934, 'chlorpheniramine-paracetamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1935, 'bromazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1936, 'bromazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1937, 'ivy ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1937, 'thyme ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1937, 'licorice ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'thiamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'riboflavin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'lodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1938, 'lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1939, 'dill oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1939, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'dexpanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1946, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1947, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1948, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1948, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1948, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1949, 'piracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1949, 'ginkgo');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1949, 'meclofexonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1949, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1949, 'vit.b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1950, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1950, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1951, 'omega');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1951, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1951, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'arachis hypogaea oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1952, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'vitamin(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1955, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1957, 'ondansetron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1958, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1959, 'eucalyptus globe leaf oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1959, 'mentha piperita oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1959, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1959, 'eugenia caryophyllus bud oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1959, 'menthol zeylanicum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1959, 'cinnamon bark oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1961, 'luspatercept');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1962, 'irinotecan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1963, 'irinotecan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1964, 'luspatercept');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1965, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1968, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1970, 'bevacizumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1972, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1972, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1974, 'bevacizumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1975, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1976, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1977, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1981, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1981, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1981, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1981, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1981, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1983, 'isoconazole nitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1984, 'isoconazole nitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1985, 'calcium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1985, 'magnesium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1985, 'vit. d3 1000 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1985, 'vit. k2 - mk7 25 mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1986, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1987, 'activated charachol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1987, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1988, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1988, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1988, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1988, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1988, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1989, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1990, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1991, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1992, 'fluconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1994, 'cherry');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1996, 'honey-lemon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1997, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2003, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2004, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2004, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2004, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2004, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2005, 'ana syllium 14 sachets 390 psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2005, 'pineapple flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2005, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2005, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2006, 'cetylpyridinium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2006, 'chlorocresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2006, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'malt extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2008, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2009, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2011, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2012, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2013, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2017, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2017, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2019, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2020, 'sulfur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2020, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2020, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2021, 'capsaicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2021, 'curcumin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2022, 'vitamin d3 400 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2022, 'drop');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2023, 'capsaicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2024, 'capsaicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2025, 'capsaicin methylsalicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2026, 'spirulina');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2027, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2030, 'carbamazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2032, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2032, 'pineapple flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2032, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2032, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2033, 'carbamazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2034, 'carbamazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2035, 'carbamazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2037, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2037, 'pineapple flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2037, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2037, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2038, 'carbamazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2039, 'carbimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2040, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2040, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2043, 'carboplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2044, 'carboplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2045, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2045, 'benfotiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2045, 'pyridoxine hcl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2045, 'cyanobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2045, 'cholecalciferol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2048, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2049, 'carboplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2050, 'carboplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2053, 'isosorbide dinitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2054, 'dexlansoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2055, 'fresh ivy powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2055, 'fresh thyme liquid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2055, 'licorice liquid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2058, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'collagen oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'sesamum indicum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2064, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2065, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2066, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2067, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2067, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2067, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2068, 'multivitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2069, 'torsemide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2070, 'cratageus (hawthorn) extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2072, 'dexrazoxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2073, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2073, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2075, 'acetylsalicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2076, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2076, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'fennel fruit extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'peppermint extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'anise extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'd-alpha tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'vitamind3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2084, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2086, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2087, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'benzalkonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2091, 'lercanidipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'pdms (polysiloxane)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'onion oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2093, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2094, 'tizanidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2097, 'potassium sodium hydrogen citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2098, 'eplerenone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2099, 'eplerenone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2101, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2103, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2104, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2104, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2105, 'caraway oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2105, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2105, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2106, 'caraway oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2106, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2106, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2107, 'phenazopyridine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2107, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2109, 'vitamin d3 4000 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2111, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'raspberry ketone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'garcinia cambogia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'green coffee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'caffeine anhydrous');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2115, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2115, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2115, 'vitamin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2117, 'l-carnitine l-tartrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2117, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'avobenzone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'homosalate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'octisalate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'octocrylene. oxybenzone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'green tea leaf extract (aqueous). cucumber extract (aqueous)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'tocopheryl acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'cetostearyl alcohol ceteareth-20');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'isopropyl myristate monopropylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'apricot oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2123, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2123, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2123, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2124, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2124, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2124, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2127, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2128, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2129, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2129, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2130, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2131, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2132, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2133, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'eugenia caryophyllus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'mentha piperita');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'chlorhexidine digluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'sodium saccharine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'myrtrimonium bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'sodium benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'benzoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'zinc chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2137, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2140, 'phenol-basicfuchsine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2142, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2143, 'besifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2144, 'lactobacillus rhamnoses gg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'zinc pyrithion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2148, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'clove extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2150, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2151, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2153, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2154, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2155, 'pirenoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2156, 'pirenoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2157, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'mineral oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'eurica oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'myrestic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'r');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2159, 'betasitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2160, 'vitamin d (cholecalciferol) vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'rutin');