INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'aloe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'chamomil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25378, 'panthe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'oil comb (grape seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'almond');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'paraffin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25379, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'oil comb (grape seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'almond');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'paraffin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25380, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'oils(silicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'cedar wood');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'almond');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'grape seed)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25381, 'ginseng ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'oils(silicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'cedar wood');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'almond');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'grape seed)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25382, 'ginseng ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'saw palmetto extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'ginkgo');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25383, 'vitamin c&e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25384, 'pygeum africanum extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25384, 'pumpkin seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25384, 'saw palmetto oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25384, 'tomato extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25384, 'uva ursi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25386, 'pygeum africanum extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25387, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25387, 'pygeum africanum extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25388, 'bear berry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25388, 'pumpkin seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25388, 'pygeum africanum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25388, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25388, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25388, 'zinc gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25389, 'hamamelis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25389, 'ichtammol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25389, 'potassium iodide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25390, 'pumpkin seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25390, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25390, 'lycopene extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25391, 'saw palmetto berry powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25391, 'pygeum resinous waxy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25391, 'stinging nettle powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25391, 'zinc gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25392, 'serenoa repens purified extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25393, 'saw palmetto ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25393, 'nettle powder ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25394, 'terazocin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25395, 'terazocin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25397, 'alprostadil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25398, 'pumpkin seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25398, 'saw palmetto oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25398, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25398, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25399, 'finasteride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25400, 'alfuzosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25401, 'neostigmine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25402, 'dutasteride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25403, 'finasteride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25404, 'protamine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25405, 'protamine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25406, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25406, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25406, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25406, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25406, 'strawberry flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25407, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25408, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25408, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25408, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25408, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25408, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25408, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25409, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25409, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25409, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25409, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25409, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25409, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25410, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25410, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25410, 'coconut diethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25410, 'edta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25410, 'sodium lauryl ether sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25411, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25411, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25411, 'coconut diethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25411, 'edta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25411, 'sodium lauryl ether sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25412, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25412, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25412, 'coconut diethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25412, 'edta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25412, 'sodium lauryl ether sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25413, 'oxiconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25414, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25415, 'indapamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25415, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25416, 'ethyl alcohol 96%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25417, 'strontium ranelate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25418, 'dothiepin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25419, 'dothiepin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25420, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25420, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25420, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25421, 'whey protein 70%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25421, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25421, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25421, 'immunoglobulins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25421, 'bioactive fractions');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25421, 'cytokines');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25422, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25422, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25422, 'bovine colostrum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25422, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25422, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'vitamins(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'phosphorous');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25423, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25424, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25425, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25426, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25427, 'dexlansoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25429, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25430, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25431, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25432, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25434, 'tacrolimus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25435, 'nitazoxanide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25437, 'tinidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25438, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25438, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25438, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25438, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25438, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25438, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25439, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25440, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25441, 'medroxyprogesterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25442, 'mesterolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25443, 'mesterolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25444, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25445, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'vitamins(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'calcium gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25447, 'calcium phospholactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25448, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25448, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25449, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25449, 'fructose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25449, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25449, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25449, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25449, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'acetyl-l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'n-acetyl cysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25450, 'beta-carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'propionyl-l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'maca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'cocoa extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'nicotinic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'acetyl-l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25451, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25454, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25455, 'prucalopride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25458, 'dithranol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25459, 'acitretin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25460, 'acitretin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25461, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25462, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25462, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25463, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25463, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25464, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25465, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25466, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25467, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25468, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25469, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25470, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25471, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25471, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25472, 'escitalopram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25473, 'escitalopram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25474, 'hypericin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25475, 'psyllium husk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25475, 'pineapple extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25475, 'apple extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25475, 'grapefruit extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25476, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25477, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25479, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25480, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25481, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25482, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25484, 'bosentan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25485, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25485, 'dextromethorphan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25485, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25485, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25486, 'ammonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25486, 'chlorpheneramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25486, 'guaiphensin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25486, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25486, 'tolu syrup');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25486, 'syrup pectoral');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25487, 'ambroxol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25488, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25489, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25491, 'etodolac');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25492, 'etodolac');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25493, 'citalopram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25494, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25494, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25494, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25494, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25497, 'follitropin beta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25498, 'follitropin beta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25499, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25499, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25499, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25499, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25499, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25499, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25500, 'calcium sennosid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'glycerol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'propylbetaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25501, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25502, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25503, 'purified water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25505, 'mercaptopurine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25506, 'allopurinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25508, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25509, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25511, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25512, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25512, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25513, 'dalfampridine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'eucalyptol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'guaiacol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'pholcodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25515, 'pyrazinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25516, 'pyrazinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25518, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25519, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25520, 'pyridostigmin bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'rosemary ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25522, 'coenzyme q-10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25523, 'coenzyme q-10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25524, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25525, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'tolnaftate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'ethambutol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'isoniazid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'pyrazinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'rifampicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25528, 'cholestyramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25529, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25530, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25530, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25530, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25531, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25532, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25533, 'dorzolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25534, 'dorzolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25534, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'soybean oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'seasame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25538, 'cholestyramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25539, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25540, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25541, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25542, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25543, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25544, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25545, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25546, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25547, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25549, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25550, 'ofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25551, 'gemifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25552, 'gemifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25553, 'quinidine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25554, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25555, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25556, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25557, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25558, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25559, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25560, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25561, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25562, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25564, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25565, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25566, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25567, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25568, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25569, 'ombitasvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25569, 'paritaprevir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25569, 'ritonavir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'light liquid paraffin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'isopropyl myristate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'polyethylene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'silica');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'dimethicon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'magnesium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'bee pollen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'korean ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25601, 'irgasan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25601, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25601, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25602, 'fenugreek');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25602, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25602, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25606, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25606, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25607, 'rabeprazole sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25608, 'rabeprazole sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25612, 'rabies vaccine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25614, 'rabies vaccine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25615, 'racecadotril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'salicylates');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'camphor oil white');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'capsicum oleoresin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'camphor oil white');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'capsicum oleoresin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'condrotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'calcium phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'astaxinthin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25621, 'leflunomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25622, 'leflunomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25623, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25623, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25623, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'glucosamine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'chondroitin sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25625, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25625, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25628, 'fluoxetine');