INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'ginseng extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'polyquaternium-67');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'polyquaternium-7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'caffiene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32997, 'sophora angus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32998, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32998, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32998, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'cyclopentasilxan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'silicone oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32999, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33002, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33002, 'lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33002, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33002, 'vitaminb1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33002, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33002, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33003, 'amino acid chelate iron 28mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33003, 'vit b12 8mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33003, 'folic acid 400mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33003, 'vit c 60mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33005, 'ferrous bisglycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33005, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33005, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33005, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33007, 'ferrous bisglyicinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33007, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33009, 'cinnamon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33012, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33012, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33012, 'ceramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33015, 'ivy leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33015, 'liquorice root');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33015, 'thyme herb');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33015, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33018, 'ivy leave extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33018, 'alpha hederin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33021, 'benzoyl broxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33021, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33021, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33022, 'ceramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33022, 'panthinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33022, 'shea putter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33022, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33023, 'digestive enzymes :lactase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33023, 'amylase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33023, 'protase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33023, 'lipase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33023, 'alpha - galact');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33023, 'hemicellulase. osidase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'vit. d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33025, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'vit. d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33026, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33028, 'probiotics');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33028, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33028, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33029, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33029, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33033, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33033, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33035, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33035, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33035, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33035, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33035, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'collagen peptides type ii');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33036, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33038, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33038, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33038, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33038, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33038, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33042, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33042, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33042, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33045, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33046, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33047, 'sodium hyalornate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33048, 'sodium hyaluronate 120mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'beta-sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'saccharide isomerate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'oryza sativa oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'butyrospermum parkii butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'boswellia serrata extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'quercetin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'ricinus communis seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'nigella sativa seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'pomegranate oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33049, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'mandelic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33052, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33057, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33057, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33057, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33057, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33074, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33075, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33076, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33077, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33078, 'agar extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33079, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33079, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33079, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33079, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33079, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33079, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33080, 'cefaclor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33082, 'hpa pure lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33085, 'omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33085, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33085, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33085, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33086, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33089, 'sodium picosulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33092, 'liposomal iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33092, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33092, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33093, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33093, 'chondroitin sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33093, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33093, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33093, 'collagen type ii');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33093, 'turmeric extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33094, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33095, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33101, 'panthenol 2%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33102, 'ivy leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33102, 'glycyrrhiza');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33102, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33103, 'scilicon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33103, 'probiotics');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33103, 'collagen. onion extract. vit e. vit a.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33105, 'omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33105, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33105, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33105, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33109, 'pitavastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33110, 'pitavastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33111, 'l-lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33113, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33113, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33113, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33113, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33114, 'mentol crystal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33114, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33114, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33121, 'lornoxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33122, 'lornoxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33125, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33125, 'losartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33131, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33142, 'collagen 10.5 gm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33142, 'calcium 1000 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33142, 'vitamins d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33142, 'vitamins c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33143, 'bicalutamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33145, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33148, 'warfarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33161, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33162, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33165, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33165, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33165, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33165, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33165, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33166, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33166, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33166, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, '6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'boswellic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'curcmin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'rosemary extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33169, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'chlorohexidine digluconat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'propolis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'alovera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33170, 'panthinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'calcium bis glycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'magnesium bis glycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'vit k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'vit. c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33171, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33175, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33179, 'fenugreek seeds extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33179, 'caraway seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33179, 'fennel seeds');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33179, 'thyme leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33179, 'dill seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33180, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33180, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33180, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'pomegranate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'cetyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'butylenes glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33188, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33189, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33189, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33189, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33189, 'salix ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33189, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33189, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33194, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33195, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33196, 'metformin hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33198, 'methotrexate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33203, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33205, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33205, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33205, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33205, 'vit k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33207, 'ca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33207, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33207, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33209, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33209, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33209, 'vitamin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33209, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33210, 'minoxidil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33212, 'mirtazapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'gotu kola');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'ginkgo');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33215, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33216, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33216, 'horse chestnut');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33216, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33216, 'lemon grass oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33216, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33216, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33217, 'cranberry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33217, 'probiotic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33217, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33219, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33219, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33221, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33223, 'ferrous bisglycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33230, 'cyclobenzaprine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'hydrolyzed marine collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'boswellia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33231, 'l-methionine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33232, 'winter green oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33232, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33232, 'bosouilla extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33232, 'mental');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33232, 'eculaptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33236, 'infant milk formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33244, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33247, 'myoinositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33250, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33251, 'naproxen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33255, 'fluconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33256, 'ivy leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33256, 'licorice root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33256, 'thyme leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33257, 'hypo-allergenic milk formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33259, 'brexpiprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33260, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33260, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33261, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33261, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33262, 'azithromycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-histidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-isoleucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-leucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-methionine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-phenylalanine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-threonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-tryptophan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-tyrosine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33263, 'l-valine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33264, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33267, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33267, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33267, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33268, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33268, 'benfotiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33268, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33268, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33268, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33268, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33269, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33269, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33269, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33270, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33270, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33270, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33270, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33271, 'agar-agar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33272, 'nepafenac');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33274, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33284, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33284, 'keratin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33284, 'almond');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33284, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33284, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33284, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33285, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33285, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33285, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33285, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33285, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33285, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33287, 'melatonin 5mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33287, 'vitamin b6 1.2 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33291, 'oxymetazoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33292, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33292, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33292, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33292, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33292, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33295, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33295, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'octetinidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'eucalyptol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33304, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33307, 'omega 3 fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33317, 'high dha fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33317, 'omega 6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33317, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33317, 'thymol oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33318, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33318, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33319, 'omega 3 fish oil 1000');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33319, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33319, 'lemon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33323, 'high purified omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33323, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33323, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33323, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'omega-3 fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33324, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33325, 'omega-3 fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33325, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33327, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33328, 'fish oil 400 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33328, 'flax seed oil 400 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33328, 'borage seed oil 400mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33328, 'vit e 30mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33330, 'tea tree');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33330, 'zinc gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33330, 'citrus(lemon)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33330, 'others');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33335, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33335, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33336, 'hydrocortisone acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33339, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33340, 'l-ornithine-l-aspartate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33341, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33341, 'hayaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33341, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33341, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33341, 'cholorohexidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33342, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33342, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33342, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'mint flavor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'poloxamer407');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'sodium phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'fluride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33343, 'benzoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'glucosamine sulphate 2kcl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'chondroitin sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'methyl sulfonyl methane(msm)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'collagen (type 2) hydrolysed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'ginkgo biloba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33349, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33353, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33353, 'co-enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33353, 'myo-inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33353, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33353, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33356, 'oxaliplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33357, 'oxaliplatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33359, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33359, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33359, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33359, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33359, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33359, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33361, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33361, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33361, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33361, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33361, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (33361, 'selenium');