INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'magnesium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'manganese');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13449, 'boron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13451, 'vitamin d');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13452, 'agar agar powder');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13453, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13453, 'olmesartan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13454, 'niacinamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13454, 'collagen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13455, 'acyclovir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13456, 'stearic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13456, 'beeswax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13456, 'camphor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13456, 'fennel oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13456, 'methylparaben');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13457, 'acyclovir');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13458, 'adapalene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13459, 'nifedipine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13460, 'citicolin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13461, 'amantadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13462, 'beta-sitosterol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13463, 'nicorandil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13464, 'adapalene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13466, 'adapalene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13467, 'gabapentin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13468, 'gabapentin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13469, 'ezetimibe');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13469, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13470, 'brentuximab vedotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13471, 'urea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13471, 'liquid paraffin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13471, 'glyceryl monostearate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13471, 'propylene glycol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13472, 'urea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13472, 'liquid paraffin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13472, 'glyceryl monostearate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13472, 'propylene glycol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13473, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13474, 'clindamycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13475, 'clindamycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13476, 'clindamycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13478, 'vitamin k1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13479, 'vitamin k1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13480, 'neomycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13480, 'polymyxin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13482, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13485, 'tilbroquinol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13485, 'tiliquinol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13485, 'tiliquinol lauryl sulphate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13488, 'adenosine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13488, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13495, 'dextromethorphan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13495, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13495, 'pseudoephedrine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13496, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13496, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13501, 'polyhexamethylene biguanide (phmb)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13501, 'sodium edetate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13501, 'isotonic solution');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13502, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13503, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13504, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13506, 'adrenaline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13507, 'tetracosactide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13510, 'doxorubicin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13511, 'doxorubicin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13512, 'atorvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13513, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13513, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13513, 'eucalyptus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13513, 'pepperment oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13513, 'stearic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13513, 'methyl paraben');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13514, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13515, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13516, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13517, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13518, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13519, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13520, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13521, 'tacrolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'sulphur');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'lemon oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'citric acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'boric acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'titanium dioxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'thyme');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'clove');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'lanolin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13522, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13525, 'chlorpheniramine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13525, 'dextromethorphan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13525, 'paracetamol(acetaminophen)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13525, 'pseudoephedrine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13526, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13527, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13528, 'piperacillin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13528, 'tazobactam');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13529, 'amikacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13530, 'betahistine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13531, 'fluconazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13537, 'diclofenac potassium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13539, 'diclofenac diethylamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13539, 'methyl salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13539, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13541, 'moxifloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13543, 'mucopolysacharide polysulfuric acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13543, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13544, 'mecobalamin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13545, 'vitamin b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13545, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13545, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13550, 'povidone- iodine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13552, 'duloxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13555, 'duloxetine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13557, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13557, 'valsartan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13558, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13558, 'valsartan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13559, 'desloratadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13560, 'salbutamol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13561, 'ipratropium bromide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13561, 'salbutamol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13562, 'isoflurane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13563, 'polidocanol=lauromacrogol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13564, 'polidocanol=lauromacrogol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13565, 'everolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13566, 'everolimus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13567, 'oxymetazoline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13568, 'oxymetazoline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13569, 'thioctic acid(alpha lipoic acid)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13569, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13569, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13569, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13569, 'ginko biloba');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13569, 'bacopa extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13570, 'methylcobalamin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13570, 'benfotiamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13570, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13571, 'ors');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13572, 'hyaluronan sodium salt');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13573, 'hyaluronan sodium salt');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13574, 'hyaluronan sodium salt');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'ginger');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'anise');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'bromelain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'fennel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'peppermint');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13575, 'papain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'ginger');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'anise');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'bromelain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'fennel');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'peppermint');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13576, 'papain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13578, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13578, 'hydroxytyrosol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13578, 'shea butter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13579, 'acetyl hexapeptide-3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13579, 'pseudoalteromonas ferment extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13579, 'ascorbyl palmitate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13579, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13579, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13579, 'glycer');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'nicotiamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'tee tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'aloe vera extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'aha');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'bha');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13580, 'uv filter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13582, 'etoricoxib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13583, 'semaglutide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13586, 'agomelatine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13587, 'sertraline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13589, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13590, 'esomeprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13591, 'esomeprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13593, 'minoxidil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13594, 'erenumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13595, 'calcium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13596, 'metformin hydrochloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13596, 'vildagliptin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13598, 'l-arginine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13598, 'menthol crystals');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13598, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13598, 'aloe vera extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13598, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13598, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13599, 'biperidene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13600, 'menthol crystal');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13600, 'clove oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13600, 'peppermint oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13600, 'camphor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13600, 'vit e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13600, 'paraffin oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13601, 'sildenafil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13602, 'collagen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'liquorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'kojic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'alpha arbutin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'vitamin (c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'b)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'glycolic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13603, 'sali');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13604, 'probiotics');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13605, 'omega 3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13607, 'whitening formula');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'oils(argan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'pumpkin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'eruca');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'nigella sativa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'mustard)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'ginseng');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13609, 'vit.e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'oils(argan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'pumpkin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'eruca');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'nigella sativa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'mustard)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'ginseng');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13610, 'vit.e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'thyme');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'liquorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13611, 'salicylic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'black seed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'eruca sativa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'salicylic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'sulfur');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13612, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'liquorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'vitamin(e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'a)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'thyme');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'rosemary');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13613, 'peppermint oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'castor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'bht');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'bees wax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'octyl stearate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13614, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13615, 'netupitant');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13615, 'palonosetron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13616, 'vonoprazan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13617, 'piroctone olamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13617, 'dimethicone copolyol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13617, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13617, 'cocamidopropyl betaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13617, 'citric acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13618, 'piroctone olamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13618, 'dimethicone copolyol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13618, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13618, 'cocamidopropyl betaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13618, 'citric acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13619, 'olanzapine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13620, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13620, 'calendula extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13620, 'chlorhexidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13620, 'paraffin oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13623, 'albendazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13624, 'albendazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13625, 'arbutin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13625, 'oligopeptide-34');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13625, 'hydrolyzed soy protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13625, 'vitamin e acetate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13625, 'tinosorb s');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13627, 'etoricoxib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13628, 'etoricoxib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13629, 'dapagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13630, 'dapagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13632, 'human albumin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13633, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13634, 'candesartan cilexetil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13634, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'glucoseaminesulfate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'chondrotinsulfate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'methyl sulphonyl methane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'ginger root extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'liquorice root extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'boswellia extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'cats claw extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'devil claw extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'turmeric root powder');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13635, 'noni juice powder extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13637, 'alcaftadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13638, 'melatonin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13640, 'n-pentane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13640, 'iso-butane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13640, 'propane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13640, 'n-butane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13640, 'denatured ethanol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13640, 'levomenthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13642, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13644, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13644, 'spironolactone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13646, 'hypertonic seawater');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13647, 'imiquimod');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13648, 'green coffee ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13648, 'garcinia cambogia');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13648, 'green tea ext.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13648, 'ashwaganda');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13650, 'alectinib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'caffein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'oil(oliv');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'wheatgerm');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'jojoba)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'ginkgo biloba');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'aloe');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13653, 'rosemary');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'oil(ginseng');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'garlic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'argan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'castor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'emu)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'vit(b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'b3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'caffein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13654, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'collagen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'oils(argan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'black seed');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'emu)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'ginkgo');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13655, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13660, 'd-aspartic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13660, 'coenzyme q10');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13660, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13662, 'diclofenac diethylamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13663, 'bromelain');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13663, 'rutoside');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13663, 'trypsin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13665, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13669, 'desloratadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13670, 'desloratadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13671, 'rupatadine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13672, 'cetirizine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13673, 'chondroitin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13673, 'glucosamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13673, 'methyl sulphonyl methane');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13677, 'levetiracetam');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'royal jelly');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'bee propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'vitamins(b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'b3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'b5');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'b7');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'b9');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'd');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13680, 'e)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13681, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13681, 'ethamivan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13682, 'myo-inositol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13682, 'd-chiro-inositol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13682, 'methyl folate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13682, 'co q10');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13682, 'alpha lactalbumin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13683, 'articaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13683, 'adrinaline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13684, 'articaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13684, 'adrinaline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13685, 'levofloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13686, 'camphor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13686, 'menthol crystals');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13686, 'eucalyptus oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13686, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13688, 'amiodarone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13689, 'gentamicin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13690, 'carbamide(urea)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13692, 'metformin hydrochloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13694, 'lacosamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13695, 'calcium bisglycinate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13695, 'vitamin k2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13695, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13696, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13696, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13696, 'magnesium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13698, 'simethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13701, 'alfacalcidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13702, 'alfacalcidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13703, 'alfacalcidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13704, 'alfacalcidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13706, 'calcium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13706, 'magnesium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13706, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13706, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13708, 'lactium-150 (milk protein hydrolysate-alpha-casozepine)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13708, 'whey protein isolate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13709, 'cyclizine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13710, 'calcium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13712, 'ascorbic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13712, 'liquorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13712, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13712, 'beri beri extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13714, 'clindamycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13715, 'clindamycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13716, 'clindamycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13717, 'b complex iron biotin vit a folic acid vit c se mn cal');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13718, 'alprostadil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13723, 'probiotic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13724, 'alfuzosin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13725, 'betamethasone valerate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13727, 'ivermectin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13727, 'lactic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13727, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13727, 'zinc pyrithione');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13727, 'eugenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13730, 'pure aloe vera gel (aruban aloe barbadensis)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13730, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13730, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13730, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13731, 'pure aloe vera gel (aruban aloe barbadensis)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13731, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13731, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13731, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13733, 'pemetrexed');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13734, 'piroctone olamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13734, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13734, 'rosemary oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13734, 'chamomile oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13734, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13734, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13736, 'alprazolam');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13740, 'potassium sodium hydrogen citrate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13741, 'borax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13741, 'sodium bicarbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13741, 'sodium chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13749, 'amlodipine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13751, 'amlodipine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13751, 'valsartan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13754, 'amlodipine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13754, 'hydrochlorothiazide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13754, 'valsartan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13756, 'aluminium hydroxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13756, 'dimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13756, 'magnesium oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13757, 'acetylsalicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13757, 'aluminium glycinate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13757, 'magnesium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13763, 'ezetimibe');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13763, 'simvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13766, 'cyclophosphamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13768, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13768, 'matricaria');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (13768, 'chamomile');