INSERT INTO med_ingredients (med_id, ingredient) VALUES (30518, 'boron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30518, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30518, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30523, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30523, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30524, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30524, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30532, 'fentanyl');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30537, 'sunactive iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30537, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'sunactive iron pyrophosphate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'pido-zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'zinc pidolate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'copper gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'vitamin b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30538, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30540, 'ferrous bisglycinate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30540, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30540, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30540, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30543, 'metronidazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'biotin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'caviar');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'nigella sativa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'vitamin(e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'f');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'b3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'ginseng');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'capsicum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30545, 'garlic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30553, 'mirabegron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30554, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30554, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30554, 'eucalyptus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30555, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30555, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30555, 'clove');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30555, 'chlorhexidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30557, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30557, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30560, 'magnesium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30560, 'manganese');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30560, 'boron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30560, 'calcium*');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30560, 'vit^d3^800');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30560, 'zinc and vit^c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'hyaluronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'calendula officinalis extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'propolis extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'phenoxyethanol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'niacinamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'd-panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'dimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'iplant olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'iplant rosemary');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'ulmus fulva bark extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'propylene glycol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'triglycerides');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30561, 'whea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30562, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30562, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30565, 'chlorhexidine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30565, 'na lauryl ether sulphate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30565, 'betaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30565, 'menthol crystal');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30565, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30565, 'thymol extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30566, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30566, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30566, 'methyl salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'hamamelis citrus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'lido ex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'mustard gtn');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'ammi visnaga ex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30568, 'liposom');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30571, 'esomeprazole');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30572, 'lactobacillus acidophilus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30572, 'beta glucan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30572, 'inulin_zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30573, 'etoricoxib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30574, 'etoricoxib');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30576, 'metformin hydrochloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30576, 'vildagliptin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30577, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30582, 'immunoglobulin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30583, 'immunoglobulin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'vitamin b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30584, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30585, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30585, 'colostrum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30585, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30585, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30585, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30587, 'agar agar liquid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30588, 'acetylcysteine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30589, 'acetylcysteine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30594, 'retinyl');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30594, 'argireline');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30594, 'liquorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30594, 'castor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30594, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30594, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30595, 'methyl salicylate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30595, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30595, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30597, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30598, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30599, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30599, 'metformin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30600, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30600, 'metformin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30601, 'dapagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30602, 'dapagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30604, 'methylprednisolone sodium succinate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30605, 'methylprednisolone sodium succinate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30606, 'gentamicin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30607, 'collagen marine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30607, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30607, 'silicon dioxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30608, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30608, 'linagliptin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30609, 'empagliflozin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30609, 'linagliptin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30612, 'colchicine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30613, 'febuxostat');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30614, 'febuxostat');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'bees wax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'dimethicone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'vit e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'tea trea oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'thyum extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'castoroil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'shea butter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'cocoabutter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'triethanolamine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'camomile extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30615, 'popylene glycol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30616, 'clorhexidin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30616, 'beeswax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30616, 'panthinol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30616, 'cactus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30616, 'onion');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30626, 'acnacidol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30626, 'allantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30626, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30626, 'parsol tx');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30626, 'uvinul a plus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30627, 'ferrous bisglycinate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30627, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30627, 'vit b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30627, 'vit c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'hyaluronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'collagen marine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'ceramide 3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'shea butter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'linoleic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'coconut oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'seed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30633, 'calendula');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30634, 'jojoba liquid wax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30636, 'ferric hydroxide polymaltose');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30638, 'emicizumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30639, 'emicizumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30640, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30640, 'tocopheryl acetate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30641, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30641, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30641, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30641, 'argan oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30641, 'sheabutter');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30641, 'caffein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30645, 'green coffee beans');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30645, 'garcinia cambogia');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30645, 'caffeine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30648, 'beta sitosterol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30648, 'beeswax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30648, 'calendula ex.');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30648, 'triclosan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30648, 'alpha bisabolol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30648, 'alpha pinene');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30650, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30651, 'chromium 100 iu');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30651, 'garcinia cambogia 200 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30651, 'green tea extract 100 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30651, 'green coffee bean extract 200 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30652, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30652, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30652, 'eucalptus extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30656, 'hylouronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30656, 'vitamin b5');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'prebiotic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'potassium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'chloride');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'citrate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30657, 'dextrose');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30658, 'hydrocortisone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30658, 'fucidic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30661, 'captopril');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30662, 'adalimumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30670, 'durvalumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30671, 'durvalumab');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30678, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30679, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30680, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30680, 'vitamin d');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30680, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30681, 'cilastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30681, 'imipenem');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30682, 'calcium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30682, 'magnesium carbonate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30682, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30682, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30683, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30684, 'clarithromycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30685, 'clarithromycin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'liquorice extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'clerilys w');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'persea gratissima oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'hydrolyzed pearl');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'sweet almond oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'lactophyt');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30689, 'hydrolyzed soy protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30690, 'alogliptin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30690, 'pioglitazone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30695, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30695, 'glycerol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30695, 'citirc acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30695, 'cocamidopropyl betaine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30697, 'irinotecan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30698, 'irinotecan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30699, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30699, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30699, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30699, 'vitamin b complex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30701, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30701, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30701, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30701, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30701, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30701, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30702, 'liposomal iron 30 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30702, 'vitamin c 70 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30703, 'iron(ferrous bisglycinate)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30703, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30703, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30703, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30703, 'niacinamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30703, 'vitamin b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30705, 'anise');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30705, 'lemon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30707, 'anise');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30708, 'caraway');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30709, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30710, 'cinnamon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30711, 'ginger');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30711, 'cinnamon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30712, 'ginger');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30712, 'lemon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30713, 'green tea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30714, 'green tea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30714, 'mint');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30715, 'hibiscus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30716, 'peppermint');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30717, 'tilia');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30720, 'ivermectin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30721, 'ivermectin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30722, 'acetylcysteine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30722, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30723, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30724, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30725, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30726, 'ivy leave extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30727, 'ivy leave extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30727, 'liquorice extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30727, 'thyme extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30728, 'ivy leaves');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30729, 'jojoba oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30729, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30729, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30729, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30729, 'propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30734, 'gelatin (collagen) hydrolysate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30734, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30737, 'alpha lipoic acid 600');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30737, 'vitamin b 1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30737, 'vitamin b 6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30737, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30737, 'vitamin b 12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30738, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30738, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30738, 'vitamin b complex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30738, 'copper');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30738, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30739, 'ezetimibe');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30739, 'simvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'beeswax');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'zno');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'paraffin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'dimethicon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'd-panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'metyl paraben');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'olive');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30743, 'vit a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'hydrolyzed wheat protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'silicon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'tocopherol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'cinnamon oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30752, 'triclosan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'keratin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'hydrolyzed wheat protein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'silicon');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'tocopherol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'olive oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'aloe vera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'cinnamon oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30753, 'triclosan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30755, 'calcium citrate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30755, 'magnesium citrate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30755, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30755, 'zinc gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30755, 'manganese gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30755, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30756, 'glycerol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30756, 'hpmc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30756, 'sod. hyaluronate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30756, 'essential oils of eukalyptus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30756, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30756, 'camomil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30757, 'cholecalciferol 100iu');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30757, 'drop');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'ferrous gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'vitamin b1');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'vitamin b2');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'vitamin b3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30758, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30759, 'dill seed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30759, 'caraway seed oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30761, 'moxifloxacin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30762, 'green tea oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30762, 'resorcinol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30762, 'salicylic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30762, 'benzoic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30762, 'cetrimide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'triclosan');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'nicotinamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'alpha-bisabolol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'tea tree oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'zn gluconate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'sulfur');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'green tea extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'calendula extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30764, 'licorice extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30765, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30765, 'kojic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30765, 'wheat germ oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30765, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30765, 'liquorice');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30766, 'lactic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30766, 'urea');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30766, 'vitamin e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30768, 'hyaluronic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30768, 'vitamin b5');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30778, 'lacosamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30779, 'lacosamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30780, 'lacosamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30782, 'lacosamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30784, 'bovine lactoferrin 100 mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30785, 'bovin lactoferrin 250mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30785, 'zinc 15mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30785, 'selenium 55mcg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30785, 'vitamin b6 10mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30788, 'beta caroten-ethylhexyl methoxycinnamate-homosalate-zinc oxide-niacinamide-tocopheryl acetate- na hyaluronate-protect complex-');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30793, 'marine hydrolyzed collagen');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30793, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'lactoferrin 100mg');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'vitamin d');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'b complex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30799, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30803, 'propolis');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30803, 'alovera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30803, 'panthenol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30806, 'colostrum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30806, 'lactoferrein');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30806, 'selenium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30806, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30806, 'vit c & e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'panax ginseng');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'ginkgo biloba');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'l arginine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'phytosterols');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'horsetail');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'spirulina');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'moringa');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30808, 'saw palmetto');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30816, 'sodium valproate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30817, 'sodium valproate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30818, 'inclisiran');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30819, 'chlorpheniramine');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30819, 'dexamethasone');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30820, 'psyllium husk');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30820, 'chromium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30822, 'diclofenac sodium');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30826, 'menthol');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30826, 'camphor');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30826, 'eucalyptus');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30829, 'fenofibrate(nanocrystal technology)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30830, 'ezetimibe');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30830, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30831, 'ezetimibe');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30831, 'rosuvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30832, 'liposomal iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30832, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30832, 'folic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30832, 'vitamin b6');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30832, 'vitamin b12');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30832, 'vitamin d3');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30833, 'atorvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30834, 'atorvastatin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30835, 'vitamin c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30836, 'cholecalciferol(vitamin d3)');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30838, 'zinc oxide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30838, 'alovera');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30838, 'chamomile');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30838, 'alantoin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30842, 'probiotic immunoblend');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30842, 'prebiotic sunfibers');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30842, 'lactic acid');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30842, 'pots of marigold');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30842, 'vit. a');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30842, 'vit. e');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30844, 'sodium zirconium cyclosilicate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30845, 'sodium zirconium cyclosilicate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30846, 'loperamide');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30847, 'iron');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30847, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30847, 'colostrum');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30847, 'vit c');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30847, 'vit b complex');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30849, 'probiotic');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30849, 'zinc');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30849, 'lactoferrin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'aloe vera extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'glycerin');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'glyceryl tri-nitrate');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'chamomil extract');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'honey');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'sweet orange oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'castor oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'rosemary oil');
INSERT INTO med_ingredients (med_id, ingredient) VALUES (30850, 'vitamin e');