INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2056, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2057, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2058, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'collagen oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'sesamum indicum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2061, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2063, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2064, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2065, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2066, 'verapamil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2067, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2067, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2067, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2068, 'multivitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2069, 'torsemide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2070, 'cratageus (hawthorn) extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2072, 'dexrazoxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2073, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2073, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2074, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2075, 'acetylsalicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2076, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2076, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'fennel fruit extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'peppermint extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2080, 'anise extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'd-alpha tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'vitamin k');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2081, 'vitamind3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2083, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2084, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2086, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2087, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2088, 'benzalkonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2089, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2090, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2091, 'lercanidipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'pdms (polysiloxane)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'onion oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2092, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2093, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2094, 'tizanidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2097, 'potassium sodium hydrogen citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2098, 'eplerenone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2099, 'eplerenone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2101, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2103, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2104, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2104, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2105, 'caraway oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2105, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2105, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2106, 'caraway oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2106, 'cinnamon oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2106, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2107, 'phenazopyridine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2107, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2109, 'vitamin d3 4000 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2111, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'raspberry ketone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'garcinia cambogia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'green coffee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'caffeine anhydrous');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2112, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2115, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2115, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2115, 'vitamin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2117, 'l-carnitine l-tartrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2117, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'avobenzone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'homosalate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'octisalate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'octocrylene. oxybenzone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'green tea leaf extract (aqueous). cucumber extract (aqueous)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'tocopheryl acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'cetostearyl alcohol ceteareth-20');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2118, 'isopropyl myristate monopropylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2119, 'apricot oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2123, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2123, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2123, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2124, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2124, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2124, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2127, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2128, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2129, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2129, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2130, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2131, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2132, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2133, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'eugenia caryophyllus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'mentha piperita');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'chlorhexidine digluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'sodium saccharine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'myrtrimonium bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'sodium benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'benzoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'zinc chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2134, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2137, 'carvedilol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2140, 'phenol-basicfuchsine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2142, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2143, 'besifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2144, 'lactobacillus rhamnoses gg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'zinc pyrithion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2146, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2148, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'clove extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2149, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2150, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2151, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2153, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2154, 'diclofenac potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2155, 'pirenoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2156, 'pirenoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2157, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'mineral oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'eurica oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'myrestic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2158, 'r');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2159, 'betasitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2160, 'vitamin d (cholecalciferol) vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'rutin');