INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16636, 'colistin (colistimethate sodium)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16637, 'colistin (colistimethate sodium)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16638, 'colistin (colistimethate sodium)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16641, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16641, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'collagen hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16642, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16643, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16643, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16643, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16643, 'collagen hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16643, 'rosehip ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16644, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16645, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16645, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16645, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16646, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16646, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16649, 'chlorthalidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16650, 'sodium cromoglycate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16651, 'colchicine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16652, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16652, 'anise oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16654, 'psyllium husk powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16655, 'psyllium husk powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16657, 'colistin (colistimethate sodium)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16659, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16659, 'sulpiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16661, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16661, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16661, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16661, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'lysin 80 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'iron 14 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'zinc 10 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'vitamin c 20 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'niacin 16 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'b1 8 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'b6 4mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'pantothenic acid 4 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'b2 2 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16662, 'b12 10 mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16664, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16665, 'linozolid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16666, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16666, 'sulpiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16667, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16670, 'pyridoxine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16670, 'methylcobalamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16670, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16670, 'd-biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16671, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16671, 'sulpiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16673, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16673, 'flucloxacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16674, 'brimonidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16674, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16675, 'dorzolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16675, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16677, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16677, 'benazepril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16680, 'oxazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16681, 'oxazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16682, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16682, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16682, 'isopropanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16682, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16682, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16682, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16683, 'atrichoke');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16683, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16683, 'tumeric');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16683, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16683, 'parsley');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16683, 'chicory');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16684, 'sage');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16684, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16684, 'marjoram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16684, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16684, 'parsley');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16684, 'chicory');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16687, 'massage cream formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16689, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16690, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16690, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16690, 'piroctone olamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16690, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16690, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16692, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16692, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16692, 'vitamind3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16692, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16692, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16692, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16693, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16693, 'octopirox');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16693, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16693, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16693, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16694, 'alexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16694, 'polyquaternium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16694, 'boric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16695, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16695, 'chelated iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16696, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16700, 'econazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16701, 'norfloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16701, 'tinidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16702, 'voriconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16703, 'voriconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16705, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16706, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16707, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16708, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16709, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16710, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16711, 'haemodialysis solution');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16716, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16716, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16720, 'memantine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16721, 'memantine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16722, 'memantine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16723, 'silodosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16724, 'silodosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16726, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16726, 'phenylephrine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16728, 'glucose amine hcl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16728, 'avocadosoyaben unsaponifible');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16728, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16728, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16728, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16728, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16729, 'psyllium fibers');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16729, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16730, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16730, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16730, 'calcium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16730, 'magnesium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16731, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16732, 'olopatadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16733, 'olopatadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16734, 'bisacodyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16735, 'prucalopride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16737, 'prucalopride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'peanut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'sesame oil (b-sitosterol)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'd-panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'candelilla wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'vitmin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'alpha bisabolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'chamomille oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16740, 'chlorhexidine.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16742, 'aminacrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16742, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16743, 'phenothrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'piroctone olamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'rosemary ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16747, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16748, 'hydrolized keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16748, 'hydrolyzed protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16748, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16748, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16749, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16749, 'extract cepae fluid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16749, 'heparin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16750, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16750, 'extract cepae fluid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16750, 'heparin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16752, 'bilastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16753, 'chondititon 500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16753, 'glucosamine 1000mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16753, 'msm 500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16753, 'collagen 1500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16753, 'hyaluronic acid 100mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16757, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16757, 'whey powder con.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16757, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16757, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16757, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16757, 'natural flavour (chocolate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16758, 'levonorgestrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16760, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16763, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16763, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16763, 'kojic dipalmitate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16765, 'pantoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16767, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16767, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16768, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16768, 'hydrochlorothiazide');