INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15256, 'cefixime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15257, 'red yeast rice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15259, 'botanical ingredients');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15261, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15261, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15262, 'nigella sativa oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15264, 'liposomal glutathione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15264, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15265, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15267, 'probiotic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15267, 'prebiotic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15267, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15268, 'rifaximin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15269, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15270, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15271, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15272, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15272, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15272, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15272, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15272, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15273, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15273, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15273, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15273, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15273, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15274, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15275, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15275, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15276, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15276, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15282, 'beta sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15282, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15282, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15282, 'vitamin a & e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15282, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15284, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15288, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15290, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15291, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15293, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15294, 'aloe capensis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15294, 'octadecadienoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15294, 'octadecenoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15298, 'ivy leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15299, 'sertaconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15300, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15300, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15300, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'maltodextrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'soy protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'sucrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'sodium caseinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15301, 'natural flavour');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15306, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15306, 'mineral oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15306, 'lanolin anhydrous');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15307, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15308, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15309, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15310, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15311, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15313, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'boric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'edetate disodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'sodium borate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'dymed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'hydranate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15315, 'poloxamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'boric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'edetate disodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'sodium borate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'dymed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'hydranate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15316, 'poloxamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'green tea ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'cod liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15317, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15318, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15318, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15318, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15319, 'multivitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15319, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15319, 'antioxidants');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15320, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15320, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15320, 'evening primrose oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15320, 'yeast concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15320, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15320, 'zinc sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15321, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15321, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15321, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15322, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15322, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15322, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15323, 'skimmed milk');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15323, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15323, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15324, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15328, 'bisacodyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15330, 'bisacodyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15335, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15337, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15337, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15338, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15338, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15339, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15340, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15341, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15342, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15342, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15343, 'bromhexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15347, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15351, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15351, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15353, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15353, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15355, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15355, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15355, 'cetrimonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15356, 'cimicifuga racemosa(black cohosh)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15358, 'mirabegron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15359, 'cetiol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15359, 'bearberry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15359, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15359, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15359, 'abil b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15359, 'butyl methoxy dibenzoyl methane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15362, 'alendronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15362, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15363, 'tranexamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15364, 'carbetocin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15365, 'octyl stearate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15366, 'milk formula stage 1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15367, 'milk formula stage 2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15368, 'milk formula stage 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15369, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15370, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15372, 'bleomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15373, 'sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15373, 'potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15373, 'choloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15373, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15374, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15374, 'sulfacetamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15376, 'tamsulosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15377, 'lercanidipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15378, 'lercanidipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15379, 'minoxidil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15380, 'bleomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'l carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'l arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'co q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'vit b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15381, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15382, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15382, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15383, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15383, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15384, 'ca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15384, 'mulivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15384, 'vitd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15384, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15384, 'magnsium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15385, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15385, 'chymotrypsin');