INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21654, 'magnesium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21654, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21655, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21656, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21657, 'magnesium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21658, 'natural herbal extracts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21658, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21658, 'low molecular weight protein hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21658, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21658, 'hpmc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21659, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21662, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21663, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21665, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21666, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21668, 'l-carnitine fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21669, 'l-carnitine l-tartrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21669, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21672, 'citalopram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21673, 'ledipasvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21673, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21678, 'leflunomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21679, 'leflunomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21683, 'bambuterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21684, 'bambuterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21685, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21687, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'soya protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'aloe vera ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'vit.e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'green tea ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21688, 'isopropyl myristate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21689, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21689, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21690, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21690, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21690, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21690, 'beta carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21690, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21692, 'telmisartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21693, 'telmisartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21694, 'lenalidomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21695, 'lenalidomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21697, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21697, 'calendula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21697, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21697, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21698, 'hydroxyprogesterone caproate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21699, 'lactium-150 (milk protein hydrolysate-alpha-casozepine)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21699, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21700, 'lenvatinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21701, 'lenvatinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21703, 'clozapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21705, 'eslicarbazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21706, 'eslicarbazepine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21707, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21709, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21710, 'lamotrigine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21712, 'bepotastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21714, 'cetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21717, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21718, 'fluvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21719, 'allopurinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21720, 'allopurinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21721, 'letrozole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21723, 'letrozole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21725, 'leuprorelin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21726, 'leuprorelin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21728, 'levamisole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21733, 'liver support formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21734, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21734, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21735, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21737, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21738, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21739, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21741, 'insulin detemir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21746, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21749, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21749, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21751, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21751, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21752, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21753, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21754, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21755, 'chloramphenicol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21756, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21761, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21762, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21764, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21765, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21767, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21768, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21769, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21772, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21773, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21774, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21775, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21775, 'aloe vera ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21775, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21775, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21775, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21775, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21776, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21778, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21778, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21778, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21778, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21779, 'bromazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21781, 'bromazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21783, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21784, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21785, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21785, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21786, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21786, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21787, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21787, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21788, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21788, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21789, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21789, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'sage');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21790, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'ginko biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'apricot');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21792, 'gel base');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21794, 'malathion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21795, 'tetramethrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21795, 'piperonyl butoxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21796, 'tetramethrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21796, 'piperonyl butoxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21797, 'tetramethrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21797, 'piperonyl butoxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21799, 'donepezil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21800, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21801, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21803, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21804, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21805, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21806, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21808, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21809, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21810, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21810, 'epinephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21811, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21812, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21813, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21813, 'epinephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21814, 'silodosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21815, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21816, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21817, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21817, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21817, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21819, 'artichoke');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21819, 'chicory');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21819, 'turmeric');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21819, 'parsely');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21821, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21822, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21824, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21825, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21825, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21827, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21828, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21828, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21829, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21833, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21834, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21835, 'zinc gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21836, 'levocetirizine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21837, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21838, 'lincomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21839, 'lincomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21840, 'lincomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21841, 'lincomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21842, 'lincomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'poly dimethyl siloxan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21844, 'lemon oil');