INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15481, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15481, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15485, 'brimonidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15485, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15486, 'brimonidine tartrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15488, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15488, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15489, 'diosmin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15489, 'hesperidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15490, 'lactoferrin 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15490, '100 mg colostrum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15490, '100mg calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15490, '40 mg zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15490, '10 mg magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15490, '350 mg vitamin c and 125mcg vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15492, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15493, 'vortioxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15494, 'vortioxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15495, 'aceclofenac');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15496, 'aceclofenac');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'liquorice ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'vitamin (c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'mulberry');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15497, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'tio2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'zno');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'cinnamate&salicylate groups');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'liquorice ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'vitamin (c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'mulberry');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15498, 'gre');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15500, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15501, 'parsley seeds');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15501, 'green tea leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15501, 'celery seeds');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15502, 'propamidine isethionate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15503, 'bromazepam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15505, 'bromhexine hcl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15506, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15506, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15507, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15507, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15507, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15508, 'mannitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15509, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15509, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15509, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15509, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15510, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15511, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15514, 'primula root fluid extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15514, 'thyme fluid extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15515, 'ammonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15515, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15515, 'ipeca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15515, 'sodium camosulphonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15517, 'benzonatate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15517, 'diphenhydramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15517, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15517, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'sweet almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'ginger oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15518, 'rosemary oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15519, 'ammonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15519, 'chlorpheniramine maleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15519, 'ipeca tincture');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15520, 'diphenhydramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15520, 'dextromethorphan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15520, 'ephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15520, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15524, 'formoterol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15526, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15530, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15532, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15532, 'oxomemazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15532, 'sodium benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15533, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15533, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15536, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15536, 'elastin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15536, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15536, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15536, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15536, 'liquorice ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15537, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15537, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15537, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15537, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15538, 'bromhexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15538, 'guaifenesin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15538, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15538, 'terbutaline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15539, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15540, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15542, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15545, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15546, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15546, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15547, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15547, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15548, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15548, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15549, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15551, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15552, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15553, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15555, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15556, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15559, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15560, 'human albumin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15562, 'bumetanide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15563, 'beta-sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15565, 'silver sulfadiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'marine collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'elastin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'vita a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'co enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'centella asiatic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15566, 'l-carnitine.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15567, 'hyoscine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15567, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15568, 'hyoscine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15568, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15570, 'hyoscin-n-butylbromid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15571, 'hyoscin-n-butylbromid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15572, 'hyoscin-n-butylbromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15576, 'hyoscine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15576, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15581, 'hyoscin-n-butylbromid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15586, 'butoconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15587, 'butoconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'st. john wart extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'sage extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'oats extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'p.o.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'foenugreek extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15590, 'allant');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15591, 'exenatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15592, 'exenatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15594, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15594, 'zinc bisglycinate chelate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15595, 'tretinoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15599, 'cabergoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15600, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15600, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15600, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15600, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15601, 'calcium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15601, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15601, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15602, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15602, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15603, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15603, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15604, 'bisabolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15604, 'sodium coceth sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15604, 'lauryl glucoside');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15604, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15605, 'bisabolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15605, 'sodium coceth sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15605, 'lauryl glucoside');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15605, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15608, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15608, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15608, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15608, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15608, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15608, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15609, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15609, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15609, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15609, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15609, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15609, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15611, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15613, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15614, 'calamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15614, 'diphenhydramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15614, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15615, 'calamine');