INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27130, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27131, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27132, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27134, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27136, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27137, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27137, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27138, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27138, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27140, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27140, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27141, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27141, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27143, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27143, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27144, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27144, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27145, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27145, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27146, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27146, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27147, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27147, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27148, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27148, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27150, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27150, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27151, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27151, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27152, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27155, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27156, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27157, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27158, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27161, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27162, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27163, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27164, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27164, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27165, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27165, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27167, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27167, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27168, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27168, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27169, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27169, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27171, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27172, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27173, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27174, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27175, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27176, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27177, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27178, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27179, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27180, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27182, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27183, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27188, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27189, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27191, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27192, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27195, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27195, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27196, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27197, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27198, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27199, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27200, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27201, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27202, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27204, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27205, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27206, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27207, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27208, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27209, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27210, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27211, 'psyllium husk powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27211, 'pineapple extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27211, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27211, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27214, 'solifenacin succinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27216, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27216, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27216, 'whey protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27217, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27218, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27219, 'ledipasvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27219, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27220, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27221, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27222, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27223, 'sofosbuvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27226, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27226, 'adapalene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27226, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27228, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27228, 'tegobetain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27228, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27228, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27228, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'pumpkin& silicon& jojoba& sesame oils');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'hydrolyzed keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27229, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'vitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27230, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'vitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27231, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'pmx-1501');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'pmx-245');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27232, 'dmdm hydantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'almond &sesame &olive & jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27233, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'vitamins(c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'a)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'bees honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27234, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27235, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27235, 'tilia flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27235, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27237, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27238, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27239, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27240, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27241, 'extract free from calves blood');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27242, 'acetylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27242, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27242, 'quercetin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27242, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27242, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27245, 'amisulpride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27246, 'amisulpride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27247, 'insulin glargine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27247, 'lixisenatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27248, 'insulin glargine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27248, 'lixisenatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27249, 'solifenacin succinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27250, 'solifenacin succinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27251, 'polyhexanide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27251, 'hydrolock');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27251, 'sodium phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27251, 'tromethamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27251, 'poloxamer 407');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27251, 'disodium edetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27252, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27252, 'hexamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27252, 'chlorocresol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27253, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27253, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27253, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27253, 'dexpanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27253, 'glycerol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27253, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27254, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27255, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27256, 'gatifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27257, 'zolmitriptan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27261, 'methylprednisolone sodium succinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27262, 'penicillin g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27264, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27269, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27271, 'carboxymethylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27272, 'carboxymethylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27273, 'acetylcysteine');