INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6434, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6434, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6435, 'tolterodine l tartarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6438, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6442, 'indapamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6444, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6444, 'silver sulfadiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6445, 'propranolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6447, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6448, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6449, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'ferrous bisglycinate127.84mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'ascorpic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6450, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6451, 'propranolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6452, 'propranolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6453, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6454, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6455, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6456, 'milk formula stage 1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6457, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6458, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6459, 'cranberry');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6462, 'omega 3 (dha');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6462, 'epa)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6462, 'coenzyme(q10)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6463, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6463, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6463, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6464, 'bisoprolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6464, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6465, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6467, 'azithromycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6469, 'amantadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6470, 'triple silicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6470, 'omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6474, 'melatonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6474, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6474, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6475, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6477, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6479, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6479, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6479, 'cyanocobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6479, 'ferrous bis-glycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6480, 'panthenol 2%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6480, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6480, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6480, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6481, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6481, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6481, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6481, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6481, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6482, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6483, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6484, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6484, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6484, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6484, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6484, 'hydrolyzed elastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6484, 'and ecoslim caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6486, 'flibanserin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6487, 'ivy leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6488, 'tirazepatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6489, 'vonoprazan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6490, 'carbamide (urea)10%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6490, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6490, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6490, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'triple silicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'onion oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'quercetin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'vit a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'soybean oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'palm oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6491, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6492, 'vitamin d 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6492, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6492, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6492, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6492, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6494, 'agomelatine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6498, 'b-sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6498, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6498, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6498, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6498, 'natural oils');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6500, 'garcinia cambogia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6500, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6501, 'insulin neutral human');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6502, 'insulin neutral human');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6502, 'insulin isophane protamine human');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'brmelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'papain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'fungal lipase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'fungal lactase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'alpha galactosidase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'fungal protease');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'lactobacillus acidophilus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'lactobacillus casei');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6505, 'lactobacillus plantarium.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6518, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6518, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6518, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6518, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6524, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6524, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6524, 'alovera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6524, 'olea oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6524, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6524, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6525, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6525, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6525, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6525, 'mentha piperita');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6526, 'high purified omega 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6526, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6526, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6526, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6527, 'eptifibatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6528, 'l-threonine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6528, 'l-tryptophan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6528, 'l-tyrosine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6528, 'l-histidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6528, 'l-lysine monoacetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6532, 'tilbroquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6532, 'tiliquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6532, 'tiliquinol lauryl sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6533, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6533, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6533, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6533, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6533, 'histidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6534, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6534, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6535, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6537, 'egg phospholipids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6537, 'soya bean oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6538, 'glutathione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6538, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6540, 'citicolione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6543, 'ertapenem');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6544, 'probiotic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6544, 'clandula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6544, 'sodium hyaluronic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6544, 'and panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6545, 'paliperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6546, 'citicolione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6547, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6547, 'cocos nucifera oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6547, 'lavender angustlfolia oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6548, 'dried ivy leaf extract 43mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6548, '5ml');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6549, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6550, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6551, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6551, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6551, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6551, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6551, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6553, 'aescin - arnica - eucalyptus oil - menthol - aloe vera extract - tea tree oil - vitamin c - vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6554, 'latanoprost');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6555, 'lactase enzyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6556, 'finest norwegian fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'l- carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'coenzyme q_10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'n_ acetyle');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'grabed bextract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'lycopene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'beta_carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'thiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'benfotamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6559, 'selenium');