INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25512, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25512, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25513, 'dalfampridine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'eucalyptol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'guaiacol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25514, 'pholcodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25515, 'pyrazinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25516, 'pyrazinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25518, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25519, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25520, 'pyridostigmin bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'rosemary ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25521, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25522, 'coenzyme q-10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25523, 'coenzyme q-10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25524, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25525, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'clioquinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25526, 'tolnaftate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'ethambutol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'isoniazid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'pyrazinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25527, 'rifampicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25528, 'cholestyramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25529, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25530, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25530, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25530, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25531, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25532, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25533, 'dorzolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25534, 'dorzolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25534, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'soybean oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'seasame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25535, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25536, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25538, 'cholestyramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25539, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25540, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25541, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25542, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25543, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25544, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25545, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25546, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25547, 'theophylline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25548, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25549, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25550, 'ofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25551, 'gemifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25552, 'gemifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25553, 'quinidine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25554, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25555, 'ciprofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25556, 'moxifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25557, 'levofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25558, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25559, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25560, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25561, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25562, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25564, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25565, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25566, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25567, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25568, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25569, 'ombitasvir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25569, 'paritaprevir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25569, 'ritonavir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25573, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25574, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25575, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'squalane se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25590, 'l');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'light liquid paraffin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'isopropyl myristate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'polyethylene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'silica');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25591, 'dimethicon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'magnesium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25599, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'bee pollen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'korean ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25600, 'lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25601, 'irgasan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25601, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25601, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25602, 'fenugreek');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25602, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25602, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25606, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25606, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25607, 'rabeprazole sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25608, 'rabeprazole sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25611, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25612, 'rabies vaccine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25614, 'rabies vaccine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25615, 'racecadotril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25616, 'salicylates');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'camphor oil white');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'capsicum oleoresin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25617, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'camphor oil white');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'capsicum oleoresin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25618, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'condrotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'calcium phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25620, 'astaxinthin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25621, 'leflunomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25622, 'leflunomide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25623, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25623, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25623, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'glucosamine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'chondroitin sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25624, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25625, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25625, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (25628, 'fluoxetine');