INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17466, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17466, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17467, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17467, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17468, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17468, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17469, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17470, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17471, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17472, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17473, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17474, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17475, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17476, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17477, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17479, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17480, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17482, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17482, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17483, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17483, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17484, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17485, 'calcium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17485, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17485, 'potassium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17485, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17486, 'calcium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17486, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17486, 'potassium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17486, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17487, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17487, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17488, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17489, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17489, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17490, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17490, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17491, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17491, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17492, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17492, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17493, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17493, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17494, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17494, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17495, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17495, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17496, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17496, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17498, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17498, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17499, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17499, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17500, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17501, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17502, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17503, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17504, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17505, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17506, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17507, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17510, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17511, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17511, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17511, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17511, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'tocopherol (vit e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'laurocapram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'eucalyptus globulus leaf (eucalyptus)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'eugenia caryophyllus flower extract (clove)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'magnesium sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, '(camphora oil)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'panax ginseng root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'persea gratissima oil (avocado oil)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'butyrospermum parkii butter (shea butter)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'glyceryl stearate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'arctium lappa root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'phenoxyethanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, '10-hydroxystearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17512, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17513, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17513, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17513, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17514, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17514, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17514, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17515, 'beepropolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17515, 'fluoride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17515, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17516, 'beepropolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17516, 'fluoride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17516, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17517, 'pimecrolimus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17519, 'dhea (dehydroepiandrosterone)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17520, 'dhea (dehydroepiandrosterone)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17521, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17523, 'melaleuca alternifolia leaf oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17527, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17528, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17528, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17529, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17530, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17532, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17532, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17533, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17533, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17534, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17535, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17536, 'nateglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17537, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17538, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17540, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17541, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17542, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17542, 'calcipotriol(calcipotriene)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17544, 'canagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17545, 'canagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17546, 'silver nano particles');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17546, 'calendula officinalis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17546, 'poly vinyl pyyrildone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17546, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17546, 'poly ethylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17546, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17548, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17549, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17550, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17550, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17550, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17550, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17551, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17551, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17552, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17552, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17553, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17553, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17554, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17554, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17555, 'nifuroxazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17556, 'nifuroxazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17558, 'panthenol - alovera extract - cucumber extract - petrolatum - honey - chamomile ext - soybean oil - vit e - vit c - allantoin - beeswax - glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17559, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17559, 'vandyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17559, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17559, 'floc acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17559, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17559, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17560, 'activated charcoal 290 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17560, 'anise extract 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17560, 'peppermint extract 80 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'choline chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17562, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17563, 'dopamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17564, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17565, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17566, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17567, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17567, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'olive leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'sage leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'eruca leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17568, 'salicylic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'sorbitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17569, 'sodium fluoride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17570, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17573, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17574, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17575, 'ethinyl estradiol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17575, 'cyproterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17576, 'gliclazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'aloe ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'vit. b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'ginseng ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (17581, 'panthenol');