INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19944, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19944, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19946, 'mitiglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19949, 'gliquidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19950, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19950, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19951, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19951, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19952, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19953, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19954, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19956, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19957, 'glutamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'glutathione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'silymarine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19959, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19960, 'vildagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19962, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19962, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19963, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19963, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19964, 'glibenclamide(glyburide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19964, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19965, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19966, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19968, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19969, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19969, 'ichtammol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19971, 'gelatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19971, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19972, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19974, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19975, 'nitroglycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19976, 'nitroglycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19977, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19979, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19980, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19983, 'magaldrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19984, 'sodium glycerophosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19985, 'terlipressin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19987, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19987, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19987, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19988, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19988, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19988, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19989, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19989, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19989, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19990, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19991, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19993, 'caviar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19993, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19993, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'lexol 300');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'cocamidopropyl betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'peg 7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19995, 'f');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19996, 'micellar casein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19997, 'partially hydrolyzed whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19997, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19998, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19998, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19998, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19999, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19999, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (19999, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20000, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20000, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20000, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20001, 'whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20001, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20001, 'whey peptide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'protein blend(whey protein isolate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'whey protein concentrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'hydrolyzed whey protein isolate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20002, 'carbohydrate blend');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'vitamin (d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'thiamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'muscle matrix');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'performance composite');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20003, 'energy & focus complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20004, 'agar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20005, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20006, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20007, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20007, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'ginger oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20008, 'orange oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'peg-7 glyceryl cocoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'eruca sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20009, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'capsacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20010, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20011, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20013, 'cabergoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20015, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20015, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20015, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20016, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20017, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20018, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20019, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20021, 'follitropin alfa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20022, 'testosterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'piroctone olamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20023, 'sodium laureth sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20024, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20024, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20024, 'chlorhexidine gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20025, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20026, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20027, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20028, 'colchicine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20028, 'probenecid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'chitosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'forskolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'garcinia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'green tea ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'vitamins (b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20029, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'safflower oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20030, 'bioflavonoids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20031, 'anti-t lymphocyte(anti-thymocyte) immunoglobulin=a.t.g.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20032, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20033, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20034, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20035, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20036, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20036, 'flucloxacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20037, 'ofloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20038, 'fesoterodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20039, 'fesoterodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20040, 'ketotifen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'oils(camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'peppermint)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'vitamin(c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20041, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'vitamin(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20042, 'c');