INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'black seed ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'eruca sativa oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15047, 'belladonna');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15047, 'phenobarbitone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15048, 'belladonna');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15048, 'phenobarbitone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15050, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15052, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15053, 'blood-coagulation factor ix');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'liquid paraffin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15055, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15058, 'leucovorin calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15058, 'folinic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15058, 'calcium folinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15059, 'leucovorin calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15059, 'folinic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15059, 'calcium folinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15060, 'bendamustine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15061, 'bendamustine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15062, 'octreotide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15063, 'octreotide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15064, 'albendazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15067, 'blood-coagulation factor ix');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15068, 'blood-coagulation factor ix');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15069, 'blood-coagulation factor ix');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15070, 'dutasteride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15071, 'gelatin (collagen) hydrolysate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15071, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15072, 'wheat bran ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15072, 'provitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15074, 'alfuzosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15075, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15075, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15075, 'boric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15075, 'irgasan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15076, 'diphenhydramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15076, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15077, 'benzathine penicillin g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15078, 'benzathine penicillin g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15080, 'benzocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15085, 'dexapanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15086, 'dexapanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15087, 'rabeprazole sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15089, 'blood-coagulation factor viii');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15090, 'blood-coagulation factor viii');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15091, 'tetanus immune globulin (human)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15093, 'rabies immune globulin (human)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15094, 'rabies immune globulin (human)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15095, 'fenoterol hydrobromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15096, 'fenoterol hydrobromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15098, 'scilla tincture');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15098, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15098, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15099, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15101, 'ethyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15101, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15101, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15101, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15101, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15101, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15103, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15104, 'bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15104, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15105, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15105, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15107, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15108, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15109, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15113, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15115, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15116, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15117, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15118, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15120, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15120, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15121, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15122, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15123, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15124, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15125, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15129, 'ivy leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15130, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15130, 'dexchlorpheniramine maleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15132, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15132, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15133, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15134, 'cefixime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15136, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15138, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15138, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15139, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15139, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15140, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15140, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15142, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15145, 'melatonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15147, 'betaxolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15148, 'betaxolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15150, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15151, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'cooper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15153, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15155, 'ivy leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15155, 'thyme leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15155, 'licorice root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15156, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15157, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15158, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15159, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15162, 'betaxolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15163, 'betaxolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15164, 'atenolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15165, 'mirabegron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15166, 'mirabegron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15167, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'licorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'vitamins (c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'titanium oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'sodium benzoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15168, 'bearberry');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15169, 'scarfade complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15170, 'beta- sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15171, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'soy lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15172, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15173, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15174, 'cyanocobalamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15177, 'betaxolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15178, 'betaxolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15180, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15180, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15186, 'sodium alginate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15186, 'squalene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15186, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15186, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15187, 'borax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15187, 'aluminium potassium sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15187, 'chlorophyll');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15187, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15188, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15188, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15189, 'ramipril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15192, 'bilastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15193, 'bilastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15194, 'praziquantel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15196, 'safinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'co enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'ginko biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15197, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15198, 'praziquantel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15252, 'telmisartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15253, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15253, 'telmisartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15254, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15255, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15255, 'd-panthenol');