INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5993, 'pentosan polysulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5994, 'pentosan polysulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5995, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5995, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5995, 'camphora bark oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5997, 'ethamsylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5998, 'ethamsylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6002, 'combination omega 3 - 6 - 9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6003, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6003, 'folicvit');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'phospholipids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6004, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6005, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6005, 'omega6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6005, 'omega9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6006, 'silymarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'n-acetyl cysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'quercetin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6007, 'co-enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6008, 'l-ornithine-l-aspartate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6010, 'omga3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6010, 'citicolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6010, 'ginko biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6010, 'multi vit');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6011, 'ivy leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6011, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6011, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6012, 'silymarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6012, 'glutathion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6012, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6012, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6013, 'curcumin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6013, 'silymarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6014, 'tilia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6016, 'vonoprazan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'co enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'glutathione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6019, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6020, 'orotic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6020, 'phospholipids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6020, 'silymarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6021, 'silymarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6023, 'silymarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'collagen type ||');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'glucosamine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'chondroitin sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'folicacid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6024, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6026, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6026, 'carbamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6026, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6026, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6029, 'cysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6029, 'phospholipids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6029, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6029, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6031, 'essential phospholipids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6031, 'vitamins (b3-b1-b2-b6-b12-e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6032, 'thiazolidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6033, 'myo_inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6033, 'd_chiro inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6033, 'quatrefolic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6033, 'cholecalciferol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6035, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6035, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6035, 'colloidal gold');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6035, 'retinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6035, 'caviar oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6035, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6036, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6036, 'alpha arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6036, 'arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6037, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6037, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6037, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6037, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6039, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6039, 'tilia flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6039, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6039, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6040, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6040, 'ginger oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6042, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6042, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6042, 'alpha arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6042, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6043, 'solifenacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6043, 'mirabegron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6047, 'solifenacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6047, 'mirabegron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6048, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6048, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6048, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6048, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6057, 'fenugreek');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6057, 'dill');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6057, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6057, 'caraway');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6058, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6058, 'tilia flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6058, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6058, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6059, 'milk formula stage 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6062, 'ivy extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6062, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6063, 'myo inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6063, 'd-chiro inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6063, 'methyl folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6064, 'myo inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6064, 'd-chiro inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6064, 'methyl folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6065, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6065, 'benfotiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6065, 'pyridoxine hcl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6065, 'cyanobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6065, 'cholecalciferol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6066, 'maca root');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6066, 'tribulus terrestris extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6066, 'saw');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'vitamins (a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'b-complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'e k)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'minerals (zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6067, 'copper)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6068, 'milk formula stage 2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6069, 'milk formula stage 1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6070, 'milk formula stage 2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'hemp seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'arnica montana');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6071, 'canola oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6074, 'harpagophytum extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6075, 'mexiletine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6077, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6080, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6082, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6084, 'dibucaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6084, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6084, 'shark-liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6085, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6085, 'flucloxacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6087, 'avocado soya bean');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6087, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6087, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6087, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6087, 'boswellia seratta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6087, 'vitd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6089, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6089, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6089, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6089, 'cetyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6089, 'natural oils');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6092, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6092, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6092, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6093, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6093, 'clavulanic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6095, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6095, 'clavulanic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6096, 'amoxicillin');