INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24816, 'uvb filters');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'passion flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'golden alga');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24818, 'photostable uva and uvb filters');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24820, 'tamarind extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24820, 'burdock extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24820, 'zinc pca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24827, 'mandelic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24827, 'lemon extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24827, 'fuit-peel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24840, 'fluorescein sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24841, 'gatifloxacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24842, 'brimonidine tartrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24843, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24844, 'sodium carboxymethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24845, 'brimonidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24845, 'timolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24846, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24847, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24848, 'piracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'ethyl alcohol 70%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'chloroxylenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24849, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'ethyl alcohol 70%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'chloroxylenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24850, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'magnesium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24851, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24852, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24852, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24852, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24853, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24853, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24853, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24854, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24855, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24856, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24856, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24856, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24857, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24857, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24857, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24858, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24858, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24859, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24860, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24860, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24861, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24862, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'glycerol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'vitis vinifera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24863, 'sambucus nigra extract fruit');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'allium cepa ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'silicone dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'slaicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'vitamin(a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24864, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24866, 'chlorpheniramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24866, 'dexamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24867, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24867, 'sulfacetamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24868, 'phenobarbitone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24870, 'phenobarbitone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24871, 'phenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24871, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24872, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24873, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24874, 'phenylephrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24875, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24876, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24877, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24878, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24879, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24880, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24881, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24882, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24883, 'prenoxdiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24884, 'prenoxdiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24885, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24886, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24887, 'fluoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24888, 'phenindione(dindevan)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'phenylpropanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'pholcodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'promethazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24889, 'tolu syrup');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24890, 'sodium acid phosphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24891, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24892, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24893, 'amphotericin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24894, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24895, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24896, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24897, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24898, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24899, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24900, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24901, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24902, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24903, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24904, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24905, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24906, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24907, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24908, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24909, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24910, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24911, 'sun protection formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24912, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'olea europaea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'pentylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'palm glycerides');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'olus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'hydrogenated lecithin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'squalene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24913, 'bet');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24914, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24915, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'natural seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'hypertonic concentration of mineral salts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'essential oil of eucalyptus globulus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24916, 'natu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24917, 'natural undiluted seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24917, 'hypertonic concentration of mineral salts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24918, 'natural undiluted seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24918, 'hypertonic concentration of mineral salts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24920, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24921, 'natural undiluted and isotonic seawater');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24922, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24923, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24924, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24925, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24926, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24927, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24928, 'citicoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24929, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24930, 'sodium picosulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24931, 'sodium picosulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24931, 'magnesium oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24931, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'balsam peru');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'bismuth subgallate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'dexapanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'hamamelis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24936, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24937, 'cefepime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24938, 'cefepime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24939, 'pimozide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24940, 'pin bark');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24940, 'grape seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24941, 'psyllium husk powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24941, 'choromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24941, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24942, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'eruca oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24944, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24945, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24945, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24946, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24946, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24947, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24948, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24948, 'pioglitazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24949, 'glimepiride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (24949, 'pioglitazone');