INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7338, 'fenofibrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'omega 3 (epa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'dha)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7340, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7341, 'fenofibrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7342, 'cholecalciferol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'liquorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7343, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'l-lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7344, 'niacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7345, 'glucosamine sulfate 1325mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7345, 'chondroitin sulphate 500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7345, 'msm 200mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7345, 'collagen hydrolysate 200mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7346, 'methyl folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7346, 'methyl cobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7346, 'vitamin b(1-2-3-5-6)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7347, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7347, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'sodium lauryl sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'chamomilla recutita extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'melaleuca alternifolia leaf oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'citrus limon peel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'carboxymethyl hydroxyethylcellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'polysorbate 80');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'cetrimonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'propolis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'rosmarinus officinalis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'cocamidopropyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'hexamidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'tocopheryl acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'peg40');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'thymus vulgaris extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7348, 'perfume (herbal)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7349, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7350, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7352, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7353, 'vonoprazan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7355, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'beta-sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'cetyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'cetearyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'ceteareth-20');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'paraffinum liquidum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'chitosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'methylparaben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'aloe barbadensis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'disodium edta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7358, 'polysorbate 60.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7359, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'beta-sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'aloe barbadensis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'chitosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'methylparaben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'disodium edta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7360, 'polysorbate 60.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7361, 'progesterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b7(biotin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b9 (folate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7362, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'benfotiamine( potent vit b1)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'vitamin b9( folate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7363, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'folate (as l-5 methyl folate) other ingredients: microcrystalline cellulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'croscarmellose sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'hypromellose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'magnesium streate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'colloidal silicon dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'maltodextrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'polyethylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'talc powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'carmoisine red');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7366, 'sunset yellow color');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'rosmarinic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7368, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7372, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7379, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7379, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'alligator oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'eugenia caryophyllus bud water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'betula papyrifera bark extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'disodium edta');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'parfum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'anthemis nabilis flower extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'calendula officinalis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'argania spinosa kernel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'melaleuca alternifolia leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'aloe vera callus extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'elaeis guineensis oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'elaeis guineensis kernel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'thymol trimethoxycinnamate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7381, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7382, 'accelerated fat loss formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7384, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7384, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7384, 'soduim hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7384, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7384, 'allantion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7384, 'allium cepa bulb extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7385, 'aescin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7385, 'diethylamine salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7386, 'linagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7386, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7388, 'thioctic acid(alpha lipoic acid)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7389, 'alpha-lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7389, 'vitamin b 12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7389, 'vitamin b 6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7389, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7389, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7391, 'fenofibrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7393, 'fenofibrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7394, 'fusidic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7395, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7395, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7395, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7395, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7396, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7396, 'dha');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7396, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7397, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7398, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7399, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7400, 'cyanocobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7401, 'alpha amylase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7403, 'pravastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (7404, 'iron');