INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18734, 'tetrahydrozoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18735, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18735, 'glutathion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18735, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18735, 'coenzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18736, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18736, 'dry yeast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18737, 'dhe(omega3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18737, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18737, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18738, 'aflibercept');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18739, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18739, 'rose oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18739, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18739, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18739, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18739, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18740, 'fluorouracil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'rosmarinus officinalis extract (rosemary)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'hydrogenated potato starch');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'allium sativum bulb extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'magnesium sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'phenoxyethanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, '(camphora oil)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'eugenia caryophyllus cinnamomum camphora bark oil carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'eucalyptus globulus leaf oil (eucalyptus)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'laurocapram');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18741, 'aqua.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18744, 'khellin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18749, 'ambroxol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18750, 'bilastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18751, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18755, 'terazocin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18756, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18756, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18757, 'terazocin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18759, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18760, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18761, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18763, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18764, 'vitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18768, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18768, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18768, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18773, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18773, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18773, 'tilia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18773, 'black seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'chamomile oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18774, 'propyl pa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'tilia flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'anise oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18775, 'marshmallow root liquid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18776, 'echinacea root powder extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18776, 'black seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18777, 'echinacea purpurea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18778, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18778, 'cetrimide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18778, 'ethyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18779, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18779, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18779, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18779, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18779, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18779, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18780, 'ketorolac tromethamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18782, 'galantamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18783, 'galantamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18784, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18784, 'famotidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18784, 'magnesium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18785, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18785, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18785, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18785, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18787, 'sertraline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18789, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18789, 'flucloxacillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18792, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18792, 'famotidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18792, 'magnesium hydroxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18793, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18793, 'climbazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18793, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18793, 'hibiscus ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18793, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18794, 'butenafine hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18798, 'gentamicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18800, 'sodium cromoglycate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18801, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18802, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18803, 'ca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18803, 'mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18804, 'lactulose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18805, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18807, 'ammonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18807, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18809, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18810, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18811, 'amoxicillin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18812, 'piperazine theophylline ethanoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18814, 'captopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18816, 'hyoscin-n-butylbromid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18817, 'caspofungin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18818, 'hyoscin-n-butylbromid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18819, 'hyoscin-n-butylbromid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18821, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18822, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18825, 'domperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18828, 'domperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18829, 'equisetum arvense');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18829, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18829, 'thymus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18829, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18829, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18830, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18831, 'diloxanide furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18831, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18832, 'ibuprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18832, 'pseudoephedrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18833, 'dried onions extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18833, 'silicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18833, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18834, 'silver colloid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18834, 'hyaluronic acid sodic salt');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18836, 'epirubicin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18838, 'mefenamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18842, 'fulvestrant');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18844, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18844, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18844, 'irgasan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18844, 'emu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18846, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18846, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18846, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18846, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18846, 'jojoba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18846, 'hydrolyzed protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18848, 'mineral oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18848, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18848, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18848, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18848, 'propyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18849, 'hyoscine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18849, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18852, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18855, 'fexofenadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18856, 'fexofenadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18858, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18859, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18859, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18861, 'tolfenamic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18862, 'fexofenadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18863, 'fexofenadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18864, 'fexofenadine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18869, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18871, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18872, 'rifaximin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18873, 'rifaximin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18876, 'atracurium besylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18877, 'atracurium besylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18880, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18881, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18881, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18881, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18884, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18884, 'sodium bicarbonte');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18884, 'tartaric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18885, 'botanical ingredients');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18886, 'dexamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18888, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18889, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18890, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18892, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18895, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18896, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18898, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18899, 'piroxicam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (18905, 'felodipine');