INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32197, 'avocado oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32197, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'lactoferrin 100 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32198, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32199, 'ivy leaves extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32199, 'chamomile flower extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32199, 'ginger extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32200, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32200, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32200, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32200, 'c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32201, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'grape seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'wheat protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'liquorice ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32202, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'collagen type 2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'chondroitin sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'se');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'mn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'cu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'zn');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32203, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'ginkobiloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'vitd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'vitc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32204, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32205, 'rabeprazole sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32207, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32208, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32208, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32208, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32208, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32209, 'triple silicone blend (cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32209, 'polydimethylsiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32209, 'decamethyltetrasiloxane)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32209, 'silicone elastomer gel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32210, 'omega 3-6-9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32210, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32210, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32211, 'medical grade honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32211, 'cmc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32211, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32211, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32211, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32212, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32212, 'belsil eg2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'hydrolysed type 2 collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'glucosamine sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'chondroitin sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'ginger root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32213, 'selenium and folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32214, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32216, 'vonoprazan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32218, 'molnupiravir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32219, 'nebivolol hydrochloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32220, 'cholecalciferol 10mcg eq.to vit d3 400 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32221, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32222, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32223, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32224, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32225, 'methylcobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32225, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32225, 'pyridoxine hcl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32226, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32226, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32227, 'menaquinone-7=vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32228, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32229, 'menaquinone-7=vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32231, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32231, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32231, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32231, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32231, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32231, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32232, 'cholecalciferol 10mcg eq.to vit d3 400 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32233, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32233, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32233, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32233, 'beta-carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32233, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32234, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32235, 'thioctic acid(alpha lipoic acid)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32235, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32235, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32236, 'vardenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32243, 'human albumin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32244, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32245, 'potassium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32247, 'halothane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32251, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32251, 'omega-3 fatty acids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32253, 'undenatured collagen type ii-hyaluronic acid -boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32254, 'cyanocobolamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32254, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32254, 'thiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32257, 'green coffee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32257, 'raspberry ketone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32257, 'garcinia cambogia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32257, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32258, 'lacosamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32259, 'linoleic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32259, 'l.carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32259, 'garcinia cambogia extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32259, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32259, 'green coffee bean extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32260, 'water for injection');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32261, 'dill oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32261, 'sodium bicarbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32262, 'multy vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32263, 'indacaterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32263, 'glycopyrronium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32267, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32267, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32267, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32267, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32272, 'lercanidipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32274, 'liposomal iron 21mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32274, 'vitamin c 120 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32274, 'folic acid (dfe) 400 mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32274, 'vitamin b 12 0.375mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32275, 'fluconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32276, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32276, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32276, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32277, 'alpha lipoic acid 600 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32277, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32277, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32277, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32277, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32280, 'miglustat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'chlorhexidine digluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32281, 'sage oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32282, 'vitamin c 500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32282, 'vitamin d3 300 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32282, 'vitamin e 15 iu');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32282, 'vitamin b6 1mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32282, 'biotin 75mcg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32282, 'zinc 2.5mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32283, 'citicoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32284, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (32284, 'alpha arbutin');