INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1559, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1559, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1560, 'pure propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1561, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1567, 'liposomal vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1567, 'derma white');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1567, 'alpha arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1567, 'ceramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'ivy leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'thyme leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'grapefruit');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1568, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1572, 'clotrimazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1572, 'selenium sulfide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1572, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1575, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1576, 'vitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1578, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1578, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1578, 'vit.c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1578, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1578, 'co-q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1578, 'antioxidants');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1579, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'vitb1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'vitb6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'vitb2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'vitb12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'follic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'vitc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'lysine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1580, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1581, 'panthenol 5%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1581, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1581, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1581, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1581, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1584, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1584, 'follic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1584, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1584, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1584, 'vit b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1584, 'vit b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1586, 'biperidene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1587, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1588, 'bisacodyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1589, 'bisacodyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'silicon oxide e551');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'calcium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'vitd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1591, 'orange flavors');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1592, 'bisacodyl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1593, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1594, 'fenugreek');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1594, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1594, 'dill seed');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1594, 'caraway');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1595, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1598, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1599, 'dapagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1600, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1600, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1600, 'triethanolamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1600, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1600, 'methyl paraben');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1600, 'cetyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1601, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1601, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1601, 'molybdneum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1601, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1601, 'vitamins(a-b1--b12-c-e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1602, 'ferrous fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1602, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1602, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1603, 'bromhexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1604, 'bromhexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1605, 'bromhexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1606, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1607, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1609, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1610, 'bisoprolol fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1610, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1611, 'meropenem');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1613, 'neomycin-bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1614, 'bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1614, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1615, 'black cumin seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1616, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1616, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1618, 'bacitracin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1618, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1618, 'glycine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1618, 'l-cysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1618, 'dl-threonine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1622, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1622, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1627, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1627, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1627, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1628, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1629, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1629, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1630, 'quetiapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1631, 'atenolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1632, 'atenolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1633, 'atenolol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1633, 'chlorthalidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1637, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1637, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1640, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1640, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1640, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1640, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1640, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1640, 'thymus vulgaris');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1641, 'candesartan cilexetil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1641, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1642, 'acetylcysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1643, 'caffeine-l.carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1643, 'grape fruit');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1643, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1644, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1644, 'co q 10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1646, 'melatonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1647, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1647, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1647, 'salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1647, 'liposome');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1649, 'alfacalcidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1650, 'b9 folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1650, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1650, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1652, 'alendronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1653, 'probiotics');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1653, 'prebiotics');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'sulfur 5%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'salicylic acid 0.5%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'd-panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1654, 'wheat germ');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1655, 'alendronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1656, 'silver sulfadiazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1656, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'retinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'cucurbita pepo seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'olea europaea fruit oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'sesamum indicum seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1658, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1661, 'alfacalcidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1663, 'esomeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1664, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1664, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1664, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1664, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'thymus vulgaris oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'mentha piperita oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'curcuma longa rhizome oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'nigella sativa seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'boswellia carterii oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1666, 'arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1667, 'indomethacin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1669, 'green coffee extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1669, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1669, 'garcinia extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1670, 'alfacalcidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1674, 'ibandronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1676, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1676, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1676, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1678, 'atorvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1679, 'mometasone furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1680, 'mometasone furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1681, 'mometasone furoate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1682, 'clopidogrel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1684, 'sucralose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1684, 'dextrose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1686, 'aniracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1686, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1686, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1687, 'l carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1688, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1688, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (1688, 'phosphorus');