INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5906, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5906, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5906, 'vitamin b9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5906, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5906, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5907, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5907, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5907, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5907, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5907, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5907, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5908, 'vitamin c-iron-zinc-pantothinic acid -vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5908, '12-and other vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5909, 'sodium hyalourinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5909, 'dexpanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5910, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5910, 'licorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5910, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5911, 'calcium and vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'vitamins c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'choline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5912, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5916, 'haloperidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5919, 'haloperidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5920, 'haloperidol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'alamond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5921, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5922, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5922, 'k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5923, 'cod liver oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5923, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5926, 'lactobacillus reutri');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5926, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5927, 'progesterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5928, 'halothane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5929, 'povidone iodine 10%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5931, 'acetyl_l_carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5931, 'ginko biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5931, 'st.john wart');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5931, 'phosphatedylserine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5932, 'hammamelis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5934, 'vonoprazan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5936, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5937, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5937, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5937, 'liposomal salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5937, 'ceramide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5937, 'pentavitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'centella asiatica extracts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'squalane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'adenosine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'd-panthenol vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5938, 'zinc oxide copper gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'licuorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5941, 'titanium dioxi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'licuorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'glycolic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5942, 'gl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5944, 'd.i water-almond oil-hyaluronic acid-sodium stearyl sulfate- glycerin-shea butter-urea - olive oil-stearic acid-cetyl alcohol-perfume- d-panthenol-coconut oil-aloe vera extract- tocopheryl acetate (vit.e)-honey-dimethicone bht-propyl paraben-methyl paraben-menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'd-panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'almond');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'caster oils');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'arnica oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'turmeric');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5945, 'tea tree oil and vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5946, 'vitamins: vitamin c vitamin b1 (thiamine) vitamin b2 (riboflavin) vitamin b3 (niacin) vitamin b5 (pantothenic acid) vitamin b6 (pyridoxine) vitamin b7 (biotin) vitamin b9 (folate) vitamin b12 (cobalamin) minerals: iron zinc calcium magnesium potassium copper manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5947, 'vitamin k1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5948, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5950, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5951, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5952, 'avocado soyabean unsaponifisbles 300 mg ratio avocado -soybean');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5954, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5955, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5956, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5957, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5958, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5959, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5959, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5959, 'amla');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5959, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5959, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5959, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5960, 'palmitoylethanolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'l-menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'omega3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'magnesium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'vit.b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5963, 'tocopherol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5964, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5967, 'vitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5971, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5971, 'olmesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5972, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5972, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5972, 'methyl salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5972, 'terpentine oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5973, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5974, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5981, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5981, 'urea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5982, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5982, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5982, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5982, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'onion honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'calendula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'olive leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5983, 'rosehi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'onion honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'aleo vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'olive leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5984, 'rosehl');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'omega 3 6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5985, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5986, 'clarithromycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5986, 'omeprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5986, 'tinidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5987, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5987, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5987, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5987, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5989, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5989, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5989, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5989, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5989, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5990, 'menthol oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5990, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5990, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5990, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'omega 3 6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'avocado');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5991, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'ferrous fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (5992, 'folic acid');