INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'chlorohexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'bht');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'aloe barbodensis leaf powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'retinol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'hydrogenated peanut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'cocos nuclfera oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'nigella sativa seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'simmondesia chinensis seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'allum cepa bulb oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'rosmarinus officinalis leaf oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'triticum vulgare germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'calendula officinalis extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6798, 'chamomila recutta extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6799, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6799, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6799, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6799, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6800, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6800, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6800, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6801, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6802, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6803, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6805, 'sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6805, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6805, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6805, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6806, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6807, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6808, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6811, 'halfa bar extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6811, 'khellin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6812, 'sildenafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'natural isotonic sea water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'vit a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'aloevera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6813, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6814, 'diclofenac sodium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'myo_inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'vitaminc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'coq10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'alpha lipoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'd_chiro insitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'n_acetyle cystiene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'grape seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'resveratrol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'choline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'pantothenic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'ripoflavin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'beta_carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'thiamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'melatonin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'be nfotiamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'd3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6815, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6816, 'alpha lipolc acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6816, 'calcium (calclum carbonate)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6816, 'vitamin b1 (thiamine hydrochloride)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6816, 'docoahexaenolc acid 177');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6816, 'vitamin d3 (cholicalciferol)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6816, 'vitamin b12 (cyanocobalamin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6819, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6820, 'fish oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6820, 'omega 6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6820, 'gla');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6820, 'thyme oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6821, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6823, 'famotidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6824, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6825, 'famotidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6826, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'avocado extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'banana extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'calendula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6827, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6828, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6828, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6828, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6828, 'ginseng oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6828, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6828, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6829, 'romosozumab aqqg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6830, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6831, 'tamsulosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6833, 'gramicidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6833, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6833, 'nystatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6833, 'triamcinolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6834, 'gramicidin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6834, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6834, 'nystatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6834, 'triamcinolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6836, 'activated charcoal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6836, 'anise');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6836, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6837, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6838, 'triamcinolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6839, 'triamcinolone acetonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6840, 'triamcinolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6841, 'tirofiban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6843, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6844, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6845, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6846, 'multivitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6846, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6847, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6848, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vit b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vit b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vit b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vit b5 vit b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'vit e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'cupper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6849, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6850, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6851, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6852, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6853, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6854, 'levetiracetam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6856, 'niacinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6856, 'zinc pca');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6857, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6857, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6858, 'betamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6858, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6859, 'amiodarone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6860, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6861, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6862, 'dapoxetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6863, 'ivy leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6863, 'licorice root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6863, 'thyme leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6864, 'ketamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6865, 'ketamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'menthol crystals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'eucalyptus oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'avocado oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'punica granatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6866, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6867, 'ketoconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6868, 'ketoconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6869, 'ketoconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6870, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6871, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6875, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6876, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6877, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6878, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6879, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6880, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6881, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6884, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6885, 'ketorolac tromethamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6886, 'ketorolac tromethamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6887, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6888, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6889, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6890, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6891, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6893, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'calcium carbonate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6894, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6895, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6895, 'arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (6895, 'kojic acid');