INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'serrapeptase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'amylase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'lipase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'protease');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2161, 'papain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2162, 'vinpocetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2165, 'vinpocetine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2166, 'lyophilized fish roe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2166, 'ginko biloba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2171, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2171, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2172, 'ezetimibe');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2172, 'simvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2173, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2174, 'glucosamine sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2174, 'chondoritin sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2174, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2174, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2174, 'hyalouronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2175, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2176, 'etoricoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2177, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2180, 'cefaclor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2181, 'cefaclor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2182, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2184, 'cyclopentasiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2184, 'belsil eg2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2185, 'cefdinir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2186, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2186, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2186, 'boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2186, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2186, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2192, 'cefaclor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2193, 'cefaclor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2195, 'cefaclor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2196, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2197, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2202, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2203, 'cephradine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2205, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2206, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2207, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2207, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2207, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2208, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2208, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2208, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2209, 'cefdinir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2210, 'cefdinir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2214, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2216, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2217, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2218, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2220, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2222, 'oxymetazoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2224, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2225, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2225, 'sulbactam');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2226, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2226, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2226, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2226, 'alantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2226, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2227, 'rupatadine fumarate 12.8 mg equivalent to rupatadine 10.000 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2228, 'papain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2228, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2228, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2228, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2228, 'anise');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2229, 'cefdinir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2232, 'cefepime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2233, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2234, 'multivitamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2235, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2236, 'cefixime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2237, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2239, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2239, 'vitamin k2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2240, 'glucosamine sulfate 1500mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2240, 'chondroitin sulfate 1200mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2240, 'msm 1000mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2240, 'tumeric roots powder 100mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2240, 'boswellia serrata 100mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2240, 'hyaluronic acid 25 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2243, 'ivy leaf dry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2243, 'n-acetyl l-cysteine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2243, 'zinc gluconate (50 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2243, '50 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2243, '13.06 mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2243, '5 ml');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2244, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2249, 'cefoperazone 0.5 g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'peppermint extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'clove oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'eugenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'paraffinum liquid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2252, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2254, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2255, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2257, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2258, 'green cofee');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2258, 'green tea');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2258, 'garcinia');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2259, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2260, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2264, 'cefotaxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2268, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'glycerine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'mango butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'coconut butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'alovera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2269, 'alentoin .');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2270, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2273, 'cefpirome');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2274, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2276, 'cefpirome 1 g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2278, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2279, 'cefoperazone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2281, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2284, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'iron bisglycynat (30mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'lactofern(100mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'vit (c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2285, 'molybdenum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2286, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2287, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2289, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2291, 'ceftriaxone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2292, 'cefuroxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2293, 'cefuroxime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2294, 'cefprozil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2295, 'cefprozil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2297, 'cefprozil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2298, 'cefprozil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2300, 'cefprozil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2301, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2302, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2303, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'glycerine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'alovera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'd- panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'clandula oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2304, 'vitamin c.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2305, 'celecoxib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2310, 'trypsin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2310, 'rutosid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2310, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2310, 'l-leucine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2311, 'milk formula stage 1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'glycerine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'chamomile extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'alo vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'tyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'mentol crystal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'jojoba extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'phenoxy ethanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'perfume rose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2312, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2313, 'ivy leaf (90mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2313, 'n-acetyl l-cysteine (50mg)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2313, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'inositol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'choline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (2316, 'selenium');