INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16770, 'zonisamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16771, 'zonisamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16772, 'zonisamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16773, 'retigabine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16774, 'retigabine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16775, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16777, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16780, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16781, 'pregabalin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16782, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16784, 'sodium valproate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16785, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16785, 'lactil 1%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16785, 'chlorhexidine gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16785, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16786, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16786, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16786, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16787, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16790, 'sulphamethoxazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16790, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16792, 'heptaminol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16794, 'melatonin 2 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16794, 'l- theanine 50 mg');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16795, 'alcohol 95%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16795, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16795, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16795, 'licorice ex.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16795, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16795, 'vitamin a&e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16796, 'alcohol 70%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16796, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16796, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16796, 'glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16796, 'propylene glycol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16796, 'potassium aluminium sulfate dodecahyd');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16797, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16797, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16797, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16797, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16798, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16798, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16799, 'enalapril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16799, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16800, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16801, 'bepotastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16802, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16802, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16802, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16802, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16803, 'dexapanthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16806, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16806, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16806, 'acetic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16806, 'collodion');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16806, 'alpha hydroxy acids to adjust ph');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16807, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16808, 'isosorbide dinitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16810, 'nitroglycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'water');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'sodium lauryl sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'cocamidopropylderaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'laureth 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'glycoledistearate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16811, 'pirec');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16816, 'ramipril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16817, 'ramipril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16820, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16820, 'soybean oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16820, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16820, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16820, 'petrolatum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16821, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16821, 'sulfacetamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16830, 'clobetasol propionate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16833, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16833, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16833, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16834, 'eprosartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16835, 'secukinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16836, 'secukinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16837, 'dactinomycin(actinomycin d)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16838, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16841, 'rebamipide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16843, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16843, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16844, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16844, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16845, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16845, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16846, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16846, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16847, 'sulphamethoxazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16847, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16849, 'sulphamethoxazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16849, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16850, 'sulphamethoxazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16850, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16851, 'sulphamethoxazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16851, 'trimethoprim');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16855, 'guava leaves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16855, 'tilia flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16855, 'fennel oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16856, 'guaiacol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16856, 'pholcodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16858, 'gelsemium extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16858, 'grindelia extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16858, 'niaouli essence');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16858, 'paracetamol(acetaminophen)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16859, 'warfarin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16861, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16861, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16863, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16863, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16864, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16864, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16865, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16865, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16866, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16866, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16868, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16868, 'valsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16870, 'camphor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16870, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16870, 'menthol crystal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16871, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16871, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16873, 'amlodipine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16873, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16875, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16876, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16877, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16879, 'indapamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16879, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16881, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16881, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16881, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16881, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16881, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16883, 'indapamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16883, 'perindopril');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'grape seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16887, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'grape seed extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'vaseline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16888, 'lanolin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16889, 'massage cream formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16890, 'cranberry extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16891, 'cranberry');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16892, 'zinc pyrithione');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16892, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16892, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16892, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16892, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16892, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'aloe vera ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'thyme ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'rosemary ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'wheat germ ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'lavender ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'jojoba ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16894, 'vit.c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16895, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16895, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16895, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16895, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16895, 'lavender oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16895, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16896, 'octisalate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16896, 'octocrylene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16896, 'avobenzone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16896, 'homosalate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16896, 'green tea leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16896, 'cucumber extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16897, 'sumatriptan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16898, 'clindamycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (16898, 'tretinoin');