INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'catalase');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'horsetail extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'paba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'l-tyrosine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'beta sitosterol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'nettle root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3863, 'chlorophyllin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3865, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3866, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3867, 'calcium dobesilate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3867, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3868, 'calcium dobesilate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3868, 'dexamethasone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3868, 'lidocaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3869, 'dexlansoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3870, 'dexlansoprazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3872, 'calcium dobesilate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3876, 'doxycycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3877, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3879, 'doxycycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3880, 'risperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3886, 'dimenhydrinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3888, 'boron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3889, 'finerenone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3892, 'dha');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3892, 'epa(omega3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3892, 'lipid soluble vitamin (a d e k)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3894, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3894, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3896, 'eucalyptus extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3896, 'camphor extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3896, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3896, 'thyme extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3897, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'rosa damascena flower');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'chlorhexidine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'thymus vulgaris extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'aloe vera leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'chamomilla recutita extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3898, 'melaleuca alternifolia leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3900, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3900, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3900, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3900, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3900, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3901, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3901, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3901, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3901, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3902, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3902, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3903, 'empagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3903, 'metformin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3906, 'lactobacillus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3906, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3907, 'cabergoline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3908, 'dydrogesterone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3911, 'doxazosin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3912, 'benzathine penicillin g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3915, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3915, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3915, 'vitamin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3915, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3915, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3916, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3917, 'cefadroxil monohydrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3919, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3920, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3921, 'ginko biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3922, 'cefadroxil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3924, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3925, 'mebeverine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3926, 'isoxsuprine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3927, 'ruxolitinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3928, 'almitrine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3928, 'ranbexine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3929, 'methylcobalamin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3931, 'undenaturated collagen type 2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3931, 'turmeric rhizome powder');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3931, 'boswellia extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3931, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3931, 'msm');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3932, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3932, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3932, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3933, 'botulinum toxin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3935, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3936, 'palmitoylethanolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3939, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3940, 'palmitoylethanolamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3941, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3941, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3941, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3941, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3942, 'bismuth subcitrate potassium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3942, 'metronidazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3942, 'tetracycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'eicosapentaenoicacid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'docosahexaenoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3943, 'vit a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3944, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3944, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3944, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3944, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3944, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3944, 'thymus vulgaris');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3946, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3947, 'calcium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3947, 'magnesium citrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3947, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3947, 'vit d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3948, 'a moisturizer formula rich with calamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3948, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3948, 'panthenol &olive oil.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'methylcobalamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'b9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3949, 'vit.c.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3950, 'lactoferrin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3950, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3953, 'type ii collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3953, 'boron glycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3953, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3956, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3956, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3956, 'anise');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3956, 'bromelain');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3956, 'fennel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3956, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'common rue');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'arnica');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'clove');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'ginger');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'peppermint');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'sandal');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'white willow');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'saffron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3957, 'myrrh');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3958, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3959, 'type ii collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3959, 'boron glycinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3959, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'calendula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'vitamins (a-c-e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'green tea extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'paraffin oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'stearic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'cetyl alcohol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3962, 'methy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3963, 'antioxidants');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3963, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3965, 'sitagliptin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3966, 'cholecalciferol(vitamin d3)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3975, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3976, 'multivitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3976, 'minerals');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3979, 'econazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3984, 'isosorbide dinitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3985, 'herbal extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3986, 'calcium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3986, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3986, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3986, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (3986, 'manganese');