INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20887, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'capalgin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'hydrolyzed wheat protein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'hydrolyzed keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'procapil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'rosemary extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'plandool g');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20888, 'saw plametto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20889, 'eptifibatide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20891, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20892, 'olanzapine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'cetrmonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'phenoxy thanol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'garlic oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'provitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20893, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20894, 'interferon');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20895, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20896, 'nifuroxazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20897, 'nifuroxazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20902, 'sodium hyaluronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20903, 'immunoglobulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20904, 'immunoglobulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20905, 'immunoglobulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20907, 'egg phospholipids');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20907, 'soya bean oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20908, 'calcium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20908, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20908, 'magnesium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20908, 'sodium acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20908, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20908, 'sodi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20909, 'calcium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20909, 'glucose (dextrose)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20909, 'magnesium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20909, 'sodium acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20909, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20910, 'interferon alfa-2b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20911, 'interferon alfa-2b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20914, 'paliperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20916, 'paliperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20917, 'paliperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20918, 'paliperidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20919, 'jojoba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20919, 'caster oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20919, 'caffine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20919, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20920, 'canagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20921, 'canagliflozin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20922, 'ceftazidime');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20923, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20924, 'povidone- iodine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20927, 'ganciclovir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20929, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20930, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20931, 'phenytoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20932, 'hexoprenaline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20933, 'hexoprenaline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20934, 'ipratropium bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20935, 'ipratropium bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20936, 'ipratropium bromide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20936, 'salbutamol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'hydrolyzed collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'hydrolyzed elastin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'bees wax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'olive oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20937, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20938, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20941, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20942, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20942, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20943, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20943, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20944, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20945, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20946, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20946, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20947, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20947, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20950, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20952, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20953, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20953, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20954, 'hydrochlorothiazide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20954, 'irbesartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20957, 'gefitinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20958, 'irinotecan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20959, 'irinotecan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20960, 'irinotecan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20962, 'irinotecan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20965, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20965, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20965, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20965, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20965, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20965, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'molybdnum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'vitamin (b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20966, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20967, 'ferrous fumarate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20967, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20967, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20967, 'pyridoxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20967, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20967, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20968, 'polysaccharide iron complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20968, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20968, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20969, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20969, 'folic');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20969, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20969, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20969, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20969, 'betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20970, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20971, 'ferrous bisglycinate chelate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20971, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20971, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20971, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20972, 'ferrous bisglycinate chelate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20972, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20972, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20972, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20973, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20973, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20973, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'zinc vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'b-complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'magnesium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'chromium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20974, 'vitamin c.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20976, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20976, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20976, 'vitamin-b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20976, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20976, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20976, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'ferrous sulphate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'vitamin (b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20977, 'e)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20979, 'ammonium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20979, 'diphenhydramine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20980, 'isosorbide-5-mononitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20981, 'isosorbide-5-mononitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20985, 'sodium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20985, 'potassium chloride');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20985, 'potassium iodide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20986, 'isotretinoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20987, 'isoniazid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20988, 'isoniazid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20996, 'soy isoflavone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20997, 'isoflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20998, 'isoflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (20999, 'isoflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21000, 'isoflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21001, 'isoflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21002, 'isosorbide dinitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21007, 'isosorbide dinitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21008, 'isosorbide dinitrate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21009, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21009, 'polymyxin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21009, 'prednisolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21012, 'isoflurane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21014, 'isoprinosine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (21015, 'isoprinosine');