INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27417, 'calendula extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27417, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27417, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27418, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27418, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27418, 'camphor');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'vitamin c 10%');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'marine collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27420, 'caviar');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27421, 'itraconazole');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27423, 'chondroitin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27423, 'glucosamine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27424, 'fluocinolone acetonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27424, 'hydroquinone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27424, 'tretinoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27425, 'neomycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27425, 'triclosan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27427, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27428, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27429, 'topiramate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27431, 'dasatinib');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27432, 'menthol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27432, 'peg 400');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27432, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27434, 'idrocilamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27435, 'idrocilamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27436, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27437, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27438, 'gabapentin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'l-arginine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'l-carnitine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'selenium');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'co-enzyme q10');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'folate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27439, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27440, 'stavudine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27441, 'inulin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27442, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27442, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27442, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27443, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27443, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27443, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27444, 'carbidopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27444, 'entacapone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27444, 'levodopa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27445, 'vaccine yellow fever');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27446, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27447, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27448, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27450, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27450, 'chlorthalidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27451, 'azilsartan');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27451, 'chlorthalidone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27453, 'tigecycline');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'witch hazel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'butcher s broom');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'ivy');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'horse-chestnut');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'yarrow');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'great burnet');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'mullein');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'st. john s warts');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27454, 'white fi');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27455, 'sodium fusidate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27456, 'sodium fusidate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27457, 'hydrocortisone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27457, 'fucidic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27459, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27460, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27461, 'cefalexin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27462, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27463, 'tadalafil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'liquorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27464, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27465, 'nateglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27466, 'nateglinide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'lauryl glucoside');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27469, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'zinc oxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27472, 'aloe vera extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'collagen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'vitamin(e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'c)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'arbutin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'papaya');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'olive');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'licorice');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27473, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'licorice extract (glabridin)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27474, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27477, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27478, 'epinastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27479, 'orlistat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27480, 'rosuvastatin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'copper');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'molybdenum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'vitamins(b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b7');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b8');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b9');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'b12)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'beta-carotene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27481, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27482, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27483, 'montelukast');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27484, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27485, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27486, 'febuxostat');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27487, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27488, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27489, 'cilostazol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27490, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27491, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27492, 'betahistine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27493, 'ustekinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27494, 'ustekinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27495, 'ustekinumab');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27496, 'isopropamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27496, 'trifluoperazine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'iron');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27497, 'vit d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'salicylic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'sulphur');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'allantoin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27499, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'citric acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'vit c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'green tea ext');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'aloe vera ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'lemon ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'ginger ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'panax ginseng ex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27501, 'glyceri');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'limonene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27502, 'linalool');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'saw palmetto');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'biotin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'limonene');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27503, 'linalool');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (27506, 'purified water');