INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14914, 'polysiloxane');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14915, 'entecavir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14916, 'entecavir');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14918, 'hypericum');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14918, 'neem');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14924, 'ginkgo biloba');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14925, 'budesonide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14928, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14928, 'teflose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14928, 'hyaluronic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14932, 'barium sulfate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14933, 'methylsilanol hydroxyproline aspartate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14933, 'darutoside');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14933, 'tamanu oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14934, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14935, 'alendronate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14935, 'vitamin d3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14936, 'ketoprofen');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14937, 'ebastine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14938, 'apixaban');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14939, 'mesterolone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14940, 'diethylamine salicylate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14940, 'methyl nicotinate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14943, 'vitamin b');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'kojic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'chamomile');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'castor oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'tocopheryl acetate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14945, 'licorice extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14946, 'cocamidopropyl betaine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14946, 'chlorhexidine gluconate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'argan oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'caffeine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'panthenol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'keratin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'nigella sativa');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'ginseng');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14947, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14948, 'hydroquinone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14948, 'retinoic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14949, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14949, 'sage oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14949, 'almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14955, 'milk formula stage 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14956, 'milk formula stage 3');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14957, 'anti-regurgitation milk formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14958, 'extra care milk formula');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14959, 'carbomer');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14961, 'dimethicone');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin a');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin d');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14962, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14964, 'beclomethasone dipropionate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14965, 'beclomethasone dipropionate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14967, 'beclomethasone dipropionate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14968, 'calcium pantothenate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14968, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14968, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14968, 'vitamin b2');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14968, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14968, 'vitamin b12');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14970, 'vitamins');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14972, 'vitamin b complex');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14974, 'vitamin b1');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14974, 'vitamin b6');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14975, 'desvenlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14976, 'desvenlafaxine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14977, 'clarithromycin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14979, 'ivy extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14980, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14982, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14983, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14984, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'vegetable glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'aloe vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'pumpkin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'vitamins b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'c & e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14986, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'vera');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'pumpkin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'sweet almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'carrot oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'shea butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'provitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'royal jelly');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (14987, 'peppermint oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'vegetable glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'sodium stearate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'sodium cocoate (coconut oil soap base)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'peg-7 oleate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'sorbitol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'saccharum officinarum (sugar cane)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'aqua');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'maris sal (sea salt)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'salvia officinalis (sage) leaf extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15007, 'thymus vulgaris (thyme) leaf extra');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'sunflower oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'sweet almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'henna');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'honey');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'wheatgerm oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'nigella seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15011, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'sweet almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'sunflower oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'coconut oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'cocoa butter');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'pro-vitamin b5');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'vitamin e and gold particles. vegetable glycerine');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'mineral powder (titanium dioxide)');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'jojoba oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'henna');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15023, 'vitamin e.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'sweet almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'vegetable glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'henna');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'pumpkin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'damask rose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'nigella seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'olive leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'parsley');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'lemon peel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'licorice root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15024, 'carrot o');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'vegetable glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'kaolin clay');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'sea salt');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'sage');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'lemon peel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'thyme');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'peppermint essential oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'lavender');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'rosemary');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15037, 'cloves');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'sweet almond oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'vegetable glycerin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'beeswax');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'sesame oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'sodium lactate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'vitamin e');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'henna');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'pumpkin');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'vitamin c');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'damask rose');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'wheat germ oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'nigella seed oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'olive leaf');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'parsley');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'lemon peel');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'licorice root extract');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'lactic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15040, 'carrot o');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15041, 'bee propolis');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15041, 'folic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15041, 'nicotinamide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15041, 'ascorbic acid');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15041, 'zinc');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15041, 'manganese');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15044, 'calcium dobesilate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15045, 'calcium dobesilate');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'titanium dioxide');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'chamomile ext.');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'tea tree oil');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'eucalyptus');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'thymol');
INSERT OR REPLACE INTO med_ingredients (med_id, ingredient) VALUES (15046, 'lavender oil');