#!/bin/bash
set -e

# Configuration
INTERACTIONS_FILE="${INTERACTIONS_OUTPUT:-assets/data/drug_interactions.json}"
BACKUPS_DIR="assets/data/backups/"

# Configure Git
git config user.name "GitHub Actions Bot"
git config user.email "actions@github.com"

# Add files
echo "Adding files to git..."
git add "$INTERACTIONS_FILE"
git add "$BACKUPS_DIR"

# Check for changes
if git diff --staged --quiet; then
    echo "No changes to commit."
    exit 0
fi

# Prepare commit message
TODAY=$(date +%Y-%m-%d)
COMMIT_MSG_FILE="commit_msg.txt"

cat <<EOF > "$COMMIT_MSG_FILE"
🔄 Monthly update: Drug interactions from OpenFDA ($TODAY)

- Total interactions: ${INTERACTION_COUNT:-Unknown}
- Source: OpenFDA API
- Auto-generated by GitHub Actions
EOF

# Commit and Push
echo "Committing changes..."
git commit -F "$COMMIT_MSG_FILE"
git push

echo "✅ Changes committed and pushed successfully."
