* Orthostatic hypotension - ibuprofen can induce sodium retention and antagonize the effect of diuretics which has been reported to be beneficial for patients with severe orthostatic hypotension.[A1651]
* Dental pain - ibuprofen is used to manage acute and chronic orofacial pain.[A10901]
* Pain - ibuprofen is widely used to reduce minor aches and pains as well as to reduce fever and manage dysmenorrhea. It is very commonly used for the relief of acute indications such as fever and tension headaches.[A39092] It is also used to manage mild to moderate pain and moderate to severe pain as an adjunct to opioid analgesics.[L40208]
* Investigational uses - efforts have been put into developing ibuprofen for the prophylaxis of Alzheimer''s disease, Parkinson disease, and breast cancer.[A39092]', '6223004190001', '', 2026, '2022-05-14', CURRENT_TIMESTAMP),
(14397, 'Aaa', 'ششش', '', '104', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 745, '2022-09-07', CURRENT_TIMESTAMP),
(23943, 'Octotramadol 50mg 12caps.', 'اوكتوترامادول 50مجم 12 كبسولة', '', '13', 'Tramadol', 'October pharma', 'Cap', 'كبسولة', '', 'Analgesics.narcotic opioid', '50mg', 'Tramadol is approved for the management of moderate to severe pain in adults.[L9257,F4679]
Tramadol is also used off-label in the treatment of premature ejaculation.[A173986]', '', '', 967, '2022-07-23', CURRENT_TIMESTAMP),
(11655, 'Aaa', 'ششش', '', '20', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 793, '2023-04-19', CURRENT_TIMESTAMP),
(27139, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 659, '2022-07-09', CURRENT_TIMESTAMP),
(13190, 'Aaa', 'ششش', '', '18', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 675, '2022-08-03', CURRENT_TIMESTAMP),
(5576, 'Globacand 16mg 28 f.c. tab.', 'جلوباكاند 16مجم 28 قرص', '', '40', 'Candesartan cilexetil', 'Global napi pharmaceuticals', 'Tab', 'أقراص', '', 'Antihypertensive.arbs', '16mg', 'May be used as a first line agent to treat uncomplicated hypertension, isolated systolic hypertension and left ventricular hypertrophy. May be used as a first line agent to delay progression of diabetic nephropathy. Candesartan may be also used as a second line agent in the treatment of congestive heart failure, systolic dysfunction, myocardial infarction and coronary artery disease in those intolerant of ACE inhibitors.', '6223002140770', '', 967, '2022-12-30', CURRENT_TIMESTAMP),
(21841, 'Lincocin 600mg/2ml i.m./i.v. 3 amp', 'لينكوسين 600مجم /2مل عضل/وريد 3 امبول', '', '24', 'Lincomycin', 'Memphis > pfizer', 'Amp', 'أمبول', '', 'Antibiotic.macrolide', '600mg', 'Lincomycin is indicated for the treatment of serious bacterial infections by susceptible strains of streptococci, pneumococci, and staphylococci in patients who are allergic to penicillins or for situations in which a penicillin is deemed inappropriate. As with all antibacterial agents, lincomycin should only be used to treat infections proven or strongly suspected to be caused by susceptible bacteria.[L33214]', '6221050010496', '', 806, '2022-07-07', CURRENT_TIMESTAMP),
(19241, 'Flustat 20 tab.', 'فلوستات 20 قرص', '15', '34', 'Chlorpheniramine+paracetamol(acetaminophen)+pseudoephedrine', 'Hi-pharm', 'Tab', 'أقراص', '', 'Cold drugs', '', '', '6224001050176', '', 1981, '2025-03-12', CURRENT_TIMESTAMP),
(32175, 'Z-gest 20 caps', 'زي-جيست 20 كبسولة', '70', '100', 'Papain+bromelain', 'Organix > pivot', 'Cap', 'كبسولة', 'مكمل غذائى يساعد على تخفيف عسر الهضم والمغص والغازات والانتفاخات', 'Digestive enzymes', '', '', '', '', 5755, '2024-08-22', CURRENT_TIMESTAMP),
(22135, 'Lutone 25mg/ml i.m. 3 amp.', 'لوتون 25 مجم / 1 مل 3 امبول', '19.5', '30', 'Progesterone', 'Misr', 'Amp', 'أمبول', 'علاج هرموني', 'Progesterone supplement', '25mg', '**Gelatinized capsules**
The gelatinized capsules are indicated for use in the prevention of endometrial hyperplasia in non-hysterectomized postmenopausal women who are receiving conjugated estrogens tablets. They are also indicated for use in secondary amenorrhea [FDA label]. 
**Vaginal gel**
Progesterone gel (8%) is indicated as progesterone supplementation or replacement as part of an Assisted Reproductive Technology (“ART”) treatment for infertile women with progesterone deficiency.  The lower concentration progesterone gel (4%) is used in the treatment of secondary amenorrhea, with the use of the 8% concentration if there is no therapeutic response to the 4% gel [F3898].
**Vaginal insert**
This form is indicated to support embryo implantation and early pregnancy by supplementation of corpus luteal function as part of an Assisted Reproductive Technology (ART) treatment program for infertile women [F3901].
**Injection (intramuscular)**
This drug is indicated in amenorrhea and abnormal uterine bleeding due to hormonal imbalance in the absence of organic pathology, such as submucous fibroids or uterine cancer [F3907]. 
**Tablets, contraceptive**
The tablet form of progesterone in contraceptive formulations is indicated for the prevention of pregnancy [F3904].', '6221035016116', '', 1382, '2024-10-29', CURRENT_TIMESTAMP),
(4618, 'Faktu oint. 30 gm', 'فاكتو مرهم 30 جم', '53', '76', 'Cinchocaine+policresulen', 'Marcyrl co. > aug pharma', 'Oint', 'مرهم', '', 'Haemorrhoids', '30 gm', 'about cinchocaine an amide derivative most potent and toxic long-acting local anesthetics a local anaesthetic mechanism of action of cinchocaine cinchocaine is a local anesthetic. it works by blocking the pathway of pain signals along nerves.', '6223005461056', '', 6320, '2024-07-28', CURRENT_TIMESTAMP),
(27597, 'Sucra sweet 50 tab sugar', 'سوكرا سويت 50 اقراص', '', '15', 'Sucralose+lactose+croscarmellose+l-leucine', 'Amriya > safe pharma', 'Tab', 'أقراص', '', 'Sweetener', '', '', '', '', 703, '2022-07-18', CURRENT_TIMESTAMP),
(4940, 'Nolaver anti-scar gel 25 gm', 'نولافير للندبات انتي سكار جل 25 جرام', '195', '260', 'Silicone+onion ext.', 'Egyptian company for cosmetics', 'Gel', 'جل', 'جل لعلاج الندبات -- علاج الحروق واثارها -- تفتيح الجلد', 'Anti-scar', '25 gm', '', '6223012630995', '', 1005, '2025-07-29', CURRENT_TIMESTAMP),
(24004, 'Aaa', 'ششش', '', '20', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 725, '2022-11-13', CURRENT_TIMESTAMP),
(29419, 'Viscera 50mg 10 tab.', 'فيسرا 50مجم 10 اقراص', '', '3', 'Tiemonium methylsulphate', 'Amoun', 'Tab', 'أقراص', '', 'Antispasmodic', '50mg', 'tiemonium methylsulfate - treatment of acute intense or refractory painful syndromes with a spasmodic component. the use of noramidopyrine is only justified when its activity confers a real advantage over other analgesics. indications: smooth muscle spasm', '6221025019806', '', 1139, '2022-07-30', CURRENT_TIMESTAMP),
(14903, 'Bambedil 1mg/ml syrup 120ml', 'بامبيديل 1مجم/مل شراب 120 مل', '22', '32', 'Bambuterol', 'Western pharmaceuticals industries', 'Syrup', 'شراب', '', 'Bronchodilator.long acting beta 2 agonist', '1mg', 'For the prevention and reversal of bronchospasm in patients 12 years of age and older with asthma and reversible bronchospasm associated with bronchitis and emphysema.', '6224007308240', '', 1643, '2024-12-01', CURRENT_TIMESTAMP),
(6719, 'Fatroxim 200 mg 30 f.c. tab.', 'فاتروكسيم 200مجم 30 قرص', '', '243', 'Rifaximin', 'Atm pharmaceutical industries', 'Tab', 'أقراص', '', 'Travelers diarrhea', '200 mg', 'Rifaximin has multiple indications by the FDA: for the treatment of patients (≥12 years of age) with traveller''s diarrhea caused by noninvasive strains of Escherichia coli; for the reduction of overt hepatic encephalopathy recurrence in patients ≥18 years of age; and in May 2015 it was approved for irritable bowel syndrome with diarrhea (IBS-D) treatment in adult men and women.', '', '', 808, '2025-08-12', CURRENT_TIMESTAMP),
(18556, 'Esmopump 40mg 14 f.c. tabs.', 'ايزموبمب 40 مجم 14 قرص', '119', '172', 'Esomeprazole', 'Organopharma', 'Tab', 'أقراص', 'علاج عسر الهضم والتهاب وارتجاع المريء والحموضة المعوية والقضاء على بكتيريا هيليكوباكتر بيلوري (جرثومة المعدة) ومرض القرحة المعدية', 'Peptic ulcer.proton pump inhibitor', '40mg', 'Esomeprazole is indicated for the treatment of acid-reflux disorders including healing and maintenance of erosive esophagitis, and symptomatic gastroesophageal reflux disease (GERD), peptic ulcer disease, H. pylori eradication, prevention of gastrointestinal bleeds with NSAID use, and for the long-term treatment of pathological hypersecretory conditions including Zollinger-Ellison Syndrome.', '6224000908102', '', 5862, '2024-09-03', CURRENT_TIMESTAMP),
(30306, 'Charmalure hair spray 275 ml', 'شارمالور بخاخ سبراي للشعر 275 مل', '', '95', 'Vitamin e+rosemary+coconut oil+olive oil+tea tree oil+peppermint oil+camphor oil+garlic oil', '> xcel pharma', 'Spray', 'بخاخ', '', 'Hair care', '275 ml', 'For the treatment of vitamin A deficiency.', '', '', 1096, '2023-04-25', CURRENT_TIMESTAMP),
(19583, 'Gasmovac 5mg 20 tab. (n/a)', 'جاسموفاك 5مجم 20 قرص', '', '45', 'Mosapride', 'Delta pharma > advocure', 'Tab', 'أقراص', '', 'Selective 5ht4 agonist', '5mg', '', '6224009460021', '', 1275, '2022-12-05', CURRENT_TIMESTAMP),
(11914, 'Unistin 50mg vial for i.v. inf.', 'يونيستين 50مجم فيال وريد 50 مل', '208', '316', 'Cisplatin', 'Hikma specialized pharmaceuticals', 'Vial', 'فيال', 'مضاد للأورام والسرطان', 'Antineoplastic', '50mg', 'For the treatment of metastatic testicular tumors, metastatic ovarian tumors and advanced bladder cancer.', '6223003840068', '', 1297, '2024-12-05', CURRENT_TIMESTAMP),
(26325, 'Rotacarnite 1gm/5ml 5 i.v. amp.', 'روتاكارنايت 1جم/5مل 5 امبولات', '40', '65', 'L-carnitine', 'Delta grand pharma > rotabiogen for pharmaceutical invest.', 'Amp', 'أمبول', '', 'Antioxidant', '1gm', 'about l-carnitine dietary supplement amino acid derivative antioxidant. mechanism of action of l-carnitine carnitine is an essential co-factor of fatty acid metabolism in the heart liver and skeletal muscle. it is normally synthesised in the liver brain a', '', '', 973, '2025-05-26', CURRENT_TIMESTAMP),
(3649, 'Ventospan 120 ml syrup', 'فينتوسبان 120 مل شراب', '', '65', 'N-acetyle cysteine+ivy extract+propolis+msm+vit c', 'Gama pharma', 'Syrup', 'شراب', '', 'Mucolytic expectorant bronchodilator', '120 ml', '', '', '', 1386, '2025-04-28', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(27876, 'Taminil-n 12mg/ml susp. 60 ml', 'تامينيل ان 12مجم/مل شراب معلق 60مل', '183', '238', 'Oseltamivir', 'El nile.', 'Susp', 'معلق', 'مضاد للفيروسات يستخدم لعلاج الانفلونزا الفيروسية', 'Antiviral.release phase', '12mg', 'According to FDA prescribing information, oseltamivir is indicated for the treatment of acute, uncomplicated illness due to influenza A and B infection in patients 2 weeks of age and older who have been symptomatic for no more than 48 hours [F3094]. In particular, this agent is indicated in adults and children including full-term neonates who present with symptoms typical of influenza when influenza virus is circulating in the community. Efficacy has been demonstrated when treatment is initiated within two days of the first onset of symptoms.[F3097]
Oseltamivir is also indicated for the prophylaxis of influenza in patients one year and older [F3094]. Specifically, post-exposure prevention in individuals one year of age or older following contact with a clinically diagnosed influenza case when influenza virus is circulating in the community qualifies for such prophylactic therapy. Oseltamivir would only be indicated for post-exposure prevention of influenza in infants less than 1 year of age during a pandemic influenza outbreak. [F3097]', '6221077041213', '', 2259, '2025-01-18', CURRENT_TIMESTAMP),
(32640, 'Cholelage oral drops 30 ml', 'كوليلاج نقط فم 30 مل', '45', '65', 'Vitamin d3', 'Masa group', 'Drops', 'نقط', '', 'Vitamin d3 supplement', '30 ml', 'For the treatment of vitamin A deficiency.', '', '', 930, '2025-07-20', CURRENT_TIMESTAMP),
(25795, 'Regenax 10 gm 10 sachets', 'ريجيناكس 10 جم 10 اكياس', '', '160', 'Gelatin (collagen) hydrolysate+vitamin c', 'Pharmazad > biohealth company for medicines', 'Sachet', 'أكياس', 'علاج الروماتيزم -- تقليل الالام المفاصل و العظام -- تقليل الالتهابات للمفاصل و العظام -- الحفاظ علي السائل الغضروفي', 'Anti-rheumatic.osteoarthritis.anabolic agents', '10 gm', 'Gelatin is used for weight loss and for treating osteoarthritis, rheumatoid arthritis, and brittle bones (osteoporosis). Some people also use it for strengthening bones, joints, and fingernails. Gelatin is also used for improving hair condition and to shorten the recovery after exercise and sports-related injury [L2113]. Gelatin is used in preparations of foods, cosmetics, and medicine [L2113].
Plasma volume expander in hypovolaemic shock [L2115]. Haemostatic [L2115].
Gelatin-based hydrogels are being used in drug delivery and tissue engineering because they are able to promote cell adhesion and proliferation. In addition, these hydrogels can be used as wound dressings because of their attractive fluid absorbance properties. Manufacturing technologies such as ultraviolet stereolithography and two-photon polymerization can be used to prepare structures containing photosensitive gelatin-based hydrogels [L2111].', '', '', 4332, '2023-02-04', CURRENT_TIMESTAMP),
(2083, 'Norkibones 30 tablet', 'نوركيبونز 30 قرص', '', '85', 'Calcium+vit d3+mg+zn', 'Nork pharma', 'Tablet', 'أقراص', '', 'Calcium supplement', '', '', '', '', 1011, '2025-01-04', CURRENT_TIMESTAMP),
(164, 'Adeno sed b forte 3 amp.', 'ادينو سيد ب فورت 3 امبولات', '', '8', 'Adenosine triphosphate+cocarboxylase+nicotinamide+vitamin b12', 'Sedico', 'Amp', 'أمبول', '', 'Vitamins', '', 'For nutritional supplementation, also for treating dietary shortage or imbalance', '6221042416022', '', 1685, '2022-12-01', CURRENT_TIMESTAMP),
(26945, 'Digest 365 daily use 30 caps. (adrien gagnon)', 'دايجست 365 مستخدم يومي 30 كبسولة', '590', '690', 'Vegetable digestive enzyme complex (digezyme)', 'Egypharma', 'Cap', 'كبسولة', '', 'Digestive enzymes', '', '', '', '', 1501, '2024-07-25', CURRENT_TIMESTAMP),
(14147, 'Androcur 50mg 20 tab.', 'اندروكور 50مجم 20 قرص', '', '120', 'Cyproterone', 'Bayer schering > bayer healthcare', 'Tab', 'أقراص', '', 'Anti-androgen', '50mg', 'For the palliative treatment of patients with advanced prostatic carcinoma.', '', '', 2977, '2022-06-26', CURRENT_TIMESTAMP),
(29884, 'Zerit 15 mg 60 caps.', 'زريت 15مجم60 كبسولة', '', '1,250', 'Stavudine', 'Bristol-myers squibb', 'Cap', 'كبسولة', '', 'Antiviral.nucleoside', '15 mg', 'For the treatment of human immunovirus (HIV) infections.', '', '', 748, '2022-08-04', CURRENT_TIMESTAMP),
(27312, 'Sotaloc 160mg tabs.', 'سوتالوك 160مجم أقراص', '', '10', 'Sotalol', 'Alfacure pharmaceuticals', 'Tab', 'أقراص', '', 'Antiarrhythmias.class iii', '160mg', 'Sotalol is indicated to treat life threatening ventricular arrhytmias and maintain normal sinus rhythm in patients with atrial fibrillation or flutter.[Label] There are also oral solutions and intravenous injections indicated for patients requiring sotalol, but for whom a tablet would not be appropriate.[Label,L6373,L6376]', '', '', 1393, '2022-07-09', CURRENT_TIMESTAMP),
