(14715, 'Avene thermal spring water 150 ml', 'افين مياه الينابيع الحرارية المضادة للتهيج 150 مل', '230', '230', '', 'Pierre - fabre france > biotech egypt', 'Unknown', 'غير محدد', '', 'Skin care', '150 ml', 'avene thermal spring water soothes softens and calms skin. achieve maximum hydration with our large size bottle. ï¿½ soothes redness associated with inflammation ï¿½ calms itching sensations ï¿½ rich in silicate and trace elements ï¿½ low salt mineral con', '', '', 821, '2022-07-21', CURRENT_TIMESTAMP),
(26940, 'Sigmalip 20 mg 10 f.c.tab.', 'سيجماليب 20مجم 10 اقراص', '', '24', 'Atorvastatin', 'Sigma', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '20 mg', 'Atorvastatin is indicated for the treatment of several types of dyslipidemias, including primary hyperlipidemia and mixed dyslipidemia in adults, hypertriglyceridemia, primary dysbetalipoproteinemia, homozygous familial hypercholesterolemia, and heterozygous familial hypercholesterolemia in adolescent patients with failed dietary modifications.[A177397]
Dyslipidemia describes an elevation of plasma cholesterol, triglycerides or both as well as to the presence of low levels of high-density lipoprotein. This condition represents an increased risk for the development of atherosclerosis.[L6025] 
Atorvastatin is indicated, in combination with dietary modifications, to prevent cardiovascular events in patients with cardiac risk factors and/or abnormal lipid profiles.[A177397]
Atorvastatin can be used as a preventive agent for myocardial infarction, stroke, revascularization, and angina, in patients without coronary heart disease but with multiple risk factors and in patients with type 2 diabetes without coronary heart disease but multiple risk factors.[A177397]
Atorvastatin may be used as a preventive agent for non-fatal myocardial infarction, fatal and non-fatal stroke, revascularization procedures, hospitalization for congestive heart failure and angina in patients with coronary heart disease.[A177397]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '6221051013458', '', 1003, '2022-12-08', CURRENT_TIMESTAMP),
(5522, 'Ginso max 30 cap', 'جنسو ماكس 30 كبسولة', '', '84', 'Ginseng', 'China', 'Cap', 'كبسولة', 'لزيادة الوزن -- علاج النحافة الشديدة -- فيتامينات متعددة', 'Multivitamin', '', '', '', '', 9076, '2023-01-28', CURRENT_TIMESTAMP),
(13627, 'Rumaximap 60mg 30 f.c. tab', 'روماكسيماب 60مجم 30 قرص', '', '147', 'Etoricoxib', 'Apex pharma', 'Tab', 'أقراص', '', 'Nsaid.selective cox-2 inhibitors', '60mg', 'For the treatment of rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, chronic low back pain, acute pain and gout.', '6223003206628', '', 1738, '2022-08-31', CURRENT_TIMESTAMP),
(30437, 'Dupixent 200 mg 2 pref. syringe s.c.', 'دوبيكسنت 200مجم 2 سرنجة معبأة تحت الجلد', '24633', '54,192', 'Dupilumab', 'Sanofi > sanofi scientific office', 'Syringe', 'حقنة', '', '', '200 mg', 'In the US, dupilumab is indicated for the treatment of patients aged six months and older with moderate-to-severe atopic dermatitis whose disease is not adequately controlled with topical prescription therapies or when those therapies are not advisable.[L42005] In Europe and Canada, the drug for this indication is approved for patients aged six years and older.[L7192,L41439] In Europe, patients six to 11 years of age should have severe atopic dermatitis and be candidates for systemic therapy.[L7192] Dupilumab can be used with or without topical corticosteroids for this condition.[L7186,L41439]
Dupilumab is indicated as an add-on maintenance treatment of patients aged six years and older with moderate-to-severe asthma characterized by an eosinophilic phenotype or with oral corticosteroid dependent asthma. However, the drug is not indicated for relief of acute bronchospasm or status asthmaticus.[L7186,L7192,L41439]
Dupilumab is indicated as an add-on maintenance treatment in adult patients with inadequately controlled chronic rhinosinusitis with nasal polyposis.[L7186] In Canada and Europe, it is used with intranasal corticosteroids.[L7192,L41439]
In the US and Europe, dupilumab is also indicated for the treatment of adults and children aged 12 years and older weighing at least 40 kg with eosinophilic esophagitis (EoE), and adults with prurigo nodularis.[L7192,L41900,L43297]', '', '', 979, '2024-12-15', CURRENT_TIMESTAMP),
(26494, 'Sandimmun neoral 50mg 50 soft gelatin caps.', 'سانديميون نيورال 50مجم 50 كبسولة', '460', '828', 'Cyclosporin', 'Novartis', 'Cap', 'كبسولة', '', 'Immunosuppressants', '50mg', '', '', '', 12688, '2024-10-16', CURRENT_TIMESTAMP),
(18869, 'Fatestatin 20 mg 10 f.c.tab.', 'فاتستاتين 20 مجم 10 أقراص', '', '33', 'Atorvastatin', 'Egpi > sea pharm for pharmaceuticals', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '20 mg', 'Atorvastatin is indicated for the treatment of several types of dyslipidemias, including primary hyperlipidemia and mixed dyslipidemia in adults, hypertriglyceridemia, primary dysbetalipoproteinemia, homozygous familial hypercholesterolemia, and heterozygous familial hypercholesterolemia in adolescent patients with failed dietary modifications.[A177397]
Dyslipidemia describes an elevation of plasma cholesterol, triglycerides or both as well as to the presence of low levels of high-density lipoprotein. This condition represents an increased risk for the development of atherosclerosis.[L6025] 
Atorvastatin is indicated, in combination with dietary modifications, to prevent cardiovascular events in patients with cardiac risk factors and/or abnormal lipid profiles.[A177397]
Atorvastatin can be used as a preventive agent for myocardial infarction, stroke, revascularization, and angina, in patients without coronary heart disease but with multiple risk factors and in patients with type 2 diabetes without coronary heart disease but multiple risk factors.[A177397]
Atorvastatin may be used as a preventive agent for non-fatal myocardial infarction, fatal and non-fatal stroke, revascularization procedures, hospitalization for congestive heart failure and angina in patients with coronary heart disease.[A177397]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '', '', 1046, '2022-07-13', CURRENT_TIMESTAMP),
(14326, 'Aaa', 'ششش', '', '70', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 597, '2022-09-07', CURRENT_TIMESTAMP),
(304, 'Alexoprine 75mg 100 chew. tab.', 'اليكسوبرين 75مجم 100 قرص مضغ', '7.5', '140', 'Aluminium aspirin', 'Alexandria', 'Tab', 'أقراص', 'مسكن للآلام', 'Nsaid', '75mg', 'description: belongs to a group of medicines called non-steroidal anti-inflammatory drugs (nsaids) indication: mild to moderate pain including headache migraine nerve pain (neuralgia) toothache sore throat period pain. relieving aches pains and fever asso', '6223000170618', '', 6326, '2024-10-26', CURRENT_TIMESTAMP),
(32123, 'Rifaxerose 550 mg 10 f.c. tabs.', 'ريفاكسيروز 550مجم 10 اقراص', '', '82', 'Rifaximin', 'Averroes pharma', 'Tab', 'أقراص', 'يستخدم فى علاج متلازمة القولون العصبي المصحوبة بالإسهال.الحد من خطر تكرار اعتلال الدماغ الكبدي.', 'Travelers diarrhea', '550 mg', 'Rifaximin has multiple indications by the FDA: for the treatment of patients (≥12 years of age) with traveller''s diarrhea caused by noninvasive strains of Escherichia coli; for the reduction of overt hepatic encephalopathy recurrence in patients ≥18 years of age; and in May 2015 it was approved for irritable bowel syndrome with diarrhea (IBS-D) treatment in adult men and women.', '', '', 1501, '2023-04-23', CURRENT_TIMESTAMP),
(29314, 'Vilazoprine 10 mg 10 tabs', 'فيلازوبرين 10مجم 10 اقراص', '', '33', 'Vilazodone', 'Eva pharma > horus for pharmaceutical products', 'Tab', 'أقراص', '', 'Antidepressant.selective serotonin reuptake inhibitor', '10 mg', 'Vilazodone is approved for treatment of major depressive disorder.[Label,A38477,A177622]', '', '', 1123, '2022-07-15', CURRENT_TIMESTAMP),
(29044, 'Vatex cream 50 gm', 'فاتكس كريم 50 جم', '99', '149', 'Vitamin c+liquorice extract+kojic acid+vitamin e+allantoin+glycerin+royal jelly+honey', 'Hi-care > rony pharma', 'Cream', 'كريم', 'كريم التفتيح.', 'Whitening topical', '50 gm', 'For the treatment of vitamin A deficiency.', '', '', 2145, '2025-08-15', CURRENT_TIMESTAMP),
(28187, 'Bronchomez syrup 120 ml', 'برونكوميز شراب 120 مل', '50', '60', 'Ivy+thyme+licorice', 'Nature care', 'Syrup', 'شراب', 'مكمل غذائى مضاد للسعال ودعم الجهاز التنفسي وتخفيف اعراض البرد', 'Cough syrup', '120 ml', '', '6225000490222', '', 840, '2025-08-16', CURRENT_TIMESTAMP),
(30438, 'Dupixent 300 mg 2 pref. syringe s.c.', 'دوبيكسنت 300مجم 2 سرنجة معبأة تحت الجلد', '24633', '54,192', 'Dupilumab', 'Sanofi > sanofi scientific office', 'Syringe', 'حقنة', '', '', '300 mg', 'In the US, dupilumab is indicated for the treatment of patients aged six months and older with moderate-to-severe atopic dermatitis whose disease is not adequately controlled with topical prescription therapies or when those therapies are not advisable.[L42005] In Europe and Canada, the drug for this indication is approved for patients aged six years and older.[L7192,L41439] In Europe, patients six to 11 years of age should have severe atopic dermatitis and be candidates for systemic therapy.[L7192] Dupilumab can be used with or without topical corticosteroids for this condition.[L7186,L41439]
Dupilumab is indicated as an add-on maintenance treatment of patients aged six years and older with moderate-to-severe asthma characterized by an eosinophilic phenotype or with oral corticosteroid dependent asthma. However, the drug is not indicated for relief of acute bronchospasm or status asthmaticus.[L7186,L7192,L41439]
Dupilumab is indicated as an add-on maintenance treatment in adult patients with inadequately controlled chronic rhinosinusitis with nasal polyposis.[L7186] In Canada and Europe, it is used with intranasal corticosteroids.[L7192,L41439]
In the US and Europe, dupilumab is also indicated for the treatment of adults and children aged 12 years and older weighing at least 40 kg with eosinophilic esophagitis (EoE), and adults with prurigo nodularis.[L7192,L41900,L43297]', '', '', 1101, '2024-12-11', CURRENT_TIMESTAMP),
(25677, 'Aaa', 'ششش', '', '9', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 830, '2022-07-30', CURRENT_TIMESTAMP),
(27606, 'Suganorm 15/850 mg 21 f.c. tabs.', 'سوجانورم 15/850مجم 21 اقراص', '', '23', 'Metformin+pioglitazone', 'Mepaco', 'Tab', 'أقراص', '', 'Anti-diabetic.sensitizers.combined glitazone +biguanide', '850 mg', '', '', '', 785, '2022-07-21', CURRENT_TIMESTAMP),
(1821, 'Ventamor soap 60 gm', 'فينتامور صابونة 60 جم', '', '80', 'Licuorice extract+vitamin c+salicylic acid+glutathione+sulfur+aloe vera', 'Prime pharma', 'Soap', 'صابون', '', 'Soap', '60 gm', '', '6224011686037', '', 701, '2022-08-17', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(32478, 'Azithromycin-aug 500 mg 6 f.c.tabs.', 'ازيثرومايسين -ايه يو جي 500 مجم 6 قرص', '87', '126', 'Azithromycin', 'Aug pharma', 'Tab', 'أقراص', '', 'Antibiotic.macrolide', '500 mg', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '6223005465573', '', 1405, '2024-07-04', CURRENT_TIMESTAMP),
(9119, 'Occufloxine 0.3% eye drops 5ml', 'اوكيوفلوكسين 0.3 % قطرة للعين 5مل', '', '8', 'Ofloxacin', 'El nile.', 'Drops', 'نقط', '', 'Antibiotic.quinolone', '0.3%', 'For the treatment of infections (respiratory tract, kidney, skin, soft tissue, UTI), urethral and cervical gonorrhoea.', '6221077063413', '', 843, '2022-12-07', CURRENT_TIMESTAMP),
(9740, 'Happy sens cream', 'هابي سينس كريم', '', '55', 'Panthovera+panthenol+honey', 'Pharma trade', 'Cream', 'كريم', '', '', '', '', '', '', 1327, '2022-08-15', CURRENT_TIMESTAMP),
