(14767, 'Avivapril 10/12.5 mg 28 tabs.', 'افيفابريل 10/12.5 مجم 28 قرص', '', '54', 'Hydrochlorothiazide+ramipril', 'Marcyrl co. > ecco pharm-egypt', 'Tab', 'أقراص', '', 'Antihypertensive.combined ace with diuretic', '12.5 mg', 'this combination product contains two active ingredients: ramipril and hydrochlorothiazide. ramipril belongs to the class of medications called ace inhibitors. it works by relaxing blood vessels and by making the heart pump more efficiently. hydrochloroth', '', '', 950, '2022-07-20', CURRENT_TIMESTAMP),
(20142, 'Haemodialysis concentrate (formula 1013)', 'هيمودياليسيس (محلول غسيل الكلى) مركز فورميولا 1013', '', '79', 'Haemodialysis solution', 'El nasr', 'Unknown', 'غير محدد', '', 'Sterile solution', '', 'the concentrated haemodialysis solutions are electrolyte water solutions with or without glucoses used in the haemodialysis process for patients with non-functioning kidneys.', '', '', 817, '2022-07-18', CURRENT_TIMESTAMP),
(19736, 'Genteal eye gel 10 gm', 'جينتيال جل للعين 10 جم', '', '30', 'Carbomer+hypromellose', 'Excelvision ag switzerland > united company for trading & distribution', 'Gel', 'جل', 'مرطب للعين.', 'Eye lubricant', '10 gm', 'mechanism of action hydroxypropyl cellulose is a derivative of cellulose that is soluble in both water and organic solvents. it is particularly good at trapping water and producing a film that serves as a barrier to water loss. hydroxypropyl cellulose pos', '5413895025785', '', 1128, '2022-12-05', CURRENT_TIMESTAMP),
(2090, 'Care by care cream 3 in 1 shampoo 300 ml', 'كير باي كير كريم 3 في 1 شامبو 300 مل', '', '115', 'Zinc oxide+olive oil+vitamin e+vitamin a+chamomile oil+thyme oil+tea tree oil+wheat germ oil', 'Macro group pharmaceuticals', 'Amp', 'أمبول', '', 'Soothing topical', '300 ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 1251, '2023-08-03', CURRENT_TIMESTAMP),
(17251, 'Dentinox 0.33% teething gel 10 gm', 'دينتينوكس 0.33% جل تسنين 10 جم', '', '45', 'Cetylpyridinium chloride+lidocaine', 'D d d > interpharma', 'Gel', 'جل', '', 'Oral care', '0.33%', 'Typically employed as the cetylpyridinium chloride salt, this compound is commonly used as an active ingredient in various over-the-counter mouthwashes, toothpastes, lozenges, and mouth sprays where it is generally indicated for antiseptic actions, gingivitis and plaque prevention, as well as action or prevention against some other oropharyngeal bacterial infections [A24813, L2754, L2755].', '50984527', '', 2007, '2023-07-27', CURRENT_TIMESTAMP),
(17425, 'Dexanocorten 8mg/2ml 3 amp', 'ديكسانوكورتين 8 مجم/2مل 3 امبولات', '19.5', '30', 'Dexamethasone sodium phosphate', 'Memphis > pharopharma', 'Amp', 'أمبول', 'كورتيزون', 'Glucocorticoid', '8mg', 'Dexamethasone and [ciprofloxacin] otic suspension is indicated for bacterial infections with inflammation in acute otitis media and acute otitis externa.[L10698] Intramuscular and intravenous injections are indicated for a number of endocrine, rheumatic, collagen, dermatologic, allergic, ophthalmic, gastrointestinal, respiratory, hematologic, neoplastic, edematous, and other conditions.[L10701] Oral tablets are indicated for the treatment of multiple myeloma.[L10710] An intravitreal implant is indicated for some forms of macular edema and non-infectious posterior uveitis affecting the posterior of the eye.[L10719] Various ophthalmic formulations are indicated for inflammatory conditions of the eye.[L10704,L10707,L10713,L10716,L10722,L10725]', '6221094050014', '', 2040, '2024-08-01', CURRENT_TIMESTAMP),
(22070, 'Oxitruhans 30 caps', 'اوكسيتروهانز 30 كبسولة', '', '169', 'Biotin+vitamin d3+zinc+selenium+vitamin e', 'Medcare pharmaceuticals', 'Cap', 'كبسولة', '', 'Multivitamin for skin hair and nails', '', '', '', '', 830, '2022-11-30', CURRENT_TIMESTAMP),
(9462, 'Otrivin 0.1% adult nasal spray 10 ml', 'اوتريفين بخاخ انف للكبار سبراي', '16', '32', 'Xylometazoline', 'Novartis > glaxo smithkline', 'Spray', 'بخاخ', 'مضاد احتقان - مزيل احتقان الانف', 'Nasal congestion.adrenergic alpha-agonist', '0.1%', 'Xylometazoline is indicated for the temporary relief of nasal congestion due to cold, hay fever or other respiratory allergies.[L31598]', '6223002640539', '', 12040, '2024-11-26', CURRENT_TIMESTAMP),
(27024, 'Simvastimibe 10/40mg 30 tabs.', 'سيمفاستيميب 10/40مجم 30 قرص', '', '75', 'Ezetimibe+simvastatin', 'Eva pharma', 'Tab', 'أقراص', '', 'Antihyperlipidemic.cholesterol absorption inhibitors.combined with statin', '40mg', 'about ezetimibe cholesterol absorption inhibitor 2-azetidinone derivative hypolipidemic agent. mechanism of action of ezetimibe it reduces the absorption of cholesterol from the intestine by localising at the brush border of the small intestine where it i', '6223002453825', '', 901, '2022-12-08', CURRENT_TIMESTAMP),
(3374, 'Defucin h topical cream 30 gm', 'ديفيوسين ه 30جم كريم', '', '29', '', 'Debeiky', 'Cream', 'كريم', '', 'Antibiotic with glucocorticoid', '30 gm', 'about hydrocortisone systemic synthetic glucocorticoid anti-inflammatory mechanism of action of hydrocortisone the drug exerts it`s pharmacological action by penetrating and binding to cytoplasmic receptor protein and causes a structural change in steroid', '6224000873134', '', 853, '2022-12-04', CURRENT_TIMESTAMP),
(17335, 'Dermalex repair psoriasis cream 60 gm', 'ديرمالكس كريم علاج الصدفية 60 جم', '', '110', '', 'Chefaro > star international company', 'Cream', 'كريم', 'يستخدم لعلاج الأكزيما والصدفية، والتهاب الجلد التماسي، والتخفيف من الأعراض التي تصاحبها.', 'Psoriasis', '60 gm', '** dermalexï¿½ repair psoriasis: - skin adjuvant therapy - psoriasis - reduces scaling itching & inflammation - accelerates the recovery of the skin s barrier - cortisone free - developed by dermatologists - suitable for psoriasis vulgaris ** instructions', '', '', 1255, '2022-07-13', CURRENT_TIMESTAMP),
(7595, 'Lucidril 250 mg 20 f.c.tabs.', 'لوسيدريل 250 مجم 20 قرص', '44', '92', 'Meclofenoxate', 'Mina pharm > lipha sante-france', 'Tab', 'أقراص', 'يحسن الدورة الدموية للمخ', 'Cerebral circulatory inhancer', '250 mg', '', '6222003700280', '', 4005, '2024-08-29', CURRENT_TIMESTAMP),
(5929, 'Septomerge 10%antiseptic solution 60ml', 'سيبتوميرج 10% محلول مطهر 60 مل', '', '60', 'Povidone iodine 10%', 'Merge pharma', 'Solution', 'محلول', '', 'Antiseptic solution', '10%', 'When in complex with iodine, indicated for inducing antisepsis for prevention of infection in minor cuts, scrapes, and burns.', '', '', 760, '2023-02-03', CURRENT_TIMESTAMP),
(23515, 'New akim hair oil 60ml', 'نيو اكيم زيت للشعر 60مل', '65', '80', 'Tea tree oil+lavender oil+rosemary oil+thyme oil+olive oil+vitamin e', 'Hi-care > prima pharm', 'Hair oil', 'زيت شعر', '', 'Hair care', '60ml', 'Indicated for topical use to help protect against infection in minor cuts, scrapes, and burns. No FDA-approved therapeutic indications.', '6224008966289', '', 1317, '2025-06-29', CURRENT_TIMESTAMP),
(33180, 'Mellitofix trio 10/5/1000 mg 30 f.c. tabs.', 'ميليتوفيكس تريو 10/5/1000مجم 30 قرص', '297', '486', 'Empagliflozin+linagliptin+metformin', 'Eva pharma', 'Tab', 'أقراص', '', 'Antidiabetic combinations', '1000 mg', 'it is a prescription medicine used along with diet and exercise to lower blood sugar in adults with type 2 diabetes alone or along with other antidiabetic medicines and also to reduce the risk of cardiovascular death in adults with type 2 diabetes who hav', '6223007357494', '', 937, '2023-09-28', CURRENT_TIMESTAMP),
(25435, 'Protostop 500mg 6 f.c. tab.', 'بروتوستوب 500مجم 6 قرص', '14.4', '19', 'Nitazoxanide', 'October pharma', 'Tab', 'أقراص', 'علاج الإسهال الناجم عن بعض أنواع العدوى الطفيلية, والاسهال الذي يعرف بإسم(إسهال المسافر)', 'Antihelminthic', '500mg', 'For the treatment of diarrhea in adults and children caused by the protozoa <i>Giardia lamblia</i>,  and for the treatment of diarrhea in children caused by the protozoan,  <i>Cryptosporidium parvum</i> [FDA label].
Nitazoxanide has not been shown to be superior to placebo medication for the management of diarrhea caused by Cryptosporidium parvum in patients with HIV/immunodeficiency [FDA label, A31973, A31976].', '6221088010956', '', 1277, '2024-04-27', CURRENT_TIMESTAMP),
(18633, 'Aaa', 'ششش', '', '16', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 735, '2023-01-07', CURRENT_TIMESTAMP),
(25836, 'Relaxiged 20 caps', 'ريلاكسيجيد 20 كبسولة', '21', '46', 'Chlorzoxazone+paracetamol(acetaminophen)', 'Jedco int. co. for pharmaceuticals', 'Cap', 'كبسولة', '', 'Muscle relaxant', '', '', '6224009747528', '', 1063, '2024-12-14', CURRENT_TIMESTAMP),
(16369, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 657, '2022-07-26', CURRENT_TIMESTAMP),
(30204, 'Blefaritto eye contour pad 24 pcs', 'بلفاريتو كونتور للعين لاصقات 24 قطعة', '', '200', 'Tea tree oil', 'Jeomed pharmaceuticals > ultra vision', 'Unknown', 'غير محدد', 'لاصقات تحتوى على خلاصة الشاى الاخضر مضاد للاكسدة ومحاربة علامات تقدم العمر وتقليل الانتفاخات وعلاج الهالات حول العين', 'Skin care.eye contour', '', 'Indicated for topical use to help protect against infection in minor cuts, scrapes, and burns. No FDA-approved therapeutic indications.', '', '', 1593, '2023-06-04', CURRENT_TIMESTAMP),
(21556, 'Lakotta post laser cream 50 gm', 'لاكوتا بوست ليزر كريم 50 جم', '75', '160', 'Chamomile+calendula+hyaluronic acid+honey+rosemary+aloe vera+sage oil+avocado oil+tea tree oil+glycerin+panthenol', 'Cosmopack > impact', 'Cream', 'كريم', '', 'Healing topical', '50 gm', 'use: apply thin layer of cream on the skin and rub gently until fully absorbed.', '', '', 920, '2025-07-04', CURRENT_TIMESTAMP),
(6906, 'Dozova woman max 30 f.c. tabs.', 'دوزوفا وومن ماكس 30 قرص', '', '260', '', 'Zeta pharma', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '6223015000238', '', 774, '2025-08-16', CURRENT_TIMESTAMP),
(26095, 'Rilastil acnilaude k emulsion 30 ml', 'ريلاسيل اكنيلود ك ايمولشن 30مل', '', '276', '', 'Rilastil laboratori milano > vamer pharma', 'Unknown', 'غير محدد', '', 'Skin care', '30 ml', 'product details smoothing and repairing treatment anti-imperfections for oily and acne-prone skins. rapidly removes skin impurities and soothes redness. micro-exfoliating action. non comedogenic. clinically and dermatologically tested. use after cleansing', '', '', 457, '2022-08-06', CURRENT_TIMESTAMP),
(13163, 'Lumicasage cream 60 gm', 'لوميكاساج كريم 60 جم', '', '70', 'Camphor+menthol+peppermint oil+clove oil', 'Brother pharma', 'Cream', 'كريم', '', 'Massage', '60 gm', '', '6224009344161', '', 995, '2024-05-14', CURRENT_TIMESTAMP),
(18859, 'Faster gel 50 gm', 'فاستر جل 50 جم', '', '10', 'Menthol+camphor', 'Al esraa pharmaceutical optima', 'Gel', 'جل', '', 'Massage', '50 gm', 'massage gel', '6224002702050', '', 1246, '2022-12-09', CURRENT_TIMESTAMP),
(26, 'Abimol extra 20 tab.', 'ابيمول اكسترا 500مجم 20 قرص', '16', '28', 'Caffeine+paracetamol', 'Glaxo smithkline', 'Tab', 'أقراص', 'مسكن وخافض حرارة', 'Analgesic.antipyretic.headache', '', 'mechanism: it is thought paracetamol reduces fever by affecting an area of the brain that regulates our body temperature (the hypothalamic heat-regulating center). paracetamol is about as effective as aspirin or ibuprofen at relieving mild to moderate pai', '6221045011101', '', 8418, '2024-10-30', CURRENT_TIMESTAMP),
(28710, 'Mb-steel 20 hard gelatin capsules', 'ام بي ستيل 20 كبسولة', '70', '120', 'Iron+vitamin c+vit b3+vit b6+vit b1+vit b12+folic acid', 'Mb pharma', 'Capsule', 'كبسولة', '', 'Multivitamin', '', '', '6224010115101', '', 1175, '2025-07-20', CURRENT_TIMESTAMP),
(18149, 'Aaa', 'ششش', '', '20', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 654, '2022-08-05', CURRENT_TIMESTAMP),
(27218, 'Sofolanork 400mg 28 tablets', 'سوفولانورك 400مجم 28 اقراص', '', '900', 'Sofosbuvir', 'Mash premiere', 'Tablet', 'أقراص', '', 'Antiviral', '400mg', 'Sofosbuvir is used in combination therapy with other antiviral medications to treat chronic hepatitis C virus (HCV) infected patients with HCV genoptypes 1-6, and to treat HCV and HIV co-infected patients. Depending on the level of cirrhosis or decompensation, combination therapy can also include either ribavirin alone or ribavirin and peg-interferon alfa.
When used in combination with [DB09027], sofosbuvir has the following indications: treatment of genotypes 1, 4, 5, or 6 infection without cirrhosis or with compensated cirrhosis; in combination with [DB00811] for genotype 1 infection with decompensated cirrhosis; or in combination with [DB00811] for the treatment of genotype 1 or 4 infection who are liver transplant recipients without cirrhosis or with compensated cirrhosis.
When used in combination with [DB11613] as the combination product Epclusa, sofosbuvir is indicated for the treatment of adult patients with chronic hepatitis C virus (HCV) genotypes 1, 2, 3, 4, 5, or 6 infection without cirrhosis or with compensated cirrhosis, or in combination with [DB00811] if associated with decompensated cirrhosis.
Resistance: Reduced susceptibility to sofosbuvir has been associated with the NS5B substitution mutation S282T [A19634].', '', '', 1785, '2022-07-30', CURRENT_TIMESTAMP),
(18435, 'Epinephrine-memphis 1 mg/ml 5 i.m./s.c. amp.', 'ابينفرين ممفيس 1مجم /مل 5 امبولات', '', '10', 'Adrenaline', 'Memphis', 'Amp', 'أمبول', 'علاج حالات الحساسية المفرطة', 'Alpha and beta adrenergic agonist', '1 mg', 'about adrenaline alpha and beta adrenergic agonist catecholamine vasoconstrictor. anti asthma inanaphylatic shock. mechanism of action of adrenaline adrenaline is an alpha and beta adrenergic agonist which exerts it`s therapeutic actions through predomina', '', '', 1228, '2023-05-04', CURRENT_TIMESTAMP),
(29123, 'Ventobronchal plus 20 tab.', 'فينتوبرونكال بلس 20 ق', '', '5', 'Dyphylline+guaifenesin', 'Sepco pharmaceutical co.', 'Tab', 'أقراص', 'علاج الكحة -- علاج ضيق التنفس -- علاج الربو', 'Cough drugs', '', 'indication for relief of acute bronchial asthma and for reversible bronchospasm associated with chronic bronchitis and emphysema. pharmacodynamics dyphylline a xanthine derivative is a bronchodilator used for relief of acute bronchial asthma and for rever', '', '', 801, '2022-05-22', CURRENT_TIMESTAMP),
(16968, 'Cutasone 0.05% oint. 20 gm', 'كيوتازون 0.05% مرهم 20 جرام', '', '13', 'Fluticasone propionate', 'T3a pharma', 'Oint', 'مرهم', '', 'Anti-inflammatory.glucocorticoid.bronchodilator', '0.05%', 'Fluticasone propionate is indicated as an inhaler for the treatment and management of asthma by prophylaxis[FDA Label]as well as inflammatory and pruritic dermatoses[F4355]. Fluticasone propionate nasal spray is indicated for managing allergic and nonallergic rhinitis[L8309,F4358].', '', '', 1140, '2022-07-01', CURRENT_TIMESTAMP),
(14436, 'Arthritis free spray topical spray.', 'ارثريتيس فري بخاخ موضعي', '', '18', 'Menthol+methyl salicylate', 'Egyptian co. for adv. pharma. (ecap) > millenium pharma-egypt', 'Spray', 'بخاخ', '', 'Analgesic', '', '', '', '', 723, '2022-07-24', CURRENT_TIMESTAMP),
(15779, 'Cangout 200mg 10 caps.', 'كانجوت 200 مجم 10 كبسولات', '', '12', 'Sulfinpyrazone', 'Multi-apex', 'Cap', 'كبسولة', 'علاج التهاب المفاصل النقرسي المزمن.الحد من مستوى حمض اليوريك بالدم.منع تكون بلورات حمض اليوريك.دعم صحة الكلى.', 'Antigout.analgesic', '200mg', 'For the treatment of gout and gouty arthritis.', '', '', 986, '2022-07-20', CURRENT_TIMESTAMP),
(24000, 'Olapex 10 mg 30 f.c. tabs.', 'اولابكس 10مجم 30 قرص', '', '234', 'Olanzapine', 'Multi-apex', 'Tab', 'أقراص', 'امراض نفسية', 'Psychiatric.antipsychotics', '10 mg', 'Olanzapine was initially used orally and intramuscularly for the chronic treatment of schizophrenia in patients over 13 years old and other psychiatric disorders such as bipolar I disorder including mixed or manic episodes.[A177014] 
Olanzapine is also indicated, in combination with lithium or valproate for the short-term treatment of acute manic or mixed episodes associated with bipolar I disorder in adults.[FDA label]
As well, olanzapine is indicated, in combination with fluoxetine for the treatment of episodes of depression associated with bipolar disorder type 1 and treatment-resistant depression in patients over 10 years old.[A177014]
Olanzapine is also approved for the management of psychomotor agitation associated with schizophrenia and bipolar I mania.[FDA label]
Schizophrenia is a complex biochemical brain disorder that affects the person''s ability to differentiate reality. It is usually observed as the presence of delusions, hallucinations, social withdrawal and disturbed thinking.[L5936]
Bipolar disorder is a mental health condition defined by periods of extreme mood disturbances. It is categorized in different types from which type 1 is known to involve episodes of severe mania and often depression while type 2 presents less severe forms of mania.[L5939]
Olanzapine is also indicated in combination with [samidorphan] for the treatment of bipolar I disorder, either as an adjunct to lithium or valproate or as monotherapy for the acute treatment of manic or mixed episodes or as maintenance therapy, and for the treatment of schizophrenia in adults.[L34359]', '6223003201050', '', 7095, '2023-01-23', CURRENT_TIMESTAMP),
(31854, 'Truehair care treatment shampoo', 'تروهير كير تريتمينت شامبو', '', '140', 'Anagain+argan oil+emu oil+fruitbio+caviar extract+ginger oil+lauryl glycoside', 'Egyptian company of cosmetics > integra pharm', 'Amp', 'أمبول', '', 'Treatment shampoo for all hair types', '', 'shampoo for promoting hair growth & energizing therapy', '', '', 485, '2023-03-07', CURRENT_TIMESTAMP),
(26939, 'Sigmagrel 75mg 20 f.c. tab', 'سيجماجريل 75مجم 20 قرص', '', '60', 'Clopidogrel', 'Sigma', 'Tab', 'أقراص', 'مضاد للتجلط -- الحفاظ علي صحة القلب -- علاج الجلطات التي تتكون في الجسم -- الحفاظ علي سيولة الدورة الدموية', 'Antiplatelet.adp receptor blocker', '75mg', 'Clopidogrel is indicated to reduce the risk of myocardial infarction for patients with non-ST elevated acute coronary syndrome (ACS), patients with ST-elevated myocardial infarction, and in recent MI, stroke, or established peripheral arterial disease,[L7213]', '6221051012079', '', 857, '2022-12-08', CURRENT_TIMESTAMP),
(8921, 'Aaa', 'ششش', '', '34', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 490, '2022-12-07', CURRENT_TIMESTAMP),
(1461, 'Betaval-s oint. 15 gm', 'بيتافال سي مرهم 15 جرام', '', '9', 'Betamethasone+salicylic acid', 'Arab drug company.', 'Oint', 'مرهم', '', 'Glucocorticoid', '15 gm', 'uses: this medication is used to treat certain skin conditions. this product contains a corticosteroid called betamethasone (for swelling redness and itch) and a drug to help remove rough patches of skin. how to use: apply a thin layer to the affected are', '6221060004812', '', 1290, '2022-12-03', CURRENT_TIMESTAMP),
(7966, 'Mepaclind 300mg 8caps.', 'ميباكليند 300 مجم 8 كبسولات', '18', '38', 'Clindamycin', 'Mepaco', 'Cap', 'كبسولة', '', 'Antibiotic.lincomycins', '300mg', 'In oral and parenteral formulations, clindamycin is indicated for the treatment of serious infections caused by susceptible anaerobic bacteria, as well as susceptible staphylococci, streptococci, and pneumococci.[L11599,L11602] Used topically, it is indicated for the treatment of acne vulgaris[L11593,L11611,L11605] and is available in combination with [benzoyl peroxide][L11584] or [tretinoin][L11590] for this purpose, or as a triple combination therapy with benzoyl peroxide and [adapalene].[L48666] Clindamycin is also indicated as a vaginal cream[L11596], suppository[L11608], or gel[L39416] for the treatment of bacterial vaginosis in non-pregnant females.
