Gelatin-based hydrogels are being used in drug delivery and tissue engineering because they are able to promote cell adhesion and proliferation. In addition, these hydrogels can be used as wound dressings because of their attractive fluid absorbance properties. Manufacturing technologies such as ultraviolet stereolithography and two-photon polymerization can be used to prepare structures containing photosensitive gelatin-based hydrogels [L2111].', '', '', 2240, '2023-09-11', CURRENT_TIMESTAMP),
(11491, 'Tolexine 50mg 14 cap', 'تولكسين 50مجم 14 كبسولة', '', '13', 'Doxycycline', 'Al hikma pharmaceuticals', 'Cap', 'كبسولة', '', 'Antibiotic', '50mg', 'Doxycycline is indicated for the treatment of various infections by gram-positive and gram-negative bacteria, aerobes and anaerobes, as well other types of bacteria, including:
- Early Lyme disease (as evidenced by erythema migraines) due to _Borrelia burgdorferi_ in adults and pediatric patients 8 years of age and older weighing 45 kg and above [L42875]
- Rickettsial infections,[L42870] such as Rocky Mountain spotted fever, typhus fever and the typhus group, Q fever, rickettsialpox, and tick fevers [L42880]
- Sexually transmitted infections [L42870]
- Respiratory tract infections [L42870] caused by _Mycoplasma pneumoniae_ and _Haemophilus influenzae_ [L42880]
- Specific bacterial infections [L42870] after indicative bacteriologic testing. These include infections caused by _Escherichia coli_, _Enterobacter aerogenes_, _Shigella_ species, _Acinetobacter_ species, and _Klebsiella_ species [L42880]
- Ophthalmic infections,[L42870] such as inclusion conjunctivitis caused by _Chlamydia trachomatis_ [L42880]
- Anthrax, including inhalational anthrax (post-exposure) [L42870]
- Alternative treatment for selected infections when [penicillin] is contraindicated [L42870]
- Adjunctive therapy in acute intestinal amebiasis and severe acne [L42870, L42880]
- Lymphogranuloma venereum caused by _Chlamydia trachomatis_ [L42880]
- Psittacosis (ornithosis) caused by _Chlamydophila psittaci_ [L42880]
- Trachoma caused by _Chlamydia trachomatis_, although the infectious agent is not always eliminated, as judged by immunofluorescence [L42880]
- Uncomplicated urethral, endocervical, or rectal infections in adults caused by _Chlamydia trachomatis_ [L42880]
- Nongonococcal urethritis caused by _Ureaplasma urealyticum_ [L42880]
- Relapsing fever due to _Borrelia recurrentis_ [L42880]
- Prophylaxis of malaria due to _Plasmodium falciparum_ in short-term travelers (<4 months) to areas with chloroquine and/or pyrimethamine-sulfadoxine resistant strains [L42870, L42880]
It is also used to treat infections caused by the following gram-negative microorganisms:
- Chancroid caused by _Haemophilus ducreyi_ [L42880]
- Plague due to _Yersinia pestis_ [L42880]
- Tularemia due to _Francisella tularensis_ [L42880]
- Cholera caused by _Vibrio cholerae_ [L42880]
- Campylobacter fetus infections caused by _Campylobacter fetus_ [L42880]
- Brucellosis due to _Brucella_ species (in conjunction with [streptomycin]) [L42880]
- Bartonellosis due to _Bartonella bacilliformis_ [L42880]
- Granuloma inguinale caused by _Klebsiella granulomatis_ [L42880]', '', '', 757, '2023-01-05', CURRENT_TIMESTAMP),
(17916, 'Dry tropan 10mg mr 10 caps.', 'دراي تروبان 10 مجم ام ار 10 كبسولات', '', '13', 'Oxybutynin', 'Borg', 'Cap', 'كبسولة', '', 'Urinary incontinence.antispasmodics.muscarinic antagonists', '10mg', 'Oxybutynin is indicated for the symptomatic treatment of overactive bladder, which causes urge urinary incontinence and frequency, and urgency.  Oxybutynin may also be used for children aged 6 and above for the symptomatic management of detrusor muscle overactivity which has been found to be related to a neurological condition. Spina bifida is an example of a neurological condition in which oxybutynin may be used to control urinary symptoms.[L8648] On occasion, oxybutynin may be used off-label to relieve bladder spasms associated with ureteral stents or urinary catheters.[T689]', '6223002570515', '', 940, '2022-12-04', CURRENT_TIMESTAMP),
(27649, 'Sumigran 6mg/0.5 ml prefilled syringe', 'سوميجران 6مجم/0.5مل سرنجات معبأة', '', '30', 'Sumatriptan', 'Sigma tec', 'Syringe', 'حقنة', 'لعلاج حالات الصداع النصفي', 'Antimigraine.vasoconstrictor agents.selective serotonin agonist', '6mg', 'A combination sumatriptan and [naproxen] tablet is indicated for the treatment of migraines with or without auras in patients 12 years of age and older.[L6793] Sumatriptan nasal powder, nasal spray, subcutaneous injection, and tablets are indicated to treat migraines with or without auras in adults.[L6796,L6799,L6805,L6808,L6811] One of the subcutaneous formulations of sumatriptan is also indicated to treat cluster headaches in adults[L6805], while the other subcutaneous formulation is not.[L6808]', '', '', 1060, '', CURRENT_TIMESTAMP),
(17061, 'Daivobet topical oint. 30 gm', 'دايفوبيت مرهم موضعي 30 جم', '222', '388', 'Betamethasone+calcipotriol(calcipotriene)', 'Leo pharmaceutical products', 'Oint', 'مرهم', '', 'Psoriasis', '30 gm', 'uses: this medication is used to treat psoriasis. it helps to reduce the redness thickening and scaling of the skin that occurs with this condition. healthy skin lowers your risk for infection and protects you against the environment. this product contain', '', '', 1793, '2024-02-08', CURRENT_TIMESTAMP),
(803, 'Antiseptol 1mg/ml mouth wash 120 ml', 'انتي سبتول 1مجم/مل مضمضة وغرغرة 120 مل', '', '9', 'Chlorhexidine', 'Kahira', 'Mouth wash', 'غسول للفم', '', 'Antiseptic solution.oral mouth wash', '1mg', 'Chlorhexidine is available over-the-counter in various formulations (e.g. solution, sponge, cloth, swab) as a topical antiseptic to sanitize prior to surgeries and/or medical procedures.[L11518,L11521,L11527,L11533] Dental formulations, available by prescription only, include an oral rinse indicated for the treatment of gingivitis[L11512] and a slow-release "chip" which is inserted into periodontal pockets and is indicated for the reduction of pocket depth in adult patients with periodontitis as an adjunct therapy to dental scaling and root planing procedures.[L11536]', '', '', 2154, '2022-09-06', CURRENT_TIMESTAMP),
(4870, 'Finofib 300mg 10 capsules', 'فينوفيب 300مجم 10كبسولات', '15', '22', 'Fenofibrate', 'Egyphar', 'Capsule', 'كبسولة', 'خافض للدهون في الدم', 'Antihyperlipidemic', '300mg', 'Fenofibrate is indicated as adjunctive therapy to diet:[L51464]
- To reduce triglyceride (TG) levels in adults with severe hypertriglyceridemia (TG greater than or equal to 500 mg/dL)
- To reduce elevated low-density lipoprotein cholesterol (LDL-C) in adults with primary hyperlipidemia when the use of recommended LDL-C lowering therapy is not possible', '6224001026607', '', 2692, '2025-04-13', CURRENT_TIMESTAMP),
(33770, 'Tiptop gel 50 gm', 'تيبتوب جل 50 جم', '75', '90', '', 'Cira pharma', 'Gel', 'جل', '', 'Lubricant', '50 gm', '', '', '', 606, '2024-05-10', CURRENT_TIMESTAMP),
(19916, 'Glucose 25% (el nasr) i.v. inf. 500 ml', 'جلوكوز 25% (النصر) محلول وريدي زجاجة 500 مل', '', '11', 'Glucose (dextrose)', 'El nasr', 'Unknown', 'غير محدد', '', 'Sterile solution', '25%', 'about glucose monosaccharide aldohexose nutritive sweetner. mechanism of action of glucose glucose is a simple carbohydrate and is used as energy source in man. it is readily converted to fat which provides a rich store of energy in concentrated form. glu', '', '', 761, '2022-10-07', CURRENT_TIMESTAMP),
(16434, 'Claforan 1 gm i.m/i.v. vial', 'كلافوران 1جم فيال', '30', '47', 'Cefotaxime', 'Sanofi', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '1 gm', 'Used to treat gonorrhoea, meningitis, and severe infections including infections of the kidney (pyelonephritis) and urinary system. Also used before an operation to prevent infection after surgery.', '6223003990404', '', 1869, '2022-12-03', CURRENT_TIMESTAMP),
(13153, 'Razantamin 16 mg 10 ext. rel. caps.', 'رازانتامين 16مجم 10 كبسول', '', '136', 'Galantamine', 'Aug pharma', 'Cap', 'كبسولة', '', 'Alzheimer s disease', '16 mg', 'Galantamine is indicated for the treatment of mild to moderate dementia of the Alzheimer’s type.[L13571]', '', '', 769, '2022-07-27', CURRENT_TIMESTAMP),
(9839, 'Aaa', 'ششش', '', '3', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 705, '2023-04-28', CURRENT_TIMESTAMP),
(23572, 'Nicotipan 500 mg 20 extended release f.c. tabs.', 'نيكوتيبان 500مجم 20 اقراص', '', '42', 'Nicotinic acid', 'Eva pharma', 'Tab', 'أقراص', '', 'Nicotinic acid', '500 mg', 'mechanism of action of nicotinic acid niacin refers to nicotinic acid as well as nicotinamide which exerts it`s action by influencing metabolic reactions. it is converted in to coenzymes ncotinamide adenine dinucleotide (nad) and its phosphate ncotinamide', '', '', 1067, '2022-07-14', CURRENT_TIMESTAMP),
(6092, 'Val shita massage cream', 'فال شيتا مساج كريم', '', '55', 'Camphor+thyme+paraffin oil', 'Value pharm', 'Cream', 'كريم', 'فيتامينات متعددة وزيت جنين القمح', 'Massage cream', '', '', '', '', 699, '2022-09-21', CURRENT_TIMESTAMP),
(14552, 'Atomorelax 20mg/5ml syrup 100 ml', 'اتوموريلاكس شراب 20مجم/5مل 100مل', '110', '128', 'Atomoxetine', 'Napco > clavita pharma', 'Syrup', 'شراب', 'ضعف الانتباه وفرط الحركة', 'Attention-deficit hyperactivity disorder', '20mg', 'Atomoxetine is indicated for the treatment of attention deficit hyperactivity disorder (ADHD) in children and adults.', '6225000160439', '', 11308, '2025-01-26', CURRENT_TIMESTAMP),
(24286, 'Orniheparate 5gm/10ml 5 amp. i.v inf.', 'اورنيهيباريت 5جم/10مل 5 امبول حقن وريدي', '75', '185', 'L-ornithine-l-aspartate', 'Eimc > rotabiogen for pharmaceutical invest.', 'Amp', 'أمبول', '', 'Liver support supplements', '5gm', '', '', '', 1017, '2025-08-23', CURRENT_TIMESTAMP),
(25239, 'Primalan 30mg/60ml 60ml syrup', 'بريمالان 30 مجم / 60 مل شراب', '', '6', 'Mequitazine', 'European egyptian pharm. ind. > sanofi aventis', 'Syrup', 'شراب', 'علاج الحساسية', 'Antihistamine.antiallergy', '30mg', 'For the treatment of Hay fever, urticaria (hives) and allergic rhinitis', '6221075050071', '', 1029, '2022-12-08', CURRENT_TIMESTAMP),
(28479, 'Tribatens 40/5/25mg 30 f.c. tabs.', 'تريباتنس 40/5/25مجم 30 قرص', '91.5', '126', 'Amlodipine+olmesartan+hydrochlorothiazide', 'Rameda', 'Tab', 'أقراص', 'علاج ارتفاع ضغط الدم', 'Antihypertensive.combined angiotensin blocker & ca++ channel blocker & diuretic', '25mg', 'pharmacology olmesartan: blocks the vasoconstrictor and aldosterone-secreting effects of angiotensin ii. amlodipine: directly acts on vascular smooth muscle to produce peripheral arterial vasodilation reducing peripheral vascular resistance and blood pres', '6223003973285', '', 1418, '2024-11-05', CURRENT_TIMESTAMP),
(19791, 'Ginseng 100 mg 24 s.g. caps.', 'جنسنج 100مجم 24 كبسولة', '', '8', 'Ginseng', 'Pharco', 'Cap', 'كبسولة', 'مقوي عام', 'General tonic', '100 mg', 'about ginseng steroid glycosides. mechanism of action of ginseng it contains chemicals called ginsenosides that seem to affect insulin levels in the body and lower blood sugar. other chemicals called polysaccharides might affect the immune system. indicat', '6223000011126', '', 1864, '2022-12-05', CURRENT_TIMESTAMP),
(16362, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 785, '2022-08-31', CURRENT_TIMESTAMP),
(13968, 'Amlosterolen 10/40mg 14 f.c. tabs.', 'املوستيرولين 10/40 مجم 14 قرص', '', '39', 'Amlodipine+atorvastatin', 'Medizen pharmaceutical industries > utopia pharmaceuticals company', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statin combined with ca channel blocker', '40mg', 'indications for atorvastatin + amlodipine this is a combination of calcium channel blocker amlodipine and hmg-coa reductase inhibitor atorvastatin. the combination generic is used to treat 1.hypertension 2.angina (that occurs with high cholesterol or trig', '', '', 953, '2022-07-21', CURRENT_TIMESTAMP),
(19145, 'Aaa', 'ششش', '', '72', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 845, '2022-12-05', CURRENT_TIMESTAMP),
(25646, 'Ramedamycin plus eye drops 10 ml', 'راميدامايسين بلس قطرة للعين 10 مل', '35.5', '51', 'Dexamethasone+tobramycin', 'Rameda', 'Drops', 'نقط', '', 'Antibiotic with glucocorticoid', '10 ml', 'about dexamethasone a potent synthetic glucocorticoid antiasthmatic anti-inflammatory and immunosuppressant. mechanism of action of dexamethasone the drug exerts it`s pharmacological action by penetrating and binding to cytoplasmic receptor protein and ca', '', '', 1006, '2025-05-28', CURRENT_TIMESTAMP),
