patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6221094018939', '', 1929, '2024-07-15', CURRENT_TIMESTAMP),
(28846, 'Uricol-n 6 eff. gr. in sachets', 'يوريكول ان فوار 6 اكياس', '', '21', 'Hexamine+khellin', 'Pharco', 'Sachet', 'أكياس', 'علاج حالات املاح حمض اليوريك', 'Antigout.analgesic', '', 'mechanism of action of colchicine it inhibits microtubule polymerization by binding to tubulin one of the main constituents of microtubules. this tubulin is essential to mitosis and therefore it inhibits the development of spindles as the nuclei are divid', '6221151485926', '', 1301, '2022-10-08', CURRENT_TIMESTAMP),
(2009, 'Capoten 25mg 20 tab', 'كابوتين 25مجم 20 قرص', '18', '32', 'Captopril', 'Smithkline beecham', 'Tab', 'أقراص', 'علاج ضغط الدم المرتفع', 'Anti-hypertensive.ace', '25mg', 'For the treatment of essential or renovascular hypertension (usually administered with other drugs, particularly thiazide diuretics). May be used to treat congestive heart failure in combination with other drugs (e.g. cardiac glycosides, diuretics, &beta;-adrenergic blockers). May improve survival in patients with left ventricular dysfunction following myocardial infarction. May be used to treat nephropathy, including diabetic nephropathy.', '6224001007101', '', 6268, '2024-10-23', CURRENT_TIMESTAMP),
(17369, 'Aaa', 'ششش', '', '27', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 684, '2022-09-23', CURRENT_TIMESTAMP),
(12812, 'Zerol cream 40 gm', 'زيرول كريم 40 جم', '185', '300', 'Silicon fluid+dimethicone+hydrophilic onion extract+emu oil+cocoa butter+bees wax+almond oil+liquid', 'Macro group pharmaceuticals', 'Cream', 'كريم', 'لتسريع التئام الجروح', 'Healing topical', '40 gm', '*specialized cream for management of keloids & hypertrophic scars with extra moisturizing properties *helps in softening smoothing and flattening new and old hypertrophic scars and keloids resulting after laser resurfacing& surgeries. *helps in relieving', '6224000437350', '', 2447, '2024-11-20', CURRENT_TIMESTAMP),
(30077, 'Acik cream 50 gm', 'اسيك كريم 50 جرام', '69.5', '85', 'Salicylic acid+lavender oil+witch hazel extract+retinol+lactic acid+propolis extract+tea tree oil+thyme oil+panthenol+vitamin e+sulfur', 'Dreams el habboba > novogen', 'Cream', 'كريم', 'كريم مضاد لحب الشباب للبشرة المختلطة والدهنية', 'Skin care.acne', '50 gm', 'Key additive in many skin-care products for the treatment of acne, psoriasis, callouses, corns, keratosis pilaris and warts.', '6774433700007', '', 2343, '2024-07-04', CURRENT_TIMESTAMP),
(5707, 'Centravita zymatrol 20 f.c. tabs.', 'سنترافيتا زيماترول 20 قرص', '', '140', 'Trypsin+bromelain+rutin+l- leucine', 'Copad', 'Tab', 'أقراص', '', 'Anti inflammatory & digestive', '', '', '', '', 935, '2025-07-03', CURRENT_TIMESTAMP),
(19201, 'Flucand 2mg/ml vial for inf.', 'فلوكاند 2مجم/مل فيال للتسريب الوريدي', '', '60', 'Fluconazole', 'Hikma pharma', 'Vial', 'فيال', '', 'Antifungals.triazoles', '2mg', 'Fluconazole can be administered in the treatment of the following fungal infections[L11043]:
 1) Vaginal yeast infections caused by Candida
 2) Systemic Candida infections
 3) Both esophageal and oropharyngeal candidiasis 
 4) Cryptococcal meningitis
 5) UTI (urinary tract infection) by Candida
 6) Peritonitis (inflammation of the peritoneum) caused by Candida
**A note on fungal infection prophylaxis**
Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '', '', 922, '2022-06-24', CURRENT_TIMESTAMP),
(21318, 'Kemprost 0.4mg 20 caps.', 'كيمبروست 0.4 مجم 20 كبسولة', '', '56', 'Tamsulosin', 'Chemipharm', 'Cap', 'كبسولة', '', 'Urination-difficulty.alpha blocker', '0.4mg', 'Tamsulosin is indicated for the treatment of signs and symptoms of benign prostatic hyperplasia.[Label]
Tamsulosin is also used off label for the treatment of ureteral stones, prostatitis, and female voiding dysfunction.[A178339,L6259]', '6222006500764', '', 1381, '2022-12-06', CURRENT_TIMESTAMP),
(6900, 'Ketoprek 2.5% topical gel 50 gm', 'كيتوبريك 2.5% جل موضعي 50 جم', '12', '34', 'Ketoprofen', 'Borg', 'Gel', 'جل', 'مسكن عام -- تقليل الالام -- خافض للحرارة -- تقليل الالتهابات', 'Nsaid.propionic acid derivatives', '2.5%', 'For symptomatic treatment of acute and chronic rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, primary dysmenorrhea and mild to moderate pain associated with musculotendinous trauma (sprains and strains), postoperative (including dental surgery) or postpartum pain.', '6223002571093', '', 1890, '2025-06-18', CURRENT_TIMESTAMP),
(28113, 'Thera-lo 3.2g/100ml oral susp. 100 ml', 'ثيرا – لو 3.2 جرام / 100 مل معلق 100 مل', '', '5', 'Paracetamol(acetaminophen)', 'Pharopharma', 'Susp', 'معلق', '', 'Antipyretic', '100ml', 'about paracetamol acetanilide derivative non narcotic analgesic antipyretic. mechanism of action of paracetamol paracetamol has analgesic and antipyretic action. it is more active on cyclo-oxygenase enzyme in brain. peripherally it is a poor inhibitor of', '', '', 1010, '2022-08-21', CURRENT_TIMESTAMP),
(6554, 'Ioprost 50mcg/ml eye drops 3 ml', 'ايوبروست 50 مكجم/مل قطرة عين 3 مل', '60', '81', 'Latanoprost', 'Alexandria > orchidia pharmaceutical industries', 'Drops', 'نقط', '', 'Antiglaucoma', '50mcg', 'Latanoprost is indicated for the reduction of elevated intraocular pressure in patients who have been diagnosed with open-angle glaucoma or ocular hypertension.[L8357,L8402,L44401] It is available as monotherapy or in a combination product with [netarsudil] [L8369] or [timolol].[L15217]
In Canada, latanoprost is also indicated to treat elevated intraocular pressure due to angle-closure glaucoma that has been treated with peripheral iridotomy or laser iridoplasty.[L8402]', '6224000219260', '', 3605, '2023-09-29', CURRENT_TIMESTAMP),
(28573, 'Trook line hair serum 120 ml', 'تروك لاين سيروم للشعر 120 مل', '', '160', 'Keratin+protein+collagen+caviar', 'Egyptian company for cosmetics > resipi pharma', 'Serum', 'سيروم', '', 'Hair care', '120 ml', 'extra shine extra care - treats moisturizes & styles hair for all hair types', '', '', 568, '2022-08-05', CURRENT_TIMESTAMP),
(23334, 'Puramax 10 gm 10 sachets', 'بيوراماكس 10 جم 10 اكياس', '100', '120', 'Lactoferrin+iron+vitamin b complex+vitamin c', 'Mb pharma', 'Sachet', 'أكياس', '', 'Multivitamin', '10 gm', '', '6224010115019', '', 1260, '2025-07-22', CURRENT_TIMESTAMP),
(19734, 'Wook-first gel 60 gm', 'ووك فيرست جل 60 جم', '', '65', '', 'Actada', 'Gel', 'جل', '', '', '60 gm', '', '', '', 813, '2022-09-01', CURRENT_TIMESTAMP),
(7443, 'Livagoal 450mg 20 caps.', 'ليفاجول 450مجم 20 كبسولة', '117', '238', 'Ursodeoxycholic acid', 'Marcyrl co.', 'Cap', 'كبسولة', 'يستخدم لعلاج الحصوات المرارية--التهاب الكبد المزمن.', 'Hepatitis', '450mg', 'Ursodeoxycholic acid is indicated for the treatment of patients with primary biliary cholangitis.[L44627] 
It is used for the short-term treatment of radiolucent, noncalcified gallbladder stones in patients selected for elective cholecystectomy. It is also used to prevent gallstone formation in obese patients experiencing rapid weight loss.[L44793]', '6223003570613', '', 10046, '2024-11-13', CURRENT_TIMESTAMP),
(27622, 'Aaa', 'ششش', '', '55', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 643, '2022-07-30', CURRENT_TIMESTAMP),
(15704, 'Calm skin cream 40 gm', 'كالم سكين كريم 40 جرام', '45', '65', 'Chamomile+dimethicone+zinc oxide', 'Global napi pharmaceuticals', 'Cream', 'كريم', 'كريم موضعي مرطب، يستخدم لعلاج طفح الحفاظ، والحد من الحكة وتشققات الجلد، و تستخدم للوقاية من ولعلاج جفاف وحكة الجلد،', 'Soothing topical', '40 gm', 'indications 1.emollient & protective agent for every day life for all members of the family. 2.protection of the skin from the deleterious effects of ultraviolet & sun rays. 3.prevention & treatment of diaper rash napkin dermatitis & sweat rash. 4.adjuvan', '6223002143467', '', 2514, '2024-05-24', CURRENT_TIMESTAMP),
(28365, 'Tortin cream 50 gm', 'تورتين كريم 50جم', '', '32', '', 'Leader cosmetics > imaginex egypt co.', 'Cream', 'كريم', 'كريم ترطيب وتغذية البشرة', 'Moisturizing topicals', '50 gm', 'skin emollient cream', '', '', 717, '2022-07-12', CURRENT_TIMESTAMP),
(14822, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 643, '2022-09-06', CURRENT_TIMESTAMP),
(20977, 'Irton syrup 100 ml', 'ايرتون شراب 100 مل', '', '25', 'Ferrous sulphate+folic acid+wheat germ oil+vitamin (b1+b6+b12+e)', 'El-obour > dr. khairy company for export', 'Syrup', 'شراب', '', 'Iron supplement', '100 ml', 'Ferrous sulfate is used for the prevention and treatment of iron deficiency anemia in adults and children.[A190804,L2240,L11800]', '', '', 656, '2022-07-16', CURRENT_TIMESTAMP),
(9736, 'Pentasa 500mg 100 slow release tab', 'بنتازا 500مجم 100 قرص ممتد المفعول', '920', '1,100', 'Mesalazine(mesalamine)(5-asa)(5-aminosalicylic acid)', 'Ferring pharmaceuticals > multipharma', 'Tab', 'أقراص', 'التهاب القولون التقرحي -- علاج مرض الكرون -- علاج التهاب القولون شديد التقرح -- تقليل الالتهابات والالام', 'Ulcerative colitis', '500mg', '', '7640128547495', '', 26822, '2025-08-03', CURRENT_TIMESTAMP),
(9553, 'Myocool massage spray 200 ml', 'ميوكول مساج اسبراي 200 مل', '230', '270', 'Menthol+eucalyptus+peppermint+boswellia+ginger ext.+camphor+red grape ext.+vitamin k', 'Purex health care', 'Spray', 'بخاخ', '', 'Massage', '200 ml', '', '6224001085000', '', 1038, '2025-08-03', CURRENT_TIMESTAMP),
(16935, 'Cura zona emulsion 200 ml', 'كيورازونا مستحلب 200 مل', '', '275', '', 'Egoteck srl > cosmocare', 'Unknown', 'غير محدد', 'للعناية بالشعر -- لنظافة وتقوية الشعر', 'Hair care', '200 ml', '', '', '', 1057, '2023-02-11', CURRENT_TIMESTAMP),
(5825, 'Fumarox 240 mg 60 cap', 'فيوماروكس 240مجم 60 كبسولة', '', '10,800', 'Dimethyl furmarate', 'Elixir pharma', 'Cap', 'كبسولة', '', 'Dimethyl furmarate', '240 mg', 'For the symptomatic relief of patients with interstitial cystitis.', '', '', 1011, '2025-07-10', CURRENT_TIMESTAMP),
(21067, 'Itrafungizole 100mg 12 caps.', 'ايترافونجيزول 100مجم 12 كبسولة', '', '42', 'Itraconazole', 'Al rowad pharmaceutical industrial co.', 'Cap', 'كبسولة', '', 'Antifungals.triazoles', '100mg', 'Itraconazole is indicated for the treatment of the following fungal infections in immunocompromised and non-immunocompromised patients:[L50051, L50056]
- Blastomycosis, pulmonary and extrapulmonary
- Histoplasmosis, including chronic cavitary pulmonary disease and disseminated, nonmeningeal histoplasmosis, and
- Aspergillosis, pulmonary and extrapulmonary, in patients who are intolerant of or who are refractory to amphotericin B therapy
It is also indicated for the treatment of the following fungal infections in non-immunocompromised patients:[L50051]
- Onychomycosis of the toenail, with or without fingernail involvement, due to dermatophytes (tinea unguium)
- Onychomycosis of the fingernail due to dermatophytes (tinea unguium).
