(20722, 'Iliadin 0.05 % adult nasal spray', 'اليادين 0.05% بخاخ للأنف للكبار', '', '4', 'Oxymetazoline', 'Amoun > merck kgaa f.r.germany', 'Spray', 'بخاخ', '', 'Nasal congestion.adrenergic alpha-agonist', '0.05 %', 'Oxymetazoline is indicated for the topical treatment of persistent facial erythema associated with rosacea in adults.[L15062]
Ophthalmic oxymetazoline is indicated for the treatment of acquired blepharoptosis in adults.[L15067]
When used in combination with tetracaine intranasally, oxymetazoline is indicated for regional anesthesia when performing a restorative procedure on Teeth 4-13 and A-J in adults and children who weigh 40 kg or more.[L15057]
Oxymetazoline can be found in over-the-counter nasal products as a nasal decongestant.[L15092]
For off-label uses, oxymetazoline has been used during nasal intubation and during ear, nose, and throat surgery to improve visualization of the airway and to minimize post-operative bleeding.[A215542]', '', '', 963, '2022-07-17', CURRENT_TIMESTAMP),
(27486, 'Staturic 80 mg 30 f.c. tabs.', 'ستاتيوريك 80مجم 30 قرص', '90', '123', 'Febuxostat', 'Mash premiere', 'Tab', 'أقراص', 'علاج النقرس -- الوقاية من حصوات الكلي -- علاج ارتفاع مستوي حمض اليوريك في الدم', 'Antigout', '80 mg', 'Febuxostat is indicated for the chronic management of hyperuricemia in adult patients with gout who have an inadequate response to a maximally titrated dose of [allopurinol], who are intolerant to allopurinol, or for whom treatment with allopurinol is not advisable.[L46073] It is not recommended for the treatment of asymptomatic hyperuricemia [L32238] or secondary hyperuricemia.[A230583]', '6222001401561', '', 8072, '2024-09-26', CURRENT_TIMESTAMP),
(29876, 'Zengaprost 0.004% eye drops 5 ml', 'زينجابروست 0.004% قطرة للعين 5مل', '96', '134', 'Travoprost', 'Marcyrl co. > ecco pharm-egypt', 'Drops', 'نقط', '', 'Antiglaucoma', '0.004%', 'Travoprost is indicated for the reduction of elevated intraocular pressure in patients with open-angle glaucoma or ocular hypertension.[L49434, L49429, L49515] It is also used in pediatric patients aged two months to less than 18 years.[L5146]', '', '', 694, '2025-04-20', CURRENT_TIMESTAMP),
(13880, 'Vitapoint anti dandruff 250ml shampoo', 'فيتابوينت مضاد للقشرة شامبو 250 مل', '', '125', 'Piroctone olamine+climbazole+salicylic acid+rosemary oil+tea tree oil+aloe vera extract.', 'Melano pharma', 'Amp', 'أمبول', '', 'Anti dandruff', '250ml', '', '6222001301007', '', 1399, '2022-09-05', CURRENT_TIMESTAMP),
(17679, 'Regi v 400mg 30 capsules', 'ريجي في 400مجم 30 كبسولة', '', '195', 'Green coffee bean extract ( 50% chlorogenic acid + poly phenols)', 'Juven for herbs and medical plants', 'Capsule', 'كبسولة', 'علاج الذبحة الصدرية — الوقاية من الذبحة الصدرية — لعلاج آلام شديدة فى الصدر — فشل القلب الاحتقانى', 'Antiobesity + antioxidant', '400mg', '', '', '', 1867, '2022-08-31', CURRENT_TIMESTAMP),
(20053, 'Granya emollient cream 60 gm', 'جرانيا كريم مرطب للجلد 60 جرام', '125', '150', '', 'Egyptian company for cosmetics > medinza pharm', 'Cream', 'كريم', 'كريم ترطيب و تنعيم للجلد -- تفتيتح الجلد', 'Moisturizing topicals', '60 gm', '', '6224001972140', '', 4381, '2025-06-24', CURRENT_TIMESTAMP),
(28536, 'Tritace comp 5/25mg 14 tab', 'تريتاس كومب مركب 5/25 مجم 14 قرص', '89', '118', 'Hydrochlorothiazide+ramipril', 'Sanofi', 'Tab', 'أقراص', '', 'Antihypertensive.combined ace with diuretic', '25mg', '', '6223003991432', '', 4527, '2024-11-16', CURRENT_TIMESTAMP),
(2482, 'Spider care 60 gm massage cream', 'سبايدر كير 60 جرام كريم مساج', '', '65', 'Menthol+camphor+eucalyptus oil+clove oil+peppermint oil+magnesium sulphate', 'Revaro pharm', 'Cream', 'كريم', '', 'Massage cream', '60 gm', '', '', '', 838, '2025-01-18', CURRENT_TIMESTAMP),
(25356, 'Pronuben baby ar milk 400 gm', 'برونوبين بيبي اي ار حليب 400جم', '', '150', 'Anti-regurgitation milk formula', 'Pronuben s.l. > rotabiogen for pharmaceutical invest.', 'Unknown', 'غير محدد', '', 'Milk products.anti-regurgitation milk', '400 gm', 'anti regurgitation formula - from birth to 12 months calcium - iron - magnesium - carob seed flour - 13 vitamins - 5 nucleotides - ara & dha', '', '', 782, '2022-08-02', CURRENT_TIMESTAMP),
(14151, 'Anestacon 2mg/ml (25ml) i.v. infusion', 'انيستاكون 2مجم/مل(25مل) وريد', '', '17', 'Fluconazole', 'Grand pharma > vodachem pharmaceuticals', 'Unknown', 'غير محدد', '', 'Antifungals.triazoles', '2mg', 'Fluconazole can be administered in the treatment of the following fungal infections[L11043]:
 1) Vaginal yeast infections caused by Candida
 2) Systemic Candida infections
 3) Both esophageal and oropharyngeal candidiasis 
 4) Cryptococcal meningitis
 5) UTI (urinary tract infection) by Candida
 6) Peritonitis (inflammation of the peritoneum) caused by Candida
**A note on fungal infection prophylaxis**
Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '', '', 837, '2022-07-07', CURRENT_TIMESTAMP),
(12803, 'Aaa', 'ششش', '', '156', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 721, '2022-05-30', CURRENT_TIMESTAMP),
(26511, 'Sanso care cream for stretch mark 100 gm', 'سانسو كير كريم لعلامات تمدد الجلد السترتش ماركس 100 جرام', '90', '100', 'Allantoin+menthol+calendula+evening primrose oil+aloe vera+panthenol+vitamin (a+e)+zinc oxide', 'Aug pharma', 'Cream', 'كريم', '', 'Firming topical', '100 gm', 'use: apply suitable amount of cream into your skin and gently massage the skin using circular movements.', '', '', 1810, '2024-05-18', CURRENT_TIMESTAMP),
(27174, 'Sodium chloride 0.9% & dextrose 5% (el nasr) i.v. inf. 500ml (polypropylene bag)', 'صوديوم كلوريد 0.9% ودكستروز 5% النصر محلول وريدي 500 مل بولي بروبيلين باج', '', '14', 'Sodium chloride', 'El nasr', 'Unknown', 'غير محدد', '', 'Normal saline', '0.9%', 'This intravenous solution is indicated for use in adults and pediatric patients as a source of electrolytes and water for hydration. Also, designed for use as a diluent and delivery system for intermittent intravenous administration of compatible drug additives.', '', '', 756, '2022-07-15', CURRENT_TIMESTAMP),
(9481, 'Soft lax massage cream 40 gm', 'سوفت لاكس مساج كريم 40 جم', '40', '55', 'Camphor oil+menthol crystals', 'Aglan pharma', 'Cream', 'كريم', '', 'Massage cream', '40 gm', '', '6224007331095', '', 1227, '2024-12-01', CURRENT_TIMESTAMP),
(21994, 'Logimax s.r. 30 tab.', 'لوجي ماكس 30 قرص', '60', '105', 'Felodipine+metoprolol', 'Astra zeneca', 'Tab', 'أقراص', 'علاج لمرض ارتفاع ضغط الدم', 'Calcium channel blocker', '', 'therapeutic indication: hypertension. logimax can be used when treatment with beta-blockers or calcium antagonists of the dihydropyridine type in monotherapy has not produced an adequate effect.', '6223003270254', '', 2259, '2023-09-28', CURRENT_TIMESTAMP),
(27866, 'Tagrisso 80 mg 30 f.c. tabs', 'تاجريسو 80مجم 30 قرص', '103524', '124,000', 'Osimertinib', 'Astra zeneca', 'Tab', 'أقراص', 'مضاد للاورام', 'Antineoplastic', '80 mg', 'Osimertinib is indicated for the: 
- adjuvant treatment of non-small cell lung cancer (NSCLC) after tumour resection in adult patients whose tumours have epidermal growth factor receptor (EGFR) exon 19 deletions or exon 21 L858R mutations, as detected by an FDA-approved test.[L50492]
- first-line treatment of adult patients with metastatic NSCLC whose tumours have EGFR exon 19 deletions or exon 21 L858R mutations.[L50492]
- in combination with [pemetrexed] and platinum-based chemotherapy for the first-line treatment of adult patients with locally advanced or metastatic NSCLC whose tumours have EGFR exon 19 deletions or exon 21 L858R mutations, as detected by an FDA-approved test.[L50492]
- treatment of adult patients with metastatic EGFR T790M mutation-positive NSCLC, as detected by an FDA-approved test, whose disease has progressed on or after EGFR tyrosine kinase inhibitor (TKI) therapy.[L50492]', '', '', 8851, '2025-02-06', CURRENT_TIMESTAMP),
(15713, 'Calmetanil 1.5mg 30 f.c. tab.', 'كالمتانيل 1.5 مجم 30 قرص', '', '5', 'Bromazepam', 'Mepaco > spimaco misr', 'Tab', 'أقراص', '', 'Psychiatric.anxiolytics-hypnotics', '1.5mg', 'For the short-term treatment of insomnia, short-term treatment of anxiety or panic attacks, if a benzodiazepine is required, and the alleviation of the symptoms of alcohol- and opiate-withdrawal.', '', '', 795, '2022-07-17', CURRENT_TIMESTAMP),
(19091, 'Aaa', 'ششش', '36', '53', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 741, '2023-09-10', CURRENT_TIMESTAMP),
(27380, 'Spectral.rs anti-aging serum 60 ml', 'سبيكترال سيروم ضد الشيخوخة والتجاعيد 60مل', '', '493', '', 'Ds laboratories > multitrade', 'Serum', 'سيروم', '', 'Skin care', '60 ml', 'spectral.rs is indicated for women and men who prefer a natural formula because it makes hair look thicker and feel stronger without using minoxidil. apply 10 sprays twice per day shake well before use. apply 10 or more sprays in the thinning area twice p', '', '', 692, '2022-08-03', CURRENT_TIMESTAMP),
(20904, 'Intraglobin f 50mg/ml (20ml=1g) i.v. infusion', 'انتراجلوبين اف 50مجم/مل )20مل = 1جم( محلول وريدي', '', '600', 'Immunoglobulin', 'Biotest pharma germany > egycopharm', 'Unknown', 'غير محدد', '', 'Iv.ig', '50mg', '', '', '', 754, '2023-01-24', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(6878, 'Ketofan 75mg 30 caps.', 'كيتوفان 75مجم 30 كبسولة', '36', '57', 'Ketoprofen', 'Amriya', 'Cap', 'كبسولة', '', 'Nsaid.propionic acid derivatives', '75mg', 'For symptomatic treatment of acute and chronic rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, primary dysmenorrhea and mild to moderate pain associated with musculotendinous trauma (sprains and strains), postoperative (including dental surgery) or postpartum pain.', '6221075022399', '', 1779, '2024-12-07', CURRENT_TIMESTAMP),
(29569, 'Umatone brain boost 30 sachets', 'يوماتون برين بوست 30 كيس', '', '550', 'Cystidine diphosphate choline+pyroloquinoline quinone+pyritinol+gamma amino butyric acid+gingko bilopa+memantine hcl', 'Pharma zad > cortexin', 'Sachet', 'أكياس', 'مكمل غذائي لعلاج التوحد وضمور خلايا المخ وتأخر الكلام', 'Dietary supplement', '', '', '9548412387438', '', 12870, '2022-10-08', CURRENT_TIMESTAMP),
(14173, 'Primaderm cream face and body 100 gm', 'بريماديرم كريم للوجه والجسم 100 جم', '', '160', '', 'Molecular cosmetics', 'Cream', 'كريم', '', 'Moisturising cream', '100 gm', '', '', '', 752, '2022-09-06', CURRENT_TIMESTAMP),
(7340, 'Toogera syrup', 'توجيرا شراب', '', '300', 'Omega 3 (epa+dha)+vitamin c+e+b2+b1+b6+b5+a+zinc', 'Innovec pharmaceutical', 'Syrup', 'شراب', '', 'Supports normal brain function', '', '', '', '', 994, '2025-09-08', CURRENT_TIMESTAMP),
(20928, 'Aaa', 'ششش', '', '60', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 708, '2022-08-06', CURRENT_TIMESTAMP),
(13689, 'Alexgenta 0.1% topical cream 15 gm', 'اليكسجينتا 0.1% كريم موضعي 15 جم', '', '5', 'Gentamicin', 'Alexandria', 'Cream', 'كريم', '', 'Aminoglycoside antibiotic', '0.1%', 'about gentamicin aminoglycoside antibiotic. mechanism of action of gentamicin gentamicin exerts its bactericidal action against gram negative organisms & some of gram positive organisms by inhibiting bacterial protein synthesis. the process involves 1. pe', '', '', 1044, '2022-07-13', CURRENT_TIMESTAMP),
(18708, 'Aaa', 'ششش', '', '2,550', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 751, '2022-07-13', CURRENT_TIMESTAMP),
(18083, 'Eduropan 8mg 20 f.c. tabs.', 'اديروبان 8 مجم 20 قرص', '31', '62', 'Lornoxicam', 'Al rowad pharmaceutical industrial co. > hygint pharmaceuticals-egypt', 'Tab', 'أقراص', 'مسكن عام للجسم -- تقليل الالام', 'Nsaid.oxicam', '8mg', 'For the treatment of acute mild to moderate pain, as well as pain and inflammation of the joints caused by certain types of rheumatic diseases.', '6224008622048', '', 1509, '2025-08-03', CURRENT_TIMESTAMP),
(27955, 'Tears naturale eye drops 15 ml', 'تيرز ناتشورال قطرة للعين 15مل', '130', '143', 'Benzalkonium chloride+dextran+hydroxypropyl methylcellulose', 'Novartis > novartis scientific office', 'Drops', 'نقط', '', 'Eye lubricant', '15 ml', 'When used as an active ingredient in products like antibacterial, antiseptic, or disinfectant soaps, topical sanitizers, or cleaning agents, benzalkonium is primarily implemented in its salt form, benzalkonium chloride, where it may often be the only active ingredient present and indicated for the primary purpose of topical washing to decrease bacteria on skin [L1806].
Conversely, when implemented as an excipient ingredient in a variety of multidose aqueous nose, eye, or ear products, benzalkonium chloride is being used as the antimicrobial preservative of choice to facilitate effective bactericidal and fungicidal actions to help minimize the growth of unwanted organisms in the multidose containers [FDA Label].', '300651418347', '', 6251, '2025-08-16', CURRENT_TIMESTAMP),
(14776, 'Avoscaldine 300mg 20 soft gelatin caps', 'افوسكالدين 300 مجم 20 كبسولة', '', '28', 'Avocado oil+soya bean oil', 'Sigma > chemipharm', 'Cap', 'كبسولة', 'مضاد للالتهابات المفصلية -- الحفاظ علي المفاصل و العظام', 'Osteoarthritis', '300mg', '', '', '', 4485, '2023-02-05', CURRENT_TIMESTAMP),
