(29506, 'Vitamin e 1000mg 24 caps.', 'فيتامين اي 1000مجم 24 كبسول', '47', '89', 'Vitamin e', 'Pharco', 'Cap', 'كبسولة', 'تأخير ظهور علامات الشيخوخة على البشرة.', 'Vitamin e', '1000mg', 'Vitamin E supplementation is indicated for treatment of vitamin E deficiency which can occur in cystic fibrosis, cholestasis and severe liver disease, abetalipoproteinemia or simply poor diet[A176104,L3063].', '6223000013342', '', 4501, '2024-11-26', CURRENT_TIMESTAMP),
(16263, 'Cholerose plus 10/10 mg 14 f.c.tablets', 'كوليروز بلس 10/10مجم 14 قرص', '63', '86', 'Ezetimibe+rosuvastatin', 'Marcyrl co.', 'Tablet', 'أقراص', 'خافض للكوليسترول ودهون الدم', 'Antihyperlipidemic.statins', '10 mg', '', '', '', 14461, '2024-02-14', CURRENT_TIMESTAMP),
(33284, 'Nody care serum 100 ml', 'نودي كير سيروم 100 مل', '147', '268', 'Argan oil+keratin oil+almond+shea butter+olive oil+panthenol', 'Everest cosmetics', 'Serum', 'سيروم', '', 'Hair care', '100 ml', '', '', '', 725, '2024-01-28', CURRENT_TIMESTAMP),
(22576, 'Aaa', 'ششش', '21', '35', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 741, '2022-07-16', CURRENT_TIMESTAMP),
(8602, 'Tetra glow lotion whitening foam 200 ml', 'تترا جلو غسول تفتيح فوم 200 مل', '', '200', '', 'Company', 'Lotion', 'لوشن', '', '', '200 ml', '', '6224011673099', '', 1047, '2024-09-12', CURRENT_TIMESTAMP),
(28839, 'Uriage thermal water 50ml', 'يورياج مياه حرارية 50 مل', '', '99', '', 'Uriage dermatological laboratories > biotech egypt', 'Unknown', 'غير محدد', '', 'Skin care', '50ml', 'uriage thermal water is a skincare water for daily use a powerful cure treatment of trace elements and minerals a source of radiance for your skin. a treatment water to moisturise this is the only thermal spa water with moisturising benefits thanks to its', '', '', 593, '2022-08-03', CURRENT_TIMESTAMP),
(16517, 'Clindacine 150mg 6 caps.', 'كلينداسين 150 مجم 6 كبسولات', '', '12', 'Clindamycin', 'Rameda', 'Cap', 'كبسولة', '', 'Antibiotic.lincomycins', '150mg', 'In oral and parenteral formulations, clindamycin is indicated for the treatment of serious infections caused by susceptible anaerobic bacteria, as well as susceptible staphylococci, streptococci, and pneumococci.[L11599,L11602] Used topically, it is indicated for the treatment of acne vulgaris[L11593,L11611,L11605] and is available in combination with [benzoyl peroxide][L11584] or [tretinoin][L11590] for this purpose, or as a triple combination therapy with benzoyl peroxide and [adapalene].[L48666] Clindamycin is also indicated as a vaginal cream[L11596], suppository[L11608], or gel[L39416] for the treatment of bacterial vaginosis in non-pregnant females.
Clindamycin is used for antimicrobial prophylaxis against _Viridans_ group streptococcal infections in susceptible patients undergoing oral, dental, or upper respiratory surgery, and may be used for prophylaxis against bacterial endocarditis in penicillin-allergic patients at high risk of these infections.[L11629]', '', '', 934, '2022-07-14', CURRENT_TIMESTAMP),
(334, 'Aliamare nasal spray 100ml', 'اليامير بخاخ انف 100 مل', '', '235', 'Seawater+hyaluronic acid sodium salt', 'Ibsa farmaceutici >', 'Spray', 'بخاخ', '', 'Nasal decongestant', '100ml', 'isotonic spray solution of seawater and sodium hyaluronate for the daily hygiene of the nose and ears in children and adults. use several times a day according to individual needs.', '8033638950654', '', 1790, '2022-12-01', CURRENT_TIMESTAMP),
(22997, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 616, '2022-10-22', CURRENT_TIMESTAMP),
(19999, 'Gold standard 100% whey protein 4.67 kg', 'جولد ستاندرد 100% واي بروتين 4.67كجم', '', '2,500', 'Whey protein isolate+whey protein concentrate+whey peptide', 'Optimum nutrition > ramco', 'Unknown', 'غير محدد', '', 'Supplement', '100%', 'whey protein isolates (wpi) are the purest form of whey protein that currently exists. *over 4 grams of glutamine & glutamic acid in each serving *more than 5 grams of the naturally occurring branched chain amino acids (bcaas) leucine isoleucine and valin', '', '', 796, '2022-07-22', CURRENT_TIMESTAMP),
(8097, 'Metoclopramide 10mg/2ml 5 amp. for iv/im inj.', 'ميتوكلوبراميد 10مجم/2مل 5 امبولات', '', '8', 'Metoclopramide', 'Sedico', 'Inj', 'حقن', '', 'Dopamine antagonist', '10mg', 'Metoclopramide in the oral tablet form is used for symptomatic treatment of both acute and recurrent diabetic gastroparesis, in addition to the treatment of gastroesophageal reflux disease (GERD) in patients who have failed to respond to traditional therapy.[L8414] A nasal spray formulation is also indicated to treat adults with acute, recurrent diabetic gastroparesis.[L14381]
In the intravenous injection form, it is indicated for the above conditions as well as for the prevention of vomiting that may follow emetogenic chemotherapy or nausea and vomiting after surgery. Intravenous metoclopramide facilitates intubation of the small bowel and stimulates gastric emptying and barium flow in patients who require radiological examination of the stomach or small intestine.  In some cases, the delay of gastrointestinal emptying interferes with the radiographic visualization of the gastrointestinal tract, and metoclopramide is used to facilitate emptying in these cases, allowing for adequate diagnostic visualization.[L8417]
Some off-label uses of metoclopramide include the management of radiation-induced nausea and vomiting, gastric bezoars, intractable hiccups, and migraine pain.[A184961,A184964,A184967,A40105]', '6221042428056', '', 2421, '2022-12-06', CURRENT_TIMESTAMP),
(12975, 'Ritalin 10mg 30 tab', 'ريتالين 10مجم 30 قرص', '', '26', 'Methylphenidate', 'Novartis', 'Tab', 'أقراص', 'علاج فرط نشاط الحركة', 'Attention deficit hyperactivity disorder ADHD', '10mg', 'Methylphenidate is indicated for the treatment of Attention Deficit Hyperactivity Disorder (ADHD) in patients 6 years of age and older and for the treatment of narcolepsy.', '', '', 11307, '2023-02-05', CURRENT_TIMESTAMP),
(33562, 'Royatonic 1000 mg 20 caps', 'روياتونيك 1000 مجم 20 كبسولة', '128', '176', 'Korean ginseng+royal jelly+bee pollen+bee propolis', 'Karman pharmaceutical industries co. > remazain pharma', 'Cap', 'كبسولة', 'مكمل غذائى غنى بالفيتامينات لدعم صحة الجسم مثل الجهاز المناعى وامداد الجسم بالطاقة', 'Tonics', '1000 mg', '', '6225000482920', '', 3455, '2025-07-31', CURRENT_TIMESTAMP),
(20245, 'Halothane b.p 2003 inhaler soln. 100 ml', 'هالوثان محلول مستنشق 100 مل', '', '45', 'Halothane', 'T3a pharma > acdima international trading', 'Sol', 'محلول', '', 'General anaesthesia', '100 ml', 'For the induction and maintenance of general anesthesia', '', '', 1022, '2023-02-03', CURRENT_TIMESTAMP),
(12231, 'Vermin 100mg 6 tab.', 'فيرمين 100مجم 6 اقراص', '3.5', '8', 'Mebendazole', 'Memphis', 'Tab', 'أقراص', 'علاج للديدان', 'Anthelmintic', '100mg', 'For the treatment of <i>Enterobius vermicularis</i> (pinworm), <i>Trichuris trichiura</i> (whipworm), <i>Ascaris lumbricoides</i> (common roundworm), <i>Ancylostoma duodenale</i> (common hookworm), <i>Necator americanus</i> (American hookworm) in single or mixed infections.', '6221050030791', '', 1787, '2025-01-01', CURRENT_TIMESTAMP),
(15351, 'Bistol plus 2.5/6.25mg 20 f.c.tab.', 'بيستول بلس 2.5/6.25 مجم 20 قرص', '20', '30', 'Bisoprolol fumarate+hydrochlorothiazide', 'Hikma pharma', 'Tab', 'أقراص', '', 'Antihypertensive.combined beta blocker with diuretic', '6.25mg', 'Bisoprolol is indicated for the treatment of mild to moderate hypertension.[L7219] It may be used off-label to treat heart failure, atrial fibrillation, and angina pectoris.[A180460,A180463]', '', '', 975, '2024-12-10', CURRENT_TIMESTAMP),
(15076, 'Benylin paed.syrup 120 ml', 'بينيلين شراب 120 مل', '', '7', 'Diphenhydramine+menthol', 'Hikma pharma > johnson & johnson usa', 'Syrup', 'شراب', '', 'Cough drugs', '120 ml', 'about diphenhydramine first generation h1 antagonist ethanolamine derivative antihistamine antiemetic antivertigo sedative and hypnotic. mechanism of action of diphenhydramine antiallergic action: it produces its antihistamine action by competitively bloc', '', '', 901, '2022-08-01', CURRENT_TIMESTAMP),
(31608, 'Vonacidan 20 mg 28 f.c.tabs.', 'فوناسيدان 20مجم 28 قرص', '138', '192', 'Vonoprazan', 'Al esraa pharmaceutical optima', 'Tab', 'أقراص', 'علاج استئصال الملوية البوابية ، والارتجاع المعدي المريئي ، وقرحة المعدة والاثني عشر.', 'Peptic ulcer.potassium-competitive acid blocker', '20 mg', 'Vonoprazan is indicated for the following conditions: 
- for healing of all grades of erosive esophagitis and relief of heartburn associated with erosive esophagitis in adults.[L51224]
- to maintain healing of all grades of erosive esophagitis and relief of heartburn associated with erosive esophagitis in adults.[L51224]
- for the relief of heartburn associated with non-erosive gastroesophageal reflux disease in adults.[L51224]
- in combination with [amoxicillin] and [clarithromycin] for the treatment of Helicobacter pylori (_H. pylori_) infection in adults.[L41695, L51224]
- in combination with amoxicillin for the treatment of H. pylori infection in adults.[L51224]', '6223004160981', '', 9095, '2025-05-24', CURRENT_TIMESTAMP),
(19521, 'Futatreat 750mg 20 f.c. tab.', 'فيوتاتريت 750 مجم 20 قرص', '112', '148', 'Levetiracetam', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', '', 'Anti-epileptic.pyrrolidine', '750mg', 'Levetiracetam is indicated as an adjunctive therapy in the treatment of partial onset seizures in epileptic patients who are one month of age and older. Additionally, it is indicated as an adjunct in the treatment of myoclonic seizures in patients with juvenile myoclonic epilepsy who are 12 years of age and older, and in primary generalized tonic-clonic seizures in patients with idiopathic generalized epilepsy who are 6 years of age and older.[L8606]
Levetiracetam is also available as an orally dissolvable tablet that is indicated as an adjunct in the treatment of partial onset seizures in patients with epilepsy who are 4 years of age and older and weigh more than 20kg.[L8609]', '6223004190803', '', 1385, '2025-09-22', CURRENT_TIMESTAMP),
(24187, 'Opti-women multivitamin 120 caps.', 'اوبتي وومن مالتي فيتامين 120 كبسولة', '', '0', 'Multivitamins+minerals', 'Optimum nutrition > ramco', 'Cap', 'كبسولة', '', 'Supplement', '', 'optimum nutrition opti-womenï- combines 23 vitamins and essential minerals with 17 specialty ingredients to create a comprehensive multivitamin for the active woman. each serving of wide-reaching nutrient support is delivered in vegetarian society approve', '', '', 807, '2022-07-09', CURRENT_TIMESTAMP),
(4516, 'Examide 100 mg 20 tabs', 'اكساميد 100مجم 20 قرص', '108', '144', 'Torsemide', 'Multi-apex', 'Tab', 'أقراص', 'مدر للبول ويستخدم للمساعدة في علاج احتباس السوائل والتورم الناجم عن قصور القلب الاحتقاني كما يستعمل لمرضى ضغط الدم المرتفع،', 'Diuretic.loop', '100 mg', '', '6223003207106', '', 1917, '2025-05-21', CURRENT_TIMESTAMP),
(33387, 'Paxotryps 20 caps', 'باكسوتريبس 20 كبسولة', '78', '110', 'Chymotrypsin+trypsin', 'Paxal pharmaceutical', 'Cap', 'كبسولة', 'مكمل غذائى يدعم صحة الانسجة', 'Enzyme replacement therapy', '', '', '', '', 4092, '2025-07-01', CURRENT_TIMESTAMP),
(3575, 'Capry top cream 40 gm', 'كابري توب كريم 40 جم', '', '39', 'Sulfur+salicylic acid+almond oil', 'Top.z pharma', 'Cap', 'كبسولة', '', 'Skin care', '40 gm', '', '', '', 1003, '2024-06-14', CURRENT_TIMESTAMP),
(28767, 'Unitense 5 mg 10 f.c. tab.', 'يونيتينس 5مجم 10 اقراص', '', '10', 'Benazepril', 'International drug agency (idi)', 'Tab', 'أقراص', '', 'Antihypertensive.ace', '5 mg', 'Benazepril is indicated for the treatment of hypertension[A840]. It may be used alone or in combination with thiazide diuretics[FDA Label].', '', '', 828, '2022-07-24', CURRENT_TIMESTAMP),
(14939, 'Acdisteron 25mg 20 f.c. tabs', 'اكدستيرون 25مجم 20 قرص', '', '65', 'Mesterolone', 'Ait', 'Tab', 'أقراص', '', 'Androgen', '25mg', '', '', '', 3032, '2022-09-04', CURRENT_TIMESTAMP),
(19701, 'Genove genocutan extramild shampoo 250ml', 'جينوفي جينوكيوتان اكستراميلد شامبو 250 مل', '', '120', 'Anionic tensioactives and softanfoters', 'Laboratorio genove s.a.', 'Amp', 'أمبول', '', 'Hair care', '250ml', 'genocuta n extrasuave shampoo can be used alternatively as a complement for antidandruff dry scalp or excessively oily hair treatments. itis also strongly recommended for damaged or colour-treated hair. use: massage into wet hair rinse and repeat if requi', '', '', 638, '2022-08-04', CURRENT_TIMESTAMP),
(4600, 'Pelembab massage gel', 'بليمباب مساج جل', '', '49', 'Camphor+eucalyptus oil+menthol', 'Yojeen', 'Gel', 'جل', '', 'Massage cream', '', '', '', '', 767, '2022-08-27', CURRENT_TIMESTAMP),
(2392, 'Cerebrocetam 1gm/5ml 6 amp.', 'سريبروسيتام 1جم 6 امبولات حقن عضلي او وريدي', '31', '60', 'Piracetam', 'Pharco', 'Amp', 'أمبول', 'لتحسين الدورة الدموية بالمخ', 'Cerebral circulatory inhancer', '1gm', 'Indicated in adult patients suffering from myoclonus of cortical origin, irrespective of aetiology, and should be used in combination with other anti-myoclonic therapies [L1125].', '6221151001683', '', 9939, '2024-12-04', CURRENT_TIMESTAMP),
(2285, 'Kindofer 30 caps', 'كندوفير 30 كبسولة', '', '450', 'Iron bisglycynat (30mg)+lactofern(100mg)+vit (c+e+b1+b6+b12)+folic acid+molybdenum', 'Reda pharma group', 'Cap', 'كبسولة', '', 'Multivitamin', '', 'For treatment of patients with documented iron deficiency in whom oral administration is unsatisfactory or impossible. Also used to replenish body iron stores in Non-Dialysis Dependent-Chronic Kidney Disease (NDD-CKD) patients receiving or not receiving erythropoietin and in Hemodialysis Dependent (HDD-CKD) and Peritoneal Dialysis Dependent (PDD-CKD) - Chronic Kidney Disease patients receiving an erythropoietin.', '', '', 1175, '2025-01-14', CURRENT_TIMESTAMP),
(6790, 'Tendonerve 30 capsules', 'تيندونيرف 30 كبسولة', '', '240', 'Alpha lipoic acid+vitamin b1+vitamin b6+vitamin b12+vitamin d3', 'Revax group - ziax', 'Capsule', 'كبسولة', '', 'Antioxidant & vitamin b', '', '', '', '', 947, '2025-08-13', CURRENT_TIMESTAMP),
(5398, 'Zeluxia 50 gm cream', 'زيلوكسيا كريم 50 جم', '63', '63', 'Propolis-bees wax - panthenol - chamomile extract - glycerin - vitamin c-vitamin e', 'Green cure pharma', 'Cream', 'كريم', '', 'Skin mositurising cream', '50 gm', '', '', '', 713, '2025-02-09', CURRENT_TIMESTAMP),
(29311, 'Vilaphoria 20 mg 30 f.c.tabs.', 'فيلافوريا 20مجم 30 قرص', '162.75', '294', 'Vilazodone', 'Rameda', 'Tab', 'أقراص', '', 'Antidepressant.selective serotonin reuptake inhibitor', '20 mg', 'Vilazodone is approved for treatment of major depressive disorder.[Label,A38477,A177622]', '', '', 2469, '2024-01-22', CURRENT_TIMESTAMP),
(2949, 'Ferosmith 30 caps', 'فيروسميث 30 كبسولة', '', '160', 'Iron+vitamin c+vitamin b6+folate+vitamin b12', 'Bio brand', 'Cap', 'كبسولة', '', 'Dietary supplement', '', '', '', '', 978, '2025-02-11', CURRENT_TIMESTAMP),
(19774, 'Bioprex 10 mg 30 f.c.tabs.', 'بيوبريكس 10 مجم 30 قرص', '160', '195', 'Olanzapine', 'Clavita pharma', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '10 mg', 'Olanzapine was initially used orally and intramuscularly for the chronic treatment of schizophrenia in patients over 13 years old and other psychiatric disorders such as bipolar I disorder including mixed or manic episodes.[A177014] 
Olanzapine is also indicated, in combination with lithium or valproate for the short-term treatment of acute manic or mixed episodes associated with bipolar I disorder in adults.[FDA label]
As well, olanzapine is indicated, in combination with fluoxetine for the treatment of episodes of depression associated with bipolar disorder type 1 and treatment-resistant depression in patients over 10 years old.[A177014]
Olanzapine is also approved for the management of psychomotor agitation associated with schizophrenia and bipolar I mania.[FDA label]
Schizophrenia is a complex biochemical brain disorder that affects the person''s ability to differentiate reality. It is usually observed as the presence of delusions, hallucinations, social withdrawal and disturbed thinking.[L5936]
Bipolar disorder is a mental health condition defined by periods of extreme mood disturbances. It is categorized in different types from which type 1 is known to involve episodes of severe mania and often depression while type 2 presents less severe forms of mania.[L5939]
Olanzapine is also indicated in combination with [samidorphan] for the treatment of bipolar I disorder, either as an adjunct to lithium or valproate or as monotherapy for the acute treatment of manic or mixed episodes or as maintenance therapy, and for the treatment of schizophrenia in adults.[L34359]', '6224011023061', '', 1164, '2025-03-25', CURRENT_TIMESTAMP),
(28109, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 651, '2022-12-30', CURRENT_TIMESTAMP),
