* Dental pain - ibuprofen is used to manage acute and chronic orofacial pain.[A10901]
* Pain - ibuprofen is widely used to reduce minor aches and pains as well as to reduce fever and manage dysmenorrhea. It is very commonly used for the relief of acute indications such as fever and tension headaches.[A39092] It is also used to manage mild to moderate pain and moderate to severe pain as an adjunct to opioid analgesics.[L40208]
* Investigational uses - efforts have been put into developing ibuprofen for the prophylaxis of Alzheimer''s disease, Parkinson disease, and breast cancer.[A39092]', '', '', 811, '2022-07-20', CURRENT_TIMESTAMP),
(5759, 'Sperkoda 20 tabs.', 'سبيركودا 20 قرص', '265', '265', 'L-arginine+acetyl l-carnitine+upedicarinone (coenzyme q10)+lycopene+zinc', 'Praxo pharm', 'Tab', 'أقراص', '', 'Fertility booster', '', '', '', '', 1582, '2024-12-14', CURRENT_TIMESTAMP),
(16195, 'Firstvoc frizz control shampoo & conditioner 150 ml', 'قيرست فوك فريز شامبو وبلسم 150 مل', '', '185', 'Dow corning+vital hair & scalp complex+vitam h+argan oil+emu oil+keratin+wheat germ oil+tea tree oil+vitamin e+aloe vera+panthenol+hydrolyzed wheat protein', 'Medinza pharm', 'Amp', 'أمبول', '', 'Hair care', '150 ml', '', '', '', 680, '2022-09-09', CURRENT_TIMESTAMP),
(30187, 'Biofilm gel 60 gm', 'بيوفيلم جل 60 جم', '70', '80', 'Camphor oil+menthol crystals+peppermint oil+colve oil+eucalyptus oil', 'Dreams elhaboba > organix pharma', 'Gel', 'جل', '', 'Massage gel', '60 gm', 'fast pain relief', '', '', 1781, '2025-11-16', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(30585, 'Gaya 10 sachet', 'جايا 10 اكياس', '75', '110', 'Lactoferrin+colostrum+vitamin e+vitamin c+zinc', 'Medcare > elmasrya elyapania', 'Sachet', 'أكياس', '', 'Multivitamin', '', 'multivitamin dose : twice per day', '', '', 541, '2024-05-18', CURRENT_TIMESTAMP),
(25175, 'Pregna model t cu 380a iud', 'بريجنا موديل تي نحاس 380ايه لولب', '', '18', 'Copper', 'Pregna international limited-india > dkt', 'Unknown', 'غير محدد', '', 'Iud', '', 'For use in the supplementation of total parenteral nutrition and in contraception with intrauterine devices [FDA Label] [L801].', '', '', 1172, '2022-07-08', CURRENT_TIMESTAMP),
(18298, 'Enbrel 25mg 4 pref. syringe', 'انبريل 25مجم 4 سرنجات معبأة للحقن', '4712', '8,904', 'Etanercept', 'Pfizer > pfizer scientific office', 'Syringe', 'حقنة', '', 'Tnf-inhibitor', '25mg', 'Etanercept is indicated for the treatment of moderately to severely active rheumatoid arthritis in adults and in chronic moderate to severe plaque psoriasis in patients 4 years of age and older.[L14862,L45523] It is also used to manage signs and symptoms of polyarticular idiopathic arthritis and Juvenile Psoriatic Arthritis in those aged 2 years and older. Etanercept is also used to manage the symptoms of psoriatic arthritis and ankylosing spondylitis.[L48526]', '', '', 2137, '2024-11-17', CURRENT_TIMESTAMP),
(1604, 'Bisolvon 8 mg 20 tab', 'بيسلفون 8 مجم 20 قرص', '14', '25', 'Bromhexine', 'Cid > boehringer ingelheim', 'Tab', 'أقراص', 'مذيب للبلغم', 'Mucolytic', '8 mg', 'Bromohexine is used alone or with other ingredients such as [diphenhydramine], [dextromethorphan], and [guaifenesin] to reduce mucus viscosity and clear mucus in conditions associated with mucus hypersecretion, including the common cold, influenza, respiratory tract infections, or other conditions.[L29975,L24819,L33060]', '6221043030104', '', 3920, '2024-11-08', CURRENT_TIMESTAMP),
(19076, 'Aaa', 'ششش', '', '22', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 771, '2022-10-14', CURRENT_TIMESTAMP),
(23018, 'Movigretal 100mg 20 tabs.', 'موفيجريتال 1000مجم 20 اقراص', '', '66', 'Cilostazol', 'El nile. > october pharma', 'Tab', 'أقراص', '', 'Antiplatelet.phosphodiesterase 3 inhibitor', '100mg', 'Indicated for the alleviation of symptoms of intermittent claudication (pain in the legs that occurs with walking and disappears with rest).', '', '', 757, '2022-07-17', CURRENT_TIMESTAMP),
(14101, 'Ziadev d3 10.000 30 tab', 'زياديف د3 10.000 وحدة 30 قرص', '90', '120', 'Vitamin d3', 'Hawy pharma group (h. p. g)', 'Tab', 'أقراص', '', 'Vitamin d', '', 'For the treatment of vitamin A deficiency.', '', '', 2071, '2025-03-12', CURRENT_TIMESTAMP),
(21405, 'Kevork 750 mg 10 f.c.tabs.', 'كيفورك 750 مجم 10 اقراص', '91', '121', 'Levofloxacin', 'Organopharma', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '750 mg', 'In oral and intravenous formulations, levofloxacin is indicated in adults for the treatment of various infections caused by susceptible bacteria, including infections of the upper respiratory tract, lower respiratory tract, skin, skin structures, urinary tract, and prostate.[L11638,L11692] The oral formulation is also indicated in both adults and children 6 months of age and older for the post-exposure management of inhalational anthrax caused by _Bacillus anthracis_ and for the treatment and/or prophylaxis of plague caused by _Yersinia pestis_.[L11638]
In its ophthalmic formulation, levofloxacin is indicated for the treatment of bacterial conjunctivitis caused by susceptible organisms.[L11641] An inhalational solution available in Canada is indicated for the management of cystic fibrosis patients aged 18 years or older with chronic pulmonary _Pseudomonas aeruginosa_ infections.[L11689]', '', '', 1143, '2024-03-23', CURRENT_TIMESTAMP),
(24660, 'Penduline kids hair oil 120ml', 'بيندولين زيت شعر للاطفال 120مل', '95', '210', 'Oils of(sesame+wheat germ+coconut+eruca sativa+pumpkin+jojoba+chamomile+olive+almond)', 'Cosmo pack > semak for cosmetics', 'Pen', 'قلم', '', 'Hair care', '120ml', 'natural oil mix how to use: hot oil treatment: wash your hair with shampoo take 30 ml of penduline oil and warm it for 3-5 minutes in water bath massage the oil into scalp using fingertips working your way from roots to ends heat a towel with clothes drye', '6223011114359', '', 581, '2025-09-02', CURRENT_TIMESTAMP),
(24368, 'Ovunhipita 75 mcg 28 tabs.', 'اوفيونهيبيتا 75مكجم 28 قرص', '46', '61', 'Desogestrel', 'Technopharma', 'Tab', 'أقراص', 'اقراص منع الحمل', 'Contraceptives', '75 mcg', 'Oral desogestrel is used in combination with [ethinylestradiol] as a contraceptive agent for the prevention of pregnancy.[FDA label]
Desogestrel is part of the combined oral contraceptives that contain a mix of estrogen and progestin which inhibit ovulation.[L5698]', '6224008302216', '', 6520, '2024-11-21', CURRENT_TIMESTAMP),
(17070, 'Daky whitening cream 60 gm', 'داكي كريم للتبييض 60 جم', '150', '250', '', 'Egyptian co. for cosmetics > medinza pharm', 'Cream', 'كريم', 'كريم لتفتيح وتبييض البشرة', 'Whitening topical', '60 gm', '', '6224001972133', '', 2316, '2024-07-25', CURRENT_TIMESTAMP),
(18108, 'Eflornihair 15 % topical cream 15 gm', 'ايفلورنيهير 15% كريم 15 جم', '', '75', 'Eflornithine', 'Sigma', 'Cream', 'كريم', '', 'Hirsutism', '15 %', 'Eflornithine is indicated to reduce the risk of relapse in adult and pediatric patients with high-risk neuroblastoma (HRNB) who have demonstrated at least a partial response to prior multiagent, multimodality therapy including anti-GD2 immunotherapy.[L49288]  It was also previously indicated for the treatment of female hirsutism and African trypanosomiasis but has since been discontinued.[L49318]', '', '', 934, '2022-07-28', CURRENT_TIMESTAMP),
(2942, 'Coloverin sr 200mg 30 capsules', 'كولوفيرين اس ار 200مجم 30 كبسولة', '', '63', 'Mebeverine', 'Chemipharm', 'Capsule', 'كبسولة', 'علاج القولون العصبى.', 'Antimuscarinic.irritable bowel syndrome', '200mg', '', '6222006501433', '', 5427, '2023-05-18', CURRENT_TIMESTAMP),
(19188, 'Flub 100mg 6 tab.', 'فلوب 100مجم 6 اقراص', '13', '19', 'Flubendazole', 'Unipharma co.', 'Tab', 'أقراص', 'للديدان', 'Anthelmintic', '100mg', 'indication: flubendazol is used in the treatment of single or mixed infections caused by: enterobiasis ascariasis hookworm and trichuriasis contraindications: hypersensitivity to the drug pregnancy and lactation side effects: flubendazol is well tolerated', '6224001183270', '', 1526, '2024-08-13', CURRENT_TIMESTAMP),
(29855, 'Dollar white cream 5% sensitive areas 30 gm', 'دولار وايت كريم 5% مناطق حساسة 30 جم', '', '155', 'Tranexamic acid+ceramide', 'Eleganz', 'Cream', 'كريم', '', 'Whitening cream', '5%', 'Taken orally, tranexamic acid is indicated for the treatment of hereditary angioedema,[L31883] cyclic heavy menstrual bleeding in premenopausal females,[L31858] and other instances of significant bleeding in the context of hyperfibrinolysis.[L31883] Given intravenously, tranexamic acid is indicated for short-term use (2-8 days) in patients with hemophilia to prevent or reduce bleeding following tooth extraction.[L31853]', '', '', 1222, '2023-06-07', CURRENT_TIMESTAMP),
(29679, 'Winrho sdf 300mcg (1500i.u.) i.m./i.v.vial', 'وينرو اس دي اف 300 مكجم (1500وحدة ) حقن', '275', '1,215', 'Rho(d)human immunoglobulin', 'Cangene corporation/canada > egyptian pharmex', 'Vial', 'فيال', 'عدم تطابق rh الدم بين الام والجنين', 'Immunoglobulin g', '300mcg', 'ivigs have demonstrated benefit in a number of primary immune deficiency disorders including b-cell disorders and combined t-cell and b-cell immune deficiency intravenous immunoglobulin (ivig) contains the pooled immunoglobulin g (igg) immunoglobulins fro', '', '', 836, '2022-05-27', CURRENT_TIMESTAMP),
(25075, 'Potafen 50 mg 20 f.c. tabs.', 'بوتافين 50مجم 20 اقراص', '', '28', 'Diclofenac potassium', 'Sigma > top pharm', 'Tab', 'أقراص', '', 'Nsaid.acetic acid derivatives', '50 mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6224009437030', '', 1485, '2022-12-08', CURRENT_TIMESTAMP),
(10409, 'Aaa', 'ششش', '', '18', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 482, '2022-12-08', CURRENT_TIMESTAMP),
(4121, 'Emeral 5 paed. supp. (n/a)', 'ايميرال 5 اقماع لبوس اطفال', '', '3', 'Caffeine+chlorotheophylline+chlorphenoxamine', 'Eipico', 'Supp', 'لبوس', '', 'Antiemetic', '', '', '6221032250162', '', 789, '2023-05-01', CURRENT_TIMESTAMP),
(3606, 'Diaphage 1000mg 30 tablets', 'دايافاج 1000مجم 30 قرص', '', '12', 'Metformin', 'Pharopharma', 'Tablet', 'أقراص', 'علاج لمرضى السكر', 'Antidiabetic.weight loss', '1000mg', '**Metformin immediate-release formulations**
Metformin is indicated as an adjunct to diet and exercise to improve glycemic control in adults and pediatric patients ≥10 years old with type 2 diabetes mellitus.[L40243]
**Metformin extended-release tablet (XR)**
The extended-release formulation of metformin is indicated as an adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus. Safety in children has not been determined to this date.[L12207]
**Metformin combination products**
Metformin is a component of a variety of combination products with other anti-diabetic agents. It is indicated, along with diet and exercise, to improve glycemic control in adult patients with type 2 diabetes mellitus in combination with DPP-4 inhibitors ([sitagliptin], [linagliptin], [alogliptin], or [saxagliptin]),[L11479,L40248,L40253,L40258,L40263] in combination with SGLT2 inhibitors ([canagliflozin], [empagliflozin], [ertugliflozin], or [dapagliflozin]),[L11479,L30503,L1134,L13679,L38729] or in combination with [pioglitazone].[L11419]', '6221094085740', '', 1417, '2022-12-04', CURRENT_TIMESTAMP),
(18660, 'Aaa', 'ششش', '', '23', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 800, '2022-10-07', CURRENT_TIMESTAMP),
(20814, 'Infinity post laser gel 120 gm', 'انفينيتي جل بعد الليزر 120 جم', '', '160', 'Hydrogenated castor oil+honey+panthenol+chamomile ext+green tea ext+aloe vera ext+calendula ext', 'Egyptian company for cosmetics > infinity pharm', 'Gel', 'جل', '', 'Moisturizing topicals', '120 gm', '', '', '', 755, '2022-07-31', CURRENT_TIMESTAMP),
(23978, 'Oflicin 200mg 10 f.c.tab.', 'اوفليسين 200مجم 10 اقراص', '', '24', 'Ofloxacin', 'Memphis', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '200mg', 'For the treatment of infections (respiratory tract, kidney, skin, soft tissue, UTI), urethral and cervical gonorrhoea.', '6221050030128', '', 983, '2022-12-07', CURRENT_TIMESTAMP),
(20746, 'Immuno-mash 30 f.c. tabs', 'اميونوماش 30 قرص', '90', '120', 'Vitamin c+zinc gluconate', 'Mash premiere', 'Tab', 'أقراص', '- يساعد في تقوية الجهاز المناعي وخصوصا في حالات الأمراض الفيروسية مثل كورونا كوفيد-19 وغيرها.', 'Immune enhancer', '', 'For the treatment of vitamin A deficiency.', '6222001406399', '', 7042, '2025-11-23', CURRENT_TIMESTAMP),
(5046, 'Uni yeast 60 tab', 'يوني ييست خميرة 60 قرص', '95', '125', 'Prebiotic+probiotic+vitamin b1+b2+b3', 'United international pharma', 'Tab', 'أقراص', '', 'Prebiotic & probiotic', '', '', '', '', 1440, '2025-07-29', CURRENT_TIMESTAMP),
(6036, 'Mirramorcare face serum 50 ml', 'ميراموركير سيروم للوجه 50 مل', '', '250', 'Hyaluronic acid+alpha arbutin+arginine', 'Repair pharma', 'Serum', 'سيروم', '', 'Skin care', '50 ml', 'The intra-articular preparations of hyaluronic acid are indicated for knee pain associated with osteoarthritis.[L32228] Hyaluronic acid is used in cosmetic applications to prevent and reduce the appearance of wrinkles on the face, and as a dermal filler to correct facial imperfections or other imperfections on other parts of the body.[L32208,L32223] It is frequently an ingredient in topical applications for wound healing and symptomatic treatment of skin irritation from various causes.[L32198] Hyaluronic acid may also be indicated in ophthalmological preparations or oral capsules to treat discomfort caused by dry eyes or conjunctivitis and for its protective qualities during and before eye surgery.[A230128,L32213] Finally, hyaluronic acid can be used off-label to coat the bladder for relief of interstitial cystitis symptoms.[A230533]', '', '', 828, '2025-07-17', CURRENT_TIMESTAMP),
(30460, 'Elbaluran 60 mg 30 f.c. tabs.', 'البالوران 60مجم 30 قرص', '', '354', 'Lurasidone', 'Apex pharma', 'Tab', 'أقراص', 'علاج انفصام الشخصية، للبالغين والمراهقين الذين يبلغون من العمر 13 عاماً', 'Antipsychotics.2nd generation', '60 mg', 'Lurasidone is indicated for the treatment of schizophrenia in patients ≥13 years old.[L16103] It is also indicated as a monotherapy for the treatment of bipolar depression in patients ≥10 years old, or in combination with lithium or valproate for the treatment of bipolar depression in adults.[L16103]', '', '', 1493, '2023-07-30', CURRENT_TIMESTAMP),
(16131, 'Cephraforte 1000mg 10 f.c.tab.', 'سيفرافورت 1000 مجم 10 قرص', '', '18', 'Cephradine', 'Sigma > sina pharm', 'Tab', 'أقراص', '', 'Antibiotic.cephalosporin.first-generation', '1000mg', 'description a semi-synthetic cephalosporin antibiotic. mechanism of action cefradine is a first generation cephalosporin antibiotic with a spectrum of activity similar to cefalexin. cefradine like the penicillins is a beta-lactam antibiotic. by binding to', '', '', 789, '2022-07-18', CURRENT_TIMESTAMP),
(1406, 'Benzyl soap', 'صابون بنزايل', '', '7', 'Antiseptic soap', 'Pharopharma', 'Soap', 'صابون', '', '', '', '', '', '', 847, '2022-09-19', CURRENT_TIMESTAMP),
(30272, 'Carbidopa/levodopa-eva 250/25 mg 20 tabs.', 'كاربيدوبا/ليفودوبا ايفا 25025مجم 20 قرص', '63', '86', 'Carbidopa+levodopa', 'Eva pharma', 'Tab', 'أقراص', '', 'Parkinson s disease.dopamine agonist', '25 mg', 'about carbidopa a noncompetitive dopa decarboxylase inhibitor antidyskinetics anti-parkinson`s agent. mechanism of action of carbidopa carbidopa inhibits the peripheral decarboxylation of levodopa and thus slowing its conversion to dopamine in extra cereb', '', '', 3401, '2025-09-10', CURRENT_TIMESTAMP),
(25600, 'R.b.g 10 caps.', 'ار.بي. جي 10 كبسولات', '', '36', 'Royal jelly+wheat germ oil+bee pollen+bee propolis+korean ginseng+lecithin', 'Arab caps > napco', 'Cap', 'كبسولة', 'مكمل غذائي -- تقوية المناعة -- تعزيز الذاكرة -- مقوي للرجال -- يعمل علي تعزيز طاقة الجسم', 'Multivitamins', '', '', '', '', 2305, '2022-05-20', CURRENT_TIMESTAMP),
(8898, 'Nitroderm tts 5 mg 7 patches', 'نيترودرم تي تي اس 5مجم 7 لصقات', '63', '126', 'Nitroglycerin', 'Novartis > sandoz', 'Patch', 'لصقة', 'موسع للشعب الهوائية -- علاج الازمات التنفسية -- تحسين التنفس', 'Anti-ischemic', '5 mg', 'Sublingual nitroglycerin is indicated for the acute relief of an attack or acute prophylaxis of angina pectoris due to coronary artery disease.[L7102,L38369,L42320] Transdermal nitroglycerin is indicated for the prevention of angina pectoris due to coronary artery disease.[L7141]
Intravenous nitroglycerin is indicated for the treatment of peri-operative hypertension; for control of congestive heart failure in the setting of acute myocardial infarction; for treatment of angina pectoris in patients who have not responded to sublingual nitroglycerin and beta (β)-blockers; and for induction of intraoperative hypotension.[L7099] 
Topical nitroglycerin ointment is used to treat moderate to severe pain associated with chronic anal fissure.[L42445]', '6223002640232', '', 3363, '2024-11-17', CURRENT_TIMESTAMP),
(3122, 'Quadriderm cream 30 gm', 'كوادريديرم كريم 30 جم', '32', '48', 'Betamethasone+clioquinol+gentamicin+tolnaftate', 'Memphis > schering plough', 'Cream', 'كريم', '', '', '30 gm', 'dosage: a thin film of quadriderm cream should be applied to cover completely the affected area two or three times daily or as prescribed by the physician. frequency of application should be determined according to severity of the condition. indications a', '6221050130286', '', 5816, '2024-07-23', CURRENT_TIMESTAMP),
(3706, 'Oxanomeg 10 capsules', 'اوكسانوميج 10 كبسولات', '', '75', '', '', 'Capsule', 'كبسولة', '', 'Antioxidant', '', '', '', '', 4970, '2023-01-14', CURRENT_TIMESTAMP),
