year of age and older 
• Pathologic hypersecretory conditions in adults', '6221032131577', '', 1763, '2022-12-05', CURRENT_TIMESTAMP),
(30206, 'Blemil plus preterm milk 400 gm', 'بليميل بلس بريتيرم لبن اطفال 400 جم', '230', '295', 'Premature milk formula', 'Laboratorios ordesa > ramco', 'Unknown', 'غير محدد', '', 'Milk products.prematue milk formula', '400 gm', 'specially formulated for preterm and low birth weight infants. it could be discontinued under medical advice after a weight of 3 kgm has been reached or until 2 months corrected age. to be used within one month from opening.', '', '', 765, '2024-02-20', CURRENT_TIMESTAMP),
(27564, 'Strepsils honey & lemon 24 lozenges', 'ستربسلز بالعسل والليمون لالتهاب الحلق والحنجرة 24 قطعة', '165', '200', 'Dichlorophenylcarbinol+amylmetacresol', 'Reckitt benckiser healthcare > united partners company', 'Lozenges', 'استحلاب', 'علاج وتخفيف التهاب واحتقان الحلق والحنجرة', 'Sore throat', '', 'soothing effective relief for sore throats', '6222048703444', '', 4184, '2024-09-29', CURRENT_TIMESTAMP),
(18342, 'Enteroquin comp. pd. for oral susp. 60 ml', 'انتروكين كومب باودر لعمل معلق 60 مل', '', '5', 'Homatropine methylbromide+iodoquinol+kaolin+phthalyl sulphathiazole+sulphadimidine+vitamin b1+b6+b12', 'Arab drug company.', 'Susp', 'معلق', '', 'Antidiarrheal', '60 ml', 'Used in conjunction with antacids or histamine H2-receptor antagonists in the treatment of peptic ulcers, gastric ulcers and duodenal ulcers, to reduce further gastric acid secretion and delay gastric emptying.', '6221060000760', '', 998, '2023-05-12', CURRENT_TIMESTAMP),
(23689, 'Nonan i.v. infusion', 'نونان محلول وريد', '', '23', 'Ammonium molybdate+cobalt+copper+iron+magnesium+sodium fluoride+sodium iodide+zinc gluconate', 'Laborataire aguettant > multi-apex', 'Unknown', 'غير محدد', '', '', '', '1. Expectorant in cough syrups.
2. The ammonium ion (NH4+) in the body plays an important role in the maintenance of acid-base balance. The kidney uses ammonium (NH4+) in place of sodium (Na+) to combine with fixed anions in maintaining acid-base balance, especially as a homeostatic compensatory mechanism in metabolic acidosis.
The therapeutic effects of Ammonium Chloride depend upon the ability of the kidney to utilize ammonia in the excretion of an excess of fixed anions and the conversion of ammonia to urea by the liver, thereby liberating hydrogen (H+) and chloride (Cl–) ions into the extracellular fluid.
Ammonium Chloride Injection, USP, after dilution in isotonic sodium chloride injection, may be indicated in the treatment of patients with:
 (1) hypochloremic states and (2) metabolic alkalosis.', '', '', 893, '2022-07-30', CURRENT_TIMESTAMP),
(28075, 'Terventin 20mg 10 f.c.tab.', 'ترفنتين 20مجم 10 اقراص', '', '18', 'Bambuterol', 'Egyphar', 'Tab', 'أقراص', '', 'Bronchodilator.long acting beta 2 agonist', '20mg', 'For the prevention and reversal of bronchospasm in patients 12 years of age and older with asthma and reversible bronchospasm associated with bronchitis and emphysema.', '6224001026546', '', 735, '2022-12-13', CURRENT_TIMESTAMP),
(375, 'Allear 5 mg 20 f.c.tabs.', 'اليير 5مجم 20 قرص', '52', '78', 'Levocetirizine', 'Western pharmaceuticals industries', 'Tab', 'أقراص', '', 'Antihistamine.non-sedative.third-generation', '5 mg', 'Levocetirizine is indicated to treat symptoms of perennial allergic rhinitis and uncomplicated skin manifestations of chronic idiopathic urticaria.[L7694] It is also used over the counter for a variety of mild allergy symptoms.[A181748]', '6224007308097', '', 4271, '2024-12-10', CURRENT_TIMESTAMP),
(24418, 'Oxynorm 10 mg/ml 5 i.m./i.v. amp.', 'اوكسينورم 10مجم/مل 5 امبول حقن وريد او عضل', '', '150', 'Oxycodone', 'Hamol limited > egyptian pharmaceutical trading company', 'Amp', 'أمبول', '', 'Analgesic', '10 mg', 'Oxycodone is indicated for the treatment of moderate to severe pain.[Label] There is also an extended release formulation indicated for chronic moderate to severe pain requiring continuous opioid analgesics for an extended period.[Label]', '', '', 901, '2022-07-21', CURRENT_TIMESTAMP),
(26622, 'Scino beem cream 125 gm', 'ساينو بيم كريم 125جم', '', '199', '', 'Hi-care > scin.off scientific office', 'Cream', 'كريم', '', 'Moisturizing topicals', '125 gm', 'skin soothing cream cream to protect & soothe nappy rash with natural ingredients .. 0% alcohol', '', '', 568, '2022-08-03', CURRENT_TIMESTAMP),
(32600, 'Calcium 3 - 20 tabs.', 'كالسيوم 3 - 20 قرص', '70', '95', 'Calcium+magnesium+vitamin d3', 'Plasma pharm', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '6225000488823', '', 1088, '2024-06-01', CURRENT_TIMESTAMP),
(8649, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 677, '2023-05-03', CURRENT_TIMESTAMP),
(14880, 'Cervetolka plus 500/50 mg 20 caps.', 'سيرفيتولكا بلس 500/5مجم 20 كبسولة', '300', '360', 'Citicoline+tyrosine', 'Biomed', 'Cap', 'كبسولة', 'دعم الوظائف الطبيعية للمخ والذاكرة والتركيز', 'Cerebral circulatory inhancer', '50 mg', '', '', '', 8693, '2024-08-03', CURRENT_TIMESTAMP),
(3679, 'Vera care advance 60 ml gel', 'فيرا كير ادفانس جل 60 مل', '', '265', 'Lactroproxidase enzyme+sodium algenate+macrogols', 'Avento pharmaceutical', 'Gel', 'جل', '', 'Deep wound management', '60 ml', '', '6224002151056', '', 1077, '2025-05-03', CURRENT_TIMESTAMP),
(4370, 'Olanvexa 20 mg 30 orally disintegrating tabs.', 'اولانفيكسا 20 مجم 30 قرص ذائب بالفم', '', '327', 'Olanzapine', 'Multicare', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '20 mg', 'Olanzapine was initially used orally and intramuscularly for the chronic treatment of schizophrenia in patients over 13 years old and other psychiatric disorders such as bipolar I disorder including mixed or manic episodes.[A177014] 
Olanzapine is also indicated, in combination with lithium or valproate for the short-term treatment of acute manic or mixed episodes associated with bipolar I disorder in adults.[FDA label]
As well, olanzapine is indicated, in combination with fluoxetine for the treatment of episodes of depression associated with bipolar disorder type 1 and treatment-resistant depression in patients over 10 years old.[A177014]
Olanzapine is also approved for the management of psychomotor agitation associated with schizophrenia and bipolar I mania.[FDA label]
Schizophrenia is a complex biochemical brain disorder that affects the person''s ability to differentiate reality. It is usually observed as the presence of delusions, hallucinations, social withdrawal and disturbed thinking.[L5936]
Bipolar disorder is a mental health condition defined by periods of extreme mood disturbances. It is categorized in different types from which type 1 is known to involve episodes of severe mania and often depression while type 2 presents less severe forms of mania.[L5939]
Olanzapine is also indicated in combination with [samidorphan] for the treatment of bipolar I disorder, either as an adjunct to lithium or valproate or as monotherapy for the acute treatment of manic or mixed episodes or as maintenance therapy, and for the treatment of schizophrenia in adults.[L34359]', '', '', 892, '2025-06-17', CURRENT_TIMESTAMP),
(2155, 'Catalin 1 tablet with 15 solventfor instillation', 'كاتالين 1ق', '', '34', 'Pirenoxine', 'Senju pharmaceutical co.', 'Tablet', 'أقراص', '', '', '', '', '', '', 853, '2022-09-21', CURRENT_TIMESTAMP),
(3469, 'Dermatop 0.25% cream 10 gm', 'ديرماتوب 0.25% كريم 10 جم', '', '10', 'Prednicarbate', 'Global napi pharmaceuticals > sanofi pasteur-france', 'Cream', 'كريم', '', 'Glucocorticoid', '0.25%', 'For the relief of the inflammatory and pruritic manifestations of corticosteroid-responsive dermatoses.', '6223002148370', '', 1602, '2022-12-04', CURRENT_TIMESTAMP),
(19942, 'Glucovance 1000/5mg 30 f.c.tab.', 'جلوكوفانس 1000/5مجم 30 قرص', '75', '124', 'Glibenclamide(glyburide)+metformin', 'Merck sante-france > oasis commercial agency', 'Tab', 'أقراص', '', 'Anti-diabetic.combined secretagogues+sensitizers', '5mg', 'about metformin biguanide derivative oral anti-diabetic. mechanism of action of metformin it is a biguanide which exerts antidiabetic action. the drug suppresses gluconeogenesis in liver and thus suppresses hepatic glucose output. it enhance insulin media', '', '', 4310, '2024-09-02', CURRENT_TIMESTAMP),
(28860, 'Uromes 400mg/4ml 5 amp.for i.v. inj. 4 ml', 'يوروميز 400مجم/4مل 5 امبول4مل', '155', '415', 'Mesna', 'Hikma specialized pharmaceuticals', 'Inj', 'حقن', 'منع نزيف المثانة (التهاب المثانة النزفية) خلال العلاج الكيميائي', 'Uroprotectant', '400mg', '', '', '', 1003, '2024-12-05', CURRENT_TIMESTAMP),
(4672, 'Farcopril 25mg 20 tab.', 'فاركوبريل 25مجم 20 قرص', '', '4', 'Captopril', 'Pharco', 'Tab', 'أقراص', '', 'Antihypertensive.ace', '25mg', 'For the treatment of essential or renovascular hypertension (usually administered with other drugs, particularly thiazide diuretics). May be used to treat congestive heart failure in combination with other drugs (e.g. cardiac glycosides, diuretics, &beta;-adrenergic blockers). May improve survival in patients with left ventricular dysfunction following myocardial infarction. May be used to treat nephropathy, including diabetic nephropathy.', '', '', 884, '2022-12-02', CURRENT_TIMESTAMP),
(7899, 'Cutersy anti-dandruff lotion 100 ml', 'كيوترسي لوشن مضاد للقشرة 100 مل', '', '220', 'Piroctone olamine+zinc pyrithione+tea trea extract+saw palmetto+rosemary extract+salicylic acid+panthenol', 'Versy pharmaceutical', 'Lotion', 'لوشن', '', 'Antifungal, antibacterial, antioxidant, moisturizer', '100 ml', '', '', '', 793, '2025-11-04', CURRENT_TIMESTAMP),
(4921, 'Flamotal 800 mg 10 tabs.', 'فلاموتال 800مجم 10 قرص', '24', '35', 'Ibuprofen', 'Global napi pharmaceuticals > future pharmaceutical industries (fpi)', 'Tab', 'أقراص', '', 'Nsaid.propionic acid derivatives', '800 mg', 'Ibuprofen is the most commonly used and prescribed NSAID. It is a very common over-the-counter medication widely used as an analgesic, anti-inflammatory and antipyretic.[A39096]
The use of ibuprofen and its enantiomer [DB09213] in a racemic mix is common for the management of mild to moderate pain related to dysmenorrhea, headache, migraine, postoperative dental pain, spondylitis, osteoarthritis, rheumatoid arthritis, and soft tissue disorder.[A39097]
Due to its activity against prostaglandin and thromboxane synthesis, ibuprofen has been attributed to alteration of platelet function and prolongation of gestation and labour.[A39092]
As ibuprofen is a widely used medication, the main therapeutic indications are:
* Patent Ductus Arteriosus - it is a neonatal condition wherein the ductus arteriosus (blood vessel that connects the main pulmonary artery to the proximal descending aorta) fails to close after birth causing severe risk of heart failure. The prostaglandin inhibition of ibuprofen has been studied for the treatment of this condition as it is known that prostaglandin E2 is responsible for keeping the ductus arteriosus open.[A39100]
* Rheumatoid- and osteo-arthritis - ibuprofen is very commonly used in the symptomatic treatment of inflammatory, musculoskeletal and rheumatic disorders.[A39176]
* Cystic fibrosis - the use of high dosages of ibuprofen has been proven to decrease inflammation and decreasing polymorphonuclear cell influx in the lungs.[A39177]
* Orthostatic hypotension - ibuprofen can induce sodium retention and antagonize the effect of diuretics which has been reported to be beneficial for patients with severe orthostatic hypotension.[A1651]
* Dental pain - ibuprofen is used to manage acute and chronic orofacial pain.[A10901]
* Pain - ibuprofen is widely used to reduce minor aches and pains as well as to reduce fever and manage dysmenorrhea. It is very commonly used for the relief of acute indications such as fever and tension headaches.[A39092] It is also used to manage mild to moderate pain and moderate to severe pain as an adjunct to opioid analgesics.[L40208]
* Investigational uses - efforts have been put into developing ibuprofen for the prophylaxis of Alzheimer''s disease, Parkinson disease, and breast cancer.[A39092]', '6223004190025', '', 1913, '2024-09-25', CURRENT_TIMESTAMP),
(26740, 'Selgon 10mg 6 infant supp.', 'سيلجون 10مجم 6 اقماع لبوس رضع', '9', '15', 'Pipazethate', 'Eipico', 'Supp', 'لبوس', '', 'Anti-cough', '10mg', 'For the treatment of cough.', '6221032250384', '', 5996, '2024-07-23', CURRENT_TIMESTAMP),
(25130, 'Prandaglim met 12.5/500 mg 30 f.c. tabs.', 'برانداجليم ميت 12.5/500محم 30 اقراص', '', '96', 'Alogliptin+metformin', 'Eva pharma', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.dpp-4 inhibitors', '500 mg', 'alogliptin is an orally administered anti-diabetic drug in the dpp-4 inhibitor class. like other medications for the treatment of type 2 diabetes alogliptin does not decrease the risk of heart attack and stroke. like other members of the gliptin class it', '', '', 812, '2022-07-27', CURRENT_TIMESTAMP),
(29111, 'Venoxor 75 mg 28 tabs.', 'فينوكسور 75مجم 28 اقراص', '', '82', 'Venlafaxine', 'Unipharma co.', 'Tab', 'أقراص', '', 'Psychiatric.antidepressants', '75 mg', 'Venlafaxine is indicated for the management of major depressive disorder (MDD), generalized anxiety disorder (GAD), social anxiety disorder (SAD), and panic disorder.[L43030]', '', '', 1054, '2022-07-16', CURRENT_TIMESTAMP),
(31401, 'Sputal syrup 100 ml', 'سبوتال شراب 100 مل', '38', '55', 'Ivy leaves', 'Organix > biotec', 'Syrup', 'شراب', 'مكمل غذائى مهدئ للسعال وطارد للبلغم ويحسن وظائف الجهاز التنفسي', 'Anti-cough.antitussive and expectorant', '100 ml', 'sputal syrup for productive cough', '6225000507319', '', 1628, '2025-08-10', CURRENT_TIMESTAMP),
(16578, 'Co- avazir eye oint. 5 gm', 'كو افازير مرهم للعين 5 جم', '19.5', '30', 'Dexamethasone+tobramycin', 'Orchidia pharmaceutical industries', 'Oint', 'مرهم', '', 'Antibiotic with glucocorticoid', '5 gm', 'about dexamethasone a potent synthetic glucocorticoid antiasthmatic anti-inflammatory and immunosuppressant. mechanism of action of dexamethasone the drug exerts it`s pharmacological action by penetrating and binding to cytoplasmic receptor protein and ca', '6223005441652', '', 3344, '2024-08-20', CURRENT_TIMESTAMP),
(5090, 'Vismed 0.18% eye drops 20 x 0.3 ml sdu', 'فيزميد 0.18% قطرة عين 20 * 0.3 مل وحدات مفردة', '', '290', 'Sodium hyaluronate', 'Rheuma', 'Drops', 'نقط', '', 'Eye surgery.tissue lubricant', '0.18%', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '4028694000829', '', 702, '2025-06-23', CURRENT_TIMESTAMP),
(31607, 'Vonacidan 10 mg 20 f.c.tabs.', 'فوناسيدان 10مجم 20 قرص', '64', '72', 'Vonoprazan', 'Al esraa pharmaceutical optima', 'Tab', 'أقراص', 'علاج استئصال الملوية البوابية ، والارتجاع المعدي المريئي ، وقرحة المعدة والاثني عشر', 'Peptic ulcer.potassium-competitive acid blocker', '10 mg', 'Vonoprazan is indicated for the following conditions: 
- for healing of all grades of erosive esophagitis and relief of heartburn associated with erosive esophagitis in adults.[L51224]
