(15322, 'Bio-whey protein powder 420 gm 14 serve', 'بايو-واي بروتين بودرة 420 جم 14 جرعة', '', '230', 'Skimmed milk+whey protein isolate+whey protein concentrate', 'Bio pharma egypt', 'Powder', 'بودرة', '', 'Dietary supplement', '420 gm', '', '', '', 912, '2022-07-18', CURRENT_TIMESTAMP),
(30058, 'Averocal d syrup 120 ml', 'افيروكال دي شراب 120 مل', '', '35', 'Calcium glubionate+vitamin d3+cyanocobalamine+vitamin k1', 'Averroes pharma', 'Syrup', 'شراب', '', 'Calcium supplement', '120 ml', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 1147, '2024-05-14', CURRENT_TIMESTAMP),
(30100, 'Alin 20 film coated tablets', 'الين 20 قرص', '95', '120', 'Selenium+zinc+magnesium+vit.c+vit.e+vit.d+vit.a+b1+b2+b5+b6+b12', 'Pharma zad > genebiotic-egypt', 'Tablet', 'أقراص', '', 'Multivitamin', '', 'selenium .. 60 mcg', '', '', 792, '2025-06-25', CURRENT_TIMESTAMP),
(31604, 'Vivanta mix plus hair serum 100 ml', 'فيفانتا ميكس بلس سيرم للشعر 100 مل', '250', '325', 'Stemoxydine', 'Egyptian company for cosmetics > pharmix', 'Serum', 'سيروم', '', 'Hair care', '100 ml', 'contains 5% stemoxydine', '', '', 753, '2024-03-04', CURRENT_TIMESTAMP),
(28253, 'Toleen antiseptic spray 80 ml', 'تولين سبراي مطهر 80مل', '', '25', 'Ethyl alcohol 70%', '> lusenda pharma', 'Spray', 'بخاخ', 'سبراى مطهر للقضاء على البكتيريا والفطريات', 'Antiseptic', '80 ml', 'Investigated for use/treatment in burns and burn infections, cardiac surgery, inflammatory disorders (unspecified), ischemic reperfusion injury, and sepsis and septicemia.', '', '', 987, '2022-07-12', CURRENT_TIMESTAMP),
(26461, 'Quetiasu 25mg 30 tabs', 'كويتياسو 25 مجم 30 قرص', '', '63', 'Quetiapine', 'Sun pharma', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '25mg', 'Quetiapine is used in the symptomatic treatment of schizophrenia.  In addition, it may be used for the management of acute manic or mixed episodes in patients with bipolar I disorder, as a monotherapy or combined with other drugs. It may be used to manage depressive episodes in bipolar disorder. In addition to the above indications, quetiapine is used in combination with antidepressant drugs for the treatment of major depression.[L8546]
Some off-label uses for this drug include the management of post-traumatic stress disorder (PTSD), generalized anxiety disorder, and psychosis associated with Parkinson''s disease.[A185438,A185447,T685]', '', '', 905, '2022-10-05', CURRENT_TIMESTAMP),
(260, 'Alcofan 100 mg 5 supp.', 'الكوفان 100مجم لبوس 5 اقماع', '', '7', 'Ketoprofen', 'Alexandria', 'Supp', 'لبوس', '', 'Nsaid.propionic acid derivatives', '100 mg', 'For symptomatic treatment of acute and chronic rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, primary dysmenorrhea and mild to moderate pain associated with musculotendinous trauma (sprains and strains), postoperative (including dental surgery) or postpartum pain.', '6223000172438', '', 1371, '2022-12-01', CURRENT_TIMESTAMP),
(15961, 'Cebion 100mg/ml oral drops 30 ml', 'سيبيون 100 مجم / مل نقط 30 مل', '', '6', 'Vitamin c', 'Amoun > merck kgaa f.r.germany', 'Drops', 'نقط', '', 'Vitamin c', '100mg', 'For the treatment of vitamin A deficiency.', '6221025012418', '', 1020, '2022-12-03', CURRENT_TIMESTAMP),
(20868, 'Insulinagypt n 100 i.u./ml (10ml) vial', 'انسوليناجيبت ان 100 وحدة دولية / مل 10 مل فيال', '48', '77', 'Insulin isophane protamine human', 'Mup', 'Vial', 'فيال', '', 'Anti-diabetic.insulin analouge', '10ml', 'Human insulin is indicated to improve glycemic control in adults and pediatric patients with diabetes mellitus.', '', '', 1069, '2025-03-09', CURRENT_TIMESTAMP),
(9496, 'Burnasores 0.25% oint. 30 gm', 'برناسورس مرهم 30 جرام', '100', '150', 'Beta-sitosterol', 'Global napi pharmaceuticals', 'Oint', 'مرهم', '', 'Healing topical', '0.25%', 'beta-sitosterol is used for heart disease and high cholesterol. it is also used for boosting the immune system and for preventing colon cancer as well as for gallstones the common cold and flu (influenza) hiv/aids rheumatoid arthritis tuberculosis psorias', '6223002143597', '', 2390, '2024-06-13', CURRENT_TIMESTAMP),
(5753, 'Melano sulfur soap', 'ميلانو صابونة كبريت', '', '60', '', 'Melano pharma', 'Soap', 'صابون', '', '', '', '', '', '', 1021, '2024-06-11', CURRENT_TIMESTAMP),
(21501, 'Kyprolis 60 mg pd. iv inf. vial', 'كيبروليس 60مجم وريد فيال', '18310', '25,047', 'Carfilzomib', 'Amgen > multipharma', 'Vial', 'فيال', '', 'Antineoplastic agent.proteasome inhibitor', '60 mg', 'Carfilzomib is indicated for the treatment of adult patients with relapsed or refractory multiple myeloma who have received one to three lines of therapy in combination with lenalidomide and dexamethasone; or dexamethasone; or daratumumab and dexamethasone; or daratumumab and hyaluronidase-fihj and dexamethasone; or isatuximab and dexamethasone. It is also indicated as a single agent for the treatment of patients with relapsed or refractory multiple myeloma who have received one or more lines of therapy.[L39392,L42350]', '', '', 1520, '2025-08-23', CURRENT_TIMESTAMP),
(6925, 'Dk trudal(d3&k2)30 tabs', 'دي كي ترودال (د3 مع كي2) 30 قرص', '', '200', 'Vitamin d3&k2', 'Medicolena', 'Tab', 'أقراص', '', 'Supplement', '', 'For the treatment of vitamin A deficiency.', '', '', 955, '2025-08-16', CURRENT_TIMESTAMP),
(31581, 'Vildagluse plus 50/500 mg 30 tabs.', 'فيلداجلوز بلس 50500مجم 30 قرص', '120', '132', 'Metformin hydrochloride+vildagliptin', 'Debeiky > inspire pharmaceutical company', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.dpp-4 inhibitors', '500 mg', '**Metformin immediate-release formulations**
Metformin is indicated as an adjunct to diet and exercise to improve glycemic control in adults and pediatric patients ≥10 years old with type 2 diabetes mellitus.[L40243]
**Metformin extended-release tablet (XR)**
The extended-release formulation of metformin is indicated as an adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus. Safety in children has not been determined to this date.[L12207]
**Metformin combination products**
Metformin is a component of a variety of combination products with other anti-diabetic agents. It is indicated, along with diet and exercise, to improve glycemic control in adult patients with type 2 diabetes mellitus in combination with DPP-4 inhibitors ([sitagliptin], [linagliptin], [alogliptin], or [saxagliptin]),[L11479,L40248,L40253,L40258,L40263] in combination with SGLT2 inhibitors ([canagliflozin], [empagliflozin], [ertugliflozin], or [dapagliflozin]),[L11479,L30503,L1134,L13679,L38729] or in combination with [pioglitazone].[L11419]', '6224000866860', '', 2342, '2024-06-25', CURRENT_TIMESTAMP),
(18908, 'Felodipin stada 10 mg 10 mr tabs.', 'فيلوديبين ستادا 10 مجم ام ار 10 اقراص', '', '24', 'Felodipine', 'Global napi pharmaceuticals > stada', 'Tab', 'أقراص', '', 'Antihypertensive.selective calcium channel blocker', '10 mg', 'For the treatment of mild to moderate essential hypertension.', '', '', 737, '2022-07-13', CURRENT_TIMESTAMP),
(27465, 'Starlidine 120mg 10 f.c.tab.', 'ستارليدين 120 مجم 10اقراص', '', '15', 'Nateglinide', 'International drug agency (idi)', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.glinides', '120mg', 'For the treatment of non-insulin dependent-diabetes mellitus in conjunction with diet and exercise.', '', '', 757, '2022-07-29', CURRENT_TIMESTAMP),
(30945, 'Moscow massage cream 100 gm', 'موسكو كريم مساج 100 جم', '85', '95', 'Glucosamine+methyl salicylate+menthol+camphor+vitamin c+emu oil+omga3', 'Hi care > tetra pharm', 'Cream', 'كريم', 'كريم مساج يستخدم فى تخفيف الألم ,تنشيط الدورة الدموية , إزالة التوتر ,يمنح الجسم الاسترخاء ويحد من توتر العضلات.', 'Massage cream', '100 gm', 'massage cream glucosamine+methyl salicylate+menthol+camphor+vitamin c+emu oil+ega3', '6225000502314', '', 7753, '2025-05-14', CURRENT_TIMESTAMP),
(25654, 'Rame-zithro 1% eye drops 2.5 ml', 'رامي-زيثرو 1% قطرة للعين 2.5مل', '', '18', 'Azithromycin', 'Rameda', 'Drops', 'نقط', '', 'Antibiotic.macrolide', '1%', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '', '', 1018, '2022-07-17', CURRENT_TIMESTAMP),
(27657, 'Sun sola solution 60 ml', 'سانسولا محلول 60 مل', '', '29', 'Aluminium chloride+calcium hydroxide+menthol', 'Zad', 'Solution', 'محلول', 'علاج فرط التعرق', '', '60 ml', '*dental use: it cleanse prevent stains and relief inflammation (2.5 ml to be added to 100 ml water) *dermatological use: helps to decrease sweatening in persons suffering from hyperhydrosis (used without dilution).', '', '', 1052, '2022-05-29', CURRENT_TIMESTAMP),
(14073, 'Amristatin 40mg 10 f.c. tab.', 'امريستاتين 40مجم 10 أقراص', '', '33', 'Simvastatin', 'Amriya', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '40mg', 'Simvastatin is indicated for the treatment of hyperlipidemia to reduce elevated total cholesterol (total-C), low-density lipoprotein cholesterol (LDL‑C), apolipoprotein B (Apo B), and triglycerides (TG), and to increase high-density lipoprotein cholesterol (HDL-C).[F4655, F4658]
This includes the treatment of primary hyperlipidemia (Fredrickson type IIa, heterozygous familial and nonfamilial), mixed dyslipidemia (Fredrickson type IIb), hypertriglyceridemia (Fredrickson type IV hyperlipidemia), primary dysbetalipoproteinemia (Fredrickson type III hyperlipidemia), homozygous familial hypercholesterolemia (HoFH) as an adjunct to other lipid-lowering treatments, as well as adolescent patients with Heterozygous Familial Hypercholesterolemia (HeFH).[F4655, F4658]
Simvastatin is also indicated to reduce the risk of cardiovascular morbidity and mortality including myocardial infarction, stroke, and the need for revascularization procedures. It is primarily used in patients at high risk of coronary events because of existing coronary heart disease, diabetes, peripheral vessel disease, history of stroke or other cerebrovascular disease.[F4655, F4658]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '', '', 786, '2022-12-03', CURRENT_TIMESTAMP),
(26472, 'Aaa', 'ششش', '', '19', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 753, '2023-07-09', CURRENT_TIMESTAMP),
(12666, 'Aaa', 'ششش', '', '3', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 784, '2022-08-06', CURRENT_TIMESTAMP),
(9479, 'Msg-fer 120 ml syrup', 'ام اس جي فير شراب 120 مل', '', '49', 'Ferrous bisglycinate + vit b6 + vit b12', 'Msg pharma', 'Syrup', 'شراب', '', 'Multivitamin', '120 ml', 'Ferrous sulfate is used for the prevention and treatment of iron deficiency anemia in adults and children.[A190804,L2240,L11800]', '', '', 652, '2022-08-17', CURRENT_TIMESTAMP),
(12556, 'Elong 60mg 4 tab', 'ايلونج 60مجم 4 قرص', '', '240', 'Dapoxetine', 'Damam', 'Tab', 'أقراص', 'للتأخير للرجال', 'Delay action', '60mg', 'For the treatment of premature ejaculation.', '', '', 5000, '2023-02-04', CURRENT_TIMESTAMP),
(29204, 'Vetovancin 1 gm i.v. vial', 'فيتوفانسين 1جم فيال', '123', '176', 'Vancomycin', 'Sigma tec > vetopharm-egypt', 'Vial', 'فيال', '', 'Antibiotic tricyclic glycopeptide', '1 gm', 'Administered intravenously, vancomycin is indicated in adult and pediatric patients for the treatment of septicemia, infective endocarditis, skin and skin structure infections, bone infections, and lower respiratory tract infections.[L41529] Administered orally, vancomycin is indicated in adult and pediatric patients for the treatment of _Clostridium difficile_-associated diarrhea and for enterocolitis caused by _Staphylococcus aureus_ (including methicillin-resistant strains).[L41534]', '', '', 1331, '2024-12-15', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(27684, 'Sunnyshift 4 mg i.v. inf. vial', 'صاني شيفت 4مجم فيال وريدي', '', '650', 'Zoledronic acid', 'Sunny pharmaceuticals', 'Vial', 'فيال', 'منع وعلاج هشاشة العظام -- علاج زيادة الكالسيوم في الدم', 'Osteoporosis.bisphosphonates', '4 mg', 'Zoledronic acid is indicated to treat hypercalcemia of malignancy, multiple myeloma, bone metastases from solid tumors, osteoporosis in men and postmenopausal women, glucocorticoid induced osteoporosis, and Paget''s disease of bone in men and women.[L13712,L13715,L13721] Zoledronic acid is also indicated for the prevention of osteoporosis in post menopausal women and glucocorticoid induced osteoporosis.[L13712,L13715,L13721]', '', '', 1975, '2022-05-15', CURRENT_TIMESTAMP),
(4996, 'Tola kids leave-in cream 100 ml', 'تولا كيدز ليف ان كريم 100مل', '', '189', 'Hair care', '', 'Cream', 'كريم', '', 'ALBA PHARMA', '100 ml', '', '', '', 678, '2025-06-22', CURRENT_TIMESTAMP),
