**Pantoprazole delayed-release oral suspension**:
**Short-Term Treatment of erosive esophagitis associated with gastroesophageal reflux disease (GERD)**
Indicated in adults and pediatric patients five years of age and above for the short-term treatment (up to 8 weeks) in the healing and symptomatic relief of erosive esophagitis. For adult patients who have not healed after 8 weeks of treatment, an additional 8-week course of pantoprazole may be considered. Safety of treatment beyond 8 weeks in pediatric patients has not been determined.[F3202]
**Maintenance of healing of erosive esophagitis**
Indicated for maintenance of healing of erosive esophagitis and reduction in relapse rates of daytime and nighttime heartburn symptoms in adult patients with GERD.[F3202]
**Pathological hypersecretory conditions including Zollinger-Ellison syndrome**
Indicated for the long-term treatment of the above conditions.[F3202]', '', '', 1019, '2025-01-25', CURRENT_TIMESTAMP),
(30164, 'Asmatropim 250mcg/ml 20 nebulizer vial soln.', 'اسماتروبيم 250مكجم/مل 20 امبول', '70', '100', 'Ipratropium bromide', 'Global advanced pharmaceuticals (gap) > global pharmaceutical industries', 'Vial', 'فيال', 'مضاد لازمات الربو', 'Anti-muscarinic.asthma', '250mcg', 'Inhaled ipratropium is indicated in combination with inhaled beta-agonist systemic corticosteroids for the management of severe exacerbations of asthma flares requiring treatment.[A176939]
Asthma exacerbations are characterized by a progressive increase in one or more of asthma symptoms accompanied by a decrease in expiratory flow.[L5900]
As a single agent, ipratropium was indicated for the symptomatic relief of rhinorrhea associated with the common cold or seasonal allergic rhinitis for patients 5 years or older. It does not alleviate nasal congestion nor sneezing.[FDA label]
Rhinorrhea refers to recurrent or chronic watery nasal discharge. This condition is debilitating and its pathogenesis and etiology is complex and not very well understood presenting very substantial cost burden.[L5903]
Additionally, ipratropium is indicated as a bronchodilator for maintenance treatment of bronchospasm associated with chronic obstructive pulmonary disease including chronic bronchitis and emphysema.[FDA label]
The chronic obstructive pulmonary disease includes a large number of conditions characterized by breathlessness. As this includes several conditions, the etiology, symptoms, and treatments are diverse.[L5906]
Ipratropium has also been studied to be used for the treatment of sialorrhea.[A176942]
Sialorrhea is a common symptom that accompanies different neurologic conditions and it is characterized by drooling or excessive salivation.[A176963]', '6223004901317', '', 4070, '2024-08-11', CURRENT_TIMESTAMP),
(18576, 'Espax 20 capsules', 'اسباكس 20 كبسولة', '', '30', 'Peppermint oil 40 mg +ginger oil 40 mg +chamomile oil 40 mg +fennel oil 40 mg +caraway oil40 mg', 'Arab caps > egypt pharma group', 'Capsule', 'كبسولة', '', 'Git disturbances', '', 'Indicated for the over-the-counter use for:
-the symptomatic relief of minor spasms of the gastrointestinal tract, flatulence and abdominal pain, especially in patients with irritable bowel syndrome.
-the temporary relief of itching associated with insect bites, eczema, minor burn, sunburn, minor skin irritations, minor cuts, scrapes, atopic dermatitis and other skin disorders.
-the temporary symptomatic relief of mild joint and muscle pain as a local topical analgesic.
-the temporary relief of tension-type headache.', '', '', 802, '2022-07-29', CURRENT_TIMESTAMP),
(9367, 'Aaa', 'ششش', '', '42', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 839, '2022-05-30', CURRENT_TIMESTAMP),
(25796, 'Regenerate 30mg 20 caps.', 'ريجينيريت 30مجم 20 كبسولة', '', '10', 'Adenosine triphosphate disodium', 'Pharopharma', 'Cap', 'كبسولة', '', 'Antioxidant', '30mg', 'For nutritional supplementation, also for treating dietary shortage or imbalance', '', '', 1005, '2022-06-18', CURRENT_TIMESTAMP),
(29013, 'Vascomedra 600mg 30 f.c. tab.', 'فاسكوميدرا 600مجم 30 قرص', '64.5', '108', 'Diosmin', 'Mash premiere > biomed', 'Tab', 'أقراص', 'مقوي الأوردة والأوعية الدموية -- يقلل من ظهور الدوالي في الجسم', 'Vascular-protecting agent', '600mg', 'Diosmin is used over-the-counter alone or with ingredients such as [hesperidin] and [diosmetin] to support vein and capillary function.[L32823,L32848]', '', '', 2782, '2024-09-27', CURRENT_TIMESTAMP),
(16631, 'Colgy 10 sachets', 'كولجي 10 اكياس', '', '130', 'Gelatin (collagen) hydrolysate+vitamin c', 'Pharma zad > dawaa pharma', 'Sachet', 'أكياس', 'يستخدم كعلاج لالتهاب المفاصل --الروماتويد.', 'Antirheumatic.osteoarthritis.anabolic agents', '', 'Gelatin is used for weight loss and for treating osteoarthritis, rheumatoid arthritis, and brittle bones (osteoporosis). Some people also use it for strengthening bones, joints, and fingernails. Gelatin is also used for improving hair condition and to shorten the recovery after exercise and sports-related injury [L2113]. Gelatin is used in preparations of foods, cosmetics, and medicine [L2113].
Plasma volume expander in hypovolaemic shock [L2115]. Haemostatic [L2115].
Gelatin-based hydrogels are being used in drug delivery and tissue engineering because they are able to promote cell adhesion and proliferation. In addition, these hydrogels can be used as wound dressings because of their attractive fluid absorbance properties. Manufacturing technologies such as ultraviolet stereolithography and two-photon polymerization can be used to prepare structures containing photosensitive gelatin-based hydrogels [L2111].', '6224008851141', '', 2122, '2023-02-02', CURRENT_TIMESTAMP),
(14849, 'Baby choice cream 75gm', 'بيبي تشويس كريم 75 جم', '', '49', 'Zinc oxide+olive oil', 'Leader for cosmetics > globe international pharmaceuticals', 'Cream', 'كريم', '', 'Diaper rash', '75gm', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 848, '2022-07-11', CURRENT_TIMESTAMP),
(23221, 'Nalbuphine 20mg/ml i.m./i.v./s.c.amp.', 'نالبوفين 20مجم/مل امبول', '17.25', '33', 'Nalbuphine', 'Cid > spimaco misr', 'Amp', 'أمبول', '', 'Analgesics.opioid', '20mg', 'For the relief of moderate to severe pain.', '', '', 1117, '2024-11-05', CURRENT_TIMESTAMP),
(10532, 'Sinupret forte 50 sugar c.tabs.', 'سينوبريت فورت 50 قرص', '154', '210', 'Elder flowers+gentian root+primose flowers+shop vervain wort+sorrel herb', 'Bionorica ag-germany > technomed group-egypt', 'Tab', 'أقراص', 'مضاد للاحتقان -- تقليل الالام بالحلق -- تقليل الالتهابات', 'Decongestant', '', '', '4029799166243', '', 7592, '2025-08-11', CURRENT_TIMESTAMP),
(11509, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 798, '2022-12-26', CURRENT_TIMESTAMP),
(14053, 'Ampiclox 500mg 12caps.', 'امبيكلوكس 500 مجم 12 كبسولة', '', '9', 'Ampicillin+cloxacillin', 'Mup > smithkline beecham', 'Cap', 'كبسولة', '', 'Penicillins.penicillin with b-lactamase inhibitor', '500mg', 'indications 1.respiratory tract infection 2.urinary tract infection 3.bone and joint infection 4.skin infection 5.soft tissue infection dose: adult: 250 - 500mg every 6 hours for 7 - 10 days. mechanism of action of ampicillin ampicillin is a bactericidal', '6221508020114', '', 1472, '2022-12-02', CURRENT_TIMESTAMP),
(28644, 'Uft 28 capsules', 'يو اف تي 28 كبسول', '', '650', 'Tegafur+uracil', 'Merck kgaa f.r.germany > merck kgaa f.r-egypt', 'Capsule', 'كبسولة', '', 'Antineoplastic', '', 'uft is an anticancer medication composed of a fixed molar ration (1:4) of tegafur and uracil to be administered with calcium folinate. in the body tegafur is converted into 5-fluorouracil (5-fu) the active antineoplastic metabolite. the mechanism of cytot', '', '', 485, '2022-08-06', CURRENT_TIMESTAMP),
(24623, 'Pedia topical spray 100 ml', 'بيديا سبراي موضعي 100مل', '', '25', 'Aloe vera+chlorhexidine+menthol+panthenol+chamomile+bee propolis+tea tree oil+glycerin', 'Hi-care > pedia pharma', 'Spray', 'بخاخ', 'سبراى معقم ومرطب للجلد', 'Antiseptic', '100 ml', 'Indicated for use as a topical agent to soothe sensitive skin and to relieve symptoms of various skin conditions, including contact or atopic dermatitis, eczema, dermatitis and acne urticata, first- and second-degree burns, radiation dermatitis, and sunburn.', '', '', 921, '2022-07-10', CURRENT_TIMESTAMP),
(14059, 'Aaa', 'ششش', '', '12', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 675, '2022-09-06', CURRENT_TIMESTAMP),
(10818, 'Spironolactone (delta) 50mg 10 tab.', 'سبيرونولاكتون 50مجم 10 اقراص', '', '5', 'Spironolactone', 'Global napi pharmaceuticals > al delta pharmaceuticals trading co.', 'Tab', 'أقراص', '', 'Diuretic.potassium-sparing diuretics', '50mg', 'Spironolactone is indicated for the treatment of the following conditions:
- NYHA Class III-IV heart failure and reduced ejection fraction to increase survival, manage edema, and reduce the need for hospitalization for heart failure. Spironolactone is usually administered in conjunction with other heart failure therapies.[L44602]
- Hypertension, as add-on therapy, in patients not adequately controlled by other agents.[L44602, L47810]
- Edema associated with hepatic cirrhosis when edema is not responsive to fluid and sodium restriction.[L44602, L47810]
- Edema associated with nephrotic syndrome when treatment of the underlying disease, restriction of fluid and sodium intake, and the use of other diuretics produce an inadequate response.[L44602]
- Refractory edema associated with congestive cardiac failure, malignant ascites, hepatic cirrhosis with ascites, and essential hypertension.[L47810]
- Short-term preoperative treatment of patients with primary hyperaldosteronism.[L44602, L47810]
- Diagnosis of primary aldosteronism.[L47810]
- Long-term maintenance therapy for patients with discrete aldosterone-producing adrenal adenomas who are not candidates for surgery.[L44602]
- Long-term maintenance therapy for patients with bilateral micro or macronodular adrenal hyperplasia (idiopathic hyperaldosteronism).[L44602]
As spironolactone has antiandrogenic activity, its off-label uses include the treatment of hirsutism, female pattern hair loss, and adult acne vulgaris.[A178135, A261025]', '', '', 1000, '2022-10-18', CURRENT_TIMESTAMP),
(24852, 'Pharocola 60 eff. granules sachets', 'فاروكولا 60 كيس حبيبات فوارة', '', '33', 'Citric acid+sodium bicarbonte+tartaric acid', 'Pharopharma', 'Sachet', 'أكياس', '', 'Antacid', '', 'interactions: antacids:concurrent use of antacids with citrates may result in systemic alkalosis. concomitant administration of antacids with sodium citrate and sodium bicarbonate may promote the development of calcium stones in patients with uric acid st', '', '', 889, '2022-07-08', CURRENT_TIMESTAMP),
(6020, 'Hepatic forte 30 soft gelatin caps.', 'هيباتيك فورت 30 كبسولة', '', '21', 'Orotic acid+phospholipids+silymarin', 'Adwia', 'Cap', 'كبسولة', 'علاج مساعد لامراض الكبد مثل تليف الكبد والتهاب الكبد الوبائي -- علاج حصوات المرارة -- الحد من مستوي السكر في الدم لدي مرضي السكر', 'Liver support supplements', '', 'about silymarin a polyphenolic flavonoid hepatoprotective(antihepatotoxic) antioxidant. mechanism of action of silymarin silymarin stimulates rna polymerase a and results in an increase in ribosomal protein synthesis and leads to the synthesis of new hepa', '6223002976447', '', 1283, '2022-10-29', CURRENT_TIMESTAMP),
(32647, 'Clarivee vaginal wash 250 ml', 'كلاريفي غسول مهبلي 250 مل', '86', '87', 'Thyme. tea tree oil. malva sylvestris. chamomile. calendula. aloevera gel. citric acid. rose oil', 'Novogen', 'Vaginal wash', 'غسول مهبلي', '', 'Vaginal cleanser', '250 ml', '', '', '', 658, '2025-08-06', CURRENT_TIMESTAMP),
(8502, 'Mylobac 25mg 20 tabs.', 'ميلوباك 25مجم 20 قرص', '21', '34', 'Baclofen', 'Pharopharma', 'Tab', 'أقراص', 'باسط للعضلات ومسكن آلام', 'Cns.analgesic.skeletal muscle relaxant', '25mg', 'Oral baclofen is indicated for the treatment of spasticity resulting from multiple sclerosis and is particularly useful for the relief of flexor spasms and concomitant pain, clonus, and muscular rigidity. It may also be used to treat patients with spinal cord injuries and other spinal cord diseases. Baclofen should not be used to treat skeletal muscle spasms resulting from rheumatic disorders.[L39434]
Intrathecal baclofen is also indicated for the management of severe spasticity of the cerebral or spinal original in patients 4 years of age and older. It is reserved for patients unresponsive to oral baclofen therapy, or those who experience intolerable central nervous system side effects at effective doses. For use in spasticity due to traumatic brain injury, baclofen should be considered after at least one year of injury.[L39429]', '6221094502414', '', 7024, '2024-09-04', CURRENT_TIMESTAMP),
