(17098, 'Danset 8mg/4ml 3 amp.', 'دانست 8مجم/4مل 3 امبولات حقن عضل/وريد', '142.5', '159', 'Ondansetron', 'Adwia', 'Amp', 'أمبول', 'مضاد للقيء والترجيع', 'Antiemetic', '8mg', 'In the adult patient population:
i) orally administered ondansetron tablets and orally disintegrating tablets (ODT) are indicated for:
- the prevention of nausea and vomiting associated with emetogenic cancer chemotherapy, including high dose (ie. greater than or equal to 50 mg/m2) cisplatin therapy, and radiotherapy, and
- the prevention and treatment of postoperative nausea and vomiting
ii) intravenously administered ondansetron injection formulations are indicated for:
- the prevention of nausea and vomiting associated with emetogenic cancer chemotherapy, including high dose (ie. greater than or equal to 50 mg/m2) cisplatin therapy, and
- the prevention and treatment of postoperative nausea and vomiting
In the pediatric (4-18 years of age) patient population:
i) ondansetron was effective and well tolerated when given to children 4-12 years of age for the treatment of post-chemotherapy induced nausea and vomiting,
ii) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for the treatment of children 3 years of age or younger,
iii) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for use in any age group of the pediatric population for the treatment of post-radiotherapy induced nausea and vomiting, and
iV) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for use in any age group of the pediatric population for the treatment of postoperative nausea and vomiting
In the geriatric (>65 years of age) patient population:
i) efficacy and tolerance of ondansetron were similar to that observed in younger adults for the treatment of post-chemotherapy and radiotherapy-induced nausea and vomiting, and
ii) clinical experience in the use of ondansetron in the prevention and treatment of postoperative nausea and vomiting is limited and is not indicated for use in the geriatric patient population', '6223002978304', '', 22487, '2025-10-21', CURRENT_TIMESTAMP),
(5736, 'Rocoxar 120 mg 7 tabs.', 'روكوكسار 120مجم 7 اقراص', '', '64', 'Etoricoxib', 'Delta pharma', 'Tab', 'أقراص', '', 'Nsaid.selective cox-2 inhibitors', '120 mg', 'For the treatment of rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, chronic low back pain, acute pain and gout.', '6221163016019', '', 1214, '2025-07-07', CURRENT_TIMESTAMP),
(26015, 'Rheumarene 1% gel 20 gm', 'رومارين 1% جل 20جم', '14.5', '22', 'Diclofenac sodium', 'Sedico', 'Gel', 'جل', '', 'Nsaid.acetic acid derivatives', '1%', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6221042300017', '', 985, '2025-11-23', CURRENT_TIMESTAMP),
(16453, 'Claudizol 100 mg 30 tab.', 'كلوديزول 100 مجم 30 قرص', '', '90', 'Cilostazol', 'Genesis pharmaceuticals', 'Tab', 'أقراص', '', 'Antiplatelet.phosphodiesterase 3 inhibitor', '100 mg', 'Indicated for the alleviation of symptoms of intermittent claudication (pain in the legs that occurs with walking and disappears with rest).', '', '', 724, '2022-07-24', CURRENT_TIMESTAMP),
(26499, 'Sandostatin lar 30 mg vial i.m.+pref. syringe', 'ساندوستاتين لار 30مجم فيال عضل + سرنجة معبأة', '13500', '18,246', 'Octreotide', 'Novartis', 'Vial', 'فيال', 'هرمونات الغدة النخامية', 'Hypothalmic hormones.somatostatin analogues', '30 mg', 'Octreotide by injection is used for the treatment of acromegaly and the reduction of flushing and diarrhea symptoms related to carcinoid tumors and/or vasoactive intestinal peptide (VIPoma) tumors.[L14513] The delayed-release oral formulation is used for the long-term treatment of acromegaly in patients who tolerate and respond adequately to injectable octreotide and [lanreotide].[L14507,L45528]', '', '', 4702, '2024-11-06', CURRENT_TIMESTAMP),
(21577, 'Lamivex acne gel 50 gm', 'لاميفيكس جل لحب الشباب 50 جرام', '95', '110', 'Lactic acid+glycolic acid+chlorhexidine+sulphur+retinol+liquorice+vitamin c+vitamin e+aloe vera+panthenol', 'Egyptian co. for cosemetics > three one pharma', 'Gel', 'جل', 'لحب الشباب', 'Anti-acne', '50 gm', 'For use as an alkalinizing agent.', '', '', 7227, '2025-09-17', CURRENT_TIMESTAMP),
(28590, 'Trusopt 2 % opthalmic solution 5 ml', 'تروسوبت 2% محلول للعين 5مل', '', '57', 'Dorzolamide', 'Mundipharma > multipharma', 'Solution', 'محلول', '', 'Antiglaucoma', '2 %', 'Dorzolamide is indicated for the management of elevated intraocular pressure in patients with ocular hypertension or open-angle glaucoma.[L11377] It can also be used in combination with [timolol] for the same indication in patients who are insufficiently responsive to ophthalmic beta-blockers.[L11380]
Its pre-operative use was also investigated to prevent elevated intraocular pressure after neodynium yttrium aluminum garnet laser posterior capsulotomy.[A190183]', '', '', 728, '2022-08-02', CURRENT_TIMESTAMP),
(22545, 'Mepabrufen 20 tab.', 'ميبابروفين 20 قرص', '', '7', 'Ibuprofen+paracetamol(acetaminophen)', 'Mepaco', 'Tab', 'أقراص', '', 'Nsaid', '', 'ibuprofen is a type of medicine called a non-steroidal anti-inflammatory drug (nsaid). it works by blocking the action of a substance in the body called cyclo-oxygenase (cox). cyclo-oxygenase is involved in the production of various chemicals in the body', '6223002212163', '', 848, '2023-01-05', CURRENT_TIMESTAMP),
(15210, 'Bio balance organic argan oil conditioner 180 ml', 'بيو بالانس بلسم بزيت الارجان العضوي 180 مل', '', '177', '', 'Alpaya dermaceuticals > vamer pharma', 'Conditioner', 'بلسم', '', 'Hair care', '180 ml', 'reverses damage with each use. restores moisture and continuously hydrates while protecting hair from future damage. the rich creamy conditioner formulated with organic argan oil shea butter niacinamide panthenol soy corn and wheat proteins reverses damag', '', '', 634, '2022-08-03', CURRENT_TIMESTAMP),
(17253, 'Dentocaine 7.5% dental gel 10 gm', 'دنتوكايين 7.5% جل للاسنان 10 جم', '', '4', 'Benzocaine', 'Pharco', 'Gel', 'جل', '', 'Analgesic.local anesthetic', '7.5%', 'Benzocaine is indicated for local anesthesia in dentistry, minor trauma, and as preparation for infiltrative anesthesia.[A231219] Benzocaine products are indicated for topical anesthesia in a wide variety of conditions including skin irritation,[L32454] oral pain,[L32459] and hemorrhoids.[L32464]', '6223000013267', '', 1391, '2022-12-04', CURRENT_TIMESTAMP),
(31948, 'Vavra b neuro 30 capsules', 'فافرا بي نيورو 30 كبسولة', '149', '185', 'Vitamins b1+b2+b3+b5+b6+biotin+folic acid+b12', 'Copad egypt > trendy company', 'Capsule', 'كبسولة', 'مكمل غذائى يستخدم لعلاج الانيميا وتحسين الجهاز العصبى', 'Vitamin b complex', '', 'empower your healthy life', '', '', 2379, '2024-12-01', CURRENT_TIMESTAMP),
(8867, 'Aaa', 'ششش', '', '9', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 504, '2023-01-14', CURRENT_TIMESTAMP),
(4923, 'Flash act 50mg 9 sachets', 'فلاش اكت 5 اكياس', '21', '30', 'Diclofenac potassium', 'European egyptian pharm. ind.', 'Sachet', 'أكياس', 'مسكن وخافض للحرارة ومضاد للالتهابات', 'Nsaid.acetic acid derivatives', '50mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6221076181576', '', 2928, '2024-10-30', CURRENT_TIMESTAMP),
(16006, 'Nearby you skin moisturizing 30gm cream', 'نيرباي يو كريم مرطب ملطف للجلد 30 جم', '', '45', 'Panthenol-urea - shea butter - dimethicone potassium hydroxide - glycerin - sodium benzoate - aloe vera leaf extract - stearic acid - paraffin wax - glyceryl stearate - water', 'Near international', 'Cream', 'كريم', '', 'Moisturising cream', '30gm', '', '', '', 1234, '2024-07-14', CURRENT_TIMESTAMP),
(10594, 'Aaa', 'ششش', '', '34', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 589, '2022-08-15', CURRENT_TIMESTAMP),
(12872, 'Aaa', 'ششش', '', '9', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 793, '2022-10-11', CURRENT_TIMESTAMP),
(17825, 'Donifoxate 80 mg 30 f.c. tablets', 'دونيفوكسات 80 مجم 30 قرص', '85.75', '119', 'Febuxostat', 'Eva pharma', 'Tablet', 'أقراص', '', 'Antigout', '80 mg', 'Febuxostat is indicated for the chronic management of hyperuricemia in adult patients with gout who have an inadequate response to a maximally titrated dose of [allopurinol], who are intolerant to allopurinol, or for whom treatment with allopurinol is not advisable.[L46073] It is not recommended for the treatment of asymptomatic hyperuricemia [L32238] or secondary hyperuricemia.[A230583]', '6224009763092', '', 2904, '2023-11-20', CURRENT_TIMESTAMP),
(3143, 'Immuphi 100 ml syrup', 'اميوفي شراب 100 مل', '', '555', 'Omega iii+vitamin e', 'Phi pharma', 'Syrup', 'شراب', '', 'High concentration of omega 3', '100 ml', '', '', '', 940, '2025-02-25', CURRENT_TIMESTAMP),
(25419, 'Prothiaden 75mg 10 tab.', 'بروثيادين 75 مجم 10 قرص.', '', '18', 'Dothiepin', 'Kahira > abbott laboratories', 'Tab', 'أقراص', '', 'Tricyclic antidepressant', '75mg', '', '6221068905647', '', 1335, '2022-12-08', CURRENT_TIMESTAMP),
(17671, 'Dimicap facial wash 250 ml', 'ديميكاب غسول وجه 250 مل', '149', '194', 'Aloe vera+chamomile+tea tree oil+vitamin e+panthenol+glycerin+allantoin+salicylic acid', 'Hi-care > capital pharma', 'Cap', 'كبسولة', '1- منظف لطيف مناسب لجميع أنواع البشرة.', 'Skin care', '250 ml', 'Indicated for use as a topical agent to soothe sensitive skin and to relieve symptoms of various skin conditions, including contact or atopic dermatitis, eczema, dermatitis and acne urticata, first- and second-degree burns, radiation dermatitis, and sunburn.', '', '', 16440, '2024-03-05', CURRENT_TIMESTAMP),
(27668, 'Suncross kids spf 50+ sunscreen lotion 200 ml', 'صن كروس للاطفال spf+50 لوشن 200 مل', '', '250', '', 'Kempetro for chemical industries > novell pharma', 'Lotion', 'لوشن', '', 'Sunblock', '200 ml', '', '', '', 674, '2022-08-18', CURRENT_TIMESTAMP),
(26043, 'Rhinomol-s syrup 120ml', 'رينومول اس شراب للبرد للاطفال', '31', '40', 'Chlorpheniramine+paracetamol(acetaminophen)+pseudoephedrine', 'El nile.', 'Syrup', 'شراب', 'تخفيف أعراض نزلات البرد للأطفال.', 'Common cold drugs', '120ml', 'indication: runny noses blocked noses and sinus sneezing watery itchy eyes sinus pain fever headache body aches & pain information: pseudoephedrine hydrochloride belongs to a group of medicines called sympathomimetic decongestants. it works by reducing co', '6221077051816', '', 6644, '2025-10-01', CURRENT_TIMESTAMP),
(3161, 'Cibinqo 100 mg 28 f.c.tabs', 'سيبينكو 100 مجم 28 قرص', '', '22,427', 'Abrocitinib', 'Pfizer biopharmaceuticals egypt', 'Tab', 'أقراص', '', 'Dermatological drugs', '100 mg', 'Abrocitinib is indicated for the treatment of moderate-to-severe atopic dermatitis in adults who are candidates for systemic therapy.[L39774] In the US, it is indicated to treat refractory, moderate-to-severe atopic dermatitis whose disease is not adequately controlled with other systemic drug products, including biologics, or when the use of those therapies is inadvisable.[L39769]
Abrocitinib is not recommended for use in combination with other JAK inhibitors, biologic immunomodulators, or other immunosuppressants.[L39769]', '', '', 925, '2025-02-26', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(13832, 'Aaa', 'ششش', '', '9', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 843, '2022-10-15', CURRENT_TIMESTAMP),
(30965, 'Mydrithalm 1% eye drops 20*0.5 ml sdu', 'ميدريثالم 1% نقط عين 20*0.5 مل', '70', '104', 'Tropicamide', 'Eva pharma', 'Drops', 'نقط', '', 'Mydriatic', '1%', 'Tropicamide is indicated to induce mydriasis (dilation of the pupil) for diagnostic procedures and in conditions where short-term pupil dilation is desired, either as monotherapy [L32103] or in combination with [hydroxyamphetamine] [L32178] or [phenylephrine].[L46332] It provides clinically significant mydriasis with partial cycloplegia.[L32178]', '6223004516238', '', 1755, '2024-06-27', CURRENT_TIMESTAMP),
(4293, 'Epirax 20 tab.', 'ابيراكس 20 قرص', '', '8', 'Chlordiazepoxide+clidinium bromide', 'Eipico', 'Tab', 'أقراص', 'مضا دلتقلصات المعدة والقولون -- تقليل الالام القولون -- تقليل الانتفاخات والغازات', 'Spastic colon', '', '(chlordiazepoxide and clidinium) combines in a single capsule formulation the antianxiety action of chlordiazepoxide hydrochloride and the anticholinergic/spasmolytic effects of clidinium bromide. chlordiazepoxide hydrochloride is a versatile therapeutic', '6221032112217', '', 1765, '2022-09-29', CURRENT_TIMESTAMP),
(14924, 'Saginkgo 30 caps.', 'ساجينكو 30 كبسولة', '135', '180', 'Ginkgo biloba', 'Sato pharma', 'Cap', 'كبسولة', '', 'Blood circulation inhancer', '', '_Ginkgo biloba_ does not currently have any approved therapeutic indications, and there is insufficient evidence to support its unapproved use.[A232379] It is available in over-the-counter herbal products mostly for oral use, to improve memory and cognitive problems.', '6225000457461', '', 2295, '2025-10-11', CURRENT_TIMESTAMP),
(27023, 'Aaa', 'ششش', '', '69', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 748, '2022-10-24', CURRENT_TIMESTAMP),
(30225, 'Breathovance nebulizer soln. 20 amp. 2.5ml', 'بريثوفانس محلول للاستنشاق 20 امبول 2.5 مل', '65', '90', 'Ipratropium bromide+salbutamol', 'Global advanced pharmaceuticals (gap)', 'Amp', 'أمبول', 'مضاد للربو ,علاج ازمات التنفس و الانسداد الرئوى المزمن', 'Anti-muscarinic.asthma.combined with beta agonist', '2.5ml', 'Inhaled ipratropium is indicated in combination with inhaled beta-agonist systemic corticosteroids for the management of severe exacerbations of asthma flares requiring treatment.[A176939]
Asthma exacerbations are characterized by a progressive increase in one or more of asthma symptoms accompanied by a decrease in expiratory flow.[L5900]
As a single agent, ipratropium was indicated for the symptomatic relief of rhinorrhea associated with the common cold or seasonal allergic rhinitis for patients 5 years or older. It does not alleviate nasal congestion nor sneezing.[FDA label]
Rhinorrhea refers to recurrent or chronic watery nasal discharge. This condition is debilitating and its pathogenesis and etiology is complex and not very well understood presenting very substantial cost burden.[L5903]
Additionally, ipratropium is indicated as a bronchodilator for maintenance treatment of bronchospasm associated with chronic obstructive pulmonary disease including chronic bronchitis and emphysema.[FDA label]
