**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '6224000396572', '', 934, '2022-07-08', CURRENT_TIMESTAMP),
(27710, 'Supermix 15 gm 7 sachets', 'سوبر ميكس 15جم 7 اكياس', '', '84', 'Amino acids+vitamins+minerals', 'Lemako misr factory > lmco pharm co.', 'Sachet', 'أكياس', 'فيتامينات ومعادن لدعم الكبد.', 'Liver support supplements', '15 gm', '-it improves the nutrition state in chronic illness liver disorders malnutrition and general weakness. use: 1 sachet dissolved in 100 ml of cold milk or water or juice twice daily after meals', '', '', 794, '2022-05-22', CURRENT_TIMESTAMP),
(16835, 'Cosentyx 150 mg/ml s.c. 2 prefilled pens', 'كوزينتكس 150 مجم/مل 2 اقلام معبأة للحقن', '9582', '13,360', 'Secukinumab', 'Novartis', 'Pen', 'قلم', 'علاج الصدفية -- علاج الروماتيزم -- بعض الامراض المناعية', 'Il-17a antagonist', '150 mg', 'Secukinumab is indicated the treatment of moderate to severe plaque psoriasis in patients six years and older who are candidates for systemic therapy or phototherapy.[L39600] In Europe, the drug is used in children and adolescents six to 18 years of age for this indication.[L42280]
It is also indicated for the treatment of active psoriatic arthritis (PsA). In the US, it is approved for patients two years of age and older [L39600] while in Europe, it is used alone or in combination with [methotrexate] in patients six years and older whose disease has responded inadequately to, or who cannot tolerate, conventional therapy.[L42280]
Secukinumab is also indicated in the treatment of active enthesitis-related arthritis (ERA). In the US, it is approved for patients four year of age and older.[L39600] In Europe, it is used alone or in combination with [methotrexate] in patients six years and older whose disease has responded inadequately to, or who cannot tolerate, conventional therapy.[L42280]
In the US, secukinumab is indicated for the treatment of adults with active ankylosing spondylitis, non-radiographic axial spondyloarthritis with objective signs of inflammation, moderate to severe hidradenitis suppurativa.[L48771]', '', '', 2934, '2024-05-23', CURRENT_TIMESTAMP),
(16389, 'Ciprofloxiraz 500mg 10 f.c. tab.', 'سيبروفلوكسيراز 500مجم 10 قرص', '', '27', 'Ciprofloxacin', 'Debeiky > nali pharma international', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '500mg', 'Ciprofloxacin is only indicated in infections caused by susceptible bacteria.[L6469,L6472,L6475,L6478,L6481,L6484,L6487,L6490,L6493]
Ciprofloxacin immediate release tablets, oral suspensions, and intravenous injections are indicated for the treatment of skin and skin structure infections, bone and joint infections, complicated intra-abdominal infections, nosocomial pneumonia, febrile neutropenia, adults who have inhaled anthrax, plague, chronic bacterial prostatitis, lower respiratory tract infections including acute exacerbations of chronic bronchitis, urinary tract infections, complicated urinary tract infections in pediatrics, complicated pyelonephritis in pediatrics, and acute sinusitis.[L6481,L6478]
A ciprofloxacin otic solution and otic suspension with hydrocortisone are indicated for acute otitis externa.[L6469,L6484] Ciprofloxacin suspension with dexamethasone is indicated for acute otitis media in pediatric patients with tympanostomy tubes or acute otitis externa.[L6490] A ciprofloxacin intratympanic injection is indicated for pediatric patients with bilateral otitis media with effusion who are having tympanostomy tubes placed or pediatric patients 6 months or older with acute otitis externa.[L6493]
A ciprofloxacin eye drop is indicated for bacterial corneal ulcers and conjunctivitis.[L6472] A ciprofloxacin eye ointment is indicated for bacterial conjunctivitis.[L6475]
A ciprofloxacin extended release tablet is indicated for uncomplicated urinary tract infections, complicated urinary tract infections, and acute uncomplicated pyelonephritis.[L6487]', '6225000287112', '', 1003, '2022-07-08', CURRENT_TIMESTAMP),
(30422, 'Donazepine 28/10 mg 20 caps.', 'دونازيبين 28/10مجم 20 كبسولة', '158', '250', 'Memantine+donepezil', 'Eva pharma', 'Cap', 'كبسولة', 'يستخدم العلاج في بعض حالات الخرف الخفيفة إلى المتوسطة المترافقة مع داء الزهايمر', 'Dopamine d2 agonist + central acetylcholinesterase inhibitor', '10 mg', 'about memantine n-methyl-d-aspartate receptor antagonist dopamine d2 agonist antidementia agent in alzheimer`s disease. mechanism of action of memantine memantine in an uncompetitive (low to moderate affinity to) nmda (n-methyl-d-aspartate) receptor antag', '6224009967353', '', 1672, '2024-04-10', CURRENT_TIMESTAMP),
(25982, 'Rexsol c + e serum 30 ml', 'ريكسول سي+ اها كريم ترطيب 75مل', '', '228', '', 'Rexsol usa > global health', 'Sol', 'محلول', '', 'Skin care', '30 ml', 'this remarkable serum formulated with pure vitamin-c and pure vitamin e. vitamin c stimulates collagen synthesis for a healthier and youthful complexion while vitamin e hydrates the skin for a smoother softer skin texture reducing lines & wrinkles. this r', '', '', 606, '2022-08-04', CURRENT_TIMESTAMP),
(30008, 'Zolguard 500mg 20 tab.', 'زولجارد 500مجم 20 اقراص', '', '9', 'Metronidazole', 'Unipharma co.', 'Tab', 'أقراص', '', 'Antiprotozoal.nitroimidazole', '500mg', 'Metronidazole is indicated for the treatment of confirmed trichomoniasis caused by Trichomonas vaginalis (except for in the first trimester of pregnancy) and the patient''s sexual partners, bacterial vaginosis,[L7432, L49811] certain types of amebiasis, and various anaerobic infections.[A181057, L49811] The above anaerobic infections may occur on the skin and skin structures, the abdomen, the heart, reproductive organs, central nervous system, and the respiratory system. Some may also be present in the bloodstream in cases of septicemia. Common infections treated by metronidazole are Bacteroides species infections, Clostridium infections, and Fusobacterium infections, as well as Peptococcus and Peptostreptococcus infections.[L3754] Topical formulations of metronidazole are indicated for the treatment of inflammatory lesions of rosacea.[L45166]
It is also used off-label in the treatment of Crohn''s disease, as a prophylactic agent after surgery[A181039], and in the treatment of Helicobacter pylori infection.[A181045] It has also been studied in the prevention of preterm births and to treat periodontal disease.[A1391,A181078]', '', '', 888, '2022-07-10', CURRENT_TIMESTAMP),
(23203, 'Myorelax 10 caps.', 'ميوريلاكس 10 كبسولات', '', '5', 'Carisoprodol+paracetamol(acetaminophen)', 'Amoun', 'Cap', 'كبسولة', 'باسط للعضلات.', 'Muscle relaxant', '', '', '6221025009432', '', 1428, '2022-12-06', CURRENT_TIMESTAMP),
(4666, 'Levnoseiz 1000 mg 30 tabs', 'ليفنوسيز 1000مجم 30 قرص', '', '150', 'Levetiracetam', 'Gypto pharma for pharmaceutical', 'Tab', 'أقراص', '', '', '1000 mg', 'Levetiracetam is indicated as an adjunctive therapy in the treatment of partial onset seizures in epileptic patients who are one month of age and older. Additionally, it is indicated as an adjunct in the treatment of myoclonic seizures in patients with juvenile myoclonic epilepsy who are 12 years of age and older, and in primary generalized tonic-clonic seizures in patients with idiopathic generalized epilepsy who are 6 years of age and older.[L8606]
Levetiracetam is also available as an orally dissolvable tablet that is indicated as an adjunct in the treatment of partial onset seizures in patients with epilepsy who are 4 years of age and older and weigh more than 20kg.[L8609]', '6224008874416', '', 1100, '2023-05-01', CURRENT_TIMESTAMP),
(7394, 'Efucisan 1% viscous eye drops 5 gm', 'ايفيوسيزان قطرة عين 5 جم', '', '28', 'Fusidic acid', 'Orchidia pharmaceutical industries', 'Drops', 'نقط', '', 'Antibiotic', '1%', 'For the treatment of bacterial infections.', '6223005444998', '', 1088, '2025-09-16', CURRENT_TIMESTAMP),
(14256, 'Antodine 20mg 30 f.c.tab', 'انتودين 20مجم 30 قرص', '36', '60', 'Famotidine', 'Amoun', 'Tab', 'أقراص', '', 'Peptic ulcer.anti-histamine.h2 antagonist', '20mg', 'Famotidine is indicated in pediatric and adult patients (with the bodyweight of 40 kg and above) for the management of active duodenal ulcer (DU), active gastric ulcer, symptomatic non-erosive gastroesophageal reflux disease (GERD), and erosive esophagitis due to GERD, diagnosed by biopsy.[L11139]
It is also indicated in adult patients for the treatment of pathological hypersecretory conditions (e.g., Zollinger-Ellison Syndrome, multiple endocrine neoplasias) and reduction of the risk of DU recurrence.[L11139]
The intravenous formulation of famotidine is available for some hospitalized patients with pathological hypersecretory conditions or intractable ulcers or as an alternative to the oral dosage form for short-term use in patients who are unable to take oral medication.[L11142]
Over-the-counter famotidine is used for the management and prevention of heartburn caused by gastroesophageal reflux in children and adults. Off-label uses of famotidine include the reduction of NSAIDs-associated gastrointestinal effects, treatment of refractory urticarial, prevention of stress ulcer in critically-ill patients, and symptomatic relief of gastritis.[L11166,L11172]', '6221025024176', '', 7261, '2024-07-15', CURRENT_TIMESTAMP),
(13646, 'Physiomer baby hypertonic nasal spray 60ml', 'فيزيومير بيبي هايبرتونيك بخاخ للانف 60 مل', '', '185', 'Hypertonic seawater', 'Laboratoire de la mer > star international company', 'Spray', 'بخاخ', 'بخاخ للانف في حالات المخاط --يساعد علي تحسين التنفس -- يساعد علي التخلص من المخاط --', 'Nasal decongestant', '60ml', '*clears your toddler s nasal passages and helps restore breathing as well as comfort and wellbeing during sleeping and feeding. *in daily use: it cleanses humidifies and eliminates excess mucus - clears dust allergens pollutants and pathogens (viruses and', '', '', 1207, '2023-07-06', CURRENT_TIMESTAMP),
(9221, 'Omepak 20 mg 14 caps.', 'اوميباك 20مجم 14 كبسولة', '33', '50', 'Omeprazole', 'Sedico', 'Cap', 'كبسولة', 'حموضة وقرحة معدة', 'Ppi.antacid.peptic ulcer', '20 mg', 'Omeprazole, according to the FDA label [FDA label] is a proton pump inhibitor (PPI) used for the following purposes:
• Treatment of active duodenal ulcer in adults 
• Eradication of Helicobacter pylori to reduce the risk of duodenal ulcer
recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6221042168075', '', 2554, '2024-09-26', CURRENT_TIMESTAMP),
(3041, 'Coral calcium 1000 mg cap 20', 'كورال كالسيوم 1000مجم 20 كبسولة', '', '30', 'Calcium+vitamin c+vitamin d', 'Company', 'Cap', 'كبسولة', '', 'Calcium', '1000 mg', '', '', '', 923, '2022-08-17', CURRENT_TIMESTAMP),
(12242, 'Aaa', 'ششش', '', '44', '', '', 'Unknown', 'غير محدد', 'لعلاج الدوار والدوخة وطنين الأذن', '', '', '', '', '', 675, '2022-09-17', CURRENT_TIMESTAMP),
(15442, 'Borgastatin 10mg 10 tab.', 'بورجاستاتين 10 مجم 10 قرص', '21.6', '30', 'Atorvastatin', 'Borg', 'Tab', 'أقراص', 'علاج ارتفاع الدهون والكوليسترول الضار بالدم', 'Antihyperlipidemic.statins', '10mg', 'Atorvastatin is indicated for the treatment of several types of dyslipidemias, including primary hyperlipidemia and mixed dyslipidemia in adults, hypertriglyceridemia, primary dysbetalipoproteinemia, homozygous familial hypercholesterolemia, and heterozygous familial hypercholesterolemia in adolescent patients with failed dietary modifications.[A177397]
Dyslipidemia describes an elevation of plasma cholesterol, triglycerides or both as well as to the presence of low levels of high-density lipoprotein. This condition represents an increased risk for the development of atherosclerosis.[L6025] 
Atorvastatin is indicated, in combination with dietary modifications, to prevent cardiovascular events in patients with cardiac risk factors and/or abnormal lipid profiles.[A177397]
Atorvastatin can be used as a preventive agent for myocardial infarction, stroke, revascularization, and angina, in patients without coronary heart disease but with multiple risk factors and in patients with type 2 diabetes without coronary heart disease but multiple risk factors.[A177397]
Atorvastatin may be used as a preventive agent for non-fatal myocardial infarction, fatal and non-fatal stroke, revascularization procedures, hospitalization for congestive heart failure and angina in patients with coronary heart disease.[A177397]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '', '', 3639, '2024-11-03', CURRENT_TIMESTAMP),
(15845, 'Cardioguard m 40 mg sr 10 caps.', 'كارديو جارد ام 40 مجم 10 كبسولات', '', '10', 'Isosorbide-5-mononitrate', 'Amoun', 'Cap', 'كبسولة', '', 'Antianginal', '40 mg', 'about isosorbide-5-mononitrate alkyl nitrate derivative a direct vasodilator antianginal. mechanism of action of isosorbide-5-mononitrate it is a direct smooth muscle relaxant which have a prominent action vascular smooth muscles preferentially veins than', '', '', 764, '2022-07-30', CURRENT_TIMESTAMP),
(30963, 'Mvasi 400 mg/16ml vial', 'مفاسي 400مجم16مل فيال', '12590', '17,081', 'Bevacizumab', 'Amgen > amgen scientific office', 'Vial', 'فيال', '', 'Antineoplastic', '400 mg', 'As a vascular endothelial growth factor (VEGF) inhibitor, bevacizumab is used in several chemotherapy regimens to treat metastatic colorectal cancer; metastatic, unresectable, locally advanced or recurrent non-squamous non-small cell lung cancer; metastatic renal cell carcinoma; metastatic, persistent, or recurrent cervical cancer; primary peritoneal cancer; epithelial ovarian cancer; fallopian tube cancer; breast cancer; and recurrent glioblastoma.[L12648,L39233,L41514,L43130,L43302,L49826]
