(14988, 'Beesline beeswax ointment fragrance-free 60 ml', 'بيزلين مرهم شمع العسل خالي من العطر 60 مل', '', '195', '', 'Beesline > pharma cruise medical', 'Ointment', 'مرهم', '', 'Skin care', '60 ml', 'active ingredients sweet almond oil beeswax wheat germ oil candelilla wax carrot sunflower oil & nigella seed oil. an all-natural multi-purpose & potent ointment that provides super nourishing & intense healing effects for cracked chapped & dry skin. even', '', '', 705, '2022-07-15', CURRENT_TIMESTAMP),
(20863, 'Insulin h bio nph 100i.u.vial', 'انسولين اتش بيو ان بي اتش 100 وحدة فيال', '38', '77', 'Insulin isophane protamine human', 'Sedico', 'Vial', 'فيال', '', 'Anti-diabetic.insulin analouge', '', 'Human insulin is indicated to improve glycemic control in adults and pediatric patients with diabetes mellitus.', '6221042441062', '', 1252, '2024-11-17', CURRENT_TIMESTAMP),
(4982, 'Tofaxa 5 mg 60 f.c.tabs.', 'توفاكسا 5 مجم 60 قرص', '', '4,085', 'Tofacitinib', 'Hikma specialized pharmaceuticals', 'Tab', 'أقراص', '', 'Anti rheumatic', '5 mg', 'Tofacitinib is indicated for the treatment of adult patients with moderately-to-severely active rheumatoid arthritis (RA), active psoriatic arthritis, active ankylosing spondylitis, or moderately-to-severely active ulcerative colitis who have had an inadequate response or intolerance to one or more TNF blockers.[L30395] It is also indicated as an oral solution in patients ≥2 years of age for the treatment of polyarticular course juvenile idiopathic arthritis who have had an inadequate response or intolerance to one or more TNF blockers.[L30395]
Tofacitinib is not recommended to be used in combination with other biologic disease-modifying anti-rheumatic drugs (DMARDs) or potent immunosuppressive agents such as azathioprine or cyclosporine.[L30395]', '', '', 1079, '2025-06-22', CURRENT_TIMESTAMP),
(31780, 'Liviacool massage gel 59 gm', 'ليفياكول مساج جل 59 جم', '59', '120', 'Menthol', 'Multi-apex', 'Gel', 'جل', 'كريم مساج لتخفيف الالام وازالة التوتر العضلى وتهدئة الاعصاب', 'Massage cream', '59 gm', '', '6223003206710', '', 5105, '2024-04-12', CURRENT_TIMESTAMP),
(18006, 'Easyron 30 tablets', 'ايزيرون 30 قرص', '95', '105', 'Natural iron+zinc+copper+vit-c+vit-d3+beta carotene +vit b-complex', 'Organic pharma > shefaa egypt pharma', 'Tablet', 'أقراص', 'فيتامينات ومعادن للجسم', 'Multivitamins', '', 'small pills fortified with natural iron multivitamins and minerals for anemia and increasing immunity', '6225000445512', '', 2987, '2025-08-11', CURRENT_TIMESTAMP),
(14175, 'Spinobac 5mg/5ml syrup 300ml', 'سبينوباك 5مجم/5مل شراب 300 مل', '53.5', '73', 'Baclofen', 'Saja pharmaceuticals > clavita pharma', 'Syrup', 'شراب', '', 'Cns.analgesic.skeletal muscle relaxant', '5mg', 'Oral baclofen is indicated for the treatment of spasticity resulting from multiple sclerosis and is particularly useful for the relief of flexor spasms and concomitant pain, clonus, and muscular rigidity. It may also be used to treat patients with spinal cord injuries and other spinal cord diseases. Baclofen should not be used to treat skeletal muscle spasms resulting from rheumatic disorders.[L39434]
Intrathecal baclofen is also indicated for the management of severe spasticity of the cerebral or spinal original in patients 4 years of age and older. It is reserved for patients unresponsive to oral baclofen therapy, or those who experience intolerable central nervous system side effects at effective doses. For use in spasticity due to traumatic brain injury, baclofen should be considered after at least one year of injury.[L39429]', '', '', 891, '2024-11-27', CURRENT_TIMESTAMP),
(18443, 'Epiquantel 600mg 4 f.c. tabs.', 'ابيكوانتيل 600 مجم 4 اقراص', '16.5', '32', 'Praziquantel', 'Eipico', 'Tab', 'أقراص', '', 'Anthelmintic', '600mg', 'Praziquantel is indicated in patients aged 1 year and older for the treatment of the schistosomiasis due to all species of Schistosoma (for example, Schistosoma mekongi, Schistosoma japonicum, Schistosoma mansoni and Schistosoma hematobium) and clonorchiasis and opisthorchiasis due to the liver flukes, Clonorchis sinensis/Opisthorchis viverrini (approval of this indication was based on studies in which the two species were not differentiated).[L50021]', '6221032115683', '', 1799, '2025-04-24', CURRENT_TIMESTAMP),
(7528, 'Well femme nipple care cream 50 gm', 'ويل فيم كريم العناية لتشققات الحلمة 50 جم', '', '120', 'Allantoin+tea tree oil+aloe vera extract+menthol+chamomile+thymus vulgaris', 'Smartec > wellness pharma', 'Cream', 'كريم', '', 'Moisturizing', '50 gm', '', '', '', 1199, '2022-10-24', CURRENT_TIMESTAMP),
(20621, 'Hydrozide 25 mg 30 scored tab.', 'هيدروزيد 25 مجم 30 قرص', '', '8', 'Hydrochlorothiazide', 'Epci', 'Tab', 'أقراص', '', 'Diuretic.thiazide derivatibve', '25 mg', 'Hydrochlorothiazide is indicated alone or in combination for the management of edema associated with congestive heart failure, hepatic cirrhosis, nephrotic syndrome, acute glomerulonephritis, chronic renal failure, and corticosteroid and estrogen therapy.[L8447,L8450] Hydrochlorothiazide is also indicated alone or in combination for the management of hypertension.[A185138,L8447,L8450,L45663]', '', '', 908, '2022-07-29', CURRENT_TIMESTAMP),
(13557, 'Adwivalsar-co 160/12.5mg 10 scored f.c.tab.', 'ادويفالسار -كو 160/12.5مجم 10 قرص', '', '25', 'Hydrochlorothiazide+valsartan', 'Adwia', 'Tab', 'أقراص', 'مدر للبول ويستخدم فى علاج ضغط الدم المرتفع', 'Antihypertensive. combined angiotensin blocker with diuretic', '12.5mg', 'about hydrochlorothiazide thiazide derivatibve diuretic. mechanism of action of hydrochlorothiazide it is thiazide diuretic which exerts its action by acting at site-3(central dilating segment of early distal tubule). it binds to na+cl- symporter and inhi', '', '', 2011, '2022-07-07', CURRENT_TIMESTAMP),
(18030, 'Eccotriol topical oint. 15 gm', 'ايكوتريول مرهم 15 جرام', '', '19', 'Betamethasone+calcipotriol(calcipotriene)', 'Marcyrl co. > ecco pharm-egypt', 'Oint', 'مرهم', 'يعمل على الحد من التورم، والاحمرار، والحكة التي تصاحب عدوى الجلد، ,يساعد على مقاومة الألم والالتهاب', 'Psoriasis', '15 gm', 'uses: this medication is used to treat psoriasis. it helps to reduce the redness thickening and scaling of the skin that occurs with this condition. healthy skin lowers your risk for infection and protects you against the environment. this product contain', '6223003571849', '', 1560, '2022-06-28', CURRENT_TIMESTAMP),
(8317, 'Montelair 4 mg 28 oral granules in sachets', 'مونتيلاير 4مجم 28 كيس', '', '97', 'Montelukast', 'Jedco int. co. for pharmaceuticals', 'Sachet', 'أكياس', 'التهاب الأنف التحسسي — العلاج المزمن للربو (الحساسية الصدرية – الأزمة) — الوقاية من تشنج وضيق الشعب الهوائية', 'Asthma.anti-inflammatory.leukotriene antagonist', '4 mg', 'Montelukast is indicated for:
(a) the prophylaxis and chronic treatment of asthma in adults and pediatric patients who are 12 months of age and older[L6301], although other regional health authorities specifically note this indication for adults and adolescents who are 15 years and older[L6304,L6307] and also include indications for preventing day and night-time symptoms, and the treatment of acetylsalicylic acid-sensitive asthma[L6304];
(b) the prevention of exercise-induced bronchoconstriction (EIB) in patients who are 6 years of age and older[L6301], although other regional health authorities specifically note this indication for adults and adolescents who are 15 years and older[L6304,L6307]; and
(c) the relief of symptoms of seasonal allergic rhinitis in patients 2 years of age and older and perennial allergic rhinitis in patients 6 months of age and older[L6301], although other regional health authorities specifically note the relief of seasonal allergic rhinitis symptoms for adults and adolescents who are 15 years and older[L6304,L6307].
Furthermore, some formulations like chewable montelukast tablets may also be specifically indicated by particular regulatory bodies for the prophylaxis and chronic treatment of asthma, including the prevention of day and night-time symptoms, the treatment of acetylsalicylic acid based asthma, and the prevention of exercise-induced bronchoconstriction in adult and pediatric patients aged 2 and older[L6328], between the ages 2 and 5[L6325], or between the ages of 6 and 14 years.[L6331]
Moreover, when employed for such indications montelukast is considered effective as monotherapy or when combined with other medications indicated for the maintenance treatment of chronic asthma.[L6304,L6328] For instance, montelukast and inhaled corticosteroids can be used concomitantly to demonstrate additive effects to control asthma or to decrease the necessary inhaled corticosteroid dose while still maintaining clinical stability.[L6304,L6328]
Additionally, in patients who continue to experience asthma symptoms, montelukast can also be combined with an ''as required'' short-acting beta-agonist, an inhaled corticosteroid, or inhaled corticosteroid paired with a long-acting beta-agonist.[L6304,L6328]', '', '', 1167, '2022-06-02', CURRENT_TIMESTAMP),
(2350, 'Advoxin 400 mg 5 f.c. tabs.', 'ادفوكسين 400مجم 5 اقراص', '', '68', 'Moxifloxacin', 'Egpi', 'Tab', 'أقراص', 'مضاد حيوى واسع المدى يستخدم فى علاج التهابات الجهاز التنفسي والجهاز الهضمى او الالتهابات الجلدية', 'Antibiotic.quinolone', '400 mg', 'For the treatment of sinus and lung infections such as sinusitis, pneumonia, and secondary infections in chronic bronchitis. Also for the treatment of bacterial conjunctivitis (pinkeye).', '', '', 3375, '2023-06-25', CURRENT_TIMESTAMP),
(33406, 'Phesgo 600mg/600mg/20.000 units s.c. sol. for inj. 10 ml', 'فيسجو 600مجم/600مجم/20.000وحدة 10 مل', '80000', '104,714', 'Pertuzumab + trastuzumab + hyaluronidase', 'Roche', 'Inj', 'حقن', '', 'Antineoplastic', '600mg', 'Pertuzumab is indicated for intravenous administration in combination with [trastuzumab] and [docetaxel] for the treatment of patients with HER2-positive metastatic breast cancer who have not received prior anti-HER2 therapy or chemotherapy for metastatic disease.[L14747] It is also indicated in combination with trastuzumab and other chemotherapies for the neoadjuvant treatment of HER2-positive locally advanced, inflammatory, or early-stage breast cancer as part of a complete treatment regimen[L14747] and as adjuvant treatment in patients with HER2-positive early-stage breast cancer at high risk of recurrence.[L14747]
Pertuzumab is also indicated for subcutaneous injection - in combination with trastuzumab and [hyaluronidase] - in the treatment of HER2-positive breast cancers in adults.[L14510]', '', '', 2048, '2024-11-06', CURRENT_TIMESTAMP),
(14372, 'Ardiolazin 50mg 30 f.c. tabs.', 'ارديولازين 50مجم 30 قرص', '', '21', 'Hydralazine', 'Pharma cure pharmaceuticals', 'Tab', 'أقراص', '', 'Antihypertensive', '50mg', 'Hydralazine is indicated alone or adjunct to standard therapy to treat essential hypertension.[L8782] A combination product with isosorbide dinitrate is indicated as an adjunct therapy in the treatment of heart failure.[L8785]', '', '', 523, '2022-09-21', CURRENT_TIMESTAMP),
(30162, 'Ascorbic acid oral drops 15 ml', 'اسكوربيك اسيد نقط بالفم 15 مل', '35', '45', 'Vitamin c', '> atlas pharmaceutical', 'Drops', 'نقط', '', 'Vitamin c', '15 ml', 'For the treatment of vitamin A deficiency.', '', '', 1265, '2025-12-09', CURRENT_TIMESTAMP),
(24908, 'Photoderm max ultra-fluid dark tinted spf 50+ - 40ml', 'فوتوديرم ماكس الترا فلويد دارك 40مل', '', '289', 'Sun protection formula', 'Bioderma dermatological laboratories > biotech egypt', 'Unknown', 'غير محدد', '', 'Sun block', '40ml', 'indication: sun-intolerant or sensitive skin very fair skin with freckles skin subject to extreme sunshine (high mountains tropics etc.) suitable for all skin types even combination to oily *for adults & on face only. instructions for use several times a', '', '', 783, '2022-07-20', CURRENT_TIMESTAMP),
(14020, 'Amoxil fort 250mg/5ml susp. 100ml', 'اموكسيل فورت 250 مجم / 5 مل معلق 100 مل', '', '11', 'Amoxicillin', 'Mup > smithkline beecham', 'Susp', 'معلق', '', 'Penicillins.monocomponent', '250mg', 'Amoxicillin alone is indicated to treat susceptible bacterial infections of the ear, nose, throat, genitourinary tract, skin, skin structure, and lower respiratory tract.[L11656,L11659] Amoxicillin is given with calvulanic acid to treat acute bacterial sinusitis, community acquired pneumonia, lower respiratory tract infections, acute bacterial otitis media, skin and skin structure infections, and urinary tract infections.[L11650,L7880,L11653] Amoxicillin is given with omeprazole in the treatment of _Helicobacter pylori_ (_H. pylori_) infection.[L9743,L11647]
Amoxicillin is used in combination with [vonoprazan] and [clarithromycin] as co-packaged triple therapy or in combination with [vonoprazan] as co-packaged dual therapy to treat _H. pylori_ infection in adults.[L41695]', '6221045010920', '', 1127, '2022-12-01', CURRENT_TIMESTAMP),
(22478, 'Aaa', 'ششش', '', '53', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 755, '2022-09-26', CURRENT_TIMESTAMP),
(7387, 'Marvy d 30 tab', 'مارفي دي 30 قرص', '', '120', '', 'Marvel', 'Tab', 'أقراص', '', '', '', '', '', '', 899, '2022-08-18', CURRENT_TIMESTAMP),
(1745, 'Bronchopro 15mg/5ml syrup 100ml', 'برونكوبرو 100مل شراب', '23.5', '35', 'Ambroxol', 'October pharma', 'Syrup', 'شراب', '', 'Mucolytic', '15mg', 'Ambroxol is indicated for secretolytic therapy in bronchoplmonary disease with abnormal mucus secretion and transport. It allows the mucus to be more easily cleared and ease a patient''s breathing.', '6221028030334', '', 3440, '2024-09-07', CURRENT_TIMESTAMP),
(16298, 'Cicabio cream 40ml', 'سيكابيو كريم 40 مل', '245', '599', '', 'Bioderma dermatological laboratories > biotech egypt', 'Cream', 'كريم', '', 'Healing topical', '40ml', 'the first repair care for damaged irritated non-oozing skin that accompanies every stage of epidermal reconstruction. ï¿½ cicabio crï¿½me targets every stage of skin reconstruction to promote perfectly restored skin. ï¿½ the synergetic combination of resv', '6224008838302', '', 1031, '2023-09-05', CURRENT_TIMESTAMP),
(26537, 'Sansovit syrup 600gm', 'سانسوفيت شراب 600 جرام', '', '56', 'Vitamins', 'Marcyrl co. > aug pharma', 'Syrup', 'شراب', '', 'Vitamins', '600gm', 'composition for 10 ml : vitamin a .. 2400 i.u. vitamin d3 .. 200 i.u. vitamin b1 .. 2 mg vitamin b2 .. 2 mg vitamin b6 .. 1 mg vitamin c .. 100 mg vitamin e .. 2 mg nicotinamide .. 10 mg dexpanthenol .. 4 mg', '', '', 938, '2022-06-17', CURRENT_TIMESTAMP),
(25116, 'Poxclin coolmouse topical lotion 100 ml', 'بوكسسلين كولماوس لوشن 100مل', '', '165', '', 'Youmedical b.v. > al ansar for marketing', 'Lotion', 'لوشن', '', 'Chicken pox', '100 ml', 'poxclin coolmousse - relieves the itch and helps prevent scars! poxclin coolmousse contains a unique bioactive bacterial blocker for an effective treatment to sooth the itch to recondition the skin and to help prevent scar tissue formation. poxclin coolmo', '8718053572789', '', 841, '2022-08-05', CURRENT_TIMESTAMP),
(28174, 'Turmeric & ginger box 30 capsule in', 'ترميريك وجينجر علبة 30 كبسولة', '155', '189', 'Turmeric extract + ginger powder', 'Eureka pharma llc', 'Capsule', 'كبسولة', '', 'Turmeric extract + ginger powder', '', '', '', '', 774, '2025-08-21', CURRENT_TIMESTAMP),
(2974, 'Concor plus 10/25mg 30 f.c. tablets', 'كونكور بلس 10/25مجم 30 قرص', '79.5', '108', 'Bisoprolol fumarate+hydrochlorothiazide', 'Amoun > merck kgaa f.r.germany', 'Tablet', 'أقراص', 'علاج ارتفاع ضغط الدم', 'Antihypertensive.combined beta blocker with diuretic', '25mg', 'Bisoprolol is indicated for the treatment of mild to moderate hypertension.[L7219] It may be used off-label to treat heart failure, atrial fibrillation, and angina pectoris.[A180460,A180463]', '6221025032379', '', 7207, '2024-07-14', CURRENT_TIMESTAMP),
(30726, 'Ivy potex syrup 100 ml', 'ايفي بوتكس شراب 100 مل', '40', '50', 'Ivy leave extract', 'Organix > potexpharma', 'Syrup', 'شراب', 'مكمل غذائى مضاد للسعال وداعم للجهاز التنفسى', 'Cough products', '100 ml', 'due to their broncholytic and secretolic properties ivy leaf dried extract has long provided its worth in practice. their efficacy has been demonstrated in numerous scientific studies. according to a pharmacological investigation its constituent appears t', '6225000488519', '', 1800, '2024-11-26', CURRENT_TIMESTAMP),
(11590, 'Travatan 0.004% eye drops 2.5 ml', 'ترافاتان 0.004% قطرة عين 2.5 مل', '130', '171', 'Travoprost', 'Alcon > novartis scientific office', 'Drops', 'نقط', '', 'Antiglaucoma', '0.004%', 'Travoprost is indicated for the reduction of elevated intraocular pressure in patients with open-angle glaucoma or ocular hypertension.[L49434, L49429, L49515] It is also used in pediatric patients aged two months to less than 18 years.[L5146]', '7612797423301', '', 2165, '2025-03-11', CURRENT_TIMESTAMP),
(22665, 'Metograine 20 tab', 'ميتوجرين 20 قرص', '', '8', 'Caffeine+ergotamine+metoclopramide+paracetamol(acetaminophen)', 'Eva pharma', 'Tab', 'أقراص', 'لعلاج حالات الصداع النصفي', 'Antimigraine', '', '', '6223002450428', '', 2112, '2022-12-06', CURRENT_TIMESTAMP),
(18878, 'Aaa', 'ششش', '', '137', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 750, '2022-12-05', CURRENT_TIMESTAMP),
(14876, 'Bactiflox 250mg 10 lactab.', 'باكتيفلوكس 250 مجم 10 اقراص', '', '20', 'Ciprofloxacin', 'Mup > acino', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '250mg', 'Ciprofloxacin is only indicated in infections caused by susceptible bacteria.[L6469,L6472,L6475,L6478,L6481,L6484,L6487,L6490,L6493]
Ciprofloxacin immediate release tablets, oral suspensions, and intravenous injections are indicated for the treatment of skin and skin structure infections, bone and joint infections, complicated intra-abdominal infections, nosocomial pneumonia, febrile neutropenia, adults who have inhaled anthrax, plague, chronic bacterial prostatitis, lower respiratory tract infections including acute exacerbations of chronic bronchitis, urinary tract infections, complicated urinary tract infections in pediatrics, complicated pyelonephritis in pediatrics, and acute sinusitis.[L6481,L6478]
A ciprofloxacin otic solution and otic suspension with hydrocortisone are indicated for acute otitis externa.[L6469,L6484] Ciprofloxacin suspension with dexamethasone is indicated for acute otitis media in pediatric patients with tympanostomy tubes or acute otitis externa.[L6490] A ciprofloxacin intratympanic injection is indicated for pediatric patients with bilateral otitis media with effusion who are having tympanostomy tubes placed or pediatric patients 6 months or older with acute otitis externa.[L6493]
A ciprofloxacin eye drop is indicated for bacterial corneal ulcers and conjunctivitis.[L6472] A ciprofloxacin eye ointment is indicated for bacterial conjunctivitis.[L6475]
A ciprofloxacin extended release tablet is indicated for uncomplicated urinary tract infections, complicated urinary tract infections, and acute uncomplicated pyelonephritis.[L6487]', '', '', 745, '2022-09-18', CURRENT_TIMESTAMP),
(7678, 'Magnabiotic 1 gm 10 f.c. tabs.', 'ماجنابيوتك 1جم 10 اقراص', '', '47', 'Amoxicillin+clavulanic acid', 'Sedico', 'Tab', 'أقراص', 'مضاد حيوي', 'Penicillins.penicillin with b-lactamase inhibitor', '1 gm', '', '6221042118018', '', 4656, '2022-12-06', CURRENT_TIMESTAMP),
(28907, 'Vagiclind 2% vaginal cream 40 gm', 'فاجيكليند 2% كريم مهبلي 40 جم', '58.5', '86', 'Clindamycin', 'Saja pharmaceuticals', 'Cream', 'كريم', '', 'Antibiotic.lincomycins', '2%', 'In oral and parenteral formulations, clindamycin is indicated for the treatment of serious infections caused by susceptible anaerobic bacteria, as well as susceptible staphylococci, streptococci, and pneumococci.[L11599,L11602] Used topically, it is indicated for the treatment of acne vulgaris[L11593,L11611,L11605] and is available in combination with [benzoyl peroxide][L11584] or [tretinoin][L11590] for this purpose, or as a triple combination therapy with benzoyl peroxide and [adapalene].[L48666] Clindamycin is also indicated as a vaginal cream[L11596], suppository[L11608], or gel[L39416] for the treatment of bacterial vaginosis in non-pregnant females.
Clindamycin is used for antimicrobial prophylaxis against _Viridans_ group streptococcal infections in susceptible patients undergoing oral, dental, or upper respiratory surgery, and may be used for prophylaxis against bacterial endocarditis in penicillin-allergic patients at high risk of these infections.[L11629]', '6221126002219', '', 1043, '2024-12-09', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(18905, 'Feloblock 10 mg 20 sr f.c. tabs.', 'فيلوبلوك 10 مجم اس ار 20 قرص', '', '35', 'Felodipine', 'Mepaco', 'Tab', 'أقراص', '', 'Antihypertensive.selective calcium channel blocker', '10 mg', 'For the treatment of mild to moderate essential hypertension.', '', '', 887, '2022-07-21', CURRENT_TIMESTAMP),
