(14146, 'Andriol 40mg 20 caps', 'اندريول 40مجم 20 كبسولة', '', '40', 'Testosterone', 'Sedico > schering plough', 'Cap', 'كبسولة', 'هرمون التيستوستيرون.', 'Androgen', '40mg', 'Testosterone is indicated to treat primary hypogonadism and hypogonadotropic hypogonadism.[L8983,L8935,L8938,L8986,L8989,L8992,L8995]', '6221042193022', '', 4866, '2023-02-05', CURRENT_TIMESTAMP),
(5832, 'Withstand cream 60 gm', 'ويزستاند كريم 60 جم', '', '70', '', 'Biocell', 'Cream', 'كريم', '', 'Acne', '60 gm', '', '', '', 1092, '2025-07-11', CURRENT_TIMESTAMP),
(16486, 'Clearalique 2% cream 30 gm', 'كليراليك 2% كريم 30 جم', '', '6', 'Hydroquinone', 'Delta pharma', 'Cream', 'كريم', '', 'Whitening topical', '2%', 'Hydroquinone is used as an OTC topical lightening agent for disorders of hyperpigmentation including melasma, post-inflammatory hyperpigmention, sunspots and freckles.', '', '', 923, '2022-07-13', CURRENT_TIMESTAMP),
(23762, 'Nouvelle firming anti-cellulite cream 120 ml', 'نوفيل فيرمينج للسيلولايت كريم 120 مل', '', '50', 'Tripeptide-1+caffeine+carnitine+glycyl glycine+glycerin+triethanolamine+paraffin oil+cetyl alcohol', 'Hi-care > smart marketing', 'Cream', 'كريم', 'حالات الاسترتش ماركس.', 'Firming topical', '120 ml', '', '', '', 2125, '2022-12-19', CURRENT_TIMESTAMP),
(2413, 'Lungocort 1mg/2ml 20 ampoule', 'لنجوكورت 1مجم/2مل 20 امبول', '364', '408', 'Budesonide', 'Eva pharma', 'Ampoule', 'أمبول', '', 'Bronchodilator.anti-inflammatory.glucocorticoid steroid', '1mg', 'Budesonide extended-release capsules are indicated for the treatment and maintenance of mild to moderate Crohn’s disease.[L10601,L10604] Various inhaled budesonide products are indicated for prophylactic therapy in asthma [L10607,L10613,L10619] and to reduce exacerbations of COPD.[L10619] A budesonide nasal spray is available over the counter for symptoms of hay fever and upper respiratory allergies.[L10616] Extended-release capsules are indicated to induce remission of mild to moderate ulcerative colitis[L10622] and a rectal foam is used for mild to moderate distal ulcerative colitis.[L10625] In addition, a delayed-release capsule formulation of budesonide is indicated to reduce proteinuria in adults with IgA nephropathy at risk of rapid disease progression.[L42515,L49540] Budesonide is indicated to treat eosinophilic esophagitis (EoE): For this indication, it is only approved for use in adults in Europe [L42525] while it is approved for short-term use (12 weeks) in patients 11 years of age and older in the US.[L50161]', '6223007357906', '', 987, '2025-10-13', CURRENT_TIMESTAMP),
(30354, 'Coronit 40mg 20 lentocaps.', 'كورونيت 40مجم 20 كبسولة', '', '10', 'Isosorbide dinitrate', 'Alexandria', 'Cap', 'كبسولة', '', 'Anti-ischemic', '40mg', 'For the prevention of angina pectoris due to coronary artery disease.', '6223000170403', '', 674, '2022-12-04', CURRENT_TIMESTAMP),
(17904, 'Drakon intimate feminine wash 200 ml', 'دراكون غسول للعناية بالسيدات 200 مل', '180', '299', 'Liquorice+arbutin+kojic acid+vitamin c+melon extract+panthenol+almond oil', 'Xfactor medical > pharma cruise medical', 'Unknown', 'غير محدد', '', '', '200 ml', 'indications 1.fights bad odour and provides intense freshness. 2.protect against infections. 3.lightens & rejuvenates embarrassing intimate dark areas. how to apply add a small quantity of drakon intimate feminine wash on the intimate zone massage the ski', '', '', 743, '2025-08-11', CURRENT_TIMESTAMP),
(11719, 'Trittico 50 mg 20 tabs.', 'تريتيكو 50مجم 20 قرص', '26', '38', 'Trazodone', 'Eipico > angliny', 'Tab', 'أقراص', 'علاج الامراض النفسية -- مضاد للاكتئاب -- يحسن الحالة المزاجية -- يؤخذ تحت اشراف طبي', 'Psychiatric.antidepressants', '50 mg', 'Trazodone is indicated for the treatment of major depressive disorder (MDD).[L3484] It has been used off-label for adjunct therapy in alcohol dependence, and off-label to treat anxiety and insomnia.[L3484] It may also be used off-label to treat symptoms of dementia, Alzheimer’s disease, schizophrenia, eating disorders, and fibromyalgia due to its effects on various neurotransmitter receptors.[A31634]', '6221032115232', '', 5032, '2025-08-25', CURRENT_TIMESTAMP),
(1863, 'Calcid b12 syrup 120 ml', 'كالسيد ب12 120 مل شراب', '', '14', 'Calcium-vitamin b12-vitamin d', 'Sigma', 'Syrup', 'شراب', '', 'Calcium supplement', '120 ml', '', '6221051040010', '', 1155, '2022-12-03', CURRENT_TIMESTAMP),
(25372, 'Proscar 5mg 28 f.c. tab', 'بروسكار 5مجم 28 قرص', '157', '234', 'Finasteride', 'Merck sharp & dohme > merck sharp & dohme scientific office', 'Tab', 'أقراص', '', '5 alpha-reductase inhibitor', '5mg', 'Finasteride is indicated for the treatment of symptomatic benign prostatic hyperplasia (BPH) in men with an enlarged prostate to improve symptoms, reduce the risk of acute urinary retention, and reduce the risk of the need for surgery including transurethral resection of the prostate (TURP) and prostatectomy.[L10565] A combination product with [tadalafil] is also used for the symptomatic treatment of BPH for up to 26 weeks.[L39439]
Finasteride is also indicated for the treatment of male pattern hair loss (androgenetic alopecia, hereditary alopecia, or common male baldness) in male patients.[L6235]', '00366582510000', '', 5297, '2024-05-24', CURRENT_TIMESTAMP),
(3183, 'Curazole-h shampoo 60 ml', 'كيورازول شامبو 60مل', '', '14', 'Chlorhexidine+ketoconazole', 'Eva pharma', 'Amp', 'أمبول', '', 'Anti-dandruff', '60 ml', '', '', '', 1590, '2022-09-23', CURRENT_TIMESTAMP),
(27769, 'Medipha ivy 100ml syrup', 'ميديفا ايفي شراب 100 مل', '', '50', 'Ivy leaves', 'Medipha pharma', 'Syrup', 'شراب', '', 'Couch products', '100ml', '', '6225000640658', '', 1042, '2024-06-12', CURRENT_TIMESTAMP),
(26972, 'Silkren hair cream gel 120 ml', 'سيكرين كريم جل 120مل', '', '85', 'Zinc pyrithione+coconut oil+salicylic acid+sulphur+lanolin+vitamin d', 'Hi-care > pixel pharmaceutical company', 'Cream', 'كريم', '', 'Hair care', '120 ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 2028, '2022-07-14', CURRENT_TIMESTAMP),
(845, 'Apexidone 3mg 30 f.c.tab.', 'ابيكسيدون 3مجم 30 قرص', '', '126', 'Risperidone', 'Multi-apex', 'Tab', 'أقراص', 'علاج الامراض النفسية العصبية', 'Psychiatric.antipsychotics', '3mg', 'Risperidone is indicated for the treatment of schizophrenia [L12885,L44692,L46297] and irritability associated with autistic disorder.[L12885] It is also indicated as monotherapy, or adjunctly with lithium or valproic acid, for the treatment of acute mania or mixed episodes associated with bipolar I disorder.[L12885,L44692]
Risperidone is additionally indicated in Canada for the short-term symptomatic management of aggression or psychotic symptoms in patients with severe dementia of the Alzheimer type unresponsive to nonpharmacological approaches.[L12906]
Risperidone is also used off-label for a number of conditions including as an adjunct to antidepressants in treatment-resistant depression.[A177226]', '6223003200633', '', 2223, '2022-12-02', CURRENT_TIMESTAMP),
(2734, 'Lavage clear face soap', 'لافاج كلير فيس صابون 100 مجم', '30', '38', 'Irgasan+jojoba oil+lemon oil+olive oil+sulphur+glycerin', 'Top.z pharma', 'Soap', 'صابون', 'صابونة لتنظيف الوجة -- تقليل الاحمرار و الحكة -- علاج حب الشباب', 'Soap', '', '', '6225000029101', '', 1543, '2024-03-29', CURRENT_TIMESTAMP),
(15672, 'Calcium folinate 30mg/10ml amp(n/a)', 'كالسيوم فولينيت 30مجم/10مل امبولات', '', '160', 'Leucovorin calcium=folinic acid=calcium folinate', 'Orion pharma-finland > s.m. pharma', 'Amp', 'أمبول', '', 'Folic acid supplement', '30mg', 'For the treatment of osteosarcoma (after high dose methotrexate therapy). Used to diminish the toxicity and counteract the effects of impaired methotrexate elimination and of inadvertent overdosages of folic acid antagonists, and to treat megaloblastic anemias due to folic acid deficiency. Also used in combination with 5-fluorouracil to prolong survival in the palliative treatment of patients with advanced colorectal cancer.', '', '', 1101, '2022-06-18', CURRENT_TIMESTAMP),
(24359, 'Otribaby refill 10 nasal aspirator', 'اوتريبيبي 10', '', '75', '', 'Glaxo smithkline > modern pharma', 'Unknown', 'غير محدد', '', 'Nasal decongestant', '', '', '', '', 888, '2022-07-29', CURRENT_TIMESTAMP),
(25397, 'Prostavasin 20mcg amp', 'بروستافازين 20مكجم امبولات', '', '165', 'Alprostadil', 'Schwarz > amc', 'Amp', 'أمبول', 'يستخدم آلبروستاديل لعلاج ضعف الانت -- صاب الذي سببه عصبي او نفسي أو أسباب أخرى كما يستعمل في المواليد الجدد الذين لديهم عيوب خلقية في القلب .', 'Prostaglandin e1', '20mcg', 'Alprostadil is indicated for palliative, not definitive, therapy to temporarily maintain the patency of the ductus arteriosus until corrective or palliative surgery can be performed in neonates who have congenital heart defects and who depend upon the patent ductus for survival.[L45038] It is also indicated for the treatment of erectile dysfunction due to neurogenic, vasculogenic, psychogenic, or mixed etiology,[L45028,L45033] and as an adjunct to other diagnostic tests in the diagnosis of erectile dysfunction.[L45028]', '', '', 4121, '2022-07-24', CURRENT_TIMESTAMP),
(28158, 'Aaa', 'ششش', '', '16', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 691, '2022-07-14', CURRENT_TIMESTAMP),
(2593, 'Jinjolifa 120 ml syrup', 'جينجوليفا 120 مل شراب', '', '59', 'Ginger root extract+fennel seed extract', 'Olivia pharma', 'Syrup', 'شراب', '', 'Anti colic', '120 ml', '', '', '', 935, '2025-01-23', CURRENT_TIMESTAMP),
(331, 'Algesal suractive cream 40 gm', 'الجزال كريم 40 جرام', '30.5', '46', 'Diethylamine+myrtecaine+salicylic acid', 'Chemipharm > solvay', 'Cream', 'كريم', 'لعلاج آلام العظام والروماتيزم والتهابات المفاصل.', 'Massage.topical analgesic.muscle', '40 gm', '', '6222006500115', '', 11644, '2024-07-30', CURRENT_TIMESTAMP),
(14722, 'Avene trixera nutri-fluid lotion 400ml', 'افين تريكسيرا لوشن سائل مغذي 400 مل', '', '365', '', 'Pierre - fabre france > biotech egypt', 'Lotion', 'لوشن', '', 'Moisturizing topicals', '400ml', 'benefits *nourishing yet fluid texture allow for time-saving application -- apply and get dressed immediately! *calms discomfort *helps replenish lipids which are lacking in dry skin *suitable for use on the face and body *provides 48-hour hydration *safe', '', '', 740, '2022-07-21', CURRENT_TIMESTAMP),
(19754, 'Germovid powder 450 gm', 'جيرموفيد بودرة 450 جم', '', '60', 'Natural wheat germ oil', 'Nilco > lavida group', 'Powder', 'بودرة', '', 'Vitamin e', '450 gm', '-suitable for all family members -use: 1-2 tablespoonful to be mixed with milk youghurt juice green salad fruit salad and bakeries.', '', '', 900, '2022-07-24', CURRENT_TIMESTAMP),
(28442, 'Tretomart top. gel 40 gm', 'تريتومارت جل 40 جرام', '', '14', 'Clindamycin+tretinoin', 'Amriya', 'Gel', 'جل', 'جل علاج حب الشباب واثار الحبوب والرؤوس السوداء', 'Anti-acne', '40 gm', '', '', '', 1041, '2022-06-30', CURRENT_TIMESTAMP),
(29388, 'Vipdomet 12.5/1000 mg 28 f.c. tabs', 'فيبدوميت 12.5/1000مجم 28 قرص', '', '207', 'Alogliptin+metformin', 'Takeda > takeda scientific office', 'Tab', 'أقراص', 'لعلاج مرضى السكر', 'Anti-diabetic.secretagogues.dpp-4 inhibitors', '1000 mg', '', '', '', 1531, '2022-03-25', CURRENT_TIMESTAMP),
(12555, 'Voltaren 1% emulgel 50 gm', 'فولتارين 1% ايملجل 50 جم', '45.5', '68', 'Diclofenac diethylamine', 'Novartis > glaxo smithkline', 'Gel', 'جل', 'مسكن لآلام العضلات والمفاصل', 'Massage.analgesic', '1%', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6223013531628', '', 7700, '2024-07-22', CURRENT_TIMESTAMP),
(15471, 'Breva d3 50.000 i.u. 4 tabs', 'بريفا د3 50000 وحدة دولية 4 اقراص', '', '80', 'Cholecalciferol', 'Medcare > vortex pharmaceuticals', 'Tab', 'أقراص', '', 'Vitamin d', '', 'Cholecalciferol use is indicated for the treatment of specific medical conditions like refractory rickets (or vitamin D resistant rickets), hypoparathyroidism, and familial hypophosphatemia [F4027, F4042].
Concurrently, as one of the most commonly utilized forms of vitamin D, cholecalciferol is also very frequently used as a supplement in individuals to maintain sufficient vitamin d levels in the body or to treat vitamin D deficiency, as well as various medical conditions that can be associated directly or indirectly with vitamin d insufficiency like osteoporosis and chronic kidney disease, among others [A176041, A176044, F4051].', '', '', 2053, '2022-05-08', CURRENT_TIMESTAMP),
(13924, 'Amikin 250mg/2ml vial (n/a)', 'اميكين 250مجم/2مل فيال', '', '10', 'Amikacin', 'Smithkline beecham', 'Vial', 'فيال', '', 'Aminoglycoside antibiotic', '250mg', 'The amikacin sulfate injection is indicated in the short-term treatment of serious bacterial infections due to susceptible strains of gram-negative bacteria, including Pseudomonas species, Escherichia coli, species of indole-positive and indole-negative Proteus, Providencia species, Klebsiella-Enterobacter-Serratia species, as well as Acinetobacter (Mima-Herellea) species.[F1954]
Clinical studies have shown amikacin sulfate injection to be effective in bacterial septicemia (including neonatal sepsis); in serious infections of the respiratory tract, bones and joints, central nervous system (including meningitis) and skin and soft tissue; intra-abdominal infections (including peritonitis); and in burns and postoperative infections (including post-vascular surgery).[F1954]
Clinical studies have shown amikacin also to be effective in serious, complicated, and recurrent urinary tract infections due to the above organisms. Aminoglycosides, including amikacin, are not indicated in uncomplicated first-time episodes of urinary tract infections unless the causative organisms are not susceptible to antibiotics which are less toxic.[F1954]
In September 2018, a new indication with a new dosage route was approved for this drug. Amikacin liposome inhalation suspension was approved for the treatment of lung disease caused by a group of bacteria, Mycobacterium avium complex (MAC) in a limited population of patients with the disease who do not respond to conventional treatment (refractory disease).[L4673] This indication is approved under accelerated approval based on achieving sputum culture conversion (defined as 3 consecutive negative monthly sputum cultures) by Month 6 of treatment. Clinical benefit has not yet been established.[Label]
**Important notes regarding Staphylococcus and Sensitivity testing:**
Staphylococcus aureus, including methicillin-resistant strains, is the principal Gram-positive organism sensitive to amikacin.
The use of amikacin in the treatment of staphylococcal infections should be restricted only to second-line therapy, and should be limited to only those patients suffering from severe infections caused by susceptible strains of staphylococcus species who have failed to show sensitivity to other available antibiotics.[F1949]
Bacteriologic studies should be performed to identify causative organisms and their susceptibilities to amikacin. Amikacin may be used as initial therapy in suspected gram-negative infections and therapy may be initiated before obtaining the results of susceptibility testing.[Label,F1949,F1954]', '', '', 1211, '2023-02-08', CURRENT_TIMESTAMP),
(15806, 'Carbamide-memphis 10% cream 30 gm', 'كارباميد كريم 30 جرام', '35', '40', 'Carbamide', 'Memphis', 'Cream', 'كريم', '1- علاج لتشقق اليدين والقدمين والأصابع الشديد.', 'Moisturizing topicals', '10%', 'Indicated as a dental bleaching agent. 
Indicated as an oral wound healing agent in oral mucosal injuries.
Indicated as an aid in the removal of hardened ear wax.', '6221050130293', '', 14702, '2025-07-06', CURRENT_TIMESTAMP),
(8359, 'Eternalvesion cream 60 gm', 'اتيرنالفيجن كريم 60 جم', '', '135', 'Lactic acid+alpha arbutin+kojic acid+vitamin c+licorice extract', 'Tag egy pharma', 'Cream', 'كريم', '', 'Whiting cream', '60 gm', 'For use as an alkalinizing agent.', '', '', 745, '2025-12-13', CURRENT_TIMESTAMP),
(29734, 'Aaa', 'ششش', '', '209', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 433, '2022-08-17', CURRENT_TIMESTAMP),
(23376, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 658, '2022-07-31', CURRENT_TIMESTAMP),
(7813, 'Mazemal 200 mg 20 tabs.', 'مازيمال 200مجم 20 قرص', '', '37', 'Carbamazepine', 'Unipharma co.', 'Tab', 'أقراص', '', 'Anti-epileptic.carboxamides', '200 mg', 'Carbamazepine is indicated for the treatment of epilepsy and pain associated with true trigeminal neuralgia.[L1335] In particular, carbamazepine has shown efficacy in treating mixed seizures, partial seizures with complex symptoms, and generalized tonic-clonic seizures.[A180301,L1335] Carbamazepine is also indicated for the treatment of manic episodes and mixed manic-depressive episodes caused by bipolar I disorder.[L1335] Some off-label, unapproved uses of carbamazepine include the treatment of alcohol withdrawal syndrome and restless leg syndrome.[A180415,A180421]', '6221507010055', '', 2452, '2023-05-19', CURRENT_TIMESTAMP),
(9441, 'Aaa', 'ششش', '', '34', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 699, '2023-03-10', CURRENT_TIMESTAMP),
(972, 'Robar cream 100 gm', 'روبار كريم 100 جم', '', '75', '', 'Company', 'Cream', 'كريم', '', '', '100 gm', '', '', '', 2032, '2022-12-02', CURRENT_TIMESTAMP),
(28346, 'Topzol 1% cream 20 gm', 'توبزول 1% كريم 20جم', '', '8', 'Tioconazole', 'Hikma pharma', 'Cream', 'كريم', '', 'Antifungals.imidazoles', '1%', 'For the local treatment of vulvovaginal candidiasis (moniliasis).', '', '', 811, '2022-07-28', CURRENT_TIMESTAMP),
(1752, 'Broncho-vaxom children 3.5mg 10 caps', 'برونكو-فاكسوم اطفال 10 كبسولات', '110', '158', 'Bacterial lysate', 'Memphis > om-switzerland', 'Cap', 'كبسولة', 'مقوي للمناعة -- تقليل الاصابة بالامراض التنفسية -- علاج الالتهاب الرئوي', 'Immune enhancer', '3.5mg', '', '6221050050096', '', 5960, '2024-09-25', CURRENT_TIMESTAMP),
