Olanzapine is also approved for the management of psychomotor agitation associated with schizophrenia and bipolar I mania.[FDA label]
Schizophrenia is a complex biochemical brain disorder that affects the person''s ability to differentiate reality. It is usually observed as the presence of delusions, hallucinations, social withdrawal and disturbed thinking.[L5936]
Bipolar disorder is a mental health condition defined by periods of extreme mood disturbances. It is categorized in different types from which type 1 is known to involve episodes of severe mania and often depression while type 2 presents less severe forms of mania.[L5939]
Olanzapine is also indicated in combination with [samidorphan] for the treatment of bipolar I disorder, either as an adjunct to lithium or valproate or as monotherapy for the acute treatment of manic or mixed episodes or as maintenance therapy, and for the treatment of schizophrenia in adults.[L34359]', '', '', 1019, '2024-02-08', CURRENT_TIMESTAMP),
(12232, 'Vermin 100mg/5ml susp. 30ml', 'فيرمين 100مجم/5مل معلق 30مل', '4', '10', 'Mebendazole', 'Memphis', 'Susp', 'معلق', 'طارد للديدان', 'Anthelmintic', '100mg', 'For the treatment of <i>Enterobius vermicularis</i> (pinworm), <i>Trichuris trichiura</i> (whipworm), <i>Ascaris lumbricoides</i> (common roundworm), <i>Ancylostoma duodenale</i> (common hookworm), <i>Necator americanus</i> (American hookworm) in single or mixed infections.', '6221050090030', '', 1826, '2025-01-01', CURRENT_TIMESTAMP),
(14963, 'Becal cream 40 gm', 'بيكال كريم 40 جم', '40', '75', '', 'Egyptian company for cosmetics > ballance pharma', 'Cream', 'كريم', 'علاج حب الشباب -- تقليل الالتهابات -- تقليل الحكة والاحمرار', 'Anti-acne', '40 gm', 'for acne prone skin. use once at night.', '', '', 1595, '2025-08-07', CURRENT_TIMESTAMP),
(32264, 'Aaa', 'ششش', '', '435', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 616, '2023-04-27', CURRENT_TIMESTAMP),
(25518, 'Pyritrust 1 gm/100ml soln. i.v. inf.', 'بيريترست 1جم/100مل محلول', '22.5', '28', 'Paracetamol(acetaminophen)', 'Global napi pharmaceuticals > pharma trust citical co.', 'Sol', 'محلول', '', 'Antipyretic', '1 gm', 'about paracetamol acetanilide derivative non narcotic analgesic antipyretic. mechanism of action of paracetamol paracetamol has analgesic and antipyretic action. it is more active on cyclo-oxygenase enzyme in brain. peripherally it is a poor inhibitor of', '6223004901683', '', 986, '2023-09-20', CURRENT_TIMESTAMP),
(3857, 'Dostinex 0.5 mg 2 tabs.', 'دوستينكس 0.5 مجم 2 قرص', '118.5', '172', 'Cabergoline', 'Pfizer', 'Tab', 'أقراص', 'مضاد لهرمون اللبن -- علاج بعض حالات تأخر الحمل في السيدات -- مضاد لهرمون البرولاكتين لتنشيف اللبن بعد فطام الطفل', 'Dopamine agonist and prolactin inhibitor', '0.5 mg', 'For the treatment of hyperprolactinemic disorders, either idiopathic or due to prolactinoma (prolactin-secreting adenomas). May also be used to manage symptoms of Parkinsonian Syndrome as monotherapy during initial symptomatic management or as an adjunct to levodopa therapy during advanced stages of disease.', '43544524323', '', 19778, '2024-11-10', CURRENT_TIMESTAMP),
(23612, 'Niplo cream 30gm', 'نيبلو كريم 30 جم', '', '14', 'Stearic acid+cetyl alcohol+triethanolamine+sesame oil+almond oil+jojoba oil+wheat germ oil+panthenol', 'Egyptian canadian for drug', 'Cream', 'كريم', '', 'Moisturizing topicals', '30gm', 'moisturizing cream for cracked nipples.', '', '', 729, '2022-07-09', CURRENT_TIMESTAMP),
(29992, 'Zofatrone 8mg/4ml 3 amp. for i.v/i.m inj.', 'زوفاترون 8مجم/4مل 3 امبول', '85.5', '126', 'Ondansetron', 'Eva pharma', 'Inj', 'حقن', '', '5-ht3 receptor antagonist', '8mg', 'In the adult patient population:
i) orally administered ondansetron tablets and orally disintegrating tablets (ODT) are indicated for:
- the prevention of nausea and vomiting associated with emetogenic cancer chemotherapy, including high dose (ie. greater than or equal to 50 mg/m2) cisplatin therapy, and radiotherapy, and
- the prevention and treatment of postoperative nausea and vomiting
ii) intravenously administered ondansetron injection formulations are indicated for:
- the prevention of nausea and vomiting associated with emetogenic cancer chemotherapy, including high dose (ie. greater than or equal to 50 mg/m2) cisplatin therapy, and
- the prevention and treatment of postoperative nausea and vomiting
In the pediatric (4-18 years of age) patient population:
i) ondansetron was effective and well tolerated when given to children 4-12 years of age for the treatment of post-chemotherapy induced nausea and vomiting,
ii) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for the treatment of children 3 years of age or younger,
iii) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for use in any age group of the pediatric population for the treatment of post-radiotherapy induced nausea and vomiting, and
iV) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for use in any age group of the pediatric population for the treatment of postoperative nausea and vomiting
In the geriatric (>65 years of age) patient population:
i) efficacy and tolerance of ondansetron were similar to that observed in younger adults for the treatment of post-chemotherapy and radiotherapy-induced nausea and vomiting, and
ii) clinical experience in the use of ondansetron in the prevention and treatment of postoperative nausea and vomiting is limited and is not indicated for use in the geriatric patient population', '6223004515835', '', 913, '2024-08-15', CURRENT_TIMESTAMP),
(20973, 'Irontec 20 chew. pieces', 'ايرونتيك 20 قطعة قابلة للمضغ', '48', '85', 'Iron+zinc+folic acid', 'Covertina > amoun tec', 'Piece', 'قطعة', 'يحتوي على الحديد', 'Iron supplement', '', '', '', '', 1000, '2025-08-23', CURRENT_TIMESTAMP),
(10775, 'Spasmorest 10 mg/ml 6 i.m. amp.', 'سبازمورست 10مجم/مل 6 امبولات', '', '7', 'Dicyclomine', 'Misr', 'Amp', 'أمبول', 'مضاد للتقلصات', 'Antimuscarinic.irritable bowel syndrome', '10 mg', 'Dicyclomine is indicated for the treatment of functional bowel disorder and irritable bowel syndrome.[L7967]', '', '', 825, '2023-04-27', CURRENT_TIMESTAMP),
(17683, 'Diolax 7.5mg 20*10 tab.', 'ديولاكس 7.5مجم 20*10 قرص', '', '36', 'Sennoside', 'Hikma pharma', 'Tab', 'أقراص', '', 'Laxative', '7.5mg', '', '', '', 1130, '2023-01-12', CURRENT_TIMESTAMP),
(8362, 'Ivypto 120 ml syrup', 'ايفيبتو شراب 120 مل', '', '65', 'Ivy leaves extract 50 mg+n-acetyl-l-cysteine 50 mg+zinc gluconate 13.065 mg/5 ml', 'Care theraputica for pharmaceuticals', 'Syrup', 'شراب', '', 'Mucolytic and expectorant cough therapy', '120 ml', '', '', '', 725, '2025-12-14', CURRENT_TIMESTAMP),
(15304, 'Aaa', 'ششش', '', '30', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 831, '2022-09-07', CURRENT_TIMESTAMP),
(18831, 'Farcozol plus susp. 120ml', 'فاركوزول بلس معلق 120 مل', '6', '13', 'Diloxanide furoate+metronidazole', 'Pharco', 'Susp', 'معلق', '', 'Antiprotozoal.nitroimidazole', '120ml', 'Diloxanide is used alone as a primary agent in the treatment of asymptomatic (cyst passers) intestinal amebiasis caused by Entamoeba histolytica. Diloxanide may also be used concurrently, or sequentially, with other agents such as the nitroimidazoles (eg. metronidazole) in the treatment of invasive or extraintestinal forms of amebiasis.', '6221151002413', '', 973, '2024-12-11', CURRENT_TIMESTAMP),
(15160, 'Aaa', 'ششش', '', '9', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 792, '2022-07-12', CURRENT_TIMESTAMP),
(8504, 'Myocool cream 60 gm', 'ميوكول كريم 60 جرام', '71', '85', 'Winter green oil+peppermint oil+silicon oil+cetyl alcohol+propyl paraben+petrolium jelly+stearic aci', 'Leader cosmetics > purex health care', 'Cream', 'كريم', 'آلام أسفل الظهر وعرق النسا.', 'Massage', '60 gm', '', '6224008843412', '', 10907, '2025-05-28', CURRENT_TIMESTAMP),
(25370, 'Propylthiouracil 50mg 20 tab. b.p 2002', 'بروبايلثيويوراسيل 50مجم 20 اقراص', '', '14', 'Propylthiouracil', 'Memphis', 'Tab', 'أقراص', '', 'Antithyroid', '50mg', 'Used to manage hyperthyroidism which is due to an overactive thyroid gland (Grave''s disease).', '', '', 1399, '2022-07-12', CURRENT_TIMESTAMP),
(14290, 'Aphrofemine 100mg 30 f.c. tabs', 'افروفيمين 100مجم 30 قرص', '', '600', 'Flibanserin', 'Mash premiere > biomed pharmaceuticals', 'Tab', 'أقراص', 'لزيادة الرغبة للسيدات', 'Women need', '100mg', 'For the treatment of hypoactive sexual desire disorder (HSDD) in premenopausal women.', '', '', 2939, '2023-04-02', CURRENT_TIMESTAMP),
(23819, 'Nox topical lotion 120ml', 'نوكس لوشن 120مل', '', '10', 'Zinc oxide+menthol crystals+thyme oil+coconut oil+glycerin+beeswax+stearic acid+cetyl alcohol+isopro', 'Leader cosmetics > a-one pharma', 'Lotion', 'لوشن', '', 'Soothing topical', '120ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 827, '2022-07-09', CURRENT_TIMESTAMP),
(3581, 'Nervoter 30 caps', 'نيرفوتر 30 كبسولة', '', '497', 'Alpha-lipoic acid+vitaminsb6+b12+d3', 'Total future', 'Cap', 'كبسولة', '', 'Multivitamins', '', '', '', '', 1230, '2025-04-23', CURRENT_TIMESTAMP),
(2546, 'Cibacen 10 mg 7 tab', 'سيباسين 10مجم 7 اقراص', '', '19', 'Benazepril', 'Novartis', 'Tab', 'أقراص', '', 'Antihypertensive ace', '10 mg', 'Benazepril is indicated for the treatment of hypertension[A840]. It may be used alone or in combination with thiazide diuretics[FDA Label].', '', '', 989, '2022-09-22', CURRENT_TIMESTAMP),
(2563, 'Zetadidox 10/10 mg 30 tabs.', 'زيتاديتوكس 10/10مجم 30 قرص', '37.5', '66', 'Doxylamine succinate+pyridoxine hcl(vitamin b6)', 'Zeta pharma', 'Tab', 'أقراص', '', 'Antiemetic', '10 mg', 'Used alone as a short-term sleep aid, in combination with other drugs as a night-time cold and allergy relief drug. Also used in combination with Vitamin B6 (pyridoxine) to prevent morning sickness in pregnant women.', '200406423018', '', 1864, '2025-01-20', CURRENT_TIMESTAMP),
(18789, 'Famox 250mg/5ml susp. 60ml', 'فاموكس 250 مجم / 5 مل معلق 60 مل', '', '14', 'Amoxicillin+flucloxacillin', 'Sedico > top pharm', 'Susp', 'معلق', '', 'Penicillins.penicillin with b-lactamase inhibitor', '250mg', 'amoxycillin and flucloxacillin ï¿½ generally exhibit an additive effect against sensitive bacteria and bacteria that are sensitive to amoxycillin or to flucloxacillin remain sensitive to the combination showing that antagonism does not occur when the two', '', '', 821, '2022-07-14', CURRENT_TIMESTAMP),
(1587, 'Bi-profenid 150mg 20 scored tabs.', 'باي بروفينيد 150مجم 20 قرص', '37', '54', 'Ketoprofen', 'Sanofi', 'Tab', 'أقراص', 'مسكن قوي للصداع وآلام الأسنان.', 'Nsaid.propionic acid derivatives .analgesic .antipyretic', '150mg', 'For symptomatic treatment of acute and chronic rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, primary dysmenorrhea and mild to moderate pain associated with musculotendinous trauma (sprains and strains), postoperative (including dental surgery) or postpartum pain.', '6223003990350', '', 23310, '2024-12-07', CURRENT_TIMESTAMP),
(7768, 'Ginroy 20 caps', 'جينروي 20 كبسولة', '', '140', 'Royal jelly 300 mg+ginseng300 mg+licorice roots 100mg', 'Abo el enen pharm', 'Cap', 'كبسولة', '', 'Multivitamin', '', '', '', '', 830, '2025-10-24', CURRENT_TIMESTAMP),
(20908, 'Intraperitoneal dialysis sol. anhydrous dextrose 4.25% (acetate)', 'انترابيريتونيال دياليسيس محلول اندهيريس ديكستروز 4.25% اسيتات', '', '12', 'Calcium chloride+glucose (dextrose)+magnesium chloride+sodium acetate+sodium chloride+sodi', 'El nasr', 'Sol', 'محلول', '', 'Sterile solution', '4.25%', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 798, '2022-08-03', CURRENT_TIMESTAMP),
(19924, 'Glucose 40% (mottahedoon) i.v. inf. 500 ml', 'جلوكوز 40% المتحدون محلول وريدي زجاجة 500 مل', '', '5', 'Glucose (dextrose)', 'Al mottahedoon pharma', 'Unknown', 'غير محدد', '', 'Sterile solution', '40%', 'about glucose monosaccharide aldohexose nutritive sweetner. mechanism of action of glucose glucose is a simple carbohydrate and is used as energy source in man. it is readily converted to fat which provides a rich store of energy in concentrated form. glu', '', '', 1025, '2022-07-15', CURRENT_TIMESTAMP),
(2717, 'Clavimox 625 mg 12 f.c.tabs.', 'كلافيموكس 625مجم 12 قرص', '73.5', '107', 'Amoxicillin+clavulanic acid', 'Pharco', 'Tab', 'أقراص', 'مضاد حيوي', 'Penicillins.penicillin with b-lactamase inhibitor', '625 mg', '', '6221151015734', '', 9898, '2024-12-07', CURRENT_TIMESTAMP),
(4622, 'Pelembap urea cream 60 gm', 'بليمباب يوريا كريم 60 جم', '', '100', 'Urea 10%+ceramide+panthenol', 'Yojeen', 'Cream', 'كريم', '', 'Smoothens rough dry skin', '60 gm', 'Urea is used topically for debridement and promotion of normal healing of hyperkeratotic surface lesions, particularly where healing is retarded by local infection, necrotic tissue, fibrinous or purulent debris or eschar. Urea is useful for the treatment of hyperkeratotic conditions such as dry, rough skin, dermatitis, psoriasis, xerosis, ichthyosis, eczema, keratosis, keratoderma, corns and calluses, as well as damaged, devitalized and ingrown nails.[L41484]', '', '', 834, '2025-06-18', CURRENT_TIMESTAMP),
(26505, 'Sanoplex 24 chewable tabs.', 'سانوبلكس 24 قرص مضغ', '109', '139', 'Iron(ferrous fumarate)+vitamins (b12+folic acid+b6)', 'El shorouk > zeta bio', 'Tab', 'أقراص', 'مكمل غذائي -- مصدر للحديد -- علاج حالات الانيميا -- مصدر لفيتامين ب -- مقوي اعصاب --', 'Iron supplement', '', 'ultimate bioactive iron formula specially formulated for support anemic patient and restoring the normal blood hemoglobin level specially before during and after pregnancy. ** helps in restoring the normal blood hemoglobin level in the following cases. be', '', '', 3750, '2025-08-16', CURRENT_TIMESTAMP),
(17298, 'De-prostyl-2 6 supp.', 'دي-بروستيل-2 6 اقماع لبوس', '', '4', 'Chamomile+ichthammol+potassium iodide', 'Cid', 'Supp', 'لبوس', 'علاج تضخم البروستاتا.', 'Prostate disorder', '', 'antispasmodic anxiolytic anti-inflammatory and some antimutagenic and cholesterol-lowering effects for chamomile.chamomile has sped healing time of wounds.', '6221043012476', '', 1243, '2022-12-04', CURRENT_TIMESTAMP),
(12338, 'Lacosanad 100 mg 20 f.c. tabs.', 'لاكوساناد 100مجم 20 قرص', '', '120', 'Lacosamide', 'Inad pharma', 'Tab', 'أقراص', '', 'Anti-epileptic', '100 mg', 'In the US and Europe, lacosamide is indicated for the treatment of partial-onset seizures in children and adults.[L49191, L49196, L49201] In Canada, it is reserved for use in adults.[L49206]
It is also used as an adjunctive therapy in the treatment of primary generalized tonic-clonic seizures in patients four years of age and older.[L49191, L49201]
