1) Management of hypertension alone and in combination with other antihypertensives.
2) Management of angina pectoris associated with coronary atherosclerosis.
3) Management of acute myocardial infarction in hemodynamically stable patients with a heart rate greater than 50 beats per minutes and a systolic blood pressure above 100 mmHg.
**Off-label** uses include:
1) Secondary prevention of myocardial infarction.[A178156]
2) Management of heart failure.[A178153]
3) Management of atrial fibrillation.[A178141]
4) Management of supraventricular tachycardia.[A178162]
5) Management of ventricular arrythmias such as congenital long-QT and arrhythmogenic right ventricular cardiomyopathy.[A178168]
6) Management of symptomatic thyrotoxicosis in combination with [methimazole].[A178147]
7) Prophylaxis of migraine headaches.[A178171]
8) Management of alcohol withdrawal.[A178174,A178177]', '', '', 759, '2022-07-25', CURRENT_TIMESTAMP),
(1181, 'Sly-impress massage gel 30 gm', 'سلي امبريس مساج جل 30 جم', '', '82', 'Menthol crystals 5%+camphor crystals 3%+vit e (tocopherol)+vit b5 (pantothenic acid)+panthenol+eucalyptus+ginger+clove bud oils+thymus vulgaris oil+mentha piperita oil', 'Elsaid saliy pharma', 'Gel', 'جل', '', 'Massage gel', '30 gm', '', '', '', 956, '2022-09-06', CURRENT_TIMESTAMP),
(29473, 'Vital care shampoo imperial argan 500ml', 'فيتال كير شامبو 500مل', '', '110', '', 'So.di.co. srl > bright star -egypt', 'Amp', 'أمبول', '', 'Hair care', '500ml', '', '', '', 716, '2022-07-30', CURRENT_TIMESTAMP),
(18695, 'Exelon 18 mg 10 cm 9.5mg/24h 30 transdermal patches', 'اكسيلون 9مجم 5 سم 4.5مجم/24 ساعة 30 لصقة', '822', '1,069', 'Rivastigmine', 'Lts lohmann therapie systeme ag-germany > novartis', 'Patch', 'لصقة', '', 'Anticholinesterase', '18 mg', 'For the treatment of mild to moderate dementia associated with Parkinson''s disease or of the Alzheimer''s type.', '', '', 1022, '2024-12-28', CURRENT_TIMESTAMP),
(15027, 'Beesline whitening body lotion bridal vanilla 200 ml', 'بيزلين لوشن لتفتيح الجسم برائحة الفانيلا 200 مل', '', '255', '', 'Beesline > pharma cruise medical', 'Lotion', 'لوشن', '', 'Skin care', '200 ml', 'active ingredients sweet almond oil coconut oil sodium lactate vegetable glycerin lemon peel olive leaf parsley honey lactic acid & vitamin c. aromatic fast-absorbing lotion that moisturises & lightens dry skin for a smooth blemish-free & radiant finish.', '', '', 777, '2022-07-15', CURRENT_TIMESTAMP),
(12824, 'Wega 10 sachets', 'ويجا 10 اكياس', '90', '90', 'Lactoferrin 100mg+magnesium+calcium', 'Lasanta', 'Sachet', 'أكياس', 'مكمل غذائى لدعم صحة العظام ويعزز مرونة المفاصل ويحمي الغضاريف ويعزز الجهاز المناعى', 'Multi vitamin', '', '', '', '', 1169, '2024-03-24', CURRENT_TIMESTAMP),
(151, 'Adcocycline 3% oint. 15 gm', 'ادكوسيكلين 3% مرهم 15 جم', '', '7', 'Tetracycline', 'Arab drug company.', 'Oint', 'مرهم', 'مرهم مضاد حيوي', 'Antibiotic.tetracycline', '3%', 'Used to treat bacterial infections such as Rocky Mountain spotted fever, typhus fever, tick fevers, Q fever, rickettsialpox and Brill-Zinsser disease. May be used to treat infections caused by Chlamydiae spp., B. burgdorferi (Lyme disease), and upper respiratory infections caused by typical (S. pneumoniae, H. influenzae, and M. catarrhalis) and atypical organisms (C. pneumoniae, M. pneumoniae, L. pneumophila). May also be used to treat acne. Tetracycline may be an alternative drug for people who are allergic to penicillin.', '6221060001385', '', 2036, '2022-05-27', CURRENT_TIMESTAMP),
(13292, 'Abstral 200mcg 10 sublingual tabs.', 'ابيسترال 200مكجم 10 قرص تحت اللسان', '', '1,184', 'Fentanyl', 'Kyowa kirin limited > egyptian pharmaceutical trading company', 'Tab', 'أقراص', '', 'Analgesics.opioid', '200mcg', 'Fentanyl intravenous or intramuscular injections are indicated for short term analgesia during induction, maintenance, and recovery from general or regional anesthesia.[Label] These injections are also used with a neuroleptic for premedication, induction, and as an adjunct to maintenance of anesthesia.[Label] Finally, fentanyl intravenous or intramuscular injections are used with oxygen for anesthesia in high risk patients.[Label]
Fentanyl sublingual tablets, transmucosal lozenges, buccal tablets, sublingual sprays, transdermal systems, and nasal sprays are indicated for the management of breakthrough pain in opioid tolerant cancer patients who require around the clock pain management.[L6598,L6601,L6604,L6607,L922,L6610]', '', '', 1017, '2022-07-14', CURRENT_TIMESTAMP),
(16516, 'Clindacine 1% topical gel 20 gm', 'كلينداسين 1% جل موضعي 20 جم', '', '7', 'Clindamycin', 'Rameda', 'Gel', 'جل', '', 'Antibiotic.lincomycins', '1%', 'In oral and parenteral formulations, clindamycin is indicated for the treatment of serious infections caused by susceptible anaerobic bacteria, as well as susceptible staphylococci, streptococci, and pneumococci.[L11599,L11602] Used topically, it is indicated for the treatment of acne vulgaris[L11593,L11611,L11605] and is available in combination with [benzoyl peroxide][L11584] or [tretinoin][L11590] for this purpose, or as a triple combination therapy with benzoyl peroxide and [adapalene].[L48666] Clindamycin is also indicated as a vaginal cream[L11596], suppository[L11608], or gel[L39416] for the treatment of bacterial vaginosis in non-pregnant females.
Clindamycin is used for antimicrobial prophylaxis against _Viridans_ group streptococcal infections in susceptible patients undergoing oral, dental, or upper respiratory surgery, and may be used for prophylaxis against bacterial endocarditis in penicillin-allergic patients at high risk of these infections.[L11629]', '', '', 1441, '2022-08-08', CURRENT_TIMESTAMP),
(8161, 'Midodrine 2.5mg 20 tab', 'ميدودرين 2.5مجم 20 قرص', '38', '50', 'Midodrine', 'El nile.', 'Tab', 'أقراص', 'لحالات ضغط الدم المنخفض', 'Orthostatic hypotension', '2.5mg', 'For the treatment of symptomatic orthostatic hypotension (OH).', '6221077014019', '', 9252, '2024-11-09', CURRENT_TIMESTAMP),
(23650, 'Nizaxid 15 mg/ml syrup 90 ml', 'نيزاكسيد 15مجم/مل شراب 90مل', '29', '47', 'Nizatidine', 'Sabaa > activa therapeutics', 'Syrup', 'شراب', '', 'Peptic ulcer.anti-histamine.h2 antagonist', '15 mg', 'For the treatment of acid-reflux disorders (GERD), peptic ulcer disease, active benign gastric ulcer, and active duodenal ulcer.', '6224000808280', '', 1082, '2023-12-22', CURRENT_TIMESTAMP),
(26510, 'Sanso c plus 28 tabs', 'سانسو سي بلس 28 قرص', '180', '190', 'Zinc+vitamin c+vitamin d3+vitamin e+vitamin a', 'Aug pharma', 'Tab', 'أقراص', 'فيتامينات و املاح ومعادن -- لتقوية الجهاز المناعي -- زيادة قدرة الجسم على مقاومة الامراض', 'Multivitamins', '', '', '', '', 4124, '2025-02-05', CURRENT_TIMESTAMP),
(33512, 'U-richi panthenol cream 50 gm', 'يو ريتشي بانثينول كريم 50 جم', '45', '85', 'Dexpanthenol+vitamin c+nicotinamide+liquorice extract+cocoa butter+grape seed oil+collagen+elastin+honey+zink oxide+raspberry extract+glutathione.', 'U-richi', 'Cream', 'كريم', '', 'Skin care moisturizing cream', '50 gm', '', '6224011774093', '', 3679, '2024-08-29', CURRENT_TIMESTAMP),
(4980, 'Thromoxiban 20 mg 30 tabs.', 'ثروموكسيبان 20 مجم 30 قرص', '', '390', 'Rivaroxaban', 'Medizen pharmaceutical industries', 'Tab', 'أقراص', '', 'Antiplatlet.direct factor xa inhibitor', '20 mg', 'Rivaroxaban is indicated for the prevention of venous thromboembolic events (VTE) in patients who have undergone total hips replacements and total knee replacement surgery; prevention of stroke and systemic embolism in patients with nonvalvular atrial fibrillation; treatment of deep vein thrombosis (DVT) and pulmonary embolism (PE); to reduce risk of recurrent DVT and/or PE. Rivaroxaban is also indicated, in combination with aspirin, for reducing the risk of major cardiovascular events in patients with chronic coronary artery disease or peripheral artery disease. Its use is also not recommended in those with severe renal impairment (<30mL/min).[L12819]
Rivaroxaban is also indicated for the treatment and prevention of VTE in pediatric patients (from birth to 18 years of age) and for thromboprophylaxis in pediatric patients ≥2 years old with congenital heart disease following the Fontan procedure.[L12819]', '', '', 918, '2025-06-22', CURRENT_TIMESTAMP),
(7093, 'New well vitamin b-12 spray 30 ml', 'نيو ويل فيتامين ب12 سبراي 30 مل', '', '219', 'Vitamin b-12', 'Eureka pharma llc', 'Spray', 'بخاخ', '', 'Supports nervous system health - supports the formation of red blood cells', '30 ml', 'For the treatment of vitamin A deficiency.', '', '', 758, '2025-08-23', CURRENT_TIMESTAMP),
(6594, 'Hepta panthenol rich body lotion 250 ml', 'هيبتا بانثينول ريتش بودي لوشن 250 مل', '', '199', 'Panthenol+prebiotics', 'Hepta', 'Lotion', 'لوشن', '', 'Skin care.moisturizing', '250 ml', '', '', '', 722, '2025-08-08', CURRENT_TIMESTAMP),
(30394, 'Dentohex mouth spray 60 ml', 'دينتوهكس بخاخ للفم 60 مل', '25', '50', 'Chlorhexidine+sodium fluoride+thymol+menthol+eucalyptus+green tea extract+grape seed extract+sorbitol+saccharin+glycerin', 'Italian cosmetics > ivet', 'Spray', 'بخاخ', '', 'Mouth spray', '60 ml', 'anti septic mouth spray mouth refreshing mouth cleaner mouth cleanser', '', '', 1671, '2024-03-30', CURRENT_TIMESTAMP),
(27445, 'Stamaril yellow fever vaccine', 'ستاماريل لقاح للحمى الصفراء', '', '50', 'Vaccine yellow fever', 'Sanofi pasteur-france > etimex-egypt', 'Unknown', 'غير محدد', '', 'Vaccine', '', '', '', '', 994, '2022-07-07', CURRENT_TIMESTAMP),
(17362, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 674, '2022-09-23', CURRENT_TIMESTAMP),
(24043, 'Omecarbex 40/1100mg 20 caps.', 'اوميكاربيكس 40/1100مجم 20 كبسولة', '45', '98', 'Omeprazole+sodium bicarbonate', 'Sigma > andalous pharma', 'Cap', 'كبسولة', 'لعلاج إرتجاع المري -- لعلاج قرحة المعدة والإثنى عشر', 'Peptic ulcer.proton pump inhibitor', '1100mg', 'about omeprazole proton pump inhibitor substituted benzimidazole anti-secretory antiulcer. mechanism of action of omeprazole omeprazole is a proton pump inhibitor and it is a prodrug. after administration it diffuses in to the parietal cell of the stomach', '6224000396466', '', 1787, '2025-01-14', CURRENT_TIMESTAMP),
(29051, 'Vaxigrip tetra 15mcg/0.5ml prefilled syringe', 'فاكسيجريب تيترا 15مكجم/0.5مل سرنجة معبأة', '258', '370', 'Quadrivalent inactivated influenza avirus haemagglutinin vaccine', 'Sanofi pasteur-france > etimex-egypt', 'Syringe', 'حقنة', '', 'Vaccine', '15mcg', 'description the active substances are: influenza virus (inactivated split) of the following strains: a/h1n1 a/h3n b/ yamagata lineage and b/ victoria lineage each contains 15 micrograms haemagglutinin per 0.5 ml dose. vaxigrip tetra is a vaccine. this vac', '', '', 3041, '2024-08-10', CURRENT_TIMESTAMP),
(3336, 'Debeskon oral susp. 120 ml', 'ديبيسكون معلق 120 مل', '29.5', '44', 'Sodium bicarbonate+sodium alginate', 'Debeiky', 'Susp', 'معلق', 'مضاد للعلاج الحموضة وحرقان المعدة', 'Antacid', '120 ml', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '6225000005440', '', 5077, '2025-01-02', CURRENT_TIMESTAMP),
(17942, 'Ducray nutricerat emulsion 100 ml', 'دوكري نيوتريسيرات معلق 100 مل', '245', '250', '', 'Pierre - fabre france > biotech egypt', 'Unknown', 'غير محدد', '', 'Hair care', '100 ml', '*daily emulsion that repairs and protects very dry and damaged hair ends. *to repair and protect the dry and damaged ends of your hair apply a small amount of nutricerat intense-nutrition emulsion every day. the ends of your hair will be repaired nourishe', '3282779178686', '', 699, '2023-09-03', CURRENT_TIMESTAMP),
(24897, 'Photoderm kid spray spf 50+ 200ml', 'فوتوديرم سبراي للاطفال للوقاية من الشمس 200مل', '', '650', 'Sun protection formula', 'Bioderma dermatological laboratories > biotech egypt', 'Spray', 'بخاخ', '', 'Sun block', '200ml', 'specific photoprotection for childrenï-s delicate sensitive skin. ï- photoderm kidï-s anti-uva-uvb filter system safely protects the delicate skin of children. the exclusive patented cellular bioprotectionï- complex* reinforced by peptide c provides optim', '', '', 710, '2022-07-15', CURRENT_TIMESTAMP),
(4012, 'Prixafert 30 sachets', 'بريكسافيرت 30 كيس', '', '320', '', 'Company', 'Sachet', 'أكياس', '', '', '', '', '', '', 1268, '2025-06-02', CURRENT_TIMESTAMP),
(16595, 'Cobalamin depot 1000mcg/ml 5 amp. i.m.', 'كوبالامين ديبو 1000مكجم/2مل 5 امبولات عضل', '35', '55', 'Hydroxocobalamin', 'Pharopharma', 'Amp', 'أمبول', 'فيتامين ب12', 'Vitamin b', '1000mcg', 'For treatment of pernicious anemia and the prevention and treatment of vitamin B12 deficiency arising from alcoholism, malabsorption, tapeworm infestation, celiac, hyperthyroidism, hepatic-biliary tract disease, persistent diarrhea, ileal resection, pancreatic cancer, renal disease, prolonged stress, vegan diets, macrobiotic diets or other restrictive diets. Also for the treatment of known or suspected cyanide poisoning.', '6221094504166', '', 13157, '2024-08-14', CURRENT_TIMESTAMP),
(18911, 'Felopress 2.5/2.5 mg 21 f.c. tab.', 'فيلوبريس 2.5 / 2.5 مجم 21 قرص', '', '33', 'Felodipine+ramipril', 'Liptis', 'Tab', 'أقراص', '', 'Antihypertensive', '2.5 mg', 'about felodipine a selective calcium channel blocker dihydropyridine derivative anti hypertensive. mechanism of action of felodipine felodipine is a vasoselective long acting dihydropyridine ca channel blocker. it exerts antihypertensive antianginal actio', '', '', 1151, '2022-07-11', CURRENT_TIMESTAMP),
(1521, 'Zunity 10 sachets', 'زونيتي 10 اكياس', '', '160', 'Lactobacillus+bovine colostrum+lactoferrin+zinc+selenium+vitamin e+vitamin c', 'Multi-insight pharma', 'Sachet', 'أكياس', '', 'Probiotics & multi-vitamins', '', '', '', '', 902, '2022-09-19', CURRENT_TIMESTAMP),
(8382, 'Moxipen 500mg 12 caps.', 'موكسيبن 500 مجم 12 كبسولة', '', '15', 'Amoxicillin', 'Misr', 'Cap', 'كبسولة', 'مضاد حيوي', 'Penicillins.monocomponent', '500mg', 'Amoxicillin alone is indicated to treat susceptible bacterial infections of the ear, nose, throat, genitourinary tract, skin, skin structure, and lower respiratory tract.[L11656,L11659] Amoxicillin is given with calvulanic acid to treat acute bacterial sinusitis, community acquired pneumonia, lower respiratory tract infections, acute bacterial otitis media, skin and skin structure infections, and urinary tract infections.[L11650,L7880,L11653] Amoxicillin is given with omeprazole in the treatment of _Helicobacter pylori_ (_H. pylori_) infection.[L9743,L11647]
Amoxicillin is used in combination with [vonoprazan] and [clarithromycin] as co-packaged triple therapy or in combination with [vonoprazan] as co-packaged dual therapy to treat _H. pylori_ infection in adults.[L41695]', '6221035012163', '', 4538, '2023-03-11', CURRENT_TIMESTAMP),
(28933, 'Valponex 200mg 40 enteric coated tabs.', 'فالبونكس 200مجم 40 اقراص', '', '39', 'Sodium valproate', 'Western pharmaceuticals industries', 'Tab', 'أقراص', '', 'Anti-epileptic.fatty acid', '200mg', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 723, '2022-07-27', CURRENT_TIMESTAMP),
(23069, 'Mucolase 5% syrup 120 ml', 'ميكوليز 5% شراب 120 مل', '', '6', 'Carboxymethylcysteine', 'Arab drug company.', 'Syrup', 'شراب', 'مذيب للبلغم يعمل على تقليل لزوجة المخاط في المجاري التنفسية مما يسهل خروجها عن طريق السعال', 'Mucolytic', '5%', '', '6223002147335', '', 1428, '2022-06-14', CURRENT_TIMESTAMP),
(17879, 'Doxorubicin ebewe 10 mg vial', 'دوكسوريبسين 2مجم/مل 10مجم فيال', '49.5', '103', 'Doxorubicin', 'Sandoz > b.p pharma', 'Vial', 'فيال', '', 'Antineoplastic', '10 mg', 'Doxorubicin is indicated for the treatment of neoplastic conditions like acute lymphoblastic leukemia, acute myeloblastic leukemia, Hodgkin and non-Hodgkin lymphoma, metastatic breast cancer, metastatic Wilms’ tumor, metastatic neuroblastoma, metastatic soft tissue and bone sarcomas, metastatic ovarian carcinoma, metastatic transitional cell bladder carcinoma, metastatic thyroid carcinoma, metastatic gastric carcinoma, and metastatic bronchogenic carcinoma.[L45231] Doxorubicin is also indicated for use as a component of adjuvant therapy in women with evidence of axillary lymph node involvement following resection of primary breast cancer.[L45231] For the liposomal formulation, doxorubicin is indicated for the treatment of ovarian cancer that has progressed or recurred after platinum-based chemotherapy, AIDS-Related Kaposi''s Sarcoma after the failure of prior systemic chemotherapy or intolerance to such therapy, and multiple myeloma in combination with bortezomib in patients who have not previously received bortezomib and have received at least one prior therapy.[L45226]', '', '', 889, '2025-02-03', CURRENT_TIMESTAMP),
(12182, 'Venoruton 300mg 20 caps.', 'فينوروتون 300مجم 20 كبسولة', '', '17', 'Rutoside', 'Novartis > glaxo smithkline', 'Cap', 'كبسولة', 'تقوية الاوردة الدموية -- تحسين الدورة الدموية -- تقليل الالام -- حالات الصدمات والكدمات', 'Vascular-protecting agent', '300mg', 'description a flavonol glycoside found in many plants including buckwheat; tobacco; forsythia; hydrangea; viola etc. it has been used therapeutically to decrease capillary fragility.', '6223002640393', '', 2044, '2022-12-14', CURRENT_TIMESTAMP),
(9780, 'Romix-s cream 50 gm', 'روميكس اس كريم 50 جم', '185', '220', '', 'Original group', 'Cream', 'كريم', '', 'Whitening topical', '50 gm', '', '', '', 726, '2025-01-18', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
