Pantoprazole for injection is indicated for the treatment of pathological hypersecretory conditions associated with Zollinger-Ellison Syndrome or other neoplastic conditions.[FDA label]
**Pantoprazole delayed-release oral suspension**:
**Short-Term Treatment of erosive esophagitis associated with gastroesophageal reflux disease (GERD)**
Indicated in adults and pediatric patients five years of age and above for the short-term treatment (up to 8 weeks) in the healing and symptomatic relief of erosive esophagitis. For adult patients who have not healed after 8 weeks of treatment, an additional 8-week course of pantoprazole may be considered. Safety of treatment beyond 8 weeks in pediatric patients has not been determined.[F3202]
**Maintenance of healing of erosive esophagitis**
Indicated for maintenance of healing of erosive esophagitis and reduction in relapse rates of daytime and nighttime heartburn symptoms in adult patients with GERD.[F3202]
**Pathological hypersecretory conditions including Zollinger-Ellison syndrome**
Indicated for the long-term treatment of the above conditions.[F3202]', '', '', 2407, '2025-09-02', CURRENT_TIMESTAMP),
(3289, 'Daktarin 2% oral gel 40 gm', 'دكتارين 40 جم جيل للفم', '33.5', '54', 'Miconazole', 'Janssen cilag > soficopharm', 'Gel', 'جل', 'مضاد لفطريات الفم', 'Antifungals.imidazoles', '2%', 'Miconazole is indicated for the local treatment of oropharyngeal candidiasis in adult patients and for the adjunctive treatment of diaper dermatitis complicated by candidiasis in immunocompetent patients aged four weeks and older.[L14021, L14024] Miconazole is available as both a suppository and cream for the treatment of vaginal yeast infections and the relief of associated vulvar itching and irritation.[L14027] Lastly, miconazole cream is effective in treating athlete''s foot (tinea pedis), jock itch (tinea cruris), ringworm infections (tinea corporis),[L14033] pityriasis (formerly tinea) versicolor,[A203633] and cutaneous candidiasis.[A203630]', '05413868107265', '', 11532, '2023-10-28', CURRENT_TIMESTAMP),
(22784, 'Minipress 2 mg 30 tab.', 'ميني بريس 2مجم 30 قرص', '', '7', 'Prazosin', 'Pfizer', 'Tab', 'أقراص', '', 'Antihypertensive.selective alpha 1 receptor blockers', '2 mg', 'This drug is indicated for the treatment of hypertension (high blood pressure). Prazosin can be given alone or given with other blood pressure-lowering drugs, including diuretics or beta-adrenergic blocking agents [FDA label].
Prazosin does not negatively impact lung function, and therefore may be used to manage hypertension in patients who are asthmatic or patients with chronic obstructive lung disease (COPD)[A176630].', '6221180000275', '', 1489, '2022-12-06', CURRENT_TIMESTAMP),
(14027, 'Amoxycillin 500mg 10 caps b.p.2013', 'اموكسيسيلين 500 مجم 10 كبسولة', '', '7', 'Amoxicillin', 'Arab drug company.', 'Cap', 'كبسولة', '', 'Penicillins.monocomponent', '500mg', 'Amoxicillin alone is indicated to treat susceptible bacterial infections of the ear, nose, throat, genitourinary tract, skin, skin structure, and lower respiratory tract.[L11656,L11659] Amoxicillin is given with calvulanic acid to treat acute bacterial sinusitis, community acquired pneumonia, lower respiratory tract infections, acute bacterial otitis media, skin and skin structure infections, and urinary tract infections.[L11650,L7880,L11653] Amoxicillin is given with omeprazole in the treatment of _Helicobacter pylori_ (_H. pylori_) infection.[L9743,L11647]
Amoxicillin is used in combination with [vonoprazan] and [clarithromycin] as co-packaged triple therapy or in combination with [vonoprazan] as co-packaged dual therapy to treat _H. pylori_ infection in adults.[L41695]', '6221060000470', '', 1158, '2022-12-01', CURRENT_TIMESTAMP),
(25381, 'Pross hair serum 120 ml', 'بروس سيرم للشعر 120 مل', '175', '240', 'Dimethicone+oils(silicone+cedar wood+jojoba+lavender+wheat germ+olive+almond+ grape seed)+ginseng ex', 'Hi-care > roventis pharma', 'Serum', 'سيروم', '', 'Hair care', '120 ml', '**indications ï-non-inherited alopecia. ï-dry brittle fragile and damaged hair. ï-weak hair growth rates and split ends. ï-overstressed hair due to environmental factors hair dyes and harsh chemicals. **directions for use apply a suitable amount of the se', '6224007611432', '', 2618, '2025-05-02', CURRENT_TIMESTAMP),
(23905, 'Nuxe sun melting cream spf 50 - 50 ml', 'نوكس صن كريم 50مل', '419', '485', '', 'Nuxe laboratory > biotech egypt', 'Cream', 'كريم', '', 'Skin care', '50 ml', 'this sun cream with sun and water flowers protects from appearance of visible signs of sun-induced premature skin aging and helps you achieve a perfect tan. specially formulated for the delicate skin on your face it is easily absorbed and does not leave a', '', '', 612, '2023-09-06', CURRENT_TIMESTAMP),
(22690, 'Miacalcic 50 i.u/ml 5 amp. for i.m./i.v./s.c inj.', 'مياكالسيك 50وحدة/مل 5 امبول حقن عضل/وريد/تحت الجلد', '', '76', 'Calcitonin', 'Novartis', 'Inj', 'حقن', '', 'Osteoporosis.antiresorptives', '', 'Investigated for use/treatment in myocardial infarction, heart disease, and asthma.', '6223002641901', '', 1641, '2023-04-13', CURRENT_TIMESTAMP),
(4587, 'Ezanal top. cream 5 gm', 'ايزانال كريم 5 جم', '', '8', 'Lidocaine+prilocaine', 'Multi-apex', 'Cream', 'كريم', 'مخدر موضعي', 'Local anaesthetic', '5 gm', '', '', '', 1090, '2022-05-19', CURRENT_TIMESTAMP),
(8263, 'Mobitil 15mg 10 tab.', 'موبيتيل 15مجم 10 اقراص', '23.5', '36', 'Meloxicam', 'Mup', 'Tab', 'أقراص', 'مسكن وخافض للحرارة ومضاد للالتهاباتويستخدم فى علاج التهاب المفاصل', 'Nsaid.oxicam', '15mg', 'Meloxicam is indicated for the symptomatic treatment of arthritis and osteoarthritis.  In addition, it is indicated for the pauciarticular and polyarticular course of Juvenile Rheumatoid Arthritis (JRA) in patients aged 2 years old or above.[L11398] Off-label uses include the treatment of dental or post-surgical pain. In addition to the above, meloxicam has also been studied in the treatment of neuropathic pain. [A190189]
Meloxicam, in combination with [bupivacaine], is indicated for postsurgical analgesia in adult patients for up to 72 hours following soft tissue surgical procedures, foot and ankle procedures, and other orthopedic procedures in which direct exposure to articular cartilage is avoided.[L50427]', '6221508016414', '', 10293, '2024-11-21', CURRENT_TIMESTAMP),
(16690, 'Complete hair lotion 200 ml', 'كومبليت لوشن للشعر 200 مل', '250', '300', 'Panthenol+salicylic acid+piroctone olamine+aloe vera+cetrimide', 'Hi-care > health well egypt', 'Lotion', 'لوشن', '', 'Hair care', '200 ml', 'application: apply a suitable amount to the scalp and rub gently for 30 seconds once or twice daily.', '', '', 1224, '2025-01-06', CURRENT_TIMESTAMP),
(23741, 'Normotensil 2mg 7 f.c. tabs.', 'نورموتنسيل 2مجم 7 اقراص', '', '6', 'Lacidipine', 'Unipharma co.', 'Tab', 'أقراص', 'علاج ارتفاع ضغط الدم', 'Antihypertensive.selective calcium channel blocker', '2mg', 'Indicated for the treatment of hypertension either alone or in combination with other antihypertensive agents, including β-adrenoceptor antagonists, diuretics, and ACE-inhibitors [L1126].', '', '', 951, '2022-07-15', CURRENT_TIMESTAMP),
(12845, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 739, '2022-07-08', CURRENT_TIMESTAMP),
(28323, 'Topicrem ultra-moisturizing hand cream 75 ml', 'توبيكريم ترطيب فائق لليدين كريم 75مل', '', '169', '', 'Laboratoire dermatologique > spring', 'Cream', 'كريم', '', 'Skin care', '75 ml', '*suitable for all ages. *for sensitive skin. *use twice on face and nick.', '', '', 808, '2022-08-01', CURRENT_TIMESTAMP),
(2440, 'Cetal sinus 20 caplets', 'سيتال سينس 20 قرص', '21', '36', 'Paracetamol(acetaminophen)+pseudoephedrine', 'Eipico', 'Cap', 'كبسولة', 'علاج نزلات البرد والانفلونزا -- تقليل الاحتقان والرشح و العطس والزكام -- تقليل الالام والالتهابات', 'Cold products', '', 'about paracetamol acetanilide derivative non narcotic analgesic antipyretic. mechanism of action of paracetamol paracetamol has analgesic and antipyretic action. it is more active on cyclo-oxygenase enzyme in brain. peripherally it is a poor inhibitor of', '6221032118790', '', 7674, '2024-12-06', CURRENT_TIMESTAMP),
(6047, 'Mirfenacin mr 5/50 mg 30 f.c. tabs.', 'ميرفيناسين ام ار 5/50مجم 30 قرص', '339', '411', 'Solifenacin+mirabegron', 'Hikma', 'Tab', 'أقراص', '', 'Urinary incontinence.antispasmodics.muscarinic antagonists', '50 mg', '', '6221000011009', '', 1744, '2025-11-23', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(17127, 'Daviken 250mg/5ml syrup 120ml', 'دافيكين 250 مجم / 5 مل شراب 120 مل', '', '13', 'Sodium valproate', 'Amoun', 'Syrup', 'شراب', '', 'Anti-epileptic.fatty acid', '250mg', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 661, '2022-07-30', CURRENT_TIMESTAMP),
(15778, 'Cangout 100mg 10 tab.', 'كانجاوت 100مجم 10 اقراص', '', '10', 'Sulfinpyrazone', 'Multi-apex', 'Tab', 'أقراص', '', 'Antigout.analgesic', '100mg', 'For the treatment of gout and gouty arthritis.', '', '', 1262, '2022-07-01', CURRENT_TIMESTAMP),
(17005, 'Cymbalta 30 mg 28 caps.', 'سيمبالتا 30مجم 28 كبسولة', '305', '399', 'Duloxetine', 'Eli lilly', 'Cap', 'كبسولة', 'مضاد اكتئاب . مهديء', 'Psychiatric.antidepressants', '30 mg', '**Indicated** for:
1) Management of Major Depressive Disorder.[label]
2) Management of Generalized Anxiety Disorder.[label]
3) Management of diabetic peripheral neuropathy.[label]
4) Management of fibromyalgia.[label]
5) Management of chronic musculoskeletal pain.[label]
6) Management of osteoarthritis of the knee in adults.[L6364]
7) Management of chronic lower back pain in adults.[L6364]
8) Management of stress urinary incontinence in adult women.[L6367]
**Off-label** uses include:
1) Management of chemotherapy-induced peripheral neuropathy.[A178603]
2) Management of stress urinary incontinence in adult men after prostatectomy until recovery is complete.[L6370]', '', '', 5858, '2024-11-06', CURRENT_TIMESTAMP),
(1197, 'Tribteston-z 30 caps', 'تريبتستون زد 30 كبسولة', '', '90', 'Tributes terrestrial extract+zinc', 'Alphabet pharma', 'Cap', 'كبسولة', '', 'Aphrodisiac', '', '', '', '', 1332, '2022-10-07', CURRENT_TIMESTAMP),
(2279, 'Cefrone 500 mg i.m/i.v vial', 'سيفرون 500 مجم فيال', '14', '22', 'Cefoperazone', 'Mup', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '500 mg', 'Indicated for the treatment of following infections caused by susceptible bacteria:[label]
1) Respiratory tract infections caused by _S. pneumoniae_, _H. influenzae_, _S. aureus_ (penicillinase and non-penicillinase producing strains), _S. pyogenes_ (Group A beta-hemolytic streptococci), _P. aeruginosa_, _Klebsiella pneumoniae_, _E. coli_, _Proteus mirabilis_, and Enterobacter species.
2) Peritonitis and other intra-abdominal infections caused by _E. coli_, _P. aeruginosa_, and anaerobic gram-negative bacilli (including _Bacteroides fragilis_).
3) Bacterial septicemia caused by _S. pneumoniae_, _S. agalactiae_, _S. aureus_, _Pseudomonas aeruginosa_, _E. coli_, _Klebsiella_ spp., _Klebsiella pneumoniae_, Proteus species (indole-positive and indole-negative), _Clostridium_ spp. and anaerobic gram-positive cocci.
4) Infections of the skin and skin structures caused by S. aureus (penicillinase and non-penicillinase producing strains), S. pyogenes, and P. aeruginosa.
5) Pelvic Inflammatory Disease, Endometritis, and Other Infections of the Female Genital Tract caused by N. gonorrhoeae, S. epidermidis, S. agalactiae, E. coli, Clostridium spp., Bacteroides species (including Bacteroides fragilis), and anaerobic gram-positive cocci.
6) Urinary tract infections caused by Escherichia coli and Pseudomonas aeruginosa.
7) Enterococcal Infections. Although cefoperazone has been shown to be clinically effective in the treatment of infections caused by enterococci in cases of peritonitis and other intra-abdominal infections, infections of the skin and skin structures, pelvic inflammatory disease, endometritis and other infections of the female genital tract, and urinary tract infections, the majority of clinical isolates of enterococci tested are not susceptible to cefoperazone but fall just at or in the intermediate zone of susceptibility, and are moderately resistant to cefoperazone. However, _in vitro_ susceptibility testing may not correlate directly with _in vivo_ results. Despite this, cefoperazone therapy has resulted in clinical cures of enterococcal infections, chiefly in polymicrobial infections. Cefoperazone should be used in enterococcal infections with care and at doses that achieve satisfactory serum levels of cefoperazone.', '', '', 917, '2024-11-03', CURRENT_TIMESTAMP),
(17270, 'Depapalin 75mg 20 caps.', 'ديبابالين 75 مجم 20 كبسولة', '', '46', 'Pregabalin', 'Debeiky > rameda', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '75mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 764, '2022-07-18', CURRENT_TIMESTAMP),
