(6718, 'Jedcovate 0.05% cream', 'جدكوفيت كريم 0.05%', '', '6', 'Clobetasol propionate', 'Jedco int. co. for pharmaceuticals', 'Cream', 'كريم', '', 'Topical adenocorticoid', '0.05%', 'Clobetasol propionate is indicated to treat moderate to severe plaque psoriasis[L11818,L11821,L11824] as well as inflammatory and pruritic manifestations of corticosteroid-responsive dermatoses.[L11815,L11827]
The ophthalmic suspension of clobetasol propionate is indicated for the treatment of post-operative inflammation and pain following ocular surgery.[L50657]', '', '', 766, '2022-08-20', CURRENT_TIMESTAMP),
(17059, 'Daivobet topical gel 30 gm', 'دايفوبيت جل موضعي 30 جرام', '', '182', 'Betamethasone+calcipotriol(calcipotriene)', 'Leo pharmaceutical products', 'Gel', 'جل', 'علاج موضعي لصدفية فروة الرأس عند البالغين وعلى جلد مناطق الجسم الأخرى لعلاج الصدفية الخفيفة إلى المعتدلة (الصدفية الشائع) عند البالغين.', 'Psoriasis', '30 gm', 'uses: this medication is used to treat psoriasis. it helps to reduce the redness thickening and scaling of the skin that occurs with this condition. healthy skin lowers your risk for infection and protects you against the environment. this product contain', '', '', 6008, '2022-06-18', CURRENT_TIMESTAMP),
(3736, 'Rotanid calamine soap 60 gm', 'روتانيد كالامين صابون', '', '30', 'Zinc oxide+glycerin+panthenol+calamine+salicylic acid', 'Rotex pharma', 'Soap', 'صابون', '', 'Anti-inflammatory', '60 gm', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 1293, '2022-12-04', CURRENT_TIMESTAMP),
(31714, 'Aaa', 'ششش', '', '35', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 517, '2023-05-04', CURRENT_TIMESTAMP),
(28792, 'Lucente capella hair lotion 100 ml', 'لوسينت كابيلا لوشن للشعر 100 مل', '', '450', 'Procapil+ginkgo biloba+saw palmetto+quaterinized panthenol', 'Macro group pharmaceuticals', 'Cap', 'كبسولة', '', 'Hair care', '100 ml', '', '', '', 761, '2024-06-11', CURRENT_TIMESTAMP),
(29144, 'Verdenodeb 20mg 4 f.c. tabs.', 'فيردينوديب 20مجم 4 اقراص', '28.8', '53', 'Vardenafil', 'Debeiky > novell pharma', 'Tab', 'أقراص', '', 'Tonic for men', '20mg', 'Vardenafil is indicated for the treatment of erectile dysfunction.[L45563,L45568,L45573]', '', '', 3558, '2025-08-15', CURRENT_TIMESTAMP),
(22060, 'Losec 20mg 7 caps.', 'لوزيك 20 مجم 7 كبسولات', '', '32', 'Omeprazole', 'Astra zeneca', 'Cap', 'كبسولة', '', 'Peptic ulcer.proton pump inhibitor', '20mg', 'Omeprazole, according to the FDA label [FDA label] is a proton pump inhibitor (PPI) used for the following purposes:
• Treatment of active duodenal ulcer in adults 
• Eradication of Helicobacter pylori to reduce the risk of duodenal ulcer
recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6223003270438', '', 1023, '2022-12-06', CURRENT_TIMESTAMP),
(4128, 'Isotretinoin 20mg 30 soft gelatin caps.', 'ايزوتريتينوين 20مجم 30 كبسولة', '282', '372', 'Isotretinoin', 'Ranbaxy', 'Cap', 'كبسولة', '', 'Anti-acne', '20mg', 'Isotretinoin is indicated to treat severe recalcitrant nodular acne and patients ≥12 years enrolled in the iPLEDGE program.[Label,L6579]', '6224009052516', '', 2093, '2024-06-14', CURRENT_TIMESTAMP),
(25292, 'Procidal 8.6% topical solution 200 ml', 'بروسيدال 8.6% لوشن 200مل', '', '8', 'Povidone- iodine', 'Global napi pharmaceuticals', 'Solution', 'محلول', '', 'Antiseptic', '8.6%', 'about povidone iodine iodine preparation external broad microbicidal spectrum antiseptic. mechanism of action of povidone iodine povidone iodine is an iodophore antiseptic and is a microbicidal drug. it releases iodine from its complex and produces pharma', '', '', 815, '2022-07-10', CURRENT_TIMESTAMP),
(21303, 'Kemirica 300mg 10 caps.', 'كيميريكا 300مجم 10 كبسولات', '', '60', 'Pregabalin', 'Chemipharm', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '300mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '6222006500856', '', 2047, '2023-01-24', CURRENT_TIMESTAMP),
(23866, 'Nuxe cleansing milk with rose petals 200 ml', 'نوكس 200مل', '', '265', '', 'Nuxe laboratory > biotech egypt', 'Unknown', 'غير محدد', '', 'Skin care', '200 ml', 'this rose petal cleansing milk for face and eyes cleanses and removes make-up protecting skin from becoming dry. cleansing milk key benefit : a rich texture adapted to dry skin easy to use delivering comfort to your face. use apply your cleansing milk wit', '', '', 559, '2022-08-03', CURRENT_TIMESTAMP),
(2680, 'Citra 20 lozenges', 'اقراص سيترا للاستحلاب 2شريط', '', '14', '', 'Eva pharma', 'Lozenges', 'استحلاب', '', 'Vitamin c', '', '', '6223002450176', '', 1743, '2022-12-03', CURRENT_TIMESTAMP),
(13672, 'Alerid 10 mg 20 chewable tab.', 'اليريد 10مجم 20 قرص للمضغ', '', '11', 'Cetirizine', 'Global napi pharmaceuticals', 'Tab', 'أقراص', '', 'Antihistamine.antiallergy', '10 mg', '**Seasonal Allergic Rhinitis**: Indicated for the relief of symptoms associated with seasonal allergic rhinitis caused by allergens such as ragweed, grass and tree pollens in adults and children 2 years of age and above. Symptoms treated effectively include sneezing, rhinorrhea, nasal pruritus, ocular pruritus, tearing, and redness of the eyes [FDA label]. 
**Perennial allergic rhinitis**: This drug is indicated for the relief of symptoms associated with perennial allergic rhinitis due to allergens including dust mites, animal dander, and molds in adults and children 6 months of age and older. Symptoms treated effectively include sneezing, rhinorrhea, postnasal discharge, nasal pruritus, ocular pruritus, and tearing [FDA label]. 
**Chronic urticaria**: Cetirizine is indicated for the treatment of the uncomplicated skin manifestations of chronic idiopathic urticaria in adults and children 6 months of age and older. It markedly reduces the occurrence, severity, and duration of hives and significantly reduces pruritus [FDA label].', '6223002142248', '', 1823, '2022-12-01', CURRENT_TIMESTAMP),
(3697, 'Diltiazem 90mg s.r. 10 cap.', 'ديلتيازيم 90مجم 10 كبسولات ممتد المفعول', '', '8', 'Diltiazem', 'Eipico', 'Cap', 'كبسولة', '', 'Antihypertensive.nonselective calcium channel blocker', '90mg', '**Oral**
Indicated for the management of hypertension, to lower blood pressure, alone or in combination with other antihypertensive agents.[L10556]
Indicated for use to improve exercise tolerance in patients with chronic stable angina.[L10556]
Indicated for the management of variant angina (Prinzmetal''s angina).[L6298]
**Intravenous**
Indicated for the short-term management of atrial fibrillation or atrial flutter for temporary control of rapid ventricular rate.[L6292]
Indicated for the rapid conversion of paroxysmal supraventricular tachycardias (PSVT) to sinus rhythm. This includes AV nodal reentrant tachycardias and reciprocating tachycardias associated with an extranodal accessory pathway such as the WPW syndrome or short PR syndrome.[L6292]
**Off-label**
Indicated for off-label uses in anal fissures (as topical formulation), migraine prophylaxis, cramps in lower leg related to rest, pulmonary hypertension,[L6289] idiopathic dilated cardiomyopathy, and proteinuria associated with diabetic nephropathy.[L6298]', '6221032131669', '', 1446, '2023-08-01', CURRENT_TIMESTAMP),
(10139, 'Sacrofer 100mg/5ml 5 amp for i.v. inj.', 'ساكروفير 100مجم/5مل 5 امبولات', '190', '275', 'Iron', 'Amoun', 'Inj', 'حقن', 'علاج حالات الانيميا ونقص الحديد', 'Anemia.iron supplement', '100mg', 'For treatment of patients with documented iron deficiency in whom oral administration is unsatisfactory or impossible. Also used to replenish body iron stores in Non-Dialysis Dependent-Chronic Kidney Disease (NDD-CKD) patients receiving or not receiving erythropoietin and in Hemodialysis Dependent (HDD-CKD) and Peritoneal Dialysis Dependent (PDD-CKD) - Chronic Kidney Disease patients receiving an erythropoietin.', '6221025020178', '', 23313, '2024-09-05', CURRENT_TIMESTAMP),
(9373, 'Oriplex 30 sugar coated tab.', 'اوريبلكس 30 قرص', '3.35', '14', 'Calcium pantothenate+nicotinamide+vitamin b1+vitamin b2+vitamin b6', 'Arab drug company.', 'Tab', 'أقراص', 'مصدر لفيتامين ب -- يساعد علي تحسين وظائف الاعصاب -- يساعد علي تحسين الذاكرة -- يستخدم لمرضي السكر للوقاية من التهاب الاعصاب الشديد المصاحب لنقص فيتامين ب', 'Vitamins', '', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 4269, '2023-08-15', CURRENT_TIMESTAMP),
(31057, 'Oxilab sachets 30 sachet for women(150 gm)', 'اوكسي لاب 30 كيس للسيدات 150 جم', '279', '350', 'L-carnitine+acetyl l-carnitine+l-arginine+n-acetyl-cysteine+selenium+zinc+iron+copper+folic acid+vitamin b12+vitamin c+vitamin e vitamin b6+vitamin d3+vitamin b5+beta-carotene', 'Brand nutrition > drug lab pharmaceuticals', 'Sachet', 'أكياس', '', 'Fertility supplement', '150 gm', 'oxi lab sachets *high quality fertility supplement designed for women who want to enhance their fertility and reproductive health *(16 active ingredients:amino acids minerals vitamins) *ingredients l-carnitine acetyl-l-carnitine l-arginine n-acetyl-cystei', '6224011629034', '', 1571, '2025-03-09', CURRENT_TIMESTAMP),
(29335, 'Villa borghini greasy hair shampoo 200 ml', 'فيلا بورجيني شامبو للشعر 200مل', '', '195', '', 'Villa borghini s.r.l > spring', 'Amp', 'أمبول', '', 'Hair care', '200 ml', 'description greasy hair shampoo thanks to the combination of specific active ingredients cleans and sanitizes very delicately all kind of hair and scalp even the most sensitive ones. the hair remain clean soft and bright for days from the first applicatio', '', '', 774, '2022-08-03', CURRENT_TIMESTAMP),
(24616, 'Pearla soap 100 gm', 'بيرلا صابون 100جم', '32.95', '50', '', 'Egyptian company for cosmetics > pearla pharm co.', 'Soap', 'صابون', '', 'Soap', '100 gm', 'emollient soap', '', '', 702, '2023-09-03', CURRENT_TIMESTAMP),
(19373, 'Four mix syrup 120 ml', 'فور ميكس شراب 120 مل', '', '8', 'Guava leaves+thyme leaves+fennel', 'Sigma > pharma cure pharmaceuticals', 'Syrup', 'شراب', '', 'Cough drugs', '120 ml', '', '6224000651107', '', 679, '2022-07-21', CURRENT_TIMESTAMP),
(17027, 'Cytarabine stada 20mg/ml (100mg) vial', 'سيتارابين ستادا 20 مجم / مل فيال', '', '24', 'Cytarabine', 'Cell pharm gmbh-germany > germa pharm', 'Vial', 'فيال', '', 'Antiviral.nucleoside', '20mg', 'For the treatment of acute non-lymphocytic leukemia, acute lymphocytic leukemia and blast phase of chronic myelocytic leukemia.
Cytarabine is indicated in combination with [daunorubicin] for the treatment of newly-diagnosed therapy-related acute myeloid leukemia (t-AML) or AML with myelodysplasia-related changes (AML-MRC) in adults and pediatric patients 1 year and older.[L32843]', '', '', 1180, '2022-07-29', CURRENT_TIMESTAMP),
(17058, 'Daisy dent mouth wash 120 ml', 'ديزي دنت غسول للفم 120 مل', '', '13', '', 'El-helou perfumes & cosmetics > capital pharma', 'Mouth wash', 'غسول للفم', '', 'Oral care', '120 ml', '', '', '', 642, '2022-08-03', CURRENT_TIMESTAMP),
(19442, 'Aaa', 'ششش', '', '15', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 794, '2022-08-26', CURRENT_TIMESTAMP),
(18123, 'Egynir 300mg 10 cap', 'ايجينير 300مجم 10 كبسولات', '69.5', '100', 'Cefdinir', 'Sigma tec pharmaceutical industries > egyphar', 'Cap', 'كبسولة', '', 'Antibiotic.cephalosporin.third-generation', '300mg', 'Cefdinir is indicated to treat acute bacterial otitis media, acute maxillary sinusitis, community-acquired (CA) pneumonia, acute bacterial exacerbations of chronic bronchitis, pharyngitis/tonsillitis, and uncomplicated skin and skin structure infections in children and adults.[L7330,A180739]
The organisms susceptible to cefdinir have been listed below in addition to their associated clinical condition that may be treated with cefdinir.[L7330] Various beta-lactamase producing organisms may be treated, as indicated in certain sections below.
**Respiratory**
