(19967, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 797, '2022-07-22', CURRENT_TIMESTAMP),
(26141, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 735, '2022-07-09', CURRENT_TIMESTAMP),
(17666, 'Dilozole susp. 120 ml', 'ديلوزول معلق 120 مل', '', '6', 'Diloxanide furoate+metronidazole', 'Alexandria', 'Susp', 'معلق', '', 'Antiprotozoal.nitroimidazole', '120 ml', 'Diloxanide is used alone as a primary agent in the treatment of asymptomatic (cyst passers) intestinal amebiasis caused by Entamoeba histolytica. Diloxanide may also be used concurrently, or sequentially, with other agents such as the nitroimidazoles (eg. metronidazole) in the treatment of invasive or extraintestinal forms of amebiasis.', '6223000176351', '', 962, '2023-01-13', CURRENT_TIMESTAMP),
(20948, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '6223002212422', '', 656, '2023-02-06', CURRENT_TIMESTAMP),
(7112, 'Stomezyme 20 film coated tablets', 'ستوميزايم 20 قرص', '', '230', 'Papin 480 mg - bromelin 390 mg - pancreatin 300 mg - trypsin 144 mg - rutin 201 mg - zinc 15 mg - selenium 0.06 mg', 'Sejo pharma', 'Tablet', 'أقراص', '', 'Digestive enzymes & powerful anti inflammatory', '', '', '', '', 1043, '2025-08-24', CURRENT_TIMESTAMP),
(7480, 'Locasten 1% top. solution 20 ml', 'لوكاستن 1% محلول 20 مل', '11', '18', 'Clotrimazole', 'Alexandria', 'Solution', 'محلول', '', 'Antifungals.imidazoles', '1%', '**Topical preparations**
Clotrimazole topical cream is indicated for the topical treatment of the following dermal infections [F3088], [F3121]:
Tinea pedis, tinea cruris, and tinea corporis due to _Trichophyton rubrum_, _Trichophyton mentagrophytes_, _Epidermophyton floccosum_
Candidiasis due to _Candida albicans_
Tinea versicolor due to _Malassezia furfur_
Diaper rash infected by _Candida albicans_
In some preparations, clotrimazole may be combined with betamethasone dipropionate, a corticosteroid [F3121]. 
**Oral preparations**
The oral troche preparation is indicated for the local treatment of oropharyngeal candidiasis [FDA label].  It is also indicated as a prophylactic drug to reduce the incidence of oropharyngeal candidiasis in patients immunocompromised by conditions such as chemotherapy, radiotherapy, or steroid therapy utilized in the treatment of leukemia, solid tumors, or renal transplantation [FDA label]. Troche preparations are not indicated for the treatment of any systemic mycoses [FDA label].', '6223000178904', '', 1515, '2024-09-15', CURRENT_TIMESTAMP),
(622, 'Amostigmine 0.5mg/ml 3amp', 'اموستجمين0.5مجم/مل 3امبولات', '', '5', 'Neostigmine', 'Amoun', 'Amp', 'أمبول', 'علاج انتفاخ البطن بعد العمليات الجراحية -- علاج احتباس البول', 'Para sympathomimtic', '0.5mg', 'Neostigmine is used for the symptomatic treatment of myasthenia gravis by improving muscle tone.', '6221025007421', '', 1026, '2022-12-01', CURRENT_TIMESTAMP),
(19399, 'Free nose propolis nasal spray (+12 year) 20 ml', 'فري نوز بروبوليس(+12 سنة) بخاخ 20 مل', '', '89', 'Saline solution+propolis+thyme+eucalyptus', 'Pharmalink s.l. > aug pharma', 'Spray', 'بخاخ', 'علاج حالات احتقان الأنف واحتقان الجيوب الأنفية -- لترطيب تجاويف الأنف في البيئات الجافة -- تعزيز فعالية مزيلات الاحتقان العلاجية والحد من استخدامها', 'Nasal decongestant', '20 ml', 'nasal decongestant with propolis and thyme. from 12 year and above. *recommended dose: 1 or 2 sprays 3 times a day', '', '', 1498, '2022-06-01', CURRENT_TIMESTAMP),
(32448, 'Astin 10 mg 20 f.c. tabs.', 'استين 10مجم 20 قرص', '28.8', '46', 'Ebastine', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', '', 'Anti-histamine.anti-allergy', '10 mg', 'about ebastine second generation long-acting and selective h1 antagonist non-sedative antihistamine. mechanism of action of ebastine drug and its active metabolite is selective peripheral histamine h1 receptor antagonist. thus it prevents the attachment o', '6223004190964', '', 837, '2025-11-03', CURRENT_TIMESTAMP),
(2008, 'Ferblod advance 120 ml syrup', 'فيرب لود ادفانس شراب 120 مللي', '', '45', 'Iron+vitamin c+zinc+b1+b2+b3+b6+b12+folic acid+manganese+lysine+iodine+copper+malt extract+pantothenic acid', 'Astramed', 'Syrup', 'شراب', '', 'Multivitamin', '120 ml', '', '', '', 811, '2025-01-02', CURRENT_TIMESTAMP),
(22240, 'Malsa 11.5 % topical cream 30 gm', 'ملسا11.5% كريم لتأخير نمو الشعر 30جم', '', '200', 'Eflornithine', 'Debeiky > igea pharma', 'Cream', 'كريم', '', 'Hirsutism', '11.5 %', 'Eflornithine is indicated to reduce the risk of relapse in adult and pediatric patients with high-risk neuroblastoma (HRNB) who have demonstrated at least a partial response to prior multiagent, multimodality therapy including anti-GD2 immunotherapy.[L49288]  It was also previously indicated for the treatment of female hirsutism and African trypanosomiasis but has since been discontinued.[L49318]', '', '', 2852, '2022-07-15', CURRENT_TIMESTAMP),
(26033, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 582, '2022-09-20', CURRENT_TIMESTAMP),
(32937, 'Hacaci plus 30 tabs.', 'هاكاشي بلس 30 قرص', '70', '78', 'Calcium+magnesium+zinc+vitamin d3', 'Medtronic', 'Tab', 'أقراص', 'مكمل غذائى لدعم صحة العظام والوقاية من الكساح وهشاشة العظام وتخفيف توتر العضلات', 'Calcium supplement', '', 'calcium deficiency', '6225000501430', '', 1582, '2025-07-06', CURRENT_TIMESTAMP),
(33067, 'La tree beaute facial wash 200 ml', 'لا تري بيوت غسول 200 مل', '115', '154', '', 'Egyptian co. for cosmetics > la tree beaute', 'Facial wash', 'غسول للوجه', '', 'Skin care', '200 ml', '', '', '', 1139, '2025-08-03', CURRENT_TIMESTAMP),
(21428, 'Kipro 30 tabs', 'كيبرو 30 قرص', '', '60', 'Vitamin d3+vitamin k2+magnesium', 'Healthy tech pharma > nutr-med pharma', 'Tab', 'أقراص', 'فيتامينات متعددة لعلاج نقص فيتامين دال -- وهشاشة العظام', '', '', 'For the treatment of vitamin A deficiency.', '', '', 1138, '2022-05-12', CURRENT_TIMESTAMP),
(18238, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 798, '2022-07-20', CURRENT_TIMESTAMP),
(3988, 'Ectomethrin 2.5 % oint. 20 gm', 'اكتومثرين 2.5% مرهم 20 جم', '12', '21', 'Permethrin', 'Misr > apc (arab perfumes chemicals and pharmaceutical co.)', 'Oint', 'مرهم', '', 'Scabicide', '2.5 %', 'For the treatment of infestation with <i>Sarcoptes scabiei</i> (scabies).', '6221035007046', '', 1152, '2024-12-05', CURRENT_TIMESTAMP),
(7489, 'Relaxospasm 30 mg 10 capsules', 'ريلاكسوسبازم 30 مجم 10 كبسولا', '', '27', 'Cyclobenzaprine', 'Eva pharma', 'Capsule', 'كبسولة', '', 'Cns.analgesic.skeletal muscle relaxant', '30 mg', 'Cyclobenzaprine is indicated as a short-term (2-3 weeks) adjunct therapy, along with rest and physical therapy, for relief of muscle spasm associated with acute, painful musculoskeletal conditions. It has not been found effective in the treatment of spasticity originating from cerebral or spinal cord disease, or spasticity in children with cerebral palsy.[L8408,L8411] Cyclobenzaprine is also occasionally used off-label for reducing pain and sleep disturbances in patients with fibromyalgia.[A184946]', '', '', 1093, '2025-09-22', CURRENT_TIMESTAMP),
(7446, 'Polyvance 60 gm gel', 'بوليفانس جل 60 جم', '60', '70', 'Menthol crystal + aescin + eucalyptus + tea tree oil + pomegranateseed oil + vitamin e + ginger + camphor + thymus oil + clove oil', 'Sobik pharma', 'Gel', 'جل', '', 'Massage gel', '60 gm', '', '', '', 2023, '2025-08-01', CURRENT_TIMESTAMP),
(31845, 'Foliraq 5000 mcg 30 capsules', 'فوليراك 5000مكجم 30 كبسولة', '', '45', 'Folic acid', 'Hp pharma', 'Capsule', 'كبسولة', '', 'Folate derivatives (b9) water soluble vitamins', '5000 mcg', 'Folic acid is indicated for the treatment of folic acid deficiency, megaloblastic anemia, and in anemias of nutritional origins, pregnancy, infancy, or childhood.', '', '', 703, '2023-05-04', CURRENT_TIMESTAMP),
(19472, 'Aaa', 'ششش', '', '32', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 736, '2022-10-18', CURRENT_TIMESTAMP),
(32370, 'Alejon facial moisturizer gel 75 gm', 'اليجون فاشيال مرطب للوجه جل 75 جم', '160', '210', '', 'Alejon co.', 'Gel', 'جل', '', 'Skin care', '75 gm', '', '6224010497450', '', 735, '2025-06-24', CURRENT_TIMESTAMP),
(4038, 'Egynir 125mg/5ml pd. for oral susp. 60ml', 'ايجينير 125مجم/5مل معلق 60 مل', '32.5', '49', 'Cefdinir', 'Egyphar', 'Susp', 'معلق', 'مضاد حيوي يستخدم لعلاج التهاب الجيوب الأنفية--التهاب الأذن الوسطى--التهاب اللوزتين--الالتهاب الرئوي.', 'Antibiotic.cephalosporin.third-generation', '125mg', 'Cefdinir is indicated to treat acute bacterial otitis media, acute maxillary sinusitis, community-acquired (CA) pneumonia, acute bacterial exacerbations of chronic bronchitis, pharyngitis/tonsillitis, and uncomplicated skin and skin structure infections in children and adults.[L7330,A180739]
The organisms susceptible to cefdinir have been listed below in addition to their associated clinical condition that may be treated with cefdinir.[L7330] Various beta-lactamase producing organisms may be treated, as indicated in certain sections below.
**Respiratory**
Acute bacterial exacerbations of chronic bronchitis caused by Haemophilus influenzae, Haemophilus parainfluenzae, Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
Community-acquired pneumonia caused by Haemophilus influenzae, Haemophilus parainfluenzae, Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
**Ear, nose, and throat** 
Acute bacterial otitis media caused by Haemophilus influenzae, Moraxella catarrhalis, and Streptococcus pneumoniae (penicillin-susceptible only)
Tonsillitis caused by Streptococcus pyogenes
Pharyngitis caused by Streptococcus pyogenes
Acute maxillary sinusitis caused by Haemophilus pneumoniae and Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
**Skin and skin structure infections**
Uncomplicated skin and skin structure infections caused by Staphylococcus aureus and Streptococcus pyogenes', '6224001026706', '', 1670, '2025-01-04', CURRENT_TIMESTAMP),
(31506, 'Totron 30 pieces', 'توترون 30 قطعة', '90', '105', 'Iron+lactoferrin+zinc+vitamin c', 'Brand nutrition > marketova pharma health care', 'Piece', 'قطعة', '', 'Multivitamins', '', 'iron deficiency anemia', '', '', 440, '2025-08-08', CURRENT_TIMESTAMP),
(32193, 'U-richi panthenol cream 20gm', 'يو ريتشي بانثينول كريم 20 جرام', '25', '30', 'Dexpanthenol+vitamin c+nicotinamide+liquorice extract+cocoa butter+grape seed oil+collagen+elastin+honey+zink oxide+raspberry extract+glutathione.', 'Egyptian company for cosmetics e.c.c. > u-richi', 'Cream', 'كريم', 'يتميز هذا المنتج بقدرته على توفير ترطيب عميق للبشرة، مما يجعلها أكثر نعومة وحيوية و تجديد البشرة وتحسين مرونتها بفضل مكوناته الطبيعية والمعززة لصحة البشرة مثل فيتامين C، الكولاجين، وزبدة الشيا', 'Skin care moisturizing cream', '20gm', '', '6224011774116', '', 14743, '2025-04-15', CURRENT_TIMESTAMP),
(28905, 'V2 - 24 caps.', 'في 2 24 كبسول', '', '7', 'Vitamins', 'Pharco', 'Cap', 'كبسولة', '', 'Vitamins', '', 'about vitamins vitamins are substances that are found in foods we eat. the term vitamin is derived from the words vital and amine because vitamins are required for life and were originally thought to be amines. all vitamins are not amines. vitamins are di', '6223000011379', '', 956, '2023-06-01', CURRENT_TIMESTAMP),
(29863, 'Zeina mouth wash 150 ml', 'زينة غسول للفم 150مل', '', '12', '', 'Hi-care > chemi health', 'Mouth wash', 'غسول للفم', '', 'Oral care', '150 ml', '', '', '', 774, '2022-07-09', CURRENT_TIMESTAMP),
(30829, 'Lipanthyl 145 mg 20 f.c.tabs.', 'ليبانتيل 145مجم 20 قرص', '94', '174', 'Fenofibrate(nanocrystal technology)', 'Abbott', 'Tab', 'أقراص', '', 'Antihyperlipidemic.fibrates', '145 mg', 'about fenofibrate fibric acid derivative ppara agonist antilipemic agent antigout. mechanism of action of fenofibrate it is prodrug which has greater ldl (low density lipoprotein) cholesterol lowering potential. it lowers circulating triglyceride levels b', '8002660043627', '', 6539, '2024-09-05', CURRENT_TIMESTAMP),
(7140, 'Imeglibright 500 mg 30 f.c. tabs.', 'ايميجليبرايت 500مجم 30 قرص', '', '159', 'Imeglimin', 'Al esraa pharmaceutical optima', 'Tab', 'أقراص', '', 'Anti-diabetic', '500 mg', '', '', '', 1132, '2025-08-24', CURRENT_TIMESTAMP),
(23594, 'Zyma colin 120 ml syrup', 'زيما كولين شراب 120 مل', '160', '280', 'Citicoline', 'Zyma pharma', 'Syrup', 'شراب', '', 'Supports normal brain functions', '120 ml', '', '', '', 2275, '2024-09-02', CURRENT_TIMESTAMP),
(18605, 'Ethoxa 250 mg 50 caps.', 'ايثوكسا 250 مجم 50 كبسولة', '', '56', 'Ethosuximide', 'Delta pharma', 'Cap', 'كبسولة', '', 'Anti-epileptic.succinimide', '250 mg', 'For the treatment of petit mal epilepsy.', '', '', 1084, '2022-08-04', CURRENT_TIMESTAMP),
