(12814, 'Jeroan syrup 100 ml', 'جيروان شراب 100 مل', '36', '45', 'Ginger root extract+fennel seed extract', 'Better health pharma', 'Syrup', 'شراب', 'مضاد لانتفاخ البطن. مضاد للمغص لاضطرابات الجهاز الهضمي', 'Anti flatulence anti-colic git disturbance', '100 ml', '', '', '', 2111, '2025-08-31', CURRENT_TIMESTAMP),
(29171, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 763, '2022-08-13', CURRENT_TIMESTAMP),
(19148, 'Flogencyl 1.5% gel', 'فلوجينسيل 1.5% جل', '', '12', 'Aescin', 'Expan pharm international-france > united partners company', 'Gel', 'جل', '', 'Anti-inflammatory', '1.5%', 'description: horse chestnut is a plant. its seed bark flower and leaves are used to make medicine indication: varicose veins and other circulatory problems (chronic venous insufficiency). taking horse chestnut seed extract can reduce some symptoms of poor', '', '', 906, '2022-07-20', CURRENT_TIMESTAMP),
(26078, 'Rifampin 150mg 10 caps. (debeiky)', 'ريفامبين 150مجم 10 كبسول', '7.5', '24', 'Rifampicin', 'Debeiky', 'Cap', 'كبسولة', '', 'Antibiotic.antituberculosis', '150mg', 'about rifampicin rifamycin derivative antituberculosis antibiotic. mechanism of action of rifampicin rifampicin is primarily bactericidal and has some bacteriostatic properties also. it acts by inhibiting dna dependent rna polymerase and thus stopping the', '', '', 735, '2025-08-19', CURRENT_TIMESTAMP),
(29317, 'Vilazover 40 mg 30 tabs', 'فيلازوفير 40مجم 30 قرص', '267', '338', 'Vilazodone', 'Averroes pharma-egypt', 'Tab', 'أقراص', 'مضاد للاكتئاب', 'Antidepressant.selective serotonin reuptake inhibitor', '40 mg', 'Vilazodone is approved for treatment of major depressive disorder.[Label,A38477,A177622]', '6224008179467', '', 4627, '2024-01-22', CURRENT_TIMESTAMP),
(3459, 'Dermalone cream 15 gm', 'درمالون15 جم كريم', '', '6', 'Econazole+triamcinolone', 'Smithkline beecham > glaxo smithkline', 'Cream', 'كريم', 'علاج للفطريات', '', '15 gm', 'side effects of econazole + triamcinolone acetonide 1.burning 2.itching pregnancy related information may be used breast feeding related information use with caution indications for econazole + triamcinolone acetonide skin infections about econazole synth', '', '', 1178, '2022-09-23', CURRENT_TIMESTAMP),
(24808, 'Pharmaceris h-sensitonin hair shampoo 250 ml', 'فارماسيريس - شامبو للشعر اتش سينسوتونين- 250 مل', '', '180', '', 'Laboratorium kosmetyczne dr irena eris sp. z o.o. > multitrade', 'Amp', 'أمبول', '', 'Hair care', '250 ml', 'indications: the shampoo is recommended for daily care of sensitive scalp prone to irritation and fine and delicate hair. use: apply the shampoo onto wet hair. rub it into the scalp to work up lather. leave it on for about 1-2 minutes. rinse thoroughly wi', '', '', 824, '2022-07-30', CURRENT_TIMESTAMP),
(15621, 'Calcao plus 10 chew. pieces', 'كالكاو بلس 10 قرص مضغ', '', '25', 'Calcium+vitamin d3+magnesium', 'Pharma zad > alwadi pharma', 'Piece', 'قطعة', '', 'Calcium supplement', '', '', '', '', 781, '2022-07-15', CURRENT_TIMESTAMP),
(24432, 'Ozurdex intravitreal implant 0.7 mg', 'اوزورديكس 0.7مجم زرعة للعين انترافيتريال امبلانت', '12428', '18,353', 'Dexamethasone', 'Allergan', 'Unknown', 'غير محدد', 'علاج فقدان الرؤية نتيجة انسداد اوردة العين -- علاج وذمة بقعية لمرضي السكر -- علاج التهاب الجزء الخلفيمن العين', 'Glucocorticoid', '0.7 mg', 'Dexamethasone and [ciprofloxacin] otic suspension is indicated for bacterial infections with inflammation in acute otitis media and acute otitis externa.[L10698] Intramuscular and intravenous injections are indicated for a number of endocrine, rheumatic, collagen, dermatologic, allergic, ophthalmic, gastrointestinal, respiratory, hematologic, neoplastic, edematous, and other conditions.[L10701] Oral tablets are indicated for the treatment of multiple myeloma.[L10710] An intravitreal implant is indicated for some forms of macular edema and non-infectious posterior uveitis affecting the posterior of the eye.[L10719] Various ophthalmic formulations are indicated for inflammatory conditions of the eye.[L10704,L10707,L10713,L10716,L10722,L10725]', '', '', 4187, '2024-11-09', CURRENT_TIMESTAMP),
(25583, 'Qv face purifying mask 75 gm', 'كيو في ماسك الوجه 75جم', '', '313', '', 'Ego pharmaceuticals pty ltd. > vamer pharma', 'Unknown', 'غير محدد', '', 'Skin care', '75 gm', 'pamper yourself with this luxurious clay-based face mask. even clear complexions need a bit of extra help sometimes.', '', '', 546, '2022-08-04', CURRENT_TIMESTAMP),
(10322, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 674, '2023-05-03', CURRENT_TIMESTAMP),
(11803, 'Aaa', 'ششش', '', '135', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 794, '2022-08-15', CURRENT_TIMESTAMP),
(7908, 'Nessrined 100 ml syrup', 'نسرينيد شراب 100 مل', '', '89', 'Iron+lysine+vit.c+a+b complex+zinc+cooper+manganese+folic acid', 'Prolife egypt', 'Syrup', 'شراب', '', 'Multivitamin & appetizer & source of protein', '100 ml', '', '', '', 903, '2025-11-05', CURRENT_TIMESTAMP),
(29961, 'Zinotraval 25mg/5ml syp. 120 ml', 'زينوترافيل 25مجم/5مل شراب 120مل', '', '10', 'Amitriptyline', 'Debeiky > pharmachemic pharmaceutical development', 'Unknown', 'غير محدد', '', 'Psychiatric.antidepressants', '25mg', 'This drug in indicated for the following conditions [FDA label]:
Major depressive disorder in adults [L46357]
Management of neuropathic pain in adults
Prophylactic treatment of chronic tension-type headache (CTTH) in adults
Prophylactic treatment of migraine in adults
Treatment of nocturnal enuresis in children aged 6 years and above when organic pathology, including spina bifida and related disorders, have been excluded and no response has been achieved to all other non-drug and drug treatments, including antispasmodics and vasopressin-related products. This product should only be prescribed by a healthcare professional with expertise in the management of persistent enuresis [FDA label]
Off-label uses: irritable bowel syndrome, sleep disorders, diabetic neuropathy, agitation, fibromyalgia, and insomnia', '', '', 870, '2022-07-09', CURRENT_TIMESTAMP),
(7563, 'Lotensine 25mg 20 tab.', 'لوتنسين 25مجم 20 قرص', '', '11', 'Captopril', 'Kahira', 'Tab', 'أقراص', '', 'Antihypertensive.ace', '25mg', 'For the treatment of essential or renovascular hypertension (usually administered with other drugs, particularly thiazide diuretics). May be used to treat congestive heart failure in combination with other drugs (e.g. cardiac glycosides, diuretics, &beta;-adrenergic blockers). May improve survival in patients with left ventricular dysfunction following myocardial infarction. May be used to treat nephropathy, including diabetic nephropathy.', '6221068000793', '', 994, '2022-12-06', CURRENT_TIMESTAMP),
(11881, 'Ultravist-300 vial 50 ml', 'الترافيست 300مجم 50مل فيال', '160', '375', 'Iopromide', 'Bayer schering > bayer healthcare', 'Vial', 'فيال', 'في اجراءات الاشعة - عامل مغاير لونيا', 'Radiographic procedures.contrast agent', '50 ml', 'Iopromide, as the product IOVIST, is approved by the FDA for use as an intra-arterial or intravenous X-ray contrast agent.[L46906] For intra-arterial administration, iopromide is indicated for cerebral arteriography, peripheral arteriography, coronary arteriography, left ventriculography, visceral angiography, and aortography in adults and radiographic evaluation of cardiac chambers and related arteries in pediatric patients aged 2 years and older.[L46906] For intravenous administration, iopromide is indicated for excretory urography in adults and pediatric patients aged 2 years and older, contrast Computed Tomography (CT) of the head and body (intrathoracic, intra-abdominal, and retroperitoneal regions) for the evaluation of neoplastic and non-neoplastic lesions in adults and pediatric patients aged 2 years and older, and contrast mammography to visualize known or suspected lesions of the breast in adults, as an adjunct following mammography and/or ultrasound.[L46906]
Iopromide is also approved by Health Canada as an intravascular contrasting agent, although the indications differ depending on the dosage. At 300 mg I/mL, iopromide is indicated for computed tomography (CT), excretory urography, pediatric excretory urography, renal arteriography, peripheral arteriography (bifemoral pelvis/leg), cerebral arteriography, phlebography of the extremities, and arthrography.[L46911]', '', '', 2435, '2025-03-13', CURRENT_TIMESTAMP),
(11318, 'Tetanus antitoxin 1500 i u 10 ampoules', 'تيتانوس مصل انتي توكسين 1500 وحدة دولية 10 امبولات', '950', '1,100', 'Tetenus vaccine', 'Sinochem ningbo imp.-china > international trading office', 'Ampoule', 'أمبول', 'مصل طبي ضد الفيروسات والأمراض التي قد تنتقل بالجروح', 'Anti tetanus serum', '', '', '6224011116244', '', 4285, '2025-08-04', CURRENT_TIMESTAMP),
(7057, 'Skinova image sunscreen spf+50 gel', 'سكينوفا ايمدج صنسكرين جل', '', '360', '', '', 'Gel', 'جل', '', '', '', '', '', '', 721, '2022-08-21', CURRENT_TIMESTAMP),
(12183, 'Venoruton forte 500mg 10 tab.', 'فينوروتون فورت 500مجم 10 اقراص', '', '17', 'Rutoside', 'Novartis > glaxo smithkline', 'Tab', 'أقراص', 'تقوية الاوردة الدموية -- تحسين الدورة الدموية -- تقليل الالام -- حالات الصدمات والكدمات', 'Veinotonic', '500mg', 'description a flavonol glycoside found in many plants including buckwheat; tobacco; forsythia; hydrangea; viola etc. it has been used therapeutically to decrease capillary fragility.', '6223002640713', '', 1647, '2022-12-14', CURRENT_TIMESTAMP),
(19018, 'Fever n flu night time sachets', 'فيفر اند فلو نايت تايم اكياس', '', '5', 'Diphenhydramine+paracetamol(acetaminophen)+pseudoephedrine', 'Pharopharma', 'Sachet', 'أكياس', '', 'Cold drugs', '', '', '', '', 921, '2022-07-26', CURRENT_TIMESTAMP),
(2918, 'Gybenash 28gm 14 sachets', 'جايبيناش 28جم 14 اكياس', '', '210', 'Palmitoylethanolamide(pea)', 'Biomed', 'Sachet', 'أكياس', '', 'Neuropathic pain', '28gm', '', '', '', 1153, '2022-07-09', CURRENT_TIMESTAMP),
(14467, 'Asmakast 5 mg 30 chewable tab', 'ازماكاست 5مجم 30 قرص للمضغ', '75', '120', 'Montelukast', 'Mina pharm > sandoz', 'Tab', 'أقراص', 'علاج أزمات الصدر وصعوبة وضيق التنفس', 'Asthma.anti-inflammatory.leukotriene antagonist', '5 mg', 'Montelukast is indicated for:
(a) the prophylaxis and chronic treatment of asthma in adults and pediatric patients who are 12 months of age and older[L6301], although other regional health authorities specifically note this indication for adults and adolescents who are 15 years and older[L6304,L6307] and also include indications for preventing day and night-time symptoms, and the treatment of acetylsalicylic acid-sensitive asthma[L6304];
(b) the prevention of exercise-induced bronchoconstriction (EIB) in patients who are 6 years of age and older[L6301], although other regional health authorities specifically note this indication for adults and adolescents who are 15 years and older[L6304,L6307]; and
(c) the relief of symptoms of seasonal allergic rhinitis in patients 2 years of age and older and perennial allergic rhinitis in patients 6 months of age and older[L6301], although other regional health authorities specifically note the relief of seasonal allergic rhinitis symptoms for adults and adolescents who are 15 years and older[L6304,L6307].
Furthermore, some formulations like chewable montelukast tablets may also be specifically indicated by particular regulatory bodies for the prophylaxis and chronic treatment of asthma, including the prevention of day and night-time symptoms, the treatment of acetylsalicylic acid based asthma, and the prevention of exercise-induced bronchoconstriction in adult and pediatric patients aged 2 and older[L6328], between the ages 2 and 5[L6325], or between the ages of 6 and 14 years.[L6331]
Moreover, when employed for such indications montelukast is considered effective as monotherapy or when combined with other medications indicated for the maintenance treatment of chronic asthma.[L6304,L6328] For instance, montelukast and inhaled corticosteroids can be used concomitantly to demonstrate additive effects to control asthma or to decrease the necessary inhaled corticosteroid dose while still maintaining clinical stability.[L6304,L6328]
Additionally, in patients who continue to experience asthma symptoms, montelukast can also be combined with an ''as required'' short-acting beta-agonist, an inhaled corticosteroid, or inhaled corticosteroid paired with a long-acting beta-agonist.[L6304,L6328]', '6223002642489', '', 11254, '2024-10-22', CURRENT_TIMESTAMP),
(17380, 'Aaa', 'ششش', '', '40', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 818, '2022-09-23', CURRENT_TIMESTAMP),
(19962, 'Glybformin 5/500mg 30 tab.', 'جليبوفورمين 5/500 مجم 30 قرص', '18', '45', 'Glibenclamide(glyburide)+metformin', 'International drug industries > novell pharma', 'Tab', 'أقراص', '', 'Anti-diabetic.combined secretagogues+sensitizers', '500mg', 'about metformin biguanide derivative oral anti-diabetic. mechanism of action of metformin it is a biguanide which exerts antidiabetic action. the drug suppresses gluconeogenesis in liver and thus suppresses hepatic glucose output. it enhance insulin media', '6223004070440', '', 1154, '2025-08-16', CURRENT_TIMESTAMP),
(7001, 'Kidzona omega oral drops 30 ml', 'كيدزونا اوميجا نقط فم 30 مل', '115', '135', 'Fish oil+vitamin d3+vitamin b complex', 'Original group', 'Drops', 'نقط', '', 'Multivitamin', '30 ml', 'Under FDA approval, fish oil pharmaceuticals are typically products consisting of a combination of the omega-3-fatty acids eicosapentaenoic acid (EPA) and docosahexaenoic acid (DHA) and are indicated primarily as an adjunct to diet to reduce triglyceride levels in adult patients with severe (>=500 mg/dL) hypertriglyceridemia [FDA Label, F36].
Under EMA approval, such fish oil pharmaceuticals comprised of virtually the same fish and fish oil derived omega-3-fatty acids EPA and DHA are indicated specifically for (a) adjuvant treatment in secondary prevention after myocardial infarction, in addition to other standard therapy (ie. statins, antiplatelet medicinal products, beta blockers, ACE inhibitors), and (b) as a supplement to diet when dietary measures alone are insufficient to produce an adequate response, particularly with type IV hypertriglyceridemia in monotherapy or type IIb/III in combination with statins, when control of triglycerides is insufficient [L2661]. In addition, prescribing information for EMA approved fish oil pharmaceuticals are also indicated as an adjunct to diet to reduce very high (>=500 mg/dL) triglyceride levels in adult patients, much like similar FDA approved indications [F37, FDA Label].', '', '', 1072, '2025-01-18', CURRENT_TIMESTAMP),
(11654, 'Nearby you calamine 120 ml lotion', 'نير باي يو كالامين لوشن 120 مل', '', '65', 'Calamine+melaleuca alternifolia (tea tree) extract+tocopherol (vitamin e)+glycerin+thymelaea hirsuta leaf extract+chlorhexidine+hydrogenated olive oil+aloe vera leaf extract+panthenol+chamomilla recutita (chamomile) extract+hydrogenated castor oil+hydrogenated jojoba oil+zinc oxide & allantoin', 'Near international', 'Lotion', 'لوشن', '', 'Napkin lotion', '120 ml', '', '', '', 991, '2024-07-14', CURRENT_TIMESTAMP),
(302, 'Alexlactive 200 sugar coated tab.', 'اليكس ليكتف شوجر 200 قرص', '', '36', 'Aloin + belladona', 'Alexandria', 'Tab', 'أقراص', '', 'Laxative', '', 'belladonna is a plant. the leaf and root are used to make medicine. belladonna is used as a sedative to stop bronchial spasms in asthma and whooping cough and as a cold and hay fever remedy. it is also used for parkinson s disease colic motion sickness an', '', '', 1503, '2022-05-15', CURRENT_TIMESTAMP),
(21681, 'Aaa', 'ششش', '', '68', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 677, '2022-08-21', CURRENT_TIMESTAMP),
(564, 'Awadist joint 665mg 20 tabs', 'اواديست جوينت 665مجم 20 قرص', '', '30', 'Paracetamol(acetaminophen)', 'High performance pharma (hp pharma)', 'Tab', 'أقراص', '', '', '665mg', '', '', '', 1206, '2023-07-02', CURRENT_TIMESTAMP),
(2847, 'Revimerz 50gm cream', 'ريفيميرز كريم 50 جم', '', '85', 'Sesameoil + hyaluronic acid + proplis wax + tea tree oil', 'Bio legend pharmaceutical company', 'Cream', 'كريم', '', 'Wound healing cream', '50gm', '', '', '', 865, '2022-07-25', CURRENT_TIMESTAMP),
(30027, 'Zopiclone 7.5mg 10 f.c. tabs.', 'زوبيكلون 7.5مجم 10قرص', '', '9', 'Zopiclone', 'Eva pharma', 'Tab', 'أقراص', '', 'Psychiatric.anxiolytics-hypnotics', '7.5mg', 'For the short-term treatment of insomnia.', '', '', 3088, '2022-07-07', CURRENT_TIMESTAMP),
(4057, 'Eldoquine 2 % cream 14.18 gm (n/a', 'الدوكين 2% كريم 14.8 جم', '', '20', 'Hydroquinone', 'Icn pharmaceutical inc u.s.a > eimc', 'Cream', 'كريم', 'كريم تفتيح للجلد -- ترطيب الجلد وتنعيمه -- علاج اثار الحروق والشمس', 'Whitening topical', '2 %', 'Hydroquinone is used as an OTC topical lightening agent for disorders of hyperpigmentation including melasma, post-inflammatory hyperpigmention, sunspots and freckles.', '301870394313', '', 1243, '2022-12-04', CURRENT_TIMESTAMP),
(4986, 'Flucamox 250mg/5ml susp. 80ml', 'فلوكاموكس 250 مجم/5مل معلق 80 مل', '', '11', 'Amoxicillin+flucloxacillin', 'Sedico', 'Susp', 'معلق', '', 'Penicillins.penicillin with b-lactamase inhibitor', '250mg', 'amoxycillin and flucloxacillin ï¿½ generally exhibit an additive effect against sensitive bacteria and bacteria that are sensitive to amoxycillin or to flucloxacillin remain sensitive to the combination showing that antagonism does not occur when the two', '6221042482010', '', 897, '2022-12-05', CURRENT_TIMESTAMP),
(30910, 'Meron 20 tabs.', 'ميرون 20 قرص', '79.5', '92', 'Chelated iron+lactoferrin+folic acid+vitamins b1+b6+b12+vitamin c+zinc', 'Medcare > novogen', 'Tab', 'أقراص', '', 'Multivitamin', '', 'anemia chelated iron combined with lactoferrin folic acid and vitamins', '6774433700014', '', 2456, '2024-07-04', CURRENT_TIMESTAMP),
(18803, 'Aliva 30 tabs', 'اليفا 30 قرص', '', '99', 'Ca+mg', 'Swivel med', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '', '', 1012, '2024-05-27', CURRENT_TIMESTAMP),
(703, 'Methyl cobal 500 ampoule imported', 'ميثيل كوبال 500 امبولات - مستورد', '', '0', '', 'Company', 'Ampoule', 'أمبول', '', '', '', '', '', '', 1516, '2022-07-15', CURRENT_TIMESTAMP),
