(5414, 'Gemzar 200mg i.v. vial', 'جيمزار 200 مجم فيال', '342', '445', 'Gemcitabine', 'Eli lilly', 'Vial', 'فيال', '', 'Antineoplastic', '200mg', 'Gemcitabine is a chemotherapeutic agent used as monotherapy or in combination with other anticancer agents. 
In combination with [carboplatin], it is indicated for the treatment of advanced ovarian cancer that has relapsed at least 6 months after completion of platinum-based therapy.[L32950]
Gemcitabine in combination with [paclitaxel] is indicated for the first-line treatment of patients with metastatic breast cancer after failure of prior anthracycline-containing adjuvant chemotherapy, unless anthracyclines were clinically contraindicated.[L32950]
In combination with [cisplatin], gemcitabine is indicated for the first-line treatment of patients with inoperable, locally advanced (Stage IIIA or IIIB) or metastatic (Stage IV) non-small cell lung cancer (NSCLC).[L32950] Dual therapy with cisplatin is also used to treat patients with Stage IV (locally advanced or metastatic) transitional cell carcinoma (TCC) of the bladder.[L32955]
Gemcitabine is indicated as first-line treatment for patients with locally advanced (nonresectable Stage II or Stage III) or metastatic (Stage IV) adenocarcinoma of the pancreas. Gemcitabine is indicated for patients previously treated with [fluorouracil].[L32950]', '', '', 1269, '2025-01-14', CURRENT_TIMESTAMP),
(12631, 'Windy 200mg 10 sachet', 'ويندي 200مجم 10 اكياس فوار', '14', '25', 'Acetylcysteine', 'Pharco', 'Sachet', 'أكياس', 'مذيب بلغم', 'Mucolytic', '200mg', 'Acetylcysteine is indicated for mucolytic therapy and in the management of [acetaminophen] overdose.[L31378,L31383,L31388,L31478]', '6221151002321', '', 3148, '2023-09-05', CURRENT_TIMESTAMP),
(32704, 'Danasetron 8mg/4ml 5 amp.', 'داناسيترون 8 مجم/2مل 5 امبول', '156', '225', 'Ondansetron', 'Sunny medical', 'Amp', 'أمبول', '', 'Antiemetic', '8mg', 'In the adult patient population:
i) orally administered ondansetron tablets and orally disintegrating tablets (ODT) are indicated for:
- the prevention of nausea and vomiting associated with emetogenic cancer chemotherapy, including high dose (ie. greater than or equal to 50 mg/m2) cisplatin therapy, and radiotherapy, and
- the prevention and treatment of postoperative nausea and vomiting
ii) intravenously administered ondansetron injection formulations are indicated for:
- the prevention of nausea and vomiting associated with emetogenic cancer chemotherapy, including high dose (ie. greater than or equal to 50 mg/m2) cisplatin therapy, and
- the prevention and treatment of postoperative nausea and vomiting
In the pediatric (4-18 years of age) patient population:
i) ondansetron was effective and well tolerated when given to children 4-12 years of age for the treatment of post-chemotherapy induced nausea and vomiting,
ii) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for the treatment of children 3 years of age or younger,
iii) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for use in any age group of the pediatric population for the treatment of post-radiotherapy induced nausea and vomiting, and
iV) ondansetron tablets, ondansetron ODT, ondansetron injection are not indicated for use in any age group of the pediatric population for the treatment of postoperative nausea and vomiting
In the geriatric (>65 years of age) patient population:
i) efficacy and tolerance of ondansetron were similar to that observed in younger adults for the treatment of post-chemotherapy and radiotherapy-induced nausea and vomiting, and
ii) clinical experience in the use of ondansetron in the prevention and treatment of postoperative nausea and vomiting is limited and is not indicated for use in the geriatric patient population', '6251065023709', '', 959, '2024-12-21', CURRENT_TIMESTAMP),
(32045, 'Hinda b comp 30tablets', 'هيندا بي كومب 30 قرص', '88.5', '150', 'Vit b1(thiamin hcl)100mg&vit b6(pyridoxin hcl) 50mg&vit b12(cyanococobalamin)1000mcg', 'Hp pharma', 'Tablet', 'أقراص', '', 'Multivitamin', '', 'hinda b comp cyanocobalamin+pyridoxin+thiamin price=78l.e co..hi performance pc.vitamine b complex vit b1(thiamin hcl)100mg&vit b6(pyridoxin hcl) 50mg&vit b12(cyanococobalamin)1000mcg dose:one tablet once daily', '6224011394154', '', 507, '2024-08-29', CURRENT_TIMESTAMP),
(9790, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 824, '2023-05-03', CURRENT_TIMESTAMP),
(20089, 'Guaflex-n syrup 120 ml', 'جوافلكس-ان شراب 120 مل', '25', '45', 'Guava leaves+tilia flower+fennel oil', 'Mepaco', 'Syrup', 'شراب', '', 'Cough drugs', '120 ml', 'helps in improving respiratory functions', '6223002218080', '', 1545, '2025-08-23', CURRENT_TIMESTAMP),
(29867, 'Zeltrod 6mg 10 tab.', 'زيلترود 6مجم 10 اقراص', '', '15', 'Tegaserod', 'Sigma', 'Tab', 'أقراص', 'يُستخدم كعلاج قصير الأمد من متلازمة القولون العصبي والتي تشمل آلام البطن، والانتفاخ، والإمساك', 'Motility stimulant', '6mg', 'Tegaserod is a serotonin-4 (5-HT4) receptor agonist indicated for the treatment of adult women less than 65 years of age with irritable bowel syndrome with constipation (IBS-C) [F4223, F4229]. The safety and effectiveness of tegaserod in men with IBS-C have not been established [F4223, F4229].', '', '', 847, '2022-07-15', CURRENT_TIMESTAMP),
(4098, 'Eltroxin 100 mcg 100 tabs.', 'التروكسين 100مكجم 100 قرص', '86.5', '115', 'Thyroxine', 'Aspen europe gmbh > glaxo smithkline', 'Tab', 'أقراص', 'علاج نقص افراز الغدة الدرقية', 'Thyroid hormone', '100 mcg', '', '6221045009801', '', 9312, '2024-07-16', CURRENT_TIMESTAMP),
(19599, 'Aaa', 'ششش', '', '34', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 745, '2022-05-30', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(7236, 'Levanic 750 mg 5 tab', 'ليفانيك 750 مجم 5 اقراص', '45', '66', 'Levofloxacin', 'Mup', 'Tab', 'أقراص', 'مضاد حيوي', 'Antibiotic.quinolone', '750 mg', 'In oral and intravenous formulations, levofloxacin is indicated in adults for the treatment of various infections caused by susceptible bacteria, including infections of the upper respiratory tract, lower respiratory tract, skin, skin structures, urinary tract, and prostate.[L11638,L11692] The oral formulation is also indicated in both adults and children 6 months of age and older for the post-exposure management of inhalational anthrax caused by _Bacillus anthracis_ and for the treatment and/or prophylaxis of plague caused by _Yersinia pestis_.[L11638]
In its ophthalmic formulation, levofloxacin is indicated for the treatment of bacterial conjunctivitis caused by susceptible organisms.[L11641] An inhalational solution available in Canada is indicated for the management of cystic fibrosis patients aged 18 years or older with chronic pulmonary _Pseudomonas aeruginosa_ infections.[L11689]', '6221508510417', '', 5758, '2024-11-11', CURRENT_TIMESTAMP),
(28551, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 781, '2022-10-22', CURRENT_TIMESTAMP),
(389, 'Allergex caffeine 20 tab.', 'اليرجيكس كافيين 20 قرص', '4.75', '20', 'Caffeine+chlorphenoxamine', 'Eipico', 'Tab', 'أقراص', '', 'Antihistamine', '', '', '6221032110077', '', 2521, '2025-06-23', CURRENT_TIMESTAMP),
(18076, 'Sly amylase 60 ml syrup', 'سلي اميليز شراب 60 مل', '60', '115', 'Alphaamylase 109.3 mg+lactase 333 mg+vit d3', 'Elsaid saliy pharma', 'Syrup', 'شراب', '', 'Antiinflammatory anti-edemtous', '60 ml', '', '', '', 1213, '2025-08-11', CURRENT_TIMESTAMP),
(33267, 'Nervivox 30 sublingual tabs', 'نيرفيفوكس 30 قرص', '54', '90', 'Folic acid+vitamin b6+vitamin b12', 'K and m pharma', 'Tab', 'أقراص', '', 'Dietary supplement', '', 'Folic acid is indicated for the treatment of folic acid deficiency, megaloblastic anemia, and in anemias of nutritional origins, pregnancy, infancy, or childhood.', '6224011427012', '', 2313, '2024-07-11', CURRENT_TIMESTAMP),
(27793, 'Sylovina 20 sachets', 'سيلوفينا 20 كيس', '', '150', 'Psyllium husk powder+chromium', 'Rameda', 'Sachet', 'أكياس', '', 'Weight loss', '', 'indications #sylovina is used as an adjunct in weight management and digestive health. dosage #one sachet twice daily 15 minutes before breakfast and 15 minutes before the main meal. #not for use in children < 15 years old. #not for use during pregnancy o', '', '', 798, '2022-07-27', CURRENT_TIMESTAMP),
(22396, 'Maxi-mum 10 sachets', 'ماكسي مام 10 اكياس', '', '29', 'Feonugreek+fennel+chamomile+anise', 'Pharma zad > dawaa', 'Sachet', 'أكياس', '', 'Lactagauge', '', 'stimulates normal breastfeeding dose: 1 sachet to be dissolved in a cup of water per day', '', '', 912, '2022-07-18', CURRENT_TIMESTAMP),
(26280, 'Rony hair spray 120 ml', 'روني سبراي للشعر 120مل', '39.95', '80', '', 'Hi-care > rony pharma', 'Spray', 'بخاخ', '', 'Hair care', '120 ml', 'for hair growth and nourishment', '', '', 898, '2025-08-16', CURRENT_TIMESTAMP),
(23324, 'Naviluca 2mg/ml vial for i.v. inf. 50 ml', 'نافيلوكا 2مجم/مل فيال 50مل', '50.5', '92', 'Fluconazole', 'Arabcomed-egypt > rotabiogen for pharmaceutical invest.', 'Vial', 'فيال', '', 'Antifungals.triazoles', '2mg', 'Fluconazole can be administered in the treatment of the following fungal infections[L11043]:
 1) Vaginal yeast infections caused by Candida
 2) Systemic Candida infections
 3) Both esophageal and oropharyngeal candidiasis 
 4) Cryptococcal meningitis
 5) UTI (urinary tract infection) by Candida
 6) Peritonitis (inflammation of the peritoneum) caused by Candida
**A note on fungal infection prophylaxis**
Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '', '', 820, '2024-11-10', CURRENT_TIMESTAMP),
(10302, 'Selenium daily vit 30 tabs', 'سيلنيوم ديلي فيت 30 قرص', '95', '100', 'Selenium+vitamin a+vitamin e+vitamin c', 'Zoser pharma', 'Tab', 'أقراص', '', 'Multivitamins', '', '', '', '', 1468, '2024-07-02', CURRENT_TIMESTAMP),
(22688, 'Miacalcic 200 i.u./ml nasal spray 2 ml', 'مياكالسيك 200وحدة/مل سبراي للانف 2 مل', '', '150', 'Calcitonin', 'Novartis', 'Spray', 'بخاخ', '', 'Osteoporosis.antiresorptives', '2 ml', 'Investigated for use/treatment in myocardial infarction, heart disease, and asthma.', '4897102130027', '', 1088, '2024-12-11', CURRENT_TIMESTAMP),
