Indicated for the management of variant angina (Prinzmetal''s angina).[L6298]
**Intravenous**
Indicated for the short-term management of atrial fibrillation or atrial flutter for temporary control of rapid ventricular rate.[L6292]
Indicated for the rapid conversion of paroxysmal supraventricular tachycardias (PSVT) to sinus rhythm. This includes AV nodal reentrant tachycardias and reciprocating tachycardias associated with an extranodal accessory pathway such as the WPW syndrome or short PR syndrome.[L6292]
**Off-label**
Indicated for off-label uses in anal fissures (as topical formulation), migraine prophylaxis, cramps in lower leg related to rest, pulmonary hypertension,[L6289] idiopathic dilated cardiomyopathy, and proteinuria associated with diabetic nephropathy.[L6298]', '', '', 778, '2022-07-18', CURRENT_TIMESTAMP),
(6908, 'Ketorolac 0.5gm/100ml eye drops 5 ml', 'كيتورولاك قطرة عين 5 مل', '', '6', 'Ketorolac tromethamine', 'Memphis', 'Drops', 'نقط', 'قطرة عين مسكنة ومضادة للالتهاب', 'Nsaid.acetic acid derivatives', '0.5gm', 'Ketorolac is a Non-steroidal anti-inflammatory drug (NSAID) and has antipyretic, analgesic and anti-inflammatory properties.[A176131]  It is indicated for short term management of acute pain that requires the calibre of pain management offered by opioids.[L3674]  Clinicians may choose to initiate ketorolac to manage post-operative pain, spinal and soft tissue pain, rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, menstrual disorders and headaches among other ailments.[L6520] Regardless of the etiology of pain, patients should use the lowest possible dose, and avoid using ketorolac for an extended period of time (ideally ≤ 5 days).[L3674] A benefit of choosing ketorolac over other analgesics with similar potency is that that there does not appear to be a risk of dependence or tolerance with ketorolac use.[A176131]', '', '', 2791, '2023-02-05', CURRENT_TIMESTAMP),
(24424, 'Oxytetracid 250 mg 16 caps.', 'اوكسيتيتراسيد 250مجم 16 كبسول', '', '11', 'Oxytetracycline+polymyxin', 'Cid', 'Cap', 'كبسولة', '', 'Antibiotic', '250 mg', 'about oxytetracycline tetracycline derivative a broad spectrum antibiotic. mechanism of action of oxytetracycline oxytetracycline is a broad spectrum antibiotic which has action against both gram positive organisms & gram negative organisms. it exerts its', '', '', 1024, '2022-07-13', CURRENT_TIMESTAMP),
(23117, 'Muslgix 20 caps.', 'موسلجيكس 20 كبسولة', '25', '40', 'Ibuprofen+methocarbamol', 'Pharopharma > ema pharm', 'Cap', 'كبسولة', '', 'Cns.analgesic.skeletal muscle relaxant', '', 'muslgix provides a double approach to the management of discomfort associated with musculoskeletal disorders through muscle relaxation and analgesic effect. indications/ uses: muslgix is used in the symptomatic treatment of musculoskeletal conditions asso', '6224000912147', '', 1958, '2024-11-19', CURRENT_TIMESTAMP),
(24035, 'Olumiant 2 mg 28 f.c. tabs.', 'اوليوميانت 2مجم 28 قرص', '', '12,847', 'Baricitinib', 'Eli lilly', 'Tab', 'أقراص', '', 'Janus kinase (jak) inhibitor', '2 mg', 'In the US and Europe, baricitinib is indicated for the treatment of adult patients with moderately to severely active rheumatoid arthritis who have had an inadequate response to one or more TNF blockers. Baricitinib may be used as monotherapy or in combination with [methotrexate] [L41760,L41770] or other DMARDs.[L41760]
In Europe, baricitinib is indicated for the treatment of moderate to severe atopic dermatitis in adult patients who are candidates for systemic therapy.[L41770]
In the US, baricitinib is also indicated for the treatment of coronavirus disease 2019 (COVID-19) in hospitalized adults requiring supplemental oxygen, non-invasive or invasive mechanical ventilation, or extracorporeal membrane oxygenation.[L41760] Recently, it is also approved as the treatment for severe alopecia areata in adults.[L42070]', '', '', 1337, '2022-08-04', CURRENT_TIMESTAMP),
(22967, 'Moony tooth paste 65 gm', 'موني معجون اسنان 65جم', '20', '40', 'Chlorhexidine gluconate 0.1%+ sodium monofluorophosphate 0.76%+bee propolis 0.3%+calcium carbonate 3', 'Sesic > rony pharma', 'Unknown', 'غير محدد', '', 'Tooth paste', '65 gm', 'Chlorhexidine is available over-the-counter in various formulations (e.g. solution, sponge, cloth, swab) as a topical antiseptic to sanitize prior to surgeries and/or medical procedures.[L11518,L11521,L11527,L11533] Dental formulations, available by prescription only, include an oral rinse indicated for the treatment of gingivitis[L11512] and a slow-release "chip" which is inserted into periodontal pockets and is indicated for the reduction of pocket depth in adult patients with periodontitis as an adjunct therapy to dental scaling and root planing procedures.[L11536]', '', '', 1239, '2024-05-13', CURRENT_TIMESTAMP),
(12229, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 691, '2022-11-30', CURRENT_TIMESTAMP),
(3412, 'Olazorix 20 mg 21 f.c.tabs.', 'اولازوريكس 20مجم 21 قرص', '147.25', '198', 'Olanzapine', 'Mash premiere', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '20 mg', 'Olanzapine was initially used orally and intramuscularly for the chronic treatment of schizophrenia in patients over 13 years old and other psychiatric disorders such as bipolar I disorder including mixed or manic episodes.[A177014] 
Olanzapine is also indicated, in combination with lithium or valproate for the short-term treatment of acute manic or mixed episodes associated with bipolar I disorder in adults.[FDA label]
As well, olanzapine is indicated, in combination with fluoxetine for the treatment of episodes of depression associated with bipolar disorder type 1 and treatment-resistant depression in patients over 10 years old.[A177014]
Olanzapine is also approved for the management of psychomotor agitation associated with schizophrenia and bipolar I mania.[FDA label]
Schizophrenia is a complex biochemical brain disorder that affects the person''s ability to differentiate reality. It is usually observed as the presence of delusions, hallucinations, social withdrawal and disturbed thinking.[L5936]
Bipolar disorder is a mental health condition defined by periods of extreme mood disturbances. It is categorized in different types from which type 1 is known to involve episodes of severe mania and often depression while type 2 presents less severe forms of mania.[L5939]
Olanzapine is also indicated in combination with [samidorphan] for the treatment of bipolar I disorder, either as an adjunct to lithium or valproate or as monotherapy for the acute treatment of manic or mixed episodes or as maintenance therapy, and for the treatment of schizophrenia in adults.[L34359]', '', '', 908, '2025-01-22', CURRENT_TIMESTAMP),
(6289, 'Cobafolic plus 30 cap', 'كوبافوليك بلس 30 كبسولة', '', '180', 'Iron as (ferrous bis glycinate)+vitamin c+quatrefolic+methylcobalamin', 'Wellness pharma', 'Cap', 'كبسولة', '', 'Supplement', '', 'For treatment of patients with documented iron deficiency in whom oral administration is unsatisfactory or impossible. Also used to replenish body iron stores in Non-Dialysis Dependent-Chronic Kidney Disease (NDD-CKD) patients receiving or not receiving erythropoietin and in Hemodialysis Dependent (HDD-CKD) and Peritoneal Dialysis Dependent (PDD-CKD) - Chronic Kidney Disease patients receiving an erythropoietin.', '', '', 1175, '2024-08-03', CURRENT_TIMESTAMP),
(29135, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 658, '2022-12-08', CURRENT_TIMESTAMP),
(28444, 'Trevicta 263mg prefilled syringe', 'تريفيكتا 263مجم سرنجات معبأة للحقن', '', '10,875', 'Paliperidone', 'Janssen cilag > soficopharm', 'Syringe', 'حقنة', 'امراض نفسية -- مضاد لحالات الذهان والفصام', 'Psychiatric.antipsychotics', '263mg', 'As an oral extended-release tablet and a once-monthly extended-release suspension for intramuscular injection, paliperidone is indicated for the treatment of adults and adolescents with schizophrenia and in the treatment of schizoaffective disorder in combination with antidepressants or mood stabilizers.[L16168,L37744] Paliperidone is also available in both an every-three-month and twice-yearly extended-release suspension for intramuscular injection for the treatment of schizophrenia.[L4137,L37749]', '', '', 3050, '2023-02-13', CURRENT_TIMESTAMP),
(27245, 'Solian 200mg 30 scored tablets', 'سوليان 200مجم 30 قرص', '', '219', 'Amisulpride', 'Sanofi winthrop > ramco', 'Tablet', 'أقراص', '', 'Psychiatric.antipsychotics', '200mg', 'Intravenous amisulpride is indicated in adults for the prevention of postoperative nausea and vomiting, either alone or in combination with an antiemetic of a different class. It is also indicated for the treatment of postoperative nausea and vomiting in patients who have received anti-emetic prophylaxis with an agent of a different class or have not received prophylaxis.[L32759]
Oral amisulpride is indicated for the treatment of acute and chronic schizophrenic disorders, characterized by positive symptoms with delusions, hallucinations, thought disorders, hostility and suspicious behavior; or primarily negative symptoms (deficit syndrome) with blunted affect, emotional and social withdrawal. Amisulpride also controls secondary negative symptoms in productive conditions as well as affective disorders such as depressive mood or retardation.[L32764]', '3582910079996', '', 1430, '2022-12-08', CURRENT_TIMESTAMP),
(14996, 'Beesline deo whitening elder rose spray 150 ml', 'بيزلين ديو بخاخ لتفتيح البشرة برائحة الورد 150 مل', '195', '225', '', 'Beesline > pharma cruise medical', 'Spray', 'بخاخ', '', 'Skin care', '150 ml', 'active ingredients alum rock vitamin e aloe vera ginger soybean vitamin c lumiskin teflose lactic acid sodium lactate vitamin b3 & propolis. a skin-friendly spray deodorant with 72hr antiperspirant action to prevent moisture & body odour. all the while de', '', '', 720, '2025-08-07', CURRENT_TIMESTAMP),
(5298, 'Betasept antiseptic soln. 10% 200 ml', 'بيتاسيبت 10% محلول مطهر 200 مل', '', '150', 'Povidone- iodine', 'Panax pharma', 'Sol', 'محلول', '', 'Antiseptic', '10%', '', '', '', 738, '2025-08-16', CURRENT_TIMESTAMP),
(10677, 'Solupred oro 20mg 20 orodispersible tabs.', 'سوليوبريد 20مجم 20 قرص ذائب بالفم', '90', '142', 'Prednisolone', 'Sanofi winthrop > sanofi', 'Tab', 'أقراص', 'يستخدم لتثبيط المناعة', 'Glucocorticoid', '20mg', 'Prednisolone is indicated to treat endocrine, rheumatic, and hematologic disorders; collagen, dermatologic, ophthalmic, respiratory, and gastrointestinal diseases; allergic and edematous states; and other conditions like tuberculous meningitis.[L9542]', '42607477231740', '', 14137, '2025-08-04', CURRENT_TIMESTAMP),
(26234, 'Aaa', 'ششش', '', '46', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 776, '2023-01-24', CURRENT_TIMESTAMP),
(32770, 'Dufaximin 550 mg 28 f.c. tabs.', 'دوفاكسيمين 550 مجم 28 قرص', '338', '480', 'Rifaximin', 'Aug pharma', 'Tab', 'أقراص', 'علاج إسهال المسافرين وعلاج متلازمة القولون العصبي المتوسطة', 'Travelers diarrhea', '550 mg', 'Rifaximin has multiple indications by the FDA: for the treatment of patients (≥12 years of age) with traveller''s diarrhea caused by noninvasive strains of Escherichia coli; for the reduction of overt hepatic encephalopathy recurrence in patients ≥18 years of age; and in May 2015 it was approved for irritable bowel syndrome with diarrhea (IBS-D) treatment in adult men and women.', '6223005460806', '', 9250, '2024-08-16', CURRENT_TIMESTAMP),
(29912, 'Ziaflex massage gel 50 gm', 'زيافلكس مساج جل 50 جم', '55', '65', '', '> ziax', 'Gel', 'جل', 'علاج آمن وفعال لآلام العظام والتقلصات العضلية', 'Massage', '50 gm', '', '', '', 1588, '2025-05-21', CURRENT_TIMESTAMP),
(11097, 'Sylvester 1 - 20 caps', 'سلفستر 1 للتخسيس وانقاص الوزن 20 كبسولة', '70', '150', 'Gymnema sylvestre+chromium picocolinate', 'Debeiky', 'Cap', 'كبسولة', 'للتخسيس وانقاص الوزن وبرامج الحمية الغذائية', 'Weight loss', '', '', '', '', 25008, '2024-04-23', CURRENT_TIMESTAMP),
(29000, 'Varicoid 250 iu/g cream 20 gm', 'فاريكويد 250وحدة/جم كريم 20جم', '', '7', 'Mucopolysaccharide polysulfate', 'T3a pharma', 'Cream', 'كريم', '', '', '250 iu', '', '', '', 634, '2022-07-21', CURRENT_TIMESTAMP),
(23499, 'Neuth lightening intelligence system night cream 30 ml', 'نيوث كريم تفتيح ليلي 30 مل', '', '330', '', 'Neuth > eva pharma', 'Cream', 'كريم', '', 'Skin care', '30 ml', 'neuth lightening intelligence system is a complete system that inhibits all steps of skin darkening leaving skin even toned. formula does not contain hydroquinone or kojic acid which are proven to be harmful to the skin. formula contains a stable form of', '', '', 1116, '2022-07-09', CURRENT_TIMESTAMP),
(22635, 'Metformin-el nasr 500mg 200 tab.', 'ميتفورمين النصر 500مجم 200 قرص', '', '26', 'Metformin hydrochloride', 'El nasr', 'Tab', 'أقراص', '', 'Anti-diabetic.sensitizers.biguanide', '500mg', '**Metformin immediate-release formulations**
Metformin is indicated as an adjunct to diet and exercise to improve glycemic control in adults and pediatric patients ≥10 years old with type 2 diabetes mellitus.[L40243]
**Metformin extended-release tablet (XR)**
The extended-release formulation of metformin is indicated as an adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus. Safety in children has not been determined to this date.[L12207]
**Metformin combination products**
Metformin is a component of a variety of combination products with other anti-diabetic agents. It is indicated, along with diet and exercise, to improve glycemic control in adult patients with type 2 diabetes mellitus in combination with DPP-4 inhibitors ([sitagliptin], [linagliptin], [alogliptin], or [saxagliptin]),[L11479,L40248,L40253,L40258,L40263] in combination with SGLT2 inhibitors ([canagliflozin], [empagliflozin], [ertugliflozin], or [dapagliflozin]),[L11479,L30503,L1134,L13679,L38729] or in combination with [pioglitazone].[L11419]', '6221067002316', '', 3854, '2022-12-06', CURRENT_TIMESTAMP),
(26149, 'Rinosan nasal spray 30 ml', 'رينوسان سبراي بخاخ للانف 30مل', '', '49', '', 'Apipharma > suecal pharmaceuticals', 'Spray', 'بخاخ', '', 'Nasal decongestant', '30 ml', 'isotonic solution for nasal humidification and cleansing.', '', '', 823, '2022-07-25', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(11767, 'Aaa', 'ششش', '', '180', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 801, '2022-08-17', CURRENT_TIMESTAMP),
(32469, 'Azathioprine-evapharma 50 mg 30 f.c.tabs.', 'ازاثيوبرين -ايفا فارما 50 مجم 30 قرص', '72', '96', 'Azathioprine', 'Eva pharma', 'Tab', 'أقراص', '', 'Immunosuppressant', '50 mg', 'Azathioprine is indicated to treat rheumatoid arthritis and prevent renal transplant rejection.[L11214]', '6223013100398', '', 2304, '2024-09-15', CURRENT_TIMESTAMP),
(18822, 'Farcosef 500mg vial', 'فاركوسيف 500مجم فيال', '', '7', 'Cephradine', 'Pharco b', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.first-generation', '500mg', 'description a semi-synthetic cephalosporin antibiotic. mechanism of action cefradine is a first generation cephalosporin antibiotic with a spectrum of activity similar to cefalexin. cefradine like the penicillins is a beta-lactam antibiotic. by binding to', '6223000010884', '', 753, '2023-02-06', CURRENT_TIMESTAMP),
(33068, 'La tree beaute glycerine soap 60 gm', 'لا تري بيوت صابونة جلسرين 60 جم', '46', '65', '', 'Egyptian co. for cosmetics > la tree beaute', 'Soap', 'صابون', '', 'Skin care', '60 gm', '', '', '', 1079, '2025-11-03', CURRENT_TIMESTAMP),
(23859, 'Nuxe aquabella micro-exfoliating purifying gel 150 ml', 'نوكس اكوابيلا جل 150مل', '235', '365', '', 'Nuxe laboratory > biotech egypt', 'Gel', 'جل', '', 'Skin care', '150 ml', 'facial cleanser for combination skin. this facial cleansing gel infused with natural blue micro-beads deeply cleanses without drying the skin. every day this purifying gel removes excess sebum and smooths away irregularities for clear fresh and luminous s', '', '', 934, '2023-09-03', CURRENT_TIMESTAMP),
(11847, 'Ultracaine 5% gel 30 gm', 'التراكايين جل 30 جرام', '21', '31', 'Lidocaine', 'Memphis', 'Gel', 'جل', 'مخدر موضعى ومسكن للالام', 'Analgesic.local anesthetic', '5%', 'Lidocaine is an anesthetic of the amide group indicated for production of local or regional anesthesia by infiltration techniques such as percutaneous injection and intravenous regional anesthesia by peripheral nerve block techniques such as brachial plexus and intercostal and by central neural techniques such as lumbar and caudal epidural blocks [F4349, L5930].', '6221050130224', '', 8193, '2024-07-17', CURRENT_TIMESTAMP),
(28428, 'Tremogine 10 mg 10 tab.', 'تريموجين 10مجم 10 اقراص', '', '13', 'Selegiline chloride', 'Eva pharma', 'Tab', 'أقراص', '', 'Parkinson s disease.mao-b inhibitor', '10 mg', 'Monotherapy for initial treatment of Parkinson''s disease, as well as an adjunct therapy in patients with a decreased response to levodopa/carbadopa. Also used for the palliative treatment of mild to moderate Alzheimer''s disease and at higher doses, for the treatment of depression.', '', '', 946, '2022-07-09', CURRENT_TIMESTAMP),
