recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6221088021600', '', 3491, '2024-09-03', CURRENT_TIMESTAMP),
(9811, 'Phara fero 27 - 20 chocolate pills', 'فرافيرو 27 20 كبسولة', '94', '160', 'Amino acids chelated minerals with vitamins', 'Delta pharma > devartlab pharma', 'Unknown', 'غير محدد', 'مصدر للحديد -- علاج الانيميا -- مقوي للجسم -- مصدر للطاقة', 'Iron supplement', '', '', '6223006935600', '', 7749, '2025-01-21', CURRENT_TIMESTAMP),
(28895, 'Uvascreen sun block lotion 50+ spf 60 gm', 'يوفاسكربن صن بلوك لوشن 50+ اس بي اف 60 جرام', '160', '250', 'Sun protection formula', 'Hi-care > roventis pharma', 'Lotion', 'لوشن', 'واقى شمس', 'Sun block', '60 gm', '', '6224010525269', '', 1041, '2025-09-05', CURRENT_TIMESTAMP),
(24344, 'Ostocal syrup 100 ml', 'اوستوكال شراب 100مل', '40', '50', 'Calcium carbonate+magnesium carbonate+vitamin d3+zinc', 'Sigma > international trading office', 'Syrup', 'شراب', '', 'Calcium supplement', '100 ml', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 1498, '2025-02-10', CURRENT_TIMESTAMP),
(14363, 'Aaa', 'ششش', '', '15', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 715, '2022-09-07', CURRENT_TIMESTAMP),
(7427, 'Mal wasser 60 ml spray', 'مال واسر سبراي 60 مل', '', '115', 'Sea salt+panthenol+tocopherol', 'Maldive pharmaceutical industries', 'Spray', 'بخاخ', '', 'Moisturizing and soothing spray', '60 ml', '', '', '', 927, '2025-09-20', CURRENT_TIMESTAMP),
(18838, 'Farostan forte 500mg 10 tab.', 'فاروستان فورت 500 مجم 10 قرص', '', '5', 'Mefenamic acid', 'Pharopharma', 'Tab', 'أقراص', '', 'Nsaid.fenamates', '500mg', 'For the treatment of rheumatoid arthritis, osteoarthritis, dysmenorrhea, and mild to moderate pain, inflammation, and fever.', '', '', 1274, '2022-07-28', CURRENT_TIMESTAMP),
(28041, 'Tentavair 40mcg/actuation inhaler 120 doses', 'تنتافير 40مكجم/جرعة 120جرعة', '', '37', 'Ciclesonide', 'Mdi pharma', 'Inhaler', 'جهاز استنشاق', '', 'Bronchodilator.anti-inflammatory.glucocorticoid steroid', '40mcg', 'For the treatment of nasal symptoms associated with seasonal and perennial allergic rhinitis in adults and adolescents 12 years of age and older.', '', '', 812, '2022-07-13', CURRENT_TIMESTAMP),
(8548, 'Nalpain 20mg/ml 5 amps.', 'نالبين 20مجم/مل 5 امبول', '37.25', '60', 'Nalbuphine', 'Alfacure pharmaceuticals', 'Amp', 'أمبول', '', 'Analgesics.opioid', '20mg', 'For the relief of moderate to severe pain.', '', '', 785, '2024-11-05', CURRENT_TIMESTAMP),
(21452, 'Aaa', 'ششش', '', '48', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 806, '2022-12-06', CURRENT_TIMESTAMP),
(21262, 'Aaa', 'ششش', '', '42', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 772, '2022-11-30', CURRENT_TIMESTAMP),
(16834, 'Cosarnomid 600 mg 10 f.c. tab.', 'كوزارنوميد 600 مجم 10 قرص', '', '33', 'Eprosartan', 'Pharmed healthcare', 'Tab', 'أقراص', '', 'Antihypertensive.angiotensin blocker', '600 mg', 'For the management of hypertension alone or in combination with other classes of antihypertensive agents. Also used as a first-line agent in the treatment of diabetic nephropathy, as well as a second-line agent in the treatment of congestive heart failure (only in those intolerant of ACE inhibitors).', '', '', 757, '2022-07-18', CURRENT_TIMESTAMP),
(32366, 'Alejon collagen serum 50 ml', 'اليجون كولاجين سيروم 50 مل', '350', '380', '', 'Alejon co.', 'Serum', 'سيروم', '', 'Skin care', '50 ml', '', '', '', 687, '2025-06-24', CURRENT_TIMESTAMP),
(20473, 'Hidonac 200mg/ml soln. for i.v. inf. 25ml', 'هايدوناك 200 مجم / مل محلول 25 مل', '481', '688', 'Acetylcysteine', 'Zambon > pharmacon', 'Sol', 'محلول', '', 'Mucolytic', '200mg', 'Acetylcysteine is indicated for mucolytic therapy and in the management of [acetaminophen] overdose.[L31378,L31383,L31388,L31478]', '', '', 1220, '2024-11-26', CURRENT_TIMESTAMP),
(6960, 'Klarimix 250mg 14 tab.', 'كلاريميكس 250مجم 14 اقراص', '60', '90', 'Clarithromycin', 'Sigma', 'Tab', 'أقراص', '', 'Antibiotic.macrolide', '250mg', 'An alternative medication for the treatment of acute otitis media caused by <i>H. influenzae, M. catarrhalis, or S. pneumoniae</i> in patients with a history of type I penicillin hypersensitivity. Also for the treatment of pharyngitis and tonsillitis caused by susceptible <i>Streptococcus pyogenes</i>, as well as respiratory tract infections including acute maxillary sinusitis, acute bacterial exacerbations of chronic bronchitis, mild to moderate community-acquired pneuomia, Legionnaires'' disease, and pertussis. Other indications include treatment of uncomplicated skin or skin structure infections, helicobacter pylori infection, duodenal ulcer disease, bartonella infections, early Lyme disease, and encephalitis caused by <i>Toxoplasma gondii</i> (in HIV infected patients in conjunction with pyrimethamine). Clarithromycin may also decrease the incidence of cryptosporidiosis, prevent the occurence of α-hemolytic (viridans group) streptococcal endocarditis, as well as serve as a primary prevention for <i>Mycobacterium avium</i> complex (MAC) bacteremia or disseminated infections (in adults, adolescents, and children with advanced HIV infection).
Clarithromycin is indicated in combination with [vonoprazan] and [amoxicillin] as co-packaged triple therapy to treat _Helicobacter pylori_ (_H. pylori_) infection in adults.[L41695]', '6221051010167', '', 1219, '2025-02-11', CURRENT_TIMESTAMP),
(8567, 'Aaa', 'ششش', '', '16', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 752, '2022-06-02', CURRENT_TIMESTAMP),
(23214, 'Nafenira eye drops 15 ml', 'نافينيرا قطرة للعين 15 مل', '', '8', 'Naphazoline+pheniramine', 'Chemipharm', 'Drops', 'نقط', 'علاج حساسية العين -- تقليل إحتقان العين -- علاج إحمرار العين و تهيجه.', 'Corneal vascularity.antihistamine combined with alpha 1 agonist', '15 ml', 'about naphazoline imidazoline derivative alpha-adrenergic agonist a decongestant vasoconstrictor. mechanism of action of naphazoline naphazoline exerts its vasoconstrictor action by acting as a selective alpha-1 adrenergic agonist. thus it reduces blood f', '', '', 1629, '2022-06-02', CURRENT_TIMESTAMP),
(7886, 'Kivaterne 30 tabs', 'كيفاتيرن 30 قرص', '', '150', 'Chymotrypsin+trypsin+bromelain+pancreatin ( protease+amylase+lipase )', 'Druglab pharmaceuticals', 'Tab', 'أقراص', '', 'Anti-inflammatory and anti-edematous', '', '', '', '', 854, '2025-11-04', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(15470, 'Breva d3 10.000 i.u. 30 tabs.', 'بريفا دي3 10000 وحدة دولية 30 قرص', '100', '250', 'Cholecalciferol', 'Medcare > vortex pharmaceuticals', 'Tab', 'أقراص', 'فيتامين دال', 'Vitamin d', '', 'Cholecalciferol use is indicated for the treatment of specific medical conditions like refractory rickets (or vitamin D resistant rickets), hypoparathyroidism, and familial hypophosphatemia [F4027, F4042].
Concurrently, as one of the most commonly utilized forms of vitamin D, cholecalciferol is also very frequently used as a supplement in individuals to maintain sufficient vitamin d levels in the body or to treat vitamin D deficiency, as well as various medical conditions that can be associated directly or indirectly with vitamin d insufficiency like osteoporosis and chronic kidney disease, among others [A176041, A176044, F4051].', '6224001079443', '', 4918, '2025-04-20', CURRENT_TIMESTAMP),
(1818, 'Heptafolice 20 tabs', 'هيبتافوليك 20 قرص', '', '55', 'FOLICE ACID + VITAMIN B 12', 'Hepta pharma', 'Tab', 'أقراص', '', 'Folic acide', '', '', '', '', 847, '2024-12-16', CURRENT_TIMESTAMP),
(29882, 'Zepexene 5 mg 10 caps. (n/a)', 'زيبكسين 5مجم 10 كبسول', '', '2', 'Potassium clorazepate', 'Hi-pharm', 'Cap', 'كبسولة', '', 'Anti-epileptic.benzodiazepines', '5 mg', 'For use as an electrolyte replenisher and in the treatment of hypokalemia.', '', '', 763, '2022-07-15', CURRENT_TIMESTAMP),
(32836, 'Famferrin 30 caps.', 'فامفيرين 30 كبسولة', '255', '285', 'Lactoferrin+vitamin c+iron', 'Trendy company', 'Cap', 'كبسولة', '', 'Iron supplement', '', 'lactoferrin ... 100 mg vitamin c ... 500 mg iron ... 14 mg', '6224011149075', '', 657, '2025-01-22', CURRENT_TIMESTAMP),
(10007, 'Aaa', 'ششش', '', '40', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 734, '2023-01-11', CURRENT_TIMESTAMP),
(11335, 'Prominexil 120 ml lotion', 'برومينكسيل لوشن 120 مل', '180', '230', 'Aminixeil+procapil+fiberhance bm solution+caffeine 5%+keratin+collagen+rosemary+saw palmetto+panthenol+argan / jojoba /olive oile', 'United scientific office ( uso pharma )', 'Lotion', 'لوشن', '', 'Anti hair loss', '120 ml', '', '', '', 1014, '2025-08-04', CURRENT_TIMESTAMP),
(29709, 'Xanoxiban 10 mg 10 f.c. tabs.', 'زانوكسيبان 10مجم 10 اقراص', '', '130', 'Rivaroxaban', 'Hikma pharma', 'Tab', 'أقراص', '', 'Antiplatelet.direct factor xa inhibitor', '10 mg', 'Rivaroxaban is indicated for the prevention of venous thromboembolic events (VTE) in patients who have undergone total hips replacements and total knee replacement surgery; prevention of stroke and systemic embolism in patients with nonvalvular atrial fibrillation; treatment of deep vein thrombosis (DVT) and pulmonary embolism (PE); to reduce risk of recurrent DVT and/or PE. Rivaroxaban is also indicated, in combination with aspirin, for reducing the risk of major cardiovascular events in patients with chronic coronary artery disease or peripheral artery disease. Its use is also not recommended in those with severe renal impairment (<30mL/min).[L12819]
Rivaroxaban is also indicated for the treatment and prevention of VTE in pediatric patients (from birth to 18 years of age) and for thromboprophylaxis in pediatric patients ≥2 years old with congenital heart disease following the Fontan procedure.[L12819]', '', '', 918, '2022-07-16', CURRENT_TIMESTAMP),
(19254, 'Fabuglycina syrup 120 ml', 'فابوجليسينا شراب 120 مل', '', '45', 'Iron', 'Praxo pharm', 'Syrup', 'شراب', '', 'Iron supplement', '120 ml', 'For treatment of patients with documented iron deficiency in whom oral administration is unsatisfactory or impossible. Also used to replenish body iron stores in Non-Dialysis Dependent-Chronic Kidney Disease (NDD-CKD) patients receiving or not receiving erythropoietin and in Hemodialysis Dependent (HDD-CKD) and Peritoneal Dialysis Dependent (PDD-CKD) - Chronic Kidney Disease patients receiving an erythropoietin.', '', '', 801, '2022-07-18', CURRENT_TIMESTAMP),
(20897, 'Intest-relief 220mg/5ml susp.', 'انتيست-ريليف 220 مجم / 5 مل معلق', '', '4', 'Nifuroxazide', 'Multi-apex', 'Susp', 'معلق', '', 'Antidiarrheal', '220mg', 'indications infectious diarrhea in children and adults chronic colitis enterocolitis as an adjunctive treatment in combined therapy of intestinal dysbiosis. contraindication hypersensitivity to 5-nitrofurane derivatives and/or other components of the drug', '', '', 814, '2022-07-13', CURRENT_TIMESTAMP),
(16005, 'Cefdin 125mg/5ml susp. 60ml', 'سيفدين 125مجم/5مل معلق 60 مل', '', '34', 'Cefdinir', 'Novartis', 'Susp', 'معلق', '', 'Antibiotic.cephalosporin.third-generation', '125mg', 'Cefdinir is indicated to treat acute bacterial otitis media, acute maxillary sinusitis, community-acquired (CA) pneumonia, acute bacterial exacerbations of chronic bronchitis, pharyngitis/tonsillitis, and uncomplicated skin and skin structure infections in children and adults.[L7330,A180739]
The organisms susceptible to cefdinir have been listed below in addition to their associated clinical condition that may be treated with cefdinir.[L7330] Various beta-lactamase producing organisms may be treated, as indicated in certain sections below.
**Respiratory**
Acute bacterial exacerbations of chronic bronchitis caused by Haemophilus influenzae, Haemophilus parainfluenzae, Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
Community-acquired pneumonia caused by Haemophilus influenzae, Haemophilus parainfluenzae, Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
**Ear, nose, and throat** 
Acute bacterial otitis media caused by Haemophilus influenzae, Moraxella catarrhalis, and Streptococcus pneumoniae (penicillin-susceptible only)
Tonsillitis caused by Streptococcus pyogenes
Pharyngitis caused by Streptococcus pyogenes
Acute maxillary sinusitis caused by Haemophilus pneumoniae and Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
