(23585, 'Nifurox 200mg/5ml 100ml susp.', 'نيفيوروكس 200مجم/5مل 100 مل معلق', '14', '23', 'Nifuroxazide', 'Eipico', 'Susp', 'معلق', '', 'Antidiarrheal', '200mg', '', '6221032222220', '', 936, '2025-08-23', CURRENT_TIMESTAMP),
(12579, 'Futaparky 25/250 mg 30 tabs', 'فوتاباركي 25/250مجم 30 قرص', '117', '153', 'Carbidopa+levodopa', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', 'داء يستخدم فى علاج مرض الشلل الرعاش', 'Parkinson s disease.dopamine agonist', '250 mg', '', '6223004190193', '', 1222, '2025-04-19', CURRENT_TIMESTAMP),
(2135, 'Resvagil vag. gel 30 ml', 'ريسافاجيل جل مهبلي 30 مل', '455', '475', '', 'Abbott', 'Gel', 'جل', '', 'Vaginal care', '30 ml', '', '', '', 1090, '2025-11-06', CURRENT_TIMESTAMP),
(15411, 'Boilz shampoo 120 ml', 'بويلز شامبو 120 مل', '', '42', '', 'Egyptian company for cosmetics > compete pharm', 'Amp', 'أمبول', 'شامبو لنظافة الشعر __ العناية بالشعر __ الحفاظ علي نعومة وعدم تقصف الشعر', 'Hair care', '120 ml', 'anti-dandruff', '', '', 2016, '2022-04-12', CURRENT_TIMESTAMP),
(13246, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 762, '2022-07-08', CURRENT_TIMESTAMP),
(607, 'Vitosel syrup 30 ml', 'فيتوسيل شراب 30 مل', '70', '110', 'Lactoferrin+ferrus fumerate+colostrum+vitamins', 'Med care > drug pharma egypt', 'Syrup', 'شراب', '', 'Iron supplement', '30 ml', '', '', '', 1232, '2025-08-13', CURRENT_TIMESTAMP),
(31596, 'Vitamin d3 2400 i.u./ml oral drops 30 ml', 'فيتامين د3 2400وحدةمل نقط بالفم 30 مل', '26.5', '45', 'Cholecalciferol(vitamin d3)', 'Napco', 'Drops', 'نقط', '', 'Vitamin d', '30 ml', 'description derivative of 7-dehydroxycholesterol formed by ultraviolet rays breaking of the c9-c10 bond. it differs from ergocalciferol in having a single bond between c22 and c23 and lacking a methyl group at c24 indication for the treatment of vitamin d', '', '', 945, '2024-03-25', CURRENT_TIMESTAMP),
(31853, 'Aaa', 'ششش', '270', '370', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 587, '2024-03-02', CURRENT_TIMESTAMP),
(22884, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 714, '2023-02-09', CURRENT_TIMESTAMP),
(13647, 'Aldara 5% cream 12 sachets', 'الدارا 5% كريم 12 كيس', '615', '879', 'Imiquimod', 'Meda ab > multipharma', 'Cream', 'كريم', '', 'Immune response modifier', '5%', 'For the topical treatment of clinically typical, nonhyperkeratotic, nonhypertrophic actinic keratoses on the face or scalp in immunocompetent adults. Also indicated for the treatment of external genital and perianal warts/condyloma acuminata in individuals 12 years old and above.', '', '', 3607, '2025-09-10', CURRENT_TIMESTAMP),
(19098, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 741, '2022-07-18', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(20888, 'Integrado hair loss shampoo 200 ml', 'انتجرادو شامبو لتساقط الشعر', '200', '250', 'Capalgin + hydrolyzed wheat protein + hydrolyzed keratin + procapil + rosemary extract + plandool g + saw plametto', 'Egyptian co. for cosmetics > orchidia pharmaceutical industries', 'Amp', 'أمبول', 'لتساقط الشعر', 'Hair fall', '200 ml', 'integrado anti-hair loss shampoo is designed for both women & men affected by temporary and premature hair loss. it effectively helps in prevent-ing hair loss caused by stress fatigue general weakness or after pregnancy. itï-s suitable for all types of sc', '', '', 1065, '2025-03-09', CURRENT_TIMESTAMP),
(4806, 'Siva soft topical lotion 120 ml', 'سيفا سوفت لوشن 120 مل', '', '60', 'Calamine+zinc oxide+aloe vera extract+olive oil+jojoba oil+tea tree oil+beeswax+allantoin+glycerin', 'Alpha bio pharm', 'Lotion', 'لوشن', '', 'Skin care.soothing', '120 ml', '', '', '', 730, '2025-06-21', CURRENT_TIMESTAMP),
(28969, 'Vanihair 11.5 % topical cream 15 gm', 'فانيهير 11.5% كريم 15 جرام', '', '75', 'Eflornithine', 'Biopharm egypt', 'Cream', 'كريم', '', 'Hirsutism', '11.5 %', 'Eflornithine is indicated to reduce the risk of relapse in adult and pediatric patients with high-risk neuroblastoma (HRNB) who have demonstrated at least a partial response to prior multiagent, multimodality therapy including anti-GD2 immunotherapy.[L49288]  It was also previously indicated for the treatment of female hirsutism and African trypanosomiasis but has since been discontinued.[L49318]', '', '', 1287, '2022-06-18', CURRENT_TIMESTAMP),
(8474, 'Vonopravin 10 mg 28 f.c. tab', 'فونوبرافين 10مجم 28 قرص', '117', '172', 'Vonoprazan', 'Future pharmaceutical industries (fpi) > utopia', 'Tab', 'أقراص', '', 'Peptic ulcer.potassium-competitive acid blocker', '10 mg', 'Vonoprazan is indicated for the following conditions: 
- for healing of all grades of erosive esophagitis and relief of heartburn associated with erosive esophagitis in adults.[L51224]
- to maintain healing of all grades of erosive esophagitis and relief of heartburn associated with erosive esophagitis in adults.[L51224]
- for the relief of heartburn associated with non-erosive gastroesophageal reflux disease in adults.[L51224]
- in combination with [amoxicillin] and [clarithromycin] for the treatment of Helicobacter pylori (_H. pylori_) infection in adults.[L41695, L51224]
- in combination with amoxicillin for the treatment of H. pylori infection in adults.[L51224]', '6224009687909', '', 2384, '2024-11-16', CURRENT_TIMESTAMP),
(14802, 'Azgoclatens ophth. sol. 5ml', 'ازجوكلاتينس محلول معقم للعين 5 مل', '', '39', 'Brimonidine+timolol', 'Grand pharma > apic', 'Sol', 'محلول', '', 'Antiglaucoma', '5ml', '', '', '', 926, '2022-07-08', CURRENT_TIMESTAMP),
(24760, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 717, '2022-07-18', CURRENT_TIMESTAMP),
(23347, 'Negacef 1 gm i.v. vial', 'نيجاسيف 1جم فيال', '', '15', 'Ceftazidime', 'Julphar', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '1 gm', 'Ceftazidime is indicated for the treatment of lower respiratory tract infections, skin and skin structure infections, urinary tract infections, bacterial septicemia, bone and joint infections, gynecologic infections, intra-abdominal infections (including peritonitis), and central nervous system infections (including meningitis) caused by susceptible bacteria.[L32935]
Ceftazidime is indicated in combination with [avibactam] to treat infections caused by susceptible Gram-negative organisms, including complicated intra-abdominal infections (cIAI), in conjunction with [metronidazole], and complicated urinary tract infections (cUTI), including pyelonephritis, in patients aged three months and older. This combination is also indicated to treat hospital-acquired and ventilator-associated bacterial pneumonia (HABP/VABP) in patients aged 18 years and older.[L45128]
In all cases, to mitigate the risk of bacterial resistance and preserve clinical efficacy, ceftazidime should only be used for infections that are confirmed or strongly suspected to be caused by susceptible bacterial strains.[L32935, L45128]', '', '', 877, '2022-07-18', CURRENT_TIMESTAMP),
(28617, 'Tussistop 30mg/5ml syrup 100 ml', 'توسيستوب شراب للكحة', '32.5', '49', 'Levodropropizine', 'Atco pharma', 'Syrup', 'شراب', '- مهديء للكحة والسعال', 'Anti-cough.antitussive', '30mg', '', '6223004048005', '', 25095, '2024-08-20', CURRENT_TIMESTAMP),
(24836, 'Pharmaceris w-whitening foam eye and face cleansing puri-albucin i 150 ml', 'فارماسيرزمستحضر تفتيح البقع الداكنة مناسب لتفتيح أثار الحبوب 150 مل', '', '185', '', 'Laboratorium kosmetyczne dr irena eris sp. z o.o. > multitrade', 'Foam', 'فوم', '', 'Whitening topical', '150 ml', 'indications: gentle foam is recommended for daily cleansing of the face and eye area. replaces traditional soap. action: effectively cleanses the skin removing any impurities and make-up residues. a complex of active ingredients (vitamin pp acerola) brigh', '', '', 793, '2022-08-02', CURRENT_TIMESTAMP),
(28675, 'Ultra zinc 30 tabs', 'الترا زنك 30 قرص', '', '40', 'Zinc+copper', 'Vitabiotics', 'Tab', 'أقراص', 'مكمل غذائي غني بالزنك', 'Zinc supplement', '', '', '6224001078293', '', 5027, '2022-05-31', CURRENT_TIMESTAMP),
(32222, 'Sodium bicarb 1000mg 30 capsules', 'صوديوم بايكارب 1000مجم 30 كبسولة', '90', '110', 'Sodium bicarbonate', 'Biomed', 'Capsule', 'كبسولة', '', 'Alkalinizer', '1000mg', 'Sodium bicarbonate is used for the treatment of metabolic acidosis which may occur in severe renal disease, uncontrolled diabetes, circulatory insufficiency due to shock or severe dehydration, extracorporeal circulation of blood, cardiac arrest and severe primary lactic acidosis. Also is indicated in severe diarrhea which is often accompanied by a significant loss of bicarbonate. Further indicated in the treatment of certain drug intoxications, including barbiturates (where dissociation of the barbiturateprotein complex is desired), in poisoning by salicylates or methyl alcohol and in hemolytic reactions requiring alkalinization of the urine to diminish nephrotoxicity of blood pigments.', '793591680040', '', 1216, '2025-11-13', CURRENT_TIMESTAMP),
(20016, 'Gonal-f 150 i.u. pen', 'جونال-اف 150 وحدة دولية قلم', '', '200', 'Follitropin alfa', 'Serono-switzerland > united company for trading & distribution', 'Pen', 'قلم', '', 'Infertility drugs.follicle stimulating hormone', '', 'In women having been diagnosed with primary ovarian failure, it is used in combination with human chorionic gonadotropin (hCG) to assist in ovulation and fertility. In men with hypogonadotrophic hypogonadism, it is used to induce spermatogenesis. Follitropin may also be used to cause the ovary to produce several follicles, which can then be harvested for use in gamete intrafallopian transfer (GIFT) or in vitro fertilization (IVF).', '', '', 3422, '2022-02-18', CURRENT_TIMESTAMP),
(11200, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 791, '2023-04-27', CURRENT_TIMESTAMP),
(15511, 'Broncal 8mg s.r.20 caps.', 'برونكال اس ار 8 مجم 20 كبسولة', '', '19', 'Salbutamol', 'Hikma pharma', 'Cap', 'كبسولة', '', 'Bronchodilator', '8mg', 'about salbutamol beta2-adrenergic agonist phenethylamine derivative bronchodilator(antiasthma) uterine relaxant. mechanism of action of salbutamol salbutamol is a short acting ?2 receptor agonist. it selectively stimulates ?2 receptors present in airway u', '', '', 1008, '2022-07-20', CURRENT_TIMESTAMP),
(15093, 'Berirab p 300i.u./2ml i.m inj.', 'بيريراب بي 300 وحدة / 2 مل', '', '480', 'Rabies immune globulin (human)', 'Csl behering-gmbh -germany > 2s pharma group', 'Inj', 'حقن', '', 'Immunoglobulin', '2ml', 'Inactivated rabies virus antigen B is indicated for pre- and post-exposure prophylaxis against rabies.[L12795]', '', '', 805, '2022-07-27', CURRENT_TIMESTAMP),
(10400, 'Yarnax massage gel 50 gm', 'يارناكس مساج جل 50 جم', '', '50', '', 'Great pharma group', 'Gel', 'جل', '', 'Massage', '50 gm', '', '6224008232100', '', 798, '2022-02-22', CURRENT_TIMESTAMP),
(8865, 'Bilangavit 20 tabs', 'بيلانجافيت 20 قرص', '120', '140', 'Vitamin', 'Good health', 'Tab', 'أقراص', '', 'Multivitamins', '', 'For the treatment of vitamin A deficiency.', '', '', 1413, '2025-09-28', CURRENT_TIMESTAMP),
(14577, 'Atracurium besylate 25 mg/2.5ml (50mg) 5 amps.', 'اتراكوريوم بيسيلات 25 مجم / 2.5 مل 5 امبولات', '', '94', 'Atracurium besylate', 'Hospira inc.-uk > pfizer scientific office', 'Amp', 'أمبول', '', 'General anaesthesia', '25 mg', 'For use, as an adjunct to general anesthesia, to facilitate endotracheal intubation and to provide skeletal muscle relaxation during surgery or mechanical ventilation.', '', '', 881, '2022-07-21', CURRENT_TIMESTAMP),
(18340, 'Enteromycin dry 60 ml syrup', 'انتيرومايسين شراب جاف 60 مل', '', '5', 'Alumina gel+clioquinol+streptomycin', 'El nile.', 'Syrup', 'شراب', 'علاج حمى الأرانب -- الحفاظ على صحة الجهاز الهضمي -- لعلاج الإسهال الناتج عن عدوى بكتيرية', 'Antidiarrheal', '60 ml', '', '', '', 1144, '2023-04-27', CURRENT_TIMESTAMP),
(21704, 'Aaa', 'ششش', '', '46', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 624, '2022-10-09', CURRENT_TIMESTAMP),
(32009, 'Aaa', 'ششش', '160', '220', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 522, '2024-03-02', CURRENT_TIMESTAMP),
(9707, 'Aaa', 'ششش', '', '12', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 624, '2022-09-21', CURRENT_TIMESTAMP),
(13877, 'Alzimer 5mg 10 f.c. tab.', 'الزيمير 5مجم 10 قرص', '', '76', 'Donepezil', 'Amoun', 'Tab', 'أقراص', '', 'Central acetylcholinesterase inhibitor', '5mg', 'Donepezil, administered orally[L7916] or via transdermal delivery system,[L41125] is indicated for the treatment of dementia of the Alzheimer''s type. It is also available as an extended-release capsule in combination with [memantine] for the treatment of moderate-to-severe dementia of the Alzheimer''s type in patients previously stabilized on 10mg of donepezil hydrochloride once daily.[L7937] 
Off-label uses include the management of vascular dementia, Parkinson''s Disease-associated dementia, and Lewy body dementia, amongst others.[A182333,T668]', '', '', 829, '2022-07-09', CURRENT_TIMESTAMP),
(29838, 'Zapimert 30mg 30 f.c. tabs.', 'زابيمرت 30مجم 30 قرص', '126', '165', 'Mirtazapine', 'Debeiky > growth pharma', 'Tab', 'أقراص', 'مهدئ -- علاج الامراض النفسية -- مضاد للاكتئاب -- يؤخذ تحت اشراف طبي', 'Psychiatric.antidepressants', '30mg', 'This drug is indicated for the treatment of major depressive disorder and its associated symptoms.[FDA label]
Mirtazapine has been used off-label for a variety of conditions including panic disorder, generalized anxiety disorder, dysthymia, tension headaches, hot flushes, post-traumatic stress disorder (PTSD), sleep disorders, substance abuse disorders, and sexual disorders, among others.[A177811,A177946]', '6224009664238', '', 5253, '2024-09-25', CURRENT_TIMESTAMP),
(21058, 'Itorisperidone 4 mg 30 f.c. tabs.', 'ايتوريسبيريدون 4 مجم 30 قرص', '', '78', 'Risperidone', 'Sigma > international trading office', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '4 mg', 'Risperidone is indicated for the treatment of schizophrenia [L12885,L44692,L46297] and irritability associated with autistic disorder.[L12885] It is also indicated as monotherapy, or adjunctly with lithium or valproic acid, for the treatment of acute mania or mixed episodes associated with bipolar I disorder.[L12885,L44692]
Risperidone is additionally indicated in Canada for the short-term symptomatic management of aggression or psychotic symptoms in patients with severe dementia of the Alzheimer type unresponsive to nonpharmacological approaches.[L12906]
Risperidone is also used off-label for a number of conditions including as an adjunct to antidepressants in treatment-resistant depression.[A177226]', '', '', 759, '2022-07-12', CURRENT_TIMESTAMP),
(18075, 'Edemex 0.25mg/ml 3 amp. i.m/i.v', 'اديمكس 0.25 مجم/مل 3 امبولات حقن عضل/وريد', '', '7', 'Bumetanide', 'Memphis', 'Amp', 'أمبول', 'مُدر للبول', 'Diuretic.loop', '0.25mg', 'For the treatment of edema associated with congestive heart failure, hepatic and renal disease including the nephrotic syndrome.', '', '', 994, '2022-08-18', CURRENT_TIMESTAMP),
(25606, 'Folicatoon 30 f.c. tabs.', 'فوليكاتون 30 قرص', '85', '105', 'Folic acid+vitamin b12', 'Organix', 'Tab', 'أقراص', 'مكمل غذائى لعلاج الانيميا ودعم الجهاز العصبى والمناعى للجسم وامداد الجسم بالطاقة', 'Folic acid.anemia', '', 'Folic acid is indicated for the treatment of folic acid deficiency, megaloblastic anemia, and in anemias of nutritional origins, pregnancy, infancy, or childhood.', '6225000490833', '', 6932, '2025-08-18', CURRENT_TIMESTAMP),
