(4055, 'Benmuv massage spray 200 ml', 'بنموف مساج سبراي 200 مل', '260', '290', '', 'Acino', 'Spray', 'بخاخ', '', 'Massage', '200 ml', '', '6225000666924', '', 1353, '2025-11-17', CURRENT_TIMESTAMP),
(16155, 'Cerebroforte 20% syrup 120ml', 'سيربروفورت شراب 120 مل', '47', '62', 'Piracetam', 'Unipharma co.', 'Syrup', 'شراب', 'علاج انخفاض التركيز وضعف الذاكرة', 'Cerebral circulatory inhancer', '20%', 'Indicated in adult patients suffering from myoclonus of cortical origin, irrespective of aetiology, and should be used in combination with other anti-myoclonic therapies [L1125].', '6224000730468', '', 3593, '2024-08-30', CURRENT_TIMESTAMP),
(30068, 'Zyvox 100mg/5ml granules for oral susp. 150ml', 'زيفوكس 100مجم/5مل حبيبات لعمل معلق 150مل', '', '1,600', 'Linezolid', 'Fresenius kabi > pfizer', 'Susp', 'معلق', '', 'Antibiotic.oxazolidinone', '100mg', 'Linezolid is indicated in adults and children for the treatment of infections caused by susceptible Gram-positive bacteria, including nosocomial pneumonia, community-acquired pneumonia, skin and skin structure infections, and vancomycin-resistant _Enterococcus faecium_ infections.[L32965] Examples of susceptible bacteria include _Staphylococcus aureus_, _Streptococcus pneumoniae_, _Streptococcus pyogenes_, and _Streptococcus agalactiae_.[L32965]
Linezolid is not indicated for the treatment of Gram-negative infections, nor has it been evaluated for use longer than 28 days.[L32965]', '', '', 910, '2022-07-13', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(27690, 'Sunsense face tint cream 75 gm', 'صنسينس تنت للوجه كريم 75 جم', '', '391', '', 'Ego pharmaceuticals pty ltd. > vamer pharma', 'Cream', 'كريم', '', 'Sun block', '75 gm', '', '', '', 595, '2022-08-04', CURRENT_TIMESTAMP),
(12640, 'Wintriaxone 1gm pd. for i.v inj.', 'وينترياكسون 1جم حقن وريد', '29', '48', 'Ceftriaxone', 'Sanofi', 'Inj', 'حقن', 'مضاد حيوي', 'Antibiotic.cephalosporin.third-generation', '1gm', 'Ceftriaxone is used for the treatment of the infections (respiratory, skin, soft tissue, UTI, ENT) caused by susceptible organisms.[L15082] Organisms that are generally susceptible to ceftriaxone include S. pneumoniae, S. pyogenes (group A beta-hemolytic streptococci), coagulase-negative staphylococci, Some Enterobacter spp, H. influenzae, N. gonorrhoeae, P. mirabilis, E. coli, Klebsiella spp, M. catarrhalis, B. burgdorferi, and some oral anaerobes.[A215582]', '', '', 3036, '2024-11-08', CURRENT_TIMESTAMP),
(5578, 'Globacin 400mg 10 coated tab.', 'جلوباسين 400مجم 10 اقراص', '', '30', 'Pefloxacin', 'Global napi pharmaceuticals', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '400mg', 'For the treatment of uncomplicated gonococcal urethritis in males and for gram-negative-bacterial infections in the gastrointestinal system and the genitourinary tract.', '', '', 780, '2022-12-30', CURRENT_TIMESTAMP),
(27113, 'Snapgab 300 mg 30 caps.', 'سنابجاب 300مجم 30 كبسول', '', '114', 'Pregabalin', 'Mash premiere > ta pharma', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '300 mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 849, '2022-07-17', CURRENT_TIMESTAMP),
(2636, 'Ciprodiazole 500/500mg 20 f.c. tabs', 'سيبروديازول 500/500مجم 20 قرص', '103', '148', 'Ciprofloxacin+metronidazole', 'Mina pharm', 'Tab', 'أقراص', 'مضاد حيوى واسع المدى يستخدم لعلاج الالتهابات التنفسية والتهابات المسالك البولية وعلاج البكتيريا اللاهوائية', 'Antibiotic quinolone with antiprotozoal', '500mg', '', '6222003702420', '', 21135, '2024-06-27', CURRENT_TIMESTAMP),
(19829, 'Omega a.i.t. 30 cap.s', 'اوميجا ايه اي تي 30 كبسولة', '', '135', 'Omega oil+wheat germ oil', 'Acdima international trading', 'Cap', 'كبسولة', '', 'Omega 3', '', '', '6224000588816', '', 2711, '2024-05-31', CURRENT_TIMESTAMP),
(15766, 'Candistan 100 mg 6 vag. tabs.', 'كانديستان 100مجم 6 اقراص مهبلي', '', '9', 'Clotrimazole', 'Arab drug company.', 'Tab', 'أقراص', '', 'Antifungals.imidazoles', '100 mg', '**Topical preparations**
Clotrimazole topical cream is indicated for the topical treatment of the following dermal infections [F3088], [F3121]:
Tinea pedis, tinea cruris, and tinea corporis due to _Trichophyton rubrum_, _Trichophyton mentagrophytes_, _Epidermophyton floccosum_
Candidiasis due to _Candida albicans_
Tinea versicolor due to _Malassezia furfur_
Diaper rash infected by _Candida albicans_
In some preparations, clotrimazole may be combined with betamethasone dipropionate, a corticosteroid [F3121]. 
**Oral preparations**
The oral troche preparation is indicated for the local treatment of oropharyngeal candidiasis [FDA label].  It is also indicated as a prophylactic drug to reduce the incidence of oropharyngeal candidiasis in patients immunocompromised by conditions such as chemotherapy, radiotherapy, or steroid therapy utilized in the treatment of leukemia, solid tumors, or renal transplantation [FDA label]. Troche preparations are not indicated for the treatment of any systemic mycoses [FDA label].', '6221060000272', '', 852, '2023-04-17', CURRENT_TIMESTAMP),
(3601, 'Diamox 250 mg 24 cap', 'دياموكس 250 مجم 24 كبسولة', '', '135', 'Acetazolamide', 'Avet lifesciences', 'Cap', 'كبسولة', 'علاج ارتفاع ضغط العين', 'Diuretic.carbonic anhydrase inhibitors', '250 mg', 'For adjunctive treatment of: edema due to congestive heart failure; drug-induced edema; centrencephalic epilepsies; chronic simple (open-angle) glaucoma', '', '', 4734, '2022-05-28', CURRENT_TIMESTAMP),
(25347, 'Promostatin 3.75 gm 30 sachets', 'بروموستاتين 3.75جم 30 اكياس', '', '522', 'Colesevelam', 'Al esraa pharmaceutical optima', 'Sachet', 'أكياس', '', 'Bile acid sequestrant', '3.75 gm', 'For use, alone or in combination with an HMG-CoA reductase inhibitor, as adjunctive therapy to diet and exercise for the reduction of elevated LDL cholesterol in patients with primary hypercholesterolemia (Fredrickson Type IIa).', '', '', 796, '2022-07-11', CURRENT_TIMESTAMP),
(14611, 'Aubagio 14 mg 28 tab', 'اوباجيو 14مجم 28 قرص', '', '16,000', 'Teriflunomide', 'Sanofi winthrop > sanofi', 'Tab', 'أقراص', '', 'Immunosuppressants', '14 mg', 'Used in the treatment of relapsing forms of multiple sclerosis (MS).', '', '', 2742, '2022-07-05', CURRENT_TIMESTAMP),
(14095, 'Analgex oblong 500mg 200 f.c. tab.', 'انالجكس اوبلونج 500 مجم 200 قرص', '100', '260', 'Dipyrone(metamizole)', 'Alexandria', 'Tab', 'أقراص', '', 'Antipyretic', '500mg', '', '6223000170960', '', 1093, '2024-11-10', CURRENT_TIMESTAMP),
(13026, 'Aaa', 'ششش', '', '26', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 698, '2022-09-22', CURRENT_TIMESTAMP),
(24796, 'Pharmaceris e-emotopic special lipid-replenishing cream 75 ml', 'فارماسيرز اي كريم 75مل', '', '140', '', 'Laboratorium kosmetyczne dr irena eris sp. z o.o. > multitrade', 'Cream', 'كريم', '', 'Skin care', '75 ml', 'indications recommended for very dry sensitive and atopic skin prone to irritation microdamage and redness as well as itching and burning. recommended for people with atopic dermatitis regardless of age. for conditioning use in people during and after der', '', '', 674, '2022-08-02', CURRENT_TIMESTAMP),
(6484, 'Perfection eye contour cream 30g', 'بيرفكشن كريم لمحيط العين 30 جم', '', '150', 'Vitamin c+vitamin e+liquorice+hydrolyzed collagen+hydrolyzed elastine+and ecoslim caffeine', 'Perfection pharmaceuticals', 'Cream', 'كريم', '', 'Skin care.eye contour', '', 'For the treatment of vitamin A deficiency.', '', '', 764, '2022-08-03', CURRENT_TIMESTAMP),
(5626, 'Glucose 20% (otsuka) i.v. inf. 500 ml (rubber cap)', 'جلوكوز 20% اوتوسوكا محلول وريدي 500 مل زجاجة بغطاء مطاطي', '', '11', 'Glucose (dextrose)', 'Otsuka', 'Cap', 'كبسولة', '', 'Sterile solution', '20%', '', '', '', 1081, '2022-12-05', CURRENT_TIMESTAMP),
(26673, 'Sedacoron 200mg 20 tab.', 'سيداكورون 200مجم 20 اقراص', '', '11', 'Amiodarone', 'Sandoz > b.p pharma', 'Tab', 'أقراص', '', 'Antiarrhythmias.class iii', '200mg', 'The FDA approved indications for amiodarone are recurrent ventricular fibrillation (VF) and recurrent hemodynamically unstable ventricular tachycardia (VT). The FDA emphasizes that this drug should only be given in these conditions when they are clinically documented and have not responded to normal therapeutic doses of other antiarrhythmic agents, or when other drugs are not tolerated by the patient.[L3561]
Off-label indications include atrial fibrillation and supraventricular tachycardia.[A189666,A189720,A189723,L11286]', '', '', 1166, '2022-07-12', CURRENT_TIMESTAMP),
(20599, 'Hydro soap 80 gm', 'هيدرو صابونة 80 جم', '48', '60', '', 'Hi-care > roventis pharma', 'Soap', 'صابون', '', 'Soap', '80 gm', '*for sensitive & dry skin *prevent itching. *rich moisturizing.', '', '', 1541, '2025-07-03', CURRENT_TIMESTAMP),
(11626, 'Tri tect antiseptic soap 100 gm', 'تراي تيكت صابونة المطهرة 100 جم', '50', '60', '', 'Dr. chabrawichi factories > macro group pharmaceuticals', 'Soap', 'صابون', '', 'Soap', '100 gm', 'medicated soap contains a unique blend of antiseptic compounds that clean skin and eliminate germs bacteria fungi viruses & unpleasant body odors. - tritect antiseptic soap is advised to be used in:- * all dermatological cases requiring the use of antisep', '6224000437305', '', 1219, '2025-03-04', CURRENT_TIMESTAMP),
(31895, 'Devart c-zinc 20 chew. tabs.', 'ديفارت سي زينك 20 قرص', '', '65', 'Vitamin c+zinc', 'Devartlab pharma', 'Tab', 'أقراص', 'مكمل غذائى مضاد للاكسدة ويعمل على دعم الجهاز المناعى وصحة البشرة والشعر', 'Zinc supplement', '', 'For the treatment of vitamin A deficiency.', '', '', 1488, '2023-03-08', CURRENT_TIMESTAMP),
(13035, 'Radiance 10 sachets', 'راديانس 10 اكياس', '', '140', 'Collegen hydrolysate', 'Bioactive', 'Sachet', 'أكياس', 'علاج لالتهاب المفاصل والروماتيزم', 'Anti-rheumatic.osteoarthritis.anabolic agents', '', '', '', '', 1665, '2022-09-22', CURRENT_TIMESTAMP),
(21476, 'Kolocurejed 135 mg 20 c. tab.', 'كولوكيورجيد 135 مجم 20 قرص', '', '13', 'Mebeverine', 'Jedco int. co. for pharmaceuticals', 'Tab', 'أقراص', '', 'Antimuscarinic.irritable bowel syndrome', '135 mg', 'about mebeverine reserpine derivative antimuscarinic a musculotropic antispasmodic motility stimulant. mechanism of action of mebeverine mebeverine has a direct relaxant effect on smooth muscle. this will inhibits gastrointestinal propulsive motility and', '', '', 773, '2022-07-20', CURRENT_TIMESTAMP),
(24786, 'Pharco-vap oint.', 'فاركو فاب مرهم', '', '6', 'Camphor+eucalyptus oil+menthol+methyl salicylate+thymol', 'Pharco', 'Oint', 'مرهم', '', '', '', 'mechanism of action of camphor camphor acts as a rubefacient when it is rubbed on the skin and causes localized vasodilatation; which gives feelings of comfort and warmth. when applied gently on the skin it acts as an anti-pruritic agent and creates a fee', '', '', 806, '2022-07-15', CURRENT_TIMESTAMP),
(29606, 'Voxazoldin 2mg/ml iv inf. vial 300 ml', 'فوكسازولدين 2مجم/مل فيال 300 مل حقن وريدي', '120', '255', 'Linezolid', 'Arabcomed-egypt > rotabiogen for pharmaceutical invest.', 'Vial', 'فيال', 'مضاد حيوي', 'Antibiotic.oxazolidinone', '2mg', 'Linezolid is indicated in adults and children for the treatment of infections caused by susceptible Gram-positive bacteria, including nosocomial pneumonia, community-acquired pneumonia, skin and skin structure infections, and vancomycin-resistant _Enterococcus faecium_ infections.[L32965] Examples of susceptible bacteria include _Staphylococcus aureus_, _Streptococcus pneumoniae_, _Streptococcus pyogenes_, and _Streptococcus agalactiae_.[L32965]
Linezolid is not indicated for the treatment of Gram-negative infections, nor has it been evaluated for use longer than 28 days.[L32965]', '', '', 855, '2024-12-07', CURRENT_TIMESTAMP),
(22546, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 704, '2023-01-05', CURRENT_TIMESTAMP),
(25684, 'Rancif 500mg 10 f.c.tab.', 'رانسيف 500مجم 10 اقراص', '48', '69', 'Ciprofloxacin', 'Cid > ranbaxy', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '500mg', 'Ciprofloxacin is only indicated in infections caused by susceptible bacteria.[L6469,L6472,L6475,L6478,L6481,L6484,L6487,L6490,L6493]
Ciprofloxacin immediate release tablets, oral suspensions, and intravenous injections are indicated for the treatment of skin and skin structure infections, bone and joint infections, complicated intra-abdominal infections, nosocomial pneumonia, febrile neutropenia, adults who have inhaled anthrax, plague, chronic bacterial prostatitis, lower respiratory tract infections including acute exacerbations of chronic bronchitis, urinary tract infections, complicated urinary tract infections in pediatrics, complicated pyelonephritis in pediatrics, and acute sinusitis.[L6481,L6478]
A ciprofloxacin otic solution and otic suspension with hydrocortisone are indicated for acute otitis externa.[L6469,L6484] Ciprofloxacin suspension with dexamethasone is indicated for acute otitis media in pediatric patients with tympanostomy tubes or acute otitis externa.[L6490] A ciprofloxacin intratympanic injection is indicated for pediatric patients with bilateral otitis media with effusion who are having tympanostomy tubes placed or pediatric patients 6 months or older with acute otitis externa.[L6493]
A ciprofloxacin eye drop is indicated for bacterial corneal ulcers and conjunctivitis.[L6472] A ciprofloxacin eye ointment is indicated for bacterial conjunctivitis.[L6475]
A ciprofloxacin extended release tablet is indicated for uncomplicated urinary tract infections, complicated urinary tract infections, and acute uncomplicated pyelonephritis.[L6487]', '6224009052035', '', 1115, '2024-10-17', CURRENT_TIMESTAMP),
(20341, 'Aaa', 'ششش', '', '21', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 722, '2022-12-05', CURRENT_TIMESTAMP),
(2798, 'Cloracef mr 500mg 10 f.c. tabs. (n/a)', 'كلوراسيف ام ار 500مجم 10 اقراص', '', '38', 'Cefaclor', 'Dar al dawa development & investment co. > multipharma', 'Tab', 'أقراص', '', 'Antibiotic.cephalosporin.second-generation', '500mg', 'For the treatment of certain infections caused by bacteria such as pneumonia and ear, lung, skin, throat, and urinary tract infections.', '6251107227010', '', 1064, '2023-04-18', CURRENT_TIMESTAMP),
(9369, 'Tronic starpsin 10 tabs', 'ترونيك ستاربسين 10 اقراص', '89', '100', 'Rutosidetrihydrate+bromelain+trpsin', 'Med tronic', 'Tab', 'أقراص', '', 'Anti-inflammatory', '', '', '', '', 1533, '2025-10-29', CURRENT_TIMESTAMP),
(30985, 'Newtone 30 chew. tabs.', 'نيوتون 30 قرص مضغ', '60', '75', 'Vitamins(a+e+d+e+k+c)+vitamin b complex+folic acid+zinc+selenium+chromium+magnesium+potassium', 'Pharmazad > sanvix pharma', 'Tab', 'أقراص', '', 'Multivitamins and minerals', '', 'unique formula designed to improve your immunity and increase your vitality with chocolate flavor and easy to be swallowed or as a chewable tablet.', '', '', 1023, '2024-08-10', CURRENT_TIMESTAMP),
(20960, 'Irinotecan actavis 40mg/2ml vial(n/a)', 'ارينوتيكان اكتافيس 40 مجم / 2 مل فيال', '', '350', 'Irinotecan', 'Actavis > multipharma', 'Vial', 'فيال', '', 'Antineoplastic', '40mg', 'Irinotecan is indicated for the treatment of:
- Metastatic carcinoma of the colon or rectum as first-line treatment in combination with [fluorouracil] and [leucovorin].[L50181, L50201]
