(14476, 'Totimax 150 gm 10 sachets', 'توتيماكس 150 جم 10 اكياس', '95', '95', 'Whey proteinisolate 5gm+full cream milk powder 3 gm+cocoa powder 3gm+sucrose 1gm+lethicin 0.8 gm+dextrose 2 gm+dietary fibers 2gm', 'Bme pharma', 'Sachet', 'أكياس', '', 'Dietarysupplement protein', '150 gm', '', '', '', 1626, '2025-01-14', CURRENT_TIMESTAMP),
(19759, 'Gesiket 75 mg 20 caps.', 'جيسيكيت 75 مجم 20 كبسولة', '', '18', 'Ketoprofen', 'El-obour > atm pharmaceutical industries', 'Cap', 'كبسولة', '', 'Nsaid.propionic acid derivatives', '75 mg', 'For symptomatic treatment of acute and chronic rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, primary dysmenorrhea and mild to moderate pain associated with musculotendinous trauma (sprains and strains), postoperative (including dental surgery) or postpartum pain.', '6225000082809', '', 875, '2022-12-05', CURRENT_TIMESTAMP),
(6031, 'Hepato-forte 30 caps.', 'هيباتو-فورت 30 كبسولة', '24', '81', 'Essential phospholipids+vitamins (b3-b1-b2-b6-b12-e)', 'Safe pharma > amoun', 'Cap', 'كبسولة', 'مدعم للكبد', 'Liver support supplements', '', '', '6221025048233', '', 8754, '2023-09-22', CURRENT_TIMESTAMP),
(33328, 'Omigrand 1230 mg 20 caps.', 'اوميجراند 1230 مجم 20 كبسولة', '75', '105', 'Fish oil 400 mg+flax seed oil 400 mg+borage seed oil 400mg+vit e 30mg', 'Royal group', 'Cap', 'كبسولة', '', 'Multivitamin', '1230 mg', 'Under FDA approval, fish oil pharmaceuticals are typically products consisting of a combination of the omega-3-fatty acids eicosapentaenoic acid (EPA) and docosahexaenoic acid (DHA) and are indicated primarily as an adjunct to diet to reduce triglyceride levels in adult patients with severe (>=500 mg/dL) hypertriglyceridemia [FDA Label, F36].
Under EMA approval, such fish oil pharmaceuticals comprised of virtually the same fish and fish oil derived omega-3-fatty acids EPA and DHA are indicated specifically for (a) adjuvant treatment in secondary prevention after myocardial infarction, in addition to other standard therapy (ie. statins, antiplatelet medicinal products, beta blockers, ACE inhibitors), and (b) as a supplement to diet when dietary measures alone are insufficient to produce an adequate response, particularly with type IV hypertriglyceridemia in monotherapy or type IIb/III in combination with statins, when control of triglycerides is insufficient [L2661]. In addition, prescribing information for EMA approved fish oil pharmaceuticals are also indicated as an adjunct to diet to reduce very high (>=500 mg/dL) triglyceride levels in adult patients, much like similar FDA approved indications [F37, FDA Label].', '', '', 424, '2024-04-12', CURRENT_TIMESTAMP),
(15989, 'Cefause 500mg vial i.m/i.v.', 'سيفايوز 500 مجم فيال', '19.5', '29', 'Cefotaxime', 'Otsuka > badr pharma', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '500mg', 'Used to treat gonorrhoea, meningitis, and severe infections including infections of the kidney (pyelonephritis) and urinary system. Also used before an operation to prevent infection after surgery.', '', '', 1567, '2024-09-27', CURRENT_TIMESTAMP),
(29910, 'Zex cream 120 gm', 'زكس كريم 120جم', '', '80', 'Rutin+caffeine+collagen+elastin+tea tree oil+calndula+aloe vera+vitamin (c+e)+centella extract+grape', 'Leader cosmetics > beauty & beyond international', 'Cream', 'كريم', '', 'Firming topical', '120 gm', 'controls and reduce stretch marks cellulite enhance fat lipolysis and body carving', '', '', 720, '2022-07-30', CURRENT_TIMESTAMP),
(14709, 'Avene micellar lotion cleanser and make-up remover 200ml', 'افين ميسيلار منظف ​200 مل', '', '185', '', 'Pierre - fabre france > biotech egypt', 'Lotion', 'لوشن', '', 'Skin care', '200ml', 'gentle no-rinse cleanser toner and make-up remover (3-in-1). technologically advanced cleansing water removes impurities and make-up. it is based on a micelle principle that protects and releases cleansing agents and softening actives upon contact with sk', '', '', 718, '2022-08-03', CURRENT_TIMESTAMP),
(15577, 'Aaa', 'ششش', '', '24', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 682, '2022-10-30', CURRENT_TIMESTAMP),
(15061, 'Bendamustine-accord 25 mg 5 vials', 'بنداموستين-اكورد 25 مجم 5 فيال', '', '2,000', 'Bendamustine hydrochloride', 'Accord healthcare limited > united group pharmaceutical(u.g.p.)', 'Vial', 'فيال', 'مضاد للاورام', 'Antineoplastic agent.alkylating agent', '25 mg', 'Bendamustine is indicated for use in the treatment of  indolent B-cell non-Hodgkin lymphoma (NHL) that has progressed during or within six months of treatment with [rituximab] or a rituximab-containing regimen.[L50632]
The indication for chronic lymphocytic leukemia (CLL) was removed from the US drug label in April 2024.[L50632]', '', '', 1483, '2022-04-07', CURRENT_TIMESTAMP),
(13436, 'Tetra care hair shampoo 200 ml', 'تيترا كير شامبو للشعر 200 مل', '150', '180', 'CAFFEINE + BIOTIN + JOJOBA EXTRACT + ROSEMARY EXTRAXT + ALO VERA EXTRACT + ALLANTOIN + OLIVE OIL + VIT B3', 'Tetra pharm', 'Amp', 'أمبول', '', 'Anti hair fallen shampoo (zero sulphate)', '200 ml', 'Caffeine is indicated for the short term treatment of apnea of prematurity in infants and off label for the prevention and treatment of bronchopulmonary dysplasia caused by premature birth.[T716,L9851] In addition, it is indicated in combination with sodium benzoate to treat respiratory depression resulting from an overdose with CNS depressant drugs.[L9899] Caffeine has a broad range of over the counter uses, and is found in energy supplements, athletic enhancement products, pain relief products, as well as cosmetic products.[T716,L9854,L9872]', '6225000502345', '', 2740, '2025-01-22', CURRENT_TIMESTAMP),
(20169, 'Aaa', 'ششش', '', '49', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 609, '2022-07-25', CURRENT_TIMESTAMP),
(22744, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 786, '2022-09-10', CURRENT_TIMESTAMP),
(31013, 'Nulivia 10 sachets', 'نوليفيا 10 اكياس', '70', '75', 'Fructo-oligosaccharide', 'Zad pharma > atlas pharmaceutical', 'Sachet', 'أكياس', 'مستحضر غني بالأنولين. يساعد في سلامة الجهاز الهضمي.', 'Prebiotic', '', '', '6222019610627', '', 959, '2023-09-10', CURRENT_TIMESTAMP),
(24779, 'Pevisone cream 15 gm', 'بيفيزون كريم 15 جرام', '', '8', 'Econazole+triamcinolone', 'Mina pharm > janssen cilag', 'Cream', 'كريم', '', 'Antifungal with glucocorticoid', '15 gm', 'side effects of econazole + triamcinolone acetonide 1.burning 2.itching pregnancy related information may be used breast feeding related information use with caution indications for econazole + triamcinolone acetonide skin infections about econazole synth', '6222003700358', '', 1052, '2022-12-08', CURRENT_TIMESTAMP),
(28032, 'Tensofor 7.5mg/ml oral drops 15 ml', 'تنسوفور 7.5مجم/مل نقط للفم 15مل', '8.75', '13', 'Etilefrine', 'Pharopharma', 'Drops', 'نقط', '', 'Hypotension', '7.5mg', 'indications: hypotension- prophylactics of vascular collapse- dumping syndrome- vasomotor headache. drug interactions: the action of etilefrine is increased at its concomitant application with tricyclic antidepressants amantadine isoniazid and theophyllin', '', '', 972, '2024-12-20', CURRENT_TIMESTAMP),
(22182, 'Maddox calcium 20 eff. tabs.', 'مادوكس كالسيوم 20 قرص فوارة', '', '85', 'Calcium', 'Maddox pharma', 'Tab', 'أقراص', '', 'Calcium supplement', '', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 938, '2022-07-07', CURRENT_TIMESTAMP),
(2377, 'Lacto-apex 5 - 20 caps.', 'لاكتو ايبكس 5 - 20 كبسولة', '195', '230', 'Lactoferrin+vitamin c+vitamin d3+zinc+echinacea purpurea', 'Apex pharma', 'Cap', 'كبسولة', '', 'Immunty booster', '', '', '6223003206536', '', 1008, '2024-04-28', CURRENT_TIMESTAMP),
(17244, 'Denora whitening cream 60 gm', 'دينورا كريم تفتيح 60 جم', '', '49', 'Kojic acid+licuorice extract+vitamin c+thyme+wheat germ oil', 'Egyptian company for cosmetics > admin pharma', 'Cream', 'كريم', 'كريم غنى بالفيتامينات ومضادات الاكسدة للتفتيح ومحاربة علامات الشيخوخه', 'Whitening topical', '60 gm', '', '', '', 969, '2022-07-08', CURRENT_TIMESTAMP),
(13933, 'Aminoplasmal 10% i.v.infusion', 'امينوبلازمال 10% محلول وريدي', '75', '109', 'Amino acids', 'B-braun meslungen ag-germany > sunny medical', 'Unknown', 'غير محدد', '', '', '10%', 'about amino acids an amino acid is any molecule that contains both amine and carboxyl functional groups. these amino acids are the basic components of proteins. there are twenty standard amino acids used by cells in protein biosynthesis that are specified', '', '', 959, '2024-11-23', CURRENT_TIMESTAMP),
(19410, 'Fresubin energy fibre 500 ml', 'فريسوبين انرجي فايبر 500 مل', '', '117', 'Fat+carbohydrates+protein', 'Fresenius kabi', 'Unknown', 'غير محدد', 'مكمل غذائي', 'Dietary supplement', '500 ml', '', '', '', 1964, '2022-05-28', CURRENT_TIMESTAMP),
(18847, 'Fast care-d shampoo 120 ml', 'فاست كير-دي شامبو 120 مل', '95', '115', '', 'Leader cosmetics > original pharma group', 'Amp', 'أمبول', '', 'Hair care', '120 ml', 'anti-dandruff', '6224010525177', '', 1206, '2025-01-18', CURRENT_TIMESTAMP),
(25252, 'Primox 15mg 14 f.c.tab.', 'بريموكس 15مجم 14 اقراص', '', '38', 'Moexipril', 'Mina pharm > schwarz', 'Tab', 'أقراص', '', 'Antihypertensive.ace', '15mg', 'For the treatment of hypertension.', '6222003701331', '', 850, '2022-12-08', CURRENT_TIMESTAMP),
(3918, 'Sensajoy acne night gel 50 gm', 'سنساجوي جل مسائي لحب الشباب 50 جم', '200', '230', '', 'Orchidia', 'Gel', 'جل', '', 'Skin care', '50 gm', '', '6223005443861', '', 843, '2025-03-09', CURRENT_TIMESTAMP),
(14877, 'Bactiflox 500mg 10 lactab.', 'باكتيفلوكس 500مجم 10 اقراص', '', '31', 'Ciprofloxacin', 'Mup > acino', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '500mg', 'Ciprofloxacin is only indicated in infections caused by susceptible bacteria.[L6469,L6472,L6475,L6478,L6481,L6484,L6487,L6490,L6493]
Ciprofloxacin immediate release tablets, oral suspensions, and intravenous injections are indicated for the treatment of skin and skin structure infections, bone and joint infections, complicated intra-abdominal infections, nosocomial pneumonia, febrile neutropenia, adults who have inhaled anthrax, plague, chronic bacterial prostatitis, lower respiratory tract infections including acute exacerbations of chronic bronchitis, urinary tract infections, complicated urinary tract infections in pediatrics, complicated pyelonephritis in pediatrics, and acute sinusitis.[L6481,L6478]
A ciprofloxacin otic solution and otic suspension with hydrocortisone are indicated for acute otitis externa.[L6469,L6484] Ciprofloxacin suspension with dexamethasone is indicated for acute otitis media in pediatric patients with tympanostomy tubes or acute otitis externa.[L6490] A ciprofloxacin intratympanic injection is indicated for pediatric patients with bilateral otitis media with effusion who are having tympanostomy tubes placed or pediatric patients 6 months or older with acute otitis externa.[L6493]
A ciprofloxacin eye drop is indicated for bacterial corneal ulcers and conjunctivitis.[L6472] A ciprofloxacin eye ointment is indicated for bacterial conjunctivitis.[L6475]
A ciprofloxacin extended release tablet is indicated for uncomplicated urinary tract infections, complicated urinary tract infections, and acute uncomplicated pyelonephritis.[L6487]', '', '', 1571, '2022-06-25', CURRENT_TIMESTAMP),
(18020, 'Ebastel 10mg 10 tab.', 'ايباستيل 10مجم 10 اقراص', '', '12', 'Ebastine', 'Global napi pharmaceuticals', 'Tab', 'أقراص', 'مضاد للحساسية يستخدم في علاج الحساسية الموسمية', 'Antihistamine.antiallergy', '10mg', 'about ebastine second generation long-acting and selective h1 antagonist non-sedative antihistamine. mechanism of action of ebastine drug and its active metabolite is selective peripheral histamine h1 receptor antagonist. thus it prevents the attachment o', '6223002142392', '', 1659, '2022-12-04', CURRENT_TIMESTAMP),
(5661, 'Glycerin infantile 10 supp. (glaxo)', 'جلسرين لبوس جلاكسو 10 اقماع للاطفال', '10', '19', 'Glycerin', 'Glaxo smithkline', 'Supp', 'لبوس', '', 'Laxative', '', 'It is used as a solvent, emollient, pharmaceutical agent, and sweetening agent.', '6221045001706', '', 4758, '2024-10-21', CURRENT_TIMESTAMP),
(21564, 'Bevato 30 tabs', 'بيفاتو 30 قرص', '285', '335', 'Vit b12+vit b1+vit b6+vit d3+alpha lipoic acid+folate', 'Navigen', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '', '', 2214, '2025-02-26', CURRENT_TIMESTAMP),
(28270, 'Tomed lactoferrin 200mg multivitamin', 'توميد لاكتوفيرين 200مجم 10 اكياس', '190', '210', '200 mg lactoferrin+27 mg iron+50 mg zn+200 mcg folic acid+vitamin c+vitamin ( b1+b6+b12 )', 'Swivel nutrient > wellmed', 'Unknown', 'غير محدد', 'اكياس مصدر للحديد -- علاج الانيميا -- مصدر للطاقة', 'Iron supplement', '200mg', '', '', '', 5087, '2025-12-14', CURRENT_TIMESTAMP),
(12691, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 828, '2022-12-14', CURRENT_TIMESTAMP),
(20735, 'Immuguard 14 sachets', 'اميوجارد 14 اكياس', '135', '195', 'High concentration bovine colostrum+vitamins+minerals', 'Nutrixia > dulex lab', 'Sachet', 'أكياس', 'مقوي للمناعة -- تقليل الاصابة بالامراض التنفسية -- علاج الالتهاب الرئوي', 'Immune enhancer', '', '', '6224007394649', '', 3477, '2025-07-04', CURRENT_TIMESTAMP),
(31812, 'Gleam mix whitening cream 50 gm', 'جليم ميكس كريم تفتيح للبشرة 50 جم', '110', '150', 'Kojic acid+titanium dioxide+alpha arbutin', 'Egyptian company for cosmetics > kmt pharma', 'Cream', 'كريم', 'كريم تفتيح وترطيب البشرة ومحاربة علامات الشيخوخه', 'Skin care.whitening', '50 gm', '', '6224011031196', '', 4305, '2024-06-29', CURRENT_TIMESTAMP),
(757, 'Jelace 20 tablets', 'جيلاس 20 قرص', '', '180', 'Gelatin (collagen) hydrolysate+vitamin c', 'Linkopharm', 'Tablet', 'أقراص', '', 'Anti-rheumatic.osteoarthritis.anabolic agents', '', 'Gelatin is used for weight loss and for treating osteoarthritis, rheumatoid arthritis, and brittle bones (osteoporosis). Some people also use it for strengthening bones, joints, and fingernails. Gelatin is also used for improving hair condition and to shorten the recovery after exercise and sports-related injury [L2113]. Gelatin is used in preparations of foods, cosmetics, and medicine [L2113].
Plasma volume expander in hypovolaemic shock [L2115]. Haemostatic [L2115].
Gelatin-based hydrogels are being used in drug delivery and tissue engineering because they are able to promote cell adhesion and proliferation. In addition, these hydrogels can be used as wound dressings because of their attractive fluid absorbance properties. Manufacturing technologies such as ultraviolet stereolithography and two-photon polymerization can be used to prepare structures containing photosensitive gelatin-based hydrogels [L2111].', '6224008585961', '', 849, '2022-10-27', CURRENT_TIMESTAMP),
(18223, 'Emedrotec 3mg 20 buccal bioadhesive tab.', 'ايمدروتيك 3 مجم 20 قرص', '', '16', 'Prochlorperazine', 'Eva pharma', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '3mg', 'Indicated for the symptomatic treatment of severe nausea and vomiting.[label]
Indicated for the management of manifestations of psychotic disorders, such as schizophrenia and generalized non-psychotic anxiety. The use of prochlorperazine for the management of generalized non-psychotic anxiety is typically not a first-line therapy and should be limited to doses of less than 20 mg per day or for shorter than 12 weeks.[label,L6634]
Off-label uses include use in emergency settings for adult and pediatric migraines. The American Headache Society recommends the use of prochlorperazine as the first-line medication in this setting. In pediatric migraines, a non-steroidal anti-inflammatory agent is often used in combination with dopamine antagonist.[L6637]', '6223002451852', '', 879, '2022-07-13', CURRENT_TIMESTAMP),
(16469, 'Clavucin 625mg 10 f.c.tab.', 'كلافيوسين 625مجم 10 قرص', '', '24', 'Amoxicillin+clavulanic acid', 'T3a pharma', 'Tab', 'أقراص', '', 'Penicillins.penicillin with b-lactamase inhibitor', '625mg', '', '', '', 1349, '2022-07-08', CURRENT_TIMESTAMP),
(29647, 'Westabreath 500 mcg 20 f.c. tabs.', 'ويستابريث 500 مكجم 20 قرص', '160', '212', 'Roflumilast', 'Western pharmaceuticals industries', 'Tab', 'أقراص', 'علاج داء الانسداد الرئوي المزمن -- مضاد للالتهاب', 'Pde-4 inhibitor', '500 mcg', 'Oral roflumilast is indicated to reduce the risk of COPD exacerbations in patients with severe COPD associated with chronic bronchitis and a history of exacerbations.[L37564, L46541, L46546]
The topical cream of roflumilast is indicated for the treatment of plaque psoriasis, including intertriginous areas, and mild to moderate atopic dermatitis in patients six years of age and older.[L51219] 
The topical foam is approved for use in patients nine years of age and older to treat seborrheic dermatitis.[L49276]', '6224007308806', '', 1645, '2025-05-26', CURRENT_TIMESTAMP),
(4939, 'Sucair mouth wash 120 ml', 'سوكير120 مل غسول فم', '', '55', 'Mouth wash formula', 'Prime pharma', 'Mouth wash', 'غسول للفم', '', 'Oral care', '120 ml', '', '', '', 743, '2025-06-22', CURRENT_TIMESTAMP),
(11563, 'Total wellness 30 tab', 'توتال ويلنس 30 قرص', '', '32', 'Vitamins+minerals', 'Company', 'Tab', 'أقراص', 'فيتامينات وأملاح متعددة', 'Multivitamins', '', '', '', '', 2059, '2023-01-21', CURRENT_TIMESTAMP),
(14226, 'Nervadixin 20 caps', 'نيرفاديكسين 20 كبسولة', '250', '280', 'Alpha lipoic acid 600mg+vitamin b1 150mg+vitamin b6 25mg+vitamin b12 500mcg+vitamin d3 25mcg', 'Curannova pharmaceutical', 'Cap', 'كبسولة', '', 'Dietary supplement', '', '', '', '', 2343, '2025-02-27', CURRENT_TIMESTAMP),
