(12639, 'Wintriaxone 500mg pd. for i.m inj.', 'وينترياكسون 500مجم فيال عضل', '21.75', '37', 'Ceftriaxone', 'Sanofi', 'Inj', 'حقن', '', 'Antibiotic.cephalosporin.third-generation', '500mg', 'Ceftriaxone is used for the treatment of the infections (respiratory, skin, soft tissue, UTI, ENT) caused by susceptible organisms.[L15082] Organisms that are generally susceptible to ceftriaxone include S. pneumoniae, S. pyogenes (group A beta-hemolytic streptococci), coagulase-negative staphylococci, Some Enterobacter spp, H. influenzae, N. gonorrhoeae, P. mirabilis, E. coli, Klebsiella spp, M. catarrhalis, B. burgdorferi, and some oral anaerobes.[A215582]', '6223003991647', '', 938, '2024-11-08', CURRENT_TIMESTAMP),
(26931, 'Sigdutaster 0.5mg 10 capsule', 'سيجدوتاستر 0.5مجم 10 كبسولات', '', '28', 'Dutasteride', 'Sigma', 'Capsule', 'كبسولة', '', '8 alpha-reductase inhibitor', '0.5mg', 'Indicated for the treatment of symptomatic benign prostatic hyperplasia (BPH) in men with an enlarged prostate gland to improve symptoms, and reduce the risk of acute urinary retention and the need for BPH-related surgery alone or in combination with [tamsulosin].[L10568]', '', '', 1092, '2022-07-07', CURRENT_TIMESTAMP),
(20874, 'Aaa', 'ششش', '', '55', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 824, '2022-07-08', CURRENT_TIMESTAMP),
(9543, 'Heparin sodium-nile 5000 i.u./ml 100 amps.', 'هيبارين صوديوم -النيل 5000 وحدة دولية/مل 100 امبولة', '', '4,050', 'Heparin sodium', 'El nile.', 'Amp', 'أمبول', '', 'Anticoagulant.high mwt heparin', '', 'Unfractionated heparin is indicated for prophylaxis and treatment of venous thrombosis and its extension, prevention of post-operative deep venous thrombosis and pulmonary embolism and prevention of clotting in arterial and cardiac surgery. In cardiology, it is used to prevent embolisms in patients with atrial fibrillation and as an adjunct antithrombin therapy in patients with unstable angina and/or non-Q wave myocardial infarctions (i.e. non-ST elevated acute coronary artery syndrome) who are on platelet glycoprotein (IIb/IIIa) receptor inhibitors. Additionally, it is used to prevent clotting during dialysis and surgical procedures, maintain the patency of intravenous injection devices and prevent in vitro coagulation of blood transfusions and in blood samples drawn for laboratory values.', '', '', 877, '2025-08-08', CURRENT_TIMESTAMP),
(5062, 'folic acid (mepaco) 500 mcg 20 tabs', 'حمض فوليك 500مكجم 20 قرص', '20', '40', 'folic acid', 'mepaco', 'tablet', 'أقراص', '', 'Folic acid supplement', '500 mcg', 'Folic acid is indicated for the treatment of folic acid deficiency, megaloblastic anemia, and in anemias of nutritional origins, pregnancy, infancy, or childhood.', '6223002212583', '', 6005, '2025-12-17', CURRENT_TIMESTAMP),
(1996, 'Candy honey&lemon 24 lozenges', 'كاندي عسل وليمون 24 قرص', '35', '73', 'Honey-lemon', 'Pharos trade > brother pharma', 'Lozenges', 'استحلاب', '', 'Sore throat', '', '', '6224009344024', '', 1479, '2024-05-16', CURRENT_TIMESTAMP),
(28593, 'Trustnal 500 mg 10 f.c. tabs.', 'ترستنال 500مجم 10 اقراص', '31', '40', 'Nitazoxanide', 'Adwia', 'Tab', 'أقراص', '', 'Antihelminthic', '500 mg', 'For the treatment of diarrhea in adults and children caused by the protozoa <i>Giardia lamblia</i>,  and for the treatment of diarrhea in children caused by the protozoan,  <i>Cryptosporidium parvum</i> [FDA label].
Nitazoxanide has not been shown to be superior to placebo medication for the management of diarrhea caused by Cryptosporidium parvum in patients with HIV/immunodeficiency [FDA label, A31973, A31976].', '', '', 1070, '2024-06-21', CURRENT_TIMESTAMP),
(24793, 'Pharmaceris e-emotopic emollient wash gel 400 ml', 'فارماسيرز اي ايمولنت جل غسول 400مل', '', '249', '', 'Laboratorium kosmetyczne dr irena eris sp. z o.o. > multitrade', 'Gel', 'جل', '', 'Skin care', '400 ml', 'indications gentle non-foaming formula recommended for daily care of sensitive dry rough skin prone to irritations itchiness and burning. also to be used preventively on healthy skin to prevent dryness and minimize the risk of developing aggravating or tr', '', '', 650, '2022-07-12', CURRENT_TIMESTAMP),
(26415, 'S-26 gold 1 milk (pro) 800 gm', 'اس-26 جولد 1 لبن اطفال 800 جم', '599', '720', 'Milk formula stage 1', 'Pfizer > food and beverage trading', 'Unknown', 'غير محدد', '', 'Milk products.first stage (age 0-6 months)', '800 gm', '', '300087217026', '', 896, '2025-07-13', CURRENT_TIMESTAMP),
(19939, 'Glucose 5% (ultimate) i.v. inf. 500 ml', 'جلوكوز 5% التيميت محلول وريدي 500 مل', '', '11', 'Glucose (dextrose)', 'Ultimate pharma', 'Unknown', 'غير محدد', '', 'Antihypoglycemic', '5%', 'about glucose monosaccharide aldohexose nutritive sweetner. mechanism of action of glucose glucose is a simple carbohydrate and is used as energy source in man. it is readily converted to fat which provides a rich store of energy in concentrated form. glu', '', '', 928, '2022-10-07', CURRENT_TIMESTAMP),
(23525, 'New jolly hair oil 120 ml', 'نيو جولي زيت شعر 120 مل', '90', '110', 'Olive oil+chamomile oil+coconut oil+sage oil+snake oil', 'Hi-care > top.z pharma', 'Hair oil', 'زيت شعر', '', 'Hair care', '120 ml', 'In a clinical context, olive oil is used as a source of calories and fatty acids in patients requiring parenteral nutrition. A formulation called Clinolipid, comprising olive oil and [soybean oil], is indicated in all age groups, including term and preterm neonates, as a source of calories and essential fatty acids for parenteral nutrition (PN) when oral or enteral nutrition is not possible, insufficient, or contraindicated.[L51013]', '6225000029149', '', 3934, '2024-06-21', CURRENT_TIMESTAMP),
(10634, 'Sofenacin plus 5/50mg 30 f.c. tab', 'سوفيناسين بلس 5/50مجم 30 قرص', '', '408', 'Solifenacin succinate+mirabegron', 'Marcyrl co.', 'Tab', 'أقراص', 'علاج التبول اللارادي', 'Urinary incontinence.antispasmodics.muscarinic antagonists', '50mg', 'Solifenacin tablets are indicated to treat an overactive bladder with urinary incontinence, urgency, and frequency.[L7511]', '6223003573188', '', 4951, '2024-07-14', CURRENT_TIMESTAMP),
(15275, 'Bioglita plus 15/500mg 30 f.c.tab.', 'بيوجليتا بلس 15/500 مجم 30 قرص', '75', '105', 'Metformin+pioglitazone', 'Arab caps > andalous pharma', 'Tab', 'أقراص', '', 'Anti-diabetic.sensitizers.combined glitazone +biguanide', '500mg', '', '6223004691904', '', 1567, '2024-10-28', CURRENT_TIMESTAMP),
(281, 'Exliance 2mg 28 tab', 'اكسليانس 2مجم 28 قرص', '1248', '1,622', 'Baricitinib', 'Excellence Pharm', 'Tab', 'أقراص', 'التهاب المفاصل الروماتويدي', 'Janus Kinase (JAK) inhibitor (rheumatoid arthritis)', '2mg', 'In the US and Europe, baricitinib is indicated for the treatment of adult patients with moderately to severely active rheumatoid arthritis who have had an inadequate response to one or more TNF blockers. Baricitinib may be used as monotherapy or in combination with [methotrexate] [L41760,L41770] or other DMARDs.[L41760]
In Europe, baricitinib is indicated for the treatment of moderate to severe atopic dermatitis in adult patients who are candidates for systemic therapy.[L41770]
In the US, baricitinib is also indicated for the treatment of coronavirus disease 2019 (COVID-19) in hospitalized adults requiring supplemental oxygen, non-invasive or invasive mechanical ventilation, or extracorporeal membrane oxygenation.[L41760] Recently, it is also approved as the treatment for severe alopecia areata in adults.[L42070]', '6225000393844', '', 5277, '2024-07-07', CURRENT_TIMESTAMP),
(18144, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 704, '2022-09-16', CURRENT_TIMESTAMP),
(3705, 'Melano intimate feminine wash 200 ml', 'ميلانو غسول للعناية الشخصية للسيدات 200 مل', '', '80', '', 'Melano pharma', 'Unknown', 'غير محدد', '', '', '200 ml', '', '', '', 870, '2024-06-11', CURRENT_TIMESTAMP),
(15045, 'Bekcium 500mg 30 caps.', 'بيكسيوم 500 مجم 30 كبسولة', '', '27', 'Calcium dobesilate', 'Alexandria', 'Cap', 'كبسولة', '', 'Vasoprotective', '500mg', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 1282, '2022-07-24', CURRENT_TIMESTAMP),
(18537, 'Aaa', 'ششش', '', '10', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 694, '2022-07-24', CURRENT_TIMESTAMP),
(4895, 'Flagentyl 500mg 4 f.c. tabs.', 'فلاجنتيل 500مجم 4 اقراص', '', '22', 'Secnidazole', 'Sanofi', 'Tab', 'أقراص', '', 'Antiprotozoal', '500mg', 'Secnidazole is indicated for treating trichomoniasis and bacterial vaginosis in patients 12 years of age and older.[L39524] In other countries, it is also available as a combination product with other antibacterial drugs, such as [itraconazole].[L16023]', '6223003990565', '', 2118, '2022-12-05', CURRENT_TIMESTAMP),
(16329, 'Cilobiogen 100mg 10 scored tabs.', 'سيلوبيوجين 100 مجم 10 اقراص', '', '13', 'Cilostazol', 'International drug agency (idi) > biocapital pharma', 'Tab', 'أقراص', '', 'Antiplatelet.phosphodiesterase 3 inhibitor', '100mg', 'Indicated for the alleviation of symptoms of intermittent claudication (pain in the legs that occurs with walking and disappears with rest).', '', '', 806, '2022-07-13', CURRENT_TIMESTAMP),
(11133, 'Aaa', 'ششش', '', '30', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 541, '2022-12-09', CURRENT_TIMESTAMP),
(13145, 'Aaa', 'ششش', '', '52', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 705, '2022-09-22', CURRENT_TIMESTAMP),
(6944, 'Delepe 60 mg 3 f.c. tabs.', 'ديليبي 60مجم 3 قرص', '', '60', 'Dapoxetine', 'Penta pharma', 'Tab', 'أقراص', '', '', '60 mg', 'For the treatment of premature ejaculation.', '', '', 875, '2025-08-16', CURRENT_TIMESTAMP),
(4026, 'Egyfast cream 75 gm', 'ايجي فاست كريم 75 جرام', '23', '36', 'Massage cream', 'Leader cosmetics > scientific center', 'Cream', 'كريم', 'كريم مساج للجسم -- تقليل اللام العضلات -- استرخاء العضلات', 'Massage cream', '75 gm', 'herbal massage cream', '6224001079047', '', 2130, '2024-01-22', CURRENT_TIMESTAMP),
(10483, 'Aaa', 'ششش', '', '30', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 661, '2022-12-03', CURRENT_TIMESTAMP),
(21172, 'Jilifen 1.2ml (300mcg) 5 amps. ((tender&export))', 'جيليفين 1.2 مل (300 ميكروجرام) 5 امبول', '', '0', 'Filgrastim', 'Vacsera > international trading office', 'Amp', 'أمبول', '', 'Immunostimulant', '1.2ml', 'Filgrastim is indicated to decrease the incidence of infection‚ as manifested by febrile neutropenia‚ in patients with nonmyeloid malignancies receiving myelosuppressive anti-cancer drugs associated with a significant incidence of severe neutropenia with fever.[L40714]
Filgrastim is indicated for reducing the time to neutrophil recovery and the duration of fever, following induction or consolidation chemotherapy treatment of patients with acute myeloid leukemia.[L40714]
Filgrastim is indicated to reduce the duration of neutropenia and neutropenia-related clinical sequelae‚ e.g.‚ febrile neutropenia, in patients with nonmyeloid malignancies undergoing myeloablative chemotherapy followed by bone marrow transplantation.[L40714]
Filgrastim is indicated for the mobilization of autologous hematopoietic progenitor cells into the peripheral blood for collection by leukapheresis.[L40714]
Filgrastim is indicated for chronic administration to reduce the incidence and duration of sequelae of neutropenia (e.g.‚ fever‚ infections‚ oropharyngeal ulcers) in symptomatic patients with congenital neutropenia‚ cyclic neutropenia‚ or idiopathic neutropenia.[L40714]
Filgrastim is indicated to increase survival in patients acutely exposed to myelosuppressive doses of radiation.[L40714]', '', '', 812, '2022-07-13', CURRENT_TIMESTAMP),
(24878, 'Phenytin 100mg/2ml 10 amps.', 'فينيتين 100مجم/2مل 10 امبولات', '95', '110', 'Phenytoin', 'El nile.', 'Amp', 'أمبول', '', 'Anti-epileptic.hydantoin', '100mg', 'Phenytoin is indicated to treat grand mal seizures, complex partial seizures, and to prevent and treat seizures during or following neurosurgery.[L9362] Injectable phenytoin and [Fosphenytoin], which is the phosphate ester prodrug formulation of phenytoin[A188571], are indicated to treat tonic-clonic status epilepticus, and for the prevention and treatment of seizures occurring during neurosurgery.[L10740]', '', '', 744, '2025-08-30', CURRENT_TIMESTAMP),
(7079, 'Lamifen 1% cream 15 gm', 'لاميفين كريم 15 جرام', '14.5', '18', 'Terbinafine', 'Pharopharma > egpi', 'Cream', 'كريم', 'مضاد للفطريات', 'Antifungals.allylamines', '1%', 'Terbinafine hydrochloride is indicated to treat fungal skin and nail infections caused by _Trichophyton_ species, _Microsporum canis_, _Epidermophyton floccosum_,[L9068] and _Tinea_ species.[L9065] Terbinafine hydrochloride also treats yeast infections of the skin caused by _Candida_ species and _Malassezia furfur_.[L9068]', '6223003930387', '', 15562, '2024-09-28', CURRENT_TIMESTAMP),
(11385, 'Thiozin 50mg 20 f.c tab', 'ثيوزين 50مجم 20 قرص', '', '13', 'Thioridazine', 'Delta pharma', 'Tab', 'أقراص', 'علاج الامراض النفسية -- مضاد للاكتئاب -- يؤخذ تحت اشراف طبي', 'Anti psychotic', '50mg', 'For the treatment of schizophrenia and generalized anxiety disorder.', '', '', 1108, '2023-01-12', CURRENT_TIMESTAMP),
(12718, 'Aaa', 'ششش', '', '90', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 640, '2022-08-01', CURRENT_TIMESTAMP),
(9377, 'Orlistat 120mg 30 capsules', 'اورليستات 120مجم 30 كبسولة', '207', '249', 'Orlistat', 'Sigma > october pharma', 'Capsule', 'كبسولة', 'للتخسيس وبرامج انقاص الوزن والحمية الغذائية', 'Weight loss', '120mg', 'Orlistat is indicated for obesity management including weight loss and weight maintenance when used in combination with calorie reduction in overweight and obese adults; this indication applies to both the prescription formulation of 120 mg[L11130] and the over-the-counter formulation of 60 mg.[L31963] Orlistat in the 120 mg prescription formulation is also indicated to reduce the risk of weight regain following weight loss.[L11130]', '6221088021969', '', 8721, '2025-08-02', CURRENT_TIMESTAMP),
(11589, 'Histamedizen 30mg/5ml oral susp. 100 ml', 'هيستاميديزين 30مجم5مل معلق', '20', '33', 'Fexofenadine', 'Medizen pharmaceutical industries', 'Susp', 'معلق', '', 'Anti-histamine.anti-allergy', '30mg', 'In the United States, fexofenadine is indicated for the symptomatic treatment of allergic rhinitis in patients ≥2 years old and chronic idiopathic urticaria in patients ≥6 months old.[L4269] In Canada, fexofenadine carries the same indications but is approved only for patients ≥12 years old.[L10779] Fexofenadine is also available in combination with [pseudoephedrine] for the symptomatic treatment of season allergic rhinitis in patients ≥12 years old.[L10800]', '', '', 879, '2024-07-23', CURRENT_TIMESTAMP),
(1926, 'Jomamor 10 hard gelatin capules', 'جومامور كبسولات 10 كبسولة', '', '90', 'N-acetylcysteine+selenium+vitamin e+vitamin b2', 'Pharma zid', 'Cap', 'كبسولة', '', '', '', '', '', '', 2773, '2024-12-25', CURRENT_TIMESTAMP),
(6240, 'Flowadjust 50 mg 30 prolonged rel. tabs.', 'فلوادجاست 50مجم 30 قرص', '381', '498', 'Mirabegron', 'Amoun', 'Tab', 'أقراص', '', 'Overactive bladder', '50 mg', 'Mirabegron is indicated for the treatment of overactive bladder (OAB) - with symptoms of urge urinary incontinence, urgency, and urinary frequency - either alone or in combination with [solifenacin].[L32853] It is also indicated for the treatment of neurogenic detrusor overactivity (NDO) in pediatric patients 3 years of age and older and weighing 35kg or more.[L32853]', '6221025045034', '', 986, '2025-11-24', CURRENT_TIMESTAMP),
(14219, 'Anthelios xl spf 50+ nutritive oil 200 ml', 'انثيليوس اكس ال زيت مغذي 200 مل', '', '299', '', 'La roche-posay > united company for trading & distribution', 'Oil', 'زيت', '', 'Sun block', '200 ml', '*properties sensitive skin to skin prone to sun intolerance commonly known as sun allergies. extreme sunshine intensity. prevention of sun-induced pigment spots (pregnancy photosensitization...). very high broad photostable uva/uvb protection. optimal spf', '', '', 868, '2022-08-01', CURRENT_TIMESTAMP),
(30768, 'Kolagra hyaluronic acid serum 30 ml', 'كولاجرا هيالورنيك اسيد سيرم 30 مل', '199', '319', 'Hyaluronic acid+vitamin b5', 'Egyptian company for cosmetics > bio stream', 'Serum', 'سيروم', '', 'Skin care.firming', '30 ml', 'The intra-articular preparations of hyaluronic acid are indicated for knee pain associated with osteoarthritis.[L32228] Hyaluronic acid is used in cosmetic applications to prevent and reduce the appearance of wrinkles on the face, and as a dermal filler to correct facial imperfections or other imperfections on other parts of the body.[L32208,L32223] It is frequently an ingredient in topical applications for wound healing and symptomatic treatment of skin irritation from various causes.[L32198] Hyaluronic acid may also be indicated in ophthalmological preparations or oral capsules to treat discomfort caused by dry eyes or conjunctivitis and for its protective qualities during and before eye surgery.[A230128,L32213] Finally, hyaluronic acid can be used off-label to coat the bladder for relief of interstitial cystitis symptoms.[A230533]', '6225000411777', '', 660, '2024-04-26', CURRENT_TIMESTAMP),
(23813, 'Novophane k shampoo 125 ml', 'نوفوفان ك شامبو 125مل', '', '149', '', 'Acm dermatological laboratories > biotech egypt', 'Amp', 'أمبول', '', 'Hair care', '125 ml', 'properties novophane.k shampoo efficiently eliminates chronic or/and flaky scalp conditions. it contains soothing and moisturizing agents. directions for use apply novophane.k shampoo onto wet hair. lather by gently massaging the scalp. leave for a few mi', '', '', 902, '2022-07-29', CURRENT_TIMESTAMP),
(19337, 'Fortatec 10 gm 20 sachets', 'فورتاتيك 10جرام 20 كيس', '50', '140', 'Ferrous fumarate+lactoferrin+folic acid+vitamin(b1+b6+b12+c)+calcium', 'Novotec pharma', 'Sachet', 'أكياس', '', 'Iron supplement', '10 gm', 'Ferrous sulfate is used for the prevention and treatment of iron deficiency anemia in adults and children.[A190804,L2240,L11800]', '', '', 1451, '2025-12-13', CURRENT_TIMESTAMP),
(16617, 'Colchicine 500 mcg 10 tab', 'كولشيسين 500 مكجم 10 قرص', '15', '19', 'Colchicine', 'El nasr', 'Tab', 'أقراص', 'مسكن وعلاج لمرض النقرس', 'Antigout.analgesic', '500 mcg', 'Colchicine is indicated for the prophylaxis and treatment of gout flares. It is also indicated in Familial Mediterranean fever (FMF) in children and adults of four years of age and older.[L8138] It is also indicated to reduce the risk of myocardial infarction (MI), stroke, coronary revascularization, and cardiovascular death in adult patients with established atherosclerotic disease or with multiple risk factors for cardiovascular disease.[L47591] 
Some off-label uses of colchicine include the treatment of the manifestations of Behcet''s syndrome, pericarditis, and postpericardiotomy syndrome.[A183932,A183935]', '3400936275096', '', 4390, '2025-06-21', CURRENT_TIMESTAMP),
(3783, 'Dolcyl 4mg 30 tab.', 'دولسيل 4مجم 30 قرص', '51', '69', 'Glimepiride', 'Mup', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.sulfonylurea', '4mg', 'Glimepiride is indicated for the management of type 2 diabetes in adults as an adjunct to diet and exercise to improve glycemic control as monotherapy. 
It may also be indicated for use in combination with metformin or insulin to lower blood glucose in patients with type 2 diabetes whose high blood sugar levels cannot be controlled by diet and exercise in conjunction with an oral hypoglycemic (a drug used to lower blood sugar levels) agent alone.[L10322]', '6221508511223', '', 3327, '2024-12-10', CURRENT_TIMESTAMP),
