(21216, 'Kadcyla 100 mg pd. vial for inf.', 'كادسيلا 100 مجم فيال', '27220', '34,025', 'Ado-trastuzumab emtansine', 'F.hoffman la roche', 'Vial', 'فيال', '', 'Antineoplastic', '100 mg', 'indication used in her2-positive metastatic breast cancer patients who have already used taxane and/or trastuzumab for metastatic disease or had their cancer recur within 6 months of adjuvant treatment. the fda label has two precautions. first that trastu', '', '', 1890, '2023-09-19', CURRENT_TIMESTAMP),
(22823, 'Mirage 1 gm i.v. vial', 'ميراج 1جم فيال للحقن الوريدي', '251', '350', 'Meropenem', 'Misr > adwia', 'Vial', 'فيال', '', 'Antibiotic.carbapenem', '1 gm', 'For use as single agent therapy for the treatment of the following infections when caused by susceptible isolates of the designated microorganisms: <b>complicated skin and skin structure infections</b> due to <i>Staphylococcus aureus</i> (b-lactamase and non-b-lactamase producing, methicillin-susceptible isolates only), <i>Streptococcus pyogenes</i>, <i>Streptococcus agalactiae</i>, viridans group streptococci, <i>Enterococcus faecalis</i> (excluding vancomycin-resistant isolates), <i>Pseudomonas aeruginosa</i>, <i>Escherichia coli</i>, <i>Proteus mirabilis</i>, <i>Bacteroides fragilis</i> and <i>Peptostreptococcus</i> species; <b>complicated appendicitis and peritonitis</b> caused by viridans group streptococci, <i>Escherichia coli</i>, <i>Klebsiella pneumoniae</i>, <i>Pseudomonas aeruginosa</i>, <i>Bacteroides fragilis</i>, <i>B. thetaiotaomicron</i>, and <i>Peptostreptococcus</i> species. Also for use in the treatment of bacterial meningitis caused by <i>Streptococcus pneumoniae</i>, <i>Haemophilus influenzae</i> (b-lactamase and non-b-lactamase-producing isolates), and <i>Neisseria meningitidis</i>.', '6223002976362', '', 7743, '2024-08-01', CURRENT_TIMESTAMP),
(24576, 'Pariet 10mg 14 tab.', 'باريت 10مجم 14 قرص', '', '75', 'Rabeprazole sodium', 'Janssen cilag > soficopharm', 'Tab', 'أقراص', '', 'Peptic ulcer.proton pump inhibitor', '10mg', 'For the treatment of acid-reflux disorders (GERD), peptic ulcer disease, H. pylori eradication, and prevention of gastroinetestinal bleeds with NSAID use.', '', '', 886, '2022-08-02', CURRENT_TIMESTAMP),
(17455, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 782, '2022-09-23', CURRENT_TIMESTAMP),
(29730, 'Xeljanz 5 mg 60 tab', 'زيلجانز 5 مجم 60 قرص', '17200', '23,074', 'Tofacitinib', 'Pfizer', 'Tab', 'أقراص', 'مضاد للروماتيزم -- علاج حالات التهاب المفاصل الروماتيزمية', 'Anti rheumatic', '5 mg', 'Tofacitinib is indicated for the treatment of adult patients with moderately-to-severely active rheumatoid arthritis (RA), active psoriatic arthritis, active ankylosing spondylitis, or moderately-to-severely active ulcerative colitis who have had an inadequate response or intolerance to one or more TNF blockers.[L30395] It is also indicated as an oral solution in patients ≥2 years of age for the treatment of polyarticular course juvenile idiopathic arthritis who have had an inadequate response or intolerance to one or more TNF blockers.[L30395]
Tofacitinib is not recommended to be used in combination with other biologic disease-modifying anti-rheumatic drugs (DMARDs) or potent immunosuppressive agents such as azathioprine or cyclosporine.[L30395]', '', '', 8779, '2024-11-06', CURRENT_TIMESTAMP),
(24121, 'One alpha 2mcg/ml oral drops 10ml', 'ون الفا 2مكجم/مل نقط بالفم 10 مل', '154', '221', 'Alfacalcidol', 'Leo pharmaceutical products > egyptian pharmaceutical trading company', 'Drops', 'نقط', '', 'Vitamin d', '2mcg', 'Alfacalcidol is indicated in adult patients with chronic renal failure for the management of hypocalcemia, secondary hyperparathyroidism, or osteodystrophy.[L33284]
Alfacalcidol is indicated in the management of nutritional and malabsorptive rickets and osteomalacia, vitamin D-dependent rickets and osteomalacia, and hypophosphataemic vitamin D resistant rickets and osteomalacia.[L33364,L33369]', '', '', 1127, '2024-08-25', CURRENT_TIMESTAMP),
(12705, 'Xithrone 500mg 5 f.c.tab.', 'زيثرون 500مجم 5 اقراص', '58.5', '86', 'Azithromycin', 'Amoun', 'Tab', 'أقراص', 'مضاد حيوي', 'Antibiotic.macrolide', '500mg', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '6221025014122', '', 20876, '2024-07-24', CURRENT_TIMESTAMP),
(3950, 'Health pro synbiotic 7 sachets', 'هيلث برو سينبيوتيك 7 اكياس', '', '98', 'Lactoferrin+zinc', 'Nutrixia for human care pharma', 'Sachet', 'أكياس', '', '', '', '', '', '', 836, '2025-05-31', CURRENT_TIMESTAMP),
(20676, 'Aaa', 'ششش', '', '20', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 758, '2022-07-14', CURRENT_TIMESTAMP),
(17390, 'Desitin extra nappy cream 75 ml', 'ديسيتين اكسترا كريم للحفاضات 75 مل', '', '80', '', 'Johnson & johnson consumer > united company for trading & distribution', 'Cream', 'كريم', '', 'Diaper rash', '75 ml', 'nappy cream for sensitive skin of babies.', '', '', 652, '2022-08-02', CURRENT_TIMESTAMP),
(6629, 'Isopto atropine 1% eye drops 5 ml', 'ايزوبتو اتروبين 1% نقط للعين 5 مل', '', '13', 'Atropine sulphate', 'Novartis > novartis scientific office', 'Drops', 'نقط', 'تقليل الالام بالعين -- تقليل الاحمرار والتورم والالتهاب بالعين', 'Antimuscarinic.antispasmodic', '1%', 'The intravenous, intramuscular, subcutaneous, intraosseous and endotracheal use of atropine is indicated for the temporary blockade of severe or life-threatening muscarinic effects.[L42815,L42835] The intramuscular use of atropine in the form of a pen injector is indicated for the treatment of poisoning by susceptible organophosphorus nerve agents having cholinesterase activity as well as organophosphorus or carbamate insecticides in adult and pediatric patients.[L42825] The ophthalmic use of atropine is indicated for mydriasis, cycloplegia, and penalization of the healthy eye in the treatment of amblyopia.[L42830] 
In combination with difenoxin or diphenoxylate (tablets for oral use), atropine is indicated as adjunctive therapy in the management of acute nonspecific diarrhea.[L42840,L42865]', '5413895003073', '', 1138, '2022-12-06', CURRENT_TIMESTAMP),
(23500, 'Neuth purifying cleansing gel system 150 ml', 'نيوث جل 150مل', '', '175', '', 'Neuth > eva pharma', 'Gel', 'جل', '', 'Skin care', '150 ml', 'de-clogs pores dissolves excess oil and makeup traces without stripping the face from essential moisture. directions 1.wash your hands before cleansing your face to eliminate all traces of bacteria and dirt. 2.splash water all over your face squeeze a sma', '', '', 746, '2022-07-17', CURRENT_TIMESTAMP),
(2596, 'Cinaretam 400/25mg 20 cap.', 'سيناريتام 20كبسولة', '', '6', 'Cinnarizine+piracetam', 'Misr', 'Cap', 'كبسولة', 'مضاد للدوار', 'Antivertigo', '25mg', 'about cinnarizine piperazines derivative antihistamine antivertigo. mechanism of action of cinnarizine cinnarizine is a specific competitive h1 receptor antagonist. it suppresses the vestibular end organ receptors and thus inhibits the activation of centr', '6221035012040', '', 964, '2022-09-09', CURRENT_TIMESTAMP),
(18013, 'Ebaclean vag. wash 250 ml', 'ايباكلين غسول مهبلي 250 ملي', '', '30', 'Chlorhexidine+aloe vera+thyme+liquorice+citric acid', 'El-helou perfumes & cosmetics > beauty & beyond international', 'Unknown', 'غير محدد', '', 'Vaginal wash', '250 ml', 'vaginal wash for mild to moderate vaginal disorders vaginal infection and daily hygine.', '', '', 794, '2022-07-26', CURRENT_TIMESTAMP),
(27875, 'Aaa', 'ششش', '95', '124', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 717, '2023-09-16', CURRENT_TIMESTAMP),
(24388, 'Oxatrilepazine 600 mg 10 f.c.tab', 'اوكساتريليبازين 600مجم 10 اقراص', '', '27', 'Oxcarbazepine', 'Medizen pharmaceutical industries > mira international', 'Tab', 'أقراص', '', 'Anti-epileptic.carboxamides', '600 mg', 'In the United States, oxcarbazepine is indicated for use as monotherapy or adjunctive therapy in the treatment of partial-onset seizures in adults and as monotherapy in the treatment of partial-onset seizures in pediatric patients aged 4 years and above, and as adjunctive therapy in pediatric patients aged 2 years and above with partial-onset seizures.[L8627] 
In Canada, oxcarbazepine is indicated for use as monotherapy or adjunctive therapy in the treatment of partial-onset seizures in patients 6 years of age and older.[L8630]', '', '', 1041, '2022-07-22', CURRENT_TIMESTAMP),
(19300, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 658, '2022-12-05', CURRENT_TIMESTAMP),
(29176, 'Verony 100 mg 14 sachets', 'فيروني 100مجم 14 كيس', '', '88', 'Lactoferrin', 'D. b. k for pharm. industries > pharma life', 'Sachet', 'أكياس', '', 'Iron supplement', '100 mg', 'lactoferrin is a bioactive 80-kda iron binding glycoprotein. dosage: 1 sachet to be dissolved in quarter glass of water and taken twice daily before meals.', '', '', 995, '2022-07-29', CURRENT_TIMESTAMP),
(23897, 'Nuxe reve de miel foot cream 75 ml', 'نوكس ريف كريم 75مل', '', '199', '', 'Nuxe laboratory > biotech egypt', 'Cream', 'كريم', '', 'Skin care', '75 ml', 'this luxurious foot cream with honey and cereal oils helps to replenishe lipids soothe repair and provide 24-hour hydration for dry and rough feet. our star ingredient to regain comfort quickly to your feet: shea butter use massage your ultra-comfortable', '', '', 572, '2022-07-31', CURRENT_TIMESTAMP),
(3956, 'Easy meal 20 capsules', 'ايزي ميل 20 كبسولة', '', '16', 'Chamomile+ginger+anise+bromelain+fennel+peppermint', 'Mepaco', 'Capsule', 'كبسولة', '', 'Git disturbances', '', '', '6223002211753', '', 1303, '2022-12-04', CURRENT_TIMESTAMP),
(10101, 'Futacare 30 tabs.', 'فوتاكير 30 قرص', '', '95', 'Vitamin c+vitamin d3+zinc', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', '', 'Multivitamin', '', 'For the treatment of vitamin A deficiency.', '', '', 855, '2024-05-31', CURRENT_TIMESTAMP),
(11974, 'Urisept 100 mg 20 sugar c.tabs.', 'يوريسبت 100مجم 20 قرص', '', '5', 'Phenazopyridine', 'Kahira', 'Tab', 'أقراص', 'مسكن يستخدم فى تخفيف أعراض الألم، والحرقان، والإلحاح، والتكرار، و أسباب عدم الراحة الأخرى الناشئة عن تهيج الغشاء المخاطي المسالك البولية السفلى بسبب العدوى ،الجراحة ، عمليات التنظير ، الإصابات .', 'Urinary.analgesic.antiseptic', '100 mg', 'Phenazopyridine hydrochloride is indicated to relieve uncomfortable symptoms that occur as a consequence of mucosal irritation of the lower urinary tract in adults.  The irritation may be a result of trauma, surgery, endoscopic procedures, infection, or the insertion of instruments or urinary catheters.[L7826] Phenazopyridine may be used in combination with antimicrobial therapy but is not used as an antimicrobial agent. It contributes to the relief of discomfort and pain before antimicrobial therapy begins to take effect.  It is important to note that the duration of treatment with this drug should last a maximum of 2 days.[L7826] Phenazopyridine is available in many countries as an over the counter drug.[A182147]', '6221068000489', '', 3126, '2023-02-19', CURRENT_TIMESTAMP),
(33397, 'Peptamen ace milk 430 gm', 'بيبتامين ايه سي اي لبن 430 جم', '992', '1,111', 'Extra care milk formula', 'Nestle', 'Unknown', 'غير محدد', '', 'Extra care milk', '430 gm', 'specialized nutritional formulas designed to help patients who have problems digesting normal foods and for those who cannot tolerate a standard tube feeding formula. unique ingredients such as enzymatically hydrolyzed whey protein and medium chain trigly', '7613032994198', '', 1039, '2025-11-21', CURRENT_TIMESTAMP),
(25901, 'Repo cream 50 gm', 'ريبو كريم 50جم', '80', '90', 'Bee propolis+royal jelly+honey+hazelnut oil+sesame oil+arnica ext+comfrey ext+bees wax+olive ext', 'Hi-care > rovamed pharma', 'Cream', 'كريم', '', 'Healing topical', '50 gm', 'indications 1. acute wounds: 2. burns including all degrees 3. surgical wounds including circumcision obstetrical wounds cosmetic surgical wounds. 4. hemorrhoids and anal fissures 5. episiotomy 6. chronic wounds: (including diabetic foot ulcers bed sores', '', '', 934, '2024-02-18', CURRENT_TIMESTAMP),
(15686, 'Cal-d b12 - 5 amp.', 'كال-د ب12 5 امبول', '', '8', 'Calcium gluconate+calcium levulinate+vitamin b12+vitamin d2', 'Misr', 'Amp', 'أمبول', '', 'Calcium supplement', '', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 1086, '2022-07-07', CURRENT_TIMESTAMP),
(15004, 'Beesline deo whitening sport pulse spray 150 ml', 'بيزلين ديو سبراي تبييض 150 مل', '225', '225', '', 'Beesline > pharma cruise medical', 'Spray', 'بخاخ', '', 'Skin care', '150 ml', 'active ingredients alum rock vitamin e aloe vera ginger soybean vitamin c lumiskin teflose lactic acid sodium lactate vitamin b3 & propolis. a skin-friendly spray deodorant with 72hr antiperspirant action to prevent moisture & body odour. all the while de', '', '', 787, '2024-10-03', CURRENT_TIMESTAMP),
(32084, 'Aaa', 'ششش', '', '65', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 647, '2023-03-09', CURRENT_TIMESTAMP),
(31910, 'Skyrizi 75 mg/0.83 ml 2 prefilled syringe', 'سكايريزي 75 مجم /0.83 مل 2 حقنة معبأة', '50000', '65,714', 'Risankizumab', 'Abbvie ltd. > abbvie scientific office', 'Syringe', 'حقنة', '', '.', '75 mg', 'Risankizumab is indicated to treat:
- moderate-to-severe **plaque psoriasis** in adults who are candidates for systemic therapy or phototherapy.[L39885,L44191,L44231]
- active **psoriatic arthritis** in adults.[L39885,L44191,L44231] In Canada and Europe, it may be used alone or in combination with a conventional non-biologic disease-modifying antirheumatic drug (cDMARD) (e.g., methotrexate).[L44191,L44231]
- moderately to severely active **Crohn''s disease** in adults.[L39885,L44191,L44231] In Canada, it is used in patients who have had an inadequate response, intolerance, or demonstrated dependence on corticosteroids; or an inadequate response, intolerance, or loss of response to immunomodulators or biologic therapies.[L44191]
- moderately to severely active **ulcerative colitis** in adults.[L50938]', '', '', 3936, '2025-11-02', CURRENT_TIMESTAMP),
(11807, 'Aurei 60gm massage gel', 'اوري مساج جل 60 جم', '', '55', 'Glucosamine+cetylmyristoleate+menthol+camphor oil+eucalyptus oil+peppermint oil', 'Ccc pharma', 'Gel', 'جل', '', 'Massage gel', '60gm', '', '', '', 925, '2022-08-18', CURRENT_TIMESTAMP),
