(21381, 'Zinkacin 10 tabs', 'زنكاسين 10 اقراص', '', '28', 'Zinc', 'Vortex pharma', 'Tab', 'أقراص', '', 'Zinc', '', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 799, '2024-07-12', CURRENT_TIMESTAMP),
(24246, 'Orencia 250 mg powder for iv infusion (n/a)', 'اورينسيا 250مجم بودر للحقن الوريدي', '', '3,499', 'Abatacept', 'Bristol-myers squibb > united company for trading & distribution', 'Powder', 'بودرة', '', 'Selective t cell costimulation modulator', '250 mg', 'Abatacept is indicated in adult patients for the treatment of moderately-to-severely active rheumatoid arthritis and in patients ≥2 years of age for the treatment of active psoriatic arthritis.[L48811] In patients two years of age and older, abatacept is also indicated for the treatment of moderately-to-severely active juvenile idiopathic arthritis.[L20504]
Abatacept is also indicated for the prophylaxis of acute graft-versus-host disease, in combination with [methotrexate] and a calcineurin inhibitor such as [tacrolimus], in patients two years of age and older who are undergoing hematopoietic stem cell transplantation from a matched or 1 allele-mismatched unrelated donor.[L20504]', '', '', 921, '2022-08-02', CURRENT_TIMESTAMP),
(3999, 'Neuroenergize 300mg tabs', 'نيوروانرجايز 300مجم اقراص', '', '125', 'Alpha lipoic acid', 'Uptown pharma egypt', 'Tab', 'أقراص', '', 'Antioxidant vitamin', '300mg', '', '', '', 921, '2025-06-02', CURRENT_TIMESTAMP),
(28876, 'Ursomix forte 10 f.c. tab.', 'اورسومكس فورت 10 اقراص', '', '25', 'Chenodeoxycholic acid+ursodeoxycholic acid', 'Global napi pharmaceuticals > germa pharm', 'Tab', 'أقراص', '', 'Liver support supplements', '', 'Chenodiol is indicated for patients with radiolucent stones in well-opacifying gallbladders, in whom selective surgery would be undertaken except for the presence of increased surgical risk due to systemic disease or age. Chenodiol will not dissolve calcified (radiopaque) or radiolucent bile pigment stones.', '', '', 841, '2022-08-05', CURRENT_TIMESTAMP),
(22225, 'Magnetrel 2.5/10mg 30 caps.', 'ماجنيتريل 10/2.5مجم 30كبسول', '', '54', 'Amlodipine+benazepril', 'Rameda', 'Cap', 'كبسولة', '', 'Antihypertensive.combined ace with calcium channel blocker', '10mg', 'mechanism of action of amlodipine amlodipine is a second generation dihydropyridine ca channel blocker. it exerts it`s antihypertensive antianginal actions through blocking the influx of ca ions through voltage gated l-type ca channels to the peripheral v', '6223003970895', '', 823, '2022-07-17', CURRENT_TIMESTAMP),
(22407, 'Maxitrol eye oint. 3.5 gm', 'ماكسيترول مرهم عين 3.5جم', '', '13', 'Dexamethasone+neomycin sulphate+polymyxin b sulphate', 'Alcon > novartis scientific office', 'Oint', 'مرهم', '', '', '3.5 gm', 'about dexamethasone a potent synthetic glucocorticoid antiasthmatic anti-inflammatory and immunosuppressant. about neomycin an aminoglycoside antibiotic ammonium detoxicant. mechanism of action of neomycin this aminoglycoside cause protein synthesis inhib', '5413895006319', '', 1240, '2022-07-16', CURRENT_TIMESTAMP),
(5819, 'Gynotrazonagen 600mg 3 vaginal ovules+applicator', 'جينوترا زوناجين 600مجم 3 اقماع لبوس مهبلي', '21.5', '33', 'Isoconazole nitrate', 'Marcyrl co.', 'Unknown', 'غير محدد', 'مضاد للفطريات', 'Antifungals.imidazoles', '600mg', 'about isoconazole azole derivative broad spectrum antifungal mechanism of action of isoconazole isoconazole is an imidazole antifungal with a broad spectrum of activity. it is also active against some gram positive bacteria indications for isoconazole 1.v', '6223003571139', '', 7480, '2024-10-04', CURRENT_TIMESTAMP),
(20625, 'Hygi-tadine 0.5 mg / ml syrup 120 ml', 'هيجى تادين 0.5 مجم / مل شراب 120 مل', '18', '38', 'Desloratadine', 'Dbk pharma > hygint pharmaceuticals-egypt', 'Syrup', 'شراب', '', 'Antihistamine.antiallergy', '0.5 mg', 'For the relief of symptoms of seasonal allergic rhinitis, perennial (non-seasonal) allergic rhinitis. Desloratidine is also used for the sympomatic treatment of pruritus and urticaria (hives) associated with chronic idiopathic urticaria.', '6225000047792', '', 1745, '2024-11-27', CURRENT_TIMESTAMP),
(636, 'Amoxicillin 500mg 12 caps.', 'اموكسيسيللين 500مجم 12 كبسولة', '', '10', 'Amoxicillin', 'October pharma', 'Cap', 'كبسولة', 'مضاد حيوى يستخدم في علاج التهاب الأذن الوسطى الحاد والالتهاب الرئوي والتهاب الجيوب الأنفية البكتيرى الحاد والتهاب البلعوم البكتيرى وعدوى المسالك البولية والقضاء على بكتيريا هيليكوباكتر بيلوري (جرثومة المعدة) وعدوى الأسنان', 'Penicillins.monocomponent', '500mg', 'Amoxicillin alone is indicated to treat susceptible bacterial infections of the ear, nose, throat, genitourinary tract, skin, skin structure, and lower respiratory tract.[L11656,L11659] Amoxicillin is given with calvulanic acid to treat acute bacterial sinusitis, community acquired pneumonia, lower respiratory tract infections, acute bacterial otitis media, skin and skin structure infections, and urinary tract infections.[L11650,L7880,L11653] Amoxicillin is given with omeprazole in the treatment of _Helicobacter pylori_ (_H. pylori_) infection.[L9743,L11647]
Amoxicillin is used in combination with [vonoprazan] and [clarithromycin] as co-packaged triple therapy or in combination with [vonoprazan] as co-packaged dual therapy to treat _H. pylori_ infection in adults.[L41695]', '6221088021464', '', 35065, '2023-06-24', CURRENT_TIMESTAMP),
(23166, 'Fast freeze magnesium massage spray 200 ml', 'فاست فريز مغنسيوم مساج سبراي 200 مل', '', '250', 'Camphor+menthol+magnesium', 'Rotabiogen', 'Spray', 'بخاخ', '', 'Massage', '200 ml', '', '6224011378222', '', 799, '2023-01-20', CURRENT_TIMESTAMP),
(16672, 'Combi soft acne lotion 35 ml', 'كومبي سوفت لوشن لحب الشباب 35 مل', '', '36', '', 'Hi-care > pharma comb', 'Lotion', 'لوشن', '', 'Anti-acne', '35 ml', '', '', '', 1304, '2022-07-17', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(32008, 'Dropaviton oraldrops 15 ml', 'دروبافيتون 400 وحدة دولية/مل قطرات فموية 15 مل', '', '41', 'Cholecalciferol(vitamin d3)', '> nutripharma', 'Drops', 'نقط', 'مكمل غذائى لدعم النمو الطبيعي للعظام والوقاية من الكساح ولين العظام', 'Vitamin d', '15 ml', '', '', '', 1606, '2023-03-09', CURRENT_TIMESTAMP),
(20604, 'Hydrocortisone roussel 10mg 25 tabs.(illegal import)', 'هيدروكورتيزون روسيل 10 مجم 25 قرص', '', '0', 'Hydrocortisone acetate', 'Sanofi >', 'Tab', 'أقراص', '', 'Glucocorticoid', '10mg', 'For the relief of the inflammatory and pruritic manifestations of corticosteroid-responsive dermatoses. Also used to treat endocrine (hormonal) disorders (adrenal insufficiency, Addisons disease). It is also used to treat many immune and allergic disorders, such as arthritis, lupus, severe psoriasis, severe asthma, ulcerative colitis, and Crohn''s disease.', '', '', 3104, '2023-03-15', CURRENT_TIMESTAMP),
(18421, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 640, '2022-07-30', CURRENT_TIMESTAMP),
(11451, 'Tiocon 1% cream 20 gm', 'تيوكون كريم 20 جرام', '16', '29', 'Tioconazole', 'Global napi pharmaceuticals', 'Cream', 'كريم', '', 'Antifungals.imidazoles', '1%', 'For the local treatment of vulvovaginal candidiasis (moniliasis).', '6223002148479', '', 2664, '2025-09-17', CURRENT_TIMESTAMP),
(15081, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 712, '2023-04-19', CURRENT_TIMESTAMP),
(30035, 'Phlegomez 120 ml syrup', 'فليجوميز 120 مل شراب', '', '85', 'Omega 3 from fish oil', 'Nature care', 'Syrup', 'شراب', '', 'Multivitamin', '120 ml', '', '', '', 1047, '2022-07-26', CURRENT_TIMESTAMP),
(13945, 'Calcieba 30 caps', 'كالسيبا 30 كبسولة', '', '140', 'Calcium bisglycinate+magnesium bisglycinate+vitamin d3', 'Obaid pharma', 'Cap', 'كبسولة', '', 'Multivitamins', '', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 1704, '2024-06-11', CURRENT_TIMESTAMP),
(14055, 'Aaa', 'ششش', '', '21', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 776, '2022-09-06', CURRENT_TIMESTAMP),
(16029, 'Livorno cream 60 gm', 'ليفورنو كريم 60 جم', '', '55', 'Zinc oxide+chlorhexidine+tea tree oil+panthenol', 'Neiphco', 'Cream', 'كريم', '', '', '60 gm', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 1155, '2024-09-18', CURRENT_TIMESTAMP),
(23823, 'Easyrest 50 gm gel', 'ايزيريست جل 50 جم', '', '55', 'Turmeric longa leaf extract menthol calcium sulfate eucalyptus oil amygdalus plum oil magnesium sulfate thyme plant extract phenoxyethanol cinnamon extract trigonella seed extract - grape linoleic acid (omega-6)) linolenic acid (omega 3) mentha piperita o', 'Karmed pharm', 'Gel', 'جل', '', 'Massage gel', '50 gm', '', '', '', 623, '2023-01-13', CURRENT_TIMESTAMP),
(32023, 'Magnesium citrate 120 veg. caps. (now)', 'ماغنيسيوم سيترات 120 كبسولة', '1450', '1,600', 'Magnesium', 'Now foods > soficopharm', 'Cap', 'كبسولة', '', '.', '', 'Used for immediate control of life-threatening convulsions in the treatment of severe toxemias (pre-eclampsia and eclampsia) of pregnancy and in the treatment of acute nephritis in children. Also indicated for replacement therapy in magnesium deficiency, especially in acute hypomagnesemia accompanied by signs of tetany similar to those of hypocalcemia. Also used in uterine tetany as a myometriat relaxant.', '733739012944', '', 906, '2025-09-22', CURRENT_TIMESTAMP),
(28142, 'Aaa', 'ششش', '', '13', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 708, '2023-01-12', CURRENT_TIMESTAMP),
(1592, 'Bisadyl 5mg for children 10 supp.', 'بيساديل 5مجم 10 اقماع لبوس اطفال', '12', '30', 'Bisacodyl', 'Amriya', 'Supp', 'لبوس', '', 'Laxative', '5mg', 'Bisacodyl is indicated to relieve occasional constipation and irregularity.[L13362]', '6221075100042', '', 1616, '2024-11-06', CURRENT_TIMESTAMP),
(28368, 'Aaa', 'ششش', '', '18', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 706, '2022-10-08', CURRENT_TIMESTAMP),
(24476, 'Panadol cold & flu day 24 f.c. tabs', 'بانادول كولد اند فلو 24 قرص', '50', '76', 'Caffeine+paracetamol(acetaminophen)+phenylephrine hydrochloride', 'Alexandria > glaxo smithkline', 'Tab', 'أقراص', '1- تخفيف أعراض نزلات البرد الشديدة.', 'Cold drugs', '', '', '6222010610800', '', 8060, '2024-07-29', CURRENT_TIMESTAMP),
(22294, 'Mariez fruit syrup 120 ml', 'ماريز فروت شراب 120مل', '', '9', 'Orange juice+grapefruit juice+malt', 'Al esraa pharmaceutical optima > merge pharmaceutical co.', 'Syrup', 'شراب', '', '', '120 ml', '', '6221077584239', '', 996, '2022-12-06', CURRENT_TIMESTAMP),
(20187, 'Hair gain 2% lotion 50 ml', 'هير جين 2% لوشن 50 مل', '', '30', 'Minoxidil', 'Pharco', 'Lotion', 'لوشن', '', 'Antihypertensives.hair regrowth.vasodilator agents', '2%', 'For the treatment of severe hypertension and in the topical treatment (regrowth) of androgenic alopecia in males and females and stabilisation of hair loss in patients with androgenic alopecia.', '6223000012260', '', 1211, '2022-07-17', CURRENT_TIMESTAMP),
(13154, 'Vigoton plus 30 caps', 'فيجوتون بلس 30 كبسولة', '190', '240', 'Lutein+zeaxanthin+omega 3+beta-carotene+selenium+copper+vitamin c+vitamin e+zinc+riboflavin', 'Octabiotic pharma', 'Cap', 'كبسولة', '', 'Antioxidant', '', '', '', '', 1726, '2025-09-23', CURRENT_TIMESTAMP),
(14098, 'Anallerge 4 mg 60 tab.', 'انالليرج 4 مجم 60 قرص', '16.5', '30', 'Chlorpheniramine', 'Kahira', 'Tab', 'أقراص', 'مضاد للحساسية -- تقليل الالتهابات -- تقليل الحكة والاحمرار', 'Antihistamine.antiallergy', '4 mg', 'For the treatment of rhinitis, urticaria, allergy, common cold, asthma and hay fever.', '6221068001158', '', 11813, '2024-07-24', CURRENT_TIMESTAMP),
(7061, 'Lactulose hek 65% syrup 120ml', 'لاكتيلوز شراب 120 مل', '55', '83', 'Lactulose', 'Eipico > fresenius kabi', 'Syrup', 'شراب', '', 'Laxative', '65%', 'Lactulose is indicated for use as a laxative in the treatment of chronic constipation in adults and geriatric patients.[FDA Label,L6199,L6202]
Additionally, lactulose is also employed as an adjunct to protein restriction and supportive therapy for the prevention and treatment of portal-systemic encephalopathy (PSE), including both the hepatic pre-coma and coma variations.[FDA Label,L6199,L6202] In particular, lactulose solution has been effective at managing PSE resulting from surgical portacaval shunts or from chronic hepatic diseases like cirrhosis.[L6199]
Moreover, there have also been studies demonstrating the capacity for lactulose to minimize the formation of gallstones and even some investigations regarding the experimental use of the agent in developing novel anticancer agents owing to its ability to bind galactin carbohydrates involved in various tumor progressions [L6202].', '6221032222664', '', 11478, '2025-08-21', CURRENT_TIMESTAMP),
(13110, 'Folicyan 30 sublingual tabs (sita pharma )', 'فوليسيان 30 قرص تحت اللسان', '165', '180', 'Vitamin b12+folic acid+vitamin b6', 'Sita pharma', 'Tab', 'أقراص', '', 'Multivitamins', '', 'For the treatment of vitamin A deficiency.', '', '', 806, '2025-12-13', CURRENT_TIMESTAMP),
(32053, 'Char 500 mg 30 capsules', 'تشار 500مجم 30 كبسولة', '', '45', 'Activated charcoal', 'Hp pharma', 'Capsule', 'كبسولة', 'يستخدم فى التخلص من السموم و الانتفاخ وغازات البطن و امتصاص الروائح والغازات النتنة و عند ارتفاع الكوليسترول في الدم', 'Dietary supplement', '500 mg', 'Used as a antidote to treat poisonings following excessive oral ingestion of certain medications or poisons.', '', '', 1702, '2023-05-04', CURRENT_TIMESTAMP),
(21621, 'Lasaromep 160mg 14 f.c. tab.', 'لازاروميب 160 مجم 14 قرص', '', '26', 'Valsartan', 'Mepaco', 'Tab', 'أقراص', '', 'Antihypertensive.angiotensin blocker', '160mg', 'Valsartan is indicated for the treatment of hypertension to reduce the risk of fatal and nonfatal cardiovascular events, primarily strokes and myocardial infarctions. It is also indicated for the treatment of heart failure (NYHA class II-IV) and for left ventricular dysfunction or failure after myocardial infarction when the use of an angiotensin-converting enzyme inhibitor (ACEI) is not appropriate.[F4703, L11305]
It is also used in combination with [sacubitril].[L36445]', '', '', 808, '2022-07-24', CURRENT_TIMESTAMP),
(2767, 'Clindam 150 mg 16 caps.', 'كليندام 150مجم 16 كبسولة', '', '29', 'Clindamycin', 'Sigma > october pharma', 'Cap', 'كبسولة', '', 'Antibiotic.lincomycins', '150 mg', 'In oral and parenteral formulations, clindamycin is indicated for the treatment of serious infections caused by susceptible anaerobic bacteria, as well as susceptible staphylococci, streptococci, and pneumococci.[L11599,L11602] Used topically, it is indicated for the treatment of acne vulgaris[L11593,L11611,L11605] and is available in combination with [benzoyl peroxide][L11584] or [tretinoin][L11590] for this purpose, or as a triple combination therapy with benzoyl peroxide and [adapalene].[L48666] Clindamycin is also indicated as a vaginal cream[L11596], suppository[L11608], or gel[L39416] for the treatment of bacterial vaginosis in non-pregnant females.
Clindamycin is used for antimicrobial prophylaxis against _Viridans_ group streptococcal infections in susceptible patients undergoing oral, dental, or upper respiratory surgery, and may be used for prophylaxis against bacterial endocarditis in penicillin-allergic patients at high risk of these infections.[L11629]', '6221051020012', '', 1480, '2022-12-04', CURRENT_TIMESTAMP),
(23680, 'Noflu syrup 100ml', 'نوفلو شراب 100 مل', '9.5', '17', 'Chlorpheniramine+paracetamol(acetaminophen)+phenylpropanolamine', 'Kahira', 'Syrup', 'شراب', '', 'Cold drugs', '100ml', 'description a histamine h1 antagonist used in allergic reactions hay fever rhinitis urticaria and asthma. indication for the treatment of rhinitis urticaria allergy common cold asthma and hay fever. pharmacodynamics in allergic reactions an allergen inter', '6221068402931', '', 1067, '2024-12-07', CURRENT_TIMESTAMP),
(17548, 'Diacurimap 10 mg 30 f.c. tabs.', 'دياكيوريماب 10مجم 30 قرص', '150', '204', 'Empagliflozin', 'Multi-apex', 'Tab', 'أقراص', 'لمرضى السكر', 'Anti-diabetic.secretagogues.sglt2 inhibitors', '10 mg', 'Empagliflozin is indicated as an adjunct to diet and exercise to improve glycemic control in patients aged 10 years and older with type 2 diabetes. It is used either alone or in combination with [metformin] or [linagliptin].[L13679, L13673, L13688, L49449] It is also indicated to reduce the risk of cardiovascular death in adult patients with both type 2 diabetes mellitus and established cardiovascular disease, either alone or as a combination product with metformin.[L13688, L40778]
An extended-release combination product containing empagliflozin, metformin, and linagliptin was approved by the FDA in January 2020 for the improvement of glycemic control in adults with type 2 diabetes mellitus when used adjunctively with diet and exercise.[L11479]
Empagliflozin is also approved to reduce the risk of cardiovascular mortality and hospitalization due to heart failure in adult patients with heart failure, either alone or in combination with metformin.[L13688, L45578] It is also indicated in adults to reduce the risk of sustained decline in eGFR, end-stage kidney disease, cardiovascular death, and hospitalization in adults with chronic kidney disease at risk of progression.[L40778, L48255]
Empagliflozin is not approved for use in patients with type 1 diabetes.', '6223003206352', '', 13222, '2024-03-19', CURRENT_TIMESTAMP),
(30015, 'Azemibe 10/20mg 10 f.c. tabs.', 'ازيميب 10/20 مجم 10 اقراص', '', '33', 'Atorvastatin+ezetimibe', 'Innovision pharm', 'Tab', 'أقراص', '', 'Antihyperlipidemic.cholesterol absorption inhibitors.combined with statin', '20mg', '', '', '', 880, '2022-10-05', CURRENT_TIMESTAMP),
(5534, 'Glaryl 2mg 30 tabs.', 'جلاريل 2مجم 30 قرص', '24', '36', 'Glimepiride', 'Global napi pharmaceuticals', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.sulfonylurea', '2mg', 'Glimepiride is indicated for the management of type 2 diabetes in adults as an adjunct to diet and exercise to improve glycemic control as monotherapy. 
It may also be indicated for use in combination with metformin or insulin to lower blood glucose in patients with type 2 diabetes whose high blood sugar levels cannot be controlled by diet and exercise in conjunction with an oral hypoglycemic (a drug used to lower blood sugar levels) agent alone.[L10322]', '6223002142705', '', 1384, '2024-11-22', CURRENT_TIMESTAMP),
