(15507, 'Panthowaves 50 gm cream', 'بانثوويفز كريم 50 جم', '', '120', 'Niacinamide+jojoba oil+panthenol', 'Waves for pharmacies management and public supplies-waves', 'Cream', 'كريم', '', 'Skin emollient', '50 gm', '', '', '', 861, '2024-08-16', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(13408, 'Coxritor 90 mg 30 f.c.tabs.', 'كوكسريتور 90مجم 30 قرص', '207', '297', 'Etoricoxib', 'Global napi pharmaceuticals > global pharmaceutical industries', 'Tab', 'أقراص', 'يستخدم لعلاج لألم الحاد.علاج الالتهاب المفصلي الروماتيدي.', 'Nsaid.selective cox-2 inhibitors', '90 mg', 'For the treatment of rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, chronic low back pain, acute pain and gout.', '6223004900808', '', 14785, '2024-07-14', CURRENT_TIMESTAMP),
(33874, 'Vitalox b12 energy 10 oral ampoules x 7 ml', 'فيتالوكس بي12 اينيرجي 10 امبول × 7 مل', '590', '790', 'Vitamin b12', 'Loxymore pharma', 'Ampoule', 'أمبول', '', 'Vitamin b', '7 ml', 'For the treatment of vitamin A deficiency.', '', '', 898, '2025-11-16', CURRENT_TIMESTAMP),
(31937, 'Karinoba 250/25 mg 20 oral disinteg. tabs.', 'كارينوبا 250/25مجم 20 قرص', '43', '110', 'Carbidopa+levodopa', 'Debeiky > elixir pharma', 'Tab', 'أقراص', 'يستخدم في علاج مرض الباركنسون', 'Parkinson s disease.dopamine agonist', '25 mg', 'about carbidopa a noncompetitive dopa decarboxylase inhibitor antidyskinetics anti-parkinson`s agent. mechanism of action of carbidopa carbidopa inhibits the peripheral decarboxylation of levodopa and thus slowing its conversion to dopamine in extra cereb', '6224010704053', '', 2747, '2024-12-15', CURRENT_TIMESTAMP),
(7758, 'Tebofortin forte 80mg 30 f.c. tab.', 'تيبوفورتين فورت 80مجم 30 قرص', '102', '165', 'Ginkgo biloba', 'Marcyrl co.', 'Tab', 'أقراص', 'منشط للدورة الدموية يعمل على علاج القلق.تحسين الذاكرة.تخفيف أعراض مرض الزهايمر.علاج التصلب المتعدد.علاج الصداع والدوخة والدوار.تحسين مشاكل العيون.', 'Anti-ischemic', '80mg', '_Ginkgo biloba_ does not currently have any approved therapeutic indications, and there is insufficient evidence to support its unapproved use.[A232379] It is available in over-the-counter herbal products mostly for oral use, to improve memory and cognitive problems.', '6223003570811', '', 1811, '2024-06-27', CURRENT_TIMESTAMP),
(8513, 'Myoflex 10 tab', 'ميوفلكس 10 اقراص', '17', '25', 'Chlorzoxazone+paracetamol(acetaminophen)', 'El nile.', 'Tab', 'أقراص', 'باسط للعضلات.', 'Muscle relaxant', '', '', '6221077015610', '', 7408, '2024-12-14', CURRENT_TIMESTAMP),
(9985, 'Rootage skin cream 50 gm', 'روتاج كريم للجلد 50 جم', '40', '65', '', 'Egpi > el-sisi international co.', 'Cream', 'كريم', '', 'Skin acre', '50 gm', '', '', '', 999, '2024-05-03', CURRENT_TIMESTAMP),
(14731, 'Averobios 642.9mg/5 ml 75ml susp.', 'افيروبيوس 642.9مجم/5مل 75 مل معلق', '82.5', '118', 'Amoxicillin+clavulanic acid', 'Sigmatec > averroes pharma-egypt', 'Susp', 'معلق', '', 'Penicillins.penicillin with b-lactamase inhibitor', '642.9mg', '', '6224008179313', '', 1358, '2024-11-21', CURRENT_TIMESTAMP),
(9650, 'Parnetil 10 mg 10 tab', 'بارنيتيل 10 مجم 10 قرص', '', '4', 'Tranylcypromine', 'Kahira', 'Tab', 'أقراص', 'مضاد للاكتئاب -- علاج نوبات الهلع -- علاج الوسواس القهري', 'Psychiatric.antidepressants', '10 mg', 'For the treatment of major depressive episode without melancholia.', '', '', 1047, '2022-05-28', CURRENT_TIMESTAMP),
(25769, 'Aaa', 'ششش', '', '90', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 638, '2022-07-21', CURRENT_TIMESTAMP),
(17612, 'Aaa', 'ششش', '', '32', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 663, '2022-07-18', CURRENT_TIMESTAMP),
(27189, 'Sodium chloride 0.9% (fipco) i.v. inf. 500 ml (rubber cap)', 'صوديوم كلوريد 0.9% فيبكو محلول ملح وريدي بغطاء مطاطي 500 مل', '', '15', 'Sodium chloride', 'El-fath (fipco)', 'Cap', 'كبسولة', '', 'Normal saline', '0.9%', 'This intravenous solution is indicated for use in adults and pediatric patients as a source of electrolytes and water for hydration. Also, designed for use as a diluent and delivery system for intermittent intravenous administration of compatible drug additives.', '', '', 1050, '2022-07-11', CURRENT_TIMESTAMP),
(24355, 'Otoxin 3mg/ml ear drops', 'اوتوكسين 3مجم/مل نقط للاذن', '', '11', 'Ofloxacin', 'Sedico', 'Drops', 'نقط', '', 'Antibiotic.quinolone', '3mg', 'For the treatment of infections (respiratory tract, kidney, skin, soft tissue, UTI), urethral and cervical gonorrhoea.', '', '', 953, '2022-07-08', CURRENT_TIMESTAMP),
(20180, 'Aaa', 'ششش', '', '10', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 664, '2022-12-02', CURRENT_TIMESTAMP),
(21154, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 720, '2022-07-18', CURRENT_TIMESTAMP),
(28607, 'Turnalev 2.5mg/5ml syrup 120 ml', 'تورناليف 2.5مجم/5مل شراب 120مل', '', '11', 'Levocetirizine', 'Lamar pharma > debeiky', 'Syrup', 'شراب', '', 'Antihistamine.non-sedative.third-generation', '2.5mg', 'Levocetirizine is indicated to treat symptoms of perennial allergic rhinitis and uncomplicated skin manifestations of chronic idiopathic urticaria.[L7694] It is also used over the counter for a variety of mild allergy symptoms.[A181748]', '', '', 743, '2022-07-17', CURRENT_TIMESTAMP),
(27231, 'Softlees hair protein 800 ml', 'سوفتليس بروتين للشعر 800مل', '', '2,400', 'Vitamin e+ vitamin b5+glycolic acid+argan oil+sesame oil+almond oil+keratin +protein+collagen+jojoba oil', 'Cosmopack > care mid east pharma', 'Unknown', 'غير محدد', '', 'Hair care', '800 ml', 'For the treatment of vitamin A deficiency.', '', '', 676, '2022-07-26', CURRENT_TIMESTAMP),
(17323, 'Derma-clinic moisturizing cream 50 gm', 'ديرما كلينك كريم مرطب 50 جم', '', '125', '', 'Borg', 'Cream', 'كريم', '', 'Moisturizing topicals', '50 gm', '*the ever luxurious moisturizing cream enriched with natural ingredients such as mango seed butter and camillia seed oil which is instantly absorbed to provide a superb emollient effect for enduring softness.', '6223002572038', '', 782, '2022-12-04', CURRENT_TIMESTAMP),
(21805, 'Lidocaine 2% 10 amp', 'ليدوكايين 2% 10 امبولات', '60', '90', 'Lidocaine', 'Alexandria', 'Amp', 'أمبول', '', 'Analgesic.local anesthetic', '2%', 'Lidocaine is an anesthetic of the amide group indicated for production of local or regional anesthesia by infiltration techniques such as percutaneous injection and intravenous regional anesthesia by peripheral nerve block techniques such as brachial plexus and intercostal and by central neural techniques such as lumbar and caudal epidural blocks [F4349, L5930].', '', '', 2152, '2024-10-18', CURRENT_TIMESTAMP),
(3664, 'Diflucan 2mg/ml (50ml) i.v. infusion', 'ديفلوكان 2 مجم/ مل (50 مل)', '97.5', '140', 'Fluconazole', 'Pfizer', 'Unknown', 'غير محدد', '', 'Antifungals.triazoles', '2mg', 'Fluconazole can be administered in the treatment of the following fungal infections[L11043]:
 1) Vaginal yeast infections caused by Candida
 2) Systemic Candida infections
 3) Both esophageal and oropharyngeal candidiasis 
 4) Cryptococcal meningitis
 5) UTI (urinary tract infection) by Candida
 6) Peritonitis (inflammation of the peritoneum) caused by Candida
**A note on fungal infection prophylaxis**
Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '6221180000831', '', 1305, '2024-11-10', CURRENT_TIMESTAMP),
(2826, 'Clozapine 25mg 30 tab.', 'كلوزابين 25مجم 30 قرص', '24', '36', 'Clozapine', 'Copad pharma', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '25mg', 'Clozapine is indicated for the treatment of severely ill patients with schizophrenia who fail to respond adequately to standard antipsychotic treatment. Because of the risks of severe neutropenia and of seizure associated with its use, Clozapine should be used only in patients who have failed to respond adequately to standard antipsychotic treatment.[L905]
Clozapine is also indicated for reducing the risk of recurrent suicidal behavior in patients with schizophrenia or schizoaffective disorder who are judged to be at chronic risk for re-experiencing suicidal behavior, based on history and recent clinical state. Suicidal behavior refers to actions by a patient that put him/herself at risk for death.[L905]', '6224000394042', '', 1492, '2024-11-04', CURRENT_TIMESTAMP),
(20882, 'Intaxel 6mg/ml 30mg vial', 'انتاكسيل 6 مجم / مل 30 مجم فيال', '', '315', 'Paclitaxel', 'Fresenius kabi > egyptian group for import and export', 'Vial', 'فيال', '', 'Antineoplastic', '6mg', 'Used in the treatment of Kaposi''s sarcoma and cancer of the lung, ovarian, and breast. Abraxane® is specfically indicated for the treatment of metastatic breast cancer and locally advanced or metastatic non-small cell lung cancer.', '', '', 738, '2022-08-01', CURRENT_TIMESTAMP),
(23308, 'Natural flax oil 1000mg 60 soft gels capsules (illegal import)', 'ناتشورال فلاكس اويل 1000مجم 60 كبسولة جيلاتينية', '', '0', 'Flaxseed oil', 'Puritans pride', 'Capsule', 'كبسولة', 'علاج ارتفاع الكوليسترول -- الحماية من ارتفاع ضغط الدم -- الحماية من امراض القلب -- تقليل الوزن -- مقوي للاعصاب وخاصة لمرضي السكر', 'Natural oil', '1000mg', '', '', '', 690, '2022-10-22', CURRENT_TIMESTAMP),
(24757, 'Peritoneal dialysis sol. with glucose 2.27 % w/w', 'بيريتونيل دياليسيس محلول مع جلوكوز 2.27%', '', '8', 'Sodium chloride+glucose', 'Baxter > hikma pharma', 'Sol', 'محلول', '', 'Normal saline', '2.27 %', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 741, '2022-07-24', CURRENT_TIMESTAMP),
(4389, 'Opta rose gel', 'اوبتا روز جل', '', '350', 'Cyclopentasiloxane+vinyl dimethicone crosspolymer+sodium hyaluronate+tocopherol+allantoin+polyaminopropyl biguanide', 'Optavit pharma', 'Gel', 'جل', '', 'Anti scar', '', '', '', '', 847, '2025-06-17', CURRENT_TIMESTAMP),
(8187, 'Omega marve syrup 60 ml', 'اوميجا مارفي شراب 60 مل', '', '75', 'Omega3 epa 400mg+dha 300mg+vitamine+vitamina+vitamind', 'Gemo pharm', 'Syrup', 'شراب', '', 'Multivitamins', '60 ml', '', '', '', 848, '2025-12-05', CURRENT_TIMESTAMP),
(26215, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 762, '2022-07-31', CURRENT_TIMESTAMP),
(14333, 'Aptamil pre nutriprem milk 400 gm', 'ابتاميل بري نيوتريبريم لبن اطفال 400 جم', '215', '400', 'Milk formula stage 3', 'Nutricia cuijk b.v. > united partners company', 'Unknown', 'غير محدد', '', 'Milk products.third stage (age 1-3 years)', '400 gm', 'for pre-mature infants from birth onwards. to be used within one month from opening. it is a whey dominant pre-term infant formula designed to provide complete nutrient-enriched nutrition for pre-term and low birth weight infants following hospital discha', '', '', 843, '2024-08-29', CURRENT_TIMESTAMP),
(13393, 'Act-hib vaccine 10mcg/0.5ml vial', 'اكت-هيب فاكاسين 10 مجم / 0.5 مل فيال', '', '50', 'Haemophilus influenza+tetanus toxoid', 'Sanofi pasteur-france > etimex-egypt', 'Vial', 'فيال', '', 'Vaccine', '10mcg', 'Indicated for active immunization in pediatric patients 15 months through 4 years of age as a booster dose for the prevention of invasive disease caused by Haemophilus influenzae type b.', '', '', 896, '2022-07-22', CURRENT_TIMESTAMP),
(23173, 'Asmazon spray 60 ml', 'اسمازون سبراي 60 مل', '55', '65', 'Climbazole', 'Pharmakon', 'Spray', 'بخاخ', '', '', '60 ml', '', '6224008056553', '', 2462, '2025-06-01', CURRENT_TIMESTAMP),
(23443, 'Netlook 40mg 20 soft gelatin capsule', 'نت لوك 40مجم 20 كبسول لحب الشباب', '302', '394', 'Isotretinoin', 'Medizen pharmaceutical industries > andalous pharma', 'Capsule', 'كبسولة', '', 'Anti-acne', '40mg', 'Isotretinoin is indicated to treat severe recalcitrant nodular acne and patients ≥12 years enrolled in the iPLEDGE program.[Label,L6579]', '6223004691942', '', 6087, '2024-10-28', CURRENT_TIMESTAMP),
(31847, 'Tiapride-clavita pharma 137.9 mg/ml syrup 30 ml', 'تيابرايد-كلافيتا فارما 137.9 مجم/ مل شراب 30 مل', '80', '107', 'Tiapride', 'Atco pharma > clavita pharma', 'Syrup', 'شراب', 'علاج الاضطرابات النفسية والذهان وخلل الحركة المتاخر او فرط الحركة', 'Dopamine blocker', '137.9 mg', 'Tiapride is indicated for the treatment of a variety of neurological and psychiatric disorders including dyskinesia, alcohol withdrawal syndrome, negative symptoms of psychosis, and agitation and aggression in the elderly.', '', '', 3255, '2024-08-29', CURRENT_TIMESTAMP),
(21549, 'Lady shine foaming cleanser 150 gm', 'ليدي شاين منظف ​​رغوي 150 جم', '', '109', '', 'Debeiky', 'Cleanser', 'منظف', '', 'Skin care', '150 gm', 'facial cleanser for acne prone skin.', '', '', 729, '2022-07-31', CURRENT_TIMESTAMP),
(32798, 'Endodrava 2 mg 28 tabs.', 'ايندودرافا 2 مجم 28 قرص', '198', '261', 'Dienogest', 'Technopharma', 'Tab', 'أقراص', 'مانع للحمل', 'Contraceptive', '2 mg', 'Indicated for use as the treatment of endometriosis alone and as a contraceptive in combination with ethinylestradiol.', '6224008302483', '', 2580, '2024-09-26', CURRENT_TIMESTAMP),
(24398, 'Oxidil 5% topical soln. 100 ml', 'اوكسيديل 5% 100مل', '', '43', 'Minoxidil', 'Debeiky > lamar pharma', 'Sol', 'محلول', '', 'Hair regrowth.vasodilator agents', '5%', 'For the treatment of severe hypertension and in the topical treatment (regrowth) of androgenic alopecia in males and females and stabilisation of hair loss in patients with androgenic alopecia.', '', '', 926, '2022-07-13', CURRENT_TIMESTAMP),
(2106, 'Carminex 6 eff. sachets', 'كارمينكس فوار 6 اكياس', '12', '25', 'Caraway oil+cinnamon oil+fennel oil', 'Mepaco', 'Sachet', 'أكياس', '', 'Git disturbances', '', '', '6223002213030', '', 2317, '2025-03-03', CURRENT_TIMESTAMP),
(27029, 'Sina seas 20 caps.', 'سينا سيز 20 كبسولة', '', '23', 'Cod liver oil', 'Safe pharma > sina pharm', 'Cap', 'كبسولة', '', 'Omega 3', '', 'Cod liver oil is predominantly manufactured, marketed, and used by the population at large as a general nutraceutical dietary supplement [A27154, A33159, L2872].
Historically, cod liver oil was often given to children because the vitamin d content in the oil had been shown to prevent or treat vitamin D deficiency and condition of rickets associated with it [A33159]. Over time, this common use in children growing up may have conferred upon cod liver oil its identity as a healthy and useful all-purpose dietary supplement.
