(24469, 'Palm fresh massage cream 60 gm', 'بالم فريش مساج كريم 60 جم', '', '32', 'Camphor oil+peppermint oil+emu oil+eucalyptus extract+methyl salicylate+turpentine oil', 'Egyptian company for cosmetics > keepaco pharm', 'Cream', 'كريم', '', 'Massage', '60 gm', 'for fast relief from pain in muscles & joints', '', '', 828, '2022-08-01', CURRENT_TIMESTAMP),
(22886, 'Model cream 150 gm', 'موديل كريم 150 جم', '', '55', 'Caffeine+aloe vera+l-carnitine+apple cidar vinegar+peanut oil+dimethicone+paraffin oil', 'El-helou perfumes & cosmetics > medifact group', 'Cream', 'كريم', 'لتحسين مظهر وملمس الجلد', 'Firming topical', '150 gm', 'skin firming cream. apply twice daily then massage.', '', '', 1892, '2022-05-14', CURRENT_TIMESTAMP),
(30711, 'Isis ginger & cinnamon 12 filter bags', 'ايزيس زنجبيل وقرفه 12 فلتر باكو', '17.5', '20', 'Ginger+cinnamon', 'Atos pharma', 'Unknown', 'غير محدد', '', 'Drinks', '', '', '', '', 844, '2025-07-15', CURRENT_TIMESTAMP),
(18527, 'Allmed d3 adult oral spray 3000 iu /2spray 21ml', 'اولميد د3 سبراي بالفم للكبار 3000وحدة دولية/2سبراي 21 مل', '', '300', 'Vitamin d', 'Allmed ltd', 'Spray', 'بخاخ', '', 'Vitamin d', '3000 iu', 'Vitamin D is indicated for use in the treatment of hypoparathyroidism, refractory rickets (also known as vitamin D resistant rickets), and familial hypophosphatemia [FDA Label].', '', '', 688, '2023-05-02', CURRENT_TIMESTAMP),
(18761, 'Ezetrol 10mg 7 tab.', 'ايزيترول 10مجم 7 قرص', '', '90', 'Ezetimibe', 'Merck sharp & dohme > global napi pharmaceuticals', 'Tab', 'أقراص', '', 'Hypolipidemic agent', '10mg', 'Ezetimibe is indicated to reduce elevated total-C, LDL-C, Apo B, and non-HDL-C in patients with primary hyperlipidemia, alone or in combination with an HMG-CoA reductase inhibitor (statin).[L11347,L11401,L11404] 
It is also indicated to reduce elevated total-C, LDL-C, Apo B, and non-HDL-C in patients with mixed hyperlipidemia in combination with [fenofibrate], and to reduce elevated total-C and LDL-C in patients with homozygous familial hypercholesterolemia (HoFH) in combination with atorvastatin or simvastatin.[L11347] In combination with [bempedoic acid], ezetimibe is indicated as an adjunct to diet, with or without other lipid-lowering therapies, to reduce LDL-C in adults with primary hyperlipidemia, including heterozygous familial hypercholesterolemia (HeFH).[L12150] 
Ezetimibe may also be used to reduce elevated sitosterol and campesterol in patients with homozygous sitosterolemia (phytosterolemia).[L11347]', '6223002140572', '', 1556, '2022-12-05', CURRENT_TIMESTAMP),
(26267, 'Ronatril 2mg 30 tab.', 'روناتريل 2مجم 30 اقراص', '', '10', 'Clonazepam', 'Hi-pharm', 'Tab', 'أقراص', '', 'Anti-epileptic.benzodiazepines', '2mg', 'Clonazepam is indicated as monotherapy or as an adjunct in the treatment of Lennox-Gastaut syndrome (petit mal variant), akinetic, and myoclonic seizures.[FDA Label][F3787] Furthermore, clonazepam may also be of some value in patients with absence spells (petit mal) who have failed to respond to succinimides.[FDA Label][F3787] Additionally, clonazepam is also indicated for the treatment of panic disorder, with or without agoraphobia, as defined in the DSM-V.[FDA Label]
Alternatively, some regional prescribing information note that clonazepam is indicated for all clinical forms of epileptic disease and seizures in adults, especially absence seizures (petit mal) including atypical absence; primary or secondarily generalised tonic-clonic (grand mal), tonic or clonic seizures; partial (focal) seizures with elementary or complex symptomatology; various forms of myoclonic seizures, myoclonus and associated abnormal movements.[L5572,F3796] Such regional label data also has clonazepam indicated for most types of epilepsy in infants and children, especially absences (petit mal), myoclonic seizures and tonic-clonic fits, whether due to primary generalized epilepsy or to secondary generalization of partial epilepsy.[F3796]', '', '', 900, '2022-07-13', CURRENT_TIMESTAMP),
(21052, 'Item-n shampoo 60ml', 'ايتم ان شامبو 60 مل', '45', '60', 'Na laurylether sulfat+cocamidopropylbetain+na cl+guar hydroxypropyltriamonium cl+citric a+na benzoat', 'Mash premiere', 'Amp', 'أمبول', '', 'Scabicide', '60ml', 'phenothrin is a chemical that kills insects (an insecticide). it is a man-made (synthetic) chemical similar to the natural insecticides called pyrethrins. phenothrin is one of a group of insecticides known as pyrethroids. it is also used to control scabie', '6222001403312', '', 1454, '2025-09-23', CURRENT_TIMESTAMP),
(16049, 'Cefotrix 500 mg i.v. vial (u.s.p.23)', 'سيفوتريكس 500 مجم فيال وريد', '', '28', 'Ceftriaxone', 'T3a pharma', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '500 mg', 'Ceftriaxone is used for the treatment of the infections (respiratory, skin, soft tissue, UTI, ENT) caused by susceptible organisms.[L15082] Organisms that are generally susceptible to ceftriaxone include S. pneumoniae, S. pyogenes (group A beta-hemolytic streptococci), coagulase-negative staphylococci, Some Enterobacter spp, H. influenzae, N. gonorrhoeae, P. mirabilis, E. coli, Klebsiella spp, M. catarrhalis, B. burgdorferi, and some oral anaerobes.[A215582]', '', '', 740, '2022-07-23', CURRENT_TIMESTAMP),
(17791, 'Gandaquinone 20 capsules', 'جانداكينون 20 كبسولة', '', '218', 'Co enzyme q10 100mg', 'Nutramed', 'Capsule', 'كبسولة', '', 'Antioxidant', '', '', '', '', 733, '2022-07-17', CURRENT_TIMESTAMP),
(2323, 'Cemi-flox 400mg 10 f.c. tabs.', 'سيمي-فلوكس 400 مجم 10 اقراص', '', '29', 'Ofloxacin', 'Arab caps > master med pharma', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '400mg', 'For the treatment of infections (respiratory tract, kidney, skin, soft tissue, UTI), urethral and cervical gonorrhoea.', '6224000696375', '', 1622, '2022-12-03', CURRENT_TIMESTAMP),
(3466, 'Dermatin cort topical cream 15 gm', 'ديرماتين كورت كريم موضعي 15 جم', '5.5', '15', 'Clotrimazole+hydrocortisone', 'Pharco', 'Cream', 'كريم', 'علاج العدوي الفطرية التي تصيب الجلد وتكون مصحوبة بحكة', 'Antifungal with glucocorticoid', '15 gm', 'about clotrimazole a broad-spectrum antifungal antibiotic imidazole derivative oral nonabsorbed antifungal agent. mechanism of action of clotrimazole clotrimazole is fungicidal or fungistatic depending on the drug concentrations. it inhibits the conversio', '6221151003038', '', 7290, '2024-11-26', CURRENT_TIMESTAMP),
(16030, 'Cefoprox 100mg 5 f.c.tab.', 'سيفوبروكس 100 مجم 5 اقراص', '', '22', 'Cefpodoxime', 'T3a pharma', 'Tab', 'أقراص', '', 'Antibiotic.cephalosporin.third-generation', '100mg', 'Indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the designated microorganisms.', '', '', 1071, '2022-07-30', CURRENT_TIMESTAMP),
(22421, 'Mdicorval 200mcg/6mcg 120 metered actuations', 'مديكورفال 200مكجم/6مكجم 120 بخة معايرة', '150', '198', 'Budesonide+formoterol', 'Mdi pharma', 'Unknown', 'غير محدد', 'موسع شعب', 'Bronchodilator.glucocorticoid steroid and long-acting b2 agonist', '200mcg', 'uses: this product contains 2 medications budesonide and formoterol. it is an inhaler used as a long-term (maintenance) treatment to prevent or decrease wheezing and trouble breathing caused by asthma or ongoing lung disease (such as copd). it works in th', '6224002249180', '', 5768, '2024-09-02', CURRENT_TIMESTAMP),
(15314, 'Biotin shampoo 12 oz 354 ml', 'بيوتين شامبو 12 اوز 354 مل', '', '0', '', 'Puritans pride', 'Amp', 'أمبول', '', 'Hair care', '354 ml', 'directions: wet hair thoroughly. apply a small amount to hands and work hair into a lather. rinse well. repeat if desired. for best results follow with puritans pride biotin conditioner. other ingredients: water sodium laureth sulfate cocamide dea hydroxy', '', '', 672, '2022-11-30', CURRENT_TIMESTAMP),
(4804, 'Sinupret syrup 100 ml', 'سينوبرت 100 مل شراب', '', '130', 'Elder flowers+gentian root+primose flowers+shop vervain wort+sorrel herb', 'Technomed group', 'Syrup', 'شراب', '', 'Decongesstant', '100 ml', '', '', '', 900, '2025-06-21', CURRENT_TIMESTAMP),
(18392, 'Aaa', 'ششش', '', '21', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 610, '2022-09-13', CURRENT_TIMESTAMP),
(7291, 'Genewoman 50+ jar 30 tabs', 'جينيوومن 50+ برطمان 30 قرص', '', '300', '', '', 'Tab', 'أقراص', '', '', '', '', '', '', 791, '2025-08-31', CURRENT_TIMESTAMP),
(20349, 'Heparin sodium-cid 5000 i.u./ml 100 s.c. amp.', 'هيبارين صوديوم سيد 5000وحدة دولية/مل 100 امبول تحت الجلد', '', '1,350', 'Heparin sodium', 'Cid', 'Amp', 'أمبول', '', 'Anticoagulant.high mwt heparin', '', 'Unfractionated heparin is indicated for prophylaxis and treatment of venous thrombosis and its extension, prevention of post-operative deep venous thrombosis and pulmonary embolism and prevention of clotting in arterial and cardiac surgery. In cardiology, it is used to prevent embolisms in patients with atrial fibrillation and as an adjunct antithrombin therapy in patients with unstable angina and/or non-Q wave myocardial infarctions (i.e. non-ST elevated acute coronary artery syndrome) who are on platelet glycoprotein (IIb/IIIa) receptor inhibitors. Additionally, it is used to prevent clotting during dialysis and surgical procedures, maintain the patency of intravenous injection devices and prevent in vitro coagulation of blood transfusions and in blood samples drawn for laboratory values.', '', '', 1801, '2022-07-01', CURRENT_TIMESTAMP),
(17778, 'Dolo-d oral susp. 60 ml', 'دولو-دي معلق للبرد 60 مل', '15', '25', 'Ibuprofen+pseudoephedrine', 'Borg', 'Susp', 'معلق', '', 'Cold drugs', '60 ml', 'ibuprofen ( analgesic anti-inflammatory and anti-pyretic activity) ibuprofen is a propionic acid derivative with analgesic anti-inflammatory and anti-pyretic activity. the drug therapeutic effects are thought to result from its inhibitory effect on the en', '6223002570294', '', 1360, '2024-06-29', CURRENT_TIMESTAMP),
(28927, 'Aaa', 'ششش', '', '3', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 687, '2022-07-15', CURRENT_TIMESTAMP),
(24047, 'Omega net 10 s.g. caps', 'اوميجا نت 10 كبسولات', '', '46', 'Shark liver oil', 'Medizen pharmaceutical industries > national arabian company', 'Cap', 'كبسولة', '', 'Omega 3', '', '', '', '', 1699, '2022-06-18', CURRENT_TIMESTAMP),
(16976, 'Cuti-care anti-dandruff shampoo 150 ml', 'كيوتي-كير شامبو مضاد للقشرة 150 مل', '99', '125', 'Zinc pyrithione+climbazole+selenium sulphide+tea tree oil+biotin+argan oil+hydrolyzed soy protein', 'Egyptian company for cosmetics > three one pharma', 'Amp', 'أمبول', 'شامبو مضاد للقشرة', 'Hair care. anti-dandruff', '150 ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 4247, '2025-01-20', CURRENT_TIMESTAMP),
(14618, 'Aug-derma vaseline cream 100 gm', 'ايه يو جي- ديرما فازلين كريم 100 جرام', '50', '70', 'Cocoa butter+isopropyl myristate+shea butter+petrolatum', 'Aug pharma', 'Cream', 'كريم', 'مرطب للجلد', 'Skin care', '100 gm', 'Indicated for topical use in over-the-counter skin products for the treatment of skin dryness and reduction of striae gravidarum (stretch marks).', '', '', 1773, '2023-12-30', CURRENT_TIMESTAMP),
(10076, 'Aaa', 'ششش', '', '18', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 796, '2022-08-12', CURRENT_TIMESTAMP),
(3729, 'Wellfemme cal 30 tabs', 'ويلفيم كال 30 قرص', '', '150', 'Calcium+magnesium+zinc+boron+manganese+copper+selenium+vitamin d', 'Wellness pharma', 'Tab', 'أقراص', '', 'Supplement', '', '', '', '', 926, '2024-08-03', CURRENT_TIMESTAMP),
(23295, 'Natristazen sr 1.5mg 30 f.c. tabs.', 'ناتريستازين اس ار 1.5مجم 30 اقراص', '11', '17', 'Indapamide', 'Medizen pharmaceutical industries', 'Tab', 'أقراص', '', 'Diuretic', '1.5mg', 'Indapamide is a diuretic indicated for use as monotherapy or in combination with other blood pressure-lowering agents to treat hypertension.[L13982] It may also be used to treat fluid and salt retention associated with congestive heart failure.[L13982]', '', '', 1220, '2023-10-12', CURRENT_TIMESTAMP),
(4924, 'Flatidyl 40mg 30 chewable tabs', 'فلاتيديل 40مجم 30 قرص للمضغ', '33', '54', 'Simethicone', 'Kahira', 'Tab', 'أقراص', 'مضاد للانتفاخ -- لعلاج حالات الانتفاخ ومغص القولون -- لتخفيف الشعور بالامتلاء وغازات البطن', 'Antiflatulent', '40mg', 'Simethicone is indicated for the treatment of bloating, pressure, and cramps caused by gas.[L31533] Simethicone is also used as part of bowel preparation for colonoscopies.[A228343]', '6221068000397', '', 15012, '2024-07-04', CURRENT_TIMESTAMP),
(19371, 'Four lite lightening cream 50 gm', 'فور لايت كرين تفتيح 50جم', '', '150', 'Tyrostat 11+licorice ex+vitamin (c+e)+bearberry ex+panthenol+allantoin+honey+stearic acid+almond oil', 'Italian cosmetics company > feel good canada', 'Cream', 'كريم', '', 'Whitening topical', '50 gm', '** ph5.5 soft healthy skin - unifies corrects and illuminates brown spots - pigmentation imperfection ** directions: apply to cleansed skin twice a day', '', '', 714, '2022-08-03', CURRENT_TIMESTAMP),
(25448, 'Pro-vit syrup 120 ml', 'برو فيت شراب 120مل', '', '20', 'Vitamins+iron', 'Ob.t pharma > raf pharma', 'Syrup', 'شراب', '', 'Multivitamins', '120 ml', '', '', '', 719, '2022-07-29', CURRENT_TIMESTAMP),
(1364, 'Hanci-care soothing spray rapid action 30 ml', 'هانسي كير سبراي ملطف سريع المفعول 30 مل', '75', '85', 'Sea water+hyaluronic acid+panthenol+hypertonic glycerol+vitamin a+vitamin e+biotin', 'Promedica', 'Spray', 'بخاخ', '', 'Nasal spray', '30 ml', '', '6224008585985', '', 1007, '2025-10-27', CURRENT_TIMESTAMP),
(23589, 'Night calm 1mg 30 f.c. tabs.', 'نايت كالم 1مجم 30 قرص', '43.5', '60', 'Eszopiclone', 'Medizen pharmaceutical industries', 'Tab', 'أقراص', '', 'Psychiatric.anxiolytics-hypnotics', '1mg', 'Eszopiclone is indicated for the treatment of insomnia.[L6769]', '6222012401833', '', 2914, '2024-06-03', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(7569, 'Miss white 60 gm cream', 'ميس وايت كريم 60 جم', '', '165', 'Alpha arbutin+vit c+liquorice ext+hyaluronic acid+collagen', 'Miss white', 'Cream', 'كريم', '', 'Skin cream', '60 gm', '', '', '', 789, '2024-08-05', CURRENT_TIMESTAMP),
(23319, 'Navesetron 0.25mg/5ml vial for i.v.', 'نافيسيترون 0.25/5مل فيال', '', '110', 'Palonosetron', 'Sedico > rameda', 'Vial', 'فيال', '', 'Antiemetic', '0.25mg', 'For the prevention of acute and delayed nausea and vomiting associated with initial and repeat courses of moderately emetogenic cancer chemotherapy, as well as prevention of acute nausea and vomiting associated with highly emetogenic cancer chemotherapy. Also used for the prevention of postoperative nausea and vomiting for up to 24 hours post operation.', '', '', 1110, '2022-07-17', CURRENT_TIMESTAMP),
(10458, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 654, '2023-01-14', CURRENT_TIMESTAMP),
(14183, 'Angitect 60mg 20 f.c.tab.', 'انجيتكت 60 مجم 20 قرص', '', '12', 'Diltiazem', 'Marcyrl co.', 'Tab', 'أقراص', '', 'Antihypertensive.nonselective calcium channel blocker', '60mg', '**Oral**
Indicated for the management of hypertension, to lower blood pressure, alone or in combination with other antihypertensive agents.[L10556]
Indicated for use to improve exercise tolerance in patients with chronic stable angina.[L10556]
Indicated for the management of variant angina (Prinzmetal''s angina).[L6298]
**Intravenous**
Indicated for the short-term management of atrial fibrillation or atrial flutter for temporary control of rapid ventricular rate.[L6292]
Indicated for the rapid conversion of paroxysmal supraventricular tachycardias (PSVT) to sinus rhythm. This includes AV nodal reentrant tachycardias and reciprocating tachycardias associated with an extranodal accessory pathway such as the WPW syndrome or short PR syndrome.[L6292]
**Off-label**
Indicated for off-label uses in anal fissures (as topical formulation), migraine prophylaxis, cramps in lower leg related to rest, pulmonary hypertension,[L6289] idiopathic dilated cardiomyopathy, and proteinuria associated with diabetic nephropathy.[L6298]', '', '', 1896, '2022-07-09', CURRENT_TIMESTAMP),
(23742, 'Norocarmena 0.02/3mg 28 f.c.tab', 'نوروكارمينا 28 قرص', '78', '103', 'Ethinyl estradiol+drospirenone', 'Laboratoires leon > amriya', 'Tab', 'أقراص', 'حبوب منع حمل عن طريق الفم', 'Contraceptives', '3mg', '', '', '', 1558, '2025-08-23', CURRENT_TIMESTAMP),
(19728, 'Gentamicin-sigma 0.1% top. cream 15 gm', 'جنتاميسين سيجما 0.1% كريم 15 جم', '', '4', 'Gentamicin', 'Sigma', 'Cream', 'كريم', '', 'Aminoglycoside antibiotic', '0.1%', 'about gentamicin aminoglycoside antibiotic. mechanism of action of gentamicin gentamicin exerts its bactericidal action against gram negative organisms & some of gram positive organisms by inhibiting bacterial protein synthesis. the process involves 1. pe', '', '', 867, '2022-07-14', CURRENT_TIMESTAMP),
(7186, 'Schwancell 20 hard gelatin capsules', 'شوانسيل 20 كبسولة', '', '160', 'Alpha lipoic aacid+benfotiamine+vitamin d3+vitamin b12 ( methylcobalamine)+vitamin b6', 'Magic dose pharma', 'Capsule', 'كبسولة', '', 'Antioxidant', '', '', '6224008689973', '', 1430, '2025-08-25', CURRENT_TIMESTAMP),
