Alfacalcidol is indicated in the management of nutritional and malabsorptive rickets and osteomalacia, vitamin D-dependent rickets and osteomalacia, and hypophosphataemic vitamin D resistant rickets and osteomalacia.[L33364,L33369]', '', '', 883, '2024-09-26', CURRENT_TIMESTAMP),
(13528, 'Advoctam 4.5 gm pd. for iv inf.', 'ادفوكتام 4.5جم بودره وريد', '', '40', 'Piperacillin+tazobactam', 'Mup > arab caps', 'Unknown', 'غير محدد', '', 'Antibiotic', '4.5 gm', 'about piperacillin a semisynthetic extended spectrum penicillin(ureidopenicillin) antiboitic. mechanism of action of piperacillin piperacillin is a semi synthetic antipseudomonal penicillin. it binds to the penicillin binding protein in the cell wall of b', '', '', 1186, '2022-07-07', CURRENT_TIMESTAMP),
(2099, 'Carfalone 50mg 20 f.c. tabs.', 'كارفالون 50مجم 20 قرص', '149', '198', 'Eplerenone', 'Marcyrl co.', 'Tab', 'أقراص', 'علاج لمرضى القلب -- مرضى ضغط الدم', 'Aldosterone receptor antagonist', '50mg', 'For improvement of survival of stable patients with left ventricular systolic dysfunction (ejection fraction <40%) and clinical evidence of congestive heart failure after an acute myocardial infarction.', '6223003579388', '', 2606, '2025-07-15', CURRENT_TIMESTAMP),
(13734, 'Aliquam anti-dandruff shampoo 200 ml', 'الكيوم شامبو ضد القشرة 200 مل', '', '40', 'Piroctone olamine+salicylic acid+rosemary oil+chamomile oil+jojoba oil+panthenol', 'Egyptian company for cosmetics > italian cosmetics co.', 'Amp', 'أمبول', '', 'Hair care', '200 ml', '', '', '', 464, '2022-08-05', CURRENT_TIMESTAMP),
(9999, 'Aaa', 'ششش', '', '35', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 801, '2023-01-02', CURRENT_TIMESTAMP),
(27021, 'Simvastat 10mg 7 tab.', 'سيمفاستات 10مجم 7 اقراص', '', '25', 'Simvastatin', 'T3a pharma > rexcel', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '10mg', 'Simvastatin is indicated for the treatment of hyperlipidemia to reduce elevated total cholesterol (total-C), low-density lipoprotein cholesterol (LDL‑C), apolipoprotein B (Apo B), and triglycerides (TG), and to increase high-density lipoprotein cholesterol (HDL-C).[F4655, F4658]
This includes the treatment of primary hyperlipidemia (Fredrickson type IIa, heterozygous familial and nonfamilial), mixed dyslipidemia (Fredrickson type IIb), hypertriglyceridemia (Fredrickson type IV hyperlipidemia), primary dysbetalipoproteinemia (Fredrickson type III hyperlipidemia), homozygous familial hypercholesterolemia (HoFH) as an adjunct to other lipid-lowering treatments, as well as adolescent patients with Heterozygous Familial Hypercholesterolemia (HeFH).[F4655, F4658]
Simvastatin is also indicated to reduce the risk of cardiovascular morbidity and mortality including myocardial infarction, stroke, and the need for revascularization procedures. It is primarily used in patients at high risk of coronary events because of existing coronary heart disease, diabetes, peripheral vessel disease, history of stroke or other cerebrovascular disease.[F4655, F4658]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '', '', 734, '2022-07-16', CURRENT_TIMESTAMP),
(12620, 'White precipitate oint 30 gm', 'مرهم راسب ابيض 30 جرام', '', '10', 'Ammoniated mercury+liquid paraffin+vaseline', 'Company', 'Oint', 'مرهم', 'علاج الديدان الشرجية ومنع تكاثرها -- التخلص من الحكة في هذه المنطقة', '', '30 gm', '', '8951175472210', '', 2919, '2022-05-28', CURRENT_TIMESTAMP),
(14038, 'Ampicillin-cid 500 mg 12 caps.', 'امبيسيلين سيد 500 مجم 12 كبسولة', '', '10', 'Ampicillin', 'Cid', 'Cap', 'كبسولة', '', 'Penicillins.monocomponent', '500 mg', 'For treatment of infection (Respiratory, GI, UTI and meningitis) due to E. coli, P. mirabilis, enterococci, Shigella, S. typhosa and other Salmonella, nonpenicillinase-producing N. gononhoeae, H. influenzae, staphylococci, streptococci including streptoc', '', '', 876, '2022-07-22', CURRENT_TIMESTAMP),
(785, 'Nazowell 150 mg 1 cap.', 'نازويل 150مجم 1 كبسولة', '24.5', '36', 'Fluconazole', 'Health well', 'Cap', 'كبسولة', 'مضاد فطريات', 'Antifungals.triazoles', '150 mg', 'Fluconazole can be administered in the treatment of the following fungal infections[L11043]:
 1) Vaginal yeast infections caused by Candida
 2) Systemic Candida infections
 3) Both esophageal and oropharyngeal candidiasis 
 4) Cryptococcal meningitis
 5) UTI (urinary tract infection) by Candida
 6) Peritonitis (inflammation of the peritoneum) caused by Candida
**A note on fungal infection prophylaxis**
Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '6224000911713', '', 6553, '2024-08-13', CURRENT_TIMESTAMP),
(28025, 'Tenotens 100mg 14 f.c.tab.', 'تينوتنس 100مجم 14 اقراص', '', '11', 'Atenolol', 'Kahira', 'Tab', 'أقراص', '', 'Antihypertensive.beta blocker.selective b1', '100mg', '**Indicated** for:[label]
1) Management of hypertension alone and in combination with other antihypertensives.
2) Management of angina pectoris associated with coronary atherosclerosis.
3) Management of acute myocardial infarction in hemodynamically stable patients with a heart rate greater than 50 beats per minutes and a systolic blood pressure above 100 mmHg.
**Off-label** uses include:
1) Secondary prevention of myocardial infarction.[A178156]
2) Management of heart failure.[A178153]
3) Management of atrial fibrillation.[A178141]
4) Management of supraventricular tachycardia.[A178162]
5) Management of ventricular arrythmias such as congenital long-QT and arrhythmogenic right ventricular cardiomyopathy.[A178168]
6) Management of symptomatic thyrotoxicosis in combination with [methimazole].[A178147]
7) Prophylaxis of migraine headaches.[A178171]
8) Management of alcohol withdrawal.[A178174,A178177]', '', '', 989, '2022-07-12', CURRENT_TIMESTAMP),
(1023, 'Ekiroz 40 mg 14 gastro resistant tablet', 'اكيروز 40مجم 14 قرص', '', '82', 'Pantoprazole', 'Hp pharma', 'Tablet', 'أقراص', '', 'Peptic ulcer proton pump inhibitor', '40 mg', '**Pantoprazole Injection**:
**Treatment of gastroesophageal reflux disease associated with a history of erosive esophagitis**
Pantoprazole for injection is indicated for short-term treatment (7-10 days) of patients having gastroesophageal reflux disease (GERD) with a history of erosive esophagitis, as an alternative to oral medication in patients who are unable to continue taking pantoprazole delayed-release tablets. _Safety and efficacy of pantoprazole injection as the initial treatment of patients having GERD with a history of erosive esophagitis have not been demonstrated at this time_.[FDA label]
**Pathological Hypersecretion Associated with Zollinger-Ellison Syndrome**
Pantoprazole for injection is indicated for the treatment of pathological hypersecretory conditions associated with Zollinger-Ellison Syndrome or other neoplastic conditions.[FDA label]
**Pantoprazole delayed-release oral suspension**:
**Short-Term Treatment of erosive esophagitis associated with gastroesophageal reflux disease (GERD)**
Indicated in adults and pediatric patients five years of age and above for the short-term treatment (up to 8 weeks) in the healing and symptomatic relief of erosive esophagitis. For adult patients who have not healed after 8 weeks of treatment, an additional 8-week course of pantoprazole may be considered. Safety of treatment beyond 8 weeks in pediatric patients has not been determined.[F3202]
**Maintenance of healing of erosive esophagitis**
Indicated for maintenance of healing of erosive esophagitis and reduction in relapse rates of daytime and nighttime heartburn symptoms in adult patients with GERD.[F3202]
**Pathological hypersecretory conditions including Zollinger-Ellison syndrome**
Indicated for the long-term treatment of the above conditions.[F3202]', '', '', 2532, '2024-10-31', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(28520, 'Trinutrex 30 caps.', 'ترينوتركس 30 كبسولة', '', '210', 'Royal jelly+ginseng+ginko biloba', 'Future pharmaceutical industries (fpi) > utopia pharmaceuticals company', 'Cap', 'كبسولة', 'مكمل غذائي ومنشط عام للجسم -- يستخدم لعلاج أمراض الذاكرة لكبار السن كالزهايمر -- لعلاج قلة التركيز -- يعزز المناعة -- يساعد مرضى السكري في تقليل الشعور بتنميل في الأطراف وإلتهاب الأعصاب.', 'Multivitamins', '', '', '6224009687855', '', 11843, '2023-02-15', CURRENT_TIMESTAMP),
(17985, 'Durogesic 75mcg/hr 5 transdermal patch', 'ديوروجيسيك 75ميكروجرام/ساعة 5 لصقات للجلد', '905', '1,294', 'Fentanyl', 'Janssen cilag', 'Patch', 'لصقة', '', 'Analgesics.opioid', '75mcg', 'Fentanyl intravenous or intramuscular injections are indicated for short term analgesia during induction, maintenance, and recovery from general or regional anesthesia.[Label] These injections are also used with a neuroleptic for premedication, induction, and as an adjunct to maintenance of anesthesia.[Label] Finally, fentanyl intravenous or intramuscular injections are used with oxygen for anesthesia in high risk patients.[Label]
