(13583, 'Ozempic 1mg prefilled pen', 'اوزمبك 1مجم اقلام معبأة للحقن', '2500', '4,000', 'Semaglutide', 'Novo nordisk', 'Pen', 'قلم', 'احتل عقار "أوزمبك" (Ozempic) عناوين الأخبار التي تحدثت عن نجاح من يتلقونه في فقدان الوزن وتحسين السيطرة على سكر الدم، منهم طبيب كتبه لمرضاه ثم استعمله ليفقد 12 كيلوغراما. فكيف يعمل هذا العقار؟ وما فقدان الوزن المتوقع عند استعماله؟ وهل له محاذير؟', 'Anti-diabetic.glp-1 receptor agonist', '1mg', 'Semaglutide is always intended to be used with a reduced calorie diet and increased physical activity. It is indicated to improve glycemic control in adults diagnosed with type 2 diabetes mellitus.[L8678,L8681] However, semaglutide is not a suitable first-line drug for diabetes that has not been controlled by diet and exercise. In addition, it has not been studied in patients with pancreatitis.  Semaglutide is not intended for use in patients with type 1 diabetes or to treat diabetic ketoacidosis.[L8678]
Semaglutide is indicated for chronic weight management in adults with obesity or overweight with at least one weight-related condition (such as high blood pressure, type 2 diabetes, or high cholesterol).[L34475,L41335]. Semaglutide it is also indicated for chronic weight management in pediatric patients aged 12 years and older with an initial BMI at the 95th percentile or greater for age and sex.[L44552]
Semaglutide is also used to reduce the risk of major adverse cardiovascular events (cardiovascular death, non-fatal myocardial infarction, or non-fatal stroke) in adults with established cardiovascular disease and either obesity or overweight.[L50452]', '', '', 52594, '2024-08-28', CURRENT_TIMESTAMP),
(20220, 'Hairowth hair shampoo 200 ml', 'هيروث شامبو للشعر 200 مل', '', '200', '', 'Kempetro for chemical industries > novell pharma', 'Amp', 'أمبول', '', 'Hair care', '200 ml', '', '', '', 713, '2022-08-02', CURRENT_TIMESTAMP),
(15301, 'Bio-tech 10 sachets 330 gm', 'بيو تيك 10 اكياس 330 جم', '99.5', '140', 'Skimmed milk+whey protein+maltodextrine+soy protein+sucrose+sodium caseinate+natural flavour', 'Bio pharma egypt', 'Sachet', 'أكياس', '', 'Dietary supplement', '330 gm', 'available in 4 flavors: vanilla | chocolate | strawberry | banana indications: -anorexia in children and adolescent of an organic or emotional-psychological cause. -underweight people. -malnourished geriatrics. fatigue and muscle weakness. -persons with i', '', '', 791, '2024-10-31', CURRENT_TIMESTAMP),
(5747, 'Marcrisa topical ointment 20 gm', 'ماركريزا مرهم 20 جم', '', '400', 'Crisaborole', 'Marcyrl', 'Ointment', 'مرهم', '', 'Dermatological drugs.nsaid.pde-4 inhibitor', '20 gm', 'Intended for the topical treatment of mild to moderate atopic dermatitis in patients 2 years of age and older.', '', '', 1771, '2024-05-27', CURRENT_TIMESTAMP),
(14231, 'Tronic d3 oral drops 15 ml', 'ترونيك د3 نقط فم 15 مل', '', '54', 'Vitamin d3', 'Medtronic for pharmaceuticals', 'Drops', 'نقط', '', 'Vitamin d', '15 ml', 'For the treatment of vitamin A deficiency.', '', '', 1359, '2024-09-04', CURRENT_TIMESTAMP),
(3598, 'Diamicron mr 30 mg 30 tab.', 'دياميكرون ام ار 30مجم 30 قرص', '60', '80', 'Gliclazide', 'Servier', 'Tab', 'أقراص', 'حالات مرضي السكري', 'Anti-diabetic.secretagogues.sulfonylurea', '30 mg', 'For the treatment of NIDDM in conjunction with diet and exercise.', '6223003960094', '', 5788, '2025-10-14', CURRENT_TIMESTAMP),
(31907, 'Copadtada 20 mg 4 tabs.', 'كوبادتادا 20مجم 4 اقراص', '', '100', 'Tadalafil', 'Copad egypt', 'Tab', 'أقراص', 'مقوى للرجال', 'Tonic for men', '20 mg', 'Tadalafil is indicated for the treatment of erectile dysfunction (ED) and either alone or in combination with [finasteride] for the treatment of benign prostatic hypertrophy (BPH).[L39095,L39439] It is also indicated for the treatment of pulmonary arterial hypertension (PAH) both alone and in combination with [macitentan] or other endothelin-1 antagonists.[L39100,L39105,L50622]', '', '', 2932, '2023-05-18', CURRENT_TIMESTAMP),
(19558, 'Gaptin 250mg/5ml oral solution 120 ml', 'جابتن 250مجم/5مل شراب 120 مل', '', '45', 'Gabapentin', 'Delta pharma', 'Solution', 'محلول', 'علاج الصرع -- يخفف الالام العصبية', 'Anti-epileptic.gaba analogs', '250mg', 'In the United States, gabapentin is officially indicated for the treatment of postherpetic neuralgia in adults and for the adjunctive treatment of partial-onset seizures, with or without secondary generalization, in patients 3 years of age and older.[L8717] In Europe, gabapentin is indicated for adjunctive therapy in the treatment of partial-onset seizures, with or without secondary generalization, in patients 6 years of age and older and as monotherapy in patients 12 years of age and older. It is also used in adults for the treatment of various types of peripheral neuropathic pain, such as painful diabetic neuropathy.[L8732]', '', '', 1291, '2022-08-16', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(22137, 'Lycomen 20 capsules', 'ليكومين 20 كبسولة', '', '39', 'Saw palmetto oil+tomato extract+d-calcium glucarate+vitamin c+zinc sulfate', 'Debeiky', 'Capsule', 'كبسولة', 'دعم صحة البروستاتا', 'Prostate support', '', 'improve prostatic functions', '6225000005433', '', 1959, '2022-12-06', CURRENT_TIMESTAMP),
(16106, 'Aaa', 'ششش', '', '45', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 614, '2022-09-08', CURRENT_TIMESTAMP),
(18458, 'Epirubicin mylan 10mg/5ml vial i.v. inf.', 'ايبريوبسين ميلان 10مجم/5مل مل فيال', '', '85', 'Epirubicin', 'Mylan s.a.s-france > ramco', 'Vial', 'فيال', '', 'Antineoplastic', '10mg', 'For use as a component of adjuvant therapy in patients with evidence of axillary node tumor involvement following resection of primary breast cancer.', '', '', 860, '2022-07-24', CURRENT_TIMESTAMP),
(8592, 'Nasotal compound spray 15 ml', 'نازوتال مركب 15 مل نقط للانف', '', '9', 'Sodium cromoglycate+xylometazoline', 'Amoun', 'Spray', 'بخاخ', '', 'Nasal decongestant', '15 ml', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '6221025004062', '', 1368, '2023-02-26', CURRENT_TIMESTAMP),
(27590, 'Suave face cream 50 gm', 'سوف كريم للوجه 50جم', '', '22', 'Tea tree oil+salicylic acid+bees wax+stearic acid+glycerin+paraffin oil+vaseline', 'El-helou perfumes & cosmetics > pharmavera pharmaceutical co.', 'Cream', 'كريم', '', 'Skin care', '50 gm', 'Indicated for topical use to help protect against infection in minor cuts, scrapes, and burns. No FDA-approved therapeutic indications.', '', '', 501, '2022-07-24', CURRENT_TIMESTAMP),
(11673, 'Hoffidux 60 ml syrup', 'هوفيدوكس شراب 60 مل', '', '180', 'Citicoline 100 mg+omega 3 (epa+dha)+gincobiloba extract', 'Hoffmann pharm', 'Syrup', 'شراب', '', 'Memory booster', '60 ml', '', '', '', 895, '2024-09-07', CURRENT_TIMESTAMP),
(18175, 'Elimbosis 5 mg 10 f.c. tabs.', 'اليمبوسيس 5مجم 10 قرص', '', '90', 'Apixaban', 'Debeiky > zeta pharm', 'Tab', 'أقراص', '', 'Anticoagulant', '5 mg', 'Apixaban is indicated for reducing the risk of stroke and systemic embolism in patients who have nonvalvular atrial fibrillation, prophylaxis of deep vein thrombosis(DVT) leading to pulmonary embolism(PE) in patients after a hip or knee replacement surgery, and treatment of DVT and PE to reduce the risk of recurrence[Label,A177565,A6897].', '', '', 1237, '2022-07-08', CURRENT_TIMESTAMP),
(14850, 'Baby comfort oint. 20 gm', 'بيبي كومفورت مرهم 20 جم', '', '16', '', 'Pharco', 'Oint', 'مرهم', 'diaper rash', 'Soothing topical', '20 gm', 'skin soothing for diaper area.', '', '', 863, '2022-09-18', CURRENT_TIMESTAMP),
(26438, 'Sacrix 1g*50 sachets', 'ساكريكس 1جم 50 كيس', '', '38', 'Sucralose+dextrose+maltodextrin', 'Pharma zad > bionil', 'Sachet', 'أكياس', '', 'Sweetener', '', 'zero calorie sweetener', '', '', 932, '2022-07-26', CURRENT_TIMESTAMP),
(32099, 'Adox 10 sachets', 'ادوكس 10 اكياس', '', '145', 'Collagen+vitamin c+omega 3+calcium+magnesium+vitamin d3+vitamin k', 'Nutrixix > geomark', 'Sachet', 'أكياس', '', 'Multivitamin', '', '', '', '', 519, '2023-04-24', CURRENT_TIMESTAMP),
(8310, 'Skykur cream 120 gm', 'سكايكور كريم 120 جم', '210', '225', '', 'Egyptian company for cosmetics > prime international pharma', 'Cream', 'كريم', '', 'Soothing topical', '120 gm', '', '', '', 935, '2025-08-23', CURRENT_TIMESTAMP),
(7686, 'Roma rova nanosilver spray 100 ml', 'روما روفا نانوسيلفر سبراي 100 مل', '', '699', 'Nanosilver+hyaluronic acid+collagen+l-carnitine+silicon+panthenol+others', 'Roma rova', 'Spray', 'بخاخ', '', 'Healing and antiscar spray', '100 ml', '', '', '', 734, '2025-10-14', CURRENT_TIMESTAMP),
(30577, 'Futi-d 400 i.u./drop oral drops 15 ml', 'فيوتي -د 400وحدة/نقطة نقط للفم 15 مل', '35', '45', 'Cholecalciferol(vitamin d3)', 'Amcomed > futinnova', 'Drops', 'نقط', '', 'Vitamin d3', '15 ml', 'description derivative of 7-dehydroxycholesterol formed by ultraviolet rays breaking of the c9-c10 bond. it differs from ergocalciferol in having a single bond between c22 and c23 and lacking a methyl group at c24 indication for the treatment of vitamin d', '', '', 1484, '2023-09-19', CURRENT_TIMESTAMP),
(19271, 'Folic acid (memphis) 5 mg 30 tab.', 'فوليك اسيد ممفيس 5مجم 30 قرص', '15.75', '16', 'Folic acid', 'Memphis', 'Tab', 'أقراص', '', 'Folic acid supplement', '5 mg', 'Folic acid is indicated for the treatment of folic acid deficiency, megaloblastic anemia, and in anemias of nutritional origins, pregnancy, infancy, or childhood.', '6221077010615', '', 1291, '2024-10-18', CURRENT_TIMESTAMP),
(28236, 'Tobrabiotic plus ophth. susp. 5 ml', 'توبرابيوتك بلس قطرة للعين 5مل', '', '9', 'Dexamethasone+tobramycin', 'Sigma tec', 'Susp', 'معلق', '', 'Antibiotic with glucocorticoid', '5 ml', '', '6221172002652', '', 886, '2022-07-20', CURRENT_TIMESTAMP),
(22384, 'Maxi care cream 75 gm', 'ماكسي كير كريم 75 جرام', '98', '137', 'Gaultheria oil+clove oil+eucalyptus oil+turpentine+willow bark+rosemary+menthol+bees wax', 'Leader cosmetics > maryo pharm', 'Cream', 'كريم', 'مساج كريم لآلام الجسم والعضلات', 'Massage', '75 gm', 'massage cream', '', '', 6719, '2024-03-27', CURRENT_TIMESTAMP),
(14827, 'Azopt 1% eye drops 5 ml', 'ازوبت 1% قطرة 5 مل', '', '57', 'Brinzolamide', 'Novartis > novartis scientific office', 'Drops', 'نقط', '', 'Antiglaucoma', '1%', 'Brinzolamide, either as a standalone agent or in combination with brimonidine, is approved by the FDA for the treatment of elevated intraocular pressure in patients with ocular hypertension or open-angle glaucoma.[L46377,L35310] Brinzolamide is also approved in Europe to be used in combination with timolol to treat the same conditions.[L35320]', '7612797425640', '', 1594, '2022-12-03', CURRENT_TIMESTAMP),
(13022, 'Aaa', 'ششش', '', '31', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 690, '2022-07-31', CURRENT_TIMESTAMP),
(18689, 'Excelsa 20mg 14 f.c.tab.', 'اكسيلسا 20 مجم 14 قرص', '67.2', '114', 'Escitalopram', 'Pharopharma', 'Tab', 'أقراص', 'مضاد اكتئاب --مهدئ نفسي -- الامراض النفسية والعصبية -- يؤخذ تحت اشراف طبي', 'Psychiatric.antidepressants', '20mg', 'Escitalopram is indicated for the acute and maintenance treatment of major depressive disorder (MDD) in adults and pediatric patients 12 years old and older and for the acute treatment of generalized anxiety disorder (GAD) in adults and pediatric patients 7 years old and older.[L8513,L8513] It is additionally indicated for symptomatic relief of obsessive-compulsive disorder (OCD) in Canada.[L8516]', '6221094001177', '', 1101, '2024-10-18', CURRENT_TIMESTAMP),
(25683, 'Clozavitone 100 mg 20 f.c. tabs.', 'كلوزافيتون 100مجم 20 قرص', '43.50', '52', 'Clozapine', 'Medisave developed', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '100 mg', 'Clozapine is indicated for the treatment of severely ill patients with schizophrenia who fail to respond adequately to standard antipsychotic treatment. Because of the risks of severe neutropenia and of seizure associated with its use, Clozapine should be used only in patients who have failed to respond adequately to standard antipsychotic treatment.[L905]
Clozapine is also indicated for reducing the risk of recurrent suicidal behavior in patients with schizophrenia or schizoaffective disorder who are judged to be at chronic risk for re-experiencing suicidal behavior, based on history and recent clinical state. Suicidal behavior refers to actions by a patient that put him/herself at risk for death.[L905]', '6225000349759', '', 785, '2024-05-15', CURRENT_TIMESTAMP),
(8576, 'Reno topical gel 60 gm', 'رينو جل 60 جم', '', '120', '', 'Jacoub', 'Gel', 'جل', '', 'Anti-acne', '60 gm', '', '', '', 1007, '2024-06-30', CURRENT_TIMESTAMP),
(23058, 'Mucasert 2% topical cream 15 gm', 'ميوكازيرت 2% كريم 15جم', '', '11', 'Sertaconazole', 'El nile.', 'Cream', 'كريم', '', 'Antifungals.imidazoles', '2%', 'For the topical treatment of interdigital tinea pedis in immunocompetent patients 12 years of age and older, caused by <i>Trichophyton rubrum</i>, <i>Trichophyton mentagrophytes</i>, and <i>Epidermophyton floccosum</i>.', '6221035003062', '', 993, '2022-07-14', CURRENT_TIMESTAMP),
(17196, 'Delay-tiazem sr 90 mg 10 caps.', 'ديلاي تيازيم اس ار 90 مجم 10 كبسولات', '', '10', 'Diltiazem', 'Glaxo smithkline', 'Cap', 'كبسولة', '', 'Antihypertensive.nonselective calcium channel blocker', '90 mg', '**Oral**
Indicated for the management of hypertension, to lower blood pressure, alone or in combination with other antihypertensive agents.[L10556]
Indicated for use to improve exercise tolerance in patients with chronic stable angina.[L10556]
Indicated for the management of variant angina (Prinzmetal''s angina).[L6298]
**Intravenous**
Indicated for the short-term management of atrial fibrillation or atrial flutter for temporary control of rapid ventricular rate.[L6292]
Indicated for the rapid conversion of paroxysmal supraventricular tachycardias (PSVT) to sinus rhythm. This includes AV nodal reentrant tachycardias and reciprocating tachycardias associated with an extranodal accessory pathway such as the WPW syndrome or short PR syndrome.[L6292]
**Off-label**
Indicated for off-label uses in anal fissures (as topical formulation), migraine prophylaxis, cramps in lower leg related to rest, pulmonary hypertension,[L6289] idiopathic dilated cardiomyopathy, and proteinuria associated with diabetic nephropathy.[L6298]', '6221045001171', '', 959, '2022-12-04', CURRENT_TIMESTAMP),
(19708, 'Genove pilo-peptan anti hair-loss shampoo 250 ml', 'جينوفي بيلوبيبتان شامبو لتساقط الشعر 250 مل', '', '169', 'Hidrolized keratin panthenol vital hair & scalp complex poliquaternium 7', 'Laboratorio genove s.a. >', 'Amp', 'أمبول', '', 'Hair care', '250 ml', 'pilopeptan anti hair-loss shampoo helps preventing hair loss by stimulating the anagen or growing phase of hair increasing local microcirculation and activating hair follicles. gently cleanses strengthens hair and slows the progression of hair loss provid', '', '', 790, '2022-08-03', CURRENT_TIMESTAMP),
(10622, 'Sodium chloride 3% (mottahedoon) i.v. inf. 500 ml', 'صوديوم كلورايد 3% المتحدون محلول ملح وريدي 500 مل', '', '14', 'Sodium chloride', 'Al mottahedoon pharma', 'Unknown', 'غير محدد', 'تستخدم في حالات الجفاف الشديد -- مضاد سريع المفعول للحموضة -- حالات تسمم المخدرات', 'Sterile solution', '3%', 'This intravenous solution is indicated for use in adults and pediatric patients as a source of electrolytes and water for hydration. Also, designed for use as a diluent and delivery system for intermittent intravenous administration of compatible drug additives.', '6223003950941', '', 2433, '2022-05-30', CURRENT_TIMESTAMP),
(20521, 'Histine 16mg 20 tab.', 'هيستين 16 مجم 20 قرص', '', '14', 'Betahistine', 'Hikma pharma > future pharmaceutical industries (fpi)', 'Tab', 'أقراص', '', 'Diamine oxidase inhibitor.anti vertigo', '16mg', 'Betahistine is indicated for the reduction of recurrent vertigo episodes associated with Ménière''s disease in patients 18 years old and above.[L16388]', '6223004190148', '', 912, '2022-12-05', CURRENT_TIMESTAMP),
(32929, 'Guaiadesca syrup 120 ml', 'جواياديسكا شراب 120 مل', '21', '33', 'Dextromethorphan + guaifenesin', 'Rameda', 'Syrup', 'شراب', 'مهدئ للسعال.ومذيب وطارد للبلغم', 'Cough products', '120 ml', 'Dextromethorphan is indicated in combination with [brompheniramine] and [pseudoephedrine] in the treatment of coughs and upper respiratory symptoms associated with allergies or the common cold.[L14366] Dextromethorphan is also used in combination with [guaifenesin] as an over-the-counter product to relieve a cough.[L14369] Dextromethorphan in combination with [quinidine] is indicated in the treatment of pseudobulbar affect.[L14363]', '6223003970468', '', 2980, '2025-04-06', CURRENT_TIMESTAMP),
(10870, 'Statomain 100mg 30 scored f.c. tabs.', 'ستاتومين 100مجم 30 قرص', '106.5', '165', 'Fluvoxamine maleate', 'Biomed', 'Tab', 'أقراص', 'مضاد للإكتئاب', 'Selective serotonin reuptake inhibitor', '100mg', 'Indicated predominantly for the management of depression and for Obsessive Compulsive Disorder (OCD) [FDA Label]. Has also been used in the management of bulimia nervosa [A250].', '6222001401165', '', 5852, '2024-10-21', CURRENT_TIMESTAMP),
(33775, 'Tonigate omega 30 capsules', 'تونيجيت اوميجا 30 كبسولة', '195', '210', 'Dha+iron+vitamind3+19 vitamins and minerals', 'Bioctiva pharma', 'Capsule', 'كبسولة', '', 'Woman health care', '', '', '6225000501546', '', 2492, '2025-10-05', CURRENT_TIMESTAMP),
(23104, 'Multisol aerosol spray', 'مالتيسول ايروسول سبراي', '', '21', 'Bacitracin+neomycin+polymyxin', 'Arab center > adm for trading & projects-egypt', 'Sol', 'محلول', '', 'Antibiotic topical', '', 'mechanism of action of bacitracin bacitracin is an antibiotic produced by the strain of bacillus subtilis. it acts by inhibiting bacterial cell wall synthesis. it is active against a variety of gram positive and a few gram negative organisms. mechanism of', '', '', 998, '2022-07-25', CURRENT_TIMESTAMP),
