(24451, 'Paediment i.v. infusion 250 ml', 'بيدمنت محلول وريدى 250 مل', '', '17', 'Calcium gluconate+glucose (dextrose)+potassium chloride+sodium chloride', 'Otsuka', 'Unknown', 'غير محدد', 'محلول غني بالكالسيوم و الجلوكوز و الاملاح -- علاج الجفاف -- علاج الجروح الجلدية --', 'Sterile solution', '250 ml', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '6222014002410', '', 6649, '2023-02-04', CURRENT_TIMESTAMP),
(18082, 'Aaa', 'ششش', '', '106', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 665, '2022-07-27', CURRENT_TIMESTAMP),
(2474, 'Chartoreg co 40 / 10 mg 28 tabs.', 'شارتوريج كو 40/10مجم 28 قرص', '90', '188', 'Telmisartan+amlodipine', 'Utopia', 'Tab', 'أقراص', '', 'Antihypertensive.angiotensin blocker', '10 mg', '', '6223012330222', '', 1222, '2025-06-11', CURRENT_TIMESTAMP),
(19343, 'Forflozin plus 5/1000 mg 30 ext. rel . f.c. tabs.', 'فورفلوزين بلس 5/1000مجم 30 قرص', '', '171', 'Dapagliflozin+metformin', 'Atco pharma', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.sglt2 inhibitors', '1000 mg', '', '', '', 884, '2024-07-30', CURRENT_TIMESTAMP),
(30764, 'Kiraglow cream 30 gm', 'كيرا جلو كريم 30 جم', '55', '70', 'Triclosan+nicotinamide+alpha-bisabolol+tea tree oil+zn gluconate+sulfur+vitamin e+green tea extract+calendula extract+licorice extract', 'Dreams el habboba > opexa', 'Cream', 'كريم', 'كريم غنى بالفيتامينات ومضادات الاكسدة ويستخدم لترطيب وتجديد البشرة وعلاج حب الشباب', 'Skin care.anti-acne', '30 gm', 'kiraglow for mild to moderate acne treatment (comedones papules and pustules)', '6224009920075', '', 2703, '2024-03-13', CURRENT_TIMESTAMP),
(10551, 'Aaa', 'ششش', '', '95', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 676, '2023-05-01', CURRENT_TIMESTAMP),
(12073, 'Gubitak 60 tabs', 'جوبيتاك 60 قرص', '299', '329', 'Garcinia cambogia+green coffee+calcium carbonate', 'Slim gate', 'Tab', 'أقراص', '', 'Supplement', '', '', '', '', 2684, '2024-03-11', CURRENT_TIMESTAMP),
(1783, 'Dom vit 30ml drops', 'دوم فيت 30 مل نقط', '', '125', 'Cod liver oil ( 255mg dha+170mg epa+20 mg vitamin a)', 'Zahrat el jabal', 'Drops', 'نقط', '', 'Multivitamins', '30ml', 'Cod liver oil is predominantly manufactured, marketed, and used by the population at large as a general nutraceutical dietary supplement [A27154, A33159, L2872].
Historically, cod liver oil was often given to children because the vitamin d content in the oil had been shown to prevent or treat vitamin D deficiency and condition of rickets associated with it [A33159]. Over time, this common use in children growing up may have conferred upon cod liver oil its identity as a healthy and useful all-purpose dietary supplement.
However, since cod liver oil is a composite of several other nutritional compounds including the omega-3 fatty acids eicosapentaenoic acid (EPA) and docosahexaenoic acid (DHA) as well as vitamin A and vitamin D [A33159, L2872, L2871], the presence in varying amounts of all of these compounds at once makes it difficult to recommend or use cod liver oil as an appropriate supplement to confer any one particular health effect or for any one particular nutritional deficiency.
Regardless, because it does contain a combination of a number of important and healthy nutritional compounds, cod liver oil has sometimes been recommended in the literature for conferring the health effects of some of these compounds, such as the potential use of cod liver oil supplements in post-heart attack patients for secondary prophylaxis associated with the use of omega-3 fatty acids [A33165].', '', '', 999, '2024-12-12', CURRENT_TIMESTAMP),
(29816, 'Zadmicin 0.1% topical oint 20 gm', 'زادميسين 0.1% مرهم موضعي 20 جرام', '5.25', '26', 'Gentamicin', 'Zad', 'Oint', 'مرهم', 'مضاد حيوي يستخدم بشكل موضعي لعلاج التهابات الجلد، مثل القوباء والتهاب الجريبات، أو لعلاج بعض الأمراض الجلدية، مثل الأكزيما، والصدفية، والحروق، والجروح.', 'Aminoglycoside antibiotic', '0.1%', 'about gentamicin aminoglycoside antibiotic. mechanism of action of gentamicin gentamicin exerts its bactericidal action against gram negative organisms & some of gram positive organisms by inhibiting bacterial protein synthesis. the process involves 1. pe', '6224007855201', '', 5734, '2024-10-18', CURRENT_TIMESTAMP),
(20886, 'Integrado hair loss cream 100 gm', 'انتجرادو كريم لتساقط الشعر 100 جرام', '200', '280', 'Shea butter+argan oil+aloe vera extract+allantoin+vitamin e+coconut oil+wheat germ oil', 'Egyptian co. for cosmetics > orchidia pharmaceutical industries', 'Cream', 'كريم', 'العناية بالشعر -- منع تساقط الشعر', 'Hair care', '100 gm', 'integrado anti-hair loss cream is an advanced formula which decreases hair loss rate. it restores hair moisture reduces breakage and tangling adds shine and promotes new hair growth. it helps in decreasing hair dryness excellent for all types of hair. dir', '', '', 1049, '2025-03-09', CURRENT_TIMESTAMP),
(16251, 'Chlorophenalex 10mg/2ml 3 i.m. s.c. i.v. amp.', 'كلوروفينالكس 10مجم/مل 3 امبولات', '9', '17', 'Chlorpheniramine', 'Alexandria', 'Amp', 'أمبول', '', 'Antihistamine.antiallergy', '10mg', 'For the treatment of rhinitis, urticaria, allergy, common cold, asthma and hay fever.', '', '', 1561, '2025-08-09', CURRENT_TIMESTAMP),
(8658, 'Aaa', 'ششش', '', '12', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 816, '2022-11-11', CURRENT_TIMESTAMP),
(25734, 'Tadinurp 5mg syrup 120 ml', 'تادينارب 5مجم شراب 120 مل', '', '28', '', 'Pharopharma', 'Syrup', 'شراب', '', '', '5mg', '', '', '', 653, '2024-07-15', CURRENT_TIMESTAMP),
(15928, 'Castor oil mepaco 60 ml', 'زيت خروع ميباكو 60 مل', '', '30', 'Castor oil', 'Mepaco', 'Oil', 'زيت', 'ملين -- علاج حالات الامساك الشديدة -- يستخدم كشربة لافراغ المعدة والامعاء من الفضلات لاجراء التشخيص او العمليات الجراحية', 'Laxative', '60 ml', 'Indicated for over-the-counter use as a laxative for oral use and as a soothing agent for topical use on skin and hair.', '6222018805079', '', 1755, '2022-12-03', CURRENT_TIMESTAMP),
(8469, 'Aaa', 'ششش', '', '419', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 857, '2022-08-17', CURRENT_TIMESTAMP),
(25598, 'Qv skin lotion 50 ml', 'كيو في لوشن 50 مل', '', '179', '', 'Ego pharmaceuticals pty ltd. > vamer pharma', 'Lotion', 'لوشن', '', 'Skin care', '50 ml', 'non-greasy lotion for dry skin. qv skin lotion repairs and soothes dry skin. with a luxuriously light formulation to be spread all over the body .', '', '', 441, '2022-08-06', CURRENT_TIMESTAMP),
(17048, 'Dabiserve 75mg 10 caps.', 'دابيسيرف 75 مجم 10 كبسولات', '', '90', 'Dabigatran etexilate', 'Hochster pharmaceutical indusries > novell pharma', 'Cap', 'كبسولة', '', 'Anticoagulant.direct thrombin inhibitor', '75mg', 'Dabigatran etexilate is available in both oral pellet and capsule form. Dabigatran etexilate pellets are indicated for the treatment of venous thromboembolic events (VTE) in pediatric patients between three months and 12 years of age who have been treated with a parenteral anticoagulant for at least 5 days. They are also indicated in the same age group to reduce the risk of recurrence of VTE in patients who have been previously treated.[L34675]
In capsule form, dabigatran etexilate is indicated in adults to reduce the risk of stroke and systemic embolism associated with non-valvular atrial fibrillation and for the treatment of deep venous thrombosis (DVT) and pulmonary embolism (PE) in patients who have been treated with a parenteral anticoagulant for 5-10 days. It is also indicated in adults to reduce the risk of recurrence of DVT and PE in patients who have been previously treated and for the prophylaxis of DVT and PE in patients who have undergone hip replacement surgery. Lastly, it is indicated in pediatric patients between eight and 18 years of age for the treatment of venous thromboembolic events (VTE) in patients who have been treated with a parenteral anticoagulant for at least 5 days and to reduce the risk of recurrence of VTE in patients who have been previously treated.[L34680]
Dabigatran etexilate is also approved by the EMA to prevent VTE in adult patients. For pediatric patients, Dabigatran etexilate is used to treat TVE and prevent recurrent TVE for patients from birth to less than 18 years of age.[L46856]', '', '', 998, '2022-07-13', CURRENT_TIMESTAMP),
(3900, 'Biotin de zinc 30 hard gelatin capsules', 'بيوتين دي اي زنك 30 كبسولة', '', '300', 'Biotin+selenium+vitamin d3+vitamin e+zinc', 'Asena pharma', 'Capsule', 'كبسولة', '', 'Biotin supplement', '', '', '', '', 992, '2025-05-27', CURRENT_TIMESTAMP),
(21111, 'Jackodan gel 60 gm', 'جاكودان جل 60 جرام', '75', '89', 'Sulphur+tea tree ex+glycolic acid+rosemary ex+vit(c+e)+salicylic acid+retinol+panthenol+lavender oil', 'Egyptian company for cosmetics > kmt pharma', 'Gel', 'جل', 'جل غنى بالفيتامينات والمعادن لترطيب وترميم الجلد ومعالجة حب الشباب', 'Anti-acne', '60 gm', '** skin gel for acne prone skin ** ingredients: sulphur + tea tree extract + glycolic acid + rosemary extract + vitamin c + salicylic acid + vitamin e + retinol + panthenol + lavender oil + liquorice extract + glycerin + peppermint extract', '', '', 14721, '2024-04-30', CURRENT_TIMESTAMP),
(8060, 'Nilda hair serum 120 ml', 'نيلدا سيروم للشعر 120 مل', '', '200', '', '', 'Serum', 'سيروم', '', '', '120 ml', '', '', '', 787, '2025-11-19', CURRENT_TIMESTAMP),
(6140, 'Nutriville b-complex 30 tabs', 'نوتريفيل بي كومبلكس 30 قرص', '', '270', 'Vitamin b', 'Company', 'Tab', 'أقراص', '', 'Vitamin b', '', 'For the treatment of vitamin A deficiency.', '', '', 933, '2025-07-25', CURRENT_TIMESTAMP),
(27200, 'Sodium chloride 0.9% (otsuka) i.v. inf. 250 ml (rubber cap)', 'صوديوم كلوريد 0.9% محلول ملح وريدي اوتوسوكا زجاجة 250 مل بغطاء مطاطي', '', '14', 'Sodium chloride', 'Otsuka', 'Cap', 'كبسولة', '', 'Sterile solution', '0.9%', 'This intravenous solution is indicated for use in adults and pediatric patients as a source of electrolytes and water for hydration. Also, designed for use as a diluent and delivery system for intermittent intravenous administration of compatible drug additives.', '', '', 792, '2022-07-12', CURRENT_TIMESTAMP),
(15585, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 658, '2022-09-20', CURRENT_TIMESTAMP),
(24011, 'Oliptina 12.5 mg 30 f.c. tabs.', 'اوليبتينا 12.5مجم 30 اقراص', '', '119', 'Alogliptin', 'Rameda', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.dpp-4 inhibitors', '12.5 mg', 'Indicated as an adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus.', '', '', 883, '2022-07-26', CURRENT_TIMESTAMP),
(25562, 'Quitapex 400mg xr 30 f.c. tab.', 'كويتابيكس 400مجم اكس ار 30 قرص', '292.5', '387', 'Quetiapine', 'Multi-apex', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '400mg', 'Quetiapine is used in the symptomatic treatment of schizophrenia.  In addition, it may be used for the management of acute manic or mixed episodes in patients with bipolar I disorder, as a monotherapy or combined with other drugs. It may be used to manage depressive episodes in bipolar disorder. In addition to the above indications, quetiapine is used in combination with antidepressant drugs for the treatment of major depression.[L8546]
Some off-label uses for this drug include the management of post-traumatic stress disorder (PTSD), generalized anxiety disorder, and psychosis associated with Parkinson''s disease.[A185438,A185447,T685]', '6223003204556', '', 1819, '2024-12-17', CURRENT_TIMESTAMP),
(10431, 'Aaa', 'ششش', '', '30', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 877, '2022-12-08', CURRENT_TIMESTAMP),
(19629, 'Aaa', 'ششش', '', '16', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 752, '2022-07-08', CURRENT_TIMESTAMP),
(8980, 'Fentorin 100 mg 10 sachets', 'فنتورين 100 مجم 10 اكياس', '', '90', 'Lactoferrin', 'Rx pharma', 'Sachet', 'أكياس', '', '', '100 mg', '', '2664008851132', '', 923, '2022-10-10', CURRENT_TIMESTAMP),
(18664, 'Euvax-b 20mcg/ml i.m (5ml) vial', 'ايفاكس-بي 20 ميكروجرام/مل (5مل) فيال', '', '37', 'Vaccine hepatitis b', 'Lg life science ltd -korea > egycopharm', 'Vial', 'فيال', '', 'Vaccine', '20mcg', '', '', '', 890, '2022-07-13', CURRENT_TIMESTAMP),
(2390, 'Cerebro 400mg 30 caps.', 'سيريبرو 400مجم 30 كبسولة', '36', '48', 'Piracetam', 'Unipharma co.', 'Cap', 'كبسولة', 'يعمل على تحسين الدورة الدموية بالمخ.', 'Cerebral circulatory inhancer', '400mg', 'Indicated in adult patients suffering from myoclonus of cortical origin, irrespective of aetiology, and should be used in combination with other anti-myoclonic therapies [L1125].', '6224000730451', '', 3057, '2025-07-15', CURRENT_TIMESTAMP),
(20861, 'Insulatard hm 100i.u./ml 10 ml vial', 'انسولاتارد اتش ام 100 وحدة دولية / مل 10 مل فيال', '75.5', '130', 'Insulin isophane protamine human', 'Novo nordisk', 'Vial', 'فيال', '', 'Anti-diabetic.insulin analouge', '10 ml', 'Human insulin is indicated to improve glycemic control in adults and pediatric patients with diabetes mellitus.', '', '', 1254, '2025-10-13', CURRENT_TIMESTAMP),
(14366, 'Arcalion forte 400mg 30 f.c.tab', 'اركاليون فورت 400 مجم 30 قرص', '', '53', 'Sulbutiamine', 'Servier', 'Tab', 'أقراص', 'منبه عصبي', 'Nootropic', '400mg', '', '6223003960032', '', 8207, '2023-02-23', CURRENT_TIMESTAMP),
(3253, 'Thivaherb 120 ml syrup', 'ثيفاهيرب 120 مل شراب', '', '55', 'Ivy+licorice+thyme', 'Spirit pharm', 'Syrup', 'شراب', '', 'Anti cough', '120 ml', '', '', '', 1049, '2025-03-02', CURRENT_TIMESTAMP),
(289, 'Alerid 10 mg 20 f.c.tabs. (n/a)', 'اليريد 10مجم 20 قرص', '', '31', 'Cetirizine', 'Global napi pharmaceuticals', 'Tab', 'أقراص', 'مضاد للحساسية يعمل على تخفيف أعراض الحساسية التي تنتج عن سيلان الأنف أو الزكام.يساعد في التخلص من حكة الأنف والحنجرة.يعمل على علاج التهاب الجيوب الأنفية.يعالج حالات الإصابة بالرمد.', 'Antihistamine.antiallergy', '10 mg', '**Seasonal Allergic Rhinitis**: Indicated for the relief of symptoms associated with seasonal allergic rhinitis caused by allergens such as ragweed, grass and tree pollens in adults and children 2 years of age and above. Symptoms treated effectively include sneezing, rhinorrhea, nasal pruritus, ocular pruritus, tearing, and redness of the eyes [FDA label]. 
**Perennial allergic rhinitis**: This drug is indicated for the relief of symptoms associated with perennial allergic rhinitis due to allergens including dust mites, animal dander, and molds in adults and children 6 months of age and older. Symptoms treated effectively include sneezing, rhinorrhea, postnasal discharge, nasal pruritus, ocular pruritus, and tearing [FDA label]. 
**Chronic urticaria**: Cetirizine is indicated for the treatment of the uncomplicated skin manifestations of chronic idiopathic urticaria in adults and children 6 months of age and older. It markedly reduces the occurrence, severity, and duration of hives and significantly reduces pruritus [FDA label].', '6223002142248', '', 1886, '2023-07-01', CURRENT_TIMESTAMP),
(5154, 'Zeluxia massage cream 100 gm', 'زيلوكسيا مساج كريم 100 جرام', '', '120', 'Methyl salicylate - camphor - menthol - eucalyptus - clove - pepermint oil', 'Green cure pharma', 'Cream', 'كريم', '', 'Massage cream', '100 gm', 'For topical use, in combination with 570 to 670 nm wavelength red light illumination, in the treatment of non-hyperkeratotic actinic keratoses of the face and scalp in immunocompetent patients when used in conjunction with lesion preparation (debridement using a sharp dermal curette).', '', '', 753, '2025-06-23', CURRENT_TIMESTAMP),
(21720, 'Lessuric 300mg 12 tab.', 'ليسيوريك 300 مجم 12 قرص', '', '5', 'Allopurinol', 'Alexandria', 'Tab', 'أقراص', '', 'Antigout.xanthine oxidase inhibitor', '300mg', 'Allopurinol is indicated in [FDA label]:
1) the management of patients with signs and symptoms of primary or secondary gout (acute attacks, tophi, joint destruction, uric acid lithiasis, and/or nephropathy).
2) the management of patients with leukemia, lymphoma and malignancies who are receiving cancer therapy which causes elevations of serum and urinary uric acid levels. Treatment with allopurinol should be discontinued when the potential for overproduction of uric acid is no longer present.
3) the management of patients with recurrent calcium oxalate calculi whose daily uric acid excretion exceeds 800 mg/day in male patients and 750 mg/day in female patients. Therapy in such patients should be carefully assessed initially and reassessed periodically to determine in each case that treatment is beneficial and that the benefits outweigh the risks.', '', '', 1085, '2022-07-17', CURRENT_TIMESTAMP),
(17803, 'Domaco camomile drink 150 gm', 'دوماكو كاموميل مشروب 150 جم', '', '70', 'Dextrose+herbal extracts from chamomile', 'Domaco > sami and co.', 'Unknown', 'غير محدد', '', 'Drinks', '150 gm', '', '6223001680246', '', 826, '2022-08-02', CURRENT_TIMESTAMP),
(17358, 'Dermenum hair lotion 150 ml', 'ديرمينام لوسيون للشعر 150 مل', '', '650', 'Molecule regen 7', 'Pharmena sa > multitrade', 'Lotion', 'لوشن', '', 'Hair care', '150 ml', 'indications: excessive hair loss in women. thinning hair also of androgenic origin. damaged weak and excessively falling out hair. greasy hair. best results can be achieved by using dermenumï¿½ women lotion twice a day ï¿½ in the morning and in the evenin', '', '', 1016, '2022-05-31', CURRENT_TIMESTAMP),
(13240, 'Totta calcium 24 tablets', 'توتاكال كالسيوم ماغنسيوم فيتامين د 24 قرص', '69', '78', 'Calcium magnesium+vitamin d', 'Octabiotic pharma', 'Tablet', 'أقراص', 'مكمل غذائي و معادن وفيتامينات كالسيوم وماغنسيوم وفيتامين دال', 'Calcium magnesium vitamin D', '', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 9867, '2023-09-06', CURRENT_TIMESTAMP),
