(26820, 'Serdolect 12mg 28 f.c. tab.', 'سيردوليكت 12مجم 14 اقراص', '700', '1,122', 'Sertindole', 'Lundbeck > multipharma', 'Tab', 'أقراص', '', 'Psychiatric.antipsychotics', '12mg', 'Used in the treatment of schizophrenia.', '', '', 803, '2024-11-17', CURRENT_TIMESTAMP),
(4607, 'Ezogast 20mg 14 dela. rel. caps', 'ايزوجاست 20مجم 14 كبسولة', '82', '122', 'Esomeprazole', 'October pharma > copad pharma', 'Cap', 'كبسولة', 'للحموضة وقرحة المعدة', 'Peptic ulcer.proton pump inhibitor', '20mg', 'Esomeprazole is indicated for the treatment of acid-reflux disorders including healing and maintenance of erosive esophagitis, and symptomatic gastroesophageal reflux disease (GERD), peptic ulcer disease, H. pylori eradication, prevention of gastrointestinal bleeds with NSAID use, and for the long-term treatment of pathological hypersecretory conditions including Zollinger-Ellison Syndrome.', '6223000443040', '', 1885, '2024-07-12', CURRENT_TIMESTAMP),
(8797, 'Aaa', 'ششش', '', '18', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 683, '2022-12-16', CURRENT_TIMESTAMP),
(10550, 'Aaa', 'ششش', '', '30', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 693, '2023-05-01', CURRENT_TIMESTAMP),
(4003, 'Vitab blast b tabs', 'فيتابلاست بي اقراص', '', '145', 'Vitamin b complex. all 8 types of vitamin b', 'Uptown pharma', 'Tab', 'أقراص', '', 'Vitamin b complex', '', 'For the treatment of vitamin A deficiency.', '', '', 741, '2022-12-04', CURRENT_TIMESTAMP),
(27745, 'Aaa', 'ششش', '', '120', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 706, '2022-10-07', CURRENT_TIMESTAMP),
(22437, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 615, '2022-10-29', CURRENT_TIMESTAMP),
(25591, 'Qv intensive body moisturiser cream 30 gm', 'كيو في كريم مرطب للجسم 30جم', '', '109', 'Light liquid paraffin+petrolatum+isopropyl myristate+polyethylene+cetearyl alcohol+silica+dimethicon', 'Ego pharmaceuticals pty ltd. > vamer pharma', 'Cream', 'كريم', '', 'Moisturizing topicals', '30 gm', '*soothing moisture for extremely dry and sensitive skin. even extremely dry cracked and sensitive skin can feel soft and pampered .', '', '', 431, '2022-08-06', CURRENT_TIMESTAMP),
(25157, 'Pregaba 50mg 20 cap.', 'بريجابا 50مجم 20 كبسولة', '', '96', 'Pregabalin', 'Egpi', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '50mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '6223003932077', '', 1200, '2022-12-08', CURRENT_TIMESTAMP),
(17262, 'Depakine 57.64mg/ml syp. 125 ml', 'ديباكين 5.764 مجم/مل شراب 125 مل', '36.5', '50', 'Valproic acid', 'Global napi pharmaceuticals > sanofi', 'Unknown', 'غير محدد', '', 'Anticonvulsant', '57.64mg', '**Indicated** for:[Label] 
1) Use as monotherapy or adjunctive therapy in the management of complex partial seizures and simple or complex absence seizures. 
2) Adjunctive therapy in the management of multiple seizure types that include absence seizures. 
3) Prophylaxis of migraine headaches.
4) Acute management of mania associated with bipolar disorder.
**Off-label** uses include:
1) Maintenance therapy for bipolar disorder.[A177919]
2) Treatment for acute bipolar depression.[A177928,A177931,A177934]
3) Emergency treatment of status epilepticus.[A177955]', '6223002147069', '', 2025, '2024-11-10', CURRENT_TIMESTAMP),
(2669, 'Citalo 2mg/ml oral solution 120 ml', 'سيتالو 2مجم/مل محلول 120 مل', '27', '38', 'Citalopram', 'Delta pharma', 'Solution', 'محلول', '', 'Psychiatric.antidepressants', '2mg', 'Citalopram is approved by the FDA for treating adults with major depressive disorder.[L47941] It has also been used off-label to treat various diseases, including but not limited to sexual dysfunction, ethanol abuse, psychiatric conditions such as obsessive-compulsive disorder (OCD), social anxiety disorder, panic disorder, and diabetic neuropathy.[L5224,A321,A322,A261296]', '6221163000933', '', 1414, '2024-09-10', CURRENT_TIMESTAMP),
(8736, 'Neurazine 25 mg 20 tab.', 'نيورازين 25 مجم 20 قرص', '8', '20', 'Chlorpromazine', 'Misr', 'Tab', 'أقراص', 'امراض نفسية', 'Psychiatric.antipsychotics', '25 mg', 'For the treatment of schizophrenia; to control nausea and vomiting; for relief of restlessness and apprehension before surgery; for acute intermittent porphyria; as an adjunct in the treatment of tetanus; to control the manifestations of the manic type of manic-depressive illness; for relief of intractable hiccups; for the treatment of severe behavioral problems in children (1 to 12 years of age) marked by combativeness and/or explosive hyperexcitable behavior (out of proportion to immediate provocations), and in the short-term treatment of hyperactive children who show excessive motor activity with accompanying conduct disorders consisting of some or all of the following symptoms: impulsivity, difficulty sustaining attention, aggressivity, mood lability, and poor frustration tolerance.', '6221035009354', '', 2170, '2024-12-15', CURRENT_TIMESTAMP),
(17685, 'Diomacte 1000mg/5ml susp. 60 ml', 'ديوماكت 20% معلق 60 مل', '15.5', '22', 'Dioctahedral smectite', 'Medizen pharmaceutical industries', 'Susp', 'معلق', '', 'Antidiarrheal', '1000mg', '', '6222012400645', '', 2398, '2024-07-24', CURRENT_TIMESTAMP),
(22809, 'Mipaflam 25 mg 20 e.c. tabs.', 'ميبافلام 25مجم 20 اقراص', '', '8', 'Diclofenac potassium', 'Mepaco', 'Tab', 'أقراص', '', 'Nsaid.acetic acid derivatives', '25 mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '', '', 800, '2022-07-16', CURRENT_TIMESTAMP),
(28117, 'Thiamphenil 0.75gm vial for i.v. or i.m. inj.', 'ثيامفينيل 0.75جم فيال', '', '8', 'Thiamphenicol', 'El nile.', 'Inj', 'حقن', '', 'Antibiotic', '0.75gm', 'thiamphenicol (also known as thiophenicol and dextrosulphenidol) is an antibiotic & immunosuppressive agent. it is the methyl-sulfonyl analogue of chloramphenicol and has a similar spectrum of activity but is 2.5 to 5 times as potent. like chloramphenicol', '', '', 695, '2022-07-28', CURRENT_TIMESTAMP),
(27358, 'Specpro 14 sachets', 'سبيكبرو 14 كيس', '135', '155', 'High concentration bovine colostrum+casecidins+oligosaccharide', 'Medcare > medicina medical ltd.', 'Sachet', 'أكياس', '', 'Immune enhancer', '', 'indications: -in recurrent infections. -three or more recurrent upper & lower respiratory infections. -for treating diarrhea & lactose intolerance. -as an immunostimulant. -for low birth body weight & malnutrition. -to enhance mental & physical activities', '6225000535886', '', 2175, '2025-08-16', CURRENT_TIMESTAMP),
(686, 'Amriphylline 0.05gm/5ml syrup 120ml', 'امريفيللين 0.05مجم/5مل شراب 120 مل', '', '6', 'Theophylline sodium glycinate', 'Amriya', 'Syrup', 'شراب', '', 'Bronchodilator', '0.05gm', 'For the treatment of the symptoms and reversible airflow obstruction associated with chronic asthma and other chronic lung diseases, such as emphysema and chronic bronchitis.', '6221075050064', '', 929, '2023-04-26', CURRENT_TIMESTAMP),
(10714, 'Aaa', 'ششش', '', '36', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 667, '2022-10-15', CURRENT_TIMESTAMP),
(1619, 'Normelan lotion for stretch marks 50 ml', 'نورميلان لوشن للاسترتش مارك 50 مل', '', '300', '', 'Green pharmaceutical', 'Lotion', 'لوشن', '', 'Skin care', '50 ml', '', '', '', 844, '2022-09-07', CURRENT_TIMESTAMP),
(19872, 'Globazure 300 mg 10 caps.', 'جلوبازور 300 مجم 10 كبسولات', '', '50', 'Pregabalin', 'Medizen pharmaceutical industries > global health care-egypt', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '300 mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 855, '2022-07-18', CURRENT_TIMESTAMP),
(19875, 'Globexor 75mg 14 caps.', 'جلوبيكسور 75 مجم 14 كبسولة', '', '48', 'Venlafaxine', 'Global napi pharmaceuticals', 'Cap', 'كبسولة', '', 'Psychiatric.antidepressants', '75mg', 'Venlafaxine is indicated for the management of major depressive disorder (MDD), generalized anxiety disorder (GAD), social anxiety disorder (SAD), and panic disorder.[L43030]', '', '', 839, '2022-07-15', CURRENT_TIMESTAMP),
(24496, 'Pancuronium bromide 4mg/2ml i.v. amp', 'بانكورونيوم بروميد 4مجم /2مل امبول حقن وريد', '', '6', 'Pancuronium', 'Hospira inc.-uk > pfizer scientific office', 'Amp', 'أمبول', '', 'Nondepolarizing neuromuscular blocker', '4mg', 'Used as a muscle relaxant during anesthesia and surgical procedures.', '', '', 655, '2022-08-03', CURRENT_TIMESTAMP),
(7707, 'Mamy care cream 50 gm', 'مامي كير كريم 50 جرام', '70', '90', 'Panthenol+allantoin+bisabolol+dimethicone+glycerin+almond oil+paraffin oil', 'Sina > health well egypt', 'Cream', 'كريم', '', 'Moisturizing topicals', '50 gm', 'moisturizing cream for nipple fissures', '6224000911102', '', 3368, '2025-08-01', CURRENT_TIMESTAMP),
(1377, 'Omega-3 enriched 40 softgels (adrien gagnon)', 'اوميجا 3 انريتش 40 كبسولة', '', '650', 'Omega-3', 'Egypharma', 'Gel', 'جل', '', 'OMEGA-3', '', 'Provided as daily supplements. Aa preparation of omega-3-acid ethyl esters is licensed in UK for prevention of recurrent events after myocardial infarction in addition to treatment of hypertriglyceridaemia.', '', '', 1114, '2022-09-04', CURRENT_TIMESTAMP),
(32376, 'Alejon oily cleanser 200 ml', 'اليجون اويلي كلينسر 200 مل', '210', '250', 'Salicylic acid+glycolic acid+tea tree oil+ginger extract+thyme extract+willow park extract+hazel extract+niacinamide+allantoin', 'Alejon co.', 'Cleanser', 'منظف', '', 'Skin care', '200 ml', 'Key additive in many skin-care products for the treatment of acne, psoriasis, callouses, corns, keratosis pilaris and warts.', '', '', 554, '2025-06-24', CURRENT_TIMESTAMP),
(17081, 'Dana whitening cream 40 gm', 'دانا كريم للتبييض 40 جم', '', '35', 'Wheat germ oil+rosemary+almond oil+jojoba oil+castor oil+licuorice+bearbery+green tea oil+vitamin c+', 'Leader cosmetics > jmp', 'Cream', 'كريم', '', 'Whitening topical', '40 gm', 'skin lightening cream', '', '', 772, '2022-07-24', CURRENT_TIMESTAMP),
(7599, 'Centravita serine 20 tabs', 'سنترافيتا سيرين 20 قرص', '', '238', '', 'Copad pharma', 'Tab', 'أقراص', '', 'Brain support', '', '', '', '', 646, '2022-08-17', CURRENT_TIMESTAMP),
(17930, 'Ducray keracnyl gel moussant (foaming gel) 200 ml', 'دوكراي كيراكنيل جل للحلاقة 200 مل', '175', '225', '', 'Pierre - fabre france > biotech egypt', 'Gel', 'جل', '', 'Skin care', '200 ml', 'cleansing care for acne-prone skin. this foaming gel enriched with myrtacineï¿½ new generation is soap-free and gently and deeply cleanses and purifies the skin. apply morning and evening to damp skin. lather and rinse thoroughly. avoid contact with the e', '', '', 954, '2023-09-02', CURRENT_TIMESTAMP),
(1773, 'Joviapram 20 mg 30 f.c. tabs.', 'جوفيا برام 20 مجم 30 قرص', '153', '201', 'Escitalopram', 'Sun pharma egypt limited', 'Tab', 'أقراص', '', 'Psychiatric.antidepressants', '20 mg', 'Escitalopram is indicated for the acute and maintenance treatment of major depressive disorder (MDD) in adults and pediatric patients 12 years old and older and for the acute treatment of generalized anxiety disorder (GAD) in adults and pediatric patients 7 years old and older.[L8513,L8513] It is additionally indicated for symptomatic relief of obsessive-compulsive disorder (OCD) in Canada.[L8516]', '', '', 1277, '2025-06-17', CURRENT_TIMESTAMP),
(2153, 'Cataflam 75mg/3ml 6 amp.', 'كتافلام 75مجم/3 مل 6 امبولات', '83', '120', 'Diclofenac potassium', 'Novartis', 'Amp', 'أمبول', 'مسكن آلام - مضاد التهاب - خافض حرارة', 'Analgesic.antipyretic.anti-inflammatory.nsaid.acetic acid derivatives', '75mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6223002641840', '', 7149, '2024-12-22', CURRENT_TIMESTAMP),
(33071, 'La tree beaute whitening cream 60 gm', 'لا تري بيوت كريم تفتيح 60 جم', '97', '150', '', 'Egyptian co. for cosmetics > la tree beaute', 'Cream', 'كريم', 'كريم لتفتيح وتغذية البشرة وازالة الكلف والتصبغات ومحاربة علامات الشيخوخه', 'Skin care.whitening', '60 gm', '', '', '', 5168, '2025-08-03', CURRENT_TIMESTAMP),
(17802, 'Dolphin k 75mg/3ml i.m. 6 amp', 'دولفن كيه 75مجم/3مل 6 امبولات عضل', '33', '48', 'Diclofenac potassium', 'Delta pharma', 'Amp', 'أمبول', '', 'Nsaid.acetic acid derivatives', '75mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6221025014399', '', 1005, '2024-11-21', CURRENT_TIMESTAMP),
(7101, 'Lantus solostar 100 i.u./ml 5 pens', 'لانتوس سولو ستار 100وحدة دولية/مل 5 اقلام', '870', '1,244', 'Insulin glargine', 'Sanofi', 'Pen', 'قلم', '', 'Anti-diabetic.insulin analouge', '', 'Human insulin is indicated to improve glycemic control in adults and pediatric patients with diabetes mellitus.', '3582910013204', '', 28251, '2024-10-16', CURRENT_TIMESTAMP),
(2521, 'Choletimb 10 mg 10 tab.', 'كوليتيمب 10اقراص', '', '14', 'Ezetimibe', 'Marcyrl co.', 'Tab', 'أقراص', '', 'Hypolipidemic agent', '10 mg', 'Ezetimibe is indicated to reduce elevated total-C, LDL-C, Apo B, and non-HDL-C in patients with primary hyperlipidemia, alone or in combination with an HMG-CoA reductase inhibitor (statin).[L11347,L11401,L11404] 
It is also indicated to reduce elevated total-C, LDL-C, Apo B, and non-HDL-C in patients with mixed hyperlipidemia in combination with [fenofibrate], and to reduce elevated total-C and LDL-C in patients with homozygous familial hypercholesterolemia (HoFH) in combination with atorvastatin or simvastatin.[L11347] In combination with [bempedoic acid], ezetimibe is indicated as an adjunct to diet, with or without other lipid-lowering therapies, to reduce LDL-C in adults with primary hyperlipidemia, including heterozygous familial hypercholesterolemia (HeFH).[L12150] 
Ezetimibe may also be used to reduce elevated sitosterol and campesterol in patients with homozygous sitosterolemia (phytosterolemia).[L11347]', '', '', 1260, '2022-09-22', CURRENT_TIMESTAMP),
(12347, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 458, '2022-08-17', CURRENT_TIMESTAMP),
(1383, 'Centropax syrup multivitamins 100 ml', 'سنتروباكس شراب فيتامينات 100 مل', '45', '58', '', 'Paxal pharmaceutical', 'Syrup', 'شراب', '', 'Multivitamin', '100 ml', '', '6224011120135', '', 1367, '2025-08-06', CURRENT_TIMESTAMP),
(1650, 'Vitajar 20 sublingual tabs', 'فيتاجار 20 قرص تحت اللسان', '', '99', 'B9 folic acid+b12+b6', 'Treato pharm', 'Tab', 'أقراص', '', 'Multivitamins', '', '', '', '', 994, '2024-11-25', CURRENT_TIMESTAMP),
(18672, 'Evirinse vag.douche 250 ml', 'افرينز دش مهبلي 250 مل', '', '37', 'Alum+chamomile extract+thymol+menthol+calendula extract+rosemary extract+vitamin c', 'Macro group pharmaceuticals', 'Unknown', 'غير محدد', '', 'Vaginal wash', '250 ml', '*external wash for intimate female care with bio active vitamin system *helps in restoring healthy vaginal moisturization & natural physiological vaginal ph *contains natural antimicrobial cooling refreshing & soothing ingredients use: 1-2 provided measur', '6224000437619', '', 687, '2022-12-05', CURRENT_TIMESTAMP),
(28118, 'Thiapril 20/12.5mg 20 tab.', 'ثيابريل 20/12.5مجم 20 اقراص', '', '14', 'Enalapril+hydrochlorothiazide', 'Unipharma co.', 'Tab', 'أقراص', '', 'Antihypertensive.combined ace with diuretic', '12.5mg', 'interactions for enalapril antacids: decrease effeciency of captopril. indomethacin: reduces hypotensive effect. digoxin: increases plasma digoxin levels. potassium preparations & potassium sparing diuretics: hyperkalaemia and increased risk of renal fail', '', '', 806, '2022-07-20', CURRENT_TIMESTAMP),
(10951, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 804, '2022-08-23', CURRENT_TIMESTAMP),
