Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '6221025023438', '', 20543, '2023-08-26', CURRENT_TIMESTAMP),
(10662, 'Aaa', 'ششش', '', '20', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 651, '2022-08-16', CURRENT_TIMESTAMP),
(22058, 'Zymaslim 30 caps', 'زيماسليم 30 كبسولة', '255', '360', 'Chromium+green coffee extract+garcinia cambogia extract', 'Zyma pharma', 'Cap', 'كبسولة', '', 'Support weight management', '', '', '6224011768016', '', 1882, '2025-08-23', CURRENT_TIMESTAMP),
(22368, 'Aaa', 'ششش', '', '21', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 727, '2022-09-28', CURRENT_TIMESTAMP),
(25945, 'Reto plus soap 75 gm', 'ريتو بلس صابون 75جم', '', '18', 'Peppermint oil+almond oil+vitamin a+lavender oil+menthol', 'Macro group pharmaceuticals', 'Soap', 'صابون', '', 'Soap', '75 gm', 'Indicated for the over-the-counter use for:
-the symptomatic relief of minor spasms of the gastrointestinal tract, flatulence and abdominal pain, especially in patients with irritable bowel syndrome.
-the temporary relief of itching associated with insect bites, eczema, minor burn, sunburn, minor skin irritations, minor cuts, scrapes, atopic dermatitis and other skin disorders.
-the temporary symptomatic relief of mild joint and muscle pain as a local topical analgesic.
-the temporary relief of tension-type headache.', '', '', 676, '2022-08-02', CURRENT_TIMESTAMP),
(13983, 'Whitnino 30 ml oral drops', 'وايتينو نقط فم 30 مل', '', '59', 'Iron ( ferrous bisglycinate ) - vit. c - folic acid - vit. b12', '2m whites pharma', 'Drops', 'نقط', '', 'Multivitamin', '30 ml', 'For treatment of patients with documented iron deficiency in whom oral administration is unsatisfactory or impossible. Also used to replenish body iron stores in Non-Dialysis Dependent-Chronic Kidney Disease (NDD-CKD) patients receiving or not receiving erythropoietin and in Hemodialysis Dependent (HDD-CKD) and Peritoneal Dialysis Dependent (PDD-CKD) - Chronic Kidney Disease patients receiving an erythropoietin.', '', '', 1135, '2022-09-06', CURRENT_TIMESTAMP),
(21948, 'Litomen 50mg 10 f.c. tab.', 'ليتومين 50 مجم 10 اقراص', '', '8', 'Miglitol', 'Sigma > hochster pharmaceutical industries', 'Tab', 'أقراص', '', 'Alpha-glucosidase inhibitor', '50mg', 'For use as an adjunct to diet to improve glycemic control in patients with non-insulin-dependent diabetes mellitus (NIDDM) whose hyperglycemia cannot be managed with diet alone.', '', '', 399, '2022-08-06', CURRENT_TIMESTAMP),
(19478, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 789, '2022-06-17', CURRENT_TIMESTAMP),
(14214, 'Anthelios xl spf 50+ cream comfort 50 ml', 'انثيليوس اكس ال 50 بي بي كريم كومفرت 50 مل', '', '325', 'Sun protection formula', 'La roche-posay > united company for trading & distribution', 'Cream', 'كريم', '', 'Sun block', '50 ml', 'properties sensitive skin. also suitable for sun intolerant skin. extreme sunshine intensity. optimal uvb spf 50+ protection and uva protection twice stricter than the european recommendation (for suncare) thanks to its patented and photostable filtering', '', '', 699, '2022-07-22', CURRENT_TIMESTAMP),
(27628, 'Sulfax plus massage gel 120 gm', 'سولفاكس بلس مساج جل 120 جرام', '125', '170', 'Eucalyptus oil+menthol+camphor oil+cetyl myristoleate', 'Egyptian company for cosmetics > parkville pharmaceuticals', 'Gel', 'جل', 'مسكن مضاد التهاب المفاصل والعظام والروماتيزم', 'Massage.topical analgesic.muscle', '120 gm', 'As an active agent, eucalyptus oil has been indicated for relief of the symptoms of catarrhal colds, and/or the relief of the symptoms of minor muscular sprains and cramps [L1857].', '6224008073529', '', 12750, '2025-08-16', CURRENT_TIMESTAMP),
(7713, 'Aquanova- pro-beauty facial cleanser gel', 'اكوانوفا برو بيوتي منظف للوجه جل', '', '250', 'Salicylic acid+vitamin c+kojic acid+niacinamide+tea tree oil+shea butter', 'Sfida pharmaceutical company', 'Gel', 'جل', '', 'Facial cleanser gel', '', 'Key additive in many skin-care products for the treatment of acne, psoriasis, callouses, corns, keratosis pilaris and warts.', '', '', 705, '2025-10-16', CURRENT_TIMESTAMP),
(25751, 'Reboss massage cream 50 gm', 'ريبوز مساج كريم 60 جرام', '50', '60', 'Camphor+menthol+methyl salicylate+eucalyptus', 'Hi-care > novex', 'Cream', 'كريم', '', 'Massage cream', '50 gm', 'reboss massage provide powerful pain reliefing effect. massage slowly on affected area 2-3 times daily.', '', '', 1196, '2025-06-18', CURRENT_TIMESTAMP),
(14571, 'Atozet 10/10mg 30 f.c. tab', 'اتوزيت 10/10مجم 30 قرص', '510', '666', 'Atorvastatin+ezetimibe', 'Merck sharp & dohme', 'Tab', 'أقراص', 'خافض للكوليسترول وللدهون في الدم', 'Antihyperlipidemic.cholesterol absorption inhibitors.combined with statin', '10mg', '', '', '', 2809, '2024-11-10', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(18973, 'Ferosalic 24 caps.', 'فيروساليك 20 كبسولة', '', '45', 'Ferrous fumarate+vitamins(b1+b2+b6+b12+c+e)+zinc+folic acid', 'Egyptian pharmaceutical center > united group pharmaceutical-egypt', 'Cap', 'كبسولة', '', 'Iron supplement', '', 'Ferrous sulfate is used for the prevention and treatment of iron deficiency anemia in adults and children.[A190804,L2240,L11800]', '', '', 924, '2022-12-04', CURRENT_TIMESTAMP),
(16512, 'Clincin 1% top. soln. 60 ml', 'كلينسين 1%محلول 60 مل', '', '21', 'Clindamycin', 'El nile.', 'Sol', 'محلول', '', 'Antibiotic.lincomycins', '1%', 'In oral and parenteral formulations, clindamycin is indicated for the treatment of serious infections caused by susceptible anaerobic bacteria, as well as susceptible staphylococci, streptococci, and pneumococci.[L11599,L11602] Used topically, it is indicated for the treatment of acne vulgaris[L11593,L11611,L11605] and is available in combination with [benzoyl peroxide][L11584] or [tretinoin][L11590] for this purpose, or as a triple combination therapy with benzoyl peroxide and [adapalene].[L48666] Clindamycin is also indicated as a vaginal cream[L11596], suppository[L11608], or gel[L39416] for the treatment of bacterial vaginosis in non-pregnant females.
Clindamycin is used for antimicrobial prophylaxis against _Viridans_ group streptococcal infections in susceptible patients undergoing oral, dental, or upper respiratory surgery, and may be used for prophylaxis against bacterial endocarditis in penicillin-allergic patients at high risk of these infections.[L11629]', '6221077082612', '', 847, '2022-07-14', CURRENT_TIMESTAMP),
(28654, 'Ulstop 20mg 14 caps.', 'الستوب 20مجم 14 كبسول', '', '42', 'Omeprazole', 'Pharco', 'Cap', 'كبسولة', '', 'Peptic ulcer.proton pump inhibitor', '20mg', 'Omeprazole, according to the FDA label [FDA label] is a proton pump inhibitor (PPI) used for the following purposes:
• Treatment of active duodenal ulcer in adults 
• Eradication of Helicobacter pylori to reduce the risk of duodenal ulcer
recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6221151001614', '', 760, '2023-01-12', CURRENT_TIMESTAMP),
(21926, 'Liptomil plus ar milk 400 gm', 'ليبتوميل بلس اي ار حليب 400 جرام', '', '119', 'Anti-regurgitation milk formula', 'Hochdorf nutricare co. > liptis', 'Unknown', 'غير محدد', '', 'Milk products.anti-regurgitation milk', '400 gm', '', '610644981414', '', 1100, '2022-07-31', CURRENT_TIMESTAMP),
(19693, 'Genotropin 4 i.u.vial', 'جينوتروبين 4 وحدة دولية فيال', '', '110', 'Somatropin', 'Pfizer', 'Vial', 'فيال', '', 'Human growth hormone', '', '', '', '', 4291, '2022-05-08', CURRENT_TIMESTAMP),
(31739, 'Amlosazide 5/25/40 mg 30 f.c. tabs.', 'املوسازيد 5/25/40مجم 30 قرص', '90', '123', 'Amlodipine+olmesartan+hydrochlorothiazide', 'Atco pharma', 'Tab', 'أقراص', '', 'Anti-hypertensive.combined angiotensin blocker & ca++ channel blocker & diuretic', '40 mg', 'pharmacology olmesartan: blocks the vasoconstrictor and aldosterone-secreting effects of angiotensin ii. amlodipine: directly acts on vascular smooth muscle to produce peripheral arterial vasodilation reducing peripheral vascular resistance and blood pres', '6223004041556', '', 757, '2024-10-09', CURRENT_TIMESTAMP),
(6858, 'Kerella lotion 30 ml', 'كيريلا لوشن 30 مل', '21.5', '31', 'Betamethasone+salicylic acid', 'Global napi pharmaceuticals', 'Lotion', 'لوشن', 'محلول مرطب وملطف للبشرة يستخدم فى علاج الصدفية والاكزيما والقشرة والحد من التورم والاحمرار والحكة', 'Corticosteroid with keratolytic', '30 ml', 'kerella is a combination of betamethasone dipropionate & salicylic acid. betamethasone dipropionate a synthetic corticosteroid has anti-inflammatory antipruritic & vasoconstrictive actions. topical salicylic acid has keratolytic properties as well as bact', '6223002144525', '', 11046, '2024-08-27', CURRENT_TIMESTAMP),
(6467, 'Infectomycin 500mg 6 f.c. tabs.', 'انفكتوميسين 500مجم 6 اقراص', '70.5', '97', 'Azithromycin', 'Egpi > ranbaxy', 'Tab', 'أقراص', 'مضاد حيوي', 'Antibiotic.macrolide', '500mg', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
