b) the Canadian product monograph specifically indicates sildenafil for the treatment of primary pulmonary arterial hypertension (PPH) or pulmonary hypertension secondary to connective tissue disease (CTD) in adult patients with WHO functional class II or III who have not responded to conventional therapy [F3859]. In addition, improvement in exercise ability and delay in clinical worsening was demonstrated in adult patients who were already stabilized on background epoprostenol therapy [F3859]; and
c) the EMA product information specifically indicates sildenafil for the treatment of adult patients with pulmonary arterial hypertension classified as WHO functional class II and III, to improve exercise capacity [F3883]. Efficacy has been shown in primary pulmonary hypertension and pulmonary hypertension associated with connective tissue disease [F3883]. The EMA label also indicates sildenafil for the treatment of pediatric patients aged 1 year to 17 years old with pulmonary arterial hypertension [F3883]. Efficacy in terms of improvement of exercise capacity or pulmonary hemodynamics has been shown in primary pulmonary hypertension and pulmonary hypertension associated with congenital heart disease [F3883].', '', '', 3152, '2024-12-06', CURRENT_TIMESTAMP),
(4733, 'Sanotact brewers yeast+zinc 60 tabs', 'سانوتاكت خميرة البيرة + الزنك 60 قرص', '', '420', '', 'Sanotact gmbh', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '', '', 888, '2025-06-19', CURRENT_TIMESTAMP),
(8230, 'Xioglia 15 sachet', 'زيوجليا 15 كيس', '405', '480', 'Cdp+inulin+biotin+pantothenate+zn bisglycinate', 'Xiotec', 'Sachet', 'أكياس', '', 'Brain nootropic', '', '', '0745314273497', '', 1568, '2025-06-15', CURRENT_TIMESTAMP),
(21707, 'Lepticure 100 mg 20 caps.', 'ليبتيكيور 100مجم 20 كبسولة', '22', '32', 'Gabapentin', 'Pharopharma', 'Cap', 'كبسولة', 'علاج الصرع -- تقليل التشنجات التي تنتج من الصرع', 'Anti-epileptic.gaba analogs', '100 mg', 'In the United States, gabapentin is officially indicated for the treatment of postherpetic neuralgia in adults and for the adjunctive treatment of partial-onset seizures, with or without secondary generalization, in patients 3 years of age and older.[L8717] In Europe, gabapentin is indicated for adjunctive therapy in the treatment of partial-onset seizures, with or without secondary generalization, in patients 6 years of age and older and as monotherapy in patients 12 years of age and older. It is also used in adults for the treatment of various types of peripheral neuropathic pain, such as painful diabetic neuropathy.[L8732]', '', '', 1586, '2025-01-17', CURRENT_TIMESTAMP),
(13577, 'Ageal eye contour cream 15 ml', 'اجيل كريم للهالات حول محيط العين 15 مل', '382', '440', '', 'Egyptian company for cosmetics > hayah lab.', 'Cream', 'كريم', '', 'Eye contour', '15 ml', 'reduce under eye puffiness', '', '', 1106, '2025-04-06', CURRENT_TIMESTAMP),
(23174, 'Aaa', 'ششش', '', '40', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 852, '2023-05-19', CURRENT_TIMESTAMP),
(18460, 'Aaa', 'ششش', '', '378', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 712, '2022-07-27', CURRENT_TIMESTAMP),
(33773, 'Tolak hair lotion', 'تولاك لوشن للشعر', '185', '135', '', 'Rosa cosmetics', 'Lotion', 'لوشن', '', 'Hair care', '', 'supports healthy hair growth for fuller longer health hair nutrient rich', '', '', 660, '2025-06-20', CURRENT_TIMESTAMP),
(26067, 'Ribovinal 200 mg 21 strips x 8 caps.', 'ريبوفينال 200مجم 21 شريط في 8 كبسول', '', '252', 'Ribavirin', 'Mash premiere', 'Cap', 'كبسولة', '', 'Anti-viral.nucleoside', '200 mg', 'Indicated for the treatment of chronic Hepatitis C virus (HCV) infection in combination with other antiviral agents with the intent to cure or achieve a sustained virologic response (SVR). Typically added to improve SVR and reduce relapse rates [A19644].
The addition of ribavirin in Technivie therapy indicated for treating HCV genotype 1a and 4 infections is recommended in patients with or without cirrhosis. 
Resistance: viral genetic determinants resulting in variable response to ribavirin therapy has not been yet determined.', '', '', 970, '2022-07-25', CURRENT_TIMESTAMP),
(27209, 'Sodium lactate 1.85% (mottahedoon) i.v. inf. 500 ml', 'صوديوم لاكتات 1.85% المتحدون محلول وريدي 500 مل', '', '6', 'Sodium lactate', 'Al mottahedoon pharma', 'Unknown', 'غير محدد', '', 'Sterile solution', '1.85%', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 740, '2022-07-14', CURRENT_TIMESTAMP),
(17428, 'Dexaprof 25mg 20 f.c. tabs.', 'ديكسابروف 25 مجم 20 قرص', '', '16', 'Dexketoprofen', 'Novartis', 'Tab', 'أقراص', '', 'Nsaid.propionic acid derivatives', '25mg', 'For short-term treatment of mild to moderate pain, including dysmenorrhoea, musculoskeletal pain and toothache [L1302].', '', '', 1007, '2022-07-14', CURRENT_TIMESTAMP),
(28010, 'Tendaseef 20 caps.', 'تينداسيف 20 كبسولة', '', '16', 'Devil s claw root', 'Safe pharma', 'Cap', 'كبسولة', '', 'Analgesic', '', 'devil s claw is also known as harpagophytum procumbens grapple plant and wood spider. devil s claw has been used most commonly for rheumatism arthritis gout muscle pain and other degenerative disorders of the musculoskeletal system.', '', '', 760, '2022-06-22', CURRENT_TIMESTAMP),
(21271, 'Keepaco plus whitening cream 40 gm', 'كيباكو بلس كريم تفتيح 40 جرام', '155', '175', 'B3 (niacinamide)', 'Healthy group for cosmetics > keepaco pharm', 'Cream', 'كريم', 'كريم تفتيح يستخدم لعلاج الكلف والتصبغات وتوحيد لون البشرة', 'Whitening topical', '40 gm', 'anti-brown marks and whitening cream', '', '', 6746, '2025-07-07', CURRENT_TIMESTAMP),
(18355, 'Epcifam 20mg 10 orally disentigrating tabs.', 'ابسيفام 20 مجم 10 اقراص', '', '7', 'Famotidine', 'Epci', 'Tab', 'أقراص', '', 'Peptic ulcer.anti-histamine.h2 antagonist', '20mg', 'Famotidine is indicated in pediatric and adult patients (with the bodyweight of 40 kg and above) for the management of active duodenal ulcer (DU), active gastric ulcer, symptomatic non-erosive gastroesophageal reflux disease (GERD), and erosive esophagitis due to GERD, diagnosed by biopsy.[L11139]
It is also indicated in adult patients for the treatment of pathological hypersecretory conditions (e.g., Zollinger-Ellison Syndrome, multiple endocrine neoplasias) and reduction of the risk of DU recurrence.[L11139]
The intravenous formulation of famotidine is available for some hospitalized patients with pathological hypersecretory conditions or intractable ulcers or as an alternative to the oral dosage form for short-term use in patients who are unable to take oral medication.[L11142]
Over-the-counter famotidine is used for the management and prevention of heartburn caused by gastroesophageal reflux in children and adults. Off-label uses of famotidine include the reduction of NSAIDs-associated gastrointestinal effects, treatment of refractory urticarial, prevention of stress ulcer in critically-ill patients, and symptomatic relief of gastritis.[L11166,L11172]', '', '', 946, '2022-07-29', CURRENT_TIMESTAMP),
(4010, 'Effegad 75 mg 30 e.r. caps.', 'ايفيجاد 75مجم 30 كبسولة', '', '90', 'Venlafaxine', 'Epci', 'Cap', 'كبسولة', 'مضاد اكتئاب - علاج أمراض نفسية', 'Psychiatric.antidepressant', '75 mg', 'Venlafaxine is indicated for the management of major depressive disorder (MDD), generalized anxiety disorder (GAD), social anxiety disorder (SAD), and panic disorder.[L43030]', '', '', 3072, '2022-11-10', CURRENT_TIMESTAMP),
(10549, 'Aaa', 'ششش', '', '85', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 695, '2023-04-28', CURRENT_TIMESTAMP),
(9605, 'Pantogar 60 caps', 'بانتوجار 60 كبسولة', '', '243', 'Calcium pantothenate+keratin+l-cystine+para-aminobenzoic acid+vitamin b1+yeast', 'Marcyrl co. > merz', 'Cap', 'كبسولة', 'لعلاج مشاكل الشعر والاظافر', 'Hair care', '', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '6223003573843', '', 9803, '2023-05-14', CURRENT_TIMESTAMP),
(8952, 'Aaa', 'ششش', '', '35', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 784, '2022-10-28', CURRENT_TIMESTAMP),
(27855, 'Tada 20 mg 2 tabs', 'تادا 20مجم 2 قرص', '', '50', 'Tadalafil', 'Unipharma co. > novell pharma', 'Tab', 'أقراص', 'مقوي للرجال', 'Tonic for men', '20 mg', 'Tadalafil is indicated for the treatment of erectile dysfunction (ED) and either alone or in combination with [finasteride] for the treatment of benign prostatic hypertrophy (BPH).[L39095,L39439] It is also indicated for the treatment of pulmonary arterial hypertension (PAH) both alone and in combination with [macitentan] or other endothelin-1 antagonists.[L39100,L39105,L50622]', '', '', 4827, '2023-04-25', CURRENT_TIMESTAMP),
(29599, 'Vortiocyrl 5 mg 14 f.c. tabs.', 'فورتيوسيرل 5مجم 14 اقراص', '', '69', 'Vortioxetine', 'Marcyrl co.', 'Tab', 'أقراص', 'مضاد للإكتئاب -- الأمراض النفسية', 'Psychiatric.antidepressants', '5 mg', 'Vortioxetine is indicated for the treatment of major depressive disorder (MDD).', '', '', 1542, '2022-05-26', CURRENT_TIMESTAMP),
(24179, 'Optiray 350mg/ml i.v. 12 vial 100 ml', 'اوبتيراي 350مجم/مل 12 امبول 100مل', '', '2,722', 'Ioversol', 'Mallinckrodt inc. > ghalioungui trading', 'Vial', 'فيال', '', 'Radiographic procedures.contrast agent', '350mg', 'As the product Optiray 300, the intra-arterial use of ioversol is indicated for cerebral arteriography and peripheral arteriography in adults, while its intravenous use is indicated for CT imaging of the head and body, venography, and intravenous excretory urography in adults.[L41780]
As the product Optiray 320, the intra-arterial use of ioversol is indicated for cerebral arteriography, peripheral arteriography, visceral and renal arteriography, aortography, coronary arteriography, and left ventriculography in adults, and angiocardiography in pediatic patients.[L41780] The intravenous use of this product is indicated for CT imaging of the head and body, venography, and intravenous excretory urography in adults and CT imaging of the head and body, and intravenous excretory urography in pediatric patients.[L41780]
As the product Optiray 350, the intra-arterial use of ioversol is indicated for peripheral arteriography coronary arteriography, and left ventriculography in adults, and angiocardiography in pediatic patients.[L41780] The intravenous use of this product is indicated for CT imaging of the head and body, venography, intravenous excretory urography, and intravenous digital subtraction angiography (IV-DSA) in adults and CT imaging of the head and body, and intravenous excretory urography in pediatric patients.[L41780]', '', '', 857, '2022-07-25', CURRENT_TIMESTAMP),
(4132, 'Haireka hair lotion 200ml', 'هيريكا هير لوشن 200مل', '249', '299', 'Haireka shampoo No sulphates, No parabens,No synthetic dyes Comosed of; - Caffeine -saw palmetto -rosemary - Aloe Vera - biotin -vitamin c -keratin -jojoba -lavender -olive oil - almond oil - thyme - panthenol -a powerful management for telegen effluvium & androgenetic alopecia -powerfully stimulates scalp circulation and stimulates hair growth -elongating the anagen phase in hair follicles -stimulates production in hair. *Indicated in: -hair falling -weak and damaged hair -hair shaft abnormalities (split ends) -dry hair and treated with chmical (dyes) -post hair transplantation *Suitable for dry and oily scalp', '', 'Lotion', 'لوشن', 'هيريكا لوشن مغذي للشعر ويستخدم لعلاج التساقط وزيادة كثافة الشعر', 'Nourishing hair lotion & reduce hair falling', '200ml', '', '', '', 1147, '2025-10-21', CURRENT_TIMESTAMP),
(14181, 'Aaa', 'ششش', '', '10', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 756, '2022-09-06', CURRENT_TIMESTAMP),
(16154, 'Cerebrodil 20mg 10 tab.', 'سيريبروديل 20 مجم 10 قرص', '', '3', 'Piribedil', 'Alfacure pharmaceuticals', 'Tab', 'أقراص', 'علاج مساعد لمرض باركنسون. اضطرابات الدورة الدموية ونقص التروية. الدوخة والدوار', 'Anti-ischemic', '20mg', 'about piribedil a piperazine derivative dopamine agonist antiparkinsonism antidyskinetic. mechanism of action of piribedil the exact mechanism of action is not known. a lesion in the nigra striatum may be responsible for parkinson`s disease which results', '', '', 913, '2022-07-09', CURRENT_TIMESTAMP),
(28690, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 761, '2022-11-30', CURRENT_TIMESTAMP),
(15240, 'Bioblas shampoo & conditioner for weak & damaged hair 200ml', 'بيوبلاس شامبو وبلسم للشعر الضعيف والتالف 200 مل', '', '98', '', 'Ego pharmaceuticals pty ltd. > vamer pharma', 'Amp', 'أمبول', '', 'Hair care', '200ml', '2*1 soap free effective against periodic and acute hair loss bioblas anti-hair loss shampoo adds body shine and volume to hair specially designed for dry damaged and dyed hair.', '', '', 492, '2022-08-05', CURRENT_TIMESTAMP),
(20059, 'Gravity cream 50 gm', 'جرافيتي كريم 50 جم', '', '75', '', 'Italian comsetics company > medico company', 'Cream', 'كريم', '', 'Whitening topical', '50 gm', '** whitening cream for face & sensitive area & dark spots. with licorice extract. ** ingredients: licorice extract + glycolic acid + citric acid + bees wax + zinc oxide + titanium dioxide + stearic acid + allantoin + triethanolamine + cetyl stearyl alcoho', '6224008461111', '', 715, '2022-08-05', CURRENT_TIMESTAMP),
(28751, 'Unirivastigmine 6 mg 10 caps.', 'يونيريفاستجمين 6مجم 10 كبسول', '', '30', 'Rivastigmine', 'Unipharma co.', 'Cap', 'كبسولة', '', 'Anticholinesterase', '6 mg', 'For the treatment of mild to moderate dementia associated with Parkinson''s disease or of the Alzheimer''s type.', '', '', 637, '2022-07-27', CURRENT_TIMESTAMP),
(20411, 'Hercul whitening cream 60 gm', 'هيركول كريم تبييض 60 جم', '', '75', 'Alpha arbutin+licorice ext+vit c+liquid paraffin+glycerin+diemthicone+titanium dioxide+octyl methoxy', 'Leader for cosmetics > junier pharma', 'Cream', 'كريم', '', 'Whitening topical', '60 gm', '** ingredients: alpha arbutin + licorice (liquorice) ext. + vitamin c + liquid paraffin + glycerin + diemthicone + titanium dioxide + octyl methoxycinnamate + beeswax + perfume ** directions of use: apply a thin layer of cream on dark area(s) at evening a', '', '', 650, '2022-08-03', CURRENT_TIMESTAMP),
(26683, 'Romamag 30 film coated tablets', 'روماماج 30 قرص', '98', '125', 'Elemental calcium 800 mg+elemental magnesium 250 mg+vitamin d3 100 i.u+zinc 10 mg+boron 0.6 mg+manganese 0.5 mg+copper 500 mcg+selenium 55 mcg', 'Sejo pharma', 'Tablet', 'أقراص', '', 'Multivitamin', '', '', '', '', 825, '2025-07-26', CURRENT_TIMESTAMP),
(7456, 'Livoprotec 140mg 10 sachet', 'ليفوبروتيك 140 مجم 10 اكياس', '', '9', 'Silymarin', 'Pharopharma', 'Sachet', 'أكياس', '', 'Liver support supplements', '140mg', '', '6221094050717', '', 1274, '2022-12-06', CURRENT_TIMESTAMP),
(27038, 'Sinemet cr 50/200mg 30 tab.(n/a)', 'سينميت سي ار 50/200مجم 30 قرص', '', '87', 'Carbidopa+levodopa', 'Merck sharp & dohme > merck sharp & dohme scientific office', 'Tab', 'أقراص', '', 'Parkinson s disease.dopamine agonist', '200mg', '', '', '', 1102, '2023-02-16', CURRENT_TIMESTAMP),
(4464, 'Panthenol-october 2% cream 30 gm', 'بانثينول 2% كريم 30 جم', '', '40', 'Panthenol', 'October pharma', 'Cream', 'كريم', '', 'Skin care.moisturizing', '2%', 'Panthenol (containing a racemic mixture of dexpanthenol and levopanthenol) is not currently available in any FDA-approved products and therefore does not have an indication.
Please see [DB09357] for FDA-approved uses of the dextrorotatory form of Panthenol.', '', '', 786, '2025-06-17', CURRENT_TIMESTAMP),
(24289, 'Oro.guard oral spray 60 ml', 'اورو.جارد سبراي للفم 60مل', '65', '79', 'Hyaluronic acid+licorice extract+clove oil', 'Hi-care > linkopharm', 'Spray', 'بخاخ', 'سبراى معقم وملطف للفم ويدعم صحة اللثة والوقاية من التسوس والروائح الكريهة والالتهابات', 'Dental sprays', '60 ml', 'The intra-articular preparations of hyaluronic acid are indicated for knee pain associated with osteoarthritis.[L32228] Hyaluronic acid is used in cosmetic applications to prevent and reduce the appearance of wrinkles on the face, and as a dermal filler to correct facial imperfections or other imperfections on other parts of the body.[L32208,L32223] It is frequently an ingredient in topical applications for wound healing and symptomatic treatment of skin irritation from various causes.[L32198] Hyaluronic acid may also be indicated in ophthalmological preparations or oral capsules to treat discomfort caused by dry eyes or conjunctivitis and for its protective qualities during and before eye surgery.[A230128,L32213] Finally, hyaluronic acid can be used off-label to coat the bladder for relief of interstitial cystitis symptoms.[A230533]', '6224008585640', '', 2154, '2025-10-08', CURRENT_TIMESTAMP),
(12272, 'Viavag 25 mg 10 f.c. tabs.', 'فيافاج 25مجم 10 اقراص', '', '35', 'Sildenafil', 'Hi-pharm', 'Tab', 'أقراص', 'مقوي للرجال', 'Tonic for men', '25 mg', 'Sildenafil is a phosphodiesterase-5 (PDE5) inhibitor that is predominantly employed for two primary indications:
(1) the treatment of erectile dysfunction [A175582, L5611, F3853, F3856, F3886]; and
(2) treatment of pulmonary hypertension, where:
a) the US FDA specifically indicates sildenafil for the treatment of pulmonary arterial hypertension (PAH) (WHO Group I) in adults to improve exercise ability and delay clinical worsening [F3850]. The delay in clinical worsening was demonstrated when sildenafil was added to background epoprostenol therapy [F3850]. Studies establishing effectiveness were short-term (12 to 16 weeks), and included predominately patients with New York Heart Association (NYHA) Functional Class II-III symptoms and idiopathic etiology (71%) or associated with connective tissue disease (CTD) (25%) [F3850];
b) the Canadian product monograph specifically indicates sildenafil for the treatment of primary pulmonary arterial hypertension (PPH) or pulmonary hypertension secondary to connective tissue disease (CTD) in adult patients with WHO functional class II or III who have not responded to conventional therapy [F3859]. In addition, improvement in exercise ability and delay in clinical worsening was demonstrated in adult patients who were already stabilized on background epoprostenol therapy [F3859]; and
c) the EMA product information specifically indicates sildenafil for the treatment of adult patients with pulmonary arterial hypertension classified as WHO functional class II and III, to improve exercise capacity [F3883]. Efficacy has been shown in primary pulmonary hypertension and pulmonary hypertension associated with connective tissue disease [F3883]. The EMA label also indicates sildenafil for the treatment of pediatric patients aged 1 year to 17 years old with pulmonary arterial hypertension [F3883]. Efficacy in terms of improvement of exercise capacity or pulmonary hemodynamics has been shown in primary pulmonary hypertension and pulmonary hypertension associated with congenital heart disease [F3883].', '6224001050510', '', 2133, '2023-06-03', CURRENT_TIMESTAMP),
(19508, 'Molnupiravir-eva 200mg 40 caps', 'مولنوبيرافير ايفا 200مجم 40 كبسولة', '420', '461', 'Molnupiravir', 'Eva pharma', 'Cap', 'كبسولة', 'مضاد فيروسات', 'Antiviral', '200mg', '[N4-hydroxycytidine] and its prodrug molnupiravir are being studied for its activity against a number of viral infections including influenza, MERS-CoV, and SARS-CoV-2.[A193014, A193029]
