(14157, 'Angikinase 100 000 i.u. vial', 'انجيكيناز 100000 وحدة دولية فيال', '', '180', 'Urokinase', 'Sedico', 'Vial', 'فيال', '', 'Thrombolytic agent', '', 'In Canada, urokinase is indicated for lysis of acute massive pulmonary emboli, acute thrombi obstructing coronary arteries, occlusive thromboemboli in peripheral arteries and grafts, and restoration of patency to intravenous catheters.[L12141]', '', '', 930, '2022-07-12', CURRENT_TIMESTAMP),
(31913, 'Incan-d advance 30 tabs.', 'انكان-دي ادفانس 30 قرص', '99', '156', 'Cholecalciferol(vitamin d3)+boron', 'Copad egypt > incandesce', 'Tab', 'أقراص', 'مكمل غذائى يستخدم لدعم النمو الطبيعي للعظام ومنع الكساح ولين العظام', 'Vitamin d', '', 'description derivative of 7-dehydroxycholesterol formed by ultraviolet rays breaking of the c9-c10 bond. it differs from ergocalciferol in having a single bond between c22 and c23 and lacking a methyl group at c24 indication for the treatment of vitamin d', '', '', 1101, '2025-07-15', CURRENT_TIMESTAMP),
(8160, 'Midodrine 1% oral drops 10ml', 'ميدودرين 1% نقط فم 10 مل', '51.5', '67', 'Midodrine', 'El nile.', 'Drops', 'نقط', '', 'Alpha1-agonist', '1%', 'For the treatment of symptomatic orthostatic hypotension (OH).', '6221077062317', '', 2407, '2024-11-09', CURRENT_TIMESTAMP),
(14471, 'Delacol oral drops 15 ml', 'ديلاكول نقط فم 15 مل', '', '50', '', 'Copad egypt', 'Drops', 'نقط', '', '', '15 ml', '', '', '', 1105, '2024-07-15', CURRENT_TIMESTAMP),
(12862, 'Zincorhea 20 mg syrup 80 ml', 'زنكوريا 20مجم شراب', '', '16', 'Zinc', 'Pharco', 'Syrup', 'شراب', 'مكمل غذائي -- مصدر للزنك --مقوي للمناعة -- مصدر للطاقة', 'Zinc supplement', '20 mg', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '6221151002260', '', 2264, '2022-12-15', CURRENT_TIMESTAMP),
(8225, 'Miopan plus 100ml susp.', 'ميوبان بلس 100 مل معلق للحموضة', '6', '15', 'Magaldrate', 'Pharco', 'Susp', 'معلق', 'حالات الحموضة وحرقان المعدة وفي حالات الانتفاخ وعسر الهضم و في حالات ارتجاع المريء', 'Antacid', '100ml', 'about magaldrate chemical complex of aluminum and magnesium hydroxides antacid. mechanism of action of magaldrate this neutralizes the gastric acid and increases the gastric ph. this reduces the direct acid irritant effect. it also enhances mucosal barrie', '6223000013830', '', 2518, '2023-08-30', CURRENT_TIMESTAMP),
(17715, 'Gasiflatyl 30 chewable tab', 'جاسيفلاتيل 30 قرص مضغ', '33', '54', 'Simethicone', 'Misr > valeant pharmaceuticals', 'Tab', 'أقراص', 'علاج الانتفاخ والشعور بالامتلاء.', 'Antiflatulent', '', 'Simethicone is indicated for the treatment of bloating, pressure, and cramps caused by gas.[L31533] Simethicone is also used as part of bowel preparation for colonoscopies.[A228343]', '6221035009125', '', 6127, '2025-02-28', CURRENT_TIMESTAMP),
(1074, 'Gioia hilltop panthenol 50gm cream', 'جيويا هيلتوب بانثينول كريم 50 جم', '', '45', 'Panthenol', 'Hilltop for medical supplies', 'Cream', 'كريم', '', 'Moisturiser skin emollient', '50gm', 'Panthenol (containing a racemic mixture of dexpanthenol and levopanthenol) is not currently available in any FDA-approved products and therefore does not have an indication.
Please see [DB09357] for FDA-approved uses of the dextrorotatory form of Panthenol.', '', '', 1100, '2022-10-16', CURRENT_TIMESTAMP),
(23621, 'Nitazode 500mg 18 f.c. tabs.', 'نيتازود 500مجم 18 قرص', '64.5', '99', 'Nitazoxanide', 'Andalous pharma', 'Tab', 'أقراص', 'علاج الديدان', 'Antihelminthic', '500mg', 'For the treatment of diarrhea in adults and children caused by the protozoa <i>Giardia lamblia</i>,  and for the treatment of diarrhea in children caused by the protozoan,  <i>Cryptosporidium parvum</i> [FDA label].
Nitazoxanide has not been shown to be superior to placebo medication for the management of diarrhea caused by Cryptosporidium parvum in patients with HIV/immunodeficiency [FDA label, A31973, A31976].', '6223004690495', '', 6231, '2025-08-11', CURRENT_TIMESTAMP),
(20343, 'Hepa-merz granulate 3 gm 6 granules in sachets', 'هيبا-ميرز 3جم 6 اكياس', '', '45', 'L-ornithine-l-aspartate', 'Pharco > merz', 'Sachet', 'أكياس', '', 'Liver support supplements', '3 gm', '', '6221151001928', '', 1043, '2023-04-27', CURRENT_TIMESTAMP),
(17281, 'Depiwhite advanced cream 40 ml', 'ديبي وايت كريم 40 مل', '399', '549', '', 'Acm dermatological laboratories > biotech egypt', 'Cream', 'كريم', '', 'Whitening topical', '40 ml', 'indications depiwhite advanced depigmenting cream has been specially designed to: - fade or eliminate brown spots and limit their reappearance. - even out the complexion. properties depiwhite advanced combines 4 high-performance depigmenting active ingred', '', '', 896, '2025-08-11', CURRENT_TIMESTAMP),
(18856, 'Fastel 180mg 10 f.c. tab.', 'فاستل 180 مجم 10 اقراص', '', '42', 'Fexofenadine', 'European egyptian pharm. ind.', 'Tab', 'أقراص', '', 'Antihistamine.antiallergy', '180mg', 'In the United States, fexofenadine is indicated for the symptomatic treatment of allergic rhinitis in patients ≥2 years old and chronic idiopathic urticaria in patients ≥6 months old.[L4269] In Canada, fexofenadine carries the same indications but is approved only for patients ≥12 years old.[L10779] Fexofenadine is also available in combination with [pseudoephedrine] for the symptomatic treatment of season allergic rhinitis in patients ≥12 years old.[L10800]', '6221076011040', '', 1567, '2022-12-05', CURRENT_TIMESTAMP),
(7466, 'Sp mix powder 200 gm', 'اس بي ميكس باودر 200 جم', '', '205', '', '', 'Powder', 'بودرة', '', '', '200 gm', '', '', '', 851, '2025-09-21', CURRENT_TIMESTAMP),
(17613, 'Dicloferaz 75mg/3ml 6 amp. i.m i.v inf.', 'ديكلوفيراز 75 مجم / 3 مل 6 امبول وريد', '13.5', '66', 'Diclofenac sodium', 'Jedco int. co. for pharmaceuticals > elrazy pharmaceuticals-egypt', 'Amp', 'أمبول', '', 'Nsaid.acetic acid derivatives', '75mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '', '', 1064, '2024-12-18', CURRENT_TIMESTAMP),
(21646, 'Laverin cream 50 gm', 'لافرين كريم 50 جرام', '35.9', '135', 'Aloe vera+wheat germ oil+vitamin a+mineral oil', 'Leader cosmetics > imaginex egypt co.', 'Cream', 'كريم', 'للعناية بالجلد', 'Skin care', '50 gm', 'Indicated for use as a topical agent to soothe sensitive skin and to relieve symptoms of various skin conditions, including contact or atopic dermatitis, eczema, dermatitis and acne urticata, first- and second-degree burns, radiation dermatitis, and sunburn.', '', '', 1138, '2025-04-13', CURRENT_TIMESTAMP),
(28719, 'Unibisol 10 mg 30 f.c. tab.', 'يونيبيسول 10مجم 30 قرص', '21', '84', 'Bisoprolol fumarate', 'Unipharma co.', 'Tab', 'أقراص', '', 'Antihypertensive.beta blocker.selective b1', '10 mg', 'Bisoprolol is indicated for the treatment of mild to moderate hypertension.[L7219] It may be used off-label to treat heart failure, atrial fibrillation, and angina pectoris.[A180460,A180463]', '', '', 1008, '2025-06-10', CURRENT_TIMESTAMP),
(7931, 'Ovioral 20 tabs', 'اوفيورال 20 قرص', '', '250', 'Inositol+chromium+folate', 'Inf nil', 'Tab', 'أقراص', '', 'Food supplement', '', '', '', '', 812, '2022-08-16', CURRENT_TIMESTAMP),
(11681, 'Aaa', 'ششش', '', '46', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 706, '2022-08-05', CURRENT_TIMESTAMP),
(21938, 'Lisitens 12.5/20mg 30 tab.', 'ليسيتنس 20/12.5مجم 20قرص', '56.25', '80', 'Hydrochlorothiazide+lisinopril', 'Hi-pharm', 'Tab', 'أقراص', '', 'Antihypertensive.combined ace with diuretic', '20mg', 'warning: this drug can cause serious (possibly fatal) harm to an unborn baby if used during pregnancy. therefore it is important to prevent pregnancy while taking this medication. uses: this medication is used to treat high blood pressure (hypertension).', '6224001050640', '', 1812, '2023-10-22', CURRENT_TIMESTAMP),
(4500, 'Prontogest 50mg/ml 10 i.m. amp', 'برونتوجيست 50 مجم/مل 10 امبولات', '', '170', 'Progesterone', 'Marcyrl pharmaceutical industries (mpi)', 'Amp', 'أمبول', '', 'Progesterone supplement', '50mg', '**Gelatinized capsules**
The gelatinized capsules are indicated for use in the prevention of endometrial hyperplasia in non-hysterectomized postmenopausal women who are receiving conjugated estrogens tablets. They are also indicated for use in secondary amenorrhea [FDA label]. 
**Vaginal gel**
Progesterone gel (8%) is indicated as progesterone supplementation or replacement as part of an Assisted Reproductive Technology (“ART”) treatment for infertile women with progesterone deficiency.  The lower concentration progesterone gel (4%) is used in the treatment of secondary amenorrhea, with the use of the 8% concentration if there is no therapeutic response to the 4% gel [F3898].
**Vaginal insert**
This form is indicated to support embryo implantation and early pregnancy by supplementation of corpus luteal function as part of an Assisted Reproductive Technology (ART) treatment program for infertile women [F3901].
**Injection (intramuscular)**
This drug is indicated in amenorrhea and abnormal uterine bleeding due to hormonal imbalance in the absence of organic pathology, such as submucous fibroids or uterine cancer [F3907]. 
**Tablets, contraceptive**
The tablet form of progesterone in contraceptive formulations is indicated for the prevention of pregnancy [F3904].', '6223003573805', '', 532, '2025-06-17', CURRENT_TIMESTAMP),
(25025, 'Polaprim eye drops 10 ml', 'بولابريم قطرة للعين 10مل', '', '5', 'Polymyxin+trimethoprim', 'Alfacure pharmaceuticals', 'Drops', 'نقط', '', 'Antibiotic', '10 ml', 'about polymyxin b basic polypeptide(polymyxin)antibiotic antibiotic. mechanism of action of polymyxin b polymixin b is a member of poly peptide antibiotic. being poly peptide they exert a detergent like effect. they have high affinity for phospholipids. p', '', '', 627, '2022-08-04', CURRENT_TIMESTAMP),
(28464, 'Triaminic chest congestion syrup 100ml', 'تريامينك شراب 100مل', '', '9', 'Guaifenesin+pseudoephedrine', 'Novartis > glaxo smithkline', 'Syrup', 'شراب', '', 'Cold drugs', '100ml', 'indication used to assist the expectoration of phlegm from the airways in acute respiratory tract infections. mechanism of action guaifenesin may act as an irritant to gastric vagal receptors and recruit efferent parasympathetic reflexes that cause glandu', '6223002642212', '', 879, '2022-07-08', CURRENT_TIMESTAMP),
(16538, 'Cliosone cream 15 gm', 'كليوزون 15جرام كريم', '', '7', 'Betamethasone+clioquinol', 'Pharopharma', 'Cream', 'كريم', '', 'Antifungal with glucocorticoid', '15 gm', 'this cream and ointment are used in short courses to treat inflammatory skin conditions such as those listed below when milder corticosteroids have not been effective and when the condition is either already infected or likely to become infected. eczema o', '6221094113016', '', 884, '2022-12-04', CURRENT_TIMESTAMP),
(22736, 'Aaa', 'ششش', '', '9', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 708, '2023-04-28', CURRENT_TIMESTAMP),
(24185, 'Optivisc 90mg / 3ml prefilled syringe', 'اوبتيفيسك 90مجم/3مل سرنجة للحقن بالمفصل', '', '6,000', 'Sodium hyaluronate', 'Ivy sports medicine > international pionneers', 'Syringe', 'حقنة', 'مسكن مضاد التهاب المفاصل', 'Analgesic anti-inflammatory.tissue lubricant', '90mg', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 5652, '2023-02-04', CURRENT_TIMESTAMP),
(20319, 'Allmed d3 infant oral spray 21 ml', 'اولميد د3 سبراي بالفم رضع 21 مل', '', '250', 'Vitamin d', 'Allmed ltd', 'Spray', 'بخاخ', 'مضاد للتورم', 'Vitamin d', '21 ml', 'Vitamin D is indicated for use in the treatment of hypoparathyroidism, refractory rickets (also known as vitamin D resistant rickets), and familial hypophosphatemia [FDA Label].', '', '', 833, '2022-08-15', CURRENT_TIMESTAMP),
(13802, 'Almitat 0.05% cream 15 gm', 'الميتات 0.05% كريم 15 جم', '', '6', 'Alclometasone', 'Uniswab > roxcel egypt', 'Cream', 'كريم', '', 'Glucocorticoid', '0.05%', 'For the relief of the inflammatory and pruritic manifestations of corticosteroid-responsive dermatoses.', '', '', 601, '2022-07-21', CURRENT_TIMESTAMP),
(29826, 'Zallanz 15mg 30 delayed rel. caps.', 'زالاناز 150مجم ممتد المفعول 30 كبسولة', '', '62', 'Lansoprazole', 'El-obour', 'Cap', 'كبسولة', '', 'Peptic ulcer.proton pump inhibitor', '15mg', 'Lansoprazole is used to reduce gastric acid secretion and is approved for short term treatment of active gastric ulcers, active duodenal ulcers, erosive reflux oesophagitis, symptomatic gastroesophageal reflux disease, and non-steroidal anti-inflammatory drug (NSAID) induced gastric and duodenal ulcers. [A4892][A177065][FDA Label]  It may be used in the maintenance and healing of several gastric conditions including duodenal ulcers, NSAID related gastric ulcers, and erosive esophagitis.[FDA Label] Lansoprazole prevents recurrence of gastric ulcers in patients who have a documented history of gastric ulcers who also use NSAIDs chronically. [FDA Label]  Predictably, it is also useful in the management of hypersecretory conditions including Zollinger-Ellison syndrome. [FDA Label]  Lansoprazole is effective at eradicating H. pylori when used in conjunction with amoxicillin and clarithromycin (triple therapy) or with amoxicillin alone (dual therapy). [FDA Label]', '6230046001974', '', 833, '2022-07-07', CURRENT_TIMESTAMP),
(7646, 'Maalox plus (lemon flavoured) oral susp. 250 ml', 'مالوكس بلس نكهة ليمون معلق 250 مل', '100', '143', 'Aluminium hydroxide+magnesium hydroxide+simethicone', 'Sanofi', 'Susp', 'معلق', 'الحموضة - حرقان الصدر', 'Antacid', '250 ml', 'mechanism of action aluminum hydroxide: neutralizes stomach hydrocloride to form alcl3 salt plus water; increases gastric ph magnesium hydroxide: promotes bowel evacuation by causing osmotic retention of fluid which causes the colon to distend with increa', '3582910089704', '', 10284, '2025-09-01', CURRENT_TIMESTAMP),
(26994, 'Simethicone 80mg 30 tab', 'سايميثيكون 80مجم 30 قرص', '', '6', 'Simethicone', 'Amoun > pyramids for trading pharmaceuticals-egypt', 'Tab', 'أقراص', 'مضاد للانتفاخ -- لعلاج حالات الانتفاخ ومغص القولون -- لتخفيف الشعور بالامتلاء وغازات البطن', 'Antiflatulent', '80mg', 'Simethicone is indicated for the treatment of bloating, pressure, and cramps caused by gas.[L31533] Simethicone is also used as part of bowel preparation for colonoscopies.[A228343]', '6221025008152', '', 5006, '2022-12-08', CURRENT_TIMESTAMP),
(22782, 'Minidiab 5mg 30 tab.', 'مينيدياب 5مجم 30اقراص', '', '17', 'Glipizide', 'Cid > pfizer', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.sulfonylurea', '5mg', 'Indicated as an adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus.[label]', '6221043060026', '', 877, '2022-12-06', CURRENT_TIMESTAMP),
(27968, 'Teddy go 30 gummies', 'تيدي جو 30 جوميز', '', '65', 'Vitamin(a+e+b12+c)+calcium+phosphorus+iodine+magnesium+zinc+folic acid', 'Copad pharma', 'Unknown', 'غير محدد', '', 'Multivitamins', '', '', '', '', 757, '2022-08-04', CURRENT_TIMESTAMP),
(16162, 'Cerederm plaster 10*20cm 10 patches', 'سيريديرم 10 * 20 سم 10 لصقات', '', '1,000', 'Reinforced siloxanes', 'Cereplas > biosource', 'Patch', 'لصقة', '', 'Scar therapy', '', 'indications / uses treatment & prevention of hypertrophic & keloid scars. contraindications hypersensitivity. open or infected wounds bedsores; weeping or ulcerated wounds burns & mucous membranes.', '', '', 917, '2022-07-14', CURRENT_TIMESTAMP),
(24684, 'Pentamol 1gm/100ml i.v. inf. vial', 'بنتامول 1جم/100مل محلول للحقن الوريدي', '46.5', '67', 'Paracetamol(acetaminophen)', 'Global pharmaceutical industries > penta pharma-egypt', 'Vial', 'فيال', 'محلول خافض للحرارة -- مسكن عام للالام -- مضاد للالتهابات', 'Antipyretic', '1gm', '', '6224007738245', '', 3863, '2024-12-04', CURRENT_TIMESTAMP),
(8267, 'Nervoric 600 mg 20 tabs', 'نيرفوريك 600 مجم 20 قرص', '', '280', 'Alpha-lipoic acid+benfotiamine+vitamin b6+folic acid+vitamin b12', 'Tetracare limited', 'Tab', 'أقراص', '', 'Multivitamin', '600 mg', '', '', '', 761, '2025-12-07', CURRENT_TIMESTAMP),
(33929, 'Zemylaise 200 ceip unit/ml syrup 120 ml', 'زيمايلاز 200وحدة/مل شراب 120 مل', '49.75', '60', 'Alpha amylase', 'Drug pharma egypt', 'Syrup', 'شراب', 'مضاد للالتهابات', 'Anti-inflammatory enzymes', '120 ml', '', '', '', 1835, '2024-06-11', CURRENT_TIMESTAMP),
(24762, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 670, '2022-07-24', CURRENT_TIMESTAMP),
(27103, 'Smile lotion 120 ml', 'سمايل لوشن 120 ملي', '', '10', 'Zinc oxide+menthol+camphor+red iron oxide', 'H.c.p co. > phoenix-egypt', 'Lotion', 'لوشن', '', 'Soothing topical', '120 ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '6225000027411', '', 662, '2022-12-08', CURRENT_TIMESTAMP),
(19794, 'Ginseng syrup 120 ml', 'جنسنج شراب 120 مل', '', '5', 'Ginseng', 'Pharco', 'Syrup', 'شراب', 'مقوي عام', 'General tonic', '120 ml', 'about ginseng steroid glycosides. mechanism of action of ginseng it contains chemicals called ginsenosides that seem to affect insulin levels in the body and lower blood sugar. other chemicals called polysaccharides might affect the immune system. indicat', '6221151001041', '', 1037, '2022-12-05', CURRENT_TIMESTAMP),
