(6538, 'Snomatica 20 capsules', 'سنوماتيكا 20 كبسولة', '', '200', 'Glutathione+collagen', 'Helian', 'Capsule', 'كبسولة', '', 'Antioxidant.support skin health', '', '', '', '', 1183, '2024-07-18', CURRENT_TIMESTAMP),
(13806, 'Aloe vera weiser 5 hair ampoules 10 ml', 'الوفيرا 5 امبولات للشعر 10 مل لتقوية الشعر', '30', '50', 'Aloe vera extract', 'Weiser', 'Ampoule', 'أمبول', '', 'Hair care', '10 ml', 'Indicated for use as a topical agent to soothe sensitive skin and to relieve symptoms of various skin conditions, including contact or atopic dermatitis, eczema, dermatitis and acne urticata, first- and second-degree burns, radiation dermatitis, and sunburn.', '', '', 787, '2024-05-17', CURRENT_TIMESTAMP),
(10672, 'Solu-cortef 100mg/2ml vial', 'سوليوكورتيف 100مجم/2مل فيال', '', '16', 'Hydrocortisone sodium succinate', 'Eipico > pfizer', 'Vial', 'فيال', '', 'Glucocorticoid', '100mg', 'Otic solutions are indicated for infections of the external auditory canal caused by susceptible organisms and with inflammation.[L10529,L10532] Hydrocortisone tablets are indicated for certain endocrine, rheumatic, collagen, allergic, ophthalmic, respiratory, hematologic, neoplastic, edematous, gastrointestinal, and other conditions.[L10535] A hydrocortisone enema is indicated for ulcerative colitis,[L10538] a topical ointment with antibiotics is indicated for corticosteroid responsive dermatoses with infections,[L7772] and a topical cream with [acyclovir] is indicated to treat cold sores.[L7321] Oral granules of hydrocortisone are used as a replacement therapy for Adrenocortical Insufficiency (AI) in children under 17 years of age.[L16533]', '6221032311931', '', 3463, '2023-04-25', CURRENT_TIMESTAMP),
(24877, 'Phenytin 50mg 50 caps.', 'فينيتين 50مجم 50 كبسولة', '16', '29', 'Phenytoin', 'El nile.', 'Cap', 'كبسولة', 'علاج الصرع -- يقلل التشننجات الناتجة عن الصرع', 'Anti-epileptic.hydantoin', '50mg', 'Phenytoin is indicated to treat grand mal seizures, complex partial seizures, and to prevent and treat seizures during or following neurosurgery.[L9362] Injectable phenytoin and [Fosphenytoin], which is the phosphate ester prodrug formulation of phenytoin[A188571], are indicated to treat tonic-clonic status epilepticus, and for the prevention and treatment of seizures occurring during neurosurgery.[L10740]', '6221077033416', '', 1317, '2024-12-19', CURRENT_TIMESTAMP),
(23178, 'Mylotarg 500mg/100ml vial for i.v. inf.', 'ميلوتارج 500مجم /100مل فيال وريد', '', '35', 'Levofloxacin', 'Grand pharma > vodachem pharmaceuticals', 'Vial', 'فيال', '', 'Antibiotic.quinolone', '500mg', 'In oral and intravenous formulations, levofloxacin is indicated in adults for the treatment of various infections caused by susceptible bacteria, including infections of the upper respiratory tract, lower respiratory tract, skin, skin structures, urinary tract, and prostate.[L11638,L11692] The oral formulation is also indicated in both adults and children 6 months of age and older for the post-exposure management of inhalational anthrax caused by _Bacillus anthracis_ and for the treatment and/or prophylaxis of plague caused by _Yersinia pestis_.[L11638]
In its ophthalmic formulation, levofloxacin is indicated for the treatment of bacterial conjunctivitis caused by susceptible organisms.[L11641] An inhalational solution available in Canada is indicated for the management of cystic fibrosis patients aged 18 years or older with chronic pulmonary _Pseudomonas aeruginosa_ infections.[L11689]', '', '', 1043, '2022-07-08', CURRENT_TIMESTAMP),
(20282, 'Healthpoint nappy cream 100 gm', 'هيلث بوينت نابي كريم 100 جم', '', '70', 'Water+zinc oxide+liquid paraffin+lanolin+cetearyl alcohol+glyceryl stearate+benzyl alcohol+peg-100 s', 'Healthpoint ltd. > paxton', 'Cream', 'كريم', 'علاج التهابات الحفاضات', 'Diaper rash', '100 gm', 'composition: water + zinc oxide + liquid paraffin + lanolin + cetearyl alcohol + glyceryl stearate + benzyl alcohol + peg-100 stearate + phenoxyethanol + hydroxyl ethyl cellulose + parfum + ethylhexylglycerin', '', '', 685, '2022-08-17', CURRENT_TIMESTAMP),
(25187, 'Preparation g.t.n cream 30 gm (twin pack)', 'بريبيراشن كريم 30جم', '', '60', 'Glyceryl trinitrate', 'E.h.o co. > top tec international', 'Cream', 'كريم', '', 'Haemorrhoids', '30 gm', '-prompt soothing relief from painful buming itching and discomfort. -shrinks swollen hemorrhoidal tissue. -protects irritated tissue. -relieves internal and external discomfort.', '', '', 975, '2022-07-16', CURRENT_TIMESTAMP),
(25167, 'Pregavalex 25 mg 30 caps.', 'بريجافالكس 25مجم 30 كبسول', '', '70', 'Pregabalin', 'Eva pharma', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '25 mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 1004, '2022-07-15', CURRENT_TIMESTAMP),
(24210, 'Oramax mouth spray 30 ml', 'اوراماكس سبراي للفم 30مل', '55', '60', 'Cocomido propyl betaine+propylene glycol+ethanol+sodium benzoate+clove oil+sage oil+myrrh oil+pepper', 'Leader cosmetics > original pharma group', 'Spray', 'بخاخ', '', 'Oral care', '30 ml', 'for oral cavity care', '6224010525023', '', 1535, '2025-01-18', CURRENT_TIMESTAMP),
(18738, 'Eylea 40mg sol. for intravitreal inj.', 'ايليا 40مجم محلول للحقن بالعين', '8260', '12,250', 'Aflibercept', 'Bayer bitterfeld gmbh-germany > bayer healthcare', 'Inj', 'حقن', '', 'Antineoplastic', '40mg', 'The opthalmic agent is used for the treatment of neovascular (Wet) age-related macular degeneration (AMD), macular edema following retinal vein occlusion (RVO), diabetic macular edema (DME), diabetic retinopathy (DR), and retinopathy of prematurity (ROP).[L45136]
The systemic injection, known as ziv-aflibercept, in combination with 5-fluorouracil, leucovorin, irinotecan-(FOLFIRI), is for the treatment of metastatic colorectal cancer that is resistant to or progressed following treatment with oxaliplatin.[L45141]', '', '', 1239, '2024-03-11', CURRENT_TIMESTAMP),
(9078, 'Aaa', 'ششش', '', '57', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 646, '2022-05-28', CURRENT_TIMESTAMP),
(23561, 'Nice feel cream 30 gm', 'نايس فيل كريم 30 جم', '40', '70', 'Shikonin+dexpanthenol+chlorohexidine+sesame oil+hyaluronic acid+collagen+vitamin e', 'Dreams el habboba > dawa egypt pharma', 'Cream', 'كريم', 'علاج الجروح والتقرحات -- ترطيب وتلطيف الجلد -- تقليل الالتهابات والاحمرار', 'Wound healing cream', '30 gm', 'wound healing cream', '', '', 1849, '2025-08-20', CURRENT_TIMESTAMP),
(32005, 'Marshmallow hair oil 100 ml', 'مارشماللو زيت للشعر 100 مل', '', '130', '', '> marshmallow pharma', 'Hair oil', 'زيت شعر', '', 'Hair care', '100 ml', '', '', '', 616, '2023-03-09', CURRENT_TIMESTAMP),
(20235, 'Aaa', 'ششش', '', '19', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 723, '2022-07-11', CURRENT_TIMESTAMP),
(32563, 'Bloom ville 30 tabs.', 'بلوم فيل 30 قرص', '225', '275', 'Vitamins(c+d3+e+b1+b2+b3+b6+b7+b9+b12)+iron+zinc+selenium+copper+magnesium+manganese+chromium+iodine+marine collagen+coenzyme-q10+grape seed ext.', 'Parkville', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '6224008073949', '', 2334, '2025-10-02', CURRENT_TIMESTAMP),
(19414, 'Friston free hair shampoo 250 ml', 'فريستون فري شامبو للشعر 250 مل', '', '150', 'Biotin+saw palmetto+aloe vera+garlic+ginseng+hydrolyzed keratin+panthenol+niacin', 'Leader cosmetics > ncs pharma', 'Amp', 'أمبول', 'علاج تساقط الشعر', 'Hair care', '250 ml', 'sulphate free. for fine & thinning hair. use: apply twice weekly. indications: -prevent hair fall. -increase hair density. -protect hair from harmful environmental conditions. -controls split ends and hair damage.', '', '', 2124, '2022-06-01', CURRENT_TIMESTAMP),
(23557, 'Liqiveem syrup 120 ml', 'ليكيفيم شراب 120 مل', '35', '50', 'Ivy leaves + licorice + thyme', 'Acs', 'Syrup', 'شراب', 'مكمل غذائى مضاد للسعال ,يخفف اعراض البرد ويدعم الجهاز التنفسي', 'Cough products', '120 ml', '', '', '', 1201, '2025-01-18', CURRENT_TIMESTAMP),
(20685, 'Ibufen 400mg 20 tab.', 'ايبوفين 400مجم 20 قرص', '', '16', 'Ibuprofen', 'Memphis', 'Tab', 'أقراص', '', 'Nsaid.propionic acid derivatives', '400mg', 'Ibuprofen is the most commonly used and prescribed NSAID. It is a very common over-the-counter medication widely used as an analgesic, anti-inflammatory and antipyretic.[A39096]
The use of ibuprofen and its enantiomer [DB09213] in a racemic mix is common for the management of mild to moderate pain related to dysmenorrhea, headache, migraine, postoperative dental pain, spondylitis, osteoarthritis, rheumatoid arthritis, and soft tissue disorder.[A39097]
Due to its activity against prostaglandin and thromboxane synthesis, ibuprofen has been attributed to alteration of platelet function and prolongation of gestation and labour.[A39092]
As ibuprofen is a widely used medication, the main therapeutic indications are:
* Patent Ductus Arteriosus - it is a neonatal condition wherein the ductus arteriosus (blood vessel that connects the main pulmonary artery to the proximal descending aorta) fails to close after birth causing severe risk of heart failure. The prostaglandin inhibition of ibuprofen has been studied for the treatment of this condition as it is known that prostaglandin E2 is responsible for keeping the ductus arteriosus open.[A39100]
* Rheumatoid- and osteo-arthritis - ibuprofen is very commonly used in the symptomatic treatment of inflammatory, musculoskeletal and rheumatic disorders.[A39176]
* Cystic fibrosis - the use of high dosages of ibuprofen has been proven to decrease inflammation and decreasing polymorphonuclear cell influx in the lungs.[A39177]
* Orthostatic hypotension - ibuprofen can induce sodium retention and antagonize the effect of diuretics which has been reported to be beneficial for patients with severe orthostatic hypotension.[A1651]
* Dental pain - ibuprofen is used to manage acute and chronic orofacial pain.[A10901]
* Pain - ibuprofen is widely used to reduce minor aches and pains as well as to reduce fever and manage dysmenorrhea. It is very commonly used for the relief of acute indications such as fever and tension headaches.[A39092] It is also used to manage mild to moderate pain and moderate to severe pain as an adjunct to opioid analgesics.[L40208]
* Investigational uses - efforts have been put into developing ibuprofen for the prophylaxis of Alzheimer''s disease, Parkinson disease, and breast cancer.[A39092]', '', '', 1908, '2023-04-28', CURRENT_TIMESTAMP),
(21288, 'Kemagel silicone gel 30 gm', 'كيماجل سيليكون جل 30 جرام', '985', '1,150', 'Polysiloxane', 'Multipharma', 'Gel', 'جل', 'علاج للندبات', 'Scar therapy', '30 gm', 'kemagelï-silicone is medical grade advanced topical silicone gel used to improve the physiological and cosmetic appearance of the scar. silicone gel has been shown to flatten soften and smooth scars as well as reduce the discoloration associated with scar', '', '', 10445, '2024-10-01', CURRENT_TIMESTAMP),
(29131, 'Ventolin diskus 200mcg/dose accuhaler', 'فنتولين ديسكس 200ميكروجرام / جرعة استنشاق', '32.5', '86', 'Salbutamol', 'Glaxo smithkline', 'Unknown', 'غير محدد', 'موسع للشعب الهوائية -- الحد من التهاب القصبات المزمن -- وقف مشاكل التنفس اثناء النشاطات', 'Bronchodilator', '200mcg', 'about salbutamol beta2-adrenergic agonist phenethylamine derivative bronchodilator(antiasthma) uterine relaxant. mechanism of action of salbutamol salbutamol is a short acting ?2 receptor agonist. it selectively stimulates ?2 receptors present in airway u', '6221045008552', '', 2366, '2023-08-13', CURRENT_TIMESTAMP),
(29026, 'Vasopine 5 mg 30 tabs.', 'فازوباين 5مجم 30 قرص', '', '24', 'Amlodipine', 'Arab drug company (adco)', 'Tab', 'أقراص', 'يستخدم لعلاج الضغط -- علاج الذبحة الصدرية', 'Antihypertensive.selective calcium channel blocker', '5 mg', 'Amlodipine may be used alone or in combination with other antihypertensive and antianginal agents for the treatment of the following conditions [FDA label]:
• Hypertension 
• Coronary artery disease
• Chronic stable angina
• Vasospastic angina (Prinzmetal’s or Variant angina) 
• Angiographically documented coronary artery disease in patients without heart failure or an ejection fraction < 40%', '', '', 5133, '2023-02-03', CURRENT_TIMESTAMP),
(29725, 'Xecamcold 20 caps.', 'زيكامكولد 20 كبسولة', '', '18', 'Guaifenesin+paracetamol(acetaminophen)+phenylepherine', 'Aug pharma', 'Cap', 'كبسولة', 'علاج حالات البرد -- مضاد للحساسية -- مسكن للالام المصاحبة لادوار البرد', 'Cold drugs', '', '', '', '', 1674, '2023-01-06', CURRENT_TIMESTAMP),
(23576, 'Nido-1 plus milk 576 gm', 'نيدو 1 بلس لبن اطفال 576 جم', '299', '310', 'Milk formula stage 3', 'Nestle', 'Unknown', 'غير محدد', '', 'Milk products.third stage (age 1-3 years)', '576 gm', 'not to replace mother s milk. for infants from 1 year age onward. to be used within one month from opening.', '', '', 832, '2025-09-01', CURRENT_TIMESTAMP),
(33872, 'Vitacid c 1000mg 12 eff. gran. in sachets', 'فيتاسيد سي 1000مجم 12 كيس حبيبات فوارة', '16', '54', 'Vitamin c', 'Cid', 'Sachet', 'أكياس', '', 'Vitamin c', '1000mg', 'For the treatment of vitamin A deficiency.', '6221043012513', '', 1679, '2025-08-15', CURRENT_TIMESTAMP),
(18642, 'Eupizar 1 gm i.v. inf. vial', 'يوبيزار 1 جم فيال', '603', '1,027', 'Gemcitabine', 'Hikma specialized pharmaceuticals', 'Vial', 'فيال', 'علاج الاورام السرطانية', 'Antineoplastic', '1 gm', 'Gemcitabine is a chemotherapeutic agent used as monotherapy or in combination with other anticancer agents. 
In combination with [carboplatin], it is indicated for the treatment of advanced ovarian cancer that has relapsed at least 6 months after completion of platinum-based therapy.[L32950]
Gemcitabine in combination with [paclitaxel] is indicated for the first-line treatment of patients with metastatic breast cancer after failure of prior anthracycline-containing adjuvant chemotherapy, unless anthracyclines were clinically contraindicated.[L32950]
In combination with [cisplatin], gemcitabine is indicated for the first-line treatment of patients with inoperable, locally advanced (Stage IIIA or IIIB) or metastatic (Stage IV) non-small cell lung cancer (NSCLC).[L32950] Dual therapy with cisplatin is also used to treat patients with Stage IV (locally advanced or metastatic) transitional cell carcinoma (TCC) of the bladder.[L32955]
Gemcitabine is indicated as first-line treatment for patients with locally advanced (nonresectable Stage II or Stage III) or metastatic (Stage IV) adenocarcinoma of the pancreas. Gemcitabine is indicated for patients previously treated with [fluorouracil].[L32950]', '', '', 1639, '2025-01-21', CURRENT_TIMESTAMP),
(14033, 'Ampicillin sodium 500mg i.m/i.v vial', 'امبيسيلين صوديوم 500 مجم فيال', '', '5', 'Ampicillin', 'Cid', 'Amp', 'أمبول', '', 'Penicillins.monocomponent', '500mg', 'For treatment of infection (Respiratory, GI, UTI and meningitis) due to E. coli, P. mirabilis, enterococci, Shigella, S. typhosa and other Salmonella, nonpenicillinase-producing N. gononhoeae, H. influenzae, staphylococci, streptococci including streptoc', '', '', 768, '2022-07-13', CURRENT_TIMESTAMP),
(18125, 'Egypro 5 mg 30 tablets', 'ايجيبرو 5 مجم 30 قرص', '40.5', '63', 'Bisoprolol fumarate', 'Egpi', 'Tablet', 'أقراص', 'لعلاج ضغط الدم المرتفع', 'Antihypertensive.beta blocker.selective b1', '5 mg', 'Bisoprolol is indicated for the treatment of mild to moderate hypertension.[L7219] It may be used off-label to treat heart failure, atrial fibrillation, and angina pectoris.[A180460,A180463]', '6223003932039', '', 11777, '2025-03-03', CURRENT_TIMESTAMP),
(9654, 'Aaa', 'ششش', '', '27', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 740, '2022-10-27', CURRENT_TIMESTAMP),
(26351, 'Rovitan 14 sachets', 'روفيتان 14 كيس', '', '98', 'Lactoferrin+vitamin c+zinc', 'Globe international pharmaceuticals', 'Sachet', 'أكياس', 'مصدر للحديد -- علاج حالات الانيميا --مصدر للزنك و فيتامين سي -- مقوي للمناعة', 'Iron supplement', '', 'lactoferrin is a bioactive 80-kda iron binding glycoprotein. indication & dosage: **for prophylaxis: 1-6 years: 1 sachet / day for 3-4 weeks. over 6 years: 2 sachet / day for 3-4 weeks. **during infections (upper respiratory diarrhea): 1-6 years: 1 sachet', '6224008365471', '', 3984, '2023-02-04', CURRENT_TIMESTAMP),
