(31207, 'Resource diabetes powder 400 gm', 'ريسورس باودر لمرضى السكر 400 جم', '', '163', 'Nutritive powder formula', 'Nestle', 'Powder', 'بودرة', '', 'Nutritive powder', '400 gm', 'resource diabetic is a nutritionally balanced diet for oral consumption or hyperglycemia. resource diabetic can be used as the sole source of nutrition or as a supplement. it can also be part of a healthy diabetic meal plan. resource diabetic is lactose f', '7613032991852', '', 870, '2022-12-08', CURRENT_TIMESTAMP),
(11631, 'Triactin 2mg/5ml 120ml syrup', 'ترايكتين شراب 120 مل فاتح شهية', '28.5', '42', 'Cyproheptadine', 'Kahira', 'Syrup', 'شراب', 'فاتح شهية ومضاد للحساسية', 'Antihistamine.sedative.first generation', '2mg', 'In the US, prescription cyproheptadine is indicated for the treatment of various allergic symptomatologies - including dermatographia, rhinitis, conjunctivitis, and urticaria - as well as adjunctive therapy in the management of anaphylaxis following treatment with epinephrine.[L32474] In Canada, cyproheptadine is available over-the-counter and is indicated for the treatment of pruritus and for appetite stimulation.[L32519] In Australia, cyproheptadine is additionally indicated for the treatment vascular headaches.[L32479]
Cyproheptadine is also used off-label for the treatment of serotonin syndrome.[A231274]', '6221068404591', '', 11567, '2025-06-15', CURRENT_TIMESTAMP),
(18438, 'Epinos fruit 6 eff. salt sachet', 'ايبينوس فواكه 6 اكياس فوار', '', '4', 'Citric acid+sodium bicarbonte+tartaric acid', 'Eipico', 'Sachet', 'أكياس', '', 'Antacid', '', 'interactions: antacids concurrent use of antacids with citrates may result in systemic alkalosis. concomitant administration of antacids with sodium citrate and sodium bicarbonate may promote the development of calcium stones in patients with uric acid st', '', '', 1010, '2022-07-12', CURRENT_TIMESTAMP),
(18347, 'Entophar 500 mg 5 vag. ovules', 'انتوفار 500 مجم 5 بويضات مهبلية', '4.25', '9', 'Metronidazole', 'Pharopharma', 'Unknown', 'غير محدد', '', 'Antiprotozoal.nitroimidazole', '500 mg', 'Metronidazole is indicated for the treatment of confirmed trichomoniasis caused by Trichomonas vaginalis (except for in the first trimester of pregnancy) and the patient''s sexual partners, bacterial vaginosis,[L7432, L49811] certain types of amebiasis, and various anaerobic infections.[A181057, L49811] The above anaerobic infections may occur on the skin and skin structures, the abdomen, the heart, reproductive organs, central nervous system, and the respiratory system. Some may also be present in the bloodstream in cases of septicemia. Common infections treated by metronidazole are Bacteroides species infections, Clostridium infections, and Fusobacterium infections, as well as Peptococcus and Peptostreptococcus infections.[L3754] Topical formulations of metronidazole are indicated for the treatment of inflammatory lesions of rosacea.[L45166]
It is also used off-label in the treatment of Crohn''s disease, as a prophylactic agent after surgery[A181039], and in the treatment of Helicobacter pylori infection.[A181045] It has also been studied in the prevention of preterm births and to treat periodontal disease.[A1391,A181078]', '6221094503169', '', 1091, '2025-08-12', CURRENT_TIMESTAMP),
(25808, 'Rego hair shampoo 250 ml', 'ريچو هير شامبو 250 ملي', '', '170', 'Dimethicone+emu oil+tea tree oil+sage leaves extract+aloe vera extract+eruca leaves extract+jojoba o', 'Macro group pharmaceuticals', 'Amp', 'أمبول', '', 'Hair care', '250 ml', '*the ideal shampoo that revitalizes tones & repairs hair follicle and scalp that can be used for all types of hair *improves hair moisturization & conditioning effects by its silicon *protects against dandruff by its ph adjustor system citric acid & aloe', '6224000437343', '', 726, '2022-08-01', CURRENT_TIMESTAMP),
(13731, 'Alhydran gel 30ml', 'الهيدران جل 30 مل', '', '449', 'Pure aloe vera gel (aruban aloe barbadensis)+jojoba oil+vitamin e+vitamin c', 'Bap medical bv > elegant care group', 'Gel', 'جل', 'مرطب للبشرة -- مكافحة الحكة والاحمرار', 'Scar therapy', '30ml', 'medical after care for the skin concentrated medical gel-creme for the treatment and the hydration (regulator of the moisture) of the vulnerable skin immediately after wound closure. suitable for the after care of burns. helps to prevent scar formation an', '', '', 987, '2022-05-13', CURRENT_TIMESTAMP),
(16722, 'Condomania 5 mg 30 f.c.tab', 'كوندومانيا 5 مجم 30 قرص', '', '49', 'Memantine', 'Sigma > rameda', 'Tab', 'أقراص', '', 'Dopamine d2 agonist', '5 mg', 'Memantine is used to manage moderate to severe Alzheimer''s dementia [FDA label]. 
A more recent systemic review and meta-analysis [A177106] indicates that memantine is beneficial as a first line drug for the treatment of Alzheimer''s dementia.  Cholinesterase inhibitors may be added to memantine for further beneficial effects on behavioral symptoms and other symptoms of dementia [A177106].', '', '', 769, '2022-07-16', CURRENT_TIMESTAMP),
(24252, 'Aaa', 'ششش', '', '58', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 628, '2022-07-18', CURRENT_TIMESTAMP),
(6910, 'Ketorolin 0.5% eye drops 15 ml', 'كيتورولين 0.5% قطرة عين 15 مل', '', '17', 'Ketorolac tromethamine', 'Pharopharma', 'Drops', 'نقط', '', 'Nsaid.acetic acid derivatives', '0.5%', 'Ketorolac is a Non-steroidal anti-inflammatory drug (NSAID) and has antipyretic, analgesic and anti-inflammatory properties.[A176131]  It is indicated for short term management of acute pain that requires the calibre of pain management offered by opioids.[L3674]  Clinicians may choose to initiate ketorolac to manage post-operative pain, spinal and soft tissue pain, rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, menstrual disorders and headaches among other ailments.[L6520] Regardless of the etiology of pain, patients should use the lowest possible dose, and avoid using ketorolac for an extended period of time (ideally ≤ 5 days).[L3674] A benefit of choosing ketorolac over other analgesics with similar potency is that that there does not appear to be a risk of dependence or tolerance with ketorolac use.[A176131]', '6221094102270', '', 810, '2022-12-06', CURRENT_TIMESTAMP),
(13179, 'Kiara -soft vit c skin 30ml serum', 'كيارا سوفت فيتامين سي سيروم للبشرة 30 مل', '', '250', 'Ascorbic acid+hyaluronic acid+aloe vera leaf extract+tocopherol+caffeine+collagen+niacinamide+ferulic acid+panthenol+argania spinosa kernel oil+lactic acid', 'Eureka beauty foundation', 'Serum', 'سيروم', '', 'Face serum', '30ml', 'Used to treat vitamin C deficiency, scurvy, delayed wound and bone healing, urine acidification, and in general as an antioxidant. It has also been suggested to be an effective antiviral agent.', '', '', 1079, '2024-06-15', CURRENT_TIMESTAMP),
(33217, 'Modern cranberry 30 capsules', 'موديرن كرانبيري 30 كبسولة', '190', '285', 'Cranberry extract+probiotic+vitamin c', 'Modern egypt pharma', 'Capsule', 'كبسولة', '', 'For urinary tract infection', '', '', '', '', 1734, '2025-08-25', CURRENT_TIMESTAMP),
(22712, 'Miconaz 2% powder spray 60 ml', 'ميكوناز سبراي 2% بودرة 60 مل', '29.5', '47', 'Miconazole', 'Mup', 'Spray', 'بخاخ', 'مضاد للفطريات', 'Antifungals.imidazoles', '2%', 'Miconazole is indicated for the local treatment of oropharyngeal candidiasis in adult patients and for the adjunctive treatment of diaper dermatitis complicated by candidiasis in immunocompetent patients aged four weeks and older.[L14021, L14024] Miconazole is available as both a suppository and cream for the treatment of vaginal yeast infections and the relief of associated vulvar itching and irritation.[L14027] Lastly, miconazole cream is effective in treating athlete''s foot (tinea pedis), jock itch (tinea cruris), ringworm infections (tinea corporis),[L14033] pityriasis (formerly tinea) versicolor,[A203633] and cutaneous candidiasis.[A203630]', '6221508240314', '', 1569, '2025-11-12', CURRENT_TIMESTAMP),
(14972, 'Becozyme i.m./i.v. 12 amp', 'بيكوزيم حقن عضل/وريد 12 امبول', '78', '120', 'Vitamin b complex', 'Bayer consumer care seitzerland > bayer healthcare', 'Amp', 'أمبول', 'فيتامين ب المركب لصحة ونشاط الجسم', 'Vitamin b', '', 'For the treatment of vitamin A deficiency.', '8221135002697', '', 19271, '2024-09-06', CURRENT_TIMESTAMP),
(4927, 'Flavicef 100mg/5ml pd. for oral susp. 30ml', 'فلافيسيف 100مجم/5مل معلق 30 مل', '28', '43', 'Cefixime', 'Kahira > rameda', 'Susp', 'معلق', 'مضاد حيوي', 'Antibiotic.cephalosporin.third-generation', '100mg', 'Cefixime is indicated for the treatment of uncomplicated urinary tract infections caused by _Escherichia coli_ and _Proteus mirabilis_, otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_, and _Streptococcus pyogenes_, pharyngitis and tonsillitis caused by _Streptococcus pyogenes_,  acute exacerbations of chronic bronchitis caused by _Streptococcus pneumoniae_ and _Haemophilus influenzae_, and uncomplicated gonorrhea (cervical/urethral) caused by _Neisseria gonorrhoeae_ (penicillinase-and non-penicillinase-producing isolates).[L49293]', '6223003970475', '', 1615, '2024-08-01', CURRENT_TIMESTAMP),
(16243, 'Chitogree 30 caps.', 'شيتو جري 30 كبسولة', '', '54', 'Chitosan+chromium picolinate+green tea leaves', 'Egpi', 'Cap', 'كبسولة', '', 'Weight loss', '', 'during weight loss programs', '6223003932343', '', 1332, '2022-07-08', CURRENT_TIMESTAMP),
(24150, 'Opranate 20/1100mg 10 caps.', 'اوبرانيت 20/1100مجم 10 كبسولات', '26.5', '35', 'Omeprazole+sodium bicarbonate', 'Rameda', 'Cap', 'كبسولة', 'للحموضة وقرحة المعدة', 'Peptic ulcer.proton pump inhibitor', '1100mg', 'about omeprazole proton pump inhibitor substituted benzimidazole anti-secretory antiulcer. mechanism of action of omeprazole omeprazole is a proton pump inhibitor and it is a prodrug. after administration it diffuses in to the parietal cell of the stomach', '', '', 1861, '2024-02-06', CURRENT_TIMESTAMP),
(18577, 'Esroblad 100mg top. gel 30 sachets', 'اسروبلاد 100مجم جل 30 كيس', '', '75', 'Oxybutynin', 'Al esraa pharmaceutical optima', 'Gel', 'جل', '', 'Urinary incontinence.antispasmodics.muscarinic antagonists', '100mg', 'Oxybutynin is indicated for the symptomatic treatment of overactive bladder, which causes urge urinary incontinence and frequency, and urgency.  Oxybutynin may also be used for children aged 6 and above for the symptomatic management of detrusor muscle overactivity which has been found to be related to a neurological condition. Spina bifida is an example of a neurological condition in which oxybutynin may be used to control urinary symptoms.[L8648] On occasion, oxybutynin may be used off-label to relieve bladder spasms associated with ureteral stents or urinary catheters.[T689]', '', '', 858, '2022-06-16', CURRENT_TIMESTAMP),
(2827, 'Tannoderm cream', 'تانودرم كريم', '', '150', 'Tyrosilane honey aloevera', 'Weiser', 'Cream', 'كريم', '', '', '', '', '6223002260829', '', 1135, '2022-09-23', CURRENT_TIMESTAMP),
(24700, 'Pentoxal 100mg/5ml amp.', 'بينتوكسال 10مجم/5مل امبول', '', '5', 'Pentoxifylline', 'Adwia', 'Amp', 'أمبول', '', 'Anti-ischemic', '100mg', 'Pentoxifylline is indicated for the treatment of intermittent claudication in patients with chronic occlusive arterial disease. Pentoxifylline may improve limb function and reduce symptoms but cannot replace other therapies such as surgical bypass or removal of vascular obstructions.[L30300]', '', '', 1135, '2022-07-09', CURRENT_TIMESTAMP),
(28546, 'Tritospot cream 30 gm', 'تريتوسبوت كريم 30 جرام', '45.5', '66', 'Euselx oily+hydrocortisone acetate+hydroquinone+tretinoin', 'Eva pharma', 'Cream', 'كريم', 'تفتيح لون البشرة بسبب آثار حب الشباب.', '', '30 gm', 'about hydroquinone benzenediol derivative depigmenting agent. mechanism of action of hydroquinone hydroquinone decreases the formation of melanin in the skin. it inhibits tyrosinase and other melanin forming enzymes and thus decreases the formation and in', '6223002450787', '', 3290, '2024-08-10', CURRENT_TIMESTAMP),
(32265, 'Aaa', 'ششش', '', '44', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 574, '2023-04-23', CURRENT_TIMESTAMP),
(22359, 'Mastervit syrup 120 ml', 'ماسترفيت شراب 120مل', '', '10', 'Vitamins(a+d3+e+c+b1+b2+b6)+panthenol', 'Dbk pharma > pharmacare', 'Syrup', 'شراب', '', 'Multivitamins', '120 ml', '', '', '', 1161, '2022-07-15', CURRENT_TIMESTAMP),
(11891, 'Unasyn 3 gm i.v./i.m. vial', 'يوناسين 3جرام فيال', '', '43', 'Ampicillin+sulbactam', 'Mup > pfizer', 'Vial', 'فيال', '', 'Penicillins.penicillin with b-lactamase inhibitor', '3 gm', 'other indications & uses beta-lactamase-producing: s. aureus e. coli klebsiella spp p. mirabilis bacteroides fragilis enterobacter spp acinetobacter calcoaceticus systemic adverse reactions systemic reactions reported in less than 1% of the patients were:', '', '', 1027, '2022-07-09', CURRENT_TIMESTAMP),
(15269, 'Biofreeze gel 59 ml', 'بيوفريز جل 59 مل', '215', '265', 'Menthol', 'Performance health inc. > eva pharma', 'Gel', 'جل', 'مسكن لآلام الجسم -- مسكن لالام العظام والعضلات', 'Analgesic', '59 ml', '', '731124100009', '', 10543, '2024-09-13', CURRENT_TIMESTAMP),
(25987, 'Rexsol collagen serum cell renewal anti-aging 50 ml', 'ريكسول كولاجين سيروم مضاد للشيخوخة 50مل', '', '513', '', 'Rexsol usa > global health', 'Sol', 'محلول', '', 'Skin care', '50 ml', 'helps to smooth facial lines wrinkles and most types of scars on the skin by supplementing the collagen under the skin and cells renewal resulting in better toned smoother and younger looking skin. refines skin texture promoting a new radiance. prefect fo', '', '', 728, '2022-08-04', CURRENT_TIMESTAMP),
(10326, 'Septazole forte 800/160mg 20 tab.', 'سيبتازول فورت 20 قرص', '', '18', 'Sulphamethoxazole+trimethoprim', 'Alexandria', 'Tab', 'أقراص', 'مضاد حيوي . أدوية السلفا', 'Antibiotic', '160mg', '', '', '', 2774, '2022-12-08', CURRENT_TIMESTAMP),
(20181, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 782, '2022-12-02', CURRENT_TIMESTAMP),
(17343, 'Aaa', 'ششش', '', '3', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 904, '2022-08-28', CURRENT_TIMESTAMP),
(7237, 'Levanox n 20 caps.', 'ليفانوكس ان 20 كبسولة', '70', '130', 'Lecithin+catechu+turmeric+milk thistle+dandelion', 'Hochster pharmaceutical industries', 'Cap', 'كبسولة', 'مدعم ومنشط لخلايا الكبد', 'Liver support supplements', '', '', '6224007751435', '', 6710, '2024-03-02', CURRENT_TIMESTAMP),
(28739, 'Unimer ped. hypertonic 18% nasal spray 100ml', 'يونيمير للاطفال 18% سبراي 100مل', '', '85', 'Hypertonic seawater', 'Ldpsa > walfarm pharmaceuticals', 'Spray', 'بخاخ', '', 'Nasal decongestant', '18%', '*it s pediatric 18% hypertonic. *it s for effective nasal hygiene and removal of mucosity by exerting a natural osmotic effect', '3700650172016', '', 887, '2022-12-14', CURRENT_TIMESTAMP),
(31873, 'Atrakta aqua facial cleanser 200 ml', 'اتراكتا اكوا منظف للوجه 200 مل', '210', '240', '', 'Ce.is.co srl > macro group pharmaceuticals', 'Cleanser', 'منظف', '', 'Skin care', '200 ml', '', '', '', 724, '2025-03-03', CURRENT_TIMESTAMP),
(12699, 'Femapent 2.5 mg 30 f.c.tabs.', 'فيمابنت 2.5مجم 30 قرص', '495', '591', 'Letrozole', 'Penta pharma', 'Tab', 'أقراص', '', 'Non-steroidal aromatase inhibitor', '2.5 mg', 'Letrozole is indicated to treat postmenopausal women with hormone receptor (HR) positive early breast cancer, postmenopausal women with early breast cancer who have periviously been treated with tamoxifen, and postmenopausal women with HR+ or unknown advanced breast cancer.[L11623] Letrozole, given with ribociclib, is indicated to treat pre, peri, and postmenopausal women with HR+ and human epidermal growth factor 2 (HER2) negative advanced or metastatic breast cancer.[L11626]', '6224007738214', '', 1504, '2025-07-20', CURRENT_TIMESTAMP),
(19707, 'Genove pilo-peptan anti hair-loss lotion 125ml', 'جينوفي بيلوبيبتان لوشن مضاد لتساقط الشعر 125 مل', '', '259', 'Pygeum africanum vital hair & scal complex hamamelis extract camomille extract ginseng extract', 'Laboratorio genove s.a. >', 'Lotion', 'لوشن', '', 'Hair care', '125ml', 'pilopeptan anti hair-loss lotion helps preventing hair loss by stimulating the anagen or growing phase of hair increasing local microcirculation and activating hair follicles. pilopeptan hair-loss lotion strengthens hair and slows the progression of hair', '', '', 631, '2022-08-03', CURRENT_TIMESTAMP),
(5813, 'Gyno-daktarin 400mg 3 vaginal ovules', 'جينودكتارين 400 مجم مهبلي 3 بويضات مهبلية', '', '25', 'Miconazole', 'Mina pharm > janssen cilag', 'Unknown', 'غير محدد', 'كبسولات مهبلية للقضاء علي الفطريات -- تقليل الالتهابات المهبلية -- تقليل الاحمرار والحكة', 'Antifungals.imidazoles', '400mg', 'Miconazole is indicated for the local treatment of oropharyngeal candidiasis in adult patients and for the adjunctive treatment of diaper dermatitis complicated by candidiasis in immunocompetent patients aged four weeks and older.[L14021, L14024] Miconazole is available as both a suppository and cream for the treatment of vaginal yeast infections and the relief of associated vulvar itching and irritation.[L14027] Lastly, miconazole cream is effective in treating athlete''s foot (tinea pedis), jock itch (tinea cruris), ringworm infections (tinea corporis),[L14033] pityriasis (formerly tinea) versicolor,[A203633] and cutaneous candidiasis.[A203630]', '6222003700525', '', 2650, '2023-01-03', CURRENT_TIMESTAMP),
(24376, 'Aaa', 'ششش', '', '1,600', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 688, '2022-07-22', CURRENT_TIMESTAMP),
(22039, 'Lorin-d 10 caps', 'لورين-دي 10 كبسولات', '', '5', 'Loratadine+pseudoephedrine', 'Eva pharma', 'Cap', 'كبسولة', 'مضاد للحساسية', 'Antihistamine.antiallergy.combined with vasoconstrictor agent', '', '', '', '', 1503, '2022-03-26', CURRENT_TIMESTAMP),
(15767, 'Candistan 2% vaginal cream 20 gm', 'كانديستان 2% كريم مهبلي 20 جم', '', '18', 'Clotrimazole', 'Arab drug company.', 'Cream', 'كريم', '', 'Antifungals.imidazoles', '2%', '**Topical preparations**
Clotrimazole topical cream is indicated for the topical treatment of the following dermal infections [F3088], [F3121]:
Tinea pedis, tinea cruris, and tinea corporis due to _Trichophyton rubrum_, _Trichophyton mentagrophytes_, _Epidermophyton floccosum_
Candidiasis due to _Candida albicans_
Tinea versicolor due to _Malassezia furfur_
Diaper rash infected by _Candida albicans_
In some preparations, clotrimazole may be combined with betamethasone dipropionate, a corticosteroid [F3121]. 
**Oral preparations**
The oral troche preparation is indicated for the local treatment of oropharyngeal candidiasis [FDA label].  It is also indicated as a prophylactic drug to reduce the incidence of oropharyngeal candidiasis in patients immunocompromised by conditions such as chemotherapy, radiotherapy, or steroid therapy utilized in the treatment of leukemia, solid tumors, or renal transplantation [FDA label]. Troche preparations are not indicated for the treatment of any systemic mycoses [FDA label].', '6221060001538', '', 960, '2022-12-03', CURRENT_TIMESTAMP),
(24111, 'Ondalenz 4 mg 5 orodispersible films', 'اوندالينز 4مجم 5 افلام فموية', '112.5', '160', 'Ondansetron', 'Nerhadou international co.', 'Film', 'فيلم', 'مضاد للقيء والترجيع', 'Antiemetic', '4 mg', 'In the adult patient population:
i) orally administered ondansetron tablets and orally disintegrating tablets (ODT) are indicated for:
