(9472, 'Serioprazole 40 mg 20 caps.', 'سريوبرازول 40 مجم 20 كبسولة', '116', '154', 'Esomeprazole', 'SERIO PHARM-EGYPT', 'Cap', 'كبسولة', 'علاج قرحة المعدة علاج اعراض ارتجاع المرىء و علاج الهيلكوباكتر بيلورى.', 'Peptic ulcer.proton pump inhibitor', '40 mg', 'Esomeprazole is indicated for the treatment of acid-reflux disorders including healing and maintenance of erosive esophagitis, and symptomatic gastroesophageal reflux disease (GERD), peptic ulcer disease, H. pylori eradication, prevention of gastrointestinal bleeds with NSAID use, and for the long-term treatment of pathological hypersecretory conditions including Zollinger-Ellison Syndrome.', '6225000092167', '', 6885, '2025-04-22', CURRENT_TIMESTAMP),
(8885, 'Nit clean 500mg 5*6 f.c. tabs.', 'نت كلين 500مجم 5*6 اقراص', '120', '180', 'Nitazoxanide', 'Western pharmaceuticals industries', 'Tab', 'أقراص', 'مضاد للطفيليات', 'Antihelminthic', '500mg', 'For the treatment of diarrhea in adults and children caused by the protozoa <i>Giardia lamblia</i>,  and for the treatment of diarrhea in children caused by the protozoan,  <i>Cryptosporidium parvum</i> [FDA label].
Nitazoxanide has not been shown to be superior to placebo medication for the management of diarrhea caused by Cryptosporidium parvum in patients with HIV/immunodeficiency [FDA label, A31973, A31976].', '', '', 2518, '2024-12-01', CURRENT_TIMESTAMP),
(7942, 'Carmelafer syrup 120 ml', 'كارميلافير شراب 120 مل', '', '110', 'Iron+vit c+vit b12+b6+zinc+folic acid', 'Mullan cosmetics', 'Syrup', 'شراب', '', 'Multivitamin', '120 ml', '', '', '', 688, '2022-12-06', CURRENT_TIMESTAMP),
(13264, 'Aaa', 'ششش', '', '170', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 555, '2022-08-18', CURRENT_TIMESTAMP),
(17264, 'Depalept 500mg/5ml vial for i.v. inf.', 'ديباليبت 500 مجم / 5 مل فيال', '', '18', 'Valproic acid', 'Chemipharm', 'Vial', 'فيال', '', 'Anticonvulsant', '500mg', '**Indicated** for:[Label] 
1) Use as monotherapy or adjunctive therapy in the management of complex partial seizures and simple or complex absence seizures. 
2) Adjunctive therapy in the management of multiple seizure types that include absence seizures. 
3) Prophylaxis of migraine headaches.
4) Acute management of mania associated with bipolar disorder.
**Off-label** uses include:
1) Maintenance therapy for bipolar disorder.[A177919]
2) Treatment for acute bipolar depression.[A177928,A177931,A177934]
3) Emergency treatment of status epilepticus.[A177955]', '6222006501280', '', 887, '2022-07-15', CURRENT_TIMESTAMP),
(16972, 'Cuteca mouth spray 60 ml', 'كيوتكا بخاخ للفم 60 مل', '', '37', 'Cocamidopropyl betaine+sorbitol+ethanol+chlrhexidine gluconate+sodium benzoate+sodium saccharin+sodi', 'Egyptian company for cosmetics > admin pharma', 'Spray', 'بخاخ', 'عناية بالفم', 'Oral care', '60 ml', '', '9654000034063', '', 1078, '2022-07-03', CURRENT_TIMESTAMP),
(16112, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 627, '2022-09-08', CURRENT_TIMESTAMP),
(19509, 'Futanorm 30 mg 10 tabs', 'فوتانورم 30مجم 10 اقراص', '', '20', 'Nimodipine', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', '', 'Calcium channel blocker', '30 mg', 'For use as an adjunct to improve neurologic outcome following subarachnoid hemorrhage (SAH) from ruptured intracranial berry aneurysms by reducing the incidence and severity of ischemic deficits.', '', '', 1139, '2022-06-12', CURRENT_TIMESTAMP),
(31059, 'Oxytoflex 10 i.u./ml 5 conc. amps. for i.v. inf.', 'اوكسيتوفليكس 10وحدة/مل 5 امبول مركز لمحلول وريد', '47.5', '70', 'Oxytocin', 'Marcyrl pharmaceutical industries (mpi)', 'Amp', 'أمبول', 'بدء أو تحسين تقلصات الرحم لتحقيق الولادة المهبلية في وقت مبكر لأسباب تتعلق بالأم أو الجنين ، علاج مساعد في الإجهاض ، السيطرة على النزيف بعد الولادة ، تحفيز المخاض في النساء اللواتي يبدأ عندهن المخاض بشكل طبيعي .', 'Smooth muscle constrictor', '', 'Administration of exogenous oxytocin is indicated in the antepartum period to initiate or improve uterine contractions for vaginal delivery in situations where there is fetal or maternal concern.[L31433] For example, It may be used to induce labor in cases of Rh sensitization, maternal diabetes, preeclampsia at or near term, and when delivery is indicated due to prematurely ruptured membranes.[A229018,L31433] Importantly, oxytocin is not approved or indicated for elective induction of labor. Oxytocin may be used to reinforce labor in select cases of uterine inertia and as adjunctive therapy in the management of incomplete or inevitable abortion. In the postpartum period, oxytocin may be used to induced contractions in the 3rd stage of labor and to control postpartum bleeding or hemorrhage.[L31433]', '6223003574383', '', 4681, '2025-05-04', CURRENT_TIMESTAMP),
(17476, 'Dextrose 25% (25ml) i.v.infusion', 'دكستروز 25% 25 مل محلول وريد', '', '5', 'Glucose (dextrose)', 'Otsuka', 'Unknown', 'غير محدد', '', 'Parenteral solutions', '25%', '', '', '', 843, '2022-07-24', CURRENT_TIMESTAMP),
(5900, 'Hair tone 40 caps', 'هيرتون 40 كبسولة', '', '38', 'Biotin+calcium pantothenate+cysteine+keratin+p-aminobenzoic acid+saccharomyces +vitamin(b1+b2+b6+e)', 'Eva pharma', 'Cap', 'كبسولة', 'لعلاج مشاكل الشعر والاظافر', 'Hair care', '', '', '6223002450367', '', 4738, '2023-01-02', CURRENT_TIMESTAMP),
(26651, 'Sebium pain (soap) 100 gm', 'سيبيوم بين صابون 100جم', '', '129', '', 'Bioderma dermatological laboratories > biotech egypt', 'Soap', 'صابون', '', 'Skin care', '100 gm', 'purifies the epidermis and regulates sebum quality thanks to patented fluidactiv. the exclusive patented complex maintains sebum quality and thus prevents clogging of the pores. apply morning and / or evening on damp skin. foaming rinse well and dry. can', '', '', 409, '2022-08-06', CURRENT_TIMESTAMP),
(24822, 'Pharmaceris t-octopirox soothing face cream spf15 30 ml', 'فارماسيريس تي اوكتوبيروكس كريم للحماية من الشمس 30 مل', '', '195', '', 'Laboratorium kosmetyczne dr irena eris sp. z o.o. > multitrade', 'Cream', 'كريم', '', 'Skin care', '30 ml', 'indications: the cream is recommended for the daily care of reddened and seborrhoeic skin prone to flaking (especially around the nose between eyebrows on the forehead and in the mouth area). it is also recommended during treatment for seborrhoeic dermati', '', '', 651, '2022-07-18', CURRENT_TIMESTAMP),
(23928, 'Oceanz 500 mg 10 sachets', 'اوشنز 500 مجم 10 اكياس', '', '40', 'Omega-3 fish oil 500 mg+whey protein conc.+selenium+zinc+vitamin c', 'Pharmazad > la porte pharma', 'Sachet', 'أكياس', 'يحسن المهارا الادراكية والعقلية -- حماية الاوعية الدموية -- تقليل مستوي الدهون الثلاثية', 'Omega 3', '500 mg', 'Provided as daily supplements. Aa preparation of omega-3-acid ethyl esters is licensed in UK for prevention of recurrent events after myocardial infarction in addition to treatment of hypertriglyceridaemia.', '', '', 795, '2022-05-19', CURRENT_TIMESTAMP),
(22696, 'Micardis plus 80/12.5mg 28 tab.', 'ميكارديس بلس 80/12.5مجم 28 قرص', '208', '270', 'Hydrochlorothiazide+telmisartan', 'Boehringer ingelheim', 'Tab', 'أقراص', '', 'Antihypertensive. combined angiotensin blocker with diuretic', '12.5mg', '', '4048846000675', '', 2051, '2024-05-09', CURRENT_TIMESTAMP),
(22652, 'Methotrexate 500mg pd. for inj. vial', 'ميثوتريكسات 500مجم فيال', '', '119', 'Methotrexate', 'Shanxi pude pharm. > acdima international trading', 'Inj', 'حقن', '', 'Antineoplastic', '500mg', 'Methotrexate oral solution is indicated for pediatric acute lymphoblastic leukemia and pediatric polyarticular juvenile idiopathic arthritis.[L7144] Methotrexate injections for subcutaneous use are indicated for severe active rheumatoid arthritis, polyarticular juvenile idiopathic arthritis and severe, recalcitrant, disabling psoriasis.[L7147,L7150,L10457] It has also been approved by the EMA for the treatment of adult patients requiring systemic therapy for moderate-to-severe plaque psoriasis.[L48796]
Other formulations are indicated to treat gestational choriocarcinoma, chorioadenoma destruens, hydatiform mole, breast cancer, epidermoid cancer of the head and neck, advanced mycosis fungoides, lung cancer, and advanced non-Hodgkin''s lymphoma.[L7180] It is also used in the maintenance of acute lymphocytic leukemia.[L7180] Methotrexate is also given before treatment with leucovorin to prolong relapse-free survival following surgical removal of a tumour in non-metastatic osteosarcoma.[L7180]', '', '', 1168, '2022-07-07', CURRENT_TIMESTAMP),
(9296, 'Aaa', 'ششش', '', '36', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 699, '2022-05-27', CURRENT_TIMESTAMP),
(30439, 'Dyspa-east 300 mg 20 caps.', 'ديسبا ايست 300مجم 20 كبسولة', '68', '140', 'Pancreatin', 'Western pharmaceuticals industries > western pharma', 'Cap', 'كبسولة', 'لعلاج انزيمات هضم الطعام', 'Digestive enzymes', '300 mg', 'about pancreatin a pancreatic enzyme combination dietary supplement fatty food digestive aid. mechanism of action of pancreatin pancreatin is made up of the pancreatic enzymes trypsin amylase and lipase. the trypsin hydrolyze proteins to oligopetides amyl', '', '', 2263, '2025-03-18', CURRENT_TIMESTAMP),
(503, 'Gestranil 0.03/0.075mg 21 sugar c.tabs', 'جيسترانيل 21 قرص', '40', '54', 'Ethinyl estradiol+gestodene', 'Acdima', 'Tab', 'أقراص', 'حبوب منع حمل عن طريق الفم', 'Contraceptive pills', '0.075mg', '', '6224000588694', '', 9531, '2024-09-26', CURRENT_TIMESTAMP),
(8879, 'Nimotop 30mg 30tabs.(illegal import)', 'نيموتوب 30مجم 30 قرص - استيراد', '', '0', 'Nimodipine', 'Bayer schering >', 'Tab', 'أقراص', 'علاج ارتفاع ضغط الدم', 'Calcium channel blocker', '30mg', 'For use as an adjunct to improve neurologic outcome following subarachnoid hemorrhage (SAH) from ruptured intracranial berry aneurysms by reducing the incidence and severity of ischemic deficits.', '8699546010387', '', 7230, '2023-02-04', CURRENT_TIMESTAMP),
(27989, 'Breztri aerosphere 160/9/4.8 mcg 120 doses', 'بريزتري استنشاق 16094.8 مكجم 120 جرعه', '680', '1,060', 'Budesonide+glycopyrronium+formoterol fumarate', 'Astrazeneca', 'Unknown', 'غير محدد', '', 'Bronchodilator.glucocorticoid steroid and long-acting beta2 agonist and anticholinergic', '4.8 mcg', '', '303104616123', '', 3401, '2025-03-24', CURRENT_TIMESTAMP),
(28703, 'Trio chond 30 tablets', 'تريوكوند 30 قرص', '150', '185', 'Chondrotin sulfate+glucosamine+hyaluronic acid+msm+calcium fructoborate', 'Steady pharma', 'Tablet', 'أقراص', '', '', '', '', '', '', 836, '2024-05-25', CURRENT_TIMESTAMP),
(24609, 'Paxeladine 0.2% 125ml syrup', 'باكسيلادين شراب 0.2% للكحة 125 مل', '', '7', 'Oxeladin', 'Arab drug company. > beaufour ipsen-france', 'Syrup', 'شراب', 'علاج الكحة الجافة', 'Cough drugs', '0.2%', '', '6221060001293', '', 961, '2022-12-08', CURRENT_TIMESTAMP),
(18328, 'Enoxirt 1 gm i.v. vial', 'انوكسيرت 1جم فيال وريد', '', '22', 'Ceftriaxone', 'Julphar', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '1 gm', 'Ceftriaxone is used for the treatment of the infections (respiratory, skin, soft tissue, UTI, ENT) caused by susceptible organisms.[L15082] Organisms that are generally susceptible to ceftriaxone include S. pneumoniae, S. pyogenes (group A beta-hemolytic streptococci), coagulase-negative staphylococci, Some Enterobacter spp, H. influenzae, N. gonorrhoeae, P. mirabilis, E. coli, Klebsiella spp, M. catarrhalis, B. burgdorferi, and some oral anaerobes.[A215582]', '', '', 1455, '2022-07-01', CURRENT_TIMESTAMP),
(22380, 'Maxdinir 250mg/5ml 60 ml susp', 'ماكسدنير 250مجم/5مل معلق 60 مل', '62.5', '92', 'Cefdinir', 'Chemipharm', 'Susp', 'معلق', '', 'Antibiotic.cephalosporin.third-generation', '250mg', 'Cefdinir is indicated to treat acute bacterial otitis media, acute maxillary sinusitis, community-acquired (CA) pneumonia, acute bacterial exacerbations of chronic bronchitis, pharyngitis/tonsillitis, and uncomplicated skin and skin structure infections in children and adults.[L7330,A180739]
The organisms susceptible to cefdinir have been listed below in addition to their associated clinical condition that may be treated with cefdinir.[L7330] Various beta-lactamase producing organisms may be treated, as indicated in certain sections below.
**Respiratory**
Acute bacterial exacerbations of chronic bronchitis caused by Haemophilus influenzae, Haemophilus parainfluenzae, Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
Community-acquired pneumonia caused by Haemophilus influenzae, Haemophilus parainfluenzae, Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
**Ear, nose, and throat** 
Acute bacterial otitis media caused by Haemophilus influenzae, Moraxella catarrhalis, and Streptococcus pneumoniae (penicillin-susceptible only)
Tonsillitis caused by Streptococcus pyogenes
Pharyngitis caused by Streptococcus pyogenes
Acute maxillary sinusitis caused by Haemophilus pneumoniae and Streptococcus pneumoniae (penicillin-susceptible only), and Moraxella catarrhalis
**Skin and skin structure infections**
Uncomplicated skin and skin structure infections caused by Staphylococcus aureus and Streptococcus pyogenes', '6222006501365', '', 1583, '2024-08-14', CURRENT_TIMESTAMP),
(24689, 'Pentasa xtend 2 gm 60 sachets', 'بنتازا اكستند 2 جرام 60 كيس', '1230', '1,980', 'Mesalazine(mesalamine)(5-asa)(5-aminosalicylic acid)', 'Ferring pharmaceuticals > multipharma', 'Pen', 'قلم', 'التهاب القولون التقرحي -- علاج مرض الكرون -- علاج التهاب القولون شديد التقرح -- تقليل الالتهابات والالام', 'Ulcerative colitis', '2 gm', 'about mesalazine 5-aminosalicylic acid derivative anti-inflammatory bowel agent. mechanism of action of mesalazine mesalazine exerts its anti-inflammatory action by inhibiting lipoxygenase enzyme. this will leads to decreased production of pro-inflammator', '7640128543817', '', 8850, '2024-11-03', CURRENT_TIMESTAMP),
(24856, 'Pharofruit eff. gr. 6 sachets', 'فاروفروت 6 اكياس', '', '6', 'Citric acid+sodium bicarbonte+tartaric acid', 'Pharopharma', 'Sachet', 'أكياس', '', 'Antacid', '', 'interactions: antacids concurrent use of antacids with citrates may result in systemic alkalosis. concomitant administration of antacids with sodium citrate and sodium bicarbonate may promote the development of calcium stones in patients with uric acid st', '', '', 891, '2022-07-09', CURRENT_TIMESTAMP),
(27743, 'Sutent 50mg 28 capsules', 'سوتنت 50 مجم 28 كبسولة', '20400', '24,480', 'Sunitinib', 'Pfizer', 'Capsule', 'كبسولة', 'علاج الاورام السرطانية', 'Antineoplastic', '50mg', 'Sunitinib is indicated for the following conditions:[L4135]
- Treatment of adult patients with gastrointestinal stromal tumor (GIST) following disease progression on (or intolerance to) [imatinib] mesylate
