(14109, 'Anastrozol synthon 1 mg 28 f.c. tab.', 'اناستروزول سينثون 1 مجم 28 قرص', '400', '706', 'Anastrozole', 'Synthon hispania s.l. > amriya', 'Tab', 'أقراص', 'لعلاج سرطان الثدي لدى النساء بعد سن اليأس', 'Non-steroidal aromatase-inhibitor', '1 mg', 'Anastrozole is indicated as adjunct therapy in the treatment of hormone receptor-positive early breast cancer in postmenopausal women, and as a first-line treatment for hormone receptor-positive (or hormone receptor-unknown) locally advanced or metastatic breast cancer in postmenopausal women.[L8863] It may also be used in the treatment of advanced breast cancer in postmenopausal women who experience disease progression despite treatment with [tamoxifen].[L8866,L8863]', '6224001616013', '', 1705, '2024-12-25', CURRENT_TIMESTAMP),
(27642, 'Sulphargin 1% cream 20 gm', 'سالفارجين 1% كريم 20جم', '18', '26', 'Silver sulfadiazine', 'El nile.', 'Cream', 'كريم', '', 'Antibiotic topical', '1%', 'Indicated as an adjunct for the prevention and treatment of wound sepsis in patients with second- and third-degree burns.', '6221077071616', '', 736, '2025-10-01', CURRENT_TIMESTAMP),
(24615, 'Pearla sd soap 100 gm', 'بيرلا اس دي صابون 100جم', '', '35', '', 'Egyptian company for cosmetics > pearla pharm co.', 'Soap', 'صابون', '', 'Soap', '100 gm', 'cleansing moisturizing soap that protects against germs & bacteria ï- combat acne and comedones. ï- regenerate epithelial cells.', '', '', 711, '2022-07-24', CURRENT_TIMESTAMP),
(13600, 'Restage gel 100 gm', 'ريستاج جل 100 جم', '96', '120', 'Menthol crystal+clove oil+peppermint oil+camphor oil+vit e+paraffin oil', 'Italian co. for cosemetics > savi pharma', 'Gel', 'جل', '', 'Analgesic and inti-inflamatory', '100 gm', 'fast acting pain killer with extra cooling effect anti inflammatory & anti edematous', '', '', 2625, '2024-10-02', CURRENT_TIMESTAMP),
(2163, 'Cavernosa 20 tabs', 'كافيرنوزا 20 قرص', '', '189', '', 'Company', 'Tab', 'أقراص', '', '', '', '', '', '', 1371, '2024-07-01', CURRENT_TIMESTAMP),
(14948, 'Beauty gel 30 gm', 'بيوتي جل 30 جم', '', '12', 'Hydroquinone+retinoic acid', 'Cid', 'Gel', 'جل', '', 'Anti-acne', '30 gm', 'about hydroquinone benzenediol derivative depigmenting agent. mechanism of action of hydroquinone hydroquinone decreases the formation of melanin in the skin. it inhibits tyrosinase and other melanin forming enzymes and thus decreases the formation and in', '6221043012605', '', 1383, '2022-12-03', CURRENT_TIMESTAMP),
(8193, 'Mineravit 20 soft gelatin caps.', 'مينرافيت 20 كبسولة', '15', '27', 'Minerals+vitamins', 'Eipico', 'Cap', 'كبسولة', 'فيتامينات متعددة -- مقوي للمناعة -- مقوي للاعصاب', 'Multivitamins', '', 'about minerals dietary mineral supplement nutritional supplement.', '6221032140319', '', 26652, '2024-12-06', CURRENT_TIMESTAMP),
(26442, 'Safa cream 30 gm', 'صفا كريم 30 جم', '59', '70', 'B-sitosterol+propolis+panthenol+calendula+chamomile', 'El-helou perfumes & cosmetics > dawaa pharma', 'Cream', 'كريم', 'كريم لعلاج الجروح والندبات -- يعمل علي ترطيب الجلد -- توحيد لون البشرة', 'Healing topical', '30 gm', 'for burns & wound healing.', '', '', 2607, '2025-05-18', CURRENT_TIMESTAMP),
(18393, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 858, '2022-09-13', CURRENT_TIMESTAMP),
(13251, 'A.one soap 100 gm', 'صابونة اي وان 100 جم', '', '10', '', 'A one pharm', 'Soap', 'صابون', '', 'Antifungal', '100 gm', 'anti-fungal anti-bacterial', '', '', 928, '2022-08-06', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(22011, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 718, '2023-04-18', CURRENT_TIMESTAMP),
(32155, 'Pro lepo topical cream 30gm', 'برو ليبو كريم موضعي 30 جم', '', '39', 'Sesame oil+bees wax+honey+zinc 5%+olive+chamomile+allantoin+lanolin+panthenol+vit a+vit e+camphore+thyme+tea oil', 'El nile for cosmetics > pro line care medicine', 'Cream', 'كريم', 'يستخدم للتخسيس، وفقدان الوزن.التخلص من السمنة والدهون.يرفع معدل الحرق موضعياً.', 'Burn cream', '30gm', '', '', '', 1273, '2023-04-23', CURRENT_TIMESTAMP),
(2857, 'Remerovit 100ml syrup', 'ريميروفيت شراب 100 مل', '', '50', 'Vit a+vit d3+vit e+vit b1+b2+b6+b12+pantothenic+nicotinamide+vit c+lysine+iron+zinc+magnesium', 'Merge pharma', 'Syrup', 'شراب', '', 'Multivitamins & minerals', '100ml', '', '', '', 774, '2022-09-09', CURRENT_TIMESTAMP),
(15233, 'Bioblas liquid conditioner 100ml', 'بيوبلاس بلسم 100مل', '', '124', '', 'Ego pharmaceuticals pty ltd. > vamer pharma', 'Conditioner', 'بلسم', '', 'Hair care', '100ml', 'contains phyto-keratin for weak damaged hair .repairing & revitalizing care reduces friction revives glistening highlights and restores hair health. allows even fragile hair to regain elasticity protects hair from periodic and acute hair loss with 100% na', '8697432094800', '', 485, '2022-08-06', CURRENT_TIMESTAMP),
(8215, 'Minoxidil forte 5% topical gel 60 gm', 'مينوكسيديل فورت 5% جل 60 جم', '84', '127', 'Minoxidil', 'Egpi > pharmacare', 'Gel', 'جل', 'علاج للصلع.', 'Hair regrowth.vasodilator agents', '5%', 'For the treatment of severe hypertension and in the topical treatment (regrowth) of androgenic alopecia in males and females and stabilisation of hair loss in patients with androgenic alopecia.', '6224007322178', '', 4985, '2024-06-27', CURRENT_TIMESTAMP),
(26481, 'Aaa', 'ششش', '', '10', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 806, '2022-06-26', CURRENT_TIMESTAMP),
(8982, 'Oponov 20 tablets', 'اوبونوف 20 قرص', '110', '135', 'Rutosid+bromelain+trypsin+l-leucine', 'Copad egypt', 'Tablet', 'أقراص', 'مضاد للالتهابات و مضاد للتورم و الالتهابات المزمنة و مضاد للاكسدة', 'Proteolytic enzyme formula', '', '', '6223011340130', '', 41651, '2024-11-16', CURRENT_TIMESTAMP),
(15190, 'Biguanelle gynaecological solution 100 ml+vaginal cannula', 'بيجوانيل غسول للسيدات 100 مل', '', '120', '', 'Lo.li pharma > habib scientific office', 'Solution', 'محلول', '', 'Vaginal wash', '100 ml', 'single-dose bottle of 100 ml ready to use + vaginal cannula', '', '', 949, '2022-10-06', CURRENT_TIMESTAMP),
(31259, 'Rotacysteine 600 mg 10 sachets', 'روتاسيستايين 600مجم 10 اكياس', '', '30', 'Acetylcysteine', 'Rotabiogen', 'Sachet', 'أكياس', '', 'Mucolytic', '600 mg', 'Acetylcysteine is indicated for mucolytic therapy and in the management of [acetaminophen] overdose.[L31378,L31383,L31388,L31478]', '', '', 1379, '2022-12-11', CURRENT_TIMESTAMP),
(18423, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 618, '2022-10-08', CURRENT_TIMESTAMP),
(25917, 'Respatio 20 mg 20 f.c.tabs.', 'ريسباتيو 20مجم 20 قرص', '63', '94', 'Sildenafil', 'Marcyrl co. > pharma right group', 'Tab', 'أقراص', 'مقوى للرجال', 'Tonic for men', '20 mg', 'Sildenafil is a phosphodiesterase-5 (PDE5) inhibitor that is predominantly employed for two primary indications:
(1) the treatment of erectile dysfunction [A175582, L5611, F3853, F3856, F3886]; and
(2) treatment of pulmonary hypertension, where:
a) the US FDA specifically indicates sildenafil for the treatment of pulmonary arterial hypertension (PAH) (WHO Group I) in adults to improve exercise ability and delay clinical worsening [F3850]. The delay in clinical worsening was demonstrated when sildenafil was added to background epoprostenol therapy [F3850]. Studies establishing effectiveness were short-term (12 to 16 weeks), and included predominately patients with New York Heart Association (NYHA) Functional Class II-III symptoms and idiopathic etiology (71%) or associated with connective tissue disease (CTD) (25%) [F3850];
b) the Canadian product monograph specifically indicates sildenafil for the treatment of primary pulmonary arterial hypertension (PPH) or pulmonary hypertension secondary to connective tissue disease (CTD) in adult patients with WHO functional class II or III who have not responded to conventional therapy [F3859]. In addition, improvement in exercise ability and delay in clinical worsening was demonstrated in adult patients who were already stabilized on background epoprostenol therapy [F3859]; and
c) the EMA product information specifically indicates sildenafil for the treatment of adult patients with pulmonary arterial hypertension classified as WHO functional class II and III, to improve exercise capacity [F3883]. Efficacy has been shown in primary pulmonary hypertension and pulmonary hypertension associated with connective tissue disease [F3883]. The EMA label also indicates sildenafil for the treatment of pediatric patients aged 1 year to 17 years old with pulmonary arterial hypertension [F3883]. Efficacy in terms of improvement of exercise capacity or pulmonary hemodynamics has been shown in primary pulmonary hypertension and pulmonary hypertension associated with congenital heart disease [F3883].', '6224007733011', '', 5971, '2024-08-04', CURRENT_TIMESTAMP),
(6895, 'Drakon face whitening cream 50 gm', 'دراكون كريم تبييض الوجه 50 جم', '', '180', 'Liquorice+arbutin+kojic acid+vitamin c+melon extract+panthenol+titanium dioxide', 'Pharma cruise medical', 'Cream', 'كريم', '', 'Skin care.whitening', '50 gm', '', '', '', 822, '2025-08-16', CURRENT_TIMESTAMP),
(13058, 'Aaa', 'ششش', '', '12', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 770, '2022-09-22', CURRENT_TIMESTAMP),
(27089, 'Slim safe 120mg 30 caps.', 'سليم سيف 120مجم 30 كبسولة', '105', '162', 'Orlistat', 'Amoun', 'Cap', 'كبسولة', '1- تخسيس البطن والأرداف.', 'Weight loss', '120mg', 'Orlistat is indicated for obesity management including weight loss and weight maintenance when used in combination with calorie reduction in overweight and obese adults; this indication applies to both the prescription formulation of 120 mg[L11130] and the over-the-counter formulation of 60 mg.[L31963] Orlistat in the 120 mg prescription formulation is also indicated to reduce the risk of weight regain following weight loss.[L11130]', '6221025023384', '', 5595, '2024-03-23', CURRENT_TIMESTAMP),
(26245, 'Rogenda emollient cream 50 gm', 'روجندا كريم 50جم', '', '35', 'Zinc oxide + olive oil + thyme oil + beeswax + coconut oil + chamomile extract', 'Hi-care > lusenda pharma', 'Cream', 'كريم', 'للترطيب والعناية بالبشرة', 'Skin care', '50 gm', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 1158, '2022-05-20', CURRENT_TIMESTAMP),
(23752, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 632, '2023-05-01', CURRENT_TIMESTAMP),
(13959, 'Amlobenzamir 5/10mg 10 caps.', 'املوبنزامير 5/10 مجم 10 كبسولات', '', '12', 'Amlodipine+benazepril', 'Medizen pharmaceutical industries > mira international', 'Cap', 'كبسولة', '', 'Antihypertensive.combined ace with calcium channel blocker', '10mg', 'mechanism of action of amlodipine amlodipine is a second generation dihydropyridine ca channel blocker. it exerts it`s antihypertensive antianginal actions through blocking the influx of ca ions through voltage gated l-type ca channels to the peripheral v', '', '', 947, '2022-07-20', CURRENT_TIMESTAMP),
(1859, 'Calci-cal syrup 120 gm', 'كالسي-كال شراب 120 جم', '', '8', 'Calcium levulinate+vitamin d3+vitamin b12', 'Hikma pharma', 'Syrup', 'شراب', '', 'Calcium supplement', '120 gm', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 1625, '2022-10-28', CURRENT_TIMESTAMP),
(4493, 'Pitanasabrandia spray 60 ml', 'بيتاناسابرانديا 60 مل بخاخ', '60', '70', 'Hyaluronic acid+panthenol+aloe vera extract+eucalyptus+menthol+vitamin a+vitamin e+wheat germ oil+glycerine+chlorhexidine', 'Alico pharma', 'Spray', 'بخاخ', '', 'Oral spray', '60 ml', 'The intra-articular preparations of hyaluronic acid are indicated for knee pain associated with osteoarthritis.[L32228] Hyaluronic acid is used in cosmetic applications to prevent and reduce the appearance of wrinkles on the face, and as a dermal filler to correct facial imperfections or other imperfections on other parts of the body.[L32208,L32223] It is frequently an ingredient in topical applications for wound healing and symptomatic treatment of skin irritation from various causes.[L32198] Hyaluronic acid may also be indicated in ophthalmological preparations or oral capsules to treat discomfort caused by dry eyes or conjunctivitis and for its protective qualities during and before eye surgery.[A230128,L32213] Finally, hyaluronic acid can be used off-label to coat the bladder for relief of interstitial cystitis symptoms.[A230533]', '', '', 859, '2025-07-15', CURRENT_TIMESTAMP),
(19427, 'Frost gel 100 gm', 'فروست جل 100 جرام', '95', '110', 'Menthol+chamomile+lavender+propylene glycol+glycerin', 'Macro group pharmaceuticals', 'Gel', 'جل', 'مساج جل لالام العضلات', 'Massage.topical analgesic.muscle', '100 gm', '*deep penetrating long lasting pain reliever cooling gel with the herbal power for relieving body sufferings *topical gel for relieving muscles & joints pain *relaxes tensed muscles & restores mobility. *can be massaged gently and evenly over tendons and', '6224000437664', '', 9809, '2025-01-31', CURRENT_TIMESTAMP),
(31858, 'Mash sunscreen kids spray 200 ml', 'ماش واقى شمس سبراي 200 مل', '350', '395', 'Sun protection formula', 'Mash premiere', 'Spray', 'بخاخ', '', 'Sun block', '200 ml', '', '', '', 947, '2024-10-13', CURRENT_TIMESTAMP),
(13365, 'Bonefit 10.000 i.u./ml oral drops 15 ml', 'بونفيت 10000 وحدة دولية/مل نقط فم 15 مل', '93', '120', 'Cholecalciferol(vitamin d3)', 'Organix > rotabogen', 'Drops', 'نقط', 'فيتامين دال', 'Vitamin d', '15 ml', 'description derivative of 7-dehydroxycholesterol formed by ultraviolet rays breaking of the c9-c10 bond. it differs from ergocalciferol in having a single bond between c22 and c23 and lacking a methyl group at c24 indication for the treatment of vitamin d', '6224011378055', '', 3061, '2025-12-01', CURRENT_TIMESTAMP),
(32121, 'Sildatrona 100 mg 12 f.c.tabs.', 'سيلداترونا 100مجم 12 قرص', '', '54', 'Sildenafil', 'Averroes pharma', 'Tab', 'أقراص', 'مقوى للرجال', 'Tonic for men', '100 mg', 'Sildenafil is a phosphodiesterase-5 (PDE5) inhibitor that is predominantly employed for two primary indications:
(1) the treatment of erectile dysfunction [A175582, L5611, F3853, F3856, F3886]; and
(2) treatment of pulmonary hypertension, where:
a) the US FDA specifically indicates sildenafil for the treatment of pulmonary arterial hypertension (PAH) (WHO Group I) in adults to improve exercise ability and delay clinical worsening [F3850]. The delay in clinical worsening was demonstrated when sildenafil was added to background epoprostenol therapy [F3850]. Studies establishing effectiveness were short-term (12 to 16 weeks), and included predominately patients with New York Heart Association (NYHA) Functional Class II-III symptoms and idiopathic etiology (71%) or associated with connective tissue disease (CTD) (25%) [F3850];
b) the Canadian product monograph specifically indicates sildenafil for the treatment of primary pulmonary arterial hypertension (PPH) or pulmonary hypertension secondary to connective tissue disease (CTD) in adult patients with WHO functional class II or III who have not responded to conventional therapy [F3859]. In addition, improvement in exercise ability and delay in clinical worsening was demonstrated in adult patients who were already stabilized on background epoprostenol therapy [F3859]; and
c) the EMA product information specifically indicates sildenafil for the treatment of adult patients with pulmonary arterial hypertension classified as WHO functional class II and III, to improve exercise capacity [F3883]. Efficacy has been shown in primary pulmonary hypertension and pulmonary hypertension associated with connective tissue disease [F3883]. The EMA label also indicates sildenafil for the treatment of pediatric patients aged 1 year to 17 years old with pulmonary arterial hypertension [F3883]. Efficacy in terms of improvement of exercise capacity or pulmonary hemodynamics has been shown in primary pulmonary hypertension and pulmonary hypertension associated with congenital heart disease [F3883].', '6224008179900', '', 3091, '2023-04-23', CURRENT_TIMESTAMP),
(32110, 'Zincokid lotion 120 ml', 'زنكوكيد لوشن 120 مل', '35', '65', 'Zinc oxide+panthenol+chamomile+aloevera+chlorhexidine', 'Nile cosmotics > prosperity company', 'Lotion', 'لوشن', 'لوشن للوجه والجسم لعلاج الجفاف والتشققات', 'Skin care', '120 ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '6224004500029', '', 1558, '2025-08-08', CURRENT_TIMESTAMP),
(15736, 'Aaa', 'ششش', '', '650', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 632, '2022-08-03', CURRENT_TIMESTAMP),
(13994, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 647, '2022-09-06', CURRENT_TIMESTAMP),
(3011, 'Controlepsy 50 mg 30 tab', 'كونترولبسي 50 مجم 30 قرص', '58.5', '78', 'Lamotrigine', 'Global napi pharmaceuticals', 'Tab', 'أقراص', 'علاج الصرع -- تقليل التشنجات الناتجة عن الصرع', 'Anti-epileptic.triazine', '50 mg', 'Lamotrigine is indicated as adjunctive therapy for the following seizure types in patients ≥2 years of age: partial seizures, primary generalized tonic-clonic seizures, and generalized seizures due to Lennox-Gastaut syndrome.[L9404]
It is also indicated for the process of conversion to drug monotherapy for those at least 16 years of age or older with partial seizures and currently are receiving treatment with carbamazepine, phenytoin, phenobarbital, primidone, or valproate as the single antiepileptic drug (AED).[L9404]
In addition to the above, lamotrigine is also indicated for the maintenance treatment of bipolar I disorder, delaying the time to mood episodes (which may include mania, hypomania, depression, mixed episodes) in adults at least 18 years or older, who have been treated for acute mood symptoms with standard therapy.[L9404]
