(22620, 'Ponvory 2 to 10 mg 14 f.c.tabs. (treatment-initiation pack)', 'بونفوري 2 الى 10 مجم 14 قرص', '', '9,000', 'Ponesimod', 'Janssen cilag', 'Tab', 'أقراص', '', 'Immunosuppressant', '10 mg', 'Ponesimod is indicated to treat adults with relapsing forms of multiple sclerosis, including clinically isolated syndrome, relapsing-remitting disease, and active secondary progressive disease.[L32709]', '', '', 679, '2023-05-04', CURRENT_TIMESTAMP),
(21074, 'Ivatherm anti-wrinkle and anti-dark circle eye cream 15 ml', 'ايفاثيرم كريم مضاد للتجاعيد والهالات السوداء للعين 15 مل', '', '334', '', 'Ivatherm srl > vamer pharma', 'Cream', 'كريم', '', 'Eye contour', '15 ml', 'anti-wrinkle and anti-dark circle eye contour cream sensitive skin 15ml anti-wrinkle and eye contour concealer significantly reduces deep and superficial wrinkles around the eyes by botox-like effect inhibiting muscle contraction. act effectively on dark', '', '', 625, '2022-07-26', CURRENT_TIMESTAMP),
(27582, 'Aaa', 'ششش', '', '33', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 649, '2022-10-28', CURRENT_TIMESTAMP),
(24516, 'Panthenol 2% hair lotion 190 ml', 'بانثينول 2% لوشن للشعر 190مل', '30', '50', 'Panthenol', 'El nile.', 'Lotion', 'لوشن', '', 'Hair care', '2%', 'Panthenol (containing a racemic mixture of dexpanthenol and levopanthenol) is not currently available in any FDA-approved products and therefore does not have an indication.
Please see [DB09357] for FDA-approved uses of the dextrorotatory form of Panthenol.', '', '', 1218, '2024-12-02', CURRENT_TIMESTAMP),
(6972, 'Candy-c 12 lozenges', 'كاندي سي 12 قرص', '', '54', 'Vitamin c+thyme+menthol', 'Brother pharma', 'Lozenges', 'استحلاب', '', 'Sore throat', '', 'For the treatment of vitamin A deficiency.', '', '', 826, '2025-08-16', CURRENT_TIMESTAMP),
(29994, 'Mast-amyl 300 u.ceip 100 ml syrup', 'ماست اميل 300 وحدة شراب 100 مل', '55', '59', 'Alpha amylase', 'Master pharmaceutical industries', 'Syrup', 'شراب', 'مضاد للقيء والترجيع', 'Anti-inflammatory enzymes', '100 ml', '', '', '', 904, '2025-08-15', CURRENT_TIMESTAMP),
(17224, 'Deltaclav 625mg 10 f.c.tab.', 'دلتاكلاف 625 مجم 10 اقراص', '', '30', 'Amoxicillin+clavulanic acid', 'Sedico > delta pharma', 'Tab', 'أقراص', '', 'Penicillins.penicillin with b-lactamase inhibitor', '625mg', '', '', '', 2099, '2022-09-10', CURRENT_TIMESTAMP),
(715, 'Anallerge 2mg/5ml syrup 100 ml', 'انالليرج 2 مجم/5مل شراب 100 مل', '7', '13', 'Chlorpheniramine', 'Kahira', 'Syrup', 'شراب', 'مضاد للحساسية', 'Antihistamine.antiallergy', '2mg', 'For the treatment of rhinitis, urticaria, allergy, common cold, asthma and hay fever.', '6221068402948', '', 2374, '2024-11-23', CURRENT_TIMESTAMP),
(6695, 'Loteranol 0.5% eye gel 5 gm', 'لوتيرانول 0.5% جل للعين 5 جم', '41', '47', 'Loteprednol etabonate', 'Orchidia', 'Gel', 'جل', '', 'Glucocorticoid', '0.5%', 'A number of prescription loteprednol etabonate ophthalmic products are specifically indicated for the treatment of post-operative inflammation and pain following ocular surgery [FDA Label].', '6223005444400', '', 2133, '2025-07-13', CURRENT_TIMESTAMP),
(6164, 'Inizio rinnovo moisturizing lotion 150 ml', 'اينيزيو رينوفو لوشن للتساقط ومرطب 150 مل', '', '270', '', 'The egyptian company for cosmetics', 'Lotion', 'لوشن', '', '', '150 ml', '', '795697092383', '', 629, '2025-07-25', CURRENT_TIMESTAMP),
(1552, 'Biomox 125mg/5ml susp. 80ml', 'بيوموكس 125مجم/5مل معلق 80 مل', '', '6', 'Amoxicillin', 'Sedico', 'Susp', 'معلق', '', 'Penicillins.monocomponent', '125mg', 'Amoxicillin alone is indicated to treat susceptible bacterial infections of the ear, nose, throat, genitourinary tract, skin, skin structure, and lower respiratory tract.[L11656,L11659] Amoxicillin is given with calvulanic acid to treat acute bacterial sinusitis, community acquired pneumonia, lower respiratory tract infections, acute bacterial otitis media, skin and skin structure infections, and urinary tract infections.[L11650,L7880,L11653] Amoxicillin is given with omeprazole in the treatment of _Helicobacter pylori_ (_H. pylori_) infection.[L9743,L11647]
Amoxicillin is used in combination with [vonoprazan] and [clarithromycin] as co-packaged triple therapy or in combination with [vonoprazan] as co-packaged dual therapy to treat _H. pylori_ infection in adults.[L41695]', '6221042476019', '', 933, '2023-05-19', CURRENT_TIMESTAMP),
(6898, 'Dozova ashwagandha ksm-66 / 60 h.g. caps.', 'دوزوفا اشواجندا كي اس ام 66 - 60 كبسولة', '', '394', 'Ksm-66', 'Zeta pharma', 'Cap', 'كبسولة', '', 'Antioxidant', '', '', '', '', 741, '2025-08-16', CURRENT_TIMESTAMP),
(12852, 'Zincofact cream 50 gm', 'زنكوفاكت كريم مرطب للجلد 50 جم', '55', '75', 'Calendula oil+chamomile oil+honey+chlorhexidine+triclosan+zinc oxide', 'El-helou perfumes & cosmetics > medifact group', 'Cream', 'كريم', 'كريم مرطب وملطف للجلد', 'Moisturizing topicals', '50 gm', 'skin emollient cream', '6224007745014', '', 4711, '2025-07-05', CURRENT_TIMESTAMP),
(9689, 'Aaa', 'ششش', '', '28', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 759, '2022-11-02', CURRENT_TIMESTAMP),
(17926, 'Ducray elution shampoo 300ml', 'دوكري شامبو شطف 300 مل', '', '99', '', 'Pierre - fabre france > biotech egypt', 'Amp', 'أمبول', '', 'Hair care', '300ml', 'dermo-protective shampoo for normal and delicate hair. your scalp can be weakened during or after an anti-dandruff treatment. elution shampoo gently cleanses your scalp and reduces the risk of recurring dandruff thanks to its very gentle cleansing base co', '', '', 696, '2022-08-03', CURRENT_TIMESTAMP),
(18710, 'Exluton 0.5mg 28 tab.', 'اكسلوتون 0.5مجم 28 قرص', '', '11', 'Lynestrenol', 'Schering plough > merck sharp & dohme scientific office', 'Tab', 'أقراص', '', 'Contraceptives', '0.5mg', 'about lynestrenol synthetic progestogen hormonal contraception mechanism of action of lynestrenol as a synthetic oral progestogen lynestrenol has similar effects as that of the natural progesterone hormone. it has a strong progestational effect on the ute', '', '', 950, '2022-12-08', CURRENT_TIMESTAMP),
(18151, 'Eldoquine forte 4 % cream 28.4 gm', 'الدوكين فورت 4% كريم 28.4 جم', '', '51', 'Hydroquinone', 'Icn pharmaceutical inc u.s.a > eimc', 'Cream', 'كريم', '', 'Whitening topical', '4 %', 'Hydroquinone is used as an OTC topical lightening agent for disorders of hyperpigmentation including melasma, post-inflammatory hyperpigmention, sunspots and freckles.', '301870012170', '', 788, '2022-12-04', CURRENT_TIMESTAMP),
(17681, 'Eurodrava 30 tab', 'يورودرافا 30 قرص', '', '480', 'Glucosamin sulfate + chondroitin sulfate + msm + boswellia serrata extract + tumeric root extract + hyaluronic acid', 'Euro pharmaceutical', 'Tab', 'أقراص', 'علاج الذبحة الصدرية — الوقاية من الذبحة الصدرية — لعلاج آلام شديدة فى الصدر — فشل القلب الاحتقانى', 'Anti rheumatoid osteoarthritis anabolic effect', '', '', '', '', 1056, '2022-08-31', CURRENT_TIMESTAMP),
(18277, 'Nashprep 10mg 14 f.c. tab', 'ناشبريب 10مجم 14 قرص', '165', '206', 'Obeticholic acid', 'Viomix', 'Tab', 'أقراص', '', 'Farnesoid x receptor (fxr) agonist', '10mg', 'Obeticholic acid is indicated for the treatment of primary biliary cholangitis in combination with ursodeoxycholic acid (UDCA) in adults with an inadequate response to UDCA. It is also used as a monotherapy in adults with PBC that are unable to tolerate UDCA.[L12633]
Obeticholic acid is currently being considered for FDA approval to treat fibrosis caused by non-alcoholic liver steatohepatitis (NASH), and is likely to be approved for this indication in 2020.[L12636]', '', '', 845, '2024-08-08', CURRENT_TIMESTAMP),
(26382, 'Royalsteride 5 mg 20 f.c. tabs.', 'رويالستيرايد 5مجم 20 قرص', '', '52', 'Finasteride', 'Hi-pharm > royal link pharma', 'Tab', 'أقراص', 'علاج حالات تضخم البروستاتا الحميد -- علاج في بعض حالات الصلع وتساقط الشعر', '5 alpha-reductase inhibitor', '5 mg', 'Finasteride is indicated for the treatment of symptomatic benign prostatic hyperplasia (BPH) in men with an enlarged prostate to improve symptoms, reduce the risk of acute urinary retention, and reduce the risk of the need for surgery including transurethral resection of the prostate (TURP) and prostatectomy.[L10565] A combination product with [tadalafil] is also used for the symptomatic treatment of BPH for up to 26 weeks.[L39439]
Finasteride is also indicated for the treatment of male pattern hair loss (androgenetic alopecia, hereditary alopecia, or common male baldness) in male patients.[L6235]', '', '', 10212, '2023-01-11', CURRENT_TIMESTAMP),
(22413, 'Maxrdax gel 50 gm', 'ماكسرداكس جل 50 جرام', '', '39', 'Menthol+camphor+eucalyptus+clove oil+alpha tocopherol+methyl salicylate', 'Egyptian co. for cosmetics > medix pharm', 'Gel', 'جل', 'جل مساج للجسم -- يساعد علي تخفيف الالام و التهابات العظام و المفاصل -- يساعد علي استرخاء الجسم', 'Massage gel', '50 gm', 'analgesic', '', '', 1829, '2022-04-09', CURRENT_TIMESTAMP),
(32604, 'Calunited 30 tabs', 'كاليونايتد 30قرص', '60', '110', 'Calcium+magnesium+vitamin d3+zinc+boron+vitamin k', 'S3r pharma', 'Tab', 'أقراص', '', 'Calcium supplement', '', 'calunited tablets dietary supplement contributes to maintenance of normal bones', '6224009947072', '', 1702, '2025-07-05', CURRENT_TIMESTAMP),
(4447, 'Etodine 300mg 10 caps.', 'ايتودين 300مجم 10 كبسولات', '', '14', 'Etodolac', 'Pharco', 'Cap', 'كبسولة', '', 'Nsaid.acetic acid derivatives', '300mg', 'For acute and long-term management of signs and symptoms of osteoarthritis and rheumatoid arthritis, as well as for the management of pain.', '6223000013144', '', 1100, '2022-11-03', CURRENT_TIMESTAMP),
(30157, 'Artilane classic 15 bottles 10 ml', 'ارتيلان كلاسيك 15زجاجه 10 مل', '295', '390', 'Enzymatic hydrolyzed collagen+hyaluronic acid+quercetine+lycopene+vitamin c+coenzyme q10+magnesium+zinc', 'Opko health iberoamerica > phoenix group', 'Bottle', 'زجاجة', '', 'Joint care', '10 ml', 'composition: enzymatic hydrolyzed collagen of high purity hyaluronic acid antioxidants (quercetine lycopene vitamin c coenzyme q10) magnesium and zinc. indication: dietary supplement for osteoarthritis treatment based on collagen hyaluronic acid and antio', '', '', 1054, '2023-11-08', CURRENT_TIMESTAMP),
(11821, 'Alkapress trio 5/160/25mg 14 f.c. tabs.', 'الكابرس تريو 5/160/25مجم 14 قرص', '52', '110', 'Amlodipine+hydrochlorothiazide+valsartan', 'Hikma pharma', 'Tab', 'أقراص', '', 'Antihypertensive. combined angiotensin blocker with calcium channel blocker', '25mg', '', '6221000010811', '', 1405, '2024-01-06', CURRENT_TIMESTAMP),
(4624, 'Fam 10mg 30 tab.', 'فام 10مجم 30 قرص', '21', '66', 'Ketorolac tromethamine', 'Alfacure pharmaceuticals', 'Tab', 'أقراص', '', 'Nsaid.acetic acid derivatives', '10mg', 'Ketorolac is a Non-steroidal anti-inflammatory drug (NSAID) and has antipyretic, analgesic and anti-inflammatory properties.[A176131]  It is indicated for short term management of acute pain that requires the calibre of pain management offered by opioids.[L3674]  Clinicians may choose to initiate ketorolac to manage post-operative pain, spinal and soft tissue pain, rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, menstrual disorders and headaches among other ailments.[L6520] Regardless of the etiology of pain, patients should use the lowest possible dose, and avoid using ketorolac for an extended period of time (ideally ≤ 5 days).[L3674] A benefit of choosing ketorolac over other analgesics with similar potency is that that there does not appear to be a risk of dependence or tolerance with ketorolac use.[A176131]', '6224007711767', '', 1652, '2025-10-23', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(16481, 'Hydrensa cleansing gel 200 ml', 'هيدرنسا جل منظف 200 مل', '149', '155', 'Essential ceramides+hyaluronic acid+niacinamide', 'Bio stream', 'Gel', 'جل', '', 'Skin care', '200 ml', '', '6224001714078', '', 661, '2024-12-01', CURRENT_TIMESTAMP),
(27373, 'Spectragel 2q gel 10 gm', 'سبكترا جل تو كيو جل 10جم', '', '800', 'Polysiloxane', 'Spectrum designs medical > p.r.t.', 'Gel', 'جل', '', 'Scar therapy', '10 gm', 'spectragel2q is a topical silicone gel designed for sensitive skin post laser chemical peeling and dermabrasion. spectragel2q is air permeable odorless and invisible in just 5 minutes. once dry spectragel2q may be worn under makeup. a great advantage of u', '', '', 942, '2023-01-19', CURRENT_TIMESTAMP),
(18138, 'El nasr solvent for antibiotics-dry mix 50ml', 'النصر مذيب المضاد الحيوي دراي ميكس 50 مل', '', '3', 'Purified water', 'El nasr', 'Sol', 'محلول', 'مياة معقمة لازابة المضاد الحيوى', 'Purified water', '50ml', 'purified water water obtained by distillation or deionization.', '', '', 1281, '2022-07-09', CURRENT_TIMESTAMP),
(6303, 'Hygi-tadine 5 mg 20 f.c. tabs.', 'هايجى تادين 5 مجم 20 قرص', '20', '48', 'Desloratadine', 'Dbk pharma > hygint pharmaceuticals-egypt', 'Tab', 'أقراص', '', 'Antihistamine.antiallergy', '5 mg', 'For the relief of symptoms of seasonal allergic rhinitis, perennial (non-seasonal) allergic rhinitis. Desloratidine is also used for the sympomatic treatment of pruritus and urticaria (hives) associated with chronic idiopathic urticaria.', '6225000047785', '', 1779, '2025-12-16', CURRENT_TIMESTAMP),
(31122, 'Prebiotic 5 gm 10 sachets', 'بريبيوتيك 5جم 10 اكياس', '69', '99', 'Dextrin', 'Jasper for pharmaceutical industries', 'Sachet', 'أكياس', '', '.', '5 gm', 'Investigated for use/treatment in HIV prevention.', '', '', 623, '2025-06-12', CURRENT_TIMESTAMP),
(15461, 'Brainal 0.02% vial for i.v. inf. (n/a yet)', 'برينال 0.02% فيال', '', '80', 'Nimodipine', 'Sigma tec', 'Vial', 'فيال', '', 'Calcium channel blocker', '0.02%', 'For use as an adjunct to improve neurologic outcome following subarachnoid hemorrhage (SAH) from ruptured intracranial berry aneurysms by reducing the incidence and severity of ischemic deficits.', '', '', 767, '2022-07-15', CURRENT_TIMESTAMP),
(25950, 'Revarest vag.douche 250 ml', 'ريفارست تشطيف مهبلي 250 مل', '75', '85', 'Rose water+glycerin+citric acid+menthol+tea tree oil+borax+cleansing & foaming system', 'Macro group pharmaceuticals', 'Unknown', 'غير محدد', 'تشطيف غسول مهبلي', 'Vaginal wash', '250 ml', 'Indicated as a diagnostic agent in routine ocular examinations or when superficial conjunctiva or corneal tissue change is suspected, and as an aid in the diagnosis of keratoconjunctivitis sicca, keratitis, abrasions or corrosions as well as the detection of foreign bodies.', '6224000437503', '', 6102, '2025-03-04', CURRENT_TIMESTAMP),
(31636, 'Yervoy 50mg/10 ml vial', 'يرفوي 50مجم10مل فيال', '54500', '72,094', 'Ipilimumab', 'Bristol-myers squibb > middle east', 'Vial', 'فيال', '', 'Antineoplastic', '50mg', 'Ipilimumab is indicated in the following cancerous conditions:[L42050]
**Melanoma**
- Treatment of unresectable or metastatic melanoma in patients ≥12 years old
- Treatment of unresectable or metastatic melanoma, in combination with [nivolumab], in adult patients
- Adjuvant treatment of patients with cutaneous melanoma with pathologic involvement of regional lymph nodes of >1 mm who have undergone complete resection, including total lymphadenectomy
**Renal Cell Carcinoma (RCC)**
- First-line treatment of patients with intermediate- or poor-risk advanced renal cell carcinoma in combination with nivolumab
**Colorectal Cancer**
- In combination with nivolumab, treatment of patients ≥12 years old with microsatellite instability-high (MSI-H) or mismatch repair deficient (dMMR) metastatic colorectal cancer that has progressed following previous treatment with a fluoropyrimidine, [oxaliplatin], and [irinotecan]
**Hepatocellular Carcinoma**
- In combination with nivolumab, treatment of patients with hepatocellular carcinoma who have been previously treated with sorafenib
**Non-Small Cell Lung Cancer (NSCLC)**
