(30101, 'Allergicasone 125/50 mcg nasal spray 140 actuations', 'اليرجيكازون 125/50مكجم بخاخ للانف 140 جرعة', '62', '92', 'Azelastine+fluticasone propionate', 'Al esraa pharmaceutical optima', 'Spray', 'بخاخ', 'مضاد للحساسية ويستخدم للتخفيف من أعراض التهاب الأنف التحسسي.', 'Antihistamine.mast cell stabilizer plus corticosteroid', '50 mcg', 'description: azelastine a phthalazine derivative is an antihistamine and mast cell stabilizer available as a nasal spray for hay fever and as eye drops for allergic conjunctivitis. indication : for the symptomatic treatment of seasonal allergic rhinitis a', '6223004161155', '', 9646, '2024-10-28', CURRENT_TIMESTAMP),
(11380, 'Canolife 10 h.g cap', 'كانولايف 10 كبسولات جيلاتينية صلبة', '', '180', 'Lactoferrin 100 mg+vitamin c 40 mg', 'Pharma zad > cantreat company', 'Cap', 'كبسولة', '', '', '', '', '', '', 4041, '2024-05-29', CURRENT_TIMESTAMP),
(14862, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 719, '2022-09-18', CURRENT_TIMESTAMP),
(21752, 'Levocarnine 10gm/100ml oral sol. 120 ml', 'ليفوكارنين 10جم/100مل محلول بالفم 120 مل', '', '32', 'L-carnitine', 'Future pharmaceutical industries (fpi)', 'Sol', 'محلول', '', 'Antioxidant', '10gm', 'about l-carnitine dietary supplement amino acid derivative antioxidant. mechanism of action of l-carnitine carnitine is an essential co-factor of fatty acid metabolism in the heart liver and skeletal muscle. it is normally synthesised in the liver brain a', '6223004197062', '', 1257, '2022-03-28', CURRENT_TIMESTAMP),
(394, 'Allergyl 2mg/5ml syrup 120ml', 'الليرجيل 2مجم/5مل شراب 120 مل', '17.5', '26', 'Chlorpheniramine', 'Arab drug company.', 'Syrup', 'شراب', '', 'Antihistamine.antiallergy', '2mg', 'For the treatment of rhinitis, urticaria, allergy, common cold, asthma and hay fever.', '6221060001125', '', 8349, '2024-10-28', CURRENT_TIMESTAMP),
(3653, 'Diet-sweet 50 tabs', 'دايت-سويت 50 قرص', '15', '23', 'Aspartame', 'Amriya', 'Tab', 'أقراص', 'سكر محلي صناعي', 'Sweetener', '', 'Used as a diet supplement and sugar substitute.', '6221075010105', '', 2611, '2024-03-20', CURRENT_TIMESTAMP),
(23503, 'Neuth restorative system anti-aging eye cream 18 ml', 'نيوث لعلاج اثار التقدم في السن كريم 18مل', '', '320', 'Coming soon..', 'Neuth > eva pharma', 'Cream', 'كريم', '', 'Eye contour', '18 ml', '', '', '', 687, '2022-07-12', CURRENT_TIMESTAMP),
(10073, 'Aaa', 'ششش', '', '17', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 856, '2022-08-12', CURRENT_TIMESTAMP),
(20224, 'Hairvogine thickening shampoo 200 ml', 'هيرفوجين شامبو لتكثيف الشعر 200 مل', '', '150', 'Caffeine', 'Mash premiere', 'Amp', 'أمبول', '', 'Hair care', '200 ml', 'Caffeine is indicated for the short term treatment of apnea of prematurity in infants and off label for the prevention and treatment of bronchopulmonary dysplasia caused by premature birth.[T716,L9851] In addition, it is indicated in combination with sodium benzoate to treat respiratory depression resulting from an overdose with CNS depressant drugs.[L9899] Caffeine has a broad range of over the counter uses, and is found in energy supplements, athletic enhancement products, pain relief products, as well as cosmetic products.[T716,L9854,L9872]', '', '', 1118, '2022-07-16', CURRENT_TIMESTAMP),
(617, 'Amosar 25mg 20 f.c.tab.', 'اموسار 25مجم 20 قرص', '', '29', 'Losartan potassium', 'Amoun', 'Tab', 'أقراص', '', 'Antihypertensive.angiotensin blocker', '25mg', 'Losartan is indicated to treat hypertension in patients older than 6 years, reduce the risk of stroke in patients with hypertension and left ventricular hypertrophy (though this benefit may not extend to patients with African heritage), and to treat diabetic nephropathy with elevated serum creatinine and proteinuria in patients with type 2 diabetes and hypertension.[L7423] Losartan with hydrochlorothiazide is indicated to treat hypertension and to reduce the risk of stroke in patients with hypertension and left ventricular hypertrophy (though this benefit may not extend to patients with African heritage).[L7426,L45663]', '6221025016263', '', 1032, '2022-12-09', CURRENT_TIMESTAMP),
(31849, 'Redand 14 sachets', 'ريداند 14 كيس', '', '120', 'Iron+lactoferrin+colostrum', 'Premier international pharmaceutical > integra pharm', 'Sachet', 'أكياس', 'مكمل غذائى لعلاج الانيميا وتحسين الجهاز المناعى للجسم', 'Dietary supplement', '', '', '6224009369386', '', 1701, '2023-03-07', CURRENT_TIMESTAMP),
(6498, 'Tanatouch 15 gm ointment', 'تانا تاتش مرهم 15 جم', '', '49', 'B-sitosterol+aloe vera+tea tree oil+bees wax+natural oils', 'Tana pharma', 'Ointment', 'مرهم', '', 'Rejuvenating and moisturizing skin ointment', '15 gm', '', '', '', 811, '2025-08-06', CURRENT_TIMESTAMP),
(9086, 'Lipicontrol 10/10mg 20 tabs', 'ليبيكونترول 10/10مجم 20 قرص', '', '102', 'Atorvastatin+ezetimibe', 'Andalous pharma', 'Tab', 'أقراص', '', 'Antihyperlipidemic.cholesterol absorption inhibitors.combined with statin', '10mg', '', '', '', 1141, '2024-07-01', CURRENT_TIMESTAMP),
(33680, 'Starville facial cleanser gel for acne 400 ml', 'ستارفيل جل منظف للوجه لحب الشباب 400 مل', '180', '210', 'Lauryl glucoside+sulphur+salicylic acid+licorice extract+aloe vera extract+panthenol+allantoin', 'Parkville', 'Gel', 'جل', '', 'Skin care.acne', '400 ml', '', '6224010337909', '', 999, '2024-03-31', CURRENT_TIMESTAMP),
(3402, 'Delzosin 500mg 3 f.c. tabs.', 'دلزوسين 500 مجم 3 قرص', '', '48', 'Azithromycin', 'Delta pharma', 'Tab', 'أقراص', 'مضاد حيوي', 'Antibiotic.macrolide', '500mg', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '6221163010147', '', 4018, '2022-12-04', CURRENT_TIMESTAMP),
(21220, 'Kadomet 250mg 30 tab', 'كادوميت 250 مجم 30 قرص', '', '20', 'Methyldopa', 'Kahira', 'Tab', 'أقراص', '', 'Antihypertensives.centeral alpha 2 agonist', '250mg', 'Methyldopa is indicated for the management of hypertension as monotherapy [L32614] or in combination with hydrochlorothiazide.[L32619] Methyldopa injection is used to manage hypertensive crises.[L32624]', '6221068924525', '', 729, '2022-12-06', CURRENT_TIMESTAMP),
(17234, 'Delvena 100mg 10 tab', 'دلفينا 100 مجم 10 اقراص', '', '45', 'Venlafaxine', 'Delta pharma', 'Tab', 'أقراص', '', 'Psychiatric.antidepressants', '100mg', 'Venlafaxine is indicated for the management of major depressive disorder (MDD), generalized anxiety disorder (GAD), social anxiety disorder (SAD), and panic disorder.[L43030]', '', '', 881, '2022-07-15', CURRENT_TIMESTAMP),
(11629, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 902, '2023-07-19', CURRENT_TIMESTAMP),
(27016, 'Aaa', 'ششش', '', '66', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 623, '2022-08-02', CURRENT_TIMESTAMP),
(10098, 'Adrien gagnon digest 365 30 caps', 'ادرين جانون دايجست 365 30 كبسولة', '', '590', '', 'Company', 'Cap', 'كبسولة', '', '', '', '', '', '', 786, '2024-05-27', CURRENT_TIMESTAMP),
(31069, 'Panthenol novex cream 50 gm', 'بانثينول نوفكس كريم 50 جم', '29', '35', 'Panthenol', 'Novex', 'Cream', 'كريم', '', 'Moisturizing topical', '50 gm', 'Panthenol (containing a racemic mixture of dexpanthenol and levopanthenol) is not currently available in any FDA-approved products and therefore does not have an indication.
Please see [DB09357] for FDA-approved uses of the dextrorotatory form of Panthenol.', '6221088000346', '', 1549, '2024-02-08', CURRENT_TIMESTAMP),
(15136, 'Napizole 40mg 14 caps.', 'نابيزول 40مجم 14 كبسولة', '41.5', '62', 'Omeprazole', 'Global napi pharmaceuticals', 'Cap', 'كبسولة', '', 'Peptic ulcer.proton pump inhibitor', '40mg', 'Omeprazole, according to the FDA label [FDA label] is a proton pump inhibitor (PPI) used for the following purposes:
• Treatment of active duodenal ulcer in adults 
• Eradication of Helicobacter pylori to reduce the risk of duodenal ulcer
recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6223002144693', '', 2721, '2024-07-07', CURRENT_TIMESTAMP),
(2465, 'Cevarol 500mg 20 tab.', 'سيفارول 500مجم 20 قرص', '8', '12', 'Vitamin c', 'Memphis', 'Tab', 'أقراص', 'فيتامين ج', 'Vitamin c', '500mg', 'For the treatment of vitamin A deficiency.', '6221050030715', '', 2986, '2024-11-17', CURRENT_TIMESTAMP),
(13117, 'Alfamash 30 e.c. tabs.', 'الفاماش 30 قرص', '135', '165', 'Trypsin+bromelain+rutin', 'Mash premiere', 'Tab', 'أقراص', '', 'Enzyme replacement therapy', '', '', '6222001402780', '', 1763, '2024-05-24', CURRENT_TIMESTAMP),
