recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '6221025004666', '', 961, '2022-12-05', CURRENT_TIMESTAMP),
(13597, 'Ajirofil anti-dandruff shampoo 125 ml', 'اجيروفيل شامبو ضد القشرة 125 مل', '', '80', '', '> vitalita', 'Amp', 'أمبول', '', 'Hair care', '125 ml', '', '', '', 918, '2022-08-05', CURRENT_TIMESTAMP),
(25536, 'Quemar cream 40 gm', 'كويمار كريم 40جم', '', '52', 'Calendula+jojoba+aloe vera+panthenol+propolis+sesame oil+honey', 'Hi-care > vortex pharmaceuticals', 'Cream', 'كريم', '', 'Skin care', '40 gm', '', '', '', 559, '2022-08-04', CURRENT_TIMESTAMP),
(19938, 'Glucose 5% (otsuka) i.v. inf. 500 ml (rubber cap)', 'جلوكوز 5% اوتوسوكا محلول وريدي 500 مل غطاء مطاط', '', '18', 'Glucose (dextrose)', 'Otsuka', 'Cap', 'كبسولة', '', 'Antihypoglycemic', '5%', '', '6225000471627', '', 790, '2022-07-12', CURRENT_TIMESTAMP),
(6313, 'Kansotib 1000 mg/26.3 ml conc. soln. for i.v. inf. vial', 'كانسوتيب 1000مجم/26.3 مل محلول مركز فيال وريد', '', '1,019', 'Gemcitabine', 'Sedico', 'Vial', 'فيال', '', 'Antineoplastic', '1000 mg', 'Gemcitabine is a chemotherapeutic agent used as monotherapy or in combination with other anticancer agents. 
In combination with [carboplatin], it is indicated for the treatment of advanced ovarian cancer that has relapsed at least 6 months after completion of platinum-based therapy.[L32950]
Gemcitabine in combination with [paclitaxel] is indicated for the first-line treatment of patients with metastatic breast cancer after failure of prior anthracycline-containing adjuvant chemotherapy, unless anthracyclines were clinically contraindicated.[L32950]
In combination with [cisplatin], gemcitabine is indicated for the first-line treatment of patients with inoperable, locally advanced (Stage IIIA or IIIB) or metastatic (Stage IV) non-small cell lung cancer (NSCLC).[L32950] Dual therapy with cisplatin is also used to treat patients with Stage IV (locally advanced or metastatic) transitional cell carcinoma (TCC) of the bladder.[L32955]
Gemcitabine is indicated as first-line treatment for patients with locally advanced (nonresectable Stage II or Stage III) or metastatic (Stage IV) adenocarcinoma of the pancreas. Gemcitabine is indicated for patients previously treated with [fluorouracil].[L32950]', '', '', 739, '2025-07-28', CURRENT_TIMESTAMP),
(28676, 'Ultracaine 20mg/ml vial 50 ml', 'التراكايين 20مجم/مل فيال 50 مل', '', '13', 'Lidocaine', 'Memphis', 'Vial', 'فيال', '', 'Analgesic.local anesthetic', '20mg', 'Lidocaine is an anesthetic of the amide group indicated for production of local or regional anesthesia by infiltration techniques such as percutaneous injection and intravenous regional anesthesia by peripheral nerve block techniques such as brachial plexus and intercostal and by central neural techniques such as lumbar and caudal epidural blocks [F4349, L5930].', '', '', 1109, '2022-06-15', CURRENT_TIMESTAMP),
(27467, 'Starlight face cream 50 gm', 'ستارلايت كريم للوجه 50 جم', '', '40', '', 'Sigma > pharma clinic co.', 'Cream', 'كريم', 'كريم تفتيح', 'Whitening topical', '50 gm', 'whitening cream', '', '', 988, '2022-12-03', CURRENT_TIMESTAMP),
(25502, 'Purified water 100% sachet', 'اكياس مياه', '', '2', 'Purified water', 'Pharmapack pharmaceutical co.', 'Sachet', 'أكياس', '', 'Purified water', '100%', 'purified water water obtained by distillation or deionization.', '', '', 675, '2022-08-03', CURRENT_TIMESTAMP),
(6768, 'Avantosis 10 ml oral drops', 'افانتوسيس نقط فم 10 مل', '', '90', '400 iu vit d 20 mg dha & 2 mg vit e / 4 drops', 'Avantgarde pharma', 'Drops', 'نقط', '', '400 iu vit d 20 mg dha & 2 mg vit e / 4 drops', '10 ml', '', '', '', 2339, '2024-05-21', CURRENT_TIMESTAMP),
(25727, 'Rasiroxpine 125mg 28 disp. tabs.', 'رازيروكسبين 125مجم 28 اقراص', '', '750', 'Deferasirox', 'Hikma specialized pharmaceuticals', 'Tab', 'أقراص', '', 'Iron chelating agents', '125mg', 'For the treatment of chronic iron overload due to blood transfusions (transfusional hemosiderosis) in patients 2 years of age and older.', '', '', 764, '2022-07-25', CURRENT_TIMESTAMP),
(2630, 'Ciprocin 10mg/ml (40ml) vial', 'سيبروسين 10مجم/مل 40 مل فيال', '', '22', 'Ciprofloxacin', 'Eipico', 'Vial', 'فيال', '', 'Antibiotic.quinolone', '10mg', 'Ciprofloxacin is only indicated in infections caused by susceptible bacteria.[L6469,L6472,L6475,L6478,L6481,L6484,L6487,L6490,L6493]
Ciprofloxacin immediate release tablets, oral suspensions, and intravenous injections are indicated for the treatment of skin and skin structure infections, bone and joint infections, complicated intra-abdominal infections, nosocomial pneumonia, febrile neutropenia, adults who have inhaled anthrax, plague, chronic bacterial prostatitis, lower respiratory tract infections including acute exacerbations of chronic bronchitis, urinary tract infections, complicated urinary tract infections in pediatrics, complicated pyelonephritis in pediatrics, and acute sinusitis.[L6481,L6478]
A ciprofloxacin otic solution and otic suspension with hydrocortisone are indicated for acute otitis externa.[L6469,L6484] Ciprofloxacin suspension with dexamethasone is indicated for acute otitis media in pediatric patients with tympanostomy tubes or acute otitis externa.[L6490] A ciprofloxacin intratympanic injection is indicated for pediatric patients with bilateral otitis media with effusion who are having tympanostomy tubes placed or pediatric patients 6 months or older with acute otitis externa.[L6493]
A ciprofloxacin eye drop is indicated for bacterial corneal ulcers and conjunctivitis.[L6472] A ciprofloxacin eye ointment is indicated for bacterial conjunctivitis.[L6475]
A ciprofloxacin extended release tablet is indicated for uncomplicated urinary tract infections, complicated urinary tract infections, and acute uncomplicated pyelonephritis.[L6487]', '', '', 1217, '2022-07-26', CURRENT_TIMESTAMP),
(30574, 'Futacoxib 90 mg 30 f.c.tabs.', 'فيوتاكوكسيب 90مجم 30 قرص', '207', '297', 'Etoricoxib', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', 'مسكن قوي ومضاد التهاب', 'Nsaid.selective cox-2 inhibitors', '90 mg', 'For the treatment of rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, chronic low back pain, acute pain and gout.', '6223003971175', '', 35002, '2024-10-07', CURRENT_TIMESTAMP),
(26148, 'Ringer lactate (compound sodium lactate) (el nile) i.v. inf. 500 ml (rubber cap)', 'رينجر لاكتات (مركب صوديوم لاكتات) النيل محلول وريدي 500 مل بغطاء مطاطي', '', '11', 'Calcium chloride+potassium chloride+sodium chloride', 'El nile', 'Cap', 'كبسولة', '', 'Ringer', '500 ml', 'Calcium acetate is one of a number of calcium salts used to treat hyperphosphatemia (too much phosphate in the blood) in patients with kidney disease.', '', '', 844, '2022-07-09', CURRENT_TIMESTAMP),
(23227, 'Nalpain 20mg/ml 5 amp.', 'نالبين 20مجم/مل 5 امبول', '37.25', '60', 'Nalbuphine', 'Alfacure pharmaceuticals', 'Amp', 'أمبول', '', 'Analgesics.opioid', '20mg', 'For the relief of moderate to severe pain.', '', '', 893, '2025-08-23', CURRENT_TIMESTAMP),
(26314, 'Rostatine 20mg 30 f.c.tab.', 'روزتاتين 20مجم 30 قرص', '', '72', 'Atorvastatin', 'Adwia', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '20mg', 'Atorvastatin is indicated for the treatment of several types of dyslipidemias, including primary hyperlipidemia and mixed dyslipidemia in adults, hypertriglyceridemia, primary dysbetalipoproteinemia, homozygous familial hypercholesterolemia, and heterozygous familial hypercholesterolemia in adolescent patients with failed dietary modifications.[A177397]
Dyslipidemia describes an elevation of plasma cholesterol, triglycerides or both as well as to the presence of low levels of high-density lipoprotein. This condition represents an increased risk for the development of atherosclerosis.[L6025] 
Atorvastatin is indicated, in combination with dietary modifications, to prevent cardiovascular events in patients with cardiac risk factors and/or abnormal lipid profiles.[A177397]
Atorvastatin can be used as a preventive agent for myocardial infarction, stroke, revascularization, and angina, in patients without coronary heart disease but with multiple risk factors and in patients with type 2 diabetes without coronary heart disease but multiple risk factors.[A177397]
Atorvastatin may be used as a preventive agent for non-fatal myocardial infarction, fatal and non-fatal stroke, revascularization procedures, hospitalization for congestive heart failure and angina in patients with coronary heart disease.[A177397]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '', '', 1101, '2022-07-25', CURRENT_TIMESTAMP),
(11542, 'Starvid oral drops 15 ml', 'ستارفيد نقط فم 15 مل', '46', '52', 'Vitamin d', 'Mpco', 'Drops', 'نقط', '', 'Vitamin d', '15 ml', 'Vitamin D is indicated for use in the treatment of hypoparathyroidism, refractory rickets (also known as vitamin D resistant rickets), and familial hypophosphatemia [FDA Label].', '', '', 1113, '2025-08-04', CURRENT_TIMESTAMP),
(28940, 'Valsarcard comb 160/12.5mg 30 f.c. tabs.', 'فالزاركارد كومب 160/12.5مجم 30 قرص', '', '63', 'Hydrochlorothiazide+valsartan', 'Mash premiere > queen pharma international', 'Tab', 'أقراص', '', 'Antihypertensive. combined angiotensin blocker with diuretic', '12.5mg', '', '', '', 778, '2022-08-12', CURRENT_TIMESTAMP),
(29503, 'Vitamin d-3 - 2000 i.u. 120 softgels (now)', 'فيتامين دال3 - 2000 وحدة دولية 120 كبسولة', '600', '999', 'Vitamin d3', 'Puritans pride', 'Gel', 'جل', '', 'Vitamin d', '', 'For the treatment of vitamin A deficiency.', '', '', 1053, '2025-09-22', CURRENT_TIMESTAMP),
(32486, 'Baby relief 12.5 mg 10 supp.', 'بيبي ريليف 12.5 مجم 10 لبوس', '24', '36', 'Diclofenac sodium', 'Pharopharma', 'Supp', 'لبوس', '', 'Nsaid.acetic acid derivatives', '12.5 mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6221094000682', '', 1584, '2024-08-09', CURRENT_TIMESTAMP),
(30785, 'Lactoferroz plus 20 caps.', 'لاكتوفريروز بلس 20 كبسولة', '220', '240', 'Bovin lactoferrin 250mg+zinc 15mg+selenium 55mcg+vitamin b6 10mg', 'Amcomed > tesla pharmaceuticals', 'Cap', 'كبسولة', 'مكمل غذائى يعالج حالات الانيميا ويحسن من مناعة الجسم ويدعم الجهاز العصبي ويعزز الطاقة', 'Anemia+iron supplements+immunity for covid-19 virus', '', 'used for armenia to elevate hemoglobin immunity for covid-19 virus (coronavirus) dose: once daily', '', '', 1961, '2025-08-13', CURRENT_TIMESTAMP),
(20495, 'Himax massage gel 30 gm', 'هاي ماكس مساج جل 30 جرام', '42', '55', 'Menthol+eucalyptus+camphor+methyl salicylate', 'Hi-care > roventis pharma', 'Gel', 'جل', 'لعلاج آلام العظام والروماتيزم والتهابات المفاصل.', 'Massage.topical analgesic.muscle', '30 gm', '*** indications ï- low back pain. ï- sciatica. ï- lumbago. ï- torticollis. ï- arthrosis: cervical arthrosis &gonarthrosis. ï- sprains and strains. ï- tendinitis. ï- epicondylitis. ï- inflammation and discomfort in arthritis. ***directions for use to be ap', '', '', 4087, '2025-05-21', CURRENT_TIMESTAMP),
(2912, 'Sinsa 20 tablets', 'سينسا 20 قرص', '', '85', 'Zinc+selenium', 'Global smith', 'Tablet', 'أقراص', '', 'Dietary supplement', '', '', '', '', 1027, '2025-02-11', CURRENT_TIMESTAMP),
(26771, 'Sensajoy acne cream 50 gm', 'سينساجوي كريم لحب الشباب 50 جم', '120', '145', '', 'Egyptian co. for cosmetics > orchidia pharmaceutical industries', 'Cream', 'كريم', 'علاج حب الشباب', 'Skin care', '50 gm', 'sensajoy is an innovative formula with an intensive blend of skin purifying ingredients that work synergically to solve oily and acne prone skin problems. it regulates sebum secretion for a shine free skin removes dead skin cells and refines wide pores. d', '', '', 1843, '2023-11-20', CURRENT_TIMESTAMP),
(29439, 'Aaa', 'ششش', '', '40', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 672, '2022-08-06', CURRENT_TIMESTAMP),
(24245, 'Orencia 125 mg soln. s.c. pre-filled syringe (n/a)', 'اورينشيا 125مجم سرنجات معبئة مسبقا', '', '2,658', 'Abatacept', 'Bristol-myers squibb > united company for trading & distribution', 'Syringe', 'حقنة', '', 'Selective t cell costimulation modulator', '125 mg', 'Abatacept is indicated in adult patients for the treatment of moderately-to-severely active rheumatoid arthritis and in patients ≥2 years of age for the treatment of active psoriatic arthritis.[L48811] In patients two years of age and older, abatacept is also indicated for the treatment of moderately-to-severely active juvenile idiopathic arthritis.[L20504]
Abatacept is also indicated for the prophylaxis of acute graft-versus-host disease, in combination with [methotrexate] and a calcineurin inhibitor such as [tacrolimus], in patients two years of age and older who are undergoing hematopoietic stem cell transplantation from a matched or 1 allele-mismatched unrelated donor.[L20504]', '', '', 1122, '2022-07-08', CURRENT_TIMESTAMP),
(33682, 'Starville micellar water 100 ml', 'ستارفيل ميسيلار ووتر 100 مل', '60', '75', '', 'Parkville', 'Unknown', 'غير محدد', '', 'Skin care', '100 ml', '', '', '', 625, '2025-07-29', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
