(29219, 'Aaa', 'ششش', '630', '990', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 694, '2023-11-19', CURRENT_TIMESTAMP),
(10636, 'Aaa', 'ششش', '', '3', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 573, '2022-06-02', CURRENT_TIMESTAMP),
(18128, 'Egyresolve 250mg soft gelatin 10capsules', 'ايجي ريسولف 250 مجم 10 كبسولات', '', '9', 'Ursodeoxycholic acid', 'Medizen pharmaceutical industries > egygel pharma for pharmaceutical industries-egypt', 'Capsule', 'كبسولة', '', 'Liver support supplements', '250mg', 'Ursodeoxycholic acid is indicated for the treatment of patients with primary biliary cholangitis.[L44627] 
It is used for the short-term treatment of radiolucent, noncalcified gallbladder stones in patients selected for elective cholecystectomy. It is also used to prevent gallstone formation in obese patients experiencing rapid weight loss.[L44793]', '', '', 1065, '2022-07-26', CURRENT_TIMESTAMP),
(29887, 'Zerit 40 mg 60 caps.', 'زيرت 40مجم 60 كبسول', '', '1,350', 'Stavudine', 'Bristol-myers squibb', 'Cap', 'كبسولة', '', 'Antiviral.nucleoside', '40 mg', 'For the treatment of human immunovirus (HIV) infections.', '', '', 662, '2022-08-04', CURRENT_TIMESTAMP),
(17689, 'Diosmin 600mg 30 f.c.tab.', 'ديوزمين 600مجم 30 قرص', '', '33', 'Diosmin', 'Marcyrl co.', 'Tab', 'أقراص', 'يعمل على حماية الأوعية الدموية', 'Vascular-protecting agent', '600mg', 'Diosmin is used over-the-counter alone or with ingredients such as [hesperidin] and [diosmetin] to support vein and capillary function.[L32823,L32848]', '6223003579678', '', 1754, '2022-12-04', CURRENT_TIMESTAMP),
(18729, 'Extrauma dna forte topical gel 25 gm', 'اكستروما دى ان اي فورت جل 25 جم', '27', '41', 'Hirudin', 'Mina pharm', 'Gel', 'جل', '1- علاج الكدمات والتجمعات الدموية.', 'Anti-inflammatory', '25 gm', 'indication : contusions distortions muscular tears traumatic hematomas edema erythema varicositis periphlebitis and anal periphlebitis with hemorrhoids. dose : dispense 2-3 cm of gel two ï¿½ three times per day and carry out a light massage until complete', '6222003701959', '', 5613, '2024-08-28', CURRENT_TIMESTAMP),
(4065, 'Menorosa 1000 mg 20 caps', 'مينوروزا 1000مجم 20 كبسولة', '170', '185', 'Evening primrose oil+vitamin e', 'Vitocare pharmaceutical', 'Cap', 'كبسولة', '', 'Pms menopause mastalgia', '1000 mg', 'Evening primrose oil is used as part of over-the-counter dietary supplements.[L1113]
It is also used for the treatment of systemic inflammatory diseases and for women''s health conditions such as cyclical mastalgia. These indications do not have sufficient evidence of their effectiveness. It was used for the treatment of atopic dermatitis in the United Kingdom but it is currently withdrawn due to lack of evidence of effectiveness.[A33131]', '', '', 901, '2025-06-23', CURRENT_TIMESTAMP),
(13887, 'Amaglust 4/30 mg 30 scored tab', 'اماجلوست 4/30مجم 30 قرص', '73.5', '102', 'Glimepiride+pioglitazone', 'Eva pharma > next pharma', 'Tab', 'أقراص', '', 'Anti-diabetic.combined secretagogues+sensitizers', '30 mg', '', '6223004519833', '', 3269, '2024-06-12', CURRENT_TIMESTAMP),
(28278, 'Tono (chocolate) 20 pieces', 'تونو 20 قطعة', '', '40', 'Vitamins+minerals', 'Nutrixia > violine', 'Piece', 'قطعة', '', 'Multivitamins', '', '** ingredients: iron 9 mg + selenium 35 mcg + zinc 7.5 mg + copper 1 mg + iodine 75 mcg + vitamin a 2500 mg + vit. b1 0.75 mg + vit. b2 0.85 mg + vit. b3 10 mg + vit. b5 5 mg + vit. b6 6 mg + biotin 150 mcg + vit. c 30 mg + vit. b12 300 mcg + folate 200 m', '', '', 835, '2022-07-19', CURRENT_TIMESTAMP),
(28219, 'Tiralepsy xr 500mg 20 f.c.tab.', 'تيراليبسي اكس ار 500مجم 20 اقراص', '114', '129', 'Levetiracetam', 'El-obour > protech pharma', 'Tab', 'أقراص', '', 'Anti-epileptic.pyrrolidine', '500mg', 'Levetiracetam is indicated as an adjunctive therapy in the treatment of partial onset seizures in epileptic patients who are one month of age and older. Additionally, it is indicated as an adjunct in the treatment of myoclonic seizures in patients with juvenile myoclonic epilepsy who are 12 years of age and older, and in primary generalized tonic-clonic seizures in patients with idiopathic generalized epilepsy who are 6 years of age and older.[L8606]
Levetiracetam is also available as an orally dissolvable tablet that is indicated as an adjunct in the treatment of partial onset seizures in patients with epilepsy who are 4 years of age and older and weigh more than 20kg.[L8609]', '6224000866426', '', 1531, '2024-07-20', CURRENT_TIMESTAMP),
(25286, 'Probric 20 mg 10 tab.', 'بروبريك 20مجم 10 قرص', '', '27', 'Bambuterol', 'Borg', 'Tab', 'أقراص', '', 'Bronchodilator.long acting beta 2 agonist', '20 mg', 'For the prevention and reversal of bronchospasm in patients 12 years of age and older with asthma and reversible bronchospasm associated with bronchitis and emphysema.', '6223002570744', '', 1134, '2022-07-11', CURRENT_TIMESTAMP),
(31486, 'Tibolian 2.5mg 28 tab', 'تيبوليان 2.5مجم 28 قرص', '62', '83', 'Tibolone', 'Cid', 'Tab', 'أقراص', '', 'Hormone replacement therapy (hrt)', '2.5mg', 'For the relief of post-menopausal symptoms and for the prevention of osteoporosis [L1724].', '', '', 1024, '2025-04-20', CURRENT_TIMESTAMP),
(19405, 'Fresh way spray topical spray.', 'فريش واي بخاخ موضعي', '', '20', 'Chloroxylenol+undecylenic acid', 'Egyptian co. for adv. pharma. (ecap) > millenium pharma-egypt', 'Spray', 'بخاخ', '', '', '', '', '', '', 862, '2022-07-27', CURRENT_TIMESTAMP),
(25231, 'Prilatop 5 mg 10 f.c. tabs.', 'بريلاتوب 5مجم 10 اقراص', '', '25', 'Cilazapril', 'Eva pharma > horus for pharmaceutical products', 'Tab', 'أقراص', '', 'Antihypertensive.ace', '5 mg', 'Cilazapril is an ACE inhibtor class drug used in the treatment of hypertension and heart failure.', '', '', 647, '2022-07-20', CURRENT_TIMESTAMP),
(4024, 'Sunlamotri 25 mg 30 disp./chew. tabs.', 'سانلاموتري 25مجم 30 قرص مضغ', '', '57', 'Lamotrigine', 'Sun pharmaceutical industries ltd.', 'Tab', 'أقراص', '', 'Anti-epileptic.triazine', '25 mg', 'Lamotrigine is indicated as adjunctive therapy for the following seizure types in patients ≥2 years of age: partial seizures, primary generalized tonic-clonic seizures, and generalized seizures due to Lennox-Gastaut syndrome.[L9404]
It is also indicated for the process of conversion to drug monotherapy for those at least 16 years of age or older with partial seizures and currently are receiving treatment with carbamazepine, phenytoin, phenobarbital, primidone, or valproate as the single antiepileptic drug (AED).[L9404]
In addition to the above, lamotrigine is also indicated for the maintenance treatment of bipolar I disorder, delaying the time to mood episodes (which may include mania, hypomania, depression, mixed episodes) in adults at least 18 years or older, who have been treated for acute mood symptoms with standard therapy.[L9404]
Limitations of use
It is important to note that lamotirigine should not be used in the treatment of acute mood episodes, as efficacy has not been established in this context.[L9404]', '', '', 742, '2025-06-03', CURRENT_TIMESTAMP),
(14271, 'Anviziram 200 mg 40 f.c.tabs.', 'انفيزيرام 200 مجم 40 قرص', '112', '320', 'Favipiravir', 'Rameda', 'Tab', 'أقراص', 'مضاد للفيروسات اثناء العمليات الجراحية وبعدها', 'Antiviral', '200 mg', 'In 2014, favipiravir was approved in Japan to treat cases of influenza that were unresponsive to conventional treatment.[A191721] Given its efficacy at targetting several strains of influenza, it has been investigated in other countries to treat novel viruses including Ebola and most recently, COVID-19.[A191688,A191724,L12012]', '', '', 2412, '2023-12-16', CURRENT_TIMESTAMP),
(2508, 'Jarvis mist spray 30 ml', 'جارفيس سبراي 30 مل', '', '85', '', 'G mark', 'Spray', 'بخاخ', '', 'Soothing.moisturizing', '30 ml', '', '', '', 822, '2025-01-21', CURRENT_TIMESTAMP),
(6654, 'Hadidos 30 capsule', 'حديدوس 30 كبسولة', '', '135', 'Iron+vit b6+vit 12+vit c+folic acid', 'Artilife health', 'Capsule', 'كبسولة', '', 'Multivitamin', '', '', '', '', 2630, '2025-08-11', CURRENT_TIMESTAMP),
(16342, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 646, '2022-08-08', CURRENT_TIMESTAMP),
(32324, 'Mavilor plus 5/12.5 mg 30 tabs.', 'مافيلور بلس 5/12.5مجم 30 قرص', '78', '108', 'Nebivolol hydrochloride+hydrochlorothiazide', 'Multi-apex', 'Tab', 'أقراص', 'علاج مرض ارتفاع ضغط الدم', 'Anti-hypertensive.combined beta blocker with diuretic', '12.5 mg', 'Nebivolol is indicated to treat hypertension.[A2762,A182579,L7985,L7988]', '6223003207373', '', 2368, '2024-09-18', CURRENT_TIMESTAMP),
(13872, 'Alzental 200mg 6 f.c. tab.', 'الزنتال 200مجم 6 اقراص', '19.5', '33', 'Albendazole', 'Eipico', 'Tab', 'أقراص', '1- علاج طارد للديدان للتخلص من ديدان البطن.', 'Anthelmintic', '200mg', 'For the treatment of parenchymal neurocysticercosis due to active lesions caused by larval forms of the pork tapeworm, <i>Taenia solium</i> and for the treatment of cystic hydatid disease of the liver, lung, and peritoneum, caused by the larval form of the dog tapeworm, <i>Echinococcus granulosus</i>.', '6221032118141', '', 1926, '2024-08-14', CURRENT_TIMESTAMP),
(28946, 'Aaa', 'ششش', '', '69', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 752, '2022-12-14', CURRENT_TIMESTAMP),
(17038, 'Cytoplatin 50mg/50ml vial', 'سيتوبلاتين 50 مجم/ 50 مل فيال', '82.5', '316', 'Cisplatin', 'Cipla ltd. - india > star international company', 'Vial', 'فيال', '', 'Antineoplastic', '50mg', 'For the treatment of metastatic testicular tumors, metastatic ovarian tumors and advanced bladder cancer.', '', '', 926, '2025-04-20', CURRENT_TIMESTAMP),
(8176, 'Milga 40 tablets', 'ميلجا 40 قرص', '68', '108', 'Benfotiamine+cyanocobalamine+pyridoxine', 'Eva pharma', 'Tablet', 'أقراص', 'منشط عام للجسم خاصة الذاكرة والتركيز.-- حالات الإرهاق العصبي المزمن.-- مسكن لآلام الأعصاب ومقوي للجهاز العصبي.-- بديل لحقن الأعصاب بنفس الفعالية.-- تكوين وتقوية كرات الدم الحمراء.-- حالات الأنيميا و الضعف العام وفقدان الطاقة.-- علاج التهاب الأعصاب خصوصا لمرضى السكر.-- دعم كفاءة وظائف الأعصاب.-- تعويض نقص فيتامين ب.-- حالات رعشة واهتزاز اليدين ورفة العين.فيتامين ب مركب - مقوي للأعصاب-- أهمية فيتامين ب المركب للجسم-- بنفوتيامينهو أحد مشتقات الثيامين “فيتامين ب1” – “Thiamine” والذي يتميز بسرعة امتصاصه، وقدرته على تخفيف آلام الأعصاب الطرفية وتقويتها خاصة في مرضى السكري. كما أنه يلعب دوراً هاماً في تنظيم عمليات التمثيل الغذائي في الجسم.-- فيتامين ب6 “بيريدوكسين”-- ينشط تكوين كريات الدم الحمراء. -- يساعد في تمثيل المواد الغذائية المختلفة مثل الأحماض الأمينية والكربوهيدرات والدهون. -- يساعد المخ والجهاز العصبي على القيام بوظيفتهما الطبيعية.-- يدخل في العديد من الوظائف الحيوية بالجسم. -- فيتامين ب12 “سيانوكوبالامين”--فيتامين ب 12 من أهم الفيتامينات التي يحتاجها الجسم، وعندما يقل تركيزه في الدم يسبب حالة مرضية تسمى “الأنيميا الخبيثة”. ويتواجد فيتامين ب12 في الصيدلية كمادة مستقلة على هيئة حقن ممتدة المفعول مثل ديبوفيت وبيوفيت، وأقراص تحت اللسان مثل دلتافيت أقراص، وكبسولات مثل أورافيت كبسول، وحديثا تم إنتاجه على هيئة فيلم يوضع على اللسان وهو “ميثايلتكنو“.-- كما يتواجد فيتامين ب 12 في الكثير من المكملات وتركيبات الفيتامينات الخاصة بالأعصاب والمقوية بوجه عام وذلك لما له من فوائد هامة جداً للجسم حيث أنه:-- يساعد في تجديد خلايا الدم الحمراء.--عامل أساسي لسلامة الجهاز العصبي.--يساعد في عمليات التمثيل الغذائي.--يساعد على تقوية جهاز المناعة.--يزيد من قدرة الجسم على القيام بوظائفه عن طريق زيادة طاقته.--دواعي استخدام ميلجا أدفانس--يدعم وظيفة الجهاز العصبي--يدعم كفاءة الأعصاب--تعويض نقص فيتامين ب1 و ب6 وب 12--الفرق بين ميلجا العادي وميلجا أدڨانس--ميلجا أقراص العادية موجود في السوق المصري منذ فترة طويلة ويتميز باحتوائه على مادة بنفوتيامين وهو فيتامين ب 1 جيد الامتصاص، وهو ما يميز ميلجا عن باقي البدائل المتوفرة بالسوق، وتم رفع تركيز هذه المادة من 40 مجم في ميلجا العادي إلى 300 مجم في ميلجا أدفانس ، كما تم رفع تركيز فيتامين ب 6 من 60 مجم إلى 100 مجم، والغرض من رفع التركيزات هو الوصول للاحتياج اليومي المطلوب من هذه المواد وجعلها بديل مناسب للأمبولات التي تعطى عن طريق الحقن.', 'Vitamin b', '', '', '6224009967544', '', 25479, '2024-05-28', CURRENT_TIMESTAMP),
(20784, 'Pirove 30 pieces', 'بيروف 30 قطعة اقراص', '70', '90', 'Iron+folic acid+vitamin c+vitamin b complex', 'Med care > biocare pharma', 'Piece', 'قطعة', 'مكمل غذائي لعلاج حالات الانيميا ونقص الحديد', '', '', 'multivitamins', '', '', 2810, '2024-10-13', CURRENT_TIMESTAMP),
(4434, 'Nephromed advance 14 sachets', 'نيفروميد ادفانس 14 كيس', '300', '375', 'L-histidine+l-isoleucine+l-leucine+l-lysine+l-methionine', 'Biomed pharmaceuticals', 'Sachet', 'أكياس', 'يستخدم في علاج الدوالي', 'Kidney failure', '', '', '', '', 2301, '2024-07-29', CURRENT_TIMESTAMP),
(12539, 'Vitosel 14 sachets', 'فيتوسيل اكياس 14 كيس', '110', '135', 'Lactoferrin+ferrus fumerate+colostrum+vitamins', 'Med care > drug pharma egypt', 'Sachet', 'أكياس', '- مكمل غذائي بالحديد لعلاج الانيميا', 'Iron supplement', '', 'product uses : treatment of irondeficincy anaemia dose : one sachet per day 3 to 6 months according to severity of the care', '', '', 4034, '2024-04-16', CURRENT_TIMESTAMP),
(23984, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 608, '2022-07-22', CURRENT_TIMESTAMP),
(10946, 'Strong (chocolate) 24 pills', 'سترونج 24 قطعة', '', '44', 'Calcium+magnesium+vitamin d3+vitamin e+vitamin c+folic acid', 'Integra pharm', 'Unknown', 'غير محدد', 'فيتامينات متعددة -- مضاد للأكسدة', 'Calcium supplement', '', '1 pill daily', '', '', 785, '2022-10-28', CURRENT_TIMESTAMP),
(16189, 'Aaa', 'ششش', '', '15', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 777, '2022-07-16', CURRENT_TIMESTAMP),
(28081, 'Tetra eye oint. 5 gm', 'تيترا مرهم للعين 5جم', '', '5', 'Oxytetracycline+polymyxin', 'Amoun', 'Oint', 'مرهم', '', 'Antibiotic', '5 gm', 'about oxytetracycline tetracycline derivative a broad spectrum antibiotic. mechanism of action of oxytetracycline oxytetracycline is a broad spectrum antibiotic which has action against both gram positive organisms & gram negative organisms. it exerts its', '', '', 943, '2022-07-28', CURRENT_TIMESTAMP),
(16695, 'Complir 14 sachets', 'كومبلير 14 كيس', '100', '140', 'Lactoferrin+chelated iron', 'Medcare > medicina medical ltd.', 'Sachet', 'أكياس', 'مكمل غذائي غني بالحديد.', 'Iron supplement', '', '', '6225000257931', '', 3964, '2024-04-22', CURRENT_TIMESTAMP),
(23660, 'No more acne cleanser 250 ml', 'نو مور اكني غسول 250 مل', '145', '165', 'Vitamins(a+c+e)+myristic acid+lauric acid+palmitic acid+salicylic acid+panthenol+tea tree oil', 'Italian co. for cosemetics > hexa group', 'Cleanser', 'منظف', 'علاج حب الشباب', 'Anti-acne', '250 ml', 'for oily & acne prone skin. unique new formula gentle on skin. use: apply a small amount to a clean fingertip and gently rub into a damp face then wash with water.', '', '', 2530, '2025-01-22', CURRENT_TIMESTAMP),
(25787, 'Refresh liquigel 1% eye drops 15 ml', 'ريفريش ليكويجل 1% قطرة عين 15 مل', '', '40', 'Sodium carboxymethylcellulose', 'Allergan > soficopharm', 'Gel', 'جل', '', 'Eye lubricant', '1%', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 1825, '2022-07-24', CURRENT_TIMESTAMP),
(26751, 'Selsun blue 118 ml itchy dry scalp shampoo (n/a)', 'سيلسن بلو 118مل شامبو', '', '35', 'Selenium sulfide', 'Famar > ramco', 'Amp', 'أمبول', '', 'Hair care', '118 ml', 'For treatment of tinea versicolor, tinea capitis, dandruff and seborrheic dermatitis of the scalp.', '', '', 706, '2022-07-29', CURRENT_TIMESTAMP),
(19902, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 710, '2022-07-15', CURRENT_TIMESTAMP),
(13054, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 740, '2022-09-22', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(21236, 'Vindo hair serum 100 ml', 'فيندو سيروم للشعر 100 مل', '185', '275', '', 'Linko pharma', 'Serum', 'سيروم', '', 'Hair care', '100 ml', '', '6224008585688', '', 896, '2025-06-28', CURRENT_TIMESTAMP),
(17194, 'Delay-tiazem sr 120 mg 10 caps.', 'ديلاي تيازيم اس ار 120 مجم 10 كبسولات', '', '12', 'Diltiazem', 'Glaxo smithkline', 'Cap', 'كبسولة', 'علاج ارتفاع ضغط الدم', 'Antihypertensive.nonselective calcium channel blocker', '120 mg', '**Oral**
Indicated for the management of hypertension, to lower blood pressure, alone or in combination with other antihypertensive agents.[L10556]
Indicated for use to improve exercise tolerance in patients with chronic stable angina.[L10556]
Indicated for the management of variant angina (Prinzmetal''s angina).[L6298]
