(5391, 'Gaviscone peppermint stand 24 sachets * 2', 'جافيسكون نعناع ستاند 24 كيس * 2', '', '288', 'Sodium alginate+sodium bicarbonate', 'Reckitt benckiser healthcare > united partners company', 'Sachet', 'أكياس', '', 'Antacid', '', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 871, '2022-12-05', CURRENT_TIMESTAMP),
(17695, 'Dipenacid 500/500mg vial for i.m./i.v. inj.', 'داي بيناسيد 500/500مجم فيال', '', '7', 'Ampicillin+dicloxacillin', 'Cid', 'Inj', 'حقن', '', 'Penicillins.penicillin with b-lactamase inhibitor', '500mg', 'the mechanism of synergistic activity of a combination of ampicillin and dicloxacillin was studied on beta-lactamase-producing citrobacter freundii gn346 and its derived beta-lactamaseless mutant gn346/16. the synergistic activity was exhibited against th', '6221043010977', '', 755, '2022-12-04', CURRENT_TIMESTAMP),
(19623, 'Gatyxel 0.3% ophthalmic soln. 5 ml', 'جاتيكسيل 0.3% قطرة عين 5 مل', '18', '18', 'Gatifloxacin', 'Orchidia pharmaceutical industries', 'Sol', 'محلول', '', 'Antibiotic.quinolone', '0.3%', 'For the treatment of bronchitis, sinusitis, community-acquired pneumonia, and skin infections (abscesses, wounds) caused by S. pneumoniae, H. influenzae, S. aureus, M. pneumoniae, C. pneumoniae, L. pneumophila, S. pyogenes', '6224000219413', '', 1512, '2024-05-27', CURRENT_TIMESTAMP),
(30089, 'Agera whitening cream 50 gm', 'اجيرا كريم تفتيح 50 جم', '275', '339', '', 'Leader cosmetics > beauty & beyond international', 'Cream', 'كريم', '', 'Skin care.whitening', '50 gm', '', '', '', 962, '2025-08-15', CURRENT_TIMESTAMP),
(3359, 'Declophen emulgel 1% 30 gm', 'ديكلوفين ايملجل 30 جم', '18', '29', 'Diclofenac sodium', 'Pharco', 'Gel', 'جل', '', 'Nsaid.acetic acid derivatives', '1%', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6221151002642', '', 1573, '2024-11-13', CURRENT_TIMESTAMP),
(2892, 'Coldact 16 caps.', 'كولداكت 16 كبسولة', '', '6', 'Caffeine+chlorpheniramine+paracetamol(acetaminophen)+phenylpropanolamine', 'Memphis', 'Cap', 'كبسولة', '', 'Cold & flu drugs', '', '', '6221050050300', '', 1469, '2022-09-09', CURRENT_TIMESTAMP),
(429, 'Alphafen 100mg/5ml susp. 120 ml', 'الفافين 100مجم/5مل معلق 120 مل', '', '8', 'Ibuprofen', 'Marcyrl co. > alfacure pharmaceuticals', 'Susp', 'معلق', '', 'Nsaid.propionic acid derivatives', '100mg', 'Ibuprofen is the most commonly used and prescribed NSAID. It is a very common over-the-counter medication widely used as an analgesic, anti-inflammatory and antipyretic.[A39096]
The use of ibuprofen and its enantiomer [DB09213] in a racemic mix is common for the management of mild to moderate pain related to dysmenorrhea, headache, migraine, postoperative dental pain, spondylitis, osteoarthritis, rheumatoid arthritis, and soft tissue disorder.[A39097]
Due to its activity against prostaglandin and thromboxane synthesis, ibuprofen has been attributed to alteration of platelet function and prolongation of gestation and labour.[A39092]
As ibuprofen is a widely used medication, the main therapeutic indications are:
* Patent Ductus Arteriosus - it is a neonatal condition wherein the ductus arteriosus (blood vessel that connects the main pulmonary artery to the proximal descending aorta) fails to close after birth causing severe risk of heart failure. The prostaglandin inhibition of ibuprofen has been studied for the treatment of this condition as it is known that prostaglandin E2 is responsible for keeping the ductus arteriosus open.[A39100]
* Rheumatoid- and osteo-arthritis - ibuprofen is very commonly used in the symptomatic treatment of inflammatory, musculoskeletal and rheumatic disorders.[A39176]
* Cystic fibrosis - the use of high dosages of ibuprofen has been proven to decrease inflammation and decreasing polymorphonuclear cell influx in the lungs.[A39177]
* Orthostatic hypotension - ibuprofen can induce sodium retention and antagonize the effect of diuretics which has been reported to be beneficial for patients with severe orthostatic hypotension.[A1651]
* Dental pain - ibuprofen is used to manage acute and chronic orofacial pain.[A10901]
* Pain - ibuprofen is widely used to reduce minor aches and pains as well as to reduce fever and manage dysmenorrhea. It is very commonly used for the relief of acute indications such as fever and tension headaches.[A39092] It is also used to manage mild to moderate pain and moderate to severe pain as an adjunct to opioid analgesics.[L40208]
* Investigational uses - efforts have been put into developing ibuprofen for the prophylaxis of Alzheimer''s disease, Parkinson disease, and breast cancer.[A39092]', '', '', 1262, '2022-10-12', CURRENT_TIMESTAMP),
(18698, 'Exelon 4.5mg 14 caps.', 'اكسيلون 4.5 مجم 14 كبسولة', '', '105', 'Rivastigmine', 'Novartis', 'Cap', 'كبسولة', '', 'Anticholinesterase', '4.5mg', 'For the treatment of mild to moderate dementia associated with Parkinson''s disease or of the Alzheimer''s type.', '', '', 767, '2022-07-30', CURRENT_TIMESTAMP),
(4015, 'Trypsin 30 tabs', 'تريبسين 30 قرص', '150', '180', 'Trypsin', 'Primex pharma', 'Tab', 'أقراص', '', 'Anti-inflammatory', '', '', '', '', 1630, '2025-08-13', CURRENT_TIMESTAMP),
(22897, 'Moist-1 cream 100 gm', 'مويست-1 كريم 100 جم', '149', '180', '', 'Leader cosmetics > purex health care', 'Cream', 'كريم', 'مرطب وملطف للجلد', 'Moisturizing topicals', '100 gm', 'indications *dry atopic skin (chronic atopic dermatitis). *dry not atopic skin. - winter dryness - chronic hand eczema - xerosis - chronic napkin eczema *over drying treatment. - with acne treatment - after laser& peeling *associate with - some disases. -', '6224008843122', '', 3806, '2025-03-09', CURRENT_TIMESTAMP),
(22424, 'Mebo 0.25% herbal and natural oint. 15 gm', 'ميبو مرهم للحروق 15 جرام', '73.5', '109', 'Beta-sitosterol', 'Julphar', 'Oint', 'مرهم', 'لعلاج الحروق ولتسريع التئام الجلد والجروح', 'Healing topical', '0.25%', 'topical ointment made from natural ingredients including sesame oil beeswax and other edible herbs which provide beta-sitosterol 18 natural amino acids 4 essential fatty acids vitamin e and polysaccharides. indications burn wounds first degree superficial', '6291100083367', '', 5760, '2024-07-07', CURRENT_TIMESTAMP),
(13183, 'Contrahistadin 20mg 30 tabs.', 'كونتراهيستادين 20مجم 30 قرص', '82.5', '120', 'Bilastine', 'Global advanced pharmaceuticals (gap)', 'Tab', 'أقراص', '', 'Anti-histamine.second-generation', '20mg', 'For symptomatic relief of nasal and non-nasal symptoms of seasonal rhinitis in patients 12 years of age and older and for symptomatic relief in chronic spontaneous urticaria in patients 18 years of age and older [FDA Label].', '6223005941527', '', 1367, '2024-12-04', CURRENT_TIMESTAMP),
(16466, 'Clavucin 156 mg/5 ml 60ml susp.', 'كلافوسين 156 مجم / 5 مل معلق 60 مل', '', '14', 'Amoxicillin+clavulanic acid', 'T3a pharma', 'Susp', 'معلق', '', 'Penicillins.penicillin with b-lactamase inhibitor', '156 mg', '', '', '', 951, '2022-07-15', CURRENT_TIMESTAMP),
(11780, 'Aaa', 'ششش', '', '75', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 651, '2022-08-15', CURRENT_TIMESTAMP),
(17758, 'Immunizzare 30 caps.', 'اميونيزار 30 كبسولة', '450', '550', 'Epicor+vitamin c+vitamin d+zinc', 'Rx healthcare', 'Cap', 'كبسولة', '', 'Immunity booster', '', '', '', '', 1159, '2024-11-07', CURRENT_TIMESTAMP),
(28779, 'Unitrexate 5gm sol. for i.m. i.v. inj. i.v. inf.(n/a yet)', 'يونيتركسات 5جم محلول للحقن', '', '780', 'Methotrexate', 'Hikma specialized pharmaceuticals', 'Inj', 'حقن', '', 'Antineoplastic', '5gm', 'Methotrexate oral solution is indicated for pediatric acute lymphoblastic leukemia and pediatric polyarticular juvenile idiopathic arthritis.[L7144] Methotrexate injections for subcutaneous use are indicated for severe active rheumatoid arthritis, polyarticular juvenile idiopathic arthritis and severe, recalcitrant, disabling psoriasis.[L7147,L7150,L10457] It has also been approved by the EMA for the treatment of adult patients requiring systemic therapy for moderate-to-severe plaque psoriasis.[L48796]
Other formulations are indicated to treat gestational choriocarcinoma, chorioadenoma destruens, hydatiform mole, breast cancer, epidermoid cancer of the head and neck, advanced mycosis fungoides, lung cancer, and advanced non-Hodgkin''s lymphoma.[L7180] It is also used in the maintenance of acute lymphocytic leukemia.[L7180] Methotrexate is also given before treatment with leucovorin to prolong relapse-free survival following surgical removal of a tumour in non-metastatic osteosarcoma.[L7180]', '', '', 1284, '2022-07-21', CURRENT_TIMESTAMP),
(7764, 'Nochel 60 f.c. tabs.', 'نوتشيل 60 قرص', '100', '300', '', 'Company', 'Tab', 'أقراص', '', 'Dietary supplement.support joints health', '', '', '', '', 1514, '2024-09-28', CURRENT_TIMESTAMP),
(22110, 'Lumiere hair oil 100ml', 'لومير زيت للشعر 100مل', '', '50', 'Panthenol+aloe vera+chamomile+thyme+ethyl alcohol+salicylic acid', 'Egpi', 'Hair oil', 'زيت شعر', '', 'Hair care', '100ml', 'special formula that nourishes and fortifies hair roots', '', '', 905, '2022-07-31', CURRENT_TIMESTAMP),
(21408, 'Khamera 60 tabs.', 'خميرة اقراص 60 قرص', '51', '60', 'Yeast', 'Mepaco > dr. khairy company for export', 'Tab', 'أقراص', 'فيتامينات متعددة ب12', 'Multivitamins', '', '', '6223002212545', '', 6052, '2025-11-24', CURRENT_TIMESTAMP),
(18472, 'Epizin 50mg vial for i.v. inf.', 'ابيزين 50 مجم فيال وريد', '', '300', 'Epirubicin', 'Korea united pharma > eimc', 'Vial', 'فيال', '', 'Antineoplastic', '50mg', 'For use as a component of adjuvant therapy in patients with evidence of axillary node tumor involvement following resection of primary breast cancer.', '', '', 743, '2022-07-27', CURRENT_TIMESTAMP),
(16237, 'Chirocaine 2.5 mg/ml 10 amp.', 'شيروكائين 2.5 مجم / مل 10 امبول', '', '224', 'Levobupivacaine', 'Abbvie ltd. > multipharma', 'Amp', 'أمبول', '', 'Local anaesthetic', '2.5 mg', 'For the production of local or regional anesthesia for surgery and obstetrics, and for post-operative pain management', '', '', 631, '2022-08-03', CURRENT_TIMESTAMP),
(25378, 'Pross hair lotion 250 ml', 'بروس هير لوشن للشعر 250 مل', '210', '260', 'Saw palmetto+caffeine+ginkgo+ginseng+royal jelly+aloe+rosemary+chamomil+clove+jojoba+lavender+panthe', 'Hi-care > roventis pharma', 'Lotion', 'لوشن', 'لوشن مغذى ومرطب للشعر يمنع التساقط والهيشان والتقصف', 'Hair care', '250 ml', '**indications ï-treatment of hair loss. ï- effective and innovative natural treatment of androgenetic alopecia. ï-maintains healthy hair growth and density. ï-damaged brittle and fragile hair. ï-split ends. ï- weak hair growth rates. ** directions for use', '6224007611272', '', 2021, '2025-03-03', CURRENT_TIMESTAMP),
(7961, 'Astroheam 10 capsules', 'استروهيم 10 كبسولة', '125', '150', 'LACTOFERRIN 200 MG + IRON 20 MG + VIT C 100 MG + FOLIC ACID 200 MCG + VIT B12 1 MCG', 'Ed pharma', 'Capsule', 'كبسولة', '', 'Dietary supplement', '', '', '', '', 2647, '2024-11-30', CURRENT_TIMESTAMP),
(24666, 'Pennel 30 caps.', 'بينيل 30 كبسولة', '', '45', 'Biphenyl dimethyl dicarboxylate+garlic oil', 'Pharmaking-korea > united pharma international-egypt', 'Cap', 'كبسولة', 'مكمل عذائى لدعم وظائف الكبد', 'Liver support supplements', '', 'biphenyl dimethyl dicarboxylate (ddb) is a hepatoprotectant which is used as an adjuvant agent in a treatment for chronic hepatitis.', '', '', 2482, '2022-06-26', CURRENT_TIMESTAMP),
(3689, 'Dilatrol 6.25mg 30 tab.', 'ديلاترول 6.25مجم 30 قرص', '31.5', '48', 'Carvedilol', 'Chemipharm', 'Tab', 'أقراص', '', 'Antihypertensive.beta blocker.unselective', '6.25mg', 'Carvedilol is indicated to treat mild to severe heart failure, left ventricular dysfunction after myocardial infarction with ventricular ejection fraction ≤40%, or hypertension.[L7889,L7892]', '6222006502331', '', 2465, '2025-01-18', CURRENT_TIMESTAMP),
(17437, 'Dexawest 30 mg 14 caps', 'ديكساويست 30مجم 14 كبسولة', '44', '66', 'Dexlansoprazole', 'Western pharmaceuticals industries', 'Cap', 'كبسولة', 'علاج قرحة المعدة مثبط لمخض البروتونات علاج اعراض ارتجاع المريء وعلاج الهيلكوباكتر بيلوري', 'Peptic ulcer.proton pump inhibitor', '30 mg', 'Dexlansoprazole is a proton pump inhibitor (PPI) indicated for the: 
- Healing of all grades of erosive esophagitis (EE) for up to eight weeks in patients 12 years of age and older.[L48827]
- Maintenance of healed EE and relief of heartburn for up to six months in adults and 16 weeks in patients 12 to 17 years of age.[L48827, L48847]
- Treatment of heartburn associated with symptomatic non-erosive gastroesophageal reflux disease (GERD) for four weeks in patients 12 years of age and older.[L48827, L48847]', '', '', 4803, '2025-02-03', CURRENT_TIMESTAMP),
(31746, 'Specovan whey protein 10 sachets 20gm', 'سبيكوفان بروتين 10 أكياس 20 جم', '', '168', 'Whey protein+colostrum+vitamin c+vitamin d+iron+oat fibers', 'Medcare > xaintylia pharmaceuticals', 'Sachet', 'أكياس', 'مكمل غذائى غنى بالحديد والبروتين لحسين بناء العضلات والعظام وتحسين الجهاز العصبى والمناعى', 'Fortified whey protein colostrum and multivitamins', '20gm', 'fortified whey protein formula and colostrum for healthy weight gain and fighting malnutrition in adults and children starting from the age of one year old.', '', '', 1834, '2023-07-02', CURRENT_TIMESTAMP),
(15326, 'Aaa', 'ششش', '', '27', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 692, '2022-06-27', CURRENT_TIMESTAMP),
(22839, 'Mirtadepine 30 mg 10 tab.', 'ميرتاديبين 30مجم 10 قرص', '', '37', 'Mirtazapine', 'Alfacure pharmaceuticals', 'Tab', 'أقراص', '', 'Psychiatric.antidepressants', '30 mg', 'This drug is indicated for the treatment of major depressive disorder and its associated symptoms.[FDA label]
Mirtazapine has been used off-label for a variety of conditions including panic disorder, generalized anxiety disorder, dysthymia, tension headaches, hot flushes, post-traumatic stress disorder (PTSD), sleep disorders, substance abuse disorders, and sexual disorders, among others.[A177811,A177946]', '', '', 1125, '2022-07-07', CURRENT_TIMESTAMP),
(25052, 'Polytar 1% liquid 150 ml', 'بولي تار 1% 150 مل', '', '11', 'Polytar', 'Global napi pharmaceuticals > steifel laboratories u.k ltd', 'Unknown', 'غير محدد', 'علاج ضد القشرة.', 'Anti-dandruff', '1%', '', '625435121481', '', 1332, '2023-01-19', CURRENT_TIMESTAMP),
(22347, 'Mash sun block 95 spf lotion 125ml', 'ماش صن بلوك 95 معامل حماية ضد اشعة الشمس لوشن 125 مل', '235', '250', 'Sun protection formula', 'Mash premiere', 'Lotion', 'لوشن', '', 'Sun block', '125ml', 'direction of use: apply freely in all parts of skin which will be exposed to the sun before the exposure by about 20 minutes. re-apply frequently if nesessary.', '6222001407419', '', 1068, '2024-10-13', CURRENT_TIMESTAMP),
(28997, 'Varex gel 75 gm', 'فاريكس جل 75جم', '', '27', 'Clove oil+menthol+thyme oil+eucalyptus oil+propylene glycol+triclosan', 'Egyptian company for cosmetics > cura sanata pharmaceuticals', 'Gel', 'جل', '', 'Massage', '75 gm', 'Clove oil is primarily indicated in conditions like colic, flatulence, and toothache [L2849].', '', '', 577, '2022-07-15', CURRENT_TIMESTAMP),
(7535, 'Loraz 50/12.5 mg 14 tablets', 'لوراز 50/12.5مجم 14 قرص', '24', '36', 'Hydrochlorothiazide+losartan', 'EGPI', 'Tablet', 'أقراص', 'علاج ضغط الدم المرتفع', 'Antihypertensive', '12.5 mg', '', '6223003930431', '', 4618, '2024-10-30', CURRENT_TIMESTAMP),
(5589, 'Dethrea d 10 ml', 'ديثري دي نقط فم 10 مل', '', '40', 'Vitamin d3', 'Vigor med pharama', 'Unknown', 'غير محدد', '', 'Multivitamin contains d3', '10 ml', 'For the treatment of vitamin A deficiency.', '', '', 783, '2025-06-30', CURRENT_TIMESTAMP),
(23766, 'Nova t cu380 ag i.u.d', 'نوفا تي 380 لولب', '', '308', 'Copper', 'Bayer schering > bayer healthcare', 'Unknown', 'غير محدد', '', 'Iud', '', 'For use in the supplementation of total parenteral nutrition and in contraception with intrauterine devices [FDA Label] [L801].', '', '', 2569, '2022-07-09', CURRENT_TIMESTAMP),
