- for the treatment of primary immunodeficiency in adult and pediatric patients[L39920, L39930, L39935, L39940, L39945, L39950, L39955, L39960, L39965, L39975, L39980, L40029, L40034, L40044]
- in combination with [hyaluronidase (human recombinant)] for the treatment of primary immunodeficiency in patients ≥2 years of age.[L42760]
### Immune Thrombocytopenic Purpura (ITP)
- for the treatment of acute or chronic immune thrombocytopenic purpura in adult and pediatric patients[L39940, L39950, L39960, L39965, L39970, L39975, L39980]
### Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)
- for the treatment of CIDP in adult patients[L39955, L39965, L39975, L39980, L40034]
- in combination with hyaluronidase (human recombinant) as a maintenance therapy in adults with chronic inflammatory demyelinating polyneuropathy (CIDP)[L40039]
### Multifocal Motor Neuropathy (MMN)
- for maintenance therapy to improve muscle strength and disability in adult patients with MMN[L39955]
### Prophylaxis of Bacterial Infection
- for the prevention of bacterial infections in patients with hypogammaglobulinemia and/or B-cell chronic lymphocytic leukemia[L39960]
### Coronary Artery Aneurysm Associated With Kawasaki Syndrome
- for the prevention of coronary artery aneurysms in pediatric patients with Kawasaki syndrome[L39960]
### Dermatomyositis
- for the treatment of dermatomyositis in adult patients[L39970]', '', '', 4314, '2023-02-19', CURRENT_TIMESTAMP),
(11752, 'Aaa', 'ششش', '', '160', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 479, '2022-08-17', CURRENT_TIMESTAMP),
(19710, 'Gentacure cream 15 gm', 'جنتاكيور كريم 15 جم', '', '9', 'Betamethasone+gentamicin', 'Debeiky > phoenix for advanced products', 'Cream', 'كريم', '', 'Antibiotic with glucocorticoid', '15 gm', 'uses: this medication contains an antibiotic which helps prevent or treat an infection and a steroid which reduces inflammation. it is used in the treatment of various eye (ophthalmic) or ear (otic) conditions. how to use: for best results this medication', '', '', 1154, '2022-07-13', CURRENT_TIMESTAMP),
(3037, 'Coprimasept 400/80 mg 20 tab.', 'كوبريماسبت 20قرص', '', '8', 'Trimethoprim - sulphamethoxazole', 'Pharcopharma', 'Tab', 'أقراص', 'مضاد حيوي', 'Antibiotic', '80 mg', 'As a monotherapy, trimethoprim is indicated for the treatment of acute episodes of uncomplicated urinary tract infections caused by susceptible bacteria, including _E. coli._, _K. pneumoniae_, _Enterobacter spp._, _P. mirabilis_, and coagulase-negative _Staphylococcus_ species.[L11893,L11890] In various formulations in combination with [sulfamethoxazole], trimethoprim is indicated for the following infections caused by bacteria with documented susceptibility: urinary tract infections, acute otitis media in pediatric patients (when clinically indicated), acute exacerbations of chronic bronchitis in adults, enteritis caused by susceptible _Shigella_, prophylaxis and treatment of _Pneumocystis jiroveci_ pneumonia, and travelers'' diarrhea caused by enterotoxigenic _E. coli_.[L11830,L11863]
Trimethoprim is available as an ophthalmic solution in combination with [polymyxin B] for the treatment of acute bacterial conjunctivitis, blepharitis, and blepharoconjunctivitis caused by susceptible bacteria.[L11887]', '', '', 990, '2022-04-14', CURRENT_TIMESTAMP),
(31512, 'Tress follicle booster lotion 60 ml', 'تريس فوليكل بوستر لوسيون 60 مل', '220', '235', '', 'Macro group pharmaceuticals', 'Lotion', 'لوشن', '', 'Hair care', '60 ml', '', '6224007384725', '', 1089, '2025-03-04', CURRENT_TIMESTAMP),
(18086, 'Aaa', 'ششش', '', '2', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 703, '2022-10-10', CURRENT_TIMESTAMP),
(20635, 'Hyperium 1 mg 20 tab.', 'هايبريوم 1 مجم 20 قرص', '', '32', 'Rilmenidine dihydrogen phosphate', 'Servier', 'Tab', 'أقراص', 'علاج فرْطُ ضغْطِ الدمّ', '', '1 mg', '', '', '', 1110, '2022-07-29', CURRENT_TIMESTAMP),
(27169, 'Sodium chloride 0.9% & dextrose 5% (fipco) i.v. inf. 500 ml', 'صوديوم كلوريد 0.9% ديكستروز 5% فيبكو محلول وريدي 500 مل', '10.5', '11', 'Glucose (dextrose)+sodium chloride', 'El-fath for the industry of medicine & cosmetics', 'Unknown', 'غير محدد', '', 'Sterile solution', '0.9%', '', '', '', 960, '2023-12-23', CURRENT_TIMESTAMP),
(25630, 'Rajo hair shampoo 250 ml', 'راجو شامبو 250مل', '', '60', 'Keratin+silicon+amla+aloe vera+panthenol+tea tree oil', 'El-helou perfumes & cosmetics > biox pharma', 'Amp', 'أمبول', '', 'Hair care', '250 ml', '', '', '', 431, '2022-08-05', CURRENT_TIMESTAMP),
(1492, 'Springrosa 30 caps', 'سبرينجروزا 30 كبسولة', '', '360', 'Evening primrose oil 1300 mg+linoleic acid 130 mg', 'Delta grand', 'Cap', 'كبسولة', '', 'Treatment of menstrual and menopause symptoms', '', 'Evening primrose oil is used as part of over-the-counter dietary supplements.[L1113]
It is also used for the treatment of systemic inflammatory diseases and for women''s health conditions such as cyclical mastalgia. These indications do not have sufficient evidence of their effectiveness. It was used for the treatment of atopic dermatitis in the United Kingdom but it is currently withdrawn due to lack of evidence of effectiveness.[A33131]', '', '', 1072, '2023-06-20', CURRENT_TIMESTAMP),
(19370, 'Fostinocort topical cream 20 gm', 'فوستينوكورت كريم موضعي 20 جم', '29', '43', 'Betamethasone+fucidic acid', 'Zad', 'Cream', 'كريم', '', 'Antibiotic with glucocorticoid', '20 gm', 'description betamethasone is a type of medicine called a topical corticosteroid. corticosteroids are medicines used for reducing inflammation. skin inflammation in eczema occurs due to the irritation of the skin and is caused by the release of various sub', '6224001588013', '', 3485, '2024-07-01', CURRENT_TIMESTAMP),
(20510, 'Zolo baby 4000 i.u./ml 15 ml drops', 'زولو بيبي 4000 وحدة دولية نقط فم 15 مل', '35', '49', 'Cholecalciferol', 'Zolox', 'Drops', 'نقط', 'دعم صحه العظام للاطفال والكبار ويعزز صحه جهاز المناعه وتحسين الرؤيه وتطوير الجهاز العصبي', 'Vitamin d', '15 ml', 'Cholecalciferol use is indicated for the treatment of specific medical conditions like refractory rickets (or vitamin D resistant rickets), hypoparathyroidism, and familial hypophosphatemia [F4027, F4042].
Concurrently, as one of the most commonly utilized forms of vitamin D, cholecalciferol is also very frequently used as a supplement in individuals to maintain sufficient vitamin d levels in the body or to treat vitamin D deficiency, as well as various medical conditions that can be associated directly or indirectly with vitamin d insufficiency like osteoporosis and chronic kidney disease, among others [A176041, A176044, F4051].', '6224002903013', '', 2948, '2025-11-16', CURRENT_TIMESTAMP),
(5100, 'Vizimpro 30 mg 30 tabs.', 'فيزيمبرو 30 مجم 30 قرص', '', '30,750', 'Dacomitinib', 'Pfizer', 'Tab', 'أقراص', '', 'Antineoplastic - 2nd generation egfr tyrosine kinase inhibitor', '30 mg', 'Dacomitinib is indicated as the first-line treatment of patients with metastatic non-small cell lung cancer (NSCLC) with epidermal growth factor receptor (EGFR) exon 19 deletion or exon 21 L858R substitution mutations as verified by an FDA-approved test.[L4812]
Lung cancer is the leading cause of cancer death and NSCLC accounts for 85% of lung cancer cases. From the cases of NSCLC, approximately 75% of the patients present a late diagnosis with metastatic and advanced disease which produces a survival rate of 5%. The presence of a mutation in EGFR accounts for more than the 60% of the NSCLC cases and the overexpression of EGFR is associated with frequent lymph node metastasis and poor chemosensitivity.[A40018, A19201]', '', '', 843, '2025-06-23', CURRENT_TIMESTAMP),
(19160, 'Aaa', 'ششش', '', '45', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 752, '2022-07-10', CURRENT_TIMESTAMP),
(1345, 'Daky sensitive whitening cream 50 gm', 'داكي للبشرة الحساسة كريم تفتيح 50 جم', '199', '250', 'Licorice+stearic acid+vitamin c+kojic acid+marine collagen+titanium dioxide+castor oil+melon extract+papaya extract+alpha arbutin+retinyl palmitate+caviar extract', 'Medinza pharm', 'Cream', 'كريم', '', 'Skin care.whitening', '50 gm', '', '', '', 1139, '2025-07-13', CURRENT_TIMESTAMP),
(1198, 'Azelast 0.05% eye drops 5 ml', 'ازيلاست 0.05% قطرة 5 مل', '', '15', 'Azelastine', 'Kahira > epci', 'Drops', 'نقط', 'مضاد للحساسية', 'Antihistamine', '0.05%', 'Intranasal azelastine is indicated for the symptomatic treatment of seasonal allergic rhinitis in patients 5 years and older and for the symptomatic treatment of vasomotor rhinitis in patients 12 years and older.[L8240] Ophthalmic azelastine solution is indicated for the treatment of itchy eyes associated with allergic conjunctivitis.[L8270]
As a 0.15% nasal spray, azelastine hydrochloride is also indicated for over-the-counter treatment of allergies in patients aged six years and older.[L34640]', '', '', 1809, '2022-05-27', CURRENT_TIMESTAMP),
(26181, 'Rostevo deep moisture shea 50 gm cream', 'روستيفو ترطيب عميق بزبدة الشيا كريم 50 جم', '', '110', 'Shea butter', 'Larose pharma', 'Cream', 'كريم', '', 'Moisturizers', '50 gm', '', '', '', 813, '2022-08-02', CURRENT_TIMESTAMP),
(20755, 'Impacta massage cream 50 gm', 'ايمباكتا كريم مساج 50 جم', '', '45', 'Menthol crystals+eucalyptus oil+camphor oil+avocado oil+clove extract+caffeine', 'Hi-care > fameco healthcare', 'Cream', 'كريم', 'كريم مساج مثالي لتخفيف الالآم العضلات والروماتيزم يخفف الآلام العرضية مثل آلام الظهر والعضلات والالتواء وآلام التهاب المفاصل وتحفيز الدورة الدموية استرخاء الصلابة', 'Analgesic', '50 gm', '', '', '', 510, '2022-08-05', CURRENT_TIMESTAMP),
(32269, 'Aaa', 'ششش', '', '925', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 614, '2023-04-23', CURRENT_TIMESTAMP),
(6177, 'Maven 3 cal 30 h.g. caps.', 'مافين 3 كال 30 كبسولة', '', '100', 'Calcium+magnesium+vitamin c+zinc+vitamin d3', 'Smafy pharma', 'Cap', 'كبسولة', '', 'Calcium supplement', '', '', '', '', 939, '2025-07-25', CURRENT_TIMESTAMP),
(25085, 'Potassium chloride 0.2% & dextrose 5% (otsuka ateco) i.v. inf. 500 ml', 'بوتاسيوم كلوريد 0.2% و دكستروز 5% محلول للحقن الوريدي', '', '8', 'Glucose (dextrose)+potassium chloride', 'Otsuka ateco pharma', 'Unknown', 'غير محدد', '', 'Sterile solution', '0.2%', 'treatment of hypokalemia', '', '', 959, '2022-07-26', CURRENT_TIMESTAMP),
(5474, 'Copadtada 5 mg 10 tablets', 'كوبادتادا 5مجم 10 اقراص', '', '65', 'Tadalafil', 'Copad pharma', 'Tablet', 'أقراص', '', '', '5 mg', 'Tadalafil is indicated for the treatment of erectile dysfunction (ED) and either alone or in combination with [finasteride] for the treatment of benign prostatic hypertrophy (BPH).[L39095,L39439] It is also indicated for the treatment of pulmonary arterial hypertension (PAH) both alone and in combination with [macitentan] or other endothelin-1 antagonists.[L39100,L39105,L50622]', '', '', 743, '2022-12-05', CURRENT_TIMESTAMP),
(21001, 'Isoflurane-ait 100% inhaler 100 ml', 'ايزوفلوران 100% للاستنشاق 100 مل', '402', '693', 'Isoflurane', 'Arab caps > acdima international trading', 'Inhaler', 'جهاز استنشاق', '', 'General anaesthesia', '100%', 'For induction and maintenance of general anesthesia.', '', '', 1261, '2024-10-14', CURRENT_TIMESTAMP),
(7127, 'Inodep 30 caps.', 'اينوديب 30 كبسولة', '', '300', 'Myo-inositol+folic acid+alfa-lactalbumina+d-chiro-inositol', 'Globe international pharmaceuticals', 'Cap', 'كبسولة', '', 'Multivitamin', '', '', '6224008365716', '', 1662, '2025-08-27', CURRENT_TIMESTAMP),
(28235, 'Tobrabiotic 0.3% eye drops 10 ml', 'توبرابيوتك 0.3% قطرة للعين 10ملي', '', '11', 'Tobramycin', 'Sigma tec', 'Drops', 'نقط', '', 'Aminoglycoside antibiotic', '0.3%', 'Inhaled tobramycin is indicated for the management of cystic fibrosis patients with _Pseudomonas aeruginosa_, but is not recommended in patients under six years of age, those with forced expiratory volume in 1 second (FEV<sub>1</sub>) <25 or >80% predicted, or in those with _Burkholderia cepacia_.[L32739,L45364]
Tobramycin applied topically to the eyes is indicated for the treatment of external eye (and adjoining structure) infections by susceptible bacteria.[L32744] 
Tobramycin injection is indicated in adult and pediatric patients for the treatment of serious bacterial infections, including septicemia (caused by _P. aeruginosa_, _Escherichia coli_, and _Klebsiella_ spp.), lower respiratory tract infections (caused by _P. aeruginosa_, _Klebsiella_ spp., _Enterobacter_ spp., _Serratia_ spp., _E. coli_, and _Staphylococcus aureus_, both penicillinase and non-penicillinase-producing strains), serious central-nervous-system infections (meningitis, caused by susceptible organisms), intra-abdominal infections including peritonitis (caused by _E. coli_, _Klebsiella_ spp., and _Enterobacter_ spp.), skin, bone, and skin structure infections (caused by _P. aeruginosa_, _Proteus_ spp., _E. coli_, _Klebsiella_ spp., _Enterobacter_ spp., _Serratia_ spp. and _S. aureus_), and complicated and recurrent urinary tract infections (caused by _P. aeruginosa_, _Proteus_ spp., _E. coli_, _Klebsiella_ spp., _Enterobacter_ spp., _Serratia_ spp., _S. aureus_, _Providencia_ spp., and _Citrobacter_ spp.).[L32749] Aminoglycosides, including tobramycin, should generally not be used in uncomplicated urinary tract infections or staphylococcal infections unless less toxic antibiotics cannot be used and the bacteria in question are known to be sensitive to aminoglycosides.[L32749,L45359]
As with all antibiotics, tobramycin use should be limited to cases where bacterial infections are known or strongly suspected to be caused by sensitive organisms, and the possible emergence of resistance should be monitored closely.[L32739,L32744,L32749]', '6221172002645', '', 871, '2022-12-13', CURRENT_TIMESTAMP),
(10029, 'Rovac 1.5 m.i.u. 10 f.c. tab.', 'روفاك 1.5 م.وحدة 10 اقراص', '30', '54', 'Spiramycin', 'Delta pharma', 'Tab', 'أقراص', '', 'Antibiotic.macrolide', '', 'Macrolide antibiotic for treatment of various infections.', '', '', 920, '2025-08-03', CURRENT_TIMESTAMP),
(26727, 'Selenium-ace 30 tabs', 'سيلينيوم -ايه سي اي 30 قرص', '95', '130', 'Vitamin a+vitamin e+vitamin c+selenium', 'Sigma > wassen international england', 'Tab', 'أقراص', 'مكمل غذائى مضاد للاكسدة ويدعم الجهاز المناعى للجسم', 'Multivitamins', '', 'For the treatment of vitamin A deficiency.', '6225000123502', '', 17886, '2024-04-09', CURRENT_TIMESTAMP),
(31806, 'Oframax 500 mg i.m. vial(n/a yet)', 'اوفراماكس 500مجم فيال حقن عضل', '', '17', 'Ceftriaxone', 'Rameda > sun pharma egypt limited', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '500 mg', 'Ceftriaxone is used for the treatment of the infections (respiratory, skin, soft tissue, UTI, ENT) caused by susceptible organisms.[L15082] Organisms that are generally susceptible to ceftriaxone include S. pneumoniae, S. pyogenes (group A beta-hemolytic streptococci), coagulase-negative staphylococci, Some Enterobacter spp, H. influenzae, N. gonorrhoeae, P. mirabilis, E. coli, Klebsiella spp, M. catarrhalis, B. burgdorferi, and some oral anaerobes.[A215582]', '', '', 593, '2023-04-18', CURRENT_TIMESTAMP),
