In postmenopausal women, strontium ranelate can also reduce the risk of vertebral and hip fractures [L1127].', '', '', 695, '2022-07-15', CURRENT_TIMESTAMP),
(1871, 'Calcidol calcium 20 tabs.', 'كالسيدول كالسيوم 20 قرص', '79', '89', 'Calcium+vit d+magnesium+zinc', 'Nutrixia > drug pharma egypt', 'Tab', 'أقراص', '', 'Calcium supplement plus vitamin d', '', 'product uses: *osteoporosis&ostopenia *bone fractures *pregnancy &lactation *post-menopause *muscle cramps&spasms dose : one tablet perday 3 months', '6221051020036', '', 1862, '2025-05-02', CURRENT_TIMESTAMP),
(2714, 'Clavimox 228.5mg/5ml pd. for oral susp. 70ml', 'كلافيموكس 228مجم/5مل معلق 70 مل', '30.5', '47', 'Amoxicillin+clavulanic acid', 'Pharco', 'Susp', 'معلق', '', 'Penicillins.penicillin with b-lactamase inhibitor', '228.5mg', 'amoxicillin is an analog of ampicillin derived from the basic penicillin nucleus 6-aminopenicillanic acid clavulanic acid is produced by the fermentation of streptomyces clavuligerus. it is a beta-lactam structurally related to the penicillins and possess', '6221151003069', '', 2008, '2024-12-07', CURRENT_TIMESTAMP),
(11528, 'Herbalone cream', 'هيربالون كريم', '45', '55', 'Zinc oxide+olive oil', 'Arz pharma', 'Cream', 'كريم', '', '', '', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 803, '2024-04-24', CURRENT_TIMESTAMP),
(18649, 'Euronemia 100mg/5ml 5 amp for i.v. or inf.', 'يورونيميا 100مجم/5 مل 5 امبولات', '192.5', '275', 'Iron', 'Amriya > european egyptian pharm. ind.', 'Amp', 'أمبول', 'يستخد لعلاج الانيميا -- تعويض نقص مستوي الحديد', 'Anemia.iron supplement', '100mg', 'For treatment of patients with documented iron deficiency in whom oral administration is unsatisfactory or impossible. Also used to replenish body iron stores in Non-Dialysis Dependent-Chronic Kidney Disease (NDD-CKD) patients receiving or not receiving erythropoietin and in Hemodialysis Dependent (HDD-CKD) and Peritoneal Dialysis Dependent (PDD-CKD) - Chronic Kidney Disease patients receiving an erythropoietin.', '6221076030980', '', 5452, '2025-03-28', CURRENT_TIMESTAMP),
(9642, 'Parazoxanide 500 mg 18 cap', 'بارازوكسانيد 500 مجم 18 كبسولة', '', '63', 'Nitazoxanide', 'Misr > pharmacare', 'Cap', 'كبسولة', 'مضاد للديدان', 'Anthelmentic', '500 mg', 'For the treatment of diarrhea in adults and children caused by the protozoa <i>Giardia lamblia</i>,  and for the treatment of diarrhea in children caused by the protozoan,  <i>Cryptosporidium parvum</i> [FDA label].
Nitazoxanide has not been shown to be superior to placebo medication for the management of diarrhea caused by Cryptosporidium parvum in patients with HIV/immunodeficiency [FDA label, A31973, A31976].', '6224007322154', '', 1391, '2022-05-26', CURRENT_TIMESTAMP),
(17104, 'Aaa', 'ششش', '', '11', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 639, '2022-08-31', CURRENT_TIMESTAMP),
(9403, 'Osipect syrup 120 ml', 'اوسيبكت شراب 120 مل', '20', '32', 'Glyceryl guaicolate+potassium citrate+terbutaline+diphenhydramine', 'Cid', 'Syrup', 'شراب', 'مهدئ للسعال.', 'Cough drugs', '120 ml', 'cough syrup', '6221043011622', '', 3428, '2024-12-05', CURRENT_TIMESTAMP),
(32171, 'New power act 8 sachets 15 gm', 'نيو باور اكت 8 اكياس 15 جرام', '95', '150', 'Pure protein+vitamins+minerals', 'Nutrixia > medifact group', 'Sachet', 'أكياس', '', 'Dietary supplement', '15 gm', '', '', '', 989, '2023-10-22', CURRENT_TIMESTAMP),
(14459, 'Asenadia 10 mg 10 sublingual tabs.', 'اسيناديا 10 مجم 10 اقراص', '', '128', 'Asenapine', 'Western pharmaceuticals industries', 'Tab', 'أقراص', '', 'Antipsychotic', '10 mg', 'Used for treatment in psychosis, schizophrenia and schizoaffective disorders, manic disorders, and bipolar disorders as monotherapy or in combination.', '6224007308776', '', 1546, '2022-07-08', CURRENT_TIMESTAMP),
(26900, 'Shalgaten 100mg 20 caps.', 'شالجاتين 100مجم 20 كبسولة', '', '18', 'Gabapentin', 'Egpi > sea pharm for pharmaceuticals', 'Cap', 'كبسولة', 'علاج الصرع -- تقليل نوبات التشنجات -- تنظيم وظائف المخ والعضلات', 'Anti-epileptic.gaba analogs', '100mg', 'In the United States, gabapentin is officially indicated for the treatment of postherpetic neuralgia in adults and for the adjunctive treatment of partial-onset seizures, with or without secondary generalization, in patients 3 years of age and older.[L8717] In Europe, gabapentin is indicated for adjunctive therapy in the treatment of partial-onset seizures, with or without secondary generalization, in patients 6 years of age and older and as monotherapy in patients 12 years of age and older. It is also used in adults for the treatment of various types of peripheral neuropathic pain, such as painful diabetic neuropathy.[L8732]', '', '', 990, '2022-04-14', CURRENT_TIMESTAMP),
(24574, 'Aaa', 'ششش', '', '27', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 629, '2022-07-30', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(21363, 'Ketofan 100mg 5 supp.', 'كيتوفان 100مجم 5 اقماع لبوس', '', '5', 'Ketoprofen', 'Amriya', 'Supp', 'لبوس', '', 'Nsaid.propionic acid derivatives', '100mg', 'For symptomatic treatment of acute and chronic rheumatoid arthritis, osteoarthritis, ankylosing spondylitis, primary dysmenorrhea and mild to moderate pain associated with musculotendinous trauma (sprains and strains), postoperative (including dental surgery) or postpartum pain.', '6221075100097', '', 900, '2022-07-09', CURRENT_TIMESTAMP),
(9452, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 620, '2022-07-22', CURRENT_TIMESTAMP),
(25253, 'Primox 7.5 mg 14 f.c.tab.', 'بريموكس 7.5مجم 14 اقراص', '', '26', 'Moexipril', 'Mina pharm > schwarz', 'Tab', 'أقراص', '', 'Antihypertensive.ace', '7.5 mg', 'For the treatment of hypertension.', '6222003701348', '', 772, '2022-12-08', CURRENT_TIMESTAMP),
(28966, 'Vancomycin-lyomark 1000mg vial for oral or inf. use', 'فانكومايسين ليومارك 1000مجم فيال', '87.5', '226', 'Vancomycin', 'Lyomark-pharma > pharmacon', 'Vial', 'فيال', '', 'Antibiotic.tricyclic glycopeptide', '1000mg', 'Administered intravenously, vancomycin is indicated in adult and pediatric patients for the treatment of septicemia, infective endocarditis, skin and skin structure infections, bone infections, and lower respiratory tract infections.[L41529] Administered orally, vancomycin is indicated in adult and pediatric patients for the treatment of _Clostridium difficile_-associated diarrhea and for enterocolitis caused by _Staphylococcus aureus_ (including methicillin-resistant strains).[L41534]', '', '', 2879, '2024-12-15', CURRENT_TIMESTAMP),
(8666, 'Neofloxin 400mg 16 f.c. tab.', 'نيوفلوكسين 400مجم 16 قرص', '32.4', '43', 'Norfloxacin', 'Alexandria', 'Tab', 'أقراص', '', 'Antibiotic.quinolone', '400mg', 'For the treatment of urinary tract infection', '6223000170557', '', 922, '2024-08-30', CURRENT_TIMESTAMP),
(24070, 'Omepak 40mg 7caps.', 'اومنيباك 40مجم 7 كبسولة', '', '15', 'Omeprazole', 'Sedico', 'Cap', 'كبسولة', '', 'Peptic ulcer.proton pump inhibitor', '40mg', 'Omeprazole, according to the FDA label [FDA label] is a proton pump inhibitor (PPI) used for the following purposes:
• Treatment of active duodenal ulcer in adults 
• Eradication of Helicobacter pylori to reduce the risk of duodenal ulcer
recurrence in adults 
• Treatment of active benign gastric ulcer in adults 
• Reduction of risk of upper gastrointestinal (GI) bleeding in critically ill adult patients.
• Treatment of symptomatic gastroesophageal reflux disease (GERD) in
patients 1 year of age and older 
• Treatment of erosive esophagitis (EE) due to acid-mediated GERD in
patients 1 month of age and older 
• Maintenance of healing of EE due to acid-mediated GERD in patients 1
year of age and older 
• Pathologic hypersecretory conditions in adults', '', '', 1007, '2022-07-09', CURRENT_TIMESTAMP),
(29835, 'Aaa', 'ششش', '', '54', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 801, '2022-12-15', CURRENT_TIMESTAMP),
(29514, 'Vitamin k-2 (menaq7) 50 mcg 30 softgels (illegal import)', 'فيتامين ك 2 50مكجم 30 كبسول', '', '0', 'Vitamin k-2', 'Puritans pride', 'Gel', 'جل', '', 'Vitamin k', '50 mcg', 'For the treatment of vitamin A deficiency.', '', '', 1336, '2022-07-12', CURRENT_TIMESTAMP),
(21660, 'Lca depigmenting cream 40 ml', 'سي اي كريم تفتيح البشرة 40 مل', '129', '155', '', 'Lca pharma > biotech egypt', 'Cream', 'كريم', '', 'Whitening topical', '40 ml', 'depigmentation cream lca pharma: mixes pigmentation and corrects tasks this cream is a daily care which enables efficient management of pigmentation. it acts quickly and prominently on brown spots. the complexion clears up and becomes homogeneous. usage t', '', '', 665, '2023-09-05', CURRENT_TIMESTAMP),
(23902, 'Nuxe reve de miel ultra-comforting body cream 200 ml', 'نوكس ريف كريم 200مل', '', '330', '', 'Nuxe laboratory > biotech egypt', 'Cream', 'كريم', '', 'Skin care', '200 ml', 'this cocooning body moisturizer with honey and botanical oils replenishes repairs and soothes irritations and sensations of tightness in dry and sensitive skin. the body cream velvety texture is rapidly absorbed with no greasy effect and provides long-las', '', '', 755, '2022-08-03', CURRENT_TIMESTAMP),
(10649, 'Solarine 36 spf sun block lotion 50 ml', 'سولارين 18+ للحماية من الشمس 120 مل', '', '120', 'Sun protection formula', 'Weiser', 'Lotion', 'لوشن', '', 'Sun block', '50 ml', '', '', '', 753, '2022-12-08', CURRENT_TIMESTAMP),
(22355, 'Master cod liver oil 20 caps.', 'ماستير كود ليفر اويل 20 كبسولة', '', '30', 'Cod liver oil', 'Medizen pharmaceutical industries > napha', 'Cap', 'كبسولة', '', 'Cod liver oil', '', 'Cod liver oil is predominantly manufactured, marketed, and used by the population at large as a general nutraceutical dietary supplement [A27154, A33159, L2872].
Historically, cod liver oil was often given to children because the vitamin d content in the oil had been shown to prevent or treat vitamin D deficiency and condition of rickets associated with it [A33159]. Over time, this common use in children growing up may have conferred upon cod liver oil its identity as a healthy and useful all-purpose dietary supplement.
However, since cod liver oil is a composite of several other nutritional compounds including the omega-3 fatty acids eicosapentaenoic acid (EPA) and docosahexaenoic acid (DHA) as well as vitamin A and vitamin D [A33159, L2872, L2871], the presence in varying amounts of all of these compounds at once makes it difficult to recommend or use cod liver oil as an appropriate supplement to confer any one particular health effect or for any one particular nutritional deficiency.
Regardless, because it does contain a combination of a number of important and healthy nutritional compounds, cod liver oil has sometimes been recommended in the literature for conferring the health effects of some of these compounds, such as the potential use of cod liver oil supplements in post-heart attack patients for secondary prophylaxis associated with the use of omega-3 fatty acids [A33165].', '', '', 1350, '2022-10-15', CURRENT_TIMESTAMP),
(23980, 'Ofloswix 0.3% ophth.solution 5 ml', 'اوفلوسويكس 0.3% قطرة للعين 5مل', '6', '12', 'Ofloxacin', 'Chemipharm', 'Solution', 'محلول', '', 'Antibiotic.quinolone', '0.3%', 'For the treatment of infections (respiratory tract, kidney, skin, soft tissue, UTI), urethral and cervical gonorrhoea.', '6222006501594', '', 1167, '2024-05-09', CURRENT_TIMESTAMP),
(7719, 'Nervivox preg cap', 'نيرفيفوكس بريج كبسولات', '', '120', 'Methylfolate+methylcobalamine', 'K&m pharma', 'Cap', 'كبسولة', '', 'Multivitamin', '', '', '', '', 932, '2025-10-16', CURRENT_TIMESTAMP),
(25225, 'Prianil c.r. 400mg 30 controlled rel. tab.', 'بريانيل سي ار 400مجم 30 اقراص', '123', '162', 'Lithium carbonate', 'El nile.', 'Tab', 'أقراص', '', 'Psychiatric.mood stabilizers', '400mg', 'Lithium carbonate is indicated as a monotherapy for the treatment of acute manic and mixed episodes associated with bipolar 1 disorder in patients ≥7 years of age.[L1275] It is also indicated as a maintenance treatment for bipolar 1 disorder in patients ≥7 years of age.[L1275]', '6221077019519', '', 4765, '2024-12-13', CURRENT_TIMESTAMP),
(30480, 'Enhantin 400mg 30 caps.', 'انهانتين 400مجم 30 كبسولة', '73.5', '102', 'Gabapentin', 'Chemipharm', 'Cap', 'كبسولة', 'مهديء ومسكن عصبي قوي', 'Anti-epileptic.gaba analogs', '400mg', 'In the United States, gabapentin is officially indicated for the treatment of postherpetic neuralgia in adults and for the adjunctive treatment of partial-onset seizures, with or without secondary generalization, in patients 3 years of age and older.[L8717] In Europe, gabapentin is indicated for adjunctive therapy in the treatment of partial-onset seizures, with or without secondary generalization, in patients 6 years of age and older and as monotherapy in patients 12 years of age and older. It is also used in adults for the treatment of various types of peripheral neuropathic pain, such as painful diabetic neuropathy.[L8732]', '6222006503499', '', 17184, '2025-05-31', CURRENT_TIMESTAMP),
(21480, 'Konakion mm paediatric 2mg/0.2ml 5 amp. i.m./i.v./oral', 'كوناكيون اطفال 2مجم/0.2 مل 5 امبولات للحقن العضلي', '', '34', 'Vitamin k1', 'F.hoffman la roche', 'Amp', 'أمبول', 'علاج النزيف', 'Vitamin k', '2mg', 'For the treatment of vitamin A deficiency.', '7640128011903', '', 1179, '2022-12-06', CURRENT_TIMESTAMP),
(2388, 'Cerebal fort 75 mg 20 cap', 'سريبال فورت 75مجم 20 كبسولة', '', '5', 'Cinnarizine', 'Alexandria', 'Cap', 'كبسولة', 'مضاد للقئ -- يحسن تدفق الدورة الدموية', 'Antiemetic.promote cerebral blood flow.antihistamine calcium channel blocker', '75 mg', 'For the treatment of vertigo/meniere''s disease, nausea and vomiting, motion sickness and also useful for vestibular symptoms of other origins.', '', '', 1273, '2022-10-09', CURRENT_TIMESTAMP),
(31832, 'Narkleen 30 caps.', 'ناركلين 30 كبسولة', '117', '150', 'Activated coconut charcoal+coconut oil+peppermint oil', '> pivot pharmaceutical', 'Cap', 'كبسولة', 'مضاد للانتفاخ لعلاج حالات الانتفاخ وغازات البطن والشعور بالامتلاء', 'Antiflatulent', '', 'Used as a antidote to treat poisonings following excessive oral ingestion of certain medications or poisons.', '', '', 8730, '2025-10-02', CURRENT_TIMESTAMP),
(3216, 'Cyclophrine eye drops 5 ml', 'سيكلوفرين قطرة عين 5 مل', '13', '37', 'Cyclopentolate+phenylephrine', 'Kahira', 'Drops', 'نقط', 'موسعة للعين', 'Mydriatic', '5 ml', '', '6221068503393', '', 2932, '2025-01-07', CURRENT_TIMESTAMP),
(15865, 'Cardura xl 4mg 28 prolonged release tabs.', 'كاردورا اكس ال 4مجم 28 قرص ممتد المفعول', '136', '255', 'Doxazosin', 'Pfizer', 'Tab', 'أقراص', '', 'Antihypertensive.selective alpha 1 receptor blockers', '4mg', 'Doxazosin is indicated to treat the symptoms of benign prostatic hypertrophy, which may include urinary frequency, urgency, and nocturia, among other symptoms. In addition, doxazosin is indicated alone or in combination with various antihypertensive agents for the management of hypertension.[L7282] Off-label uses of doxazosin include the treatment of pediatric hypertension[A180634] and the treatment of ureteric calculi.[A180637]', '5013457011128', '', 2782, '2023-09-08', CURRENT_TIMESTAMP),
