(32860, 'Folaska 20 caps', 'فولاسكا 20 كبسولة', '79', '85', '5 methyltetrahydrofolic acid + methylcobalamin', 'Skill international pharmaceutical', 'Cap', 'كبسولة', '', 'Folate supplement', '', '', '', '', 1818, '2025-08-05', CURRENT_TIMESTAMP),
(9594, 'Marostamine adult 30 caps', 'ماروستامين للبالغين 30 كبسولة', '93', '165', '', 'Brand pharma', 'Cap', 'كبسولة', '', 'Immunity booster', '', '', '', '', 2819, '2024-06-21', CURRENT_TIMESTAMP),
(18612, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 599, '2022-11-03', CURRENT_TIMESTAMP),
(19421, 'Froben 50mg 30 tab.', 'فروبن 50 مجم 30 قرص', '', '8', 'Flurbiprofen', 'Kahira > abbott laboratories', 'Tab', 'أقراص', '', 'Nsaid.propionic acid derivatives', '50mg', 'Flurbiprofen tablets are indicated for the acute or long-term symptomatic treatment of rheumatoid arthritis, osteorarthritis and anklosing spondylitis. It may also be used to treat pain associated with dysmenorrhea and mild to moderate pain accompanied by inflammation (e.g. bursitis, tendonitis, soft tissue trauma). Topical ophthalmic formulations may be used pre-operatively to prevent intraoperative miosis.', '', '', 940, '2022-07-24', CURRENT_TIMESTAMP),
(17054, 'Dacto 100mg 10 sachets', 'داكتو 100مجم 10 اكياس', '90', '100', 'Lactoferrin+magnesium+vitamins(a+b1+b2+b6+c+d3+e)+calcium+iron+potassium+zinc', 'Pharmazad > al andalusia co.', 'Sachet', 'أكياس', '', 'Iron supplement', '100mg', '-preparation: 1 sachet into 1/2 cup of water milk or juice then stir well. -dose: 1-2 sachets recommended daily dose', '', '', 1871, '2024-08-16', CURRENT_TIMESTAMP),
(13266, 'Aaa', 'ششش', '', '10', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 733, '2022-07-18', CURRENT_TIMESTAMP),
(25935, 'Aaa', 'ششش', '', '12', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 753, '2023-01-20', CURRENT_TIMESTAMP),
(4002, 'Efanol 10 tab', 'ايفانول 10 اقراص', '', '2', 'Chlorpheniramine+ephedrine+phenobarbitone+theophylline', 'Memphis', 'Tab', 'أقراص', 'يستخدم في حالات الرشح وضيق التنفس -- يستخدم لتخفيف اعراض سعال الشعب الهوائية', 'Narcotic', '', '', '', '', 2221, '2023-01-28', CURRENT_TIMESTAMP),
(19768, 'Gigazocin 200mg/5ml pd. oral susp. 25 ml', 'جيجازوسين 200 مجم / 5 مل معلق 25 مل', '', '17', 'Azithromycin', 'T3a pharma > pioneer pharmaceutical industries', 'Susp', 'معلق', '', 'Antibiotic.macrolide', '200mg', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '', '', 783, '2022-07-25', CURRENT_TIMESTAMP),
(25163, 'Pregadurff 75 mg 20 caps.', 'بريجادورف 75مجم 20 كبسولة', '', '46', 'Pregabalin', 'Hochster pharmaceutical industries', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '75 mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 1064, '2022-12-01', CURRENT_TIMESTAMP),
(26299, 'Rosalinda oro moisturizing cream 50 gm', 'روزاليندا اورو كريم مرطب 50 جرام', '140', '160', '', 'Egyptian co. for cosmetics > orchidia pharmaceutical industries', 'Cream', 'كريم', 'كريم مرطب للجلد __ يعمل علي تنعيم الجلد __ تفتيح الجلد', 'Skin care', '50 gm', 'rosalinda oro moisturizing cream is a light textured non-greasy and easily absorbed cream for daily use. helps in skin hydration and long lasting protection against dryness. helps in soothing of dry and sensitive skin. directions for use: apply a suitable', '', '', 1659, '2025-03-09', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(26911, 'Sharkilage plus 30 caps.', 'شاركيلاج بلس 30 كبسولة', '78', '150', 'Chondroitin+glucosamine+methyl sulphonyl methane', 'Arab caps > pharmacare', 'Cap', 'كبسولة', 'علاج حالات التهاب المفاصل والغضاريف -- بناء انسجة المفاصل والغضاريف -- مضاد لالتهاب المفاصل والعظام -- مضاد للروماتيزم -- تقليل الام المفاصل والركبة -- زيادة لزوجة السائل الغضروفي -- تقليل التورم الناتج من الالتهاب.', 'Anti-rheumatic.osteoarthritis.anabolic agents', '', '', '6224007326312', '', 19533, '2024-02-25', CURRENT_TIMESTAMP),
(17157, 'Aaa', 'ششش', '', '6', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 770, '2022-09-23', CURRENT_TIMESTAMP),
(25158, 'Pregabedium 100 mg 20 h.g. caps.', 'بريجابيديوم 100مجم 20 كبسولة', '', '67', 'Pregabalin', 'Sabaa > activa therapeutics', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '100 mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 888, '2022-12-01', CURRENT_TIMESTAMP),
(1981, 'Geritol 20 piece', 'جيريتول 20 قطعة', '', '90', 'Iron+zinc+vitamin c+folic acid+b12', 'Healthy life pharma', 'Piece', 'قطعة', '', 'multivitamin', '', '', '', '', 837, '2025-01-01', CURRENT_TIMESTAMP),
(4054, 'Benmuv massage gel 120 gm', 'بنموف مساج جل 120 جم', '', '170', '', 'Acino', 'Gel', 'جل', '', 'Massage', '120 gm', '', '6225000666924', '', 3030, '2025-06-06', CURRENT_TIMESTAMP),
(21042, 'Isosweet 50 sachets 1 gm', 'ايزوسويت 50 كيس 1 جم', '', '50', 'Isomalt+sucralose', 'Mpi', 'Sachet', 'أكياس', '', 'Sweetener', '1 gm', '', '', '', 887, '2022-07-27', CURRENT_TIMESTAMP),
(18518, 'Erectawest 100 mg 3 tabs.', 'اريكتاويست 100مجم 3 قرص', '', '20', 'Avanafil', 'Western pharmaceuticals industries', 'Tab', 'أقراص', '', 'Tonic for men', '100 mg', 'Avanafil is indicated for the treatment of erectile dysfunction.[L32058]', '', '', 944, '2022-09-02', CURRENT_TIMESTAMP),
(27942, 'Mb-raravio 30 film coated tablets', 'ام بي رارافيو 30 قرص', '', '70', 'Zinc+selenium+vitamin e+vitamin a+vitamin c+vitamin b6', 'Mb pharma', 'Tablet', 'أقراص', '', 'Anti-oxident', '', '', '', '', 897, '2022-12-09', CURRENT_TIMESTAMP),
(25531, 'Queenlept 25 mg 30 caps.', 'كوينليبت 25مجم 30 كبسول', '', '63', 'Pregabalin', 'Future pharmaceutical industries (fpi) > aspin pharmaceutical', 'Cap', 'كبسولة', '', 'Anti-epileptic.gaba analogs', '25 mg', 'Pregabalin is indicated for the management of neuropathic pain associated with diabetic peripheral neuropathy, postherpetic neuralgia, fibromyalgia, neuropathic pain associated with spinal cord injury, and as adjunctive therapy for the treatment of partial-onset seizures in patients 1 month of age and older.[L7066]', '', '', 718, '2022-07-13', CURRENT_TIMESTAMP),
(28068, 'Terodine 1mg 10 scored tab.', 'تيرودين 1مجم 10 اقراص', '', '10', 'Toleterodine tartrate', 'Pharopharma', 'Tab', 'أقراص', '', 'Urinary incontinence.antispasmodics.muscarinic antagonists', '1mg', 'about tolterodine tartarate anticholinergic ( antimuscarinic) treat urinary incontinence. mechanism of action of tolterodine tartarate tolterodine tartrate is a specific muscarinic receptor (m3 receptor) antagonist. it blocks muscarinic receptors which ca', '6221094067418', '', 755, '2022-07-16', CURRENT_TIMESTAMP),
(11441, 'Aaa', 'ششش', '', '5', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 729, '2022-05-16', CURRENT_TIMESTAMP),
(20600, 'Hydro z cream 25 gm', 'هيدرو زد كريم 25 جم', '', '20', 'Sun flower oil+olive oil+avocado oil+panthenol+glycerol+aloe vera extract+calendula extract+arachis', 'Hi-care > top.z pharma', 'Cream', 'كريم', '', 'Moisturizing topicals', '25 gm', 'emollient and moisturizing cream', '', '', 1555, '2023-01-16', CURRENT_TIMESTAMP),
(19983, 'Glycodal-m 480mg/5ml susp. 100 ml', 'جليكودال-ام 480مجم/5مل معلق 100 مل', '', '6', 'Magaldrate', 'Alexandria', 'Susp', 'معلق', '', 'Antacid', '480mg', 'about magaldrate chemical complex of aluminum and magnesium hydroxides antacid. mechanism of action of magaldrate this neutralizes the gastric acid and increases the gastric ph. this reduces the direct acid irritant effect. it also enhances mucosal barrie', '6223000175699', '', 928, '2023-04-28', CURRENT_TIMESTAMP),
(22305, 'Markolive cream 50 gm', 'ماركوليف كريم 50 جم', '39', '99', 'Micronized zinc oxide+panthenol+olive oil+vitamins(d+e+b5+a)+cucumis sativus+cod liver oil+green tea+chamomile+aloe vera+jojoba oil+shea butter+calendula', 'Egyptian co. for cosmetics > meroza pharma', 'Cream', 'كريم', 'كريم ترطيب وتلطيف الجلد -- لعلاج التشقق الجلدي -- اعطاء للجلد رائحة زكية', 'Soothing cream', '50 gm', 'markolive cream used for : 1-diaper rash. 2-insect bites. 3-skin wounds & burns. 4-itching. 5-urticaria. 6-dermatitis.', '', '', 1451, '2025-01-28', CURRENT_TIMESTAMP),
(24970, 'Pixaspire 2.5 mg 30 f.c. tabs', 'بيكساسبير 2.5مجم 30 قرص', '', '269', 'Apixaban', 'Al rowad pharmaceutical industrial co.', 'Tab', 'أقراص', 'مضاد للتجلط -- مذيب للجلطات', 'Anticoagulant', '2.5 mg', 'Apixaban is indicated for reducing the risk of stroke and systemic embolism in patients who have nonvalvular atrial fibrillation, prophylaxis of deep vein thrombosis(DVT) leading to pulmonary embolism(PE) in patients after a hip or knee replacement surgery, and treatment of DVT and PE to reduce the risk of recurrence[Label,A177565,A6897].', '6224000866723', '', 2967, '2022-08-09', CURRENT_TIMESTAMP),
(621, 'Amostigmine 15 mg 20 tab', 'اموستجمين اقراص 20 قرص', '', '8', 'Neostigmine', 'Amoun', 'Tab', 'أقراص', '', 'Parasympathomimetic', '15 mg', 'Neostigmine is used for the symptomatic treatment of myasthenia gravis by improving muscle tone.', '6221025013699', '', 1088, '2022-12-01', CURRENT_TIMESTAMP),
(22041, 'Lorine 5mg/5ml syrup 100ml', 'لورين 5 مجم / 5 مل شراب 100 مل', '16.8', '19', 'Loratadine', 'Spimaco > eimc', 'Syrup', 'شراب', '', 'Antihistamine.antiallergy', '5mg', 'Loratadine is a 2nd generation antihistamine and is used to manage symptoms of allergic rhinitis, wheal formation, urticaria, and other allergic dermatologic conditions.[A176435][A176438][L8486]', '6281086010624', '', 769, '2025-06-25', CURRENT_TIMESTAMP),
(16176, 'Cerumenex n 0.9074gm/10ml ear drops', 'سيرومينكس ن 0.9074 جم / 10 مل قطرة للاذن', '', '7', 'Oleyl polypeptide', 'Pharco > mundipharma', 'Drops', 'نقط', '', 'Ear wax remover', '0.9074gm', 'this medication is used to treat earwax buildup. it helps to soften loosen and remove the earwax. too much earwax can block the ear canal and reduce hearing. this medication is for use only in the ear. apply this medication into the ear usually twice dail', '6223000011706', '', 804, '2022-12-03', CURRENT_TIMESTAMP),
(7666, 'Antafrex syrup 120 ml', 'انتافريكس شراب 120 مل', '', '60', 'Ivy leaf extract', 'Three med pharma', 'Syrup', 'شراب', '', 'Anti cough', '120 ml', '', '', '', 823, '2025-10-13', CURRENT_TIMESTAMP),
(2966, 'Cona-adione 10mg 30 chewable tab.', 'كوناديون 10مجم 30 قرص مضغ', '36', '54', 'Vitamin k1', 'Arab caps > acdima international trading', 'Tab', 'أقراص', 'فيتامين ك لعلاج النزيف', 'Vitamin k', '10mg', 'For the treatment of vitamin A deficiency.', '6224000588175', '', 5492, '2024-07-26', CURRENT_TIMESTAMP),
(15150, 'Betaval 0.1% cream 20 gm', 'بيتافال 0.1% كريم 20 جم', '12.5', '20', 'Betamethasone', 'Arab drug company.', 'Cream', 'كريم', '', 'Glucocorticoid', '0.1%', 'As a member of the corticosteroid family, betamethasone is indicated for the treatment of several inflammatory conditions. As topical monotherapy, betamethasone is indicated to relieve pruritic and inflammatory symptoms of corticosteroid-responsive-dermatoses.[L11991,L10782,L11997] Betamethasone can be used topically in combination with a vitamin D analog such as calcipotriene to treat plaque psoriasis.[L12000] The corticosteroid is also available as an injectable suspension and can be used to manage a range of inflammatory conditions including endocrine disorders, gastrointestinal disorders, and rheumatic disorders among other conditions.[L11994]', '6221060003969', '', 1448, '2025-06-15', CURRENT_TIMESTAMP),
(23573, 'Nicotipan 750 mg 20 extended release f.c. tabs.', 'نيكوتيبان 750مجم 20 اقراص', '', '48', 'Nicotinic acid', 'Eva pharma', 'Tab', 'أقراص', '', 'Nicotinic acid', '750 mg', 'mechanism of action of nicotinic acid niacin refers to nicotinic acid as well as nicotinamide which exerts it`s action by influencing metabolic reactions. it is converted in to coenzymes ncotinamide adenine dinucleotide (nad) and its phosphate ncotinamide', '', '', 828, '2022-07-14', CURRENT_TIMESTAMP),
(24756, 'Peritoneal dialysis sol. with glucose 3.86 % w/v', 'غسيل بريتوني مع جلوكوز 3.86% محلول', '', '8', 'Sodium chloride+glucose', 'Baxter > hikma pharma', 'Sol', 'محلول', '', 'Normal saline', '3.86 %', 'For the treatment of small uncomplicated varicose veins of the lower extremities that show simple dilation with competent valves.', '', '', 968, '2023-05-03', CURRENT_TIMESTAMP),
(10606, 'Aaa', 'ششش', '', '7', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 671, '2022-12-08', CURRENT_TIMESTAMP),
(14891, 'Vatroca vit d3 20 pieces', 'فاتروكا فيتامين د3 20 قطعة', '', '90', 'Vitamin d3+calcium', 'Libra vale', 'Piece', 'قطعة', '', 'Multivitamin', '', 'For the treatment of vitamin A deficiency.', '', '', 778, '2023-01-05', CURRENT_TIMESTAMP),
