(6323, 'Gemis cook life massage cream 75gm', 'جيميس كوك لايف مساج كريم 75 جم', '', '190', 'Menthol+camphor oil+cinnamon oil+mentha piperita+other natural soothing and analgesic ingredients', 'Gemis cook', 'Cream', 'كريم', '', 'Massage cream', '75gm', '', '', '', 776, '2025-07-29', CURRENT_TIMESTAMP),
(11276, 'Depzabid 0.5% eye drops 5 ml', 'ديبزابيد 0.5% قطرة عين 5 مل', '12', '17', 'Moxifloxacin', 'Marcyrl co.', 'Drops', 'نقط', '', 'Antibiotic.quinolone', '0.5%', 'For the treatment of sinus and lung infections such as sinusitis, pneumonia, and secondary infections in chronic bronchitis. Also for the treatment of bacterial conjunctivitis (pinkeye).', '6223003579586', '', 875, '2024-01-06', CURRENT_TIMESTAMP),
(10495, 'Aaa', 'ششش', '', '23', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 726, '2023-04-25', CURRENT_TIMESTAMP),
(21497, 'Kuvan 100 mg 30 disp. tabs. ss', 'كيوفان 100 مجم 30 قرص', '', '17,000', 'Sapropterin', 'Excella gmbh-germany > egyptian pharmaceutical trading company', 'Tab', 'أقراص', '', 'Control blood phenylalanine', '100 mg', 'For the treatment of tetrahydrobiopterin (BH4) deficiency.', '', '', 382, '2022-08-06', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(19960, 'Gluvildan 50 mg 10 tab.', 'جلوفيلدان 50 مجم 10 قرص', '', '21', 'Vildagliptin', 'Pharco', 'Tab', 'أقراص', '', 'Anti-diabetic.secretagogues.dpp-4 inhibitors', '50 mg', 'Vildagliptin is indicated in the treatment of type II diabetes mellitus in adults. As monotherapy, vildagliptin is indicated in adults inadequately controlled by diet and exercise alone and for whom metformin is inappropriate due to contraindications or intolerance.[L32803] It is also indicated as dual therapy in combination with metformin, a sulphonylurea, or a thiazolidinedione in adults patients with insufficient glycemic control despite maximal tolerated dose of monotherapy.[L32803] 
Vildagliptin is also marketed in a combination product with [metformin] for the treatment of adults with type II diabetes mellitus who inadequately respond to either monotherapy of vildagliptin or metformin. This fixed-dose formulation can be used in combination with a sulphonylurea or insulin (i.e., triple therapy) as an adjunct to diet and exercise in adults who do not achieve adequate glycemic control with monotherapy or dual therapy.[L32813]', '', '', 1183, '2022-07-14', CURRENT_TIMESTAMP),
(20047, 'Tola hair shampoo 250 ml', 'تولا شامبو للشعر 250 مل', '195', '219', 'Caffeine+argan oil+ceramide', 'Alba pharma', 'Amp', 'أمبول', '', 'Hair care', '250 ml', '', '6224010520509', '', 755, '2025-04-09', CURRENT_TIMESTAMP),
(10321, 'Strakopina 2.5 mg 30 f.c. tabs.', 'ستراكوبينا 2.5 مجم 30 قرص', '336', '444', 'Apixaban', 'Global napi pharmaceuticals > global advanced pharmaceutical (gap)', 'Tab', 'أقراص', '', 'Anticoagulant', '2.5 mg', 'Apixaban is indicated for reducing the risk of stroke and systemic embolism in patients who have nonvalvular atrial fibrillation, prophylaxis of deep vein thrombosis(DVT) leading to pulmonary embolism(PE) in patients after a hip or knee replacement surgery, and treatment of DVT and PE to reduce the risk of recurrence[Label,A177565,A6897].', '6223005940155', '', 1294, '2024-07-20', CURRENT_TIMESTAMP),
(1541, 'Biodroxil 500mg/5ml susp. 60ml', 'بيودروكسيل 500 مجم معلق 60مل', '', '15', 'Cefadroxil', 'Kahira > novartis', 'Susp', 'معلق', '', 'Antibiotic.cephalosporin.first-generation', '500mg', 'For the treatment of the following infections (skin, UTI, ENT) caused by; <i>S. pneumoniae, H. influenzae, staphylococci, S. pyogenes</i> (group A beta-hemolytic streptococci), <i>E. coli, P. mirabilis, Klebsiella</i> sp, coagulase-negative staphylococci and <i>Streptococcus pyogenes</i>', '6223002640904', '', 904, '2022-12-03', CURRENT_TIMESTAMP),
(17816, 'Hoffcarti 20 f.c. tabs.', 'هوفكارتي 20 قرص', '', '80', 'Glucosamine+chondroitin+potassium', 'Hoffmann pharm', 'Tab', 'أقراص', '', 'Anti-rheumatic.osteoarthritis.anabolic agents', '', '', '', '', 782, '2024-09-07', CURRENT_TIMESTAMP),
(7363, 'Beliposys 20 caps', 'بيليبوسيس 20 كبسولة', '', '190', 'Alpha lipoic acid , benfotiamine( potent vit b1), vitamin b2, vitamin b6, vitamin b9( folate), vitamin b12 ,vitamin d3 ,vitamin c', 'Ep pharma', 'Cap', 'كبسولة', '', '', '', '', '', '', 1043, '2025-09-10', CURRENT_TIMESTAMP),
(28578, 'Trospikan sr 60mg 7 f.c. tabs.', 'تروسبيكان اس ار 60مجم 7 اقراص', '', '34', 'Trospium chloride', 'Hikma pharma', 'Tab', 'أقراص', '', 'Urge incontinence', '60mg', 'Trospium is indicated for the treatment of overactive bladder with symptoms of urge urinary incontinence, urgency, and urinary frequency.[L36823] It is also indicated in combination with [xanomeline] for the treatment of adult patients with schizophrenia.[L51629]', '', '', 872, '2022-07-29', CURRENT_TIMESTAMP),
(16001, 'Cefazone 2gm vial', 'سيفازون 2جم فيال', '', '28', 'Cefoperazone', 'Pharco b', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '2gm', 'Indicated for the treatment of following infections caused by susceptible bacteria:[label]
1) Respiratory tract infections caused by _S. pneumoniae_, _H. influenzae_, _S. aureus_ (penicillinase and non-penicillinase producing strains), _S. pyogenes_ (Group A beta-hemolytic streptococci), _P. aeruginosa_, _Klebsiella pneumoniae_, _E. coli_, _Proteus mirabilis_, and Enterobacter species.
2) Peritonitis and other intra-abdominal infections caused by _E. coli_, _P. aeruginosa_, and anaerobic gram-negative bacilli (including _Bacteroides fragilis_).
3) Bacterial septicemia caused by _S. pneumoniae_, _S. agalactiae_, _S. aureus_, _Pseudomonas aeruginosa_, _E. coli_, _Klebsiella_ spp., _Klebsiella pneumoniae_, Proteus species (indole-positive and indole-negative), _Clostridium_ spp. and anaerobic gram-positive cocci.
4) Infections of the skin and skin structures caused by S. aureus (penicillinase and non-penicillinase producing strains), S. pyogenes, and P. aeruginosa.
5) Pelvic Inflammatory Disease, Endometritis, and Other Infections of the Female Genital Tract caused by N. gonorrhoeae, S. epidermidis, S. agalactiae, E. coli, Clostridium spp., Bacteroides species (including Bacteroides fragilis), and anaerobic gram-positive cocci.
6) Urinary tract infections caused by Escherichia coli and Pseudomonas aeruginosa.
7) Enterococcal Infections. Although cefoperazone has been shown to be clinically effective in the treatment of infections caused by enterococci in cases of peritonitis and other intra-abdominal infections, infections of the skin and skin structures, pelvic inflammatory disease, endometritis and other infections of the female genital tract, and urinary tract infections, the majority of clinical isolates of enterococci tested are not susceptible to cefoperazone but fall just at or in the intermediate zone of susceptibility, and are moderately resistant to cefoperazone. However, _in vitro_ susceptibility testing may not correlate directly with _in vivo_ results. Despite this, cefoperazone therapy has resulted in clinical cures of enterococcal infections, chiefly in polymicrobial infections. Cefoperazone should be used in enterococcal infections with care and at doses that achieve satisfactory serum levels of cefoperazone.', '', '', 883, '2022-08-25', CURRENT_TIMESTAMP),
(2237, 'Hero vi d3 - 2800 i.u./ml oral drops 15 ml', 'هيرو في د3 نقط فم 15 مل', '', '32', 'Cholecalciferol(vitamin d3)', 'Hero mea trading', 'Drops', 'نقط', '', 'Vitamin d', '15 ml', '', '6221024996436', '', 1314, '2022-09-21', CURRENT_TIMESTAMP),
(6216, 'Linajenta plus 25/5 mg 30 f.c. tabs.', 'ليناجنتا بلس 25/5مجم 30 قرص', '', '350', 'Empagliflozin+linagliptin', 'Global napi pharmaceuticals', 'Tab', 'أقراص', '', 'Anti - diabetic.combined ( sglt2 ) inhibitor with ( dpp - 4 ) inhibitor', '5 mg', '', '', '', 951, '2025-07-25', CURRENT_TIMESTAMP),
(13565, 'Afinitor 10 mg 30 tabs.', 'افينيتور 10مجم 30 قرص', '24500', '32,564', 'Everolimus', 'Novartis', 'Tab', 'أقراص', '', 'Immunosuppressants', '10 mg', 'Everolimus is indicated for the treatment of postmenopausal women with advanced hormone receptor-positive, HER2-negative breast cancer (advanced HR+ BC) in combination with exemestane, after failure of treatment with letrozole or anastrozole.
Indicated for the treatment of adult patients with progressive neuroendocrine tumors of pancreatic origin (PNET) with unresectable, locally advanced or metastatic disease.
Indicated for the treatment of adult patients with advanced renal cell carcinoma (RCC) after failure of treatment with sunitinib or sorafenib.
Indicated for the treatment of adult patients with renal angiomyolipoma and tuberous sclerosis complex (TSC), not requiring immediate surgery.
Indicated in pediatric and adult patients with tuberous sclerosis complex (TSC) for the treatment of subependymal giant cell astrocytoma (SEGA) that requires therapeutic intervention but cannot be curatively resected.', '', '', 3173, '2024-12-04', CURRENT_TIMESTAMP),
(27248, 'Soliqua 100 units+50 mcg/ml 3 prefilled pens 3 ml', 'سوليكا 100 وحدة 50مكجم/مل 3 اقلام معبأة 3 مل', '1770', '2,531', 'Insulin glargine+lixisenatide', 'Sanofi', 'Pen', 'قلم', 'لمرضى السكر', 'Anti-diabetic.long-acting', '50 mcg', 'Human insulin is indicated to improve glycemic control in adults and pediatric patients with diabetes mellitus.', '660298035735', '', 2023, '2024-11-25', CURRENT_TIMESTAMP),
(13152, 'Rayton facial cleanser 240 ml', 'رايتون منظف للوجه 240مل', '', '78', 'Aloe vera extract+thyme extract+ginseng extract', 'El-helou perfumes & cosmetics > biocatalysis', 'Cleanser', 'منظف', '', 'Skin care', '240 ml', 'Indicated for use as a topical agent to soothe sensitive skin and to relieve symptoms of various skin conditions, including contact or atopic dermatitis, eczema, dermatitis and acne urticata, first- and second-degree burns, radiation dermatitis, and sunburn.', '', '', 1082, '2022-09-22', CURRENT_TIMESTAMP),
(14689, 'Avene cleanance k cream-gel 40 ml', 'افين كلينانس كيه كريم جيل تنظيف 40 مل', '', '149', '', 'Pierre - fabre france > biotech egypt', 'Cream', 'كريم', '', 'Skin care', '40 ml', 'daily treatment helps eliminate clogged pores blackheads and blemishes to reveal a brighter clearer complexion. ï¿½ deep cleansing: ahas and bhas (alpha-hydroxy acids and beta-hydroxy acids) unclog pores and help reduce blemishes ï¿½ formulated with 6% gl', '282779042901', '', 651, '2022-06-18', CURRENT_TIMESTAMP),
(30727, 'Ivycan syrup 120ml', 'ايفيكان شراب 120 مل', '45', '55', 'Ivy leave extract+liquorice extract+thyme extract', 'Copad > elwatania', 'Syrup', 'شراب', '', 'Anti cough', '120ml', '', '6225000460713', '', 1580, '2024-03-22', CURRENT_TIMESTAMP),
(4728, 'Babyland ors 235 ml tetrspack', 'بيبيلاند او ار اس 235 مل تتراباك', '55', '63', 'Glucose+sodium+potassium+zinc', 'Youland', 'Unknown', 'غير محدد', '', 'Ors', '235 ml', '', '', '', 1048, '2025-06-23', CURRENT_TIMESTAMP),
(24906, 'Photoderm max milk (lait) spf 100 - 100ml', 'فوتوديرم ماكس ميلك 100مل', '', '389', 'Sun protection formula', 'Bioderma dermatological laboratories > biotech egypt', 'Unknown', 'غير محدد', '', 'Sun block', '100ml', 'maximum photoprotection for skin intolerant to all types of sunshine very fair skin with freckles and skin subjected to maximum sunshine (tropics high mountains ï-). ï- the maximum anti-uvb efficacy and unmatched extreme anti-uva performance of photoderm', '', '', 696, '2022-07-16', CURRENT_TIMESTAMP),
(13834, 'Alpha more 20 sachets', 'الفا مور 20 اكياس', '', '50', '', 'Alfacure pharmaceuticals', 'Sachet', 'أكياس', 'يعمل علي زيادة افراز اللبن', 'Lactagauge', '', 'it helps increasing milk secretion. use: dissolve sachet in quarter cup of water.', '6225469852227', '', 3894, '2023-02-09', CURRENT_TIMESTAMP),
(17818, 'Done anti-wrinkle cream 50 gm', 'دون كريم مضاد للتجاعيد 50 جرام', '100', '150', 'Glycerin+panthenol+dimethicone+bees wax+vitamin e', 'El-helou perfumes & cosmetics > safe life', 'Cream', 'كريم', '1- إخفاء التجاعيد وتأخير ظهورها.', 'Firming topical.anti-wrinkle', '50 gm', 'for wrinkles.', '', '', 14320, '2025-05-08', CURRENT_TIMESTAMP),
(26253, 'Rolyt topical lotion 75ml', 'روليت لوسيون موضعي 75 مل', '24.95', '45', 'Zinc oxide+olive oil+chamomile extract+panthenol+nigella sativa oil+glycerin+calendula extract+aloe', 'Egyptian company for cosmetics > pearla pharm co.', 'Lotion', 'لوشن', 'للترطيب العميق للجلد -- حالات التشقق الجلدي', 'Moisturizing topicals', '75ml', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '', '', 959, '2023-12-23', CURRENT_TIMESTAMP),
(24874, 'Phenylephrine 2.5% eye drops usp 27', 'فينيل افرين 2.5% قطرة للعين', '', '5', 'Phenylephrine', 'Misr', 'Drops', 'نقط', '', 'Mydriatic', '2.5%', 'Phenylephrine is available in various drug formulations, which have different indications. Phenylephrine injections are indicated to treat hypotension caused by shock or anesthesia.[L9416, L9410] The ophthalmic formulation is indicated to induce mydriasis [L9413, L46332] and conjunctival vasoconstriction.[A187370] The intranasal formulation is used to treat congestion, and a topical formulation is used to treat hemorrhoids.[A187370] Off-label uses include priapism and induction of local vasoconstriction.[A187370]', '', '', 1318, '2022-07-24', CURRENT_TIMESTAMP),
(16626, 'Coldatrexy 30 f.c. tabs', 'كولداتركسي 30 قرص', '39', '63', 'Chlorpheniramine+dextromethorphan+paracetamol(acetaminophen)+phenylephrine', 'Future pharmaceutical industries (fpi)', 'Tab', 'أقراص', 'نزلات البرد والانفلونزا.', 'Cold products', '', '', '6223004190995', '', 32541, '2024-10-13', CURRENT_TIMESTAMP),
(8208, 'Egytar antidandruff shampoo 200 ml', 'ايجيتار شامبو مضاد للقشرة 200 مل', '', '120', 'Salicylic acid + piroctone olamine + zinc pyrithione + keratin + caffeine + panthenol + aloe vera extract + tea tree oil + dimethicone + garlic extract + olive extract + jojoba extract + eurica extract + menthol crystals + vitamin c + vitamin e + cetrimid', 'Egy heart international pharmaceutical', 'Amp', 'أمبول', '', 'Anti dandruff shampoo', '200 ml', 'Key additive in many skin-care products for the treatment of acne, psoriasis, callouses, corns, keratosis pilaris and warts.', '', '', 1271, '2022-09-21', CURRENT_TIMESTAMP),
(23728, 'Normesar plus 20/12.5mg 10 f.c.tab.', 'نورميسار بلس 20/12.5مجم 10 اقراص', '', '14', 'Hydrochlorothiazide+olmesartan', 'Jedco int. co. for pharmaceuticals > four a pharma', 'Tab', 'أقراص', '', 'Antihypertensive. combined angiotensin blocker with diuretic', '12.5mg', 'this drug is used to treat high blood pressure (hypertension). lowering high blood pressure helps prevent strokes heart attacks and kidney problems. this product contains two medications: olmesartan and hydrochlorothiazide. olmesartan is an angiotensin re', '', '', 819, '2022-07-13', CURRENT_TIMESTAMP),
(23753, 'Nosemys nasal spray 10 ml', 'نوزيميس سبراي للانف 10 مل', '', '26', 'Fluticasone furoate', 'Sigma tec > andalous pharma', 'Spray', 'بخاخ', '', 'Bronchodilator.anti-inflammatory.glucocorticoid steroid', '10 ml', 'Fluticasone propionate is indicated as an inhaler for the treatment and management of asthma by prophylaxis[FDA Label]as well as inflammatory and pruritic dermatoses[F4355]. Fluticasone propionate nasal spray is indicated for managing allergic and nonallergic rhinitis[L8309,F4358].', '', '', 2142, '2022-07-01', CURRENT_TIMESTAMP),
(27909, 'Melatorest 30 caps.', 'ميلاتوريست 30 كبسولة', '120', '150', 'Melatonin+l-theanine', 'Mash premiere', 'Cap', 'كبسولة', 'يساعد على تنظيم النوم الطبيعى', 'Sleep aid', '', 'oral.solid', '', '', 2423, '2024-09-26', CURRENT_TIMESTAMP),
(6363, 'Ivytova syrup 120 ml', 'ايفيتوفا شراب 120 مل', '', '48', 'Ivy+thyme+licorice', 'Marketova pharma health care', 'Syrup', 'شراب', '', 'Herbscough', '120 ml', '', '', '', 734, '2025-07-31', CURRENT_TIMESTAMP),
(13070, 'Ramefluzole 150mg 1 caps.', 'رامفلوزول 150مجم 1كبسول', '', '9', 'Fluconazole', 'Rameda', 'Cap', 'كبسولة', '', 'Antifungals.triazoles', '150mg', 'Fluconazole can be administered in the treatment of the following fungal infections[L11043]:
 1) Vaginal yeast infections caused by Candida
 2) Systemic Candida infections
 3) Both esophageal and oropharyngeal candidiasis 
 4) Cryptococcal meningitis
 5) UTI (urinary tract infection) by Candida
