Patients receiving bone marrow transplantation who are treated with cytotoxic chemotherapy and/or radiation therapy may be predisposed to candida infections, and may receive fluconazole as prophylactic therapy.[L11043]
**A note on laboratory testing**
Obtaining specimens for fungal culture and other important laboratory studies such as serology or pathology is advised before starting fluconazole therapy in order to isolate the organisms to be eliminated through treatment. It is permissible to start therapy before the results are available, however, adjusting the therapy once laboratory results confirm the causative organism may be necessary.[L11043]', '', '', 1121, '2022-07-09', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(12917, 'Clearaderm skin cleanser 150 ml', 'كليراديرم منظف ​​البشرة 150 مل', '', '195', '', 'Hi-care > pixel pharmaceutical company', 'Cleanser', 'منظف', '', 'Skin care', '150 ml', '', '', '', 719, '2024-05-31', CURRENT_TIMESTAMP),
(29458, 'Aaa', 'ششش', '27', '44', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 723, '2024-05-21', CURRENT_TIMESTAMP),
(18062, 'Ectoin allergy kids eye drops 10 amp. x 0.5 ml', 'اكتوين قطرة عين للحساسية للاطفال 10 امبولات * 0.5 مل', '235', '275', 'Ectoin', 'Bitop ag > innomed pharm', 'Amp', 'أمبول', 'مضادة للحساسية للاطفال -- مرطب للعين للاطفال', 'Eye lubricant', '0.5 ml', '-reduces inflammation of eyes. -alleviates red itchy and watery eyes. -regenerates the irritated cinjunctiva. -suitable for use with contact lenses. -suitable for children.', '', '', 1921, '2024-03-30', CURRENT_TIMESTAMP),
(7859, 'Siagen serum 30ml', 'سياجين سيروم 30 مل', '', '340', 'Collagen+hyaluronic acid+niacinamide+vitaminc+vitamin b3', 'I pharma', 'Serum', 'سيروم', '', 'Anti aging wrinkles renew skin naturally', '30ml', '', '', '', 804, '2025-11-02', CURRENT_TIMESTAMP),
(25155, 'Prefrin liquifilm eye drops 15 ml', 'بريفرين ليكويفيلم نقط للعين 15 مل', '', '4', 'Phenylephrine+polyvinyl alcohol', 'Eipico > allergan', 'Drops', 'نقط', '', '', '15 ml', 'about phenylephrine an a1-adrenergic receptor agonist phenethylamine derivative decongestant antiglaucoma mydriatic. mechanism of action of phenylephrine the drug exerts it`s pharmacological action by acting as a selective alpha-1 adrenergic agonist. it c', '6221032330772', '', 750, '2022-12-08', CURRENT_TIMESTAMP),
(26018, 'Rheumarene 50mg 20 tab.', 'رومارين 50مجم 20 اقراص', '', '14', 'Diclofenac sodium', 'Sedico', 'Tab', 'أقراص', '', 'Nsaid.acetic acid derivatives', '50mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6221042016024', '', 1446, '2022-12-08', CURRENT_TIMESTAMP),
(28974, 'Vansept spray 60 ml', 'فانسيبت سبراي 60 مل', '42', '48', 'Ethanol+isopropyl alcohol+aloe vera ext+propylene glycol+peppermint oil+glycerin', 'Hi-care > novex', 'Spray', 'بخاخ', '', 'Antiseptic', '60 ml', 'antiseptic spray. extra care for umbilical stump. 2-4 times daily.', '769503325439', '', 844, '2025-01-27', CURRENT_TIMESTAMP),
(29777, 'Xorin 250mg vial', 'زورين 250مجم فيال', '', '11', 'Cefotaxime', 'Mup', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '250mg', 'Used to treat gonorrhoea, meningitis, and severe infections including infections of the kidney (pyelonephritis) and urinary system. Also used before an operation to prevent infection after surgery.', '6221508162012', '', 698, '2022-12-15', CURRENT_TIMESTAMP),
(20717, 'Iklen cream 50 ml', 'اكلين كريم 50 مل', '', '65', 'Liquorice extract+titanium dioxide+kojic acid+vitamin c+glycolic acid', 'El-helou perfumes & cosmetics > rexel', 'Cream', 'كريم', '', 'Whitening topical', '50 ml', 'whitening cream', '', '', 642, '2022-08-05', CURRENT_TIMESTAMP),
(8701, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 818, '2023-08-06', CURRENT_TIMESTAMP),
(664, 'Ampicillin-cid 250mg 12 caps', 'امبيسللين 250مجم 12 كبسولة', '', '7', 'Ampicillin', 'Cid', 'Cap', 'كبسولة', 'مضاد حيوي', 'Penicillins', '250mg', 'For treatment of infection (Respiratory, GI, UTI and meningitis) due to E. coli, P. mirabilis, enterococci, Shigella, S. typhosa and other Salmonella, nonpenicillinase-producing N. gononhoeae, H. influenzae, staphylococci, streptococci including streptoc', '', '', 924, '2022-10-29', CURRENT_TIMESTAMP),
(16442, 'Clariostrong 500mg s.r. 7 f.c.tab.', 'كلاريوسترونج 500 مجم 7 اقراص', '', '29', 'Clarithromycin', 'Napco', 'Tab', 'أقراص', '', 'Antibiotic.macrolide', '500mg', 'An alternative medication for the treatment of acute otitis media caused by <i>H. influenzae, M. catarrhalis, or S. pneumoniae</i> in patients with a history of type I penicillin hypersensitivity. Also for the treatment of pharyngitis and tonsillitis caused by susceptible <i>Streptococcus pyogenes</i>, as well as respiratory tract infections including acute maxillary sinusitis, acute bacterial exacerbations of chronic bronchitis, mild to moderate community-acquired pneuomia, Legionnaires'' disease, and pertussis. Other indications include treatment of uncomplicated skin or skin structure infections, helicobacter pylori infection, duodenal ulcer disease, bartonella infections, early Lyme disease, and encephalitis caused by <i>Toxoplasma gondii</i> (in HIV infected patients in conjunction with pyrimethamine). Clarithromycin may also decrease the incidence of cryptosporidiosis, prevent the occurence of α-hemolytic (viridans group) streptococcal endocarditis, as well as serve as a primary prevention for <i>Mycobacterium avium</i> complex (MAC) bacteremia or disseminated infections (in adults, adolescents, and children with advanced HIV infection).
Clarithromycin is indicated in combination with [vonoprazan] and [amoxicillin] as co-packaged triple therapy to treat _Helicobacter pylori_ (_H. pylori_) infection in adults.[L41695]', '', '', 1104, '2022-07-22', CURRENT_TIMESTAMP),
(22394, 'Maximodim 1 gm vial i.m./i.v.', 'ماكسيموديم 1جرام فيال للحقن العضلي/الوريدي', '28', '59', 'Ceftazidime', 'Otsuka > badr pharma', 'Vial', 'فيال', 'مضاد حيوي', 'Antibiotic.cephalosporin.third-generation', '1 gm', 'Ceftazidime is indicated for the treatment of lower respiratory tract infections, skin and skin structure infections, urinary tract infections, bacterial septicemia, bone and joint infections, gynecologic infections, intra-abdominal infections (including peritonitis), and central nervous system infections (including meningitis) caused by susceptible bacteria.[L32935]
Ceftazidime is indicated in combination with [avibactam] to treat infections caused by susceptible Gram-negative organisms, including complicated intra-abdominal infections (cIAI), in conjunction with [metronidazole], and complicated urinary tract infections (cUTI), including pyelonephritis, in patients aged three months and older. This combination is also indicated to treat hospital-acquired and ventilator-associated bacterial pneumonia (HABP/VABP) in patients aged 18 years and older.[L45128]
In all cases, to mitigate the risk of bacterial resistance and preserve clinical efficacy, ceftazidime should only be used for infections that are confirmed or strongly suspected to be caused by susceptible bacterial strains.[L32935, L45128]', '', '', 1288, '2024-10-18', CURRENT_TIMESTAMP),
(32230, 'Aaa', 'ششش', '', '20', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 597, '2023-04-23', CURRENT_TIMESTAMP),
(14749, 'Avertol facial wash 200 ml', 'افيرتول غسول 200 مل', '', '55', 'Lauryl glucoside+panthenol+sulphur+salicylic acid+almond oil+vit b3+licorice+carbomer+oleanolic acid', 'Egyptian company for cosmetics > global pharm', 'Facial wash', 'غسول للوجه', '', 'Skin care', '200 ml', 'for acne prone skin daily care ** use: apply morning and evening on cleansed skin.', '', '', 831, '2022-07-15', CURRENT_TIMESTAMP),
(19436, 'Fruzex 40mg 12 tab.', 'فروزكس 40 مجم 12 قرص', '', '3', 'Furosemide', 'Misr', 'Tab', 'أقراص', '', 'Diuretic.loop', '40mg', 'Furosemide is indicated for the treatment of edema associated with congestive heart failure, cirrhosis of the liver, and renal disease, including the nephrotic syndrome, in adults and pediatric patients.[L7958] 
Oral furosemide is indicated alone for the management of mild to moderate hypertension or severe hypertension in combination with other antihypertensive medications.[L9659]
Intravenous furosemide is indicated as adjunctive therapy in acute pulmonary edema when a rapid onset of diuresis is desired.[L7958]
Subcutaneous furosemide is indicated for the treatment of congestion due to fluid overload in adults with NYHA Class II/III chronic heart failure. This drug formulation is not indicated for emergency situations or in patients with acute pulmonary edema.[L43408]', '', '', 837, '2022-07-30', CURRENT_TIMESTAMP),
(17203, 'Delestra rectal oint. 30 gm', 'ديليسترا مرهم 30 جم', '', '25', 'Cinchocaine+policresulen', 'Sabaa', 'Oint', 'مرهم', '', 'Haemorrhoids', '30 gm', 'about cinchocaine an amide derivative most potent and toxic long-acting local anesthetics a local anaesthetic mechanism of action of cinchocaine cinchocaine is a local anesthetic. it works by blocking the pathway of pain signals along nerves. it inhibits', '', '', 1384, '2022-07-16', CURRENT_TIMESTAMP),
(26589, 'Scanlux 300mg i/ml (100ml) 1 vial', 'سكانلوكس 300مجم فيال', '240', '910', 'Iopamidol', 'Sanochemia pharmazeutika-austria > osteo test center', 'Vial', 'فيال', '', 'Radiographic procedures.contrast agent', '300mg', '', '', '', 907, '2025-04-14', CURRENT_TIMESTAMP),
(14770, 'Avivator 5/10 mg 21 f.c. tab.', 'افيفاتور 5/10 مجم 21 قرص', '31.5', '42', 'Amlodipine+atorvastatin', 'Marcyrl co. > ecco pharm-egypt', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statin combined with ca channel blocker', '10 mg', 'indications for atorvastatin + amlodipine this is a combination of calcium channel blocker amlodipine and hmg-coa reductase inhibitor atorvastatin. the combination generic is used to treat 1.hypertension 2.angina (that occurs with high cholesterol or trig', '', '', 751, '2025-08-07', CURRENT_TIMESTAMP),
(12995, 'Megalase syrup 125 ml', 'ميجاليز شراب 125 مل', '19.5', '31', 'Alpha amylase', 'Amoun', 'Syrup', 'شراب', 'مضاد التهاب - مضاد للتورم', 'Anti-inflammatory - anti-edematous', '125 ml', 'enzymatic preparation of anti-edematous and anti-inflammatory activity. the mode of action of alpha-amylase in inflammatory edema is characterized by: - hydrolysis with polysaccharides inflammatory exudate making it more fluid - inhibition of abnormal cap', '6221025015488', '', 14973, '2024-11-13', CURRENT_TIMESTAMP),
(30986, 'Nexibronch syrup 200 ml', 'نيكسيبرونش شراب 200 مل', '39', '65', 'Primula root fluid extract+thyme fluid extract', 'Zeta pharma', 'Syrup', 'شراب', '', 'Cough products', '200 ml', 'cough products dietary supplements', '6224008407447', '', 1660, '2024-11-12', CURRENT_TIMESTAMP),
(9485, 'Aaa', 'ششش', '', '16', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 755, '2022-12-07', CURRENT_TIMESTAMP),
(14742, 'Averothiazide 5/20/12.5mg 30 f.c. tabs', 'افيروثيازيد 5/20/12.5مجم 30 قرص', '67.5', '93', 'Amlodipine+olmesartan+hydrochlorothiazide', 'Averroes pharma-egypt', 'Tab', 'أقراص', 'لعلاج إرتفاع ضغط الدم', 'Antihypertensive.combined angiotensin blocker & ca++ channel blocker & diuretic', '12.5mg', '', '6224008179474', '', 11543, '2024-09-25', CURRENT_TIMESTAMP),
(9036, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 957, '2022-12-07', CURRENT_TIMESTAMP),
(25647, 'Ramedazolamide eye drop 5 ml', 'راميدازولاميد قطرة للعين 5مل', '82.5', '108', 'Dorzolamide+timolol', 'Rameda', 'Drop', 'نقط', '', 'Antiglaucoma', '5 ml', 'about dorzolamide carbonic anhydrase inhibitor thiophene derivative a sulfonamide antiglucoma. mechanism of action of dorzolamide dorzolamide is a sulfonamide used as topical carbonic anhydrase inhibitor. inhibition of carbonic anhydrase-2 in ciliary proc', '6223003972882', '', 1066, '2025-06-17', CURRENT_TIMESTAMP),
(21885, 'Lipinorm 40 mg 7 f.c.tab.', 'ليبينورم 40مجم 7 قرص', '', '26', 'Atorvastatin', 'Mup', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '40 mg', 'Atorvastatin is indicated for the treatment of several types of dyslipidemias, including primary hyperlipidemia and mixed dyslipidemia in adults, hypertriglyceridemia, primary dysbetalipoproteinemia, homozygous familial hypercholesterolemia, and heterozygous familial hypercholesterolemia in adolescent patients with failed dietary modifications.[A177397]
Dyslipidemia describes an elevation of plasma cholesterol, triglycerides or both as well as to the presence of low levels of high-density lipoprotein. This condition represents an increased risk for the development of atherosclerosis.[L6025] 
Atorvastatin is indicated, in combination with dietary modifications, to prevent cardiovascular events in patients with cardiac risk factors and/or abnormal lipid profiles.[A177397]
Atorvastatin can be used as a preventive agent for myocardial infarction, stroke, revascularization, and angina, in patients without coronary heart disease but with multiple risk factors and in patients with type 2 diabetes without coronary heart disease but multiple risk factors.[A177397]
Atorvastatin may be used as a preventive agent for non-fatal myocardial infarction, fatal and non-fatal stroke, revascularization procedures, hospitalization for congestive heart failure and angina in patients with coronary heart disease.[A177397]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '6221508510318', '', 1114, '2022-12-06', CURRENT_TIMESTAMP),
(25285, 'Probric 10 mg 10 tab.', 'بروبريك 10مجم 10 اقراص', '', '17', 'Bambuterol', 'Borg', 'Tab', 'أقراص', '', 'Bronchodilator.long acting beta 2 agonist', '10 mg', 'For the prevention and reversal of bronchospasm in patients 12 years of age and older with asthma and reversible bronchospasm associated with bronchitis and emphysema.', '6223002570737', '', 1029, '2022-07-27', CURRENT_TIMESTAMP),
(4274, 'Epikavit 10mg/ml 3 amp.', 'ابيكافيت 10 مجم 3 امبولات', '13.5', '36', 'Vitamin k1', 'Eipico', 'Amp', 'أمبول', '', 'Vitamin k', '10mg', 'For the treatment of vitamin A deficiency.', '6221032114983', '', 962, '2025-11-19', CURRENT_TIMESTAMP),
(20416, 'Hero baby 2 milk 400 gm', 'هيرو بيبي 2 لبن اطفال 400 جم', '261', '264', 'Milk formula stage 2', 'Hero > hero mea trading', 'Unknown', 'غير محدد', '', 'Milk products.second stage (age 6-12 months)', '400 gm', 'not to replace mother s milk. for infants from 6-12 months age. to be used within one month from opening.', '8410175060143', '', 1836, '2025-11-03', CURRENT_TIMESTAMP),
(25695, 'Normocard 7.5mg 30 tab.', 'نورموكارد 7.5مجم 30 قرص', '37.5', '54', 'Bisoprolol fumarate', 'Sigma > pharma cure pharmaceuticals', 'Tab', 'أقراص', '', 'Antihypertensive.beta blocker.selective b1', '7.5mg', 'Bisoprolol is indicated for the treatment of mild to moderate hypertension.[L7219] It may be used off-label to treat heart failure, atrial fibrillation, and angina pectoris.[A180460,A180463]', '', '', 967, '2024-08-14', CURRENT_TIMESTAMP),
(5806, 'Prombet cream 50 gm', 'برومبت كريم 50 جم', '', '70', 'Resorcinol-salicylic acid-sulfur- zinc oxid-aloevera-jojoba-calendula-bees wax-glycerin', 'Star pharm', 'Cream', 'كريم', '', 'Acne cream', '50 gm', '', '', '', 840, '2025-07-09', CURRENT_TIMESTAMP),
(15513, 'Aaa', 'ششش', '', '4', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 729, '2022-10-10', CURRENT_TIMESTAMP),
(28223, 'Tiratam 500mg 20 f.c. tablets', 'تيراتام 500مجم 20 قرص', '', '100', 'Levetiracetam', 'Sigma > andalous pharma', 'Tablet', 'أقراص', 'مضاد للتشنجات والصرع', 'Anti-epileptic.pyrrolidine', '500mg', 'Levetiracetam is indicated as an adjunctive therapy in the treatment of partial onset seizures in epileptic patients who are one month of age and older. Additionally, it is indicated as an adjunct in the treatment of myoclonic seizures in patients with juvenile myoclonic epilepsy who are 12 years of age and older, and in primary generalized tonic-clonic seizures in patients with idiopathic generalized epilepsy who are 6 years of age and older.[L8606]
Levetiracetam is also available as an orally dissolvable tablet that is indicated as an adjunct in the treatment of partial onset seizures in patients with epilepsy who are 4 years of age and older and weigh more than 20kg.[L8609]', '6223004691416', '', 1550, '2023-05-01', CURRENT_TIMESTAMP),
(18895, 'Feldene 10mg 20 caps', 'فلدين 10مجم 20 كبسولة', '', '26', 'Piroxicam', 'Pfizer', 'Cap', 'كبسولة', '', 'Nsaid.oxicam', '10mg', 'For treatment of osteoarthritis and rheumatoid arthritis.', '6221180000312', '', 1060, '2022-12-05', CURRENT_TIMESTAMP),
