(14551, 'Atomafutix 40 mg 30 caps.', 'اتومافوتيكس 40مجم 30 كبسولة', '195', '260', 'Atomoxetine', 'Future pharmaceutical industries (fpi)', 'Cap', 'كبسولة', 'علاج لفرط الحركة وتشتت الذهن.', 'Attention-deficit hyperactivity disorder', '40 mg', 'Atomoxetine is indicated for the treatment of attention deficit hyperactivity disorder (ADHD) in children and adults.', '', '', 1765, '2025-04-25', CURRENT_TIMESTAMP),
(15537, 'Brother care cream 100 gm', 'برازر كير كريم 100جم', '125', '150', 'Propolis+vitamin c+urea+glycerin', 'Brother pharma', 'Cream', 'كريم', 'مرطب وعلاج لحب الشباب الحاد وحروق الشمس.', 'Skin care.moisturizing', '100 gm', 'brother care cream is a strong moisturizer that keeps the moisture inside the skin . brother care cream has a strong healing effect on the skin. indications very strong & effective moisturizer for different skin conditions that causes skin dryness such as', '', '', 4835, '2024-07-27', CURRENT_TIMESTAMP),
(5115, 'Fortymox 0.5% eye drops 10 ml', 'فورتيموكس 0.5% قطرة عين 10 مل', '44', '62', 'Moxifloxacin', 'Orchidia pharmaceutical industries', 'Drops', 'نقط', 'قطرة مضاد حيوى واسع المدى تستخدم فى علاج التهابات العين', 'Antibiotic.quinolone', '0.5%', 'For the treatment of sinus and lung infections such as sinusitis, pneumonia, and secondary infections in chronic bronchitis. Also for the treatment of bacterial conjunctivitis (pinkeye).', '6224000219536', '', 7535, '2024-09-30', CURRENT_TIMESTAMP),
(9169, 'Aaa', 'ششش', '', '8', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 712, '2023-05-02', CURRENT_TIMESTAMP),
(6778, 'Medipha zyme 10mg 20 e.c tabs', 'ميديفا زايم 10مجم 20 قرص', '', '89', 'Serratiopeptidase', 'Medipha pharma', 'Tab', 'أقراص', '', 'Anti-inflammatory anti-edema anti-biofilm', '10mg', '', '', '', 1841, '2024-06-12', CURRENT_TIMESTAMP),
(6801, 'Kefadim 1 gm vial', 'كيفاديم 1جرام فيال', '47', '69', 'Ceftazidime', 'Epci', 'Vial', 'فيال', '', 'Antibiotic.cephalosporin.third-generation', '1 gm', 'Ceftazidime is indicated for the treatment of lower respiratory tract infections, skin and skin structure infections, urinary tract infections, bacterial septicemia, bone and joint infections, gynecologic infections, intra-abdominal infections (including peritonitis), and central nervous system infections (including meningitis) caused by susceptible bacteria.[L32935]
Ceftazidime is indicated in combination with [avibactam] to treat infections caused by susceptible Gram-negative organisms, including complicated intra-abdominal infections (cIAI), in conjunction with [metronidazole], and complicated urinary tract infections (cUTI), including pyelonephritis, in patients aged three months and older. This combination is also indicated to treat hospital-acquired and ventilator-associated bacterial pneumonia (HABP/VABP) in patients aged 18 years and older.[L45128]
In all cases, to mitigate the risk of bacterial resistance and preserve clinical efficacy, ceftazidime should only be used for infections that are confirmed or strongly suspected to be caused by susceptible bacterial strains.[L32935, L45128]', '6224007321096', '', 1525, '2024-10-21', CURRENT_TIMESTAMP),
(18288, 'Massolivia gel 50 gm', 'ماسوليفيا جل 50 جم', '', '50', 'Camphor oil+eucalyptus oil+menthol oil+panthinol+to copheryl acetate+guar gum+glycerin+xanthan gum+potassium sorbate+hudroxy propyl cellulose+betaine+tween 20+propyleneglycol+ethanol 70 %+peppermint oil+paraffinum liquidum+colve oil+thyme oil+acetylated lanolin+diazolidinval urea+bht+water', 'Olivia', 'Gel', 'جل', '', '', '50 gm', '', '', '', 803, '2024-05-22', CURRENT_TIMESTAMP),
(21995, 'Logipact hair cream 120 gm', 'لوجيباكت كريم للشعر 120 جم', '150', '190', 'Keratin+biotin+jojoba oil+aloe vera+lanolin+coconut oil+argan oil+olive oil+shea butter+panthenol+vitamin e', 'Cosmopack > impact', 'Cream', 'كريم', 'كريم للشعر لتنعيمه وترطيبه -- تقوية الشعر وتغذيته -- تقليل الهيشان و التقصف', 'Hair care', '120 gm', 'instructions: apply to wet hair style as desired may also used on dry hair.', '', '', 795, '2024-06-12', CURRENT_TIMESTAMP),
(17174, 'Maxivex 30 tab', 'ماكسيفكس 30 قرص', '85', '90', 'Fortifled with iron +folic acid +copper +zinc', 'Chemist pharma', 'Tab', 'أقراص', 'مكمل غذائى لدعم صحة الجسم وعلاج الانيميا', 'Multivitamin', '', '', '6224008825296', '', 1311, '2024-09-26', CURRENT_TIMESTAMP),
(16862, 'Aaa', 'ششش', '', '30', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 657, '2022-09-09', CURRENT_TIMESTAMP),
(3484, 'Orgalase 120ml syrup', 'اوررجالاز شراب 120 مللي', '', '45', 'Alph amylase', 'Orgenia pharma', 'Syrup', 'شراب', '', 'Anti inflammatory enzymes', '120ml', '', '', '', 989, '2025-03-30', CURRENT_TIMESTAMP),
(2361, 'Evralicare 5 mg 30 tabs.', 'ايفراليكير 5 مجم 30 قرص', '8145', '11,288', 'Everolimus', 'Eva pharma', 'Tab', 'أقراص', '', 'Immunosuppressant', '5 mg', 'Everolimus is indicated for the treatment of postmenopausal women with advanced hormone receptor-positive, HER2-negative breast cancer (advanced HR+ BC) in combination with exemestane, after failure of treatment with letrozole or anastrozole.
Indicated for the treatment of adult patients with progressive neuroendocrine tumors of pancreatic origin (PNET) with unresectable, locally advanced or metastatic disease.
Indicated for the treatment of adult patients with advanced renal cell carcinoma (RCC) after failure of treatment with sunitinib or sorafenib.
Indicated for the treatment of adult patients with renal angiomyolipoma and tuberous sclerosis complex (TSC), not requiring immediate surgery.
Indicated in pediatric and adult patients with tuberous sclerosis complex (TSC) for the treatment of subependymal giant cell astrocytoma (SEGA) that requires therapeutic intervention but cannot be curatively resected.', '', '', 2540, '2025-02-04', CURRENT_TIMESTAMP),
(9234, 'Inad-c zinc 12 sachets', 'ايناد سي زنك 12 كيس', '', '48', 'Ascorbic acid+zinc gluconate', 'Inad pharma', 'Sachet', 'أكياس', '', '', '', 'Used to treat vitamin C deficiency, scurvy, delayed wound and bone healing, urine acidification, and in general as an antioxidant. It has also been suggested to be an effective antiviral agent.', '', '', 903, '2022-07-09', CURRENT_TIMESTAMP),
(21069, 'Sonismapex 25/250 mg 30 f.c. tabs.', 'سوني سمابيكس 25250مجم 30 قرص', '94.5', '129', 'Carbidopa+levodopa', 'Apex pharma', 'Tab', 'أقراص', '', 'Parkinson s disease.dopamine agonist', '250 mg', '', '', '', 1239, '2025-05-08', CURRENT_TIMESTAMP),
(2977, 'Concor cor 2.5 mg 30 f.c. tabs', 'كونكور كور 2.5مجم 30 قرص', '40.5', '60', 'Bisoprolol fumarate', 'Amoun > merck kgaa f.r.germany', 'Tab', 'أقراص', 'علاج ارتفاع ضغط الدم', 'Antihypertensive.beta blocker.selective b1', '2.5 mg', 'Bisoprolol is indicated for the treatment of mild to moderate hypertension.[L7219] It may be used off-label to treat heart failure, atrial fibrillation, and angina pectoris.[A180460,A180463]', '6221025032331', '', 15233, '2024-07-07', CURRENT_TIMESTAMP),
(6845, 'Epirovastin 20 mg 7 f.c. tab', 'ابيروفاستين 20مجم 7 اقراص', '', '38', 'Rosuvastatin', 'Eipico', 'Tab', 'أقراص', '', 'Antihyperlipidemic.statins', '20 mg', 'The FDA monograph states that rosuvastatin is indicated as an adjunct to diet in the treatment of triglyceridemia, Primary Dysbetalipoproteinemia (Type III Hyperlipoproteinemia), and Homozygous Familial Hypercholesterolemia.[F4649]
The Health Canada monograph for rosuvastatin further specifies that rosuvastatin is indicated for the reduction of elevated total cholesterol (Total-C), LDL-C, ApoB, the Total-C/HDL-C ratio and triglycerides (TG) and for increasing HDL-C in hyperlipidemic and dyslipidemic conditions when response to diet and exercise alone has been inadequate. It is also indicated for the prevention of major cardiovascular events (including risk of myocardial infarction, nonfatal stroke, and coronary artery revascularization) in adult patients without documented history of cardiovascular or cerebrovascular events, but with at least two conventional risk factors for cardiovascular disease.[F4652]
Prescribing of statin medications is considered standard practice following any cardiovascular events and for people with a moderate to high risk of development of CVD. Statin-indicated conditions include diabetes mellitus, clinical atherosclerosis (including myocardial infarction, acute coronary syndromes, stable angina, documented coronary artery disease, stroke, trans ischemic attack (TIA), documented carotid disease, peripheral artery disease, and claudication), abdominal aortic aneurysm, chronic kidney disease, and severely elevated LDL-C levels.[A181087, A181406]', '', '', 833, '2025-08-16', CURRENT_TIMESTAMP),
(20323, 'Hemoflush 0.5% oint. 30 gm', 'هيموفلاش 0.5% مرهم 30 جم', '', '7', 'Pentosan polysulphate', 'Egpi > pharmacare', 'Oint', 'مرهم', '', 'Anti-inflammatory', '0.5%', 'For the relief of bladder pain or discomfort associated with interstitial cystitis.', '', '', 1173, '2022-07-15', CURRENT_TIMESTAMP),
(31265, 'Rovime 10 sachet', 'روفايم 10 اكياس', '110', '160', 'Lactoferrin+colostrum+ferrous fumarate+vitamin c+zinc+vitamin b complex', 'Medcare > semaf pharma', 'Sachet', 'أكياس', '', 'Multivitamin', '', 'lactoferrin 100 mg colostrum 250 mg ferrous fumerate 100 mg vit c zinc vit b complex', '6229810520254', '', 1577, '2025-08-12', CURRENT_TIMESTAMP),
(1216, 'Azrolid 200mg/5ml pd. for oral susp. 22.5ml', 'ازروليد 200 مجم /5 مل معلق 22.5 مل', '37', '52', 'Azithromycin', 'Pharco > amriya', 'Susp', 'معلق', 'مضاد حيوى واسع المدى يستخدم فى علاج العديد من الالتهابات', 'Antibiotic.macrolide', '200mg', 'Azithromycin should be used only to treat or prevent infections that are proven or strongly suspected to be caused by susceptible bacteria in order to prevent the development antimicrobial resistance and maintain the efficacy of azithromycin [FDA label].
Azithromycin is indicated for the treatment of patients with mild to moderate infections caused by susceptible strains of the microorganisms listed in the specific conditions below. Recommended dosages, duration of therapy and considerations for various patient populations may vary among these infections. Refer to the FDA label and "Indications" section of this drug entry for detailed information [FDA label]. 
**Adults**:
Acute bacterial exacerbations of chronic obstructive pulmonary disease due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Acute bacterial sinusitis due to _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.
Uncomplicated skin and skin structure infections due to _Staphylococcus aureus_, _Streptococcus pyogenes_, or _Streptococcus agalactiae_. Abscesses usually require surgical drainage.
Urethritis and cervicitis due to _Chlamydia trachomatis_ or _Neisseria gonorrhoeae_.
Genital ulcer disease in men due to _Haemophilus ducreyi_ (chancroid). Due to the small number of women included in clinical trials, the efficacy of azithromycin in the treatment of chancroid in women has not been established.
**Pediatric Patients**
Acute otitis media caused by _Haemophilus influenzae_, _Moraxella catarrhalis_ or _Streptococcus pneumoniae_
Community-acquired pneumonia due to _Chlamydophila pneumoniae_, _Haemophilus influenzae_, _Mycoplasma pneumoniae_ or _Streptococcus pneumoniae_ in patients appropriate for oral therapy.
Pharyngitis/tonsillitis caused by _Streptococcus pyogenes_ as an alternative to first-line therapy in individuals who cannot use first-line therapy.', '6221075200537', '', 1522, '2025-09-09', CURRENT_TIMESTAMP),
(15408, 'Bodium firming cream 200 ml', 'بوديوم فيرمينج كريم 200 مل', '283', '326', 'Caffeine+carnitine+vitamin e', 'Egyptian company for cosmetics > hayah lab.', 'Cream', 'كريم', '', 'Skin care', '200 ml', 'use twice daily.', '', '', 687, '2025-04-06', CURRENT_TIMESTAMP),
(17468, 'Dextrose 10% & sodium chloride 0.9% (otsuka) i.v. inf. 500 ml (rubber cap)', 'دكستروز 10% صوديوم كلوريد 0.9% اوتوسوكا محلول وريدي 500 مل غطاء مطاط', '', '11', 'Glucose (dextrose)+sodium chloride', 'Otsuka', 'Cap', 'كبسولة', '', 'Sterile solution', '10%', '', '', '', 778, '2022-07-24', CURRENT_TIMESTAMP),
(32850, 'Ferrogate 20 cap', 'فيروجات 20 كبسولة', '60', '70', 'Ferrous bisglycinate+folic acid+methylcobalamine+b6+vit c', 'K and m pharma', 'Cap', 'كبسولة', '', 'Iron supplement', '', 'Ferrous sulfate is used for the prevention and treatment of iron deficiency anemia in adults and children.[A190804,L2240,L11800]', '', '', 1690, '2024-09-29', CURRENT_TIMESTAMP),
(20918, 'Invega sustenna 75 mg / 0.75 ml i.m. prefilled syringe', 'انفيجا سوستينا 75مجم/0.75مل سرنجة معبأة للحقن العضل', '2248', '2,387', 'Paliperidone', 'Alza corporation-usa > janssen cilag', 'Syringe', 'حقنة', '', 'Psychiatric.antipsychotics', '75 mg', 'As an oral extended-release tablet and a once-monthly extended-release suspension for intramuscular injection, paliperidone is indicated for the treatment of adults and adolescents with schizophrenia and in the treatment of schizoaffective disorder in combination with antidepressants or mood stabilizers.[L16168,L37744] Paliperidone is also available in both an every-three-month and twice-yearly extended-release suspension for intramuscular injection for the treatment of schizophrenia.[L4137,L37749]', '', '', 1432, '2025-08-23', CURRENT_TIMESTAMP),
(11526, 'Top-4 cream 15 gm', 'توب-فور 15جرام كريم', '12', '19', 'Betamethasone+clioquinol+gentamicin+tolnaftate', 'Hikma pharma', 'Cream', 'كريم', '', '', '15 gm', 'dosage: a thin film of this cream should be applied to cover completely the affected area two or three times daily or as prescribed by the physician. frequency of application should be determined according to severity of the condition. duration of therapy', '6221000001215', '', 1854, '2025-02-08', CURRENT_TIMESTAMP),
(10463, 'Silverhyalo cream 100 gm', 'سيلفرهيالو كريم 100 جم', '', '104', 'Silver sulfadiazine+sodium hyaluronate', 'Debeiky > philo pharm pharmaceuticals', 'Cream', 'كريم', '', 'Topical bactericidal', '100 gm', 'Indicated as an adjunct for the prevention and treatment of wound sepsis in patients with second- and third-degree burns.', '', '', 1715, '2022-10-29', CURRENT_TIMESTAMP),
(7336, 'Kidi marcal syrup 120 ml', 'كيدي ماركال شراب 120 مل', '', '90', '', '', 'Syrup', 'شراب', '', '', '120 ml', '', '', '', 960, '2022-12-06', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(29255, 'Vichy ideal soleil self tanner 100 ml', 'فيتشي ايديال 100مل', '', '329', '', 'Vichy laboratories > united company for trading & distribution', 'Sol', 'محلول', '', 'Sun block', '100 ml', 'natural 8-hour hydrating self-tanner providing a healthy glow leaving your skin more radiant than ever. for women looking for a natural hydrating self-tanner. application apply 2-4 times a week depending on the desired result. apply evenly blending in at', '', '', 623, '2022-08-17', CURRENT_TIMESTAMP),
(14883, 'Bactrocin 2% top. oint. 10 gm', 'باكتروسين 2% مرهم 10 جم', '', '18', 'Mupirocin', 'Pharopharma', 'Oint', 'مرهم', '', 'Anti-bacterial.protein synthesis inhibitor', '2%', 'Indicated for the treatment of impetigo and secondary skin infections, leading to traumatic skin lesions, due to _Staphylococcus aureus_ and _Streptococcus pyogenes_.[L10580]', '6221094112682', '', 1189, '2022-12-03', CURRENT_TIMESTAMP),
