- Histoplasmosis, including chronic cavitary pulmonary disease and disseminated, nonmeningeal histoplasmosis, and
- Aspergillosis, pulmonary and extrapulmonary, in patients who are intolerant of or who are refractory to amphotericin B therapy
It is also indicated for the treatment of the following fungal infections in non-immunocompromised patients:[L50051]
- Onychomycosis of the toenail, with or without fingernail involvement, due to dermatophytes (tinea unguium)
- Onychomycosis of the fingernail due to dermatophytes (tinea unguium).
Itraconazole oral solution is indicated for the treatment of oropharyngeal and esophageal candidiasis.[L50061]', '', '', 1132, '2022-06-18', CURRENT_TIMESTAMP),
(12561, 'Voltaren 25mg 5 supp.', 'فولتارين لبوس 25 مجم 5 اقماع اطفال', '9', '15', 'Diclofenac sodium', 'Novartis', 'Supp', 'لبوس', 'مسكن آلام . خافض حرارة', 'Nsaid.acetic acid derivatives.analgesic.antipyretic', '25mg', 'Diclofenac is indicated for use in the treatment of pain and inflammation from varying sources including inflammatory conditions such as osteoarthritis, rheumatoid arthritis, and ankylosing spondylitis, as well as injury-related inflammation due to surgery and physical trauma. It is often used in combination with [misoprostol] as a gastro-protective agent in patients with high risk of developing NSAID-induced ulcers.', '6223002640898', '', 1680, '2024-10-07', CURRENT_TIMESTAMP),
(25331, 'Proleukin i.v. infusion', 'برولوكين', '', '650', 'Aldesleukin', 'Novartis', 'Unknown', 'غير محدد', '', 'Antineoplastic', '', 'For treatment of adults with metastatic renal cell carcinoma.', '', '', 726, '2022-07-30', CURRENT_TIMESTAMP),
(13992, 'Amofluxin 500mg vial', 'اموفلوكسين 500 مجم فيال', '', '6', 'Amoxicillin+flucloxacillin', 'Rameda', 'Vial', 'فيال', '', 'Penicillins.penicillin with b-lactamase inhibitor', '500mg', 'amoxycillin and flucloxacillin ï¿½ generally exhibit an additive effect against sensitive bacteria and bacteria that are sensitive to amoxycillin or to flucloxacillin remain sensitive to the combination showing that antagonism does not occur when the two', '', '', 1029, '2022-10-09', CURRENT_TIMESTAMP),
(14549, 'Atomafutix 10 mg 30 caps.', 'اتومافوتيكس 10مجم 30 كبسولة', '78', '108', 'Atomoxetine', 'Future pharmaceutical industries (fpi)', 'Cap', 'كبسولة', '', 'Attention-deficit hyperactivity disorder', '10 mg', 'Atomoxetine is indicated for the treatment of attention deficit hyperactivity disorder (ADHD) in children and adults.', '6223004195112', '', 1373, '2025-04-25', CURRENT_TIMESTAMP),
(27640, 'Sulpha boracyl solution 125 ml', 'سلفا بوراسيل محلول 125 مل', '', '7', 'Phenol+sulphacetamide', 'Kahira', 'Solution', 'محلول', '', 'Antiseptic', '125 ml', 'phenol is used as a caustic disinfectant fungicide and topical anesthetic. italso commonly employed as an anti-pruritic and also as a preservative for injections.', '6221068402719', '', 1064, '2022-06-24', CURRENT_TIMESTAMP),
(28208, 'Tinidol plus 10 f.c. tab.', 'تنيدول بلس 10 اقراص', '', '19', 'Norfloxacin+tinidazole', 'Hikma pharma', 'Tab', 'أقراص', '', 'Antibiotic fluoroquinolone with antiprotozoal', '', 'about norfloxacin a synthetic second generation synthetic fluoroquinolone (quinolone) broad spectrum antibiotic. mechanism of action of norfloxacin norfloxacin is a bacteriostatic at low concentration and bactericidal at high concentration. it act by inhi', '', '', 879, '2022-07-15', CURRENT_TIMESTAMP),
(5345, 'Anastronate 1 mg 28 f.c. tabs.', 'اناسترونات 1مجم 28 قرص', '240', '352', 'Anastrozole', 'Hi-pharm', 'Tab', 'أقراص', '', 'Non-steroidal aromatase-inhibitor', '1 mg', 'Anastrozole is indicated as adjunct therapy in the treatment of hormone receptor-positive early breast cancer in postmenopausal women, and as a first-line treatment for hormone receptor-positive (or hormone receptor-unknown) locally advanced or metastatic breast cancer in postmenopausal women.[L8863] It may also be used in the treatment of advanced breast cancer in postmenopausal women who experience disease progression despite treatment with [tamoxifen].[L8866,L8863]', '', '', 1004, '2025-07-15', CURRENT_TIMESTAMP),
(27437, 'Stablentin 6mg/120ml syrup', 'ستابلينتين 6مجم/120مل شراب', '', '22', 'Gabapentin', 'Mepaco', 'Tab', 'أقراص', '', 'Anti-epileptic.gaba analogs', '6mg', 'In the United States, gabapentin is officially indicated for the treatment of postherpetic neuralgia in adults and for the adjunctive treatment of partial-onset seizures, with or without secondary generalization, in patients 3 years of age and older.[L8717] In Europe, gabapentin is indicated for adjunctive therapy in the treatment of partial-onset seizures, with or without secondary generalization, in patients 6 years of age and older and as monotherapy in patients 12 years of age and older. It is also used in adults for the treatment of various types of peripheral neuropathic pain, such as painful diabetic neuropathy.[L8732]', '', '', 768, '2022-07-12', CURRENT_TIMESTAMP),
(19913, 'Glucose 10% (fipco) i.v. inf. 500 ml (rubber cap)', 'جلوكوز 10% فيبكو محلول وريدي غطاء مطاط 500 مل', '', '11', 'Glucose (dextrose)', 'Otsuka', 'Cap', 'كبسولة', '', 'Antihypoglycemic', '10%', 'dextrose 10% in water (d10w) is an hypertonic iv solution used in the treatment of ketosis of starvation and provides calories (380 kcal/l) free water and no electrolytes. it should be administered using a central line if possible and should not be infuse', '', '', 834, '2022-07-30', CURRENT_TIMESTAMP),
(32814, 'Esomeprazole-eva 40mg 20 e.c. tabs.', 'ايزوميبرازول -ايفا 40 مجم 20 قرص', '96', '116', 'Esomeprazole', 'Eva pharma', 'Tab', 'أقراص', '', 'Peptic ulcer.proton pump inhibitor', '40mg', 'Esomeprazole is indicated for the treatment of acid-reflux disorders including healing and maintenance of erosive esophagitis, and symptomatic gastroesophageal reflux disease (GERD), peptic ulcer disease, H. pylori eradication, prevention of gastrointestinal bleeds with NSAID use, and for the long-term treatment of pathological hypersecretory conditions including Zollinger-Ellison Syndrome.', '6223007355681', '', 1956, '2024-06-27', CURRENT_TIMESTAMP),
(28228, 'Titan hair lotion 120 ml', 'تيتيان هير لوشن 120 ملي', '', '60', 'Panthenol+aloe vera extract+salicylic acid+lavender oil+glycerol', 'Macro group pharmaceuticals', 'Lotion', 'لوشن', '', 'Hair care', '120 ml', '- helps in stimulating peripheral circulation in the scalp by aloin potency; therefore improves nourishment of hair follicle. - protects against dandruff by maintaining normal scalp sebum secretion with salicylic acid & lavandula extract potency. - has a', '', '', 765, '2022-08-01', CURRENT_TIMESTAMP),
(4454, 'Paclitaxel actavis 6mg/ml 150mg vial', 'باكليتاكسيل اكتافيس 6مجم/مل 150مجم فيال', '', '1,400', 'Paclitaxel', 'Multipharma', 'Vial', 'فيال', '', 'Antineoplastic', '6mg', 'Used in the treatment of Kaposi''s sarcoma and cancer of the lung, ovarian, and breast. Abraxane® is specfically indicated for the treatment of metastatic breast cancer and locally advanced or metastatic non-small cell lung cancer.', '', '', 727, '2025-06-17', CURRENT_TIMESTAMP),
(26666, 'Sector massage cream 60 gm', 'سيكتور مساج كريم 60 جرام', '35', '52', 'Peppermint oil+menthol crystals+camphor oil+eucalyptus oil+eugenol oil', 'Egyptian company for cosmetics > sector', 'Cream', 'كريم', '', 'Massage', '60 gm', 'Indicated for the over-the-counter use for:
-the symptomatic relief of minor spasms of the gastrointestinal tract, flatulence and abdominal pain, especially in patients with irritable bowel syndrome.
-the temporary relief of itching associated with insect bites, eczema, minor burn, sunburn, minor skin irritations, minor cuts, scrapes, atopic dermatitis and other skin disorders.
-the temporary symptomatic relief of mild joint and muscle pain as a local topical analgesic.
-the temporary relief of tension-type headache.', '', '', 1164, '2023-08-16', CURRENT_TIMESTAMP),
(6272, 'Monoqrest 20 film coated tablets', 'مونوكريست 20 قرص', '75', '84', 'Vitamin d3 8.325 mcg, vitamin k 7.5 mcg, and calcium 167 mg', 'Novatec', 'Tablet', 'أقراص', '', 'Support bone and joint health', '', 'For the treatment of vitamin A deficiency.', '', '', 3795, '2025-07-31', CURRENT_TIMESTAMP),
(6423, 'Imodium instant 2mg 6 orodispersible tabs.', 'ايموديوم انستانت 2مجم 6 اقراص ذائبة بالفم', '54', '80', 'Loperamide', 'Mcneil products ltd. > johnson & johnson scientific office', 'Tab', 'أقراص', 'مضاد للاسهال -- لعلاج حالات الاسهال', 'Antidiarrheal', '2mg', 'Loperamide is indicated for the relief of diarrhea, including Travelers’ Diarrhea.[L42785] As an off-label use, it is often used to manage chemotherapy-related diarrhea.[A251610]', '6222003701225', '', 7083, '2024-11-18', CURRENT_TIMESTAMP),
(6077, 'Metrogypton 500 mg 20 f.c. tabs.', 'ميتروجيبتون 500مجم 20 قرص', '', '34', 'Metronidazole', 'Gypto pharma', 'Tab', 'أقراص', '', 'Antiprotozoal.nitroimidazole', '500 mg', 'Metronidazole is indicated for the treatment of confirmed trichomoniasis caused by Trichomonas vaginalis (except for in the first trimester of pregnancy) and the patient''s sexual partners, bacterial vaginosis,[L7432, L49811] certain types of amebiasis, and various anaerobic infections.[A181057, L49811] The above anaerobic infections may occur on the skin and skin structures, the abdomen, the heart, reproductive organs, central nervous system, and the respiratory system. Some may also be present in the bloodstream in cases of septicemia. Common infections treated by metronidazole are Bacteroides species infections, Clostridium infections, and Fusobacterium infections, as well as Peptococcus and Peptostreptococcus infections.[L3754] Topical formulations of metronidazole are indicated for the treatment of inflammatory lesions of rosacea.[L45166]
It is also used off-label in the treatment of Crohn''s disease, as a prophylactic agent after surgery[A181039], and in the treatment of Helicobacter pylori infection.[A181045] It has also been studied in the prevention of preterm births and to treat periodontal disease.[A1391,A181078]', '', '', 3258, '2025-07-20', CURRENT_TIMESTAMP),
(26297, 'Rosagel 0.75% gel 20 gm', 'روزاجل 0.75% جل 20 جم', '8.25', '12', 'Metronidazole', 'Eva pharma', 'Gel', 'جل', 'مضاد للفطريات المهبلية -- يحافظ علي البيئة الداخلية للمهبل -- التخلص من الروائح الكريهة للمهبل --تقليل الحكة والالتهابات المهبلية', 'Antiprotozoal.nitroimidazole', '0.75%', 'Metronidazole is indicated for the treatment of confirmed trichomoniasis caused by Trichomonas vaginalis (except for in the first trimester of pregnancy) and the patient''s sexual partners, bacterial vaginosis,[L7432, L49811] certain types of amebiasis, and various anaerobic infections.[A181057, L49811] The above anaerobic infections may occur on the skin and skin structures, the abdomen, the heart, reproductive organs, central nervous system, and the respiratory system. Some may also be present in the bloodstream in cases of septicemia. Common infections treated by metronidazole are Bacteroides species infections, Clostridium infections, and Fusobacterium infections, as well as Peptococcus and Peptostreptococcus infections.[L3754] Topical formulations of metronidazole are indicated for the treatment of inflammatory lesions of rosacea.[L45166]
It is also used off-label in the treatment of Crohn''s disease, as a prophylactic agent after surgery[A181039], and in the treatment of Helicobacter pylori infection.[A181045] It has also been studied in the prevention of preterm births and to treat periodontal disease.[A1391,A181078]', '', '', 1315, '2024-12-13', CURRENT_TIMESTAMP),
(30082, 'Addo-g 30 hard gelatin capsules', 'ادو جي 30 كبسولة جيلاتينيه', '149', '179', 'Multivitamins 13 vitamins and 11 minerals with coq10 and lactobacillus acidophilus', 'Pharma zad > elixir pharma (george group)', 'Capsule', 'كبسولة', 'مكمل غذائي لدعم وظائف الجسم .وامداد الجسم بالطاقة', 'Multivitamins with friendly bacteria and coq10', '', 'a&d&e&k1&c&b1&b2&b3&b5&b6&b9&b12&ca&mg&mn&se&fe&zn&cu&cr&mo& biotin&iodine&boron& lactobacillus acidophilus & coq10', '', '', 2484, '2024-05-27', CURRENT_TIMESTAMP),
(2794, 'Clopixol depot 200mg/ml i.m. 10 amp.', 'كلوبيكسول متخزن 200مجم/مل عضل 10 امبول', '880', '2,150', 'Zuclopenthixol', 'H.lundbeck a/s denmark > multipharma', 'Amp', 'أمبول', '', 'Psychiatric.antipsychotics', '200mg', 'Used in the management of acute psychoses such as mania or schizophrenia. However, the use of zuclopenthixol acetate in psychiatric emergencies as an alternative to standard treatments (haloperidol, clotiapine, etc.) should be cautioned, since well executed and documented trials of zuclopenthixol acetate for this use have yet to be conducted. Zuclopenthixol acetate is not intended for long-term use.', '5702157109203', '', 5411, '2025-02-08', CURRENT_TIMESTAMP),
(25355, 'Pronuben baby ac milk 400 gm', 'برونوبين بيبي لبن 400جم', '', '195', 'Extra care milk formula', 'Pronuben s.l. > rotabiogen for pharmaceutical invest.', 'Unknown', 'غير محدد', '', 'Extra care milk', '400 gm', 'advanced care formula - from birth to 12 months calcium - iron - magnesium - 13 vitamins - 5 nucleotides - ara & dha', '', '', 807, '2022-07-16', CURRENT_TIMESTAMP),
(32225, 'Geblafol-b 30 tab', 'جيبلافول-بي 30 قرص', '60', '90', 'Methylcobalamin+folic acid+pyridoxine hcl', 'Pharma zad > health for life international pharmaceutical', 'Tab', 'أقراص', '', 'Multivitamin', '', '', '', '', 920, '2025-05-13', CURRENT_TIMESTAMP),
(15050, 'Bellyroc cream 50 gm', 'بيليروك كريم 50 جرام', '45', '49', 'Zinc oxide+chamomile extract+olive oil+panthenol+jojoba oil+aloe vera extract+wheat germ oil+avocado', 'Italian cosmetics company > amazon pharm', 'Cream', 'كريم', 'مرطب وملطف لالتهاب الجلد', 'Moisturizing topicals', '50 gm', 'Zinc can be used for the treatment and prevention of zinc deficiency/its consequences, including stunted growth and acute diarrhea in children, and slowed wound healing. It is also utilized for boosting the immune system, treating the common cold and recurrent ear infections, as well as preventing lower respiratory tract infections [L2172].', '6224002280022', '', 2275, '2024-09-26', CURRENT_TIMESTAMP),
(6379, 'Isis anise 20 filter bags', 'ايزيس ينسون 20 كيس فلتر', '', '35', 'Anise', 'Atos pharma', 'Unknown', 'غير محدد', '', 'Drinks', '', '', '', '', 782, '2022-12-05', CURRENT_TIMESTAMP),
(18899, 'Feldene 20mg 5 supp.', 'فلدين 20مجم 5 اقماع لبوس', '', '24', 'Piroxicam', 'Pfizer', 'Supp', 'لبوس', '', 'Nsaid.oxicam', '20mg', 'For treatment of osteoarthritis and rheumatoid arthritis.', '6221180000374', '', 943, '2022-12-05', CURRENT_TIMESTAMP),
(6420, 'Romance vag cleanser', 'رومانس غسول تشطيف مهبلي', '', '35', 'Glycerin +ethanol70% + alovera extract + menthol crystals', 'Sun pharm', 'Cleanser', 'منظف', '', 'Vaginal douche', '', 'It is used as a solvent, emollient, pharmaceutical agent, and sweetening agent.', '6224000422615', '', 2167, '2022-12-03', CURRENT_TIMESTAMP),
(2679, 'Citra forte 2.4 gm gran. 280 gm', 'سيترافورت 280 جم حبيبات', '167', '208', 'Potassium sodium hydrogen citrate', 'Sigma > pharma mix-egypt', 'Unknown', 'غير محدد', 'جعل البول أقل حمضية مما يساعد على التخلص من حمض اليوريك، مما يساعد على منع النقرس وأنواع معينة من حصوات الكلى', 'Nephrolithiasis.urinary alkalinizer', '2.4 gm', 'For use as an electrolyte replenisher and in the treatment of hypokalemia.', '6221051050361', '', 8078, '2024-06-15', CURRENT_TIMESTAMP),
(17510, 'Dextrose 25% (misr) i.v. inj. 20 amp.', 'دكستروز 25% مصر محلول وريدي 20 امبول', '', '8', 'Glucose (dextrose)', 'Misr', 'Inj', 'حقن', '', 'Sterile solution', '25%', 'about dextrose dextrorotatory form of monosaccharide(((glucose))) in hypoglycemia and as a sweetner. mechanism of action of dextrose dextrose is used as an intravenous (((iv))) solution used to supply water and calories to the body. it is also used as dil', '', '', 1006, '2022-07-15', CURRENT_TIMESTAMP);
INSERT INTO drugs (id, trade_name, arabic_name, old_price, price, active, company, dosage_form, dosage_form_ar, usage, category, concentration, pharmacology, barcode, unit, visits, last_price_update, updated_at) VALUES
(28977, 'Vanzadime 2 gm vial for i.v./i.m. inj.', 'فانزاديم 2جم فيال', '26.4', '53', 'Ceftazidime', 'Tabuk pharmaceutical manufacturing company', 'Inj', 'حقن', '', 'Antibiotic.cephalosporin.third-generation', '2 gm', 'Ceftazidime is indicated for the treatment of lower respiratory tract infections, skin and skin structure infections, urinary tract infections, bacterial septicemia, bone and joint infections, gynecologic infections, intra-abdominal infections (including peritonitis), and central nervous system infections (including meningitis) caused by susceptible bacteria.[L32935]
Ceftazidime is indicated in combination with [avibactam] to treat infections caused by susceptible Gram-negative organisms, including complicated intra-abdominal infections (cIAI), in conjunction with [metronidazole], and complicated urinary tract infections (cUTI), including pyelonephritis, in patients aged three months and older. This combination is also indicated to treat hospital-acquired and ventilator-associated bacterial pneumonia (HABP/VABP) in patients aged 18 years and older.[L45128]
In all cases, to mitigate the risk of bacterial resistance and preserve clinical efficacy, ceftazidime should only be used for infections that are confirmed or strongly suspected to be caused by susceptible bacterial strains.[L32935, L45128]', '', '', 830, '2024-11-17', CURRENT_TIMESTAMP),
(21243, 'Aaa', 'ششش', '', '14', '', '', 'Unknown', 'غير محدد', '', '', '', '', '', '', 685, '2022-10-24', CURRENT_TIMESTAMP),
(23086, 'Mucoswab 20 unidose oral soln.* 5 ml', 'ميكوسواب 20 وحدة منفصلة محلول بالفم 5 مل', '50', '70', 'Carbocysteine+guaifenesin+oxomemazine', 'Uniswab', 'Sol', 'محلول', 'مذيب البلغم __ يعمل علي تقليل الكحة المصحوبة بالبلغم __ علاج الأزمات التنفسية', 'Mucolytic', '5 ml', '', '6224008379119', '', 3493, '2024-08-24', CURRENT_TIMESTAMP),
(537, 'Amilo 5 mg 30 tab.', 'اميلو 5مجم 30 قرص', '42', '54', 'Amlodipine', 'Alfacure pharmaceuticals', 'Tab', 'أقراص', '', 'Antihypertensive.selective calcium channel blocker', '5 mg', 'Amlodipine may be used alone or in combination with other antihypertensive and antianginal agents for the treatment of the following conditions [FDA label]:
• Hypertension 
• Coronary artery disease
• Chronic stable angina
• Vasospastic angina (Prinzmetal’s or Variant angina) 
