# .github/workflows/build_apk.yml

name: Build Flutter APK (Direct Gradle)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      apk_path: ${{ steps.upload_artifact.outputs.artifact-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # لا يزال إعداد Flutter مطلوبًا لتبعيات Dart وأدوات أخرى قد تحتاجها الإضافات
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # أو أحدث إصدار تفضله
          channel: 'stable'
          cache: true

      - name: Display Flutter Version Used
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      # خطوات التنظيف لا تزال مهمة
      - name: Clean Workspace
        run: |
          flutter clean
          chmod +x android/gradlew
          ./gradlew clean
        working-directory: ./android

      # *** تعديل هنا: تشغيل Gradle مباشرة بدلاً من flutter build ***
      - name: Build APK with Gradle Directly
        id: build_gradle # معرف للخطوة
        run: ./gradlew assembleRelease --no-daemon # إضافة --no-daemon ممارسة جيدة في CI
        working-directory: ./android # التشغيل من داخل مجلد android

      # --- التحقق والرفع ---
      # (لا حاجة لـ continue-on-error لأن نجاح الخطوة يعتمد على Gradle مباشرة)

      - name: Verify Final APK Existence and Size
        # خطوة تحقق مفيدة بعد بناء Gradle المباشر
        run: |
          echo "Checking for final APK at standard path..."
          # المسار قد يكون مختلفًا قليلاً عند استخدام Gradle مباشرة، تحقق من المسارين
          ls -lh build/app/outputs/apk/release/app-release.apk || echo "APK not found at build/app/outputs/apk/release/app-release.apk"
          echo "----------------------------------------"
          ls -lh build/app/outputs/flutter-apk/app-release.apk || echo "APK not found at build/app/outputs/flutter-apk/app-release.apk"
          echo "----------------------------------------"

      - name: List Build Output Directory
        if: always()
        run: |
          echo "Listing contents of ./build/app/outputs/:"
          ls -R build/app/outputs/ || echo "Output directory not found or inaccessible."
        working-directory: ./android # عرض المخرجات داخل مجلد android/build

      - name: Upload APK Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-gradle
          # استخدم المسار الذي تتوقع أن ينتجه Gradle مباشرة (غالبًا هذا)
          path: android/build/app/outputs/apk/release/app-release.apk
          # أو المسار الآخر إذا أكدت التحقق أنه المسار الصحيح:
          # path: android/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
