# .github/workflows/build_apk.yml

name: Build Flutter APK (Direct Gradle)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      apk_path: ${{ steps.upload_artifact.outputs.artifact-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # أو أحدث إصدار تفضله
          channel: 'stable'
          cache: true

      - name: Display Flutter Version Used
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      # *** تعديل هنا: فصل خطوات التنظيف ***
      - name: Clean Flutter Artifacts
        run: flutter clean
        # لا يحتاج working-directory (يعمل من الجذر)

      - name: Grant Gradlew Permission
        run: chmod +x android/gradlew
        # لا يحتاج working-directory (يعمل من الجذر، والمسار صحيح)

      - name: Clean Android Gradle Project
        run: ./gradlew clean --no-daemon # تأكد من إضافة --no-daemon
        working-directory: ./android # *** تحديد مجلد العمل هنا ***

      # --- بناء Gradle المباشر ---
      - name: Build APK with Gradle Directly
        id: build_gradle
        run: ./gradlew assembleRelease --no-daemon
        working-directory: ./android

      # --- التحقق والرفع ---
      - name: Verify Final APK Existence and Size
        run: |
          echo "Checking for final APK at Gradle default path..."
          ls -lh android/build/app/outputs/apk/release/app-release.apk || echo "APK not found at android/build/app/outputs/apk/release/app-release.apk"
          echo "----------------------------------------"
          echo "Checking for final APK at Flutter default path..."
          ls -lh build/app/outputs/flutter-apk/app-release.apk || echo "APK not found at build/app/outputs/flutter-apk/app-release.apk"
          echo "----------------------------------------"
        # لا يزال يعمل من الجذر، لذا المسارات كاملة

      - name: List Build Output Directory
        if: always()
        run: |
          echo "Listing contents of ./android/build/app/outputs/:"
          ls -R ./android/build/app/outputs/ || echo "Output directory not found or inaccessible."
          echo "----------------------------------------"
          echo "Listing contents of ./build/app/outputs/:"
          ls -R ./build/app/outputs/ || echo "Flutter Output directory not found or inaccessible."
          echo "----------------------------------------"
        # يعمل من الجذر

      - name: Upload APK Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-gradle
          # المسار المتوقع من بناء Gradle المباشر
          path: android/build/app/outputs/apk/release/app-release.apk
          # تحقق من مخرجات التحقق لتأكيد المسار إذا لزم الأمر
          if-no-files-found: error
