# .github/workflows/build_apk.yml

name: Build Flutter APK (Default Paths)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      apk_path: ${{ steps.upload_artifact.outputs.artifact-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Display Flutter Version Used
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      # --- Clean Steps (فصلها لضمان الصحة) ---
      - name: Clean Flutter Artifacts
        run: flutter clean

      - name: Grant Gradlew Permission
        run: chmod +x android/gradlew

      - name: Clean Android Gradle Project
        run: ./gradlew clean --no-daemon
        working-directory: ./android

      # --- Build Step (العودة إلى flutter build apk) ---
      - name: Build APK (Allowing Flutter tool check to fail)
        id: build_flutter
        continue-on-error: true # كاحتياط أخير
        run: flutter build apk --release --verbose

      # --- Verification and Upload ---
      - name: Verify Final APK Existence and Size
        # الآن يجب أن نبحث في المسار القياسي تحت جذر المشروع
        run: |
          echo "Checking for final APK at Flutter standard path..."
          ls -lh build/app/outputs/flutter-apk/app-release.apk || echo "APK not found at build/app/outputs/flutter-apk/app-release.apk"
          echo "----------------------------------------"
          # يمكنك إلغاء التعليق عن هذا للتحقق من المسار الآخر إذا أردت
          # echo "Checking for final APK at Gradle alternative path..."
          # ls -lh build/app/outputs/apk/release/app-release.apk || echo "APK not found at build/app/outputs/apk/release/app-release.apk"
          # echo "----------------------------------------"

      - name: List Build Output Directory
        if: always()
        run: |
          # عرض المجلدات تحت جذر المشروع
          echo "Listing contents of ./build/app/outputs/:"
          ls -R ./build/app/outputs/ || echo "Output directory ./build/app/outputs/ not found or inaccessible."
          echo "----------------------------------------"
          # يمكنك عرض مجلدات أخرى إذا لزم الأمر

      - name: Upload APK Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # استخدام المسار القياسي الذي يجب أن تنتجه flutter build apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
