name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # تأكد من أن هذا المسار صحيح

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Release APK
        run: |
          chmod +x build_apk.sh
          ./build_apk.sh

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
