# .github/workflows/build_apk.yml

name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Clean Flutter build artifacts
        run: flutter clean

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        working-directory: ./

      - name: Clean Android Gradle project
        run: ./gradlew clean
        working-directory: ./android

      # استمر في استخدام --verbose مؤقتًا إذا أردت
      - name: Build APK with Verbose Output
        # ملاحظة: الآن بعد نجاح Gradle، قد لا تحتاج --verbose ولكن لن يضر
        run: flutter build apk --release --verbose

      # خطوة العرض ستظل مفيدة للتأكيد
      - name: List Build Output Directory
        if: always()
        run: |
          echo "Listing contents of build/app/outputs/:"
          ls -R build/app/outputs/ || echo "Output directory not found or inaccessible."
          echo "----------------------------------------"
          echo "Listing contents of build/app/ :"
          ls -A build/app/ || echo "Build app directory not found or inaccessible."
          echo "----------------------------------------"

      # *** تعديل هنا: تغيير مسار البحث عن APK ***
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # جرب المسار الأكثر شيوعًا لمخرجات Gradle
          path: build/app/outputs/apk/release/app-release.apk
          # إذا لم يتم العثور عليه في المسار الجديد، لا يزال يعتبر خطأ
          if-no-files-found: error
